sqlplus TEST/TEST@PLATON @00_T_ORCL_2007_Modele_badge_CTRL_Standard.sql > log_00_T_ORCL_2007_Modele_badge_CTRL_Standard.log
sqlplus TEST/TEST@PLATON @00_T_ORCL_2007_Passer_en_mode_CTRL_Standard.sql > log_00_T_ORCL_2007_Passer_en_mode_CTRL_Standard.log
