DELETE FROM TABLEREFERENCE;
COMMIT;
INSERT INTO TABLEREFERENCE (TABLEREFERENCEID, ID, VALEUR, TEXTE, TEXTE_FR, TEXTE_EN, DATECREATION, DATEMAJ) VALUES (1, 0, 1, 'Etat', 'Etat', 'Report', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO TABLEREFERENCE (TABLEREFERENCEID, ID, VALEUR, TEXTE, TEXTE_FR, TEXTE_EN, DATECREATION, DATEMAJ) VALUES (2, 0, 2, 'Nature', 'Nature', 'Status', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO TABLEREFERENCE (TABLEREFERENCEID, ID, VALEUR, TEXTE, TEXTE_FR, TEXTE_EN, DATECREATION, DATEMAJ) VALUES (3, 0, 3, 'Sécurité', 'Sécurité', 'Security', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO TABLEREFERENCE (TABLEREFERENCEID, ID, VALEUR, TEXTE, TEXTE_FR, TEXTE_EN, DATECREATION, DATEMAJ) VALUES (4, 0, 4, 'Autorisation spéciale', 'Autorisation spéciale', 'Special Authorization', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO TABLEREFERENCE (TABLEREFERENCEID, ID, VALEUR, TEXTE, TEXTE_FR, TEXTE_EN, DATECREATION, DATEMAJ) VALUES (5, 0, 5, 'Durée autorisation', 'Durée autorisation', 'Duration authorization', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO TABLEREFERENCE (TABLEREFERENCEID, ID, VALEUR, TEXTE, TEXTE_FR, TEXTE_EN, DATECREATION, DATEMAJ) VALUES (22, 0, 6, 'Civilité', 'Civilité', 'Civility', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO TABLEREFERENCE (TABLEREFERENCEID, ID, VALEUR, TEXTE, TEXTE_FR, TEXTE_EN, DATECREATION, DATEMAJ) VALUES (6, 1, 1, 'En stock', 'En stock', 'In stock', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO TABLEREFERENCE (TABLEREFERENCEID, ID, VALEUR, TEXTE, TEXTE_FR, TEXTE_EN, DATECREATION, DATEMAJ) VALUES (7, 1, 2, 'Prêtée', 'Prêtée', 'On loan', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO TABLEREFERENCE (TABLEREFERENCEID, ID, VALEUR, TEXTE, TEXTE_FR, TEXTE_EN, DATECREATION, DATEMAJ) VALUES (8, 1, 3, 'En retard', 'En retard', 'In late', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO TABLEREFERENCE (TABLEREFERENCEID, ID, VALEUR, TEXTE, TEXTE_FR, TEXTE_EN, DATECREATION, DATEMAJ) VALUES (9, 1, 4, 'Volée', 'Volée', 'Stolen', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
COMMIT;
INSERT INTO TABLEREFERENCE (TABLEREFERENCEID, ID, VALEUR, TEXTE, TEXTE_FR, TEXTE_EN, DATECREATION, DATEMAJ) VALUES (10, 1, 5, 'Egarée', 'Egarée', 'Lost', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO TABLEREFERENCE (TABLEREFERENCEID, ID, VALEUR, TEXTE, TEXTE_FR, TEXTE_EN, DATECREATION, DATEMAJ) VALUES (11, 1, 6, 'Inactive', 'Inactive', 'Inactive', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO TABLEREFERENCE (TABLEREFERENCEID, ID, VALEUR, TEXTE, TEXTE_FR, TEXTE_EN, DATECREATION, DATEMAJ) VALUES (12, 1, 7, 'Prêt spécial', 'Prêt spécial', 'Special loan', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO TABLEREFERENCE (TABLEREFERENCEID, ID, VALEUR, TEXTE, TEXTE_FR, TEXTE_EN, DATECREATION, DATEMAJ) VALUES (13, 2, 1, 'Clé', 'Clé', 'Key', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
COMMIT;
INSERT INTO TABLEREFERENCE (TABLEREFERENCEID, ID, VALEUR, TEXTE, TEXTE_FR, TEXTE_EN, DATECREATION, DATEMAJ) VALUES (14, 2, 2, 'Passe', 'Passe', 'Pass', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO TABLEREFERENCE (TABLEREFERENCEID, ID, VALEUR, TEXTE, TEXTE_FR, TEXTE_EN, DATECREATION, DATEMAJ) VALUES (23, 2, 3, 'Matériel', 'Matériel', 'Material', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO TABLEREFERENCE (TABLEREFERENCEID, ID, VALEUR, TEXTE, TEXTE_FR, TEXTE_EN, DATECREATION, DATEMAJ) VALUES (15, 3, 1, 'Sécurisée', 'Sécurisée', 'Safe', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO TABLEREFERENCE (TABLEREFERENCEID, ID, VALEUR, TEXTE, TEXTE_FR, TEXTE_EN, DATECREATION, DATEMAJ) VALUES (16, 3, 2, 'Non sécurisée', 'Non sécurisée', 'Insecure', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO TABLEREFERENCE (TABLEREFERENCEID, ID, VALEUR, TEXTE, TEXTE_FR, TEXTE_EN, DATECREATION, DATEMAJ) VALUES (17, 4, 1, 'Oui', 'Oui', 'Yes', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO TABLEREFERENCE (TABLEREFERENCEID, ID, VALEUR, TEXTE, TEXTE_FR, TEXTE_EN, DATECREATION, DATEMAJ) VALUES (18, 4, 2, 'Non', 'Non', 'No', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
COMMIT;
INSERT INTO TABLEREFERENCE (TABLEREFERENCEID, ID, VALEUR, TEXTE, TEXTE_FR, TEXTE_EN, DATECREATION, DATEMAJ) VALUES (19, 5, 1, '2 heures', '2 heures', '2 hours', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO TABLEREFERENCE (TABLEREFERENCEID, ID, VALEUR, TEXTE, TEXTE_FR, TEXTE_EN, DATECREATION, DATEMAJ) VALUES (20, 5, 2, 'Heures ouvrables', 'Heures ouvrables', 'Business Hours', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO TABLEREFERENCE (TABLEREFERENCEID, ID, VALEUR, TEXTE, TEXTE_FR, TEXTE_EN, DATECREATION, DATEMAJ) VALUES (21, 5, 3, '24 heures', '24 heures', '24 hours', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

INSERT INTO TABLEREFERENCE (TABLEREFERENCEID, ID, VALEUR, TEXTE, TEXTE_FR, TEXTE_EN, DATECREATION, DATEMAJ) VALUES (170, 102, 0, 'UE', 'UE', 'EU', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
COMMIT;
INSERT INTO TABLEREFERENCE (TABLEREFERENCEID, ID, VALEUR, TEXTE, TEXTE_FR, TEXTE_EN, DATECREATION, DATEMAJ) VALUES (171, 102, 1, 'HORS UE', 'HORS UE', 'OUTSIDE EU', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

INSERT INTO TABLEREFERENCE (TABLEREFERENCEID, ID, VALEUR, TEXTE, TEXTE_FR, TEXTE_EN, DATECREATION, DATEMAJ) VALUES (30, 20, 0, '**********', '**********', '**********', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO TABLEREFERENCE (TABLEREFERENCEID, ID, VALEUR, TEXTE, TEXTE_FR, TEXTE_EN, DATECREATION, DATEMAJ) VALUES (31, 20, 1, 'CHAUFFEUR DIRECTION', 'CHAUFFEUR DIRECTION', 'DRIVER LEADERSHIP', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO TABLEREFERENCE (TABLEREFERENCEID, ID, VALEUR, TEXTE, TEXTE_FR, TEXTE_EN, DATECREATION, DATEMAJ) VALUES (32, 20, 2, 'EMPLOYE', 'EMPLOYE', 'EMPLOYEE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO TABLEREFERENCE (TABLEREFERENCEID, ID, VALEUR, TEXTE, TEXTE_FR, TEXTE_EN, DATECREATION, DATEMAJ) VALUES (33, 20, 3, 'PERSONNE', 'PERSONNE', 'PERSON', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
COMMIT;
INSERT INTO TABLEREFERENCE (TABLEREFERENCEID, ID, VALEUR, TEXTE, TEXTE_FR, TEXTE_EN, DATECREATION, DATEMAJ) VALUES (34, 20, 4, 'TRANSPORT FOND', 'TRANSPORT FOND', 'MONEY TRANSPORT', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO TABLEREFERENCE (TABLEREFERENCEID, ID, VALEUR, TEXTE, TEXTE_FR, TEXTE_EN, DATECREATION, DATEMAJ) VALUES (35, 20, 5, 'INTERVENANT EXTERIEUR', 'INTERVENANT EXTERIEUR', 'EXTERNAL', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO TABLEREFERENCE (TABLEREFERENCEID, ID, VALEUR, TEXTE, TEXTE_FR, TEXTE_EN, DATECREATION, DATEMAJ) VALUES (36, 20, 6, 'TRANSPORTEUR', 'TRANSPORTEUR', 'TRANSPORTER', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO TABLEREFERENCE (TABLEREFERENCEID, ID, VALEUR, TEXTE, TEXTE_FR, TEXTE_EN, DATECREATION, DATEMAJ) VALUES (40, 110, 0, 'Voiture', 'Voiture', 'Car', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO TABLEREFERENCE (TABLEREFERENCEID, ID, VALEUR, TEXTE, TEXTE_FR, TEXTE_EN, DATECREATION, DATEMAJ) VALUES (41, 110, 1, 'Moto', 'Moto', 'Motorcycle', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO TABLEREFERENCE (TABLEREFERENCEID, ID, VALEUR, TEXTE, TEXTE_FR, TEXTE_EN, DATECREATION, DATEMAJ) VALUES (42, 110, 2, 'Camion', 'Camion', 'Truck', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO TABLEREFERENCE (TABLEREFERENCEID, ID, VALEUR, TEXTE, TEXTE_FR, TEXTE_EN, DATECREATION, DATEMAJ) VALUES (43, 110, 3, 'Vélo', 'Vélo', 'Bike', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO TABLEREFERENCE (TABLEREFERENCEID, ID, VALEUR, TEXTE, TEXTE_FR, TEXTE_EN, DATECREATION, DATEMAJ) VALUES (44, 120, 0, 'Essence', 'Essence', 'Essence', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
COMMIT;
INSERT INTO TABLEREFERENCE (TABLEREFERENCEID, ID, VALEUR, TEXTE, TEXTE_FR, TEXTE_EN, DATECREATION, DATEMAJ) VALUES (45, 120, 1, 'Diesel', 'Diesel', 'Diesel', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO TABLEREFERENCE (TABLEREFERENCEID, ID, VALEUR, TEXTE, TEXTE_FR, TEXTE_EN, DATECREATION, DATEMAJ) VALUES (46, 120, 2, 'GPL avec valve', 'GPL avec valve', 'GPL with valve', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO TABLEREFERENCE (TABLEREFERENCEID, ID, VALEUR, TEXTE, TEXTE_FR, TEXTE_EN, DATECREATION, DATEMAJ) VALUES (47, 120, 3, 'GPL sans valve', 'GPL sans valve', 'GPL without valve', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO TABLEREFERENCE (TABLEREFERENCEID, ID, VALEUR, TEXTE, TEXTE_FR, TEXTE_EN, DATECREATION, DATEMAJ) VALUES (48, 90, 1, 'VISITEUR', 'VISITEUR', 'VISITOR', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO TABLEREFERENCE (TABLEREFERENCEID, ID, VALEUR, TEXTE, TEXTE_FR, TEXTE_EN, DATECREATION, DATEMAJ) VALUES (49, 90, 2, 'RESIDANT', 'RESIDANT', 'RESIDENT', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO TABLEREFERENCE (TABLEREFERENCEID, ID, VALEUR, TEXTE, TEXTE_FR, TEXTE_EN, DATECREATION, DATEMAJ) VALUES (50, 90, 3, 'VEHICULE', 'VEHICULE', 'VEHICLE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO TABLEREFERENCE (TABLEREFERENCEID, ID, VALEUR, TEXTE, TEXTE_FR, TEXTE_EN, DATECREATION, DATEMAJ) VALUES (51, 91, 1, 'DIRECT', 'DIRECT', 'DIRECT', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO TABLEREFERENCE (TABLEREFERENCEID, ID, VALEUR, TEXTE, TEXTE_FR, TEXTE_EN, DATECREATION, DATEMAJ) VALUES (52, 91, 2, 'REMOTE', 'REMOTE', 'REMOTE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO TABLEREFERENCE (TABLEREFERENCEID, ID, VALEUR, TEXTE, TEXTE_FR, TEXTE_EN, DATECREATION, DATEMAJ) VALUES (53, 92, 1, 'OK', 'OK', 'OK', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
COMMIT;
INSERT INTO TABLEREFERENCE (TABLEREFERENCEID, ID, VALEUR, TEXTE, TEXTE_FR, TEXTE_EN, DATECREATION, DATEMAJ) VALUES (54, 92, 2, 'PAS OK', 'PAS OK', 'NOT OK', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO TABLEREFERENCE (TABLEREFERENCEID, ID, VALEUR, TEXTE, TEXTE_FR, TEXTE_EN, DATECREATION, DATEMAJ) VALUES (60, 122, -1, 'Utilisateur', 'Utilisateur', 'User', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO TABLEREFERENCE (TABLEREFERENCEID, ID, VALEUR, TEXTE, TEXTE_FR, TEXTE_EN, DATECREATION, DATEMAJ) VALUES (61, 122, -2, 'Point de contrôle', 'Point de contrôle', 'Checkpoint', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO TABLEREFERENCE (TABLEREFERENCEID, ID, VALEUR, TEXTE, TEXTE_FR, TEXTE_EN, DATECREATION, DATEMAJ) VALUES (62, 122, -3, 'Evénement', 'Evénement', 'Event', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO TABLEREFERENCE (TABLEREFERENCEID, ID, VALEUR, TEXTE, TEXTE_FR, TEXTE_EN, DATECREATION, DATEMAJ) VALUES (63, 122, -4, 'Départ de ronde', 'Départ de ronde', 'Start patrol', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO TABLEREFERENCE (TABLEREFERENCEID, ID, VALEUR, TEXTE, TEXTE_FR, TEXTE_EN, DATECREATION, DATEMAJ) VALUES (64, 122, -5, 'Fin de ronde', 'Fin de ronde', 'End patrol', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO TABLEREFERENCE (TABLEREFERENCEID, ID, VALEUR, TEXTE, TEXTE_FR, TEXTE_EN, DATECREATION, DATEMAJ) VALUES (180, -1, 1, 'CB', 'CB', 'Card', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
COMMIT;
INSERT INTO TABLEREFERENCE (TABLEREFERENCEID, ID, VALEUR, TEXTE, TEXTE_FR, TEXTE_EN, DATECREATION, DATEMAJ) VALUES (181, -1, 2, 'ESP', 'ESP', 'Cash', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO TABLEREFERENCE (TABLEREFERENCEID, ID, VALEUR, TEXTE, TEXTE_FR, TEXTE_EN, DATECREATION, DATEMAJ) VALUES (182, -1, 3, 'Ticket', 'Ticket', 'Ticket', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO TABLEREFERENCE (TABLEREFERENCEID, ID, VALEUR, TEXTE, TEXTE_FR, TEXTE_EN, DATECREATION, DATEMAJ) VALUES (183, -1, 4, 'Chèque', 'Chèque', 'Check', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO TABLEREFERENCE (TABLEREFERENCEID, ID, VALEUR, TEXTE, TEXTE_FR, TEXTE_EN, DATECREATION, DATEMAJ) VALUES (184, -1, 5, 'Autre', 'Autre', 'Other', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO TABLEREFERENCE (TABLEREFERENCEID, ID, VALEUR, TEXTE, TEXTE_FR, TEXTE_EN, DATECREATION, DATEMAJ) VALUES (220, 123, 0, 'Vérification des personnes à accès interdit', 'Vérification des personnes à accès interdit', 'check people with denied access' , CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO TABLEREFERENCE (TABLEREFERENCEID, ID, VALEUR, TEXTE, TEXTE_FR, TEXTE_EN, DATECREATION, DATEMAJ) VALUES (65, 123, -1, 'Précaution d''accès', 'Précaution d''accès', 'Entrance requirement' , CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO TABLEREFERENCE (TABLEREFERENCEID, ID, VALEUR, TEXTE, TEXTE_FR, TEXTE_EN, DATECREATION, DATEMAJ) VALUES (66, 123, -2, 'Délai d''anticipation', 'Délai d''anticipation', 'Waiting period', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO TABLEREFERENCE (TABLEREFERENCEID, ID, VALEUR, TEXTE, TEXTE_FR, TEXTE_EN, DATECREATION, DATEMAJ) VALUES (67, 123, -3, 'Cumul des jours de visite', 'Cumul des jours de visite', 'Cumulative entrance duration', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO TABLEREFERENCE (TABLEREFERENCEID, ID, VALEUR, TEXTE, TEXTE_FR, TEXTE_EN, DATECREATION, DATEMAJ) VALUES (68, 123, -4, 'Zones d''accès', 'Zones d''accès', 'Access area', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO TABLEREFERENCE (TABLEREFERENCEID, ID, VALEUR, TEXTE, TEXTE_FR, TEXTE_EN, DATECREATION, DATEMAJ) VALUES (69, 123, -5, 'Validation par les groupes', 'Validation par les groupes', 'pool validation', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
COMMIT;
INSERT INTO TABLEREFERENCE (TABLEREFERENCEID, ID, VALEUR, TEXTE, TEXTE_FR, TEXTE_EN, DATECREATION, DATEMAJ) VALUES (69, 123, -6, 'Mesure compensatoire', 'Mesure compensatoire', 'Compensatory measure', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO TABLEREFERENCE (TABLEREFERENCEID, ID, VALEUR, TEXTE, TEXTE_FR, TEXTE_EN, DATECREATION, DATEMAJ) VALUES (70, 123, -7, 'Validation de documents', 'Validation de documents', 'Document validation', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO TABLEREFERENCE (TABLEREFERENCEID, ID, VALEUR, TEXTE, TEXTE_FR, TEXTE_EN, DATECREATION, DATEMAJ) VALUES (71, 123, -8, 'Enquête requise', 'Enquête requise', 'Need for inquiry', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO TABLEREFERENCE (TABLEREFERENCEID, ID, VALEUR, TEXTE, TEXTE_FR, TEXTE_EN, DATECREATION, DATEMAJ) VALUES (72, 123, -9, 'Saisie Résidants', 'Saisie Résidants', 'Resident registration', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO TABLEREFERENCE (TABLEREFERENCEID, ID, VALEUR, TEXTE, TEXTE_FR, TEXTE_EN, DATECREATION, DATEMAJ) VALUES (77, 123, -10, 'Transport de matières dangereuses', 'Transport de matières dangereuses', 'Hazardous products transportation', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO TABLEREFERENCE (TABLEREFERENCEID, ID, VALEUR, TEXTE, TEXTE_FR, TEXTE_EN, DATECREATION, DATEMAJ) VALUES (80, 123, -11, 'Soumission à enquête', 'Soumission à enquête', 'Submitting to inquiry', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO TABLEREFERENCE (TABLEREFERENCEID, ID, VALEUR, TEXTE, TEXTE_FR, TEXTE_EN, DATECREATION, DATEMAJ) VALUES (81, 123, -12, 'CPPA', 'CPPA', 'CPPA', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO TABLEREFERENCE (TABLEREFERENCEID, ID, VALEUR, TEXTE, TEXTE_FR, TEXTE_EN, DATECREATION, DATEMAJ) VALUES (82, 123, -13, 'Zones à regime restrictif', 'Zones à regime restrictif', 'Restricted access areas', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO TABLEREFERENCE (TABLEREFERENCEID, ID, VALEUR, TEXTE, TEXTE_FR, TEXTE_EN, DATECREATION, DATEMAJ) VALUES (83, 123, -14, 'Mineurs', 'Mineurs', 'Underage', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO TABLEREFERENCE (TABLEREFERENCEID, ID, VALEUR, TEXTE, TEXTE_FR, TEXTE_EN, DATECREATION, DATEMAJ) VALUES (84, 123, -15, 'Restreints', 'Restreints', 'Restrained', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

 INSERT INTO TABLEREFERENCE (TABLEREFERENCEID, ID, VALEUR, TEXTE, TEXTE_FR, TEXTE_EN, DATECREATION, DATEMAJ) VALUES (85, 123, -16, 'Localisations', 'Localisations', 'Localisations', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
 INSERT INTO TABLEREFERENCE (TABLEREFERENCEID, ID, VALEUR, TEXTE, TEXTE_FR, TEXTE_EN, DATECREATION, DATEMAJ) VALUES (86, 123, -17, 'Durée de la visite', 'Durée de la visite', 'Visit duration', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO TABLEREFERENCE (TABLEREFERENCEID, ID, VALEUR, TEXTE, TEXTE_FR, TEXTE_EN, DATECREATION, DATEMAJ) VALUES (73, 124, -1, 'Aucune', 'Aucune', 'None', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO TABLEREFERENCE (TABLEREFERENCEID, ID, VALEUR, TEXTE, TEXTE_FR, TEXTE_EN, DATECREATION, DATEMAJ) VALUES (74, 124, -2, 'Interdire', 'Interdire', 'Deny access', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO TABLEREFERENCE (TABLEREFERENCEID, ID, VALEUR, TEXTE, TEXTE_FR, TEXTE_EN, DATECREATION, DATEMAJ) VALUES (75, 124, -4, 'Accompagner', 'Accompagner', 'Escort', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO TABLEREFERENCE (TABLEREFERENCEID, ID, VALEUR, TEXTE, TEXTE_FR, TEXTE_EN, DATECREATION, DATEMAJ) VALUES (76, 124, -3, 'Soumettre à autorisation', 'Soumettre à autorisation', 'Ask for permission', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO TABLEREFERENCE (TABLEREFERENCEID, ID, VALEUR, TEXTE, TEXTE_FR, TEXTE_EN, DATECREATION, DATEMAJ) VALUES (78, 124, -5, 'Autoriser', 'Autoriser', 'Allow access', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO TABLEREFERENCE (TABLEREFERENCEID, ID, VALEUR, TEXTE, TEXTE_FR, TEXTE_EN, DATECREATION, DATEMAJ) VALUES (79, 124, -6, 'Soumettre pour enquête', 'Soumettre pour enquête', 'Submit to inquiry', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO TABLEREFERENCE (TABLEREFERENCEID, ID, VALEUR, TEXTE, TEXTE_FR, TEXTE_EN, DATECREATION, DATEMAJ) VALUES (94, 126, 10, 'Classe 6.2 : Matières infectieuses', 'Classe 6.2 : Matières infectieuses', 'Class 6.2: Infectious substances', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO TABLEREFERENCE (TABLEREFERENCEID, ID, VALEUR, TEXTE, TEXTE_FR, TEXTE_EN, DATECREATION, DATEMAJ) VALUES (95, 126, 11, 'Classe 7 : Matières radioactives', 'Classe 7 : Matières radioactives', 'Class 7: Radioactive material', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
COMMIT;
INSERT INTO TABLEREFERENCE (TABLEREFERENCEID, ID, VALEUR, TEXTE, TEXTE_FR, TEXTE_EN, DATECREATION, DATEMAJ) VALUES (83, 125, 0, 'CIVILITE', 'CIVILITE', 'CIVILITY', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO TABLEREFERENCE (TABLEREFERENCEID, ID, VALEUR, TEXTE, TEXTE_FR, TEXTE_EN, DATECREATION, DATEMAJ) VALUES (221, 125, -1, 'NOM', 'NOM', 'LAST NAME', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO TABLEREFERENCE (TABLEREFERENCEID, ID, VALEUR, TEXTE, TEXTE_FR, TEXTE_EN, DATECREATION, DATEMAJ) VALUES (222, 125, -2, 'PRENOM', 'PRENOM', 'FIRST NAME', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO TABLEREFERENCE (TABLEREFERENCEID, ID, VALEUR, TEXTE, TEXTE_FR, TEXTE_EN, DATECREATION, DATEMAJ) VALUES (223, 125, -3, 'NOM DE JEUNE FILLE', 'NOM DE JEUNE FILLE', 'MAIDEN NAME', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO TABLEREFERENCE (TABLEREFERENCEID, ID, VALEUR, TEXTE, TEXTE_FR, TEXTE_EN, DATECREATION, DATEMAJ) VALUES (224, 125, -4, 'DATE DE NAISSANCE', 'DATE DE NAISSANCE', 'BIRTH DATE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO TABLEREFERENCE (TABLEREFERENCEID, ID, VALEUR, TEXTE, TEXTE_FR, TEXTE_EN, DATECREATION, DATEMAJ) VALUES (225, 125, -5, 'LIEU DE NAISSANCE', 'LIEU DE NAISSANCE', 'BIRTH LOCATION', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO TABLEREFERENCE (TABLEREFERENCEID, ID, VALEUR, TEXTE, TEXTE_FR, TEXTE_EN, DATECREATION, DATEMAJ) VALUES (226, 125, -6, 'NATIONALITE', 'NATIONALITE', 'NATIONALITY', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO TABLEREFERENCE (TABLEREFERENCEID, ID, VALEUR, TEXTE, TEXTE_FR, TEXTE_EN, DATECREATION, DATEMAJ) VALUES (227, 125, -7, 'FONCTION', 'FONCTION', 'POSITION', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO TABLEREFERENCE (TABLEREFERENCEID, ID, VALEUR, TEXTE, TEXTE_FR, TEXTE_EN, DATECREATION, DATEMAJ) VALUES (228, 125, -8, 'SOCIETE', 'SOCIETE', 'COMPANY', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO TABLEREFERENCE (TABLEREFERENCEID, ID, VALEUR, TEXTE, TEXTE_FR, TEXTE_EN, DATECREATION, DATEMAJ) VALUES (229, 125, -9, 'PAYS DE NAISSANCE', 'PAYS DE NAISSANCE', 'BIRTH COUNTRY', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO TABLEREFERENCE (TABLEREFERENCEID, ID, VALEUR, TEXTE, TEXTE_FR, TEXTE_EN, DATECREATION, DATEMAJ) VALUES (230, 125, -10, 'NATIONALITE D''ORIGINE', 'NATIONALITE D''ORIGINE', 'INITIAL NATIONALITY', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO TABLEREFERENCE (TABLEREFERENCEID, ID, VALEUR, TEXTE, TEXTE_FR, TEXTE_EN, DATECREATION, DATEMAJ) VALUES (231, 125, -11, 'PAYS D''ADRESSE', 'PAYS D''ADRESSE', 'COUNTRY OF ADRESS', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO TABLEREFERENCE (TABLEREFERENCEID, ID, VALEUR, TEXTE, TEXTE_FR, TEXTE_EN, DATECREATION, DATEMAJ) VALUES (232, 125, -12, 'ADRESSE', 'ADRESSE', 'ADRESS', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
COMMIT;
INSERT INTO TABLEREFERENCE (TABLEREFERENCEID, ID, VALEUR, TEXTE, TEXTE_FR, TEXTE_EN, DATECREATION, DATEMAJ) VALUES (233, 125, -13, 'CODE POSTAL', 'CODE POSTAL', 'ZIP CODE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO TABLEREFERENCE (TABLEREFERENCEID, ID, VALEUR, TEXTE, TEXTE_FR, TEXTE_EN, DATECREATION, DATEMAJ) VALUES (234, 125, -14, 'VILLE', 'VILLE', 'CITY', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO TABLEREFERENCE (TABLEREFERENCEID, ID, VALEUR, TEXTE, TEXTE_FR, TEXTE_EN, DATECREATION, DATEMAJ) VALUES (235, 125, -15, 'STATUT', 'STATUT', 'STATUS', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO TABLEREFERENCE (TABLEREFERENCEID, ID, VALEUR, TEXTE, TEXTE_FR, TEXTE_EN, DATECREATION, DATEMAJ) VALUES (236, 125, -16, 'TELEPHONE', 'TELEPHONE', 'TELEPHONE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO TABLEREFERENCE (TABLEREFERENCEID, ID, VALEUR, TEXTE, TEXTE_FR, TEXTE_EN, DATECREATION, DATEMAJ) VALUES (237, 125, -17, 'MOBILE', 'MOBILE', 'MOBILE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO TABLEREFERENCE (TABLEREFERENCEID, ID, VALEUR, TEXTE, TEXTE_FR, TEXTE_EN, DATECREATION, DATEMAJ) VALUES (238, 125, -18, 'EMAIL', 'EMAIL', 'EMAIL', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO TABLEREFERENCE (TABLEREFERENCEID, ID, VALEUR, TEXTE, TEXTE_FR, TEXTE_EN, DATECREATION, DATEMAJ) VALUES (240, 125, -19, 'CHAMPS CONTROLES', 'CHAMPS CONTROLES', 'CHECKED FIELDS', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

INSERT INTO TABLEREFERENCE (TABLEREFERENCEID, ID, VALEUR, TEXTE, TEXTE_FR, TEXTE_EN, DATECREATION, DATEMAJ) VALUES (85, 126, 1, 'Classe 1 : Matières et objets explosibles', 'Classe 1 : Matières et objets explosibles', 'Class 1: Explosive substances and articles', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO TABLEREFERENCE (TABLEREFERENCEID, ID, VALEUR, TEXTE, TEXTE_FR, TEXTE_EN, DATECREATION, DATEMAJ) VALUES (86, 126, 2, 'Classe 2 : Gaz', 'Classe 2 : Gaz', 'Class 2 : Gases', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
COMMIT;
INSERT INTO TABLEREFERENCE (TABLEREFERENCEID, ID, VALEUR, TEXTE, TEXTE_FR, TEXTE_EN, DATECREATION, DATEMAJ) VALUES (87, 126, 3, 'Classe 3 : Liquides inflammables', 'Classe 3 : Liquides inflammables', 'Class 3: Flammable liquids', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO TABLEREFERENCE (TABLEREFERENCEID, ID, VALEUR, TEXTE, TEXTE_FR, TEXTE_EN, DATECREATION, DATEMAJ) VALUES (88, 126, 4, 'Classe 4.1 : Matières solides inflammables et matières autoréactives', 'Classe 4.1 : Matières solides inflammables et matières autoréactives', 'Class 4.1: Flammable solids, self-reactive substances and solid desensitized explosives', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO TABLEREFERENCE (TABLEREFERENCEID, ID, VALEUR, TEXTE, TEXTE_FR, TEXTE_EN, DATECREATION, DATEMAJ) VALUES (89, 126, 5, 'Classe 4.2 : Matières sujettes à l''inflammation spontanée', 'Classe 4.2 : Matières sujettes à l''inflammation spontanée', 'Class 4.2: Substances liable to spontaneous combustion', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO TABLEREFERENCE (TABLEREFERENCEID, ID, VALEUR, TEXTE, TEXTE_FR, TEXTE_EN, DATECREATION, DATEMAJ) VALUES (90, 126, 6, 'Classe 4.3 : Matières hydroréactives', 'Classe 4.3 : Matières hydroréactives', 'Class 4.3: Substances which, in contact with water, emit flammable gases', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO TABLEREFERENCE (TABLEREFERENCEID, ID, VALEUR, TEXTE, TEXTE_FR, TEXTE_EN, DATECREATION, DATEMAJ) VALUES (91, 126, 7, 'Classe 5.1 : Matières comburantes', 'Classe 5.1 : Matières comburantes', 'Class 5.1: Oxidizing substances', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO TABLEREFERENCE (TABLEREFERENCEID, ID, VALEUR, TEXTE, TEXTE_FR, TEXTE_EN, DATECREATION, DATEMAJ) VALUES (92, 126, 8, 'Classe 5.2 : Peroxydes organiques', 'Classe 5.2 : Peroxydes organiques', 'Class 5.2: Organic peroxides', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO TABLEREFERENCE (TABLEREFERENCEID, ID, VALEUR, TEXTE, TEXTE_FR, TEXTE_EN, DATECREATION, DATEMAJ) VALUES (93, 126, 9, 'Classe 6.1 : Matières toxiques', 'Classe 6.1 : Matières toxiques', 'Class 6.1: Toxic substances', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO TABLEREFERENCE (TABLEREFERENCEID, ID, VALEUR, TEXTE, TEXTE_FR, TEXTE_EN, DATECREATION, DATEMAJ) VALUES (96, 126, 12, 'Classe 8 : Matières corrosives', 'Classe 8 : Matières corrosives', 'Class 8: Corrosive substances', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO TABLEREFERENCE (TABLEREFERENCEID, ID, VALEUR, TEXTE, TEXTE_FR, TEXTE_EN, DATECREATION, DATEMAJ) VALUES (97, 126, 13, 'Classe 9 : Matières et objets divers dangereux pour l''environnement', 'Classe 9 : Matières et objets divers dangereux pour l''environnement', 'Class 9: Miscellaneous dangerous substances and articles', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
COMMIT;
INSERT INTO TABLEREFERENCE (TABLEREFERENCEID, ID, VALEUR, TEXTE, TEXTE_FR, TEXTE_EN, DATECREATION, DATEMAJ) VALUES (98, 127, 0, 'TOUS', 'TOUS', 'ALL', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO TABLEREFERENCE (TABLEREFERENCEID, ID, VALEUR, TEXTE, TEXTE_FR, TEXTE_EN, DATECREATION, DATEMAJ) VALUES (99, 127, -1, 'VISITEUR', 'VISITEUR', 'VISITOR', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO TABLEREFERENCE (TABLEREFERENCEID, ID, VALEUR, TEXTE, TEXTE_FR, TEXTE_EN, DATECREATION, DATEMAJ) VALUES (100, 127, -2, 'SOCIETE DU VISITEUR', 'SOCIETE VISITEUR', 'VISITING COMPANY', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO TABLEREFERENCE (TABLEREFERENCEID, ID, VALEUR, TEXTE, TEXTE_FR, TEXTE_EN, DATECREATION, DATEMAJ) VALUES (102, 128, 0, 'ETRANGER UE', 'ETRANGER EU', 'FOREIGN INSIDE EU', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO TABLEREFERENCE (TABLEREFERENCEID, ID, VALEUR, TEXTE, TEXTE_FR, TEXTE_EN, DATECREATION, DATEMAJ) VALUES (103, 128, 1, 'ETRANGER HORS UE', 'ETRANGER HORS UE', 'FOREIGN OUTSIDE EU', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO TABLEREFERENCE (TABLEREFERENCEID, ID, VALEUR, TEXTE, TEXTE_FR, TEXTE_EN, DATECREATION, DATEMAJ) VALUES (104, 128, 2, 'ETRANGER', 'ETRANGER', 'FOREIGN', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
COMMIT;

INSERT INTO TABLEREFERENCE (TABLEREFERENCEID, ID, VALEUR, TEXTE, TEXTE_FR, TEXTE_EN, DATECREATION, DATEMAJ) VALUES (195, 135, 0, 'Négatif', 'Négatif', 'Disabled', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO TABLEREFERENCE (TABLEREFERENCEID, ID, VALEUR, TEXTE, TEXTE_FR, TEXTE_EN, DATECREATION, DATEMAJ) VALUES (196, 135, 1, 'Positif', 'Positif', 'Enabled', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO TABLEREFERENCE (TABLEREFERENCEID, ID, VALEUR, TEXTE, TEXTE_FR, TEXTE_EN, DATECREATION, DATEMAJ) VALUES (218, 135, -1, 'Supprimé', 'Supprimé', 'Deleted', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO TABLEREFERENCE (TABLEREFERENCEID, ID, VALEUR, TEXTE, TEXTE_FR, TEXTE_EN, DATECREATION, DATEMAJ) VALUES (219, 135, -2, 'Manquant', 'Manquant', 'Missing', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
COMMIT;

INSERT INTO TABLEREFERENCE(TABLEREFERENCEID,ID,VALEUR,TEXTE,TEXTE_FR,TEXTE_EN,DATECREATION,DATEMAJ) VALUES (198,130,-1,'Text','Text','Text',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO TABLEREFERENCE(TABLEREFERENCEID,ID,VALEUR,TEXTE,TEXTE_FR,TEXTE_EN,DATECREATION,DATEMAJ) VALUES (199,130,-2,'SQL','SQL','SQL',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO TABLEREFERENCE(TABLEREFERENCEID,ID,VALEUR,TEXTE,TEXTE_FR,TEXTE_EN,DATECREATION,DATEMAJ) VALUES (200,130,-3,'AD/LDAP','AD/LDAP','AD/LDAP',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO TABLEREFERENCE(TABLEREFERENCEID,ID,VALEUR,TEXTE,TEXTE_FR,TEXTE_EN,DATECREATION,DATEMAJ) VALUES (201,131,-1,'SQL SERVER','SQL SERVER','SQL SERVER',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO TABLEREFERENCE(TABLEREFERENCEID,ID,VALEUR,TEXTE,TEXTE_FR,TEXTE_EN,DATECREATION,DATEMAJ) VALUES (202,131,-2,'ORACLE','ORACLE','ORACLE',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO TABLEREFERENCE(TABLEREFERENCEID,ID,VALEUR,TEXTE,TEXTE_FR,TEXTE_EN,DATECREATION,DATEMAJ) VALUES (203,132,1,'Immédiat','Immédiat','Instant',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO TABLEREFERENCE(TABLEREFERENCEID,ID,VALEUR,TEXTE,TEXTE_FR,TEXTE_EN,DATECREATION,DATEMAJ) VALUES (204,132,0,'Normal','Normal','Normal',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
COMMIT;

INSERT INTO TABLEREFERENCE(TABLEREFERENCEID,ID,VALEUR,TEXTE,TEXTE_FR,TEXTE_EN,DATECREATION,DATEMAJ) VALUES (205,133,1,'Actif','Actif','Enabled',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO TABLEREFERENCE(TABLEREFERENCEID,ID,VALEUR,TEXTE,TEXTE_FR,TEXTE_EN,DATECREATION,DATEMAJ) VALUES (206,133,0,'Inactif','Inactif','Disabled',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO TABLEREFERENCE(TABLEREFERENCEID,ID,VALEUR,TEXTE,TEXTE_FR,TEXTE_EN,DATECREATION,DATEMAJ) VALUES (207,133,-1,'Executé','Executé','Processed',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
COMMIT;
INSERT INTO TABLEREFERENCE(TABLEREFERENCEID,ID,VALEUR,TEXTE,TEXTE_FR,TEXTE_EN,DATECREATION,DATEMAJ) VALUES (208,134,-2,'Immédiat','Immédiat','Instant',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO TABLEREFERENCE(TABLEREFERENCEID,ID,VALEUR,TEXTE,TEXTE_FR,TEXTE_EN,DATECREATION,DATEMAJ) VALUES (209,134,-1,'Exécution unique','Exécution unique','One shot',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO TABLEREFERENCE(TABLEREFERENCEID,ID,VALEUR,TEXTE,TEXTE_FR,TEXTE_EN,DATECREATION,DATEMAJ) VALUES (210,134,0,'Quotidienne','Quotitidienne','Daily',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO TABLEREFERENCE(TABLEREFERENCEID,ID,VALEUR,TEXTE,TEXTE_FR,TEXTE_EN,DATECREATION,DATEMAJ) VALUES (211,134,1,'Jours de la semaine','Jours de la semaines','Week days',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO TABLEREFERENCE(TABLEREFERENCEID,ID,VALEUR,TEXTE,TEXTE_FR,TEXTE_EN,DATECREATION,DATEMAJ) VALUES (212,134,2,'Jours du mois','Jours du mois','days of the month',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO TABLEREFERENCE(TABLEREFERENCEID,ID,VALEUR,TEXTE,TEXTE_FR,TEXTE_EN,DATECREATION,DATEMAJ) VALUES (213,134,3,'Premier jour du mois','Premier jour du mois','first day of the month',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO TABLEREFERENCE(TABLEREFERENCEID,ID,VALEUR,TEXTE,TEXTE_FR,TEXTE_EN,DATECREATION,DATEMAJ) VALUES (214,134,4,'Dernier jour du mois','Dernier jour du mois','last day of the month',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
COMMIT;

INSERT INTO TABLEREFERENCE(TABLEREFERENCEID,ID,VALEUR,TEXTE,TEXTE_FR,TEXTE_EN,DATECREATION,DATEMAJ) VALUES (215,136,0,'Premier jour','Premier jour','First day',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO TABLEREFERENCE(TABLEREFERENCEID,ID,VALEUR,TEXTE,TEXTE_FR,TEXTE_EN,DATECREATION,DATEMAJ) VALUES (216,136,-1,'Dernier jour','Dernier jour','Last day',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
COMMIT;

INSERT INTO TABLEREFERENCE (TABLEREFERENCEID, ID, VALEUR, TEXTE, TEXTE_FR, TEXTE_EN, DATECREATION, DATEMAJ) VALUES (242, 124, -22, 'Raccourcir la visite', 'Raccourcir la visite', 'Reduce visit duration', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

INSERT INTO TABLEREFERENCE (TABLEREFERENCEID, ID, VALEUR, TEXTE, TEXTE_FR, TEXTE_EN, DATECREATION, DATEMAJ) VALUES (243, 124, -23, 'Invalider Document', 'Invalider un document', 'unvalidated one document', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

INSERT INTO TABLEREFERENCE (TABLEREFERENCEID, ID, VALEUR, TEXTE, TEXTE_FR, TEXTE_EN, DATECREATION, DATEMAJ) VALUES (257, 124, -24, 'Mettre en enquête', 'Mettre en enquête', 'Put under survey', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

INSERT INTO TABLEREFERENCE (TABLEREFERENCEID, ID, VALEUR, TEXTE, TEXTE_FR, TEXTE_EN, DATECREATION, DATEMAJ) VALUES (263, 124, -25, 'Forcer enquête', 'Forcer enquête', 'Put on survey', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);


INSERT INTO TABLEREFERENCE (TABLEREFERENCEID, ID, VALEUR, TEXTE, TEXTE_FR, TEXTE_EN, DATECREATION, DATEMAJ) VALUES (250, 139, -1, 'IMPORT', 'Import de données', 'Data import', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

INSERT INTO TABLEREFERENCE (TABLEREFERENCEID, ID, VALEUR, TEXTE, TEXTE_FR, TEXTE_EN, DATECREATION, DATEMAJ) VALUES (251, 139, -2, 'ETAT', 'Etat', 'Report', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);


INSERT INTO TABLEREFERENCE (TABLEREFERENCEID, ID, VALEUR, TEXTE, TEXTE_FR, TEXTE_EN, DATECREATION, DATEMAJ) VALUES (252, 140, -1, 'Payant', 'Payant', 'Payment requested', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO TABLEREFERENCE (TABLEREFERENCEID, ID, VALEUR, TEXTE, TEXTE_FR, TEXTE_EN, DATECREATION, DATEMAJ) VALUES (253, 140, -2, 'Gratuit', 'Gratuit', 'Free', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

INSERT INTO TABLEREFERENCE(TABLEREFERENCEID,ID,VALEUR,TEXTE,TEXTE_FR,TEXTE_EN,DATEMAJ,DATECREATION) VALUES(255,15,0,'HTTP/POST','HTTP/POST','HTTP/POST',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);

INSERT INTO TABLEREFERENCE(TABLEREFERENCEID,ID,VALEUR,TEXTE,TEXTE_FR,TEXTE_EN,DATEMAJ,DATECREATION) VALUES(254,139,-3,'PURGE','Purge','Purge',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);

INSERT INTO TABLEREFERENCE(TABLEREFERENCEID,ID,VALEUR,TEXTE,TEXTE_FR,TEXTE_EN,DATEMAJ,DATECREATION) VALUES(256,139,-4,'GESTION_WS','Gestion des webServices','Managing web services',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO TABLEREFERENCE(TABLEREFERENCEID,ID,VALEUR,TEXTE,TEXTE_FR,TEXTE_EN,DATEMAJ,DATECREATION) VALUES(263,139,-5,'GESTION_PSTK','Gestion des procédures stockées','Managing stored procedures',current_timestamp,current_timestamp);
COMMIT;


INSERT INTO TABLEREFERENCE (TABLEREFERENCEID, ID, VALEUR, TEXTE, TEXTE_FR, TEXTE_EN, DATECREATION, DATEMAJ) VALUES (253, 141, -2, 'Tous', 'Tous', 'All', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO TABLEREFERENCE (TABLEREFERENCEID, ID, VALEUR, TEXTE, TEXTE_FR, TEXTE_EN, DATECREATION, DATEMAJ) VALUES (257, 141, 0, 'Visite', 'Visite', 'Visit', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO TABLEREFERENCE (TABLEREFERENCEID, ID, VALEUR, TEXTE, TEXTE_FR, TEXTE_EN, DATECREATION, DATEMAJ) VALUES (258, 141, 1, 'Travail', 'Travail', 'Work', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

INSERT INTO TABLEREFERENCE (TABLEREFERENCEID, ID, VALEUR, TEXTE, TEXTE_FR, TEXTE_EN, DATECREATION, DATEMAJ) VALUES (259, 142,2, 'Officier de Sécurité', 'Officier de Sécurité', 'Security Officer', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO TABLEREFERENCE (TABLEREFERENCEID, ID, VALEUR, TEXTE, TEXTE_FR, TEXTE_EN, DATECREATION, DATEMAJ) VALUES (260, 142,4, 'Résident ou OS', 'Résident ou OS', 'Resident or Security Officer', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO TABLEREFERENCE (TABLEREFERENCEID, ID, VALEUR, TEXTE, TEXTE_FR, TEXTE_EN, DATECREATION, DATEMAJ) VALUES (261, 142,3, 'Accueil ou OS', 'Accueil ou Officier de Sécurité', 'Reception or Security Officer', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO TABLEREFERENCE (TABLEREFERENCEID, ID, VALEUR, TEXTE, TEXTE_FR, TEXTE_EN, DATECREATION, DATEMAJ) VALUES (262, 142,1, 'Résident ou Accueil ou OS', 'Résident ou Accueil ou Officier de Sécurité', 'Resident or Reception or Security Officer', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

COMMIT;
DELETE FROM PERIPHERIQUE_TRAITEMENT;

INSERT INTO PERIPHERIQUE_TRAITEMENT (PERIPHERIQUE_TRAITEMENTID, LIBELLE, FAMILLE, DATECREATION, DATEMAJ) VALUES (-1,'SWISS_READER',2,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO PERIPHERIQUE_TRAITEMENT (PERIPHERIQUE_TRAITEMENTID, LIBELLE, FAMILLE, DATECREATION, DATEMAJ) VALUES (-2,'MAGNETA_ESCORT2',4,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO PERIPHERIQUE_TRAITEMENT (PERIPHERIQUE_TRAITEMENTID, LIBELLE, FAMILLE, DATECREATION, DATEMAJ) VALUES (-3,'DEISTER_GUARDIX',4,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO PERIPHERIQUE_TRAITEMENT (PERIPHERIQUE_TRAITEMENTID, LIBELLE, FAMILLE, DATECREATION, DATEMAJ) VALUES (-4,'BADGE',1,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO PERIPHERIQUE_TRAITEMENT (PERIPHERIQUE_TRAITEMENTID, LIBELLE, FAMILLE, DATECREATION, DATEMAJ) VALUES (-5,'HITACHI_BIOVEIN',5,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO PERIPHERIQUE_TRAITEMENT (PERIPHERIQUE_TRAITEMENTID, LIBELLE, FAMILLE, DATECREATION, DATEMAJ) VALUES (-6,'SRI_RADIO',4,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO PERIPHERIQUE_TRAITEMENT (PERIPHERIQUE_TRAITEMENTID, LIBELLE, FAMILLE, DATECREATION, DATEMAJ) VALUES (-7,'TOPAZ_SIGPLUS',6,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO PERIPHERIQUE_TRAITEMENT (PERIPHERIQUE_TRAITEMENTID, LIBELLE, FAMILLE, DATECREATION, DATEMAJ) VALUES (-8,'IRIS_IRISCARD_A6',3,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO PERIPHERIQUE_TRAITEMENT (PERIPHERIQUE_TRAITEMENTID, LIBELLE, FAMILLE, DATECREATION, DATEMAJ) VALUES (-9,'DESKO_EVO',2,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO PERIPHERIQUE_TRAITEMENT (PERIPHERIQUE_TRAITEMENTID, LIBELLE, FAMILLE, DATECREATION, DATEMAJ) VALUES (-10,'EDEN_BIOVEIN',8,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO PERIPHERIQUE_TRAITEMENT (PERIPHERIQUE_TRAITEMENTID, LIBELLE, FAMILLE, DATECREATION, DATEMAJ) VALUES (-11,'DATALOGIC_POWERSCAN',7,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO PERIPHERIQUE_TRAITEMENT (PERIPHERIQUE_TRAITEMENTID, LIBELLE, FAMILLE, DATECREATION, DATEMAJ) VALUES (-12,'SIGN_SCREEN',6,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO PERIPHERIQUE_TRAITEMENT (PERIPHERIQUE_TRAITEMENTID, LIBELLE, FAMILLE, DATECREATION, DATEMAJ) VALUES (-13,'ARH_COMBOSMART',2,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO PERIPHERIQUE_TRAITEMENT (PERIPHERIQUE_TRAITEMENTID, LIBELLE, FAMILLE, DATECREATION, DATEMAJ) VALUES (-14,'MAGNETA_EASYRONDE',4,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO PERIPHERIQUE_TRAITEMENT (PERIPHERIQUE_TRAITEMENTID, LIBELLE, FAMILLE, DATECREATION, DATEMAJ) VALUES (-15,'SURVACOM_TRACING',4,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO PERIPHERIQUE_TRAITEMENT (PERIPHERIQUE_TRAITEMENTID, LIBELLE, FAMILLE, DATECREATION, DATEMAJ) VALUES (-16,'ZALIX_VEINSECURE',5,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO PERIPHERIQUE_TRAITEMENT (PERIPHERIQUE_TRAITEMENTID, LIBELLE, FAMILLE, DATECREATION, DATEMAJ) VALUES (-17,'WACOM_STU',6,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO PERIPHERIQUE_TRAITEMENT (PERIPHERIQUE_TRAITEMENTID, LIBELLE, FAMILLE, DATECREATION, DATEMAJ) VALUES (-19,'SIGN_SCREEN_TABLET',6,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);

COMMIT;

EXIT;