-- *******************************************************************************
-- *                                   Date de dernière mise à jour : 09/01/2009 *
-- *******************************************************************************

ALTER SESSION SET NLS_DATE_FORMAT='DD/MM/YYYY';

INSERT INTO STATUTPARKING (CODE_STATUT,STATUT_NAME) VALUES ('0','Non affecté');
INSERT INTO STATUTPARKING (CODE_STATUT,STATUT_NAME) VALUES ('1','Attribué');

INSERT INTO VERSION_SFW VALUES ('8.0.5','S00012','29559',SYSDATE,SYSDATE,'DD/MM/YYYY','');

INSERT INTO TYPEIDENTITE (TYPEIDENTITEID,LIBELLE,DATEMAJ,DATECREATION) VALUES (0,'**********',SYSDATE,SYSDATE);
INSERT INTO TYPEIDENTITE (TYPEIDENTITEID,LIBELLE,DATEMAJ,DATECREATION,DATESYNCHRO) VALUES (-1,'PASSEPORT',SYSDATE,SYSDATE,SYSDATE);
INSERT INTO TYPEIDENTITE (TYPEIDENTITEID,LIBELLE,DATEMAJ,DATECREATION,DATESYNCHRO) VALUES (-2,'CNI',SYSDATE,SYSDATE,SYSDATE);
INSERT INTO TYPEIDENTITE (TYPEIDENTITEID,LIBELLE,DATEMAJ,DATECREATION,DATESYNCHRO) VALUES (-3,'TITRE DE SEJOUR',SYSDATE,SYSDATE,SYSDATE);
INSERT INTO TYPEIDENTITE (TYPEIDENTITEID,LIBELLE,DATEMAJ,DATECREATION,DATESYNCHRO) VALUES (-4,'CIE',SYSDATE,SYSDATE,SYSDATE);
INSERT INTO TYPEIDENTITE (TYPEIDENTITEID,LIBELLE,DATEMAJ,DATECREATION,DATESYNCHRO) VALUES (-5,'VISA',SYSDATE,SYSDATE,SYSDATE);

INSERT INTO TYPEADRESSE (TYPEADRESSEID,TYPEADRESSE,DATECREATION,DATEMAJ) VALUES (0,'**********',SYSDATE,SYSDATE);
INSERT INTO TYPEADRESSE (TYPEADRESSEID,TYPEADRESSE,DATECREATION,DATEMAJ) VALUES (-1,'TAXIS',SYSDATE,SYSDATE);

INSERT INTO TYPECONSIGNE (TYPECONSIGNEID,TYPECONSIGNE,DATECREATION,DATEMAJ) VALUES (0,'**********',SYSDATE,SYSDATE);

INSERT INTO TYPEVISITE (TYPEVISITEID,TYPEVISITE,DATECREATION,DATEMAJ) VALUES (0,'Visite',SYSDATE,SYSDATE);
INSERT INTO TYPEVISITE (TYPEVISITEID,TYPEVISITE,DATECREATION,DATEMAJ) VALUES (-2,'Tous',SYSDATE,SYSDATE);
INSERT INTO TYPEVISITE (TYPEVISITEID,TYPEVISITE,DATECREATION,DATEMAJ) VALUES (-1, 'Résidant',SYSDATE,SYSDATE);
INSERT INTO TYPEVISITE (TYPEVISITEID,TYPEVISITE,TRAVAIL,DATECREATION,DATEMAJ) VALUES (-3,'Travail',1,SYSDATE,SYSDATE);

INSERT INTO NATURE (NATUREID,LIBELLE,ABREGE,TVISITE,INTERDIT,DEBUTINTERDIT,FININTERDIT,DATECREATION,DATEMAJ) VALUES ('VPARDEFAUT','**********','*','0','0',SYSDATE-1,SYSDATE+36000,SYSDATE,SYSDATE);
INSERT INTO NATURE (NATUREID,LIBELLE,ABREGE,TVISITE,INTERDIT,DEBUTINTERDIT,FININTERDIT,DATECREATION,DATEMAJ) VALUES ('-1','SOCIETE EXTERIEURE','','0','0',SYSDATE-1,SYSDATE+36000,SYSDATE,SYSDATE);
INSERT INTO NATURE (NATUREID,LIBELLE,ABREGE,TVISITE,INTERDIT,DEBUTINTERDIT,FININTERDIT,DATECREATION,DATEMAJ) VALUES ('-2','RESIDANT','','0','0',SYSDATE-1,SYSDATE+36000,SYSDATE,SYSDATE);
INSERT INTO FONCTION (CODEFONCTION,LIBELLE,DATEMAJ,DATECREATION) VALUES (0,'**********',SYSDATE,SYSDATE);
INSERT INTO AMENAGEMENT (CODEAMENAGEMENT,LIBELLE,DATECREATION,DATEMAJ) VALUES ('VPARDEFAUT','STANDARD',SYSDATE,SYSDATE);

INSERT INTO CIVILITE (CODECIVILITE,CIVILITE,LIBELLECOURT,DATECREATION,DATEMAJ) VALUES (0,'','',SYSDATE,SYSDATE);
INSERT INTO CIVILITE (CODECIVILITE,CIVILITE,LIBELLECOURT,DATECREATION,DATEMAJ) VALUES (1,'Monsieur','M.',SYSDATE,SYSDATE);
INSERT INTO CIVILITE (CODECIVILITE,CIVILITE,LIBELLECOURT,DATECREATION,DATEMAJ) VALUES (2,'Madame','Mme',SYSDATE,SYSDATE);
INSERT INTO CIVILITE (CODECIVILITE,CIVILITE,LIBELLECOURT,DATECREATION,DATEMAJ) VALUES (3,'Mademoiselle','Mlle',SYSDATE,SYSDATE);

INSERT INTO EQUIPEMENTFIXE (CODEEQUIPEMENTFIXE,LIBELLE,DATECREATION,DATEMAJ) VALUES ('E1','RETROPROJECTEUR',SYSDATE,SYSDATE);

INSERT INTO PAYS (PAYSID,LIBELLE,NATIONALITE,INTERDIT,DEBUTINTERDIT,FININTERDIT,DATEMAJ,DATECREATION) VALUES ('VPARDEFAUT','FRANCE','FRANCAISE',0,SYSDATE-1,SYSDATE+36000,SYSDATE,SYSDATE);
INSERT INTO PLANS (PLANID,LIBELLE,DATECREATION,DATEMAJ) VALUES ('VPARDEFAUT','**********',SYSDATE,SYSDATE);
INSERT INTO SITE (SITEID,LIBELLE,IS_SECURED,PAYS,DATEMAJ,DATECREATION) VALUES ('VPARDEFAUT','**********',0,'FRANCE',SYSDATE,SYSDATE);
INSERT INTO STATUTRESERVATION (CODESTATUT,LIBELLE,COLOR,COLORNAME,CONFIRMATION,NBJOURAD,NBJOURAR,NBJOURDELAI,DATECREATION,DATEMAJ)
              VALUES ('VPARDEFAUT','CONFIRME',16711680,'Blue',0,0,0,0,SYSDATE,SYSDATE);
INSERT INTO TRANCHE (CODETRANCHE,LIBELLE,DATECREATION,DATEMAJ) VALUES ('VPARDEFAUT','9H00-10H00',SYSDATE,SYSDATE);
INSERT INTO TVA (CODETVA,LIBELLE,TAUXTVA,DATECREATION,DATEMAJ) VALUES ('VPARDEFAUT','TAXE SUR LA VALEUR AJOUTE','20',SYSDATE,SYSDATE);
INSERT INTO TYPERESERVATION (CODETYPERESERVATION,LIBELLE,DATEMAJ,DATECREATION) VALUES ('VPARDEFAUT','REUNION',SYSDATE,SYSDATE);
INSERT INTO TYPETARIF (CODETYPETARIF,LIBELLE,COEFICIENT,DATECREATION) VALUES ('VPARDEFAUT','PLEIN','1',SYSDATE);
INSERT INTO VILLE (CODEVILLE,CODEPOSTAL,VILLE,DATECREATION,DATEMAJ) VALUES ('VPARDEFAUT','75002','PARIS',SYSDATE,SYSDATE);
INSERT INTO BATIMENT (BATIMENTID,SITEID,LIBELLE,NOBAT,DATEMAJ,DATECREATION) VALUES ('VPARDEFAUT','VPARDEFAUT','**********','',SYSDATE,SYSDATE);
INSERT INTO ETAGES (ETAGEID,BATIMENTID,DATECREATION,DATEMAJ) VALUES ('VPARDEFAUT','VPARDEFAUT',SYSDATE,SYSDATE);
INSERT INTO BUREAUX (BUREAUID,ETAGEID,SORTORDER,BUREAU,DATECREATION,DATEMAJ) VALUES ('VPARDEFAUT','VPARDEFAUT',0,'**********',SYSDATE,SYSDATE);
INSERT INTO SOCIETE (SOCIETEID,ISRESIDANT,NOM,INTERDIT,DEBUTINTERDIT,FININTERDIT,DATEMAJ,DATECREATION) VALUES ('VPARDEFAUT',0,'**********',0,SYSDATE-1,SYSDATE+36000,SYSDATE,SYSDATE);
INSERT INTO SOCIETE (SOCIETEID,ISRESIDANT,NOM,INTERDIT,DEBUTINTERDIT,FININTERDIT,DATEMAJ,DATECREATION,PHONKEY) VALUES ('0',1,'**********',0,SYSDATE-1,SYSDATE+36000,SYSDATE,SYSDATE,'0');
INSERT INTO DEPARTEMENT (DEPTID,SOCIETEID,LIBELLE,DATECREATION,DATEMAJ) VALUES ('VPARDEFAUT','VPARDEFAUT','**********',SYSDATE,SYSDATE);
INSERT INTO SERVICE (SERVICEID,DEPTID,LIBELLE,DATECREATION,DATEMAJ) VALUES ('VPARDEFAUT','VPARDEFAUT','**********',SYSDATE,SYSDATE);

INSERT INTO MARQUE (CODEMARQUE,LIBELLE,DATECREATION,DATEMAJ) VALUES ('MA1','COLA',SYSDATE,SYSDATE);
INSERT INTO FAMILLE (CODEFAMILLE,LIBELLE,MARGE,DATECREATION,DATEMAJ) VALUES ('F1','PERSONNEL','1',SYSDATE,SYSDATE);
INSERT INTO SOUSFAMILLE (CODESOUSFAMILLE,CODEFAMILLE,SOUSFAMILLE,MARGE,DATECREATION,DATEMAJ) VALUES ('SF1','F1','CONFORT','1',SYSDATE,SYSDATE);
INSERT INTO ARTICLE (CODEARTICLE,CODEFAMILLE,CODESOUSFAMILLE,CODETVA,FULLNAME,LIBELLE,PRIXACHATHT,PRIXVENTEHT,PRIXVENTETTC,REFERENCE,TAUXTVA,DATEMAJ,DATECREATION)
	VALUES ('CA2','F1','SF1','TVA','BOISSON GAZEUSE','BOISSON','5','7','10','REF002','20',SYSDATE,SYSDATE);
INSERT INTO ARTICLEDEFAULT (CODEARTICLEDEFAULT,CODETYPEDEFAULT,CODEARTICLE,QUANTITE,SORTORDER,DATECREATION,DATEMAJ)
	VALUES ('CAD2','COD1','CA2','2','5',SYSDATE,SYSDATE);

INSERT INTO CFGPRODUIT (CODETVA,MARGE) VALUES ('VPARDEFAUT','1');

INSERT INTO CFGGSALLESPARAM (HEUREOUVERTURE,HEUREFERMETURE,TRANCHE,REFRESERVATION)
	VALUES (TO_DATE('10:00','HH24:MI'),TO_DATE('11:00','HH24:MI'),TO_DATE('01:00','HH24:MI'),'REF001');

INSERT INTO CFGDEFAULTAGENDA (CODECIVILITE) VALUES (0);

INSERT INTO CFGGSALLESDEFAULT (CODETYPERESERVATION,CODESTATUT,CODEAMMENAGEMENT,CODETYPETARIF,HEUREDEBUT,HEUREFIN,PREPARATIONDEFAUT,RANGEMENTDEFAUT)
	VALUES ('VPARDEFAUT','VPARDEFAUT','VPARDEFAUT','VPARDEFAUT',TO_DATE('09:00','HH24:MI'),TO_DATE('17:00','HH24:MI'),TO_DATE('00:10','HH24:MI'),TO_DATE('00:10','HH24:MI'));
INSERT INTO SALLE (SITEID,SOCIETEID,BATIMENTID,CODESALLE,LIBELLE,NOSALLE,SORTORDER,DATEMAJ,DATECREATION)
	VALUES ('VPARDEFAUT','VPARDEFAUT','VPARDEFAUT','001','SALLE JAUNE','01',1,SYSDATE,SYSDATE);
INSERT INTO AMENAGSALLE (CODESALLE,CODEAMENAGEMENT,DATEMAJ,DATECREATION) VALUES ('VPARDEFAUT','VPARDEFAUT',SYSDATE,SYSDATE);

INSERT INTO RESIDANTS (SOCIETEID,RESIDANTID,PLANID,BUREAUID,CODEFONCTION,SERVICEID,THEPASSWORD,THELOGIN,SITEID,BATIMENTID,ISRESIDENT,ISACTIF,INTERDIT,NATUREID,NATIONALITEID,DATEMAJ,DATECREATION,DEBUTINTERDIT,FININTERDIT,HABILITATIONVISITE,CODECIVILITE,CIVILITE,NOMPRENOM,NOM,PRENOM)
	VALUES ('VPARDEFAUT','VPARDEFAUT','VPARDEFAUT','VPARDEFAUT',0,'VPARDEFAUT','TAFFIN','TAFFIN','VPARDEFAUT','VPARDEFAUT',1,1,0,'VPARDEFAUT','VPARDEFAUT',SYSDATE,SYSDATE,SYSDATE,SYSDATE+(100*365),'1',1,'M.','RESIDANT INCONNU','RESIDANT','INCONNU');

INSERT INTO RESIDANTS (SOCIETEID,RESIDANTID,PLANID,BUREAUID,CODEFONCTION,SERVICEID,THEPASSWORD,THELOGIN,SITEID,BATIMENTID,ISRESIDENT,ISACTIF,INTERDIT,NATUREID,NATIONALITEID,DATEMAJ,DATECREATION,NOMPRENOM,NOM,PRENOM,DEBUTINTERDIT,FININTERDIT,HABILITATIONVISITE,CODECIVILITE,CIVILITE)
	VALUES ('VPARDEFAUT','123','VPARDEFAUT','VPARDEFAUT',0,'VPARDEFAUT','TAFFIN','TAFFIN','VPARDEFAUT','VPARDEFAUT',1,1,0,'VPARDEFAUT','VPARDEFAUT',SYSDATE,SYSDATE,'TAFFIN JEAN MARIE','TAFFIN','JEAN MARIE',SYSDATE,SYSDATE+(100*365),'1',1,'M.');

INSERT INTO RESIDANTS (SOCIETEID,RESIDANTID,PLANID,BUREAUID,CODEFONCTION,SERVICEID,THEPASSWORD,THELOGIN,SITEID,BATIMENTID,ISRESIDENT,ISACTIF,INTERDIT,NATUREID,NATIONALITEID,DATEMAJ,DATECREATION,NOMPRENOM,NOM,PRENOM,DEBUTINTERDIT,FININTERDIT,HABILITATIONVISITE,CODECIVILITE,CIVILITE)
	VALUES ('VPARDEFAUT','124','VPARDEFAUT','VPARDEFAUT',0,'VPARDEFAUT','TAFFIN','TAFFIN','VPARDEFAUT','VPARDEFAUT',1,1,0,'VPARDEFAUT','VPARDEFAUT',SYSDATE,SYSDATE,'ROLLANDEAU FRANCOIS','ROLLANDEAU','FRANCOIS',SYSDATE,SYSDATE+(100*365),'1',1,'M.');

INSERT INTO RESIDANTS (SOCIETEID,RESIDANTID,PLANID,BUREAUID,CODEFONCTION,SERVICEID,THEPASSWORD,THELOGIN,SITEID,BATIMENTID,ISRESIDENT,ISACTIF,INTERDIT,NATUREID,NATIONALITEID,DATEMAJ,DATECREATION,NOMPRENOM,NOM,PRENOM,DEBUTINTERDIT,FININTERDIT,HABILITATIONVISITE,CODECIVILITE,CIVILITE)
	VALUES ('VPARDEFAUT','456','VPARDEFAUT','VPARDEFAUT',0,'VPARDEFAUT','RESIDANT','RESIDANT','VPARDEFAUT','VPARDEFAUT',1,1,0,'VPARDEFAUT','VPARDEFAUT',SYSDATE,SYSDATE,'RESIDANT Parking','RESIDANT','Parking',SYSDATE,SYSDATE+(100*365),'1',1,'M.');


INSERT INTO GRPUSER (GRPUSERID, LIBELLE, NIVEAU, STATUT, SURRESERVATION, RESAPERIODIQUE, ACCESDRAGDROP, PLANNING, RESA, PRESTA, DATECREATION, DATEMAJ, STATUTCHECK)
	VALUES ('ADMINISTRATEUR','ADMINISTRATEUR','2','VPARDEFAUT','1','1','1','11','000000111011','10',SYSDATE,SYSDATE,1);
INSERT INTO GRPUSER (GRPUSERID, LIBELLE, NIVEAU, STATUT, SURRESERVATION, RESAPERIODIQUE, ACCESDRAGDROP, PLANNING, RESA, PRESTA, DATECREATION, DATEMAJ, STATUTCHECK)
	VALUES ('VPARDEFAUT','UTILISATEUR','1','VPARDEFAUT','0','0','0','10','111000000011','00',SYSDATE,SYSDATE,0);
INSERT INTO GRPSALLE  (GRPSALLEID, LIBELLE, HEUREDEBUT, HEUREFIN, OPENPRERESA, CLOSEPRERESA, RESA, DATECREATION, DATEMAJ,SITEID)
	VALUES ('EVERYONE','EVERYONE',TO_DATE('00:00','HH24:MI'),TO_DATE('00:00','HH24:MI'),0,0,'1',SYSDATE,SYSDATE,'ALL');

INSERT INTO USERS (USERID, CIVILITEID, FIRSTNAME, USERTYPEID, GVACCESS, EXTERNALID, FULLNAME,  PROFIL_ID_ORGA, PROFIL_ID_INTER,PROFIL_SURBOOKING,THELOGIN, THEPASSWORD, USERTYPE, DATEMAJ, DATECREATION,GRPUSERID,ENABLED,GSACCESS)
	VALUES ('GESROOM',0,'ADMINISTRATEUR','Administrateur',78847,'VPARDEFAUT','ADMINISTRATEUR','VPARDEFAUT','VPARDEFAUT','0','ADM','ADM',1,SYSDATE,SYSDATE,'ADMINISTRATEUR',1,1);


INSERT INTO USERS (USERTYPEID,GVACCESS,USERID,CIVILITEID,FIRSTNAME,FULLNAME,THELOGIN,THEPASSWORD,DATEMAJ,DATECREATION,SITE,SITEID,TYPEUSERID,ID_DROITSTAXI,ID_DROITSTELEM,ENABLED)
	VALUES ('ADM','20595','VPARDEFAUT',0,'TAFFIN','TAFFIN','TAFFIN','2206',SYSDATE,SYSDATE,'**********','VPARDEFAUT',-1,1,-1,1);

INSERT INTO USERS (USERTYPEID,GVACCESS,USERID,CIVILITEID,FIRSTNAME,FULLNAME,THELOGIN,THEPASSWORD,DATEMAJ,DATECREATION,SITE,SITEID,TYPEUSERID,ID_DROITSTAXI,ID_DROITSTELEM,ENABLED)
	VALUES ('ADM','20595','123',0,'TELEMAQUE','TELEMAQUE','TELEMAQUE','TELEMAQUE',SYSDATE,SYSDATE,'**********','VPARDEFAUT',-1,1,-2,1);

INSERT INTO PARAMETRES (PREENREG,SECURITE,I_PLAN,IMPRESSION,DATESORTIVI,SORTIVI,PURGEVP,APPETEL,MONOSOC,MODULE,GESPHOTO,TRCLUNIK,TYPEANNU,IMPORTAUTO,GESTCASIER,NBESSAIS,DATECREATION,DATEMAJ,INFOBULLES,REFIMPORTATION)
	VALUES (0,0,0,0,SYSDATE,1,1,0,0,0,0,0,0,0,0,10,SYSDATE,SYSDATE,0,'1');

INSERT INTO IMPUTATION_TYPE (IMPUTATION_TYPEID,LIBELLE) VALUES ('VPARDEFAUT','Code Imputation');
INSERT INTO IMPUTATION_TYPE (IMPUTATION_TYPEID,LIBELLE) VALUES ('1','Code projet');

UPDATE ARTICLE SET GESTION=0;

INSERT INTO STATUTRESERVATION_ETAT VALUES (0,'Apres demande de réservation',SYSDATE,SYSDATE,NULL);
INSERT INTO STATUTRESERVATION_ETAT VALUES (1,'avant réunion',SYSDATE,SYSDATE,NULL);

INSERT INTO STATUTRESERVATION_SET VALUES (0,'Pas de relance',SYSDATE,SYSDATE,NULL);
INSERT INTO STATUTRESERVATION_SET VALUES (1,'Relance',SYSDATE,SYSDATE,NULL);
INSERT INTO STATUTRESERVATION_SET VALUES (2,'Confirmer',SYSDATE,SYSDATE,NULL);

INSERT INTO IMPUTATION (IMPUTATIONID, LIBELLE, LIBELLE2, IMPUTATION_TYPEID, DATECREATION, DATEMAJ) VALUES ('VPARDEFAUT','', '*****', 'VPARDEFAUT', SYSDATE, SYSDATE);

UPDATE STATUTRESERVATION set confirmation=0, NBJOURAD=0,NBJOURDELAI=0;

UPDATE CFGGSALLESPARAM SET RESA_ORDRE_SALLE=0,RESA_PRESTA_STYLE=0,FILTRE_ORDRE_TRI=0;

INSERT INTO ZONE (ZONEID, ZONENOM, ZONERESPONSABLE, DATEMAJ, DATECREATION) VALUES ('VPARDEFAUT','TOUTES ZONES','**********',SYSDATE, SYSDATE);

-- 2004_02_06
INSERT INTO TYPE_MISSION (TYPE_MISSIONID, LIBELLE, DATEMAJ, DATECREATION, DATESYNCHRO) VALUES (-1,'PRISE DE POSTE',SYSDATE,SYSDATE,SYSDATE);
INSERT INTO TYPE_MISSION (TYPE_MISSIONID, LIBELLE, DATEMAJ, DATECREATION, DATESYNCHRO) VALUES (-2,'FIN DE POSTE',SYSDATE,SYSDATE,SYSDATE);
INSERT INTO TYPE_MISSION (TYPE_MISSIONID, LIBELLE, DATEMAJ, DATECREATION, DATESYNCHRO) VALUES (-3,'SANS FIN',SYSDATE,SYSDATE,SYSDATE);
INSERT INTO TYPE_MISSION (TYPE_MISSIONID, LIBELLE, DATEMAJ, DATECREATION, DATESYNCHRO) VALUES (-4,'MISSION',SYSDATE,SYSDATE,SYSDATE);


INSERT INTO VSERVICE (VSERVICEID, LIBELLE, DATEMAJ, DATECREATION, DATESYNCHRO) VALUES (0,'**********',SYSDATE,SYSDATE,SYSDATE);
INSERT INTO OCONSIGNE (OCONSIGNEID,LIBELLE) VALUES (0,'**********');
INSERT INTO ODROIT (ODROITID,LIBELLE,OMACCESS,DATEMAJ,DATECREATION) VALUES (1,'ADMINISTRATEUR',8191,SYSDATE,SYSDATE);
INSERT INTO ODROIT (ODROITID,LIBELLE,OMACCESS,DATEMAJ,DATECREATION) VALUES (2,'AGENT',513,SYSDATE,SYSDATE);
INSERT INTO QUALIF (QUALIFID, LIBELLE, DATEMAJ, DATECREATION, DATESYNCHRO) VALUES (0,'**********',SYSDATE,SYSDATE,SYSDATE);
INSERT INTO RAPPORT (RAPPORTID, LIBELLE, NOMTABLE, DETAILS, AUTEURID, DATEMAJ, DATECREATION, DATESYNCHRO) VALUES (0,'**********','*','*',0,SYSDATE,SYSDATE,SYSDATE);
--INSERT INTO POSTE (POSTEID,LIBELLE,DATECREATION,DATEMAJ) VALUES (0,'**********',SYSDATE,SYSDATE);
INSERT INTO POSTE (POSTEID,LIBELLE,REP_LOCAL,DATECREATION,DATEMAJ) VALUES (-1,'SYSTEME','SYSTEME',SYSDATE,SYSDATE);
INSERT INTO PERSONNEL (PERSONNELID,THELOGIN,THEPASSWORD,NOM,PRENOM,DATECREATION,DATEMAJ) VALUES (-1,'Ommnigarde','OM','***','***',SYSDATE,SYSDATE);
INSERT INTO PERSONNEL (PERSONNELID,THEPASSWORD,THELOGIN,NOM,PRENOM,DATE_NAISSANCE,DATE_EMBAUCHE,DATE_ARRIVEE,DEBUT_VALIDITE,FIN_VALIDITE,QUALIFID,CODEFONCTION,MEDICAL_LAST,MEDICAL_NEXT,ODROITID,SITEID,DATEMAJ,DATECREATION) VALUES (1,2206,'TAFFIN','TAFFIN','Jean-marie','01/01/1950','01/01/1950','01/01/1950','01/01/1950','01/01/1950',0,0,'01/01/1950','01/01/1950',1,'VPARDEFAUT',SYSDATE,SYSDATE);

INSERT INTO EVENEMENT (EVENEMENTID,LIBELLE,RAPPORTID,CONSIGNEID,ISRAPPORT,DATEMAJ,DATECREATION,DATESYNCHRO) VALUES (1,'INCIDENT',0,0,0,SYSDATE,SYSDATE,SYSDATE);
INSERT INTO EVENEMENT (EVENEMENTID,LIBELLE,RAPPORTID,CONSIGNEID,ISRAPPORT,DATEMAJ,DATECREATION,DATESYNCHRO) VALUES (-1,'PRISE DE POSTE',0,0,0,SYSDATE,SYSDATE,SYSDATE);
INSERT INTO EVENEMENT (EVENEMENTID,LIBELLE,RAPPORTID,CONSIGNEID,ISRAPPORT,DATEMAJ,DATECREATION,DATESYNCHRO) VALUES (-2,'FIN DE POSTE',0,0,0,SYSDATE,SYSDATE,SYSDATE);
INSERT INTO EVENEMENT (EVENEMENTID,LIBELLE,RAPPORTID,CONSIGNEID,ISRAPPORT,DATEMAJ,DATECREATION,DATESYNCHRO) VALUES (-3,'MISSION',0,0,0,SYSDATE,SYSDATE,SYSDATE);
INSERT INTO EVENEMENT (EVENEMENTID,LIBELLE,RAPPORTID,CONSIGNEID,ISRAPPORT,DATEMAJ,DATECREATION,DATESYNCHRO) VALUES (-4,'MISSION RETARD',0,0,0,SYSDATE,SYSDATE,SYSDATE);
INSERT INTO EVENEMENT (EVENEMENTID,LIBELLE,RAPPORTID,CONSIGNEID,ISRAPPORT,DATEMAJ,DATECREATION,DATESYNCHRO) VALUES (-5,'OUVERTURE APPLI',0,0,0,SYSDATE,SYSDATE,SYSDATE);
INSERT INTO EVENEMENT (EVENEMENTID,LIBELLE,RAPPORTID,CONSIGNEID,ISRAPPORT,DATEMAJ,DATECREATION,DATESYNCHRO) VALUES (-6,'FERMETURE APPLI',0,0,0,SYSDATE,SYSDATE,SYSDATE);
INSERT INTO EVENEMENT (EVENEMENTID,LIBELLE,RAPPORTID,CONSIGNEID,ISRAPPORT,DATEMAJ,DATECREATION,DATESYNCHRO) VALUES (-7,'CONNEXION',0,0,0,SYSDATE,SYSDATE,SYSDATE);
INSERT INTO EVENEMENT (EVENEMENTID,LIBELLE,RAPPORTID,CONSIGNEID,ISRAPPORT,DATEMAJ,DATECREATION,DATESYNCHRO) VALUES (-8,'MESSAGE PONCTUEL',0,0,0,SYSDATE,SYSDATE,SYSDATE);
INSERT INTO EVENEMENT (EVENEMENTID,LIBELLE,RAPPORTID,CONSIGNEID,ISRAPPORT,DATEMAJ,DATECREATION,DATESYNCHRO) VALUES (-9,'MISSION SUPPRIMEE',0,0,0,SYSDATE,SYSDATE,SYSDATE);
INSERT INTO EVENEMENT (EVENEMENTID,LIBELLE,RAPPORTID,CONSIGNEID,ISRAPPORT,DATEMAJ,DATECREATION,DATESYNCHRO) VALUES (-10,'MISSION SUSPENDUE',0,0,0,SYSDATE,SYSDATE,SYSDATE);
INSERT INTO EVENEMENT (EVENEMENTID,LIBELLE,RAPPORTID,CONSIGNEID,ISRAPPORT,DATEMAJ,DATECREATION,DATESYNCHRO) VALUES (-11,'AGENT',0,0,0,SYSDATE,SYSDATE,SYSDATE);
INSERT INTO EVENEMENT (EVENEMENTID,LIBELLE,RAPPORTID,CONSIGNEID,ISRAPPORT,DATEMAJ,DATECREATION,DATESYNCHRO) VALUES (-12,'MOUVEMENT',0,0,0,SYSDATE,SYSDATE,SYSDATE);
INSERT INTO EVENEMENT (EVENEMENTID,LIBELLE,RAPPORTID,CONSIGNEID,ISRAPPORT,DATEMAJ,DATECREATION,DATESYNCHRO) VALUES (-13,'PROBLEME MATERIEL',0,0,0,SYSDATE,SYSDATE,SYSDATE);
INSERT INTO EVENEMENT (EVENEMENTID,LIBELLE,RAPPORTID,CONSIGNEID,ISRAPPORT,DATEMAJ,DATECREATION,DATESYNCHRO) VALUES (-14,'MC EMAIL AUTOMATIQUE',0,0,0,SYSDATE,SYSDATE,SYSDATE);
INSERT INTO EVENEMENT (EVENEMENTID,LIBELLE,RAPPORTID,CONSIGNEID,ISRAPPORT,DATEMAJ,DATECREATION,DATESYNCHRO) VALUES (-15,'ALARME',0,0,0,SYSDATE,SYSDATE,SYSDATE);
INSERT INTO EVENEMENT (EVENEMENTID,LIBELLE,RAPPORTID,CONSIGNEID,ISRAPPORT,DATEMAJ,DATECREATION,DATESYNCHRO) VALUES (-16,'VISITEUR NON PREVU',0,0,0,SYSDATE,SYSDATE,SYSDATE);
INSERT INTO EVENEMENT (EVENEMENTID,LIBELLE,RAPPORTID,CONSIGNEID,ISRAPPORT,DATEMAJ,DATECREATION,DATESYNCHRO) VALUES (-17,'COLIS NON PREVU',0,0,0,SYSDATE,SYSDATE,SYSDATE);
INSERT INTO EVENEMENT (EVENEMENTID,LIBELLE,RAPPORTID,CONSIGNEID,ISRAPPORT,DATEMAJ,DATECREATION,DATESYNCHRO) VALUES (-18,'OBJET PERDU',0,0,0,SYSDATE,SYSDATE,SYSDATE);
INSERT INTO EVENEMENT (EVENEMENTID,LIBELLE,RAPPORTID,CONSIGNEID,ISRAPPORT,DATEMAJ,DATECREATION,DATESYNCHRO) VALUES (-19,'CLE EN RETARD',0,0,0,SYSDATE,SYSDATE,SYSDATE);
INSERT INTO EVENEMENT (EVENEMENTID,LIBELLE,RAPPORTID,CONSIGNEID,ISRAPPORT,DATEMAJ,DATECREATION,GRPEVENEMENTID,DATESYNCHRO) VALUES (-20,'CHECKLIST',0,0,0,SYSDATE,SYSDATE,-1,SYSDATE);

INSERT INTO JOUR (JOURID, LIBELLE, TYPE_JOUR, CL, DATEOFWEEK, DEBUT_VALIDITE, FIN_VALIDITE, DATEMAJ, DATECREATION) VALUES (1,'DIMANCHE','DIMANCHE',7,1,SYSDATE,'01/01/2110',SYSDATE,SYSDATE);
INSERT INTO JOUR (JOURID, LIBELLE, TYPE_JOUR, CL, DATEOFWEEK, DEBUT_VALIDITE, FIN_VALIDITE, DATEMAJ, DATECREATION) VALUES (2,'LUNDI','LUNDI',1,2,SYSDATE,'01/01/2110',SYSDATE,SYSDATE);
INSERT INTO JOUR (JOURID, LIBELLE, TYPE_JOUR, CL, DATEOFWEEK, DEBUT_VALIDITE, FIN_VALIDITE, DATEMAJ, DATECREATION) VALUES (3,'MARDI','MARDI',2,3,SYSDATE,'01/01/2110',SYSDATE,SYSDATE);
INSERT INTO JOUR (JOURID, LIBELLE, TYPE_JOUR, CL, DATEOFWEEK, DEBUT_VALIDITE, FIN_VALIDITE, DATEMAJ, DATECREATION) VALUES (4,'MERCREDI','MERCREDI',3,4,SYSDATE,'01/01/2110',SYSDATE,SYSDATE);
INSERT INTO JOUR (JOURID, LIBELLE, TYPE_JOUR, CL, DATEOFWEEK, DEBUT_VALIDITE, FIN_VALIDITE, DATEMAJ, DATECREATION) VALUES (5,'JEUDI','JEUDI',4,5,SYSDATE,'01/01/2110',SYSDATE,SYSDATE);
INSERT INTO JOUR (JOURID, LIBELLE, TYPE_JOUR, CL, DATEOFWEEK, DEBUT_VALIDITE, FIN_VALIDITE, DATEMAJ, DATECREATION) VALUES (6,'VENDREDI','VENDREDI',5,6,SYSDATE,'01/01/2110',SYSDATE,SYSDATE);
INSERT INTO JOUR (JOURID, LIBELLE, TYPE_JOUR, CL, DATEOFWEEK, DEBUT_VALIDITE, FIN_VALIDITE, DATEMAJ, DATECREATION) VALUES (7,'SAMEDI','SAMEDI',6,7,SYSDATE,'01/01/2110',SYSDATE,SYSDATE);

INSERT INTO EVENEMENT_SITE (SELECT EVENEMENTID,'VPARDEFAUT' AS SITEID FROM EVENEMENT WHERE EVENEMENTID >0);

INSERT INTO CONSTEMP_SITE (CONSIGNETEMPID,SITEID) (SELECT CONSIGNETEMPID,SITEID FROM CONSIGNETEMP);
INSERT INTO CONSTEMP_POSTE (CONSIGNETEMPID,POSTEID) (SELECT CONSIGNETEMPID,POSTEID FROM CONSIGNETEMP);
INSERT INTO CONSTEMP_QUALIF (CONSIGNETEMPID,QUALIFID) (SELECT CONSIGNETEMPID,QUALIFID FROM CONSIGNETEMP);

INSERT INTO ADRESSE (ADRESSEID,TYPEADRESSEID,SOCIETE,NOM,DATECREATION,DATEMAJ) VALUES ('VPARDEFAUT',0,'********','********',SYSDATE,SYSDATE);

INSERT INTO GUICHET (GUICHETID,SITEID,GUICHET,BOITE,DATECREATION,DATEMAJ) VALUES ('VPARDEFAUT','VPARDEFAUT','Administration','B',SYSDATE,SYSDATE);

INSERT INTO INTERLOCUTEUR (SOCIETEID,INTERLOCUTEURID,CODECIVILITE,CODEFONCTION,PAYS,CIVILITE,NOMPRENOM,NOM,NOMJEUNEFILLE,PRENOM,
FONCTION,TELEPHONE,EMAIL,GSM,FAX,IMMATRICULATION,INTERDIT,DEBUTINTERDIT,FININTERDIT,NATUREID,NATIONALITEID,DATEMAJ,DATECREATION,SOCIETE,DATENAISSANCE,FINVALIDITEAUTO,PHONKEY)
VALUES
('VPARDEFAUT','2l6tAq4h207',1,0,'FRANCE','Mr','VISITEUR','VISITEUR','','','**********','01 25 46 85 92','','06 13 25 46 95',
'','','0',SYSDATE-1,SYSDATE+100*365,'VPARDEFAUT','VPARDEFAUT',SYSDATE,SYSDATE,'**********','05/08/1960',SYSDATE+365,1);

INSERT INTO INTERLOCUTEUR (SOCIETEID,INTERLOCUTEURID,CODECIVILITE,CODEFONCTION,PAYS,CIVILITE,NOMPRENOM,NOM,NOMJEUNEFILLE,PRENOM,
FONCTION,TELEPHONE,EMAIL,GSM,FAX,IMMATRICULATION,INTERDIT,DEBUTINTERDIT,FININTERDIT,NATUREID,NATIONALITEID,DATEMAJ,DATECREATION,SOCIETE,DATENAISSANCE,FINVALIDITEAUTO,PHONKEY)
VALUES
('VPARDEFAUT','123',1,0,'FRANCE','Mr','VISITEUR Parking','VISITEUR','','Parking','**********','01 25 46 85 92','','06 13 25 46 95',
'','','0',SYSDATE-1,SYSDATE+100*365,'VPARDEFAUT','VPARDEFAUT',SYSDATE,SYSDATE,'**********','05/08/1960',SYSDATE+365,1);

INSERT INTO INTERLOCUTEUR (SOCIETEID,INTERLOCUTEURID,CODECIVILITE,CODEFONCTION,PAYS,CIVILITE,NOMPRENOM,NOM,NOMJEUNEFILLE,PRENOM,
FONCTION,TELEPHONE,EMAIL,GSM,FAX,IMMATRICULATION,INTERDIT,DEBUTINTERDIT,FININTERDIT,NATUREID,NATIONALITEID,DATEMAJ,DATECREATION,SOCIETE,DATENAISSANCE,FINVALIDITEAUTO,PHONKEY)
VALUES
('VPARDEFAUT','258964',1,0,'FRANCE','Mr','DELEGUE','DELEGUE','','','**********','01 25 46 85 92','','06 13 25 46 95',
'','','0',SYSDATE-1,SYSDATE+100*365,'VPARDEFAUT','VPARDEFAUT',SYSDATE,SYSDATE,'**********','05/08/1960',SYSDATE+365,2);


UPDATE BADGES SET OBSERVATION='';


INSERT INTO TQ_COMMUNE (NOM_IMG_DEF,HAUTEUR,LARGEUR,PERMIS_TRAVAIL,PARAM_ALTAIR,TITRE,BDG_FREE1,BDG_FREE2,BDG_FREE3,BDG_FREE4,BDG_FREE5,BDG_FREE6,BDG_FREE7,BDG_FREE8,BDG_FREE9,PLANS_FREE1,PLANS_FREE2,PLANS_FREE3,PLANS_FREE4,PLANS_FREE5,PLANS_FREE6,PLANS_FREE7,PLANS_FREE8,PLANS_FREE9) VALUES ('capture_webcam_telemaque2.bmp',198,150,0,0,'Telemaque C/S','GUICHET','FINPREVU','NUMEROVISITE','NUMEROBADGE','PIECE','HEUREVISIJOUR','IMMATRICULATION','TELR','BUREAUR','CIVILITEV','CIVILITER','SITER','BATIMENT','ETAGE','BUREAUR','PLANLIBELLE','SERVICER','TELR');
INSERT INTO TQ_POSTE (NOM_POSTE,NB_CAR_RECHERCHE,DELAI_RECHERCHE,SEPARATEUR,CHAMP1,CHAMP2,CHAMP3,CHAMP4,CHAMP5,CHAMP6,CHAMP7,CHAMP8,CHAMP9,POS_CHAMP1,POS_CHAMP2,POS_CHAMP3,POS_CHAMP4,POS_CHAMP5,POS_CHAMP6,POS_CHAMP7,POS_CHAMP8,POS_CHAMP9,CRITERE_IMPORT_CHAMP,BLOCAGE_HDEBUT_VISITE,RESID_CTRL_HORAIRE_MSG,RESID_CTRL_HORAIRE_VERROU,RESID_HORAIRE_VERROU,FERMETURE_FENETRE_APRES_BDG,HISTORIQUE,MODIF_CHAMPS_OBS,MSG_ALERTEXJOUR_AVANTJ,MSG_CONFIR_ES,MSG_INFOR_FORMATIONS_PERIMEES,AFFICHAGE_DATE_SI_STATUT_LONG,BLOCAGE_SI_FORM_PERIMEE,SELECT_MODEL_BDG,SELECT_IMPR_BDG,ELARGIR_PAR_DEFAUT,TRACAGE,FICHIER_TRACE,ENVOI_BDG_MANUEL,ENVOI_BDG_AUTO,GENERATION_BDG,DEBUT_CODE,MILIEU_CHAMP,MILIEU_FORMAT,FIN_CODE,MODE_ES_VIS_RES,VISITEUR_CTRL_PLUS) VALUES ('VPARDEFAUT',1,700,'{Tab}','Civ','Nom','Prenom','Societe','Fonction','Nom jeune fille','Date naissance','Lieu naissance','Nationalite',1,2,3,4,5,6,7,8,9,'000001110',0,1,0,0,1,0,0,10,0,0,0,0,0,0,0,0,'Trace.log',1,0,1,'V','NUMEROVISITE','NUMBER/6','0',0,0);


INSERT INTO TYPEUSER (USERID,LIBELLE,DATECREATION,DATEMAJ) VALUES (-1,'ADM',SYSDATE,SYSDATE);
INSERT INTO TYPEUSER (USERID,LIBELLE,DATECREATION,DATEMAJ) VALUES (-2,'ACCUEIL',SYSDATE,SYSDATE);
INSERT INTO TYPEUSER (USERID,LIBELLE,DATECREATION,DATEMAJ) VALUES (-3,'TECH',SYSDATE,SYSDATE);
INSERT INTO TYPEUSER (USERID,LIBELLE,DATECREATION,DATEMAJ) VALUES (-4,'PARKING',SYSDATE,SYSDATE);

UPDATE TQ_COMMUNE SET VALIDATION_RESID='0,1';
UPDATE TQ_COMMUNE SET MODIF_VISITEUR_PREENREG=0,MODIF_VISITEUR_ENCOURS=0,MODIF_VISITEUR_TERMINE=0;

--Pour la hauteur et largeur soit 198/150 ou 250/198

INSERT INTO ETATAPP (ETATID,ETATNOM,VISIBLE,APP,DATECREATION,DATEMAJ) VALUES ('ETAT_ETRANGERS','ListeEtranger',1,'TQ',SYSDATE,SYSDATE);
INSERT INTO ETATAPP (ETATID,ETATNOM,VISIBLE,APP,DATECREATION,DATEMAJ) VALUES ('BLACKLISTEVIS','BlackListeVis',1,'TQ',SYSDATE,SYSDATE);
INSERT INTO ETATAPP (ETATID,ETATNOM,VISIBLE,APP,DATECREATION,DATEMAJ) VALUES ('BLACKLISTERES','BlackListeRes',1,'TQ',SYSDATE,SYSDATE);
INSERT INTO ETATAPP (ETATID,ETATNOM,VISIBLE,APP,DATECREATION,DATEMAJ) VALUES ('ETAT_VISITEUR_PAYS','NbVisiteursParPays',1,'TQ',SYSDATE,SYSDATE);
INSERT INTO ETATAPP (ETATID,ETATNOM,VISIBLE,APP,DATECREATION,DATEMAJ) VALUES ('ETAT_VISITE_DETAIL','VisiteDetailVisiteur',1,'TQ',SYSDATE,SYSDATE);
INSERT INTO ETATAPP (ETATID,ETATNOM,VISIBLE,APP,DATECREATION,DATEMAJ) VALUES ('NBBDGIMPRRES','NbBdgImprRes',1,'TQ',SYSDATE,SYSDATE);
INSERT INTO ETATAPP (ETATID,ETATNOM,VISIBLE,APP,DATECREATION,DATEMAJ) VALUES ('LISTE_PHR_PHS','PHR_PHS',1,'TQ',SYSDATE,SYSDATE);
INSERT INTO ETATAPP (ETATID,ETATNOM,VISIBLE,APP,DATECREATION,DATEMAJ) VALUES ('LISTE_ENQUETES','Enquete',1,'TQ',SYSDATE,SYSDATE);
INSERT INTO ETATAPP (ETATID,ETATNOM,VISIBLE,APP,DATECREATION,DATEMAJ) VALUES ('LISTE_PASSAGE_SELF','Repas',1,'TQ',SYSDATE,SYSDATE);
INSERT INTO ETATAPP (ETATID,ETATNOM,VISIBLE,APP,DATECREATION,DATEMAJ) VALUES ('ETAT_ETRANGERS_DETAILS','ListeEtrangerDetails',1,'TQ',SYSDATE,SYSDATE);
INSERT INTO ETATAPP (ETATID,ETATNOM,VISIBLE,APP,DATECREATION,DATEMAJ) VALUES ('STATISTIQUE','JVisite',1,'TQ_NonVisible',SYSDATE,SYSDATE);
INSERT INTO ETATAPP (ETATID,ETATNOM,VISIBLE,APP,DATECREATION,DATEMAJ) VALUES ('STATISTIQUE_OBS','JVisiteObs',1,'TQ_NonVisible',SYSDATE,SYSDATE);
INSERT INTO ETATAPP (ETATID,ETATNOM,VISIBLE,APP,DATECREATION,DATEMAJ) VALUES ('PRE_ENREG','PreEnreg',1,'TQ_NonVisible',SYSDATE,SYSDATE);
INSERT INTO ETATAPP (ETATID, ETATNOM, VISIBLE,REQUETE,FILTRE,APP,DATECREATION,DATEMAJ) VALUES ('VISITES_DEBLOQUEES', 'VisitesDebloquees', 1, '', '', 'TQ', SYSDATE, SYSDATE);
INSERT INTO ETATAPP (ETATID,ETATNOM,VISIBLE,REQUETE,FILTRE,APP,DATECREATION,DATEMAJ) VALUES ('ETAT_ESVISITE_LOG', 'ListePassagesES', 1, '', '', 'TQ', SYSDATE, SYSDATE);

-- INSERTION DES NOUVEAU ETAT GESROOM
INSERT INTO CFGETAT (CFGETATID,ETATNOM,VISIBLE,REQUETE,FILTRE,DATECREATION,DATEMAJ)
	VALUES ('Reservationdessalles1','Reservation des salles',1,'EtatReservationSalleAccueil','',SYSDATE,SYSDATE);
INSERT INTO CFGETAT (CFGETATID,ETATNOM,VISIBLE,REQUETE,FILTRE,DATECREATION,DATEMAJ)
	VALUES ('Equipementdessalles1','Equipement des salles',1,'EtatEquipementdessalles','AND F.LIBELLE<>''ALIMENTAIRE''',SYSDATE,SYSDATE);
INSERT INTO CFGETAT (CFGETATID,ETATNOM,VISIBLE,REQUETE,FILTRE,DATECREATION,DATEMAJ)
	VALUES ('Restauration1','Restauration',1,'EtatRestaurations','AND F.LIBELLE=''ALIMENTAIRE'' AND UPPER(A.LIBELLE)<>UPPER(''jetons'') AND UPPER(A.LIBELLE)<>UPPER(''Places pour repas'')',SYSDATE,SYSDATE);
INSERT INTO CFGETAT (CFGETATID,ETATNOM,VISIBLE,REQUETE,FILTRE,DATECREATION,DATEMAJ)
	VALUES ('Reservations1','Reservations',1,'EtatReservationListe','',SYSDATE,SYSDATE);
INSERT INTO CFGETAT (CFGETATID,ETATNOM,VISIBLE,REQUETE,FILTRE,DATECREATION,DATEMAJ)
	VALUES ('Places1','Places',1,'EtatPlaces','AND F.LIBELLE=''ALIMENTAIRE'' AND SF.SOUSFAMILLE=''PLACES''',SYSDATE,SYSDATE);
INSERT INTO CFGETAT (CFGETATID,ETATNOM,VISIBLE,REQUETE,FILTRE,DATECREATION,DATEMAJ)
	VALUES ('Jetons1','Jetons',1,'EtatJetons','AND F.LIBELLE=''ALIMENTAIRE'' AND UPPER(A.LIBELLE)=UPPER(''jetons'')',SYSDATE,SYSDATE);
INSERT INTO CFGETAT (CFGETATID,ETATNOM,VISIBLE,REQUETE,FILTRE,DATECREATION,DATEMAJ)
	VALUES ('Facturation1','Facturation Matériels et Prestations',1,'EtatFacturationMaterielEtPrestation','AND ( F.LIBELLE=''MATERIEL TECHNIQUE'' OR F.LIBELLE=''PRESTATIONS TECHNIQUES'')',SYSDATE,SYSDATE);
INSERT INTO CFGETAT (CFGETATID,ETATNOM,VISIBLE,REQUETE,FILTRE,DATECREATION,DATEMAJ)
	VALUES ('FacturationSalles1','Facturation Salles',1,'EtatFacturationSalle','',SYSDATE,SYSDATE);
INSERT INTO CFGETAT (CFGETATID,ETATNOM,VISIBLE,REQUETE,FILTRE,DATECREATION,DATEMAJ)
	VALUES ('Restaurationsur7j1','Restauration sur 7j',1,'EtatRestaurationSurXJours','AND F.LIBELLE=''RESTAURATION''',SYSDATE,SYSDATE);
INSERT INTO CFGETAT (CFGETATID,ETATNOM,VISIBLE,REQUETE,FILTRE,DATECREATION,DATEMAJ)
	VALUES ('Reservation1','Reservation des salles',1,'EtatReservationTypeReunion','',SYSDATE,SYSDATE);
INSERT INTO CFGETAT (CFGETATID,ETATNOM,VISIBLE,REQUETE,FILTRE,DATECREATION,DATEMAJ)
	VALUES ('Equipementdessalles2','Equipement des salles',1,'EtatEquipementdessallesTypeReunion','AND F.LIBELLE<>''RESTAURATION''',SYSDATE,SYSDATE);
INSERT INTO CFGETAT (CFGETATID,ETATNOM,VISIBLE,REQUETE,FILTRE,DATECREATION,DATEMAJ)
	VALUES ('Prvisionpause1','Prévision pauses',1,'EtatPrevisionPauses','AND F.LIBELLE=''RESTAURATION'' AND SF.SOUSFAMILLE=''PAUSES''',SYSDATE,SYSDATE);
INSERT INTO CFGETAT (CFGETATID,ETATNOM,VISIBLE,REQUETE,FILTRE,DATECREATION,DATEMAJ)
	VALUES ('Bonderestauration1','Bon de restauration',1,'EtatBonDeRestauration','AND F.LIBELLE=''RESTAURATION'' AND SF.SOUSFAMILLE=''REPAS''',SYSDATE,SYSDATE);
INSERT INTO CFGETAT (CFGETATID,ETATNOM,VISIBLE,REQUETE,FILTRE,DATECREATION,DATEMAJ)
	VALUES ('Salledereunionavecprestationrestaurant1','Salle de reunion avec prestation restaurant',1,'EtatReservationSallePrestationRestaurant','AND F.LIBELLE=''RESTAURATION'' ',SYSDATE,SYSDATE);
INSERT INTO CFGETAT (CFGETATID,ETATNOM,VISIBLE,REQUETE,FILTRE,DATECREATION,DATEMAJ)
	VALUES ('gsrm011','Réservation par tranche horaire',1,'','',SYSDATE,SYSDATE);
INSERT INTO CFGETAT (CFGETATID,ETATNOM,VISIBLE,REQUETE,FILTRE,DATECREATION,DATEMAJ)
	VALUES ('gsrm021','Taux d''occupation par société',1,'','',SYSDATE,SYSDATE);
INSERT INTO CFGETAT (CFGETATID,ETATNOM,VISIBLE,REQUETE,FILTRE,DATECREATION,DATEMAJ)
	VALUES ('gsrm031','Liste des réservations par société',1,'','',SYSDATE,SYSDATE);

UPDATE PARAMETRES SET SORTIFINVI=0;
UPDATE RESIDANTS SET BOITEPOSTALE='0';
INSERT INTO ROLE_AUTRES (USERID,SITE,SOC_RES,DIRECTIONS,PAYS,UTILISATEURS,TYPEUSER,PROFILUSER,MODIFAFF,DATECREATION,DATEMAJ) VALUES (-1,1,1,1,1,1,1,1,1,SYSDATE,SYSDATE);
INSERT INTO ROLE_PARAMETRAGES (USERID,PARAMETRAGES_GENERAUX,PERIPHERIQUES,PRESENTATION,BADGES,DATECREATION,DATEMAJ) VALUES (-1,1,1,1,1,SYSDATE,SYSDATE);
INSERT INTO ROLE_RESTES (USERID,STAT,DATECREATION,DATEMAJ) VALUES (-1,1,SYSDATE,SYSDATE);
UPDATE USERS SET SITEID=(SELECT SITEID FROM SITE WHERE LIBELLE=USERS.SITE);
UPDATE USERS SET SITEID='VPARDEFAUT' WHERE SITEID IS NULL;

INSERT INTO GRPEVENEMENT (GRPEVENEMENTID,LIBELLE,DATECREATION,DATEMAJ) VALUES (0,'SURETE',SYSDATE,SYSDATE);
INSERT INTO GRPEVENEMENT (GRPEVENEMENTID,LIBELLE,DATECREATION,DATEMAJ) VALUES (-1,'SYSTEME',SYSDATE,SYSDATE);
INSERT INTO GRPEVENEMENT (GRPEVENEMENTID,LIBELLE,DATECREATION,DATEMAJ) VALUES (1,'SECURITE',SYSDATE,SYSDATE);
INSERT INTO RONDEMOTCLE (RONDEMOTCLEID,LIBELLE,DATECREATION,DATEMAJ,ETAT) VALUES (1,'NON PREVU',SYSDATE,SYSDATE,1);
INSERT INTO RONDEMOTCLE (RONDEMOTCLEID,LIBELLE,DATECREATION,DATEMAJ,ETAT) VALUES (2,'INCIDENT',SYSDATE,SYSDATE,1);
INSERT INTO RONDEMOTCLE (RONDEMOTCLEID,LIBELLE,DATECREATION,DATEMAJ,ETAT) VALUES (3,'DEJA LU',SYSDATE,SYSDATE,1);
INSERT INTO RONDEMOTCLE (RONDEMOTCLEID,LIBELLE,DATECREATION,DATEMAJ,ETAT) VALUES (4,'NON DEFINI',SYSDATE,SYSDATE,1);
INSERT INTO RONDEMOTCLE (RONDEMOTCLEID,LIBELLE,DATECREATION,DATEMAJ,ETAT) VALUES (5,'MANQUE',SYSDATE,SYSDATE,1);

INSERT INTO INTERLOCUTEUR (SOCIETEID,INTERLOCUTEURID,CODECIVILITE,CODEFONCTION,PAYS,CIVILITE,NOMPRENOM,NOM,NOMJEUNEFILLE,PRENOM,
FONCTION,TELEPHONE,EMAIL,GSM,FAX,IMMATRICULATION,INTERDIT,DEBUTINTERDIT,FININTERDIT,NATUREID,NATIONALITEID,DATEMAJ,DATECREATION,SOCIETE,DATENAISSANCE,FINVALIDITEAUTO,PHONKEY)
VALUES
('VPARDEFAUT','VPARDEFAUT',1,0,'FRANCE','Mr','VISITEUR INCONNU','VISITEUR','','INCONNU','**********','01 25 46 85 92','','06 13 25 46 95',
'','','0',SYSDATE-1,SYSDATE+100*365,'VPARDEFAUT','VPARDEFAUT',SYSDATE,SYSDATE,'**********','05/08/1960',SYSDATE+365,1);

UPDATE PARAMETRES SET SORTIVI=1;
UPDATE PARAMETRES SET PURGEVP=1;
UPDATE TQ_POSTE SET ENVOI_BDG_MANUEL=1;
UPDATE TQ_POSTE SET GENERATION_BDG=1;
UPDATE TQ_POSTE SET DEBUT_CODE='V';

COMMIT;

INSERT INTO ZCL27_PARAMETRE (H_LISTE, FREQ_EMPL, H_LOG, H_SORTIE1, H_SORTIE2, DATECREATION, DATEMAJ)
	VALUES (TO_DATE('01/01/2000 06:00','DD/MM/YYYY HH24:MI'), 500, TO_DATE('01/01/2000 22:00','DD/MM/YYYY HH24:MI'), TO_DATE('01/01/2000 13:00','DD/MM/YYYY HH24:MI'), TO_DATE('01/01/2000 23:00','DD/MM/YYYY HH24:MI'), CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

INSERT INTO DEPFR (DEPFRID,NUMERO,DEPARTEMENT,PREFERTURE,REGION,DATECREATION,DATEMAJ) VALUES (1,'001','Ain','Bourg-en-Bresse','Rhône-Alpes',SYSDATE,SYSDATE);
INSERT INTO DEPFR (DEPFRID,NUMERO,DEPARTEMENT,PREFERTURE,REGION,DATECREATION,DATEMAJ) VALUES (2,'002','Aisne','Laon','Picardie',SYSDATE,SYSDATE);
INSERT INTO DEPFR (DEPFRID,NUMERO,DEPARTEMENT,PREFERTURE,REGION,DATECREATION,DATEMAJ) VALUES (3,'003','Allier','Moulins','Auvergne',SYSDATE,SYSDATE);
INSERT INTO DEPFR (DEPFRID,NUMERO,DEPARTEMENT,PREFERTURE,REGION,DATECREATION,DATEMAJ) VALUES (4,'004','Alpes de Hautes-Provence','Digne','Provence-Alpes-Côte d''Azur',SYSDATE,SYSDATE);
INSERT INTO DEPFR (DEPFRID,NUMERO,DEPARTEMENT,PREFERTURE,REGION,DATECREATION,DATEMAJ) VALUES (5,'005','Hautes-Alpes','Gap','Provence-Alpes-Côte d''Azur',SYSDATE,SYSDATE);
INSERT INTO DEPFR (DEPFRID,NUMERO,DEPARTEMENT,PREFERTURE,REGION,DATECREATION,DATEMAJ) VALUES (6,'006','Alpes-Maritimes','Nice','Provence-Alpes-Côte d''Azur',SYSDATE,SYSDATE);
INSERT INTO DEPFR (DEPFRID,NUMERO,DEPARTEMENT,PREFERTURE,REGION,DATECREATION,DATEMAJ) VALUES (7,'007','Ardèche','Privas','Rhône-Alpes',SYSDATE,SYSDATE);
INSERT INTO DEPFR (DEPFRID,NUMERO,DEPARTEMENT,PREFERTURE,REGION,DATECREATION,DATEMAJ) VALUES (8,'008','Ardennes','Charleville-Mézières','Champagne-Ardenne',SYSDATE,SYSDATE);
INSERT INTO DEPFR (DEPFRID,NUMERO,DEPARTEMENT,PREFERTURE,REGION,DATECREATION,DATEMAJ) VALUES (9,'009','Ariège','Foix','Midi-Pyrénées',SYSDATE,SYSDATE);
INSERT INTO DEPFR (DEPFRID,NUMERO,DEPARTEMENT,PREFERTURE,REGION,DATECREATION,DATEMAJ) VALUES (10,'010','Aube','Troyes','Champagne-Ardenne',SYSDATE,SYSDATE);
INSERT INTO DEPFR (DEPFRID,NUMERO,DEPARTEMENT,PREFERTURE,REGION,DATECREATION,DATEMAJ) VALUES (11,'011','Aude','Carcassonne','Languedoc-Roussillon',SYSDATE,SYSDATE);
INSERT INTO DEPFR (DEPFRID,NUMERO,DEPARTEMENT,PREFERTURE,REGION,DATECREATION,DATEMAJ) VALUES (12,'012','Aveyron','Rodez','Midi-Pyrénées',SYSDATE,SYSDATE);
INSERT INTO DEPFR (DEPFRID,NUMERO,DEPARTEMENT,PREFERTURE,REGION,DATECREATION,DATEMAJ) VALUES (13,'013','Bouches-du-Rhône','Marseille','Provence-Alpes-Côte d''Azur',SYSDATE,SYSDATE);
INSERT INTO DEPFR (DEPFRID,NUMERO,DEPARTEMENT,PREFERTURE,REGION,DATECREATION,DATEMAJ) VALUES (14,'014','Calvados','Caen','Basse-Normandie',SYSDATE,SYSDATE);
INSERT INTO DEPFR (DEPFRID,NUMERO,DEPARTEMENT,PREFERTURE,REGION,DATECREATION,DATEMAJ) VALUES (15,'015','Cantal','Aurillac','Auvergne',SYSDATE,SYSDATE);
INSERT INTO DEPFR (DEPFRID,NUMERO,DEPARTEMENT,PREFERTURE,REGION,DATECREATION,DATEMAJ) VALUES (16,'016','Charente','Angoulême','Poitou-Charentes',SYSDATE,SYSDATE);
INSERT INTO DEPFR (DEPFRID,NUMERO,DEPARTEMENT,PREFERTURE,REGION,DATECREATION,DATEMAJ) VALUES (17,'017','Charente-Maritime','La Rochelle','Poitou-Charentes',SYSDATE,SYSDATE);
INSERT INTO DEPFR (DEPFRID,NUMERO,DEPARTEMENT,PREFERTURE,REGION,DATECREATION,DATEMAJ) VALUES (18,'018','Cher','Bourges','Centre',SYSDATE,SYSDATE);
INSERT INTO DEPFR (DEPFRID,NUMERO,DEPARTEMENT,PREFERTURE,REGION,DATECREATION,DATEMAJ) VALUES (19,'019','Corrèze','Tulle','Limousin',SYSDATE,SYSDATE);
INSERT INTO DEPFR (DEPFRID,NUMERO,DEPARTEMENT,PREFERTURE,REGION,DATECREATION,DATEMAJ) VALUES (20,'02A','Corse-du-Sud','Ajaccio','Corse',SYSDATE,SYSDATE);
INSERT INTO DEPFR (DEPFRID,NUMERO,DEPARTEMENT,PREFERTURE,REGION,DATECREATION,DATEMAJ) VALUES (21,'02B','Haute-Corse','Bastia','Corse',SYSDATE,SYSDATE);
INSERT INTO DEPFR (DEPFRID,NUMERO,DEPARTEMENT,PREFERTURE,REGION,DATECREATION,DATEMAJ) VALUES (22,'021','Côte-d''Or','Dijon','Bourgogne',SYSDATE,SYSDATE);
INSERT INTO DEPFR (DEPFRID,NUMERO,DEPARTEMENT,PREFERTURE,REGION,DATECREATION,DATEMAJ) VALUES (23,'022','Côtes d''Armor','Saint-Brieuc','Bretagne',SYSDATE,SYSDATE);
INSERT INTO DEPFR (DEPFRID,NUMERO,DEPARTEMENT,PREFERTURE,REGION,DATECREATION,DATEMAJ) VALUES (24,'023','Creuse','Guéret','Limousin',SYSDATE,SYSDATE);
INSERT INTO DEPFR (DEPFRID,NUMERO,DEPARTEMENT,PREFERTURE,REGION,DATECREATION,DATEMAJ) VALUES (25,'024','Dordogne','Périgueux','Aquitaine',SYSDATE,SYSDATE);
INSERT INTO DEPFR (DEPFRID,NUMERO,DEPARTEMENT,PREFERTURE,REGION,DATECREATION,DATEMAJ) VALUES (26,'025','Doubs','Besançon','Franche-Comté',SYSDATE,SYSDATE);
INSERT INTO DEPFR (DEPFRID,NUMERO,DEPARTEMENT,PREFERTURE,REGION,DATECREATION,DATEMAJ) VALUES (27,'026','Drôme','Valence','Rhône-Alpes',SYSDATE,SYSDATE);
INSERT INTO DEPFR (DEPFRID,NUMERO,DEPARTEMENT,PREFERTURE,REGION,DATECREATION,DATEMAJ) VALUES (28,'027','Eure','Évreux','Haute-Normandie',SYSDATE,SYSDATE);
INSERT INTO DEPFR (DEPFRID,NUMERO,DEPARTEMENT,PREFERTURE,REGION,DATECREATION,DATEMAJ) VALUES (29,'028','Eure-et-Loir','Chartres','Centre',SYSDATE,SYSDATE);
INSERT INTO DEPFR (DEPFRID,NUMERO,DEPARTEMENT,PREFERTURE,REGION,DATECREATION,DATEMAJ) VALUES (30,'029','Finistère','Quimper','Bretagne',SYSDATE,SYSDATE);
INSERT INTO DEPFR (DEPFRID,NUMERO,DEPARTEMENT,PREFERTURE,REGION,DATECREATION,DATEMAJ) VALUES (31,'030','Gard','Nîmes','Languedoc-Roussillon',SYSDATE,SYSDATE);
INSERT INTO DEPFR (DEPFRID,NUMERO,DEPARTEMENT,PREFERTURE,REGION,DATECREATION,DATEMAJ) VALUES (32,'031','Haute-Garonne','Toulouse','Midi-Pyrénées',SYSDATE,SYSDATE);
INSERT INTO DEPFR (DEPFRID,NUMERO,DEPARTEMENT,PREFERTURE,REGION,DATECREATION,DATEMAJ) VALUES (33,'032','Gers','Auch','Midi-Pyrénées',SYSDATE,SYSDATE);
INSERT INTO DEPFR (DEPFRID,NUMERO,DEPARTEMENT,PREFERTURE,REGION,DATECREATION,DATEMAJ) VALUES (34,'033','Gironde','Bordeaux','Aquitaine',SYSDATE,SYSDATE);
INSERT INTO DEPFR (DEPFRID,NUMERO,DEPARTEMENT,PREFERTURE,REGION,DATECREATION,DATEMAJ) VALUES (35,'034','Hérault','Montpellier','Languedoc-Roussillon',SYSDATE,SYSDATE);
INSERT INTO DEPFR (DEPFRID,NUMERO,DEPARTEMENT,PREFERTURE,REGION,DATECREATION,DATEMAJ) VALUES (36,'035','Ille-et-Vilaine','Rennes','Bretagne',SYSDATE,SYSDATE);
INSERT INTO DEPFR (DEPFRID,NUMERO,DEPARTEMENT,PREFERTURE,REGION,DATECREATION,DATEMAJ) VALUES (37,'036','Indre','Châteauroux','Centre',SYSDATE,SYSDATE);
INSERT INTO DEPFR (DEPFRID,NUMERO,DEPARTEMENT,PREFERTURE,REGION,DATECREATION,DATEMAJ) VALUES (38,'037','Indre-et-Loire','Tours','Centre',SYSDATE,SYSDATE);
INSERT INTO DEPFR (DEPFRID,NUMERO,DEPARTEMENT,PREFERTURE,REGION,DATECREATION,DATEMAJ) VALUES (39,'038','Isère','Grenoble','Rhône-Alpes',SYSDATE,SYSDATE);
INSERT INTO DEPFR (DEPFRID,NUMERO,DEPARTEMENT,PREFERTURE,REGION,DATECREATION,DATEMAJ) VALUES (40,'039','Jura','Lons-le-Saunier','Franche-Comté',SYSDATE,SYSDATE);
INSERT INTO DEPFR (DEPFRID,NUMERO,DEPARTEMENT,PREFERTURE,REGION,DATECREATION,DATEMAJ) VALUES (41,'040','Landes','Mont-de-Marsan','Aquitaine',SYSDATE,SYSDATE);
INSERT INTO DEPFR (DEPFRID,NUMERO,DEPARTEMENT,PREFERTURE,REGION,DATECREATION,DATEMAJ) VALUES (42,'041','Loir-et-Cher','Blois','Centre',SYSDATE,SYSDATE);
INSERT INTO DEPFR (DEPFRID,NUMERO,DEPARTEMENT,PREFERTURE,REGION,DATECREATION,DATEMAJ) VALUES (43,'042','Loire','Saint-Étienne','Rhône-Alpes',SYSDATE,SYSDATE);
INSERT INTO DEPFR (DEPFRID,NUMERO,DEPARTEMENT,PREFERTURE,REGION,DATECREATION,DATEMAJ) VALUES (44,'043','Haute-Loire','Le Puy-en-Velay','Auvergne',SYSDATE,SYSDATE);
INSERT INTO DEPFR (DEPFRID,NUMERO,DEPARTEMENT,PREFERTURE,REGION,DATECREATION,DATEMAJ) VALUES (45,'044','Loire-Atlantique','Nantes','Pays de la Loire',SYSDATE,SYSDATE);
INSERT INTO DEPFR (DEPFRID,NUMERO,DEPARTEMENT,PREFERTURE,REGION,DATECREATION,DATEMAJ) VALUES (46,'045','Loiret','Orléans','Centre',SYSDATE,SYSDATE);
INSERT INTO DEPFR (DEPFRID,NUMERO,DEPARTEMENT,PREFERTURE,REGION,DATECREATION,DATEMAJ) VALUES (47,'046','Lot','Cahors','Midi-Pyrénées',SYSDATE,SYSDATE);
INSERT INTO DEPFR (DEPFRID,NUMERO,DEPARTEMENT,PREFERTURE,REGION,DATECREATION,DATEMAJ) VALUES (48,'047','Lot-et-Garonne','Agen','Aquitaine',SYSDATE,SYSDATE);
INSERT INTO DEPFR (DEPFRID,NUMERO,DEPARTEMENT,PREFERTURE,REGION,DATECREATION,DATEMAJ) VALUES (49,'048','Lozère','Mende','Languedoc-Roussillon',SYSDATE,SYSDATE);
INSERT INTO DEPFR (DEPFRID,NUMERO,DEPARTEMENT,PREFERTURE,REGION,DATECREATION,DATEMAJ) VALUES (50,'049','Maine-et-Loire','Angers','Pays de la Loire',SYSDATE,SYSDATE);
INSERT INTO DEPFR (DEPFRID,NUMERO,DEPARTEMENT,PREFERTURE,REGION,DATECREATION,DATEMAJ) VALUES (51,'050','Manche','Saint-Lô','Basse-Normandie',SYSDATE,SYSDATE);
INSERT INTO DEPFR (DEPFRID,NUMERO,DEPARTEMENT,PREFERTURE,REGION,DATECREATION,DATEMAJ) VALUES (52,'051','Marne','Châlons-en-Champagne','Champagne-Ardenne',SYSDATE,SYSDATE);
INSERT INTO DEPFR (DEPFRID,NUMERO,DEPARTEMENT,PREFERTURE,REGION,DATECREATION,DATEMAJ) VALUES (53,'052','Haute-Marne','Chaumont','Champagne-Ardenne',SYSDATE,SYSDATE);
INSERT INTO DEPFR (DEPFRID,NUMERO,DEPARTEMENT,PREFERTURE,REGION,DATECREATION,DATEMAJ) VALUES (54,'053','Mayenne','Laval','Pays de la Loire',SYSDATE,SYSDATE);
INSERT INTO DEPFR (DEPFRID,NUMERO,DEPARTEMENT,PREFERTURE,REGION,DATECREATION,DATEMAJ) VALUES (55,'054','Meurthe-et-Moselle','Nancy','Lorraine',SYSDATE,SYSDATE);
INSERT INTO DEPFR (DEPFRID,NUMERO,DEPARTEMENT,PREFERTURE,REGION,DATECREATION,DATEMAJ) VALUES (56,'055','Meuse','Bar-le-Duc','Lorraine',SYSDATE,SYSDATE);
INSERT INTO DEPFR (DEPFRID,NUMERO,DEPARTEMENT,PREFERTURE,REGION,DATECREATION,DATEMAJ) VALUES (57,'056','Morbihan','Vannes','Bretagne',SYSDATE,SYSDATE);
INSERT INTO DEPFR (DEPFRID,NUMERO,DEPARTEMENT,PREFERTURE,REGION,DATECREATION,DATEMAJ) VALUES (58,'057','Moselle','Metz','Lorraine',SYSDATE,SYSDATE);
INSERT INTO DEPFR (DEPFRID,NUMERO,DEPARTEMENT,PREFERTURE,REGION,DATECREATION,DATEMAJ) VALUES (59,'058','Nièvre','Nevers','Bourgogne',SYSDATE,SYSDATE);
INSERT INTO DEPFR (DEPFRID,NUMERO,DEPARTEMENT,PREFERTURE,REGION,DATECREATION,DATEMAJ) VALUES (60,'059','Nord','Lille','Nord-Pas-de-Calais',SYSDATE,SYSDATE);
INSERT INTO DEPFR (DEPFRID,NUMERO,DEPARTEMENT,PREFERTURE,REGION,DATECREATION,DATEMAJ) VALUES (61,'060','Oise','Beauvais','Picardie',SYSDATE,SYSDATE);
INSERT INTO DEPFR (DEPFRID,NUMERO,DEPARTEMENT,PREFERTURE,REGION,DATECREATION,DATEMAJ) VALUES (62,'061','Orne','Alençon','Basse-Normandie',SYSDATE,SYSDATE);
INSERT INTO DEPFR (DEPFRID,NUMERO,DEPARTEMENT,PREFERTURE,REGION,DATECREATION,DATEMAJ) VALUES (63,'062','Pas-de-Calais','Arras','Nord-Pas-de-Calais',SYSDATE,SYSDATE);
INSERT INTO DEPFR (DEPFRID,NUMERO,DEPARTEMENT,PREFERTURE,REGION,DATECREATION,DATEMAJ) VALUES (64,'063','Puy-de-Dôme','Clermont-Ferrand','Auvergne',SYSDATE,SYSDATE);
INSERT INTO DEPFR (DEPFRID,NUMERO,DEPARTEMENT,PREFERTURE,REGION,DATECREATION,DATEMAJ) VALUES (65,'064','Pyrénées-Atlantiques','Pau','Aquitaine',SYSDATE,SYSDATE);
INSERT INTO DEPFR (DEPFRID,NUMERO,DEPARTEMENT,PREFERTURE,REGION,DATECREATION,DATEMAJ) VALUES (66,'065','Hautes-Pyrénées','Tarbes','Midi-Pyrénées',SYSDATE,SYSDATE);
INSERT INTO DEPFR (DEPFRID,NUMERO,DEPARTEMENT,PREFERTURE,REGION,DATECREATION,DATEMAJ) VALUES (67,'066','Pyrénées-Orientales','Perpignan','Languedoc-Roussillon',SYSDATE,SYSDATE);
INSERT INTO DEPFR (DEPFRID,NUMERO,DEPARTEMENT,PREFERTURE,REGION,DATECREATION,DATEMAJ) VALUES (68,'067','Bas-Rhin','Strasbourg','Alsace',SYSDATE,SYSDATE);
INSERT INTO DEPFR (DEPFRID,NUMERO,DEPARTEMENT,PREFERTURE,REGION,DATECREATION,DATEMAJ) VALUES (69,'068','Haut-Rhin','Colmar','Alsace',SYSDATE,SYSDATE);
INSERT INTO DEPFR (DEPFRID,NUMERO,DEPARTEMENT,PREFERTURE,REGION,DATECREATION,DATEMAJ) VALUES (70,'069','Rhône','Lyon','Rhône-Alpes',SYSDATE,SYSDATE);
INSERT INTO DEPFR (DEPFRID,NUMERO,DEPARTEMENT,PREFERTURE,REGION,DATECREATION,DATEMAJ) VALUES (71,'070','Haute-Saône','Vesoul','Franche-Comté',SYSDATE,SYSDATE);
INSERT INTO DEPFR (DEPFRID,NUMERO,DEPARTEMENT,PREFERTURE,REGION,DATECREATION,DATEMAJ) VALUES (72,'071','Saône-et-Loire','Mâcon','Bourgogne',SYSDATE,SYSDATE);
INSERT INTO DEPFR (DEPFRID,NUMERO,DEPARTEMENT,PREFERTURE,REGION,DATECREATION,DATEMAJ) VALUES (73,'072','Sarthe','Le Mans','Pays de la Loire',SYSDATE,SYSDATE);
INSERT INTO DEPFR (DEPFRID,NUMERO,DEPARTEMENT,PREFERTURE,REGION,DATECREATION,DATEMAJ) VALUES (74,'073','Savoie','Chambéry','Rhône-Alpes',SYSDATE,SYSDATE);
INSERT INTO DEPFR (DEPFRID,NUMERO,DEPARTEMENT,PREFERTURE,REGION,DATECREATION,DATEMAJ) VALUES (75,'074','Haute-Savoie','Annecy','Rhône-Alpes',SYSDATE,SYSDATE);
INSERT INTO DEPFR (DEPFRID,NUMERO,DEPARTEMENT,PREFERTURE,REGION,DATECREATION,DATEMAJ) VALUES (76,'075','Paris','Paris','Ile-de-France',SYSDATE,SYSDATE);
INSERT INTO DEPFR (DEPFRID,NUMERO,DEPARTEMENT,PREFERTURE,REGION,DATECREATION,DATEMAJ) VALUES (77,'076','Seine-Maritime','Rouen','Haute-Normandie',SYSDATE,SYSDATE);
INSERT INTO DEPFR (DEPFRID,NUMERO,DEPARTEMENT,PREFERTURE,REGION,DATECREATION,DATEMAJ) VALUES (78,'077','Seine-et-Marne','Melun','Ile-de-France',SYSDATE,SYSDATE);
INSERT INTO DEPFR (DEPFRID,NUMERO,DEPARTEMENT,PREFERTURE,REGION,DATECREATION,DATEMAJ) VALUES (79,'078','Yvelines','Versailles','Ile-de-France',SYSDATE,SYSDATE);
INSERT INTO DEPFR (DEPFRID,NUMERO,DEPARTEMENT,PREFERTURE,REGION,DATECREATION,DATEMAJ) VALUES (80,'079','Deux-Sèvres','Niort','Poitou-Charentes',SYSDATE,SYSDATE);
INSERT INTO DEPFR (DEPFRID,NUMERO,DEPARTEMENT,PREFERTURE,REGION,DATECREATION,DATEMAJ) VALUES (81,'080','Somme','Amiens','Picardie',SYSDATE,SYSDATE);
INSERT INTO DEPFR (DEPFRID,NUMERO,DEPARTEMENT,PREFERTURE,REGION,DATECREATION,DATEMAJ) VALUES (82,'081','Tarn','Albi','Midi-Pyrénées',SYSDATE,SYSDATE);
INSERT INTO DEPFR (DEPFRID,NUMERO,DEPARTEMENT,PREFERTURE,REGION,DATECREATION,DATEMAJ) VALUES (83,'082','Tarn-et-Garonne','Montauban','Midi-Pyrénées',SYSDATE,SYSDATE);
INSERT INTO DEPFR (DEPFRID,NUMERO,DEPARTEMENT,PREFERTURE,REGION,DATECREATION,DATEMAJ) VALUES (84,'083','Var','Toulon','Provence-Alpes-Côte d''Azur',SYSDATE,SYSDATE);
INSERT INTO DEPFR (DEPFRID,NUMERO,DEPARTEMENT,PREFERTURE,REGION,DATECREATION,DATEMAJ) VALUES (85,'084','Vaucluse','Avignon','Provence-Alpes-Côte d''Azur',SYSDATE,SYSDATE);
INSERT INTO DEPFR (DEPFRID,NUMERO,DEPARTEMENT,PREFERTURE,REGION,DATECREATION,DATEMAJ) VALUES (86,'085','Vendée','La Roche-sur-Yon','Pays de la Loire',SYSDATE,SYSDATE);
INSERT INTO DEPFR (DEPFRID,NUMERO,DEPARTEMENT,PREFERTURE,REGION,DATECREATION,DATEMAJ) VALUES (87,'086','Vienne','Poitiers','Poitou-Charentes',SYSDATE,SYSDATE);
INSERT INTO DEPFR (DEPFRID,NUMERO,DEPARTEMENT,PREFERTURE,REGION,DATECREATION,DATEMAJ) VALUES (88,'087','Haute-Vienne','Limoges','Limousin',SYSDATE,SYSDATE);
INSERT INTO DEPFR (DEPFRID,NUMERO,DEPARTEMENT,PREFERTURE,REGION,DATECREATION,DATEMAJ) VALUES (89,'088','Vosges','Épinal','Lorraine',SYSDATE,SYSDATE);
INSERT INTO DEPFR (DEPFRID,NUMERO,DEPARTEMENT,PREFERTURE,REGION,DATECREATION,DATEMAJ) VALUES (90,'089','Yonne','Auxerre','Bourgogne',SYSDATE,SYSDATE);
INSERT INTO DEPFR (DEPFRID,NUMERO,DEPARTEMENT,PREFERTURE,REGION,DATECREATION,DATEMAJ) VALUES (91,'090','Territoire-de-Belfort','Belfort','Franche-Comté',SYSDATE,SYSDATE);
INSERT INTO DEPFR (DEPFRID,NUMERO,DEPARTEMENT,PREFERTURE,REGION,DATECREATION,DATEMAJ) VALUES (92,'091','Essonne','Évry','Ile-de-France',SYSDATE,SYSDATE);
INSERT INTO DEPFR (DEPFRID,NUMERO,DEPARTEMENT,PREFERTURE,REGION,DATECREATION,DATEMAJ) VALUES (93,'092','Hauts-de-Seine','Nanterre','Ile-de-France',SYSDATE,SYSDATE);
INSERT INTO DEPFR (DEPFRID,NUMERO,DEPARTEMENT,PREFERTURE,REGION,DATECREATION,DATEMAJ) VALUES (94,'093','Seine-Saint-Denis','Bobigny','Ile-de-France',SYSDATE,SYSDATE);
INSERT INTO DEPFR (DEPFRID,NUMERO,DEPARTEMENT,PREFERTURE,REGION,DATECREATION,DATEMAJ) VALUES (95,'094','Val-de-Marne','Créteil','Ile-de-France',SYSDATE,SYSDATE);
INSERT INTO DEPFR (DEPFRID,NUMERO,DEPARTEMENT,PREFERTURE,REGION,DATECREATION,DATEMAJ) VALUES (96,'095','Val-d''Oise','Pontoise','Ile-de-France',SYSDATE,SYSDATE);

INSERT INTO DEPFR (DEPFRID,NUMERO,DEPARTEMENT,PREFERTURE,REGION,DATECREATION,DATEMAJ) VALUES (97,'971','Guadeloupe','Basse Terre','Département d''Outre Mer',SYSDATE,SYSDATE);
INSERT INTO DEPFR (DEPFRID,NUMERO,DEPARTEMENT,PREFERTURE,REGION,DATECREATION,DATEMAJ) VALUES (98,'972','Martinique','Fort-de-France','Département d''Outre Mer',SYSDATE,SYSDATE);
INSERT INTO DEPFR (DEPFRID,NUMERO,DEPARTEMENT,PREFERTURE,REGION,DATECREATION,DATEMAJ) VALUES (99,'973','Guyane','Cayenne','Département d''Outre Mer',SYSDATE,SYSDATE);
INSERT INTO DEPFR (DEPFRID,NUMERO,DEPARTEMENT,PREFERTURE,REGION,DATECREATION,DATEMAJ) VALUES (100,'974','La Réunion','Saint-Denis','Département d''Outre Mer',SYSDATE,SYSDATE);
COMMIT;
INSERT INTO MARCHE (MARCHEID,MARCHE,OBJET,MANDATAIRE,MANDATAIREID,RANG,FINPREVUE,CSPS,INSPECCOMMUNE,DATECREATION,DATEMAJ,DATESYNCHRO) VALUES ('VPARDEFAUT','PAS DE MARCHE','','**********','VPARDEFAUT','-1','01/01/1900','01/01/1900','01/01/1900',SYSDATE,SYSDATE,SYSDATE);

INSERT INTO LIEU (LIEUID,LIBELLE,DATECREATION,DATEMAJ) VALUES (-1,'-NC-',SYSDATE,SYSDATE);

INSERT INTO OTACHE (OTACHEID,TYPEJOUR,HEUREEXECUTION,ACTION,HEUREDEBUT,HEUREFIN,NBJOURMOINS,SITEID,GROUPEDESTID,DATECREATION) VALUES (1,'0:0',TO_DATE('30/12/1899 08:00','DD/MM/YYYY HH24:MI'),'MAINCOURANTE',TO_DATE('30/12/1899 07:00','DD/MM/YYYY HH24:MI'),TO_DATE('30/12/1899 07:00','DD/MM/YYYY HH24:MI'),-1,'VPARDEFAULT',1865,SYSDATE);
COMMIT;

INSERT INTO OMNI_PARAM (PARAMACCES, OPTION_NBJMC, OPTION_NBJMI, OPTION_DUBIP, OPTION_BIPLONG, SEPARATEUR, OPTION_AVMISS, OPTION_TIMER_MISSION, OPTION_PASSWORD, CARTEPRO_CTRL, CARTEPRO_NBJ, MC_FILTRAGE, PASS_SENSIBLE, STATION_POSTE_ONLY, STATION_ALERT_LOCK, ALERT_NOLOCK) VALUES (
401903, 30, NULL, NULL, 0, '$DA$', 10, 5, 0, 0, 0, 0, 0, 0, 0, 0);
COMMIT;

INSERT INTO EVENEMENT_SITE (EVENEMENTID,SITEID) VALUES (1,'VPARDEFAUT');
COMMIT;

INSERT INTO PERIPHERIQUE (PERIPHERIQUEID, PERIPHERIQUE_TRAITEMENTID, NOM, AVANT, APRES, DEBUT, LONGUEUR, LONGUEUR_MAX, DECOUPE, CONVERSION, TYPE_PORT, BIT_SECONDE, BIT_DONNEE, PARITE, BIT_ARRET, CONTROLE_FLUX, DATECREATION, DATEMAJ) VALUES (-1,-4,'Lecteur Ecran Clavier','','',NULL,NULL,NULL,NULL,NULL,'PS2',NULL,NULL,'',NULL,'',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO PERIPHERIQUE (PERIPHERIQUEID, PERIPHERIQUE_TRAITEMENTID, NOM, AVANT, APRES, DEBUT, LONGUEUR, LONGUEUR_MAX, DECOUPE, CONVERSION, TYPE_PORT, BIT_SECONDE, BIT_DONNEE, PARITE, BIT_ARRET, CONTROLE_FLUX, DATECREATION, DATEMAJ) VALUES (-2,-4,'WIEGAND','','',2,10,NULL,1,NULL,'RS232',9600,8,'',1,'',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO PERIPHERIQUE (PERIPHERIQUEID, PERIPHERIQUE_TRAITEMENTID, NOM, AVANT, APRES, DEBUT, LONGUEUR, LONGUEUR_MAX, DECOUPE, CONVERSION, TYPE_PORT, BIT_SECONDE, BIT_DONNEE, PARITE, BIT_ARRET, CONTROLE_FLUX, DATECREATION, DATEMAJ) VALUES (-3,-4,'POWERSCAN','','"CR""LF"',4,99,NULL,1,NULL,'RS232',9600,8,'',1,'',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO PERIPHERIQUE (PERIPHERIQUEID, PERIPHERIQUE_TRAITEMENTID, NOM, AVANT, APRES, DEBUT, LONGUEUR, LONGUEUR_MAX, DECOUPE, CONVERSION, TYPE_PORT, BIT_SECONDE, BIT_DONNEE, PARITE, BIT_ARRET, CONTROLE_FLUX, DATECREATION, DATEMAJ) VALUES (-4,-1,'SWISS READER','','',NULL,NULL,NULL,NULL,NULL,'PS2',NULL,NULL,'',NULL,'',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);

-- Insertion des types de visite dans la table STATUTVISITE
INSERT INTO STATUTVISITE (STATUTID, STATUTVISITE) VALUES (-2,'Non venu');
INSERT INTO STATUTVISITE (STATUTID, STATUTVISITE) VALUES (-1,'Supprimée');
INSERT INTO STATUTVISITE (STATUTID, STATUTVISITE) VALUES (1,'En attente');
INSERT INTO STATUTVISITE (STATUTID, STATUTVISITE) VALUES (2,'Pré-enregistrée');
INSERT INTO STATUTVISITE (STATUTID, STATUTVISITE) VALUES (4,'Pré-enregistrée interdit');
INSERT INTO STATUTVISITE (STATUTID, STATUTVISITE) VALUES (8,'En cours');
INSERT INTO STATUTVISITE (STATUTID, STATUTVISITE) VALUES (16,'Terminée');
INSERT INTO STATUTVISITE (STATUTID, STATUTVISITE) VALUES (32,'Pré-enregistrée extérieur');
INSERT INTO STATUTVISITE (STATUTID, STATUTVISITE) VALUES (33,'En cours extérieur');
INSERT INTO STATUTVISITE (STATUTID, STATUTVISITE) VALUES (34,'En attente extérieur');
INSERT INTO STATUTVISITE (STATUTID, STATUTVISITE) VALUES (35,'Terminée extérieur');
COMMIT;

INSERT INTO STATUTCOLIS (ID_STATUTCOLIS, LIBELLE, COLOR, DATECREATION, DATEMAJ) VALUES (-1, 'Enregistré', 65535, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO STATUTCOLIS (ID_STATUTCOLIS, LIBELLE, COLOR, DATECREATION, DATEMAJ) VALUES (-2, 'En attente', 42495, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO STATUTCOLIS (ID_STATUTCOLIS, LIBELLE, COLOR, DATECREATION, DATEMAJ) VALUES (-3, 'En stock', 16711680, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO STATUTCOLIS (ID_STATUTCOLIS, LIBELLE, COLOR, DATECREATION, DATEMAJ) VALUES (-4, 'En stock partiel', 16711680, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO STATUTCOLIS (ID_STATUTCOLIS, LIBELLE, COLOR, DATECREATION, DATEMAJ) VALUES (-5, 'Traité', 32768, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO STATUTCOLIS (ID_STATUTCOLIS, LIBELLE, COLOR, DATECREATION, DATEMAJ) VALUES (-6, 'Refusé', 255, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
COMMIT;

INSERT INTO DROITSTAXI (ID_DROITSTAXI, LIBELLE, DROITS, DATECREATION, DATEMAJ) VALUES (1, 'ADMINISTRATION', 63, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO DROITSTAXI (ID_DROITSTAXI, LIBELLE, DROITS, DATECREATION, DATEMAJ) VALUES (9, 'ACCUEIL', 28, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
COMMIT;

INSERT INTO STATUTCOURSE(ID_STATUTCOURSE, LIBELLE, COLOR, DATECREATION, DATEMAJ) VALUES (-1, 'NOUVEAU', 65535, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO STATUTCOURSE(ID_STATUTCOURSE, LIBELLE, COLOR, DATECREATION, DATEMAJ) VALUES (-2, 'CONFIRME', 42495, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO STATUTCOURSE(ID_STATUTCOURSE, LIBELLE, COLOR, DATECREATION, DATEMAJ) VALUES (-3, 'TRAITE', 32768, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO STATUTCOURSE(ID_STATUTCOURSE, LIBELLE, COLOR, DATECREATION, DATEMAJ) VALUES (-4, 'ANNULE', 255, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
COMMIT;

INSERT INTO TYPEVEHICULE(ID_TYPEVEHICULE, LIBELLE, DATECREATION, DATEMAJ) VALUES (-1, 'BERLINE/BREAK', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO TYPEVEHICULE(ID_TYPEVEHICULE, LIBELLE, DATECREATION, DATEMAJ) VALUES (-2, 'MONOSPACE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
COMMIT;

INSERT INTO TYPEDOCUMENT (TYPEDOCUMENTID,LIBELLE,DATECREATION,DATEMAJ,DATESYNCHRO,PORTEEID,OBLIGATOIRE,MODIFIABLE,VALIDITEPARDEFAUT,CREATCTRL,IN_PREENREG) VALUES (6,'Habilitation amiante',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,NULL,-2,2,2,730,2,2);
INSERT INTO TYPEDOCUMENT (TYPEDOCUMENTID,LIBELLE,DATECREATION,DATEMAJ,DATESYNCHRO,PORTEEID,OBLIGATOIRE,MODIFIABLE,VALIDITEPARDEFAUT,CREATCTRL,IN_PREENREG) VALUES (0,'Formulaire 82b individuel',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,NULL,-1,1,2,730,2,2);
INSERT INTO TYPEDOCUMENT (TYPEDOCUMENTID,LIBELLE,DATECREATION,DATEMAJ,DATESYNCHRO,PORTEEID,OBLIGATOIRE,MODIFIABLE,VALIDITEPARDEFAUT,CREATCTRL,IN_PREENREG) VALUES (-2,'Autorisation de travail',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,NULL,-2,1,2,730,2,2);
INSERT INTO TYPEDOCUMENT (TYPEDOCUMENTID,LIBELLE,DATECREATION,DATEMAJ,DATESYNCHRO,PORTEEID,OBLIGATOIRE,MODIFIABLE,VALIDITEPARDEFAUT,CREATCTRL,IN_PREENREG) VALUES (-3,'Permis de conduire',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,NULL,-1,2,2,360,2,2);
COMMIT;


INSERT INTO DROITSTELEM (ID_DROITSTELEM, LIBELLE, DROITS, DATECREATION, DATEMAJ) VALUES (-1,'ADMINISTRATEUR','accueil,sortie,en_attente,preenreg,exterieurs,visiteurs,residants,es_badge,validation,sur_site,historique,messagerie,entree_colis,sortie_colis,vehicules,annuaire,taxi,vip,multisite,statistiques,administration,gestion_site,gestion_user,parametrages,modeles,pays',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO DROITSTELEM (ID_DROITSTELEM, LIBELLE, DROITS, DATECREATION, DATEMAJ) VALUES (-2,'ACCUEIL','accueil,sortie,en_attente,preenreg,visiteurs,residants,sur_site,historique,messagerie,entree_colis,sortie_colis,annuaire,vip',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
COMMIT;
INSERT INTO ZRR (ID_ZRR,CODE,LIBELLE,DEB_VALITE,FIN_VALIDITE,ACTIVE,ZONE_PARTENAIRE,SITEID,CENTRE,LOCAUX_SENSIBLES,DCREA,DDERMAJ) VALUES (0,'**********','********** Libelle','01/05/2014','01/03/2113','O','N','VPARDEFAUT','','N',SYSDATE,SYSDATE) ;
COMMIT;
INSERT INTO TYPECONSIGNE (TYPECONSIGNEID,TYPECONSIGNE,DATECREATION,DATEMAJ) VALUES (-3,'DEMANDE LPE',SYSDATE,SYSDATE);
COMMIT;
INSERT INTO GRPVALIDEUR (GRPVALIDEURID,GRPVALIDEURN,RANGVALIDEUR,DATECREATION,DATEMAJ) VALUES ('-1','GRPVALIDEUR1',1,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
COMMIT;
INSERT INTO GRPVALIDEUR (GRPVALIDEURID,GRPVALIDEURN,RANGVALIDEUR,DATECREATION,DATEMAJ) VALUES ('-2','GRPVALIDEUR2',2,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
COMMIT;
INSERT INTO GRPVALIDEUR (GRPVALIDEURID,GRPVALIDEURN,RANGVALIDEUR,DATECREATION,DATEMAJ) VALUES ('-3','GRPVALIDEUR3',3,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
COMMIT;
INSERT INTO GRPVALIDEUR (GRPVALIDEURID,GRPVALIDEURN,RANGVALIDEUR,DATECREATION,DATEMAJ) VALUES ('-4','GRPVALIDEUR4',4,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
COMMIT;

INSERT INTO NATURECOLIS (NATURECOLISID,LIBELLE,DATECREATION,DATEMAJ) VALUES (0,'LETTRE',SYSDATE,SYSDATE);
INSERT INTO NATURECOLIS (NATURECOLISID,LIBELLE,DATECREATION,DATEMAJ) VALUES (-1,'COLIS',SYSDATE,SYSDATE);
INSERT INTO NATURECOLIS (NATURECOLISID,LIBELLE,DATECREATION,DATEMAJ) VALUES (-2,'PAQUET',SYSDATE,SYSDATE);
INSERT INTO NATURECOLIS (NATURECOLISID,LIBELLE,DATECREATION,DATEMAJ) VALUES (-3,'PALETTE',SYSDATE,SYSDATE);
COMMIT;

INSERT INTO OBJVISITE (OBJVISITEID,LIBELLE,DATEMAJ,DATECREATION) VALUES (0,'**********',SYSDATE,SYSDATE);
COMMIT;
EXIT;
