CREATE TABLE [dbo].[ACTIONCONTACT](
	[CODEACTIONCONTACT] [nvarchar](14) NOT NULL,
	[LIBELLE] [nvarchar](35) NULL,
	[DATECREATION] [datetime] NOT NULL,
	[DATEMAJ] [datetime] NOT NULL,
	[DATESYNCHRO] [datetime] NULL
) ON [PRIMARY]