CREATE TABLE [dbo].[ACTIONCONTACT](
	[CODEACTIONCONTACT] [varchar](14) NOT NULL,
	[LIBELLE] [varchar](35) NULL,
	[DATECREATION] [datetime] NOT NULL,
	[DATEMAJ] [datetime] NOT NULL,
	[DATESYNCHRO] [datetime] NULL
) ON [PRIMARY]