CREATE TABLE [dbo].[AGENTPRESENT](
	[PERSONNELID] [int] NULL,
	[NOMPRENOM] [nvarchar](50) NULL,
	[ENTREE] [datetime] NULL,
	[SORTIE] [datetime] NULL,
	[SURSITE] [int] NULL,
	[PARPRISE] [int] NULL,
	[FONCTION] [nvarchar](35) NULL,
	[SITEID] [nvarchar](14) NULL,
	[POSTEID] [int] NULL
) ON [PRIMARY]