CREATE TABLE [dbo].[AGENTPRESENTLOG](
	[AGENTPRESENTLOGID] [int] NOT NULL,
	[PERSONNELID] [int] NULL,
	[NOMPRENOM] [varchar](50) NULL,
	[PASSAGE] [datetime] NULL,
	[ACTION] [int] NULL,
	[PARPRISE] [int] NULL,
	[SITEID] [varchar](14) NULL,
	[POSTEID] [int] NULL,
 CONSTRAINT [PK_AGENTPRESENTLOGID] PRIMARY KEY CLUSTERED
(
	[AGENTPRESENTLOGID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]