CREATE TABLE [dbo].[APPEL] (
	[APPELID] [int] IDENTITY(1, 1) NOT NULL
	,[USERID] [nvarchar](14) NULL
	,[QUAND] [datetime] NULL
	,[SITEID] [nvarchar](14) NULL
	,[NOM_POSTE] [nvarchar](50) NULL
	,[RESIDANTID] [nvarchar](14) NULL
	,[INTERLOCUTEURID] [nvarchar](14) NULL
	,[SOCIETE] [nvarchar](35) NULL
	,[OBJET] [nvarchar](4000) NULL
	,[TELEPHONE] [nvarchar](30) NULL
	,[DATECREATION] [datetime] NULL
	,PRIMARY KEY CLUSTERED ([APPELID] ASC) WITH (
		PAD_INDEX = OFF
		,STATISTICS_NORECOMPUTE = OFF
		,IGNORE_DUP_KEY = OFF
		,ALLOW_ROW_LOCKS = ON
		,ALLOW_PAGE_LOCKS = ON
		) ON [PRIMARY]
	) ON [PRIMARY]
