CREATE TABLE [dbo].[APPEL] (
	[APPELID] [int] IDENTITY(1, 1) NOT NULL
	,[USERID] [varchar](14) NULL
	,[QUAND] [datetime] NULL
	,[SITEID] [varchar](14) NULL
	,[NOM_POSTE] [varchar](50) NULL
	,[RESIDANTID] [varchar](14) NULL
	,[INTERLOCUTEURID] [varchar](14) NULL
	,[SOCIETE] [varchar](35) NULL
	,[OBJET] [varchar](4000) NULL
	,[TELEPHONE] [varchar](30) NULL
	,[DATECREATION] [datetime] NULL
	,PRIMARY KEY CLUSTERED ([APPELID] ASC) WITH (
		PAD_INDEX = OFF
		,STATISTICS_NORECOMPUTE = OFF
		,IGNORE_DUP_KEY = OFF
		,ALLOW_ROW_LOCKS = ON
		,ALLOW_PAGE_LOCKS = ON
		) ON [PRIMARY]
	) ON [PRIMARY]
