CREATE TABLE [dbo].[BADGES](
	[BADGEID] [nvarchar](14) NOT NULL,
	[EXTERNALID] [nvarchar](24) NULL,
	[LIBELLE] [nvarchar](35) NULL,
	[FORMAT] [image] NULL,
	[OBSERVATION] [image] NULL,
	[HAUTEUR] [int] NULL,
	[LARGEUR] [int] NULL,
	[STATUT] [int] NULL,
	[SITEID] [nvarchar](14) NULL,
	[STATUTVISITEURID] [nvarchar](14) NULL,
	[TYPEVISITEID] [int] NULL,
	[DATECREATION] [datetime] NOT NULL,
	[DATEMAJ] [datetime] NOT NULL,
	[DATESYNCHRO] [datetime] NULL,
 CONSTRAINT [PK_BADGEID] PRIMARY KEY CLUSTERED
(
	[BADGEID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
ALTER TABLE [dbo].[BADGES] ADD  DEFAULT ((1)) FOR [STATUT]