CREATE TABLE [dbo].[BATIMENT](
	[BATIMENTID] [nvarchar](14) NOT NULL,
	[EXTERNALID] [nvarchar](24) NULL,
	[SITEID] [nvarchar](14) NULL,
	[PLANID] [nvarchar](14) NULL,
	[LIBELLE] [nvarchar](60) NULL,
	[NOBAT] [nvarchar](15) NULL,
	[ADRESSE] [image] NULL,
	[CP] [nvarchar](10) NULL,
	[VILLE] [nvarchar](35) NULL,
	[PAYS] [nvarchar](35) NULL,
	[TELEPHONE] [nvarchar](20) NULL,
	[FAX] [nvarchar](20) NULL,
	[SORTORDER] [int] NULL,
	[PROVINCE] [nvarchar](35) NULL,
	[IMMEUBLE] [int] NULL,
	[DATEMAJ] [datetime] NOT NULL,
	[DATECREATION] [datetime] NOT NULL,
	[DATESYNCHRO] [datetime] NULL,
 CONSTRAINT [PK_BATIMENTID] PRIMARY KEY CLUSTERED
(
	[BATIMENTID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
ALTER TABLE [dbo].[BATIMENT]  WITH CHECK ADD  CONSTRAINT [fk_bat_siteid] FOREIGN KEY([SITEID])
REFERENCES [dbo].[SITE] ([SITEID])
GO

ALTER TABLE [dbo].[BATIMENT] CHECK CONSTRAINT [fk_bat_siteid]