CREATE TABLE [dbo].[BUREAUX] (
	[BUREAUID] [varchar](14) NOT NULL
	,[ETAGEID] [varchar](14) NOT NULL
	,[SORTORDER] [int] NULL
	,[BUREAU] [varchar](15) NOT NULL
	,[DATECREATION] [datetime] NOT NULL
	,[DATEMAJ] [datetime] NOT NULL
	,[DATESYNCHRO] [datetime] NULL
	,CONSTRAINT [PK_BUREAUID] PRIMARY KEY CLUSTERED ([BUREAUID] ASC) WITH (
		PAD_INDEX = OFF
		,STATISTICS_NORECOMPUTE = OFF
		,IGNORE_DUP_KEY = OFF
		,ALLOW_ROW_LOCKS = ON
		,ALLOW_PAGE_LOCKS = ON
		) ON [PRIMARY]
	) ON [PRIMARY]
GO

ALTER TABLE [dbo].[BUREAUX]
	WITH CHECK ADD CONSTRAINT [fk_bur_etageid] FOREIGN KEY ([ETAGEID]) REFERENCES [dbo].[ETAGES]([ETAGEID])
GO

ALTER TABLE [dbo].[BUREAUX] CHECK CONSTRAINT [fk_bur_etageid]
