CREATE TABLE [dbo].[CASIER](
	[CASIERID] [int] NOT NULL,
	[BOITE] [nvarchar](6) NULL,
	[CASIER] [nvarchar](6) NULL,
	[STATUTCASIER] [nvarchar](1) NULL,
	[DATECREATION] [datetime] NOT NULL,
	[DATEMAJ] [datetime] NOT NULL,
	[DATESYNCHRO] [datetime] NULL,
 CONSTRAINT [PK_CASIERID] PRIMARY KEY CLUSTERED
(
	[CASIERID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]