CREATE TABLE [dbo].[CFG_FICHIER](
	[CFG_FICHIERID] [int] NOT NULL,
	[TYPECFG] [nvarchar](20) NULL,
	[LIBELLE] [nvarchar](200) NULL,
	[DOCUMENT1] [nvarchar](4000) NULL,
	[DOCUMENT2] [nvarchar](4000) NULL,
	[DOCUMENT] [image] NULL,
	[TYPEFILE] [int] NULL,
	[CONTENTTYPE] [nvarchar](50) NULL,
	[DATASIZE] [int] NULL,
	[STATUT] [int] NULL,
	[DATEMAJ] [datetime] NULL,
	[DATECREATION] [datetime] NULL,
	[DATESYNCHRO] [datetime] NULL,
PRIMARY KEY CLUSTERED
(
	[CFG_FICHIERID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
ALTER TABLE [dbo].[CFG_FICHIER] ADD  DEFAULT ((1)) FOR [STATUT]