CREATE TABLE [dbo].[CFGETAT](
	[CFGETATID] [nvarchar](50) NOT NULL,
	[ETATNOM] [nvarchar](50) NULL,
	[VISIBLE] [int] NULL,
	[REQUETE] [nvarchar](50) NULL,
	[FILTRE] [nvarchar](250) NULL,
	[DATECREATION] [datetime] NULL,
	[DATEMAJ] [datetime] NULL, 
    CONSTRAINT [PK_CFGETAT] PRIMARY KEY ([CFGETATID])
) ON [PRIMARY]