CREATE TABLE [dbo].[CFGGSALLES](
	[SITE] [varchar](30) NULL,
	[NETTOYAGE] [int] NULL,
	[E_EMAIL] [varchar](15) NULL,
	[E_HOST] [varchar](50) NULL,
	[E_REPERTOIRE] [varchar](50) NULL,
	[E_USERID] [varchar](50) NULL,
	[E_DESTINATAIRE] [int] NULL
) ON [PRIMARY]