CREATE TABLE [dbo].[CFGGSALLES](
	[SITE] [nvarchar](30) NULL,
	[NETTOYAGE] [int] NULL,
	[E_EMAIL] [nvarchar](15) NULL,
	[E_HOST] [nvarchar](50) NULL,
	[E_REPERTOIRE] [nvarchar](50) NULL,
	[E_USERID] [nvarchar](50) NULL,
	[E_DESTINATAIRE] [int] NULL
) ON [PRIMARY]