CREATE TABLE [dbo].[CFGPLANNING](
	[USERID] [varchar](14) NOT NULL,
	[DERNIEREDATE] [datetime] NULL,
	[PERIODE] [int] NOT NULL,
	[POSITIONJOUR] [datetime] NULL,
	[DELEGANT] [varchar](14) NULL,
	[CODESALLE] [varchar](14) NULL
) ON [PRIMARY]