CREATE TABLE [dbo].[CLEFS](
	[CLEID] [nvarchar](14) NOT NULL,
	[REFERENCE] [nvarchar](14) NULL,
	[ACCROCHAGE1] [nvarchar](14) NULL,
	[ACCROCHAGE2] [nvarchar](14) NULL,
	[NIVEAU] [int] NULL,
	[NATURE] [int] NULL,
	[ETAT] [int] NULL,
	[DUREEAUTO] [int] NULL,
	[LIEU] [nvarchar](100) NULL,
	[LIBELLE] [nvarchar](100) NULL,
	[SITEID] [nvarchar](14) NULL,
	[TYPECLEF] [nvarchar](100) NULL,
	[COMBINAISON] [nvarchar](100) NULL,
	[SERVICE] [nvarchar](100) NULL,
	[TYPEACCES] [nvarchar](100) NULL,
	[NODEMANDE] [nvarchar](100) NULL,
	[AUTOSPECIAL] [int] NULL,
	[NATURES] [nvarchar](100) NULL,
	[TAG] [nvarchar](30) NULL,
	[DATECREATION] [datetime] NOT NULL,
	[DATEMAJ] [datetime] NOT NULL,
	[DATESYNCHRO] [datetime] NULL,
 CONSTRAINT [PK_CLEID] PRIMARY KEY CLUSTERED
(
	[CLEID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]