CREATE TABLE [dbo].[COLISEMIS](
	[COLISID] [nvarchar](14) NOT NULL,
	[INTERLOCUTEURID] [nvarchar](14) NULL,
	[RESIDANTID] [nvarchar](14) NULL,
	[STATUTCOLIS] [nvarchar](1) NULL,
	[NBCOLIS] [int] NULL,
	[DATEAR] [datetime] NULL,
	[NUMAR] [nvarchar](20) NULL,
	[LETTRECOLIS] [nvarchar](1) NULL,
	[TYPEENVOI] [nvarchar](20) NULL,
	[OBSERVATION] [nvarchar](4000) NULL,
	[ADRESSEID] [nvarchar](14) NOT NULL,
	[TICKET] [nvarchar](50) NULL,
	[POIDS] [nvarchar](10) NULL,
	[D_ACOURSE] [datetime] NULL,
	[D_ENLPREVU] [datetime] NULL,
	[D_ENLREEL] [datetime] NULL,
	[D_DEPPREVU] [datetime] NULL,
	[D_DEPREELLE] [datetime] NULL,
	[PRIX] [float] NULL,
	[D_APROB] [datetime] NULL,
	[GENRE_PROB] [nvarchar](14) NULL,
	[GUICHETID] [nvarchar](14) NULL,
	[ID_STATUTCOLIS] [int] NULL,
	[TRACKING] [nvarchar](500) NULL,
	[TRACKING_CRM] [nvarchar](500) NULL,
	[TRACKING_TRANSPORTEUR] [nvarchar](500) NULL,
	[OFICHIERID] [int] NULL,
	[LIEU] [nvarchar](50) NULL,
	[SERVICEID] [nvarchar](14) NULL,
	[NATURECOLISID] [int] NULL,
	[VALEUR] [nvarchar](10) NULL,
	[DATEMAJ] [datetime] NOT NULL,
	[DATESYNCHRO] [datetime] NULL,
	[DATECREATION] [datetime] NULL,
	[EMETTEURTYPE] [nvarchar](15) NULL,
	[CORRESTYPE] [nvarchar](15) NULL,
 CONSTRAINT [PK_COLISID] PRIMARY KEY CLUSTERED
(
	[COLISID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]