CREATE TABLE [dbo].[COMMANDE_EVENEMENT](
	[COMMANDE_EVENEMENTID] [bigint] IDENTITY(1,1) NOT NULL,
	[COMMANDEID] [int] NULL,
	[LIBELLE] [nvarchar](max) NULL,
	[STATUT] [nvarchar](14) NULL,
	[DATEHEURE] [datetime] NULL,
	[RESIDANTID] [nvarchar](14) NULL,
	[DATECREATION] [datetime] NOT NULL,
	[DATEMAJ] [datetime] NOT NULL,
PRIMARY KEY CLUSTERED
(
	[COMMANDE_EVENEMENTID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]