CREATE TABLE [dbo].[COMMANDE](
	[COMMANDEID] [bigint] IDENTITY(1,1) NOT NULL,
	[STATUT] [nvarchar](14) NULL,
	[PRIXTOTAL] [nvarchar](50) NULL,
	[REFERENCE] [nvarchar](50) NULL,
	[SITEID] [nvarchar](14) NULL,
	[NUMERO_COMMANDE] [int] NULL,
	[DATECREATION] [datetime] NULL,
	[DATEMAJ] [datetime] NULL,
PRIMARY KEY CLUSTERED
(
	[COMMANDEID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]