/****** Object:  Table [dbo].[CONFERENCE]    Script Date: 7/26/2018 16:14:49 ******/
CREATE TABLE [dbo].[CONFERENCE](
	[CONFERENCEID] [int] NOT NULL,
	[LIBELLE] [nvarchar](50) NULL,
	[DESCRIPTION] [nvarchar](4000) NULL,
	[STARTDATE] [date] NULL,
	[ENDDATE] [date] NULL,
	[TICKET] [nvarchar](50) NULL,
	[BADGEID] [nvarchar](14) NULL,
	[SITEID] [nvarchar](14) NULL,
	[OFICHIERID] [int] NULL,
	[DATECREATION] [date] NULL,
	[DATEMAJ] [date] NULL,
PRIMARY KEY CLUSTERED 
(
	[CONFERENCEID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]