CREATE TABLE [dbo].[CONTACT](
	[SOCIETEID] [nvarchar](14) NULL,
	[CODECONTACT] [nvarchar](14) NOT NULL,
	[DATECONTACT] [datetime] NULL,
	[DATEACTION] [datetime] NULL,
	[INTERLOCUTEURID] [nvarchar](14) NULL,
	[CODEORIGINECONTACT] [nvarchar](14) NULL,
	[CODEDOSSIER] [nvarchar](14) NULL,
	[CODEAFFAIRE] [nvarchar](14) NULL,
	[USERID] [nvarchar](14) NULL,
	[CODECOLLABOACTION] [nvarchar](14) NULL,
	[CODEACTIONCONTACT] [nvarchar](14) NULL,
	[CONTACTGENERE] [int] NULL,
	[ACTIONAUTO] [int] NULL,
	[ACTIONFAITLE] [datetime] NULL,
	[ACTIONFAIT] [int] NULL,
	[TEXTCONTACT] [image] NULL,
	[TEXTACTION] [image] NULL,
	[DATECREATION] [datetime] NOT NULL,
	[DATEMAJ] [datetime] NOT NULL,
	[DATESYNCHRO] [datetime] NULL,
 CONSTRAINT [PK_CODECONTACT] PRIMARY KEY CLUSTERED
(
	[CODECONTACT] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]