CREATE TABLE [dbo].[COURSE](
	[ID_COURSE] [int] NOT NULL,
	[ID_STATUTCOURSE] [nvarchar](14) NULL,
	[SITEID] [nvarchar](14) NULL,
	[DATEHEUREDEMANDE] [datetime] NULL,
	[LIEUDEPART] [nvarchar](40) NULL,
	[DATEHEUREDEPART] [datetime] NULL,
	[ID_TYPEVEHICULE] [int] NULL,
	[OBJET] [nvarchar](4000) NULL,
	[MOYENPAIEMENT] [nvarchar](50) NULL,
	[IMPUTATIONID] [nvarchar](14) NULL,
	[CODECLIENT] [nvarchar](10) NULL,
	[NUMCOURSE] [nvarchar](35) NULL,
	[REFERENCESTAXI] [nvarchar](200) NULL,
	[DELAI] [int] NULL,
	[ADRESSEID] [nvarchar](14) NULL,
	[DATEHEUREFIN] [datetime] NULL,
	[DATECREATION] [datetime] NOT NULL,
	[DATEMAJ] [datetime] NOT NULL,
	[DATESYNCHRO] [datetime] NULL,
	[COMMANDEID] [bigint] NULL,
PRIMARY KEY CLUSTERED
(
	[ID_COURSE] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]