CREATE TABLE [dbo].[DEDUP_DEDUP](
	[DEDUP1ID] [nvarchar](14) NOT NULL,
	[DEDUP2ID] [nvarchar](14) NOT NULL,
	[SIMIL_FLAG] [nvarchar](1) NULL,
	[ENTITE] [nvarchar](50) NULL,
	[JW] [int] NULL,
 CONSTRAINT [PK_DEDUP_DEDUPID] PRIMARY KEY CLUSTERED
(
	[DEDUP1ID] ASC,
	[DEDUP2ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[DEDUP_DEDUP] ADD  DEFAULT ((1)) FOR [SIMIL_FLAG]