CREATE TABLE [dbo].[DEPARTEMENT](
	[DEPTID] [varchar](14) NOT NULL,
	[SOCIETEID] [varchar](14) NULL,
	[EXTERNALID] [varchar](24) NULL,
	[LIBELLE] [varchar](40) NULL,
	[OBSERVATION] [image] NULL,
	[DATECREATION] [datetime] NOT NULL,
	[DATEMAJ] [datetime] NOT NULL,
	[DATESYNCHRO] [datetime] NULL,
 CONSTRAINT [PK_DEPTID] PRIMARY KEY CLUSTERED
(
	[DEPTID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
ALTER TABLE [dbo].[DEPARTEMENT]  WITH CHECK ADD  CONSTRAINT [fk_dep_socid] FOREIGN KEY([SOCIETEID])
REFERENCES [dbo].[SOCIETE] ([SOCIETEID])
GO

ALTER TABLE [dbo].[DEPARTEMENT] CHECK CONSTRAINT [fk_dep_socid]