CREATE TABLE dbo.DEVICE_SETTINGS (
	LIBELLE VARCHAR(50),
	VALEUR VARCHAR(MAX),
	DEVICEID INT NOT NULL,
	DATECREATION DATETIME NOT NULL,
	DATEMAJ DATETIME NOT NULL,
	DATESYNCHRO DATETIME,
	CONSTRAINT DEVICE_SETTINGS_PK PRIMARY KEY (LIBELLE,DEVICEID)
);