CREATE TABLE [dbo].[DEVIS](
	[CODEDEVIS] [nvarchar](14) NOT NULL,
	[SOCIETEID] [nvarchar](14) NULL,
	[INTERLOCUTEURID] [nvarchar](14) NULL,
	[CODEAFFAIRE] [nvarchar](14) NULL,
	[CODECLIENT] [nvarchar](14) NOT NULL,
	[COMMERCIALID] [nvarchar](14) NULL,
	[CODEMODEPAIE] [nvarchar](14) NULL,
	[CODEDELAIPAIE] [nvarchar](14) NULL,
	[CODEINTERVENNANT] [nvarchar](14) NULL,
	[NODEVIS] [nvarchar](15) NULL,
	[LIBELLE] [nvarchar](80) NULL,
	[INDICEDEVIS] [int] NULL,
	[DATEEMISSION] [datetime] NOT NULL,
	[TOTALAR] [float] NULL,
	[REMISE] [float] NULL,
	[TOTALHT] [float] NULL,
	[TOTALTVA] [float] NULL,
	[TOTALTTC] [float] NULL,
	[WIZARD] [int] NULL,
	[OBSERVATION] [image] NULL,
	[ACOMPTE] [float] NULL,
	[DATECREATION] [datetime] NOT NULL,
	[DATEMAJ] [datetime] NOT NULL,
	[DATESYNCHRO] [datetime] NULL,
	[REMISE_SALLE] [float] NULL,
 CONSTRAINT [PK_CODEDEVIS] PRIMARY KEY CLUSTERED
(
	[CODEDEVIS] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]