/*******/
CREATE TABLE [dbo].DEVICE (
	DEVICEID INT NOT NULL IDENTITY(0, 1) PRIMARY KEY
	,CONTROLKEY NVARCHAR(100)
	,[NAME] NVARCHAR(200)
	,[GUICHETID] NVARCHAR(14)
	,[KEEPALIVE] [datetime] NULL
	,[REGISTERED] INT NOT NULL DEFAULT 0
	,[DATECREATION] [datetime] NOT NULL
	,[DATEMAJ] [datetime] NOT NULL
	,[DATESYNCHRO] [datetime] NULL
	)
GO
