CREATE TABLE [dbo].[ESVISITES_LOG](
	[ESVISITES_LOGID] [nvarchar](14) NOT NULL,
	[QUIID] [nvarchar](14) NULL,
	[QUITYPE] [nvarchar](40) NULL,
	[NOMPRENOM] [nvarchar](70) NULL,
	[SOCIETE] [nvarchar](70) NULL,
	[NUMBADGE] [nvarchar](200) NULL,
	[SENS] [nvarchar](50) NULL,
	[ETAT] [nvarchar](50) NULL,
	[DETAILS] [nvarchar](200) NULL,
	[PASSAGE] [datetime] NULL,
	[TYPEINSERT] [nvarchar](14) NULL,
	[REMOTEDATE] [nvarchar](20) NULL,
	[SITEID] [nvarchar](14) NULL,
	[GUICHETID] [nvarchar](14) NULL,
	[POSTE] [nvarchar](50) NULL,
	[TYPELECTEUR] [nvarchar](40) NULL,
	[ZRR_CODE] [nvarchar](25) NULL,
	[ZRR_LIB] [nvarchar](255) NULL,
	[ZRR_LS] [nvarchar](3) NULL,
	[DATECREATION] [datetime] NOT NULL,
	[DATEMAJ] [datetime] NOT NULL,
	[DATESYNCHRO] [datetime] NULL
) ON [PRIMARY]