CREATE TABLE [dbo].[EVENEMENT_TYPE](
	[EVENEMENT_TYPEID] [int] NOT NULL,
	[EVENEMENTID] [int] NULL,
	[LIBELLE] [varchar](40) NULL,
	[DATEMAJ] [datetime] NULL,
	[DATECREATION] [datetime] NULL,
	[DATESYNCHRO] [datetime] NULL
) ON [PRIMARY]