CREATE TABLE [dbo].[EVENEMENT](
	[EVENEMENTID] [int] NOT NULL,
	[LIBELLE] [nvarchar](40) NULL,
	[RAPPORTID] [int] NULL,
	[CONSIGNEID] [int] NULL,
	[ISRAPPORT] [int] NULL,
	[DATEMAJ] [datetime] NULL,
	[DATECREATION] [datetime] NULL,
	[DATESYNCHRO] [datetime] NULL,
	[DOUBLE_SIGNATURE] [int] NULL,
	[SITEID] [nvarchar](14) NULL,
	[COLOR] [int] NULL,
	[GRPEVENEMENTID] [int] NULL,
PRIMARY KEY CLUSTERED
(
	[EVENEMENTID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[EVENEMENT] ADD  DEFAULT ((-1)) FOR [GRPEVENEMENTID]