CREATE TABLE [dbo].[FACTURE](
	[CODEFACTURE] [nvarchar](14) NOT NULL,
	[CODEAFFAIRE] [nvarchar](14) NULL,
	[CODECLIENT] [nvarchar](14) NOT NULL,
	[RESIDANTID] [nvarchar](14) NULL,
	[CODEMODEPAIE] [nvarchar](14) NULL,
	[CODEDELAIPAIE] [nvarchar](14) NULL,
	[NOFACTURE] [nvarchar](15) NULL,
	[DATEEMISSION] [datetime] NULL,
	[TOTALHT] [float] NULL,
	[TOTALTVA] [float] NULL,
	[TOTALTTC] [float] NULL,
	[REGLE] [int] NULL,
	[DATEREGLEMENT] [datetime] NULL,
	[DATECREATION] [datetime] NOT NULL,
	[DATEMAJ] [datetime] NOT NULL,
	[DATESYNCHRO] [datetime] NULL,
 CONSTRAINT [PK_CODEFACTURE] PRIMARY KEY CLUSTERED
(
	[CODEFACTURE] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]