CREATE TABLE [dbo].[FORMULAIRE_VISITE](
	[FORMULAIREID] [int] NOT NULL,
	[VISITEID] [varchar](14) NOT NULL,
 CONSTRAINT [PK_FORMULAIRE_VISITEID] PRIMARY KEY CLUSTERED
(
	[FORMULAIREID] ASC,
	[VISITEID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]