CREATE TABLE [dbo].[FORMULAIRE](
	[FORMULAIREID] [int] NOT NULL,
	[FORMULAIRE_MODELEID] [int] NOT NULL,
	[REFERENCE] [int] NULL,
	[VERSION] [int] NULL,
	[LIBELLE] [nvarchar](50) NULL,
	[XML] [nvarchar](max) NULL,
	[AUTEUR] [nvarchar](100) NULL,
	[DATECREATION] [datetime] NOT NULL,
	[DATEMAJ] [datetime] NOT NULL,
	[DATESYNCHRO] [datetime] NULL,
PRIMARY KEY CLUSTERED
(
	[FORMULAIREID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]