CREATE TABLE [dbo].[GROUPE](
	[GROUPEID] [nvarchar](14) NOT NULL,
	[EXTERNALID] [nvarchar](24) NULL,
	[GROUPE] [nvarchar](80) NULL,
	[ADRESSE] [image] NULL,
	[CODEPOSTAL] [nvarchar](10) NULL,
	[VILLE] [nvarchar](40) NULL,
	[PROVINCE] [nvarchar](35) NULL,
	[PAYS] [nvarchar](35) NULL,
	[INTERDIT] [nvarchar](1) NULL,
	[DEBUTINTERDIT] [datetime] NULL,
	[FININTERDIT] [datetime] NULL,
	[DATECREATION] [datetime] NOT NULL,
	[DATEMAJ] [datetime] NOT NULL,
	[DATESYNCHRO] [datetime] NULL,
 CONSTRAINT [PK_GROUPEID] PRIMARY KEY CLUSTERED
(
	[GROUPEID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]