CREATE TABLE [dbo].[GRPSALLE] (
    [GRPSALLEID]        VARCHAR (14) NOT NULL,
    [LIBELLE]           VARCHAR (50) NULL,
    [HEUREDEBUT]        DATETIME     NULL,
    [HEUREFIN]          DATETIME     NULL,
    [OPENPRERESA]       INT          NULL,
    [CLOSEPRERESA]      INT          NULL,
    [RESA]              VARCHAR (15) NULL,
    [SITEID]            VARCHAR (14) NULL,
    [DATECREATION]      DATETIME     NULL,
    [DATEMAJ]           DATETIME     NULL,
    [SALLE_VALIDATION]  INT          DEFAULT ((0)) NULL,
    [SALLE_STATUTFORCE] VARCHAR (14) NULL,
    [USERID]            VARCHAR (14) NULL,
    [CONFIDENTIEL]      INT          DEFAULT ((0)) NULL,
    PRIMARY KEY CLUSTERED ([GRPSALLEID] ASC)
);


GO
