CREATE TABLE [dbo].[GRPSALLE_LGRESERVATION]
(
    [GRPSALLEID] NVARCHAR(14) NOT NULL, 
    [CODELGRESERVATION] NVARCHAR(14) NOT NULL, 
    CONSTRAINT [PK_GRPSALLE_LGRESERVATION] PRIMARY KEY ([GRPSALLEID], [CODELGRESERVATION])
)
