CREATE TABLE [dbo].[GRPSITE_SITE](
	[GRPSITEID] [nvarchar](14) NOT NULL,
	[SITEID] [nvarchar](14) NOT NULL,
 CONSTRAINT [PK_GRPSITE_SITE] PRIMARY KEY CLUSTERED
(
	[GRPSITEID] ASC,
	[SITEID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]