CREATE TABLE [dbo].[GRPSITE_MENU_SITE](
	[GRPSITE_MENUID] [varchar](14) NOT NULL,
	[SITEID] [varchar](14) NOT NULL,
 CONSTRAINT [PK_GRPSITE_MENU_SITE] PRIMARY KEY CLUSTERED
(
	[GRPSITE_MENUID] ASC,
	[SITEID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]