CREATE TABLE [dbo].[GRPUSER](
	[GRPUSERID] [nvarchar](14) NOT NULL,
	[LIBELLE] [nvarchar](50) NULL,
	[NIVEAU] [nvarchar](14) NULL,
	[STATUT] [nvarchar](14) NULL,
	[STATUTCHECK] [int] NULL,
	[SURRESERVATION] [nvarchar](1) NULL,
	[RESAPERIODIQUE] [nvarchar](1) NULL,
	[ACCESDRAGDROP] [nvarchar](1) NULL,
	[PLANNING] [nvarchar](5) NULL,
	[RESA] [nvarchar](15) NULL,
	[PRESTA] [nvarchar](15) NULL,
	[DATECREATION] [datetime] NULL,
	[DATEMAJ] [datetime] NULL,
	[EMAILAUTO] [nvarchar](1) NULL,
	[VALIDEUR] [int] NULL,
	[PAYANT] [int] NULL,
	[DROITSADM] [nvarchar](500) NULL,
PRIMARY KEY CLUSTERED
(
	[GRPUSERID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[GRPUSER] ADD  DEFAULT ((0)) FOR [VALIDEUR]
GO
ALTER TABLE [dbo].[GRPUSER] ADD  DEFAULT ((0)) FOR [PAYANT]