CREATE TABLE [dbo].[GRPUSER_DROITSTELEM](
	[GRPUSERID] [nvarchar](14) NOT NULL,
	[ID_DROITSTELEM] [nvarchar](14) NOT NULL,
 CONSTRAINT [PK_GRPUSER_ID_DROITSTELEM] PRIMARY KEY CLUSTERED
(
	[GRPUSERID] ASC,
	[ID_DROITSTELEM] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]