CREATE TABLE [dbo].[HLGPARTICIPANT](
	[LGPARTICIPANTID] [nvarchar](14) NULL,
	[CODELGRESERVATION] [nvarchar](14) NULL,
	[RESIDANTID] [nvarchar](14) NULL,
	[INTERLOCUTEURID] [nvarchar](14) NULL,
	[CIVILITE] [nvarchar](14) NULL,
	[NOM] [nvarchar](35) NULL,
	[PRENOM] [nvarchar](35) NULL,
	[SOCIETE] [nvarchar](35) NULL,
	[EMAIL] [nvarchar](50) NULL,
	[DATECREATION] [datetime] NULL,
	[DATEMAJ] [datetime] NULL,
	[DATESYNCHRO] [datetime] NULL
) ON [PRIMARY]