CREATE TABLE [dbo].[IMPORT_ROI](
	[IMPORT_ROIID] [nvarchar](14) NOT NULL,
	[MVT] [nvarchar](3) NULL,
	[SOURCE] [nvarchar](12) NULL,
	[ETAT] [nvarchar](6) NULL,
	[RAISON] [nvarchar](10) NULL,
	[IDENTIFIANT] [nvarchar](10) NULL,
	[QUALITECIVILITE] [nvarchar](5) NULL,
	[NOM] [nvarchar](50) NULL,
	[PRENOM] [nvarchar](32) NULL,
	[SOCIETE] [nvarchar](5) NULL,
	[UNITEMANAGERIALE] [nvarchar](20) NULL,
	[LABELUNITEMANAGERIALE] [nvarchar](100) NULL,
	[TYPEPOPULATION] [nvarchar](2) NULL,
	[TYPEPERSONNE] [nvarchar](30) NULL,
	[IESOCIETEPRESTATION] [nvarchar](100) NULL,
	[IEDEBUTMISSION] [nvarchar](17) NULL,
	[IEFINMISSION] [nvarchar](17) NULL,
	[MAIL] [nvarchar](100) NULL,
	[CODEFONCTION] [nvarchar](4) NULL,
	[FONCTION] [nvarchar](50) NULL,
	[SITE] [nvarchar](3) NULL,
	[LIBELLESITE] [nvarchar](32) NULL,
	[BATIMENT] [nvarchar](3) NULL,
	[ETAGE] [nvarchar](3) NULL,
	[NUMEROBUREAU] [nvarchar](6) NULL,
	[RUE] [nvarchar](120) NULL,
	[CODEPOSTAL] [nvarchar](5) NULL,
	[VILLE] [nvarchar](32) NULL,
	[PAYS] [nvarchar](3) NULL,
	[TELEPHONE] [nvarchar](13) NULL,
	[TELEPHONEINTERNE] [nvarchar](6) NULL,
	[FAX] [nvarchar](13) NULL,
	[CODENATURECONTRATTRAVAIL] [nvarchar](5) NULL,
	[INDABSENCELONGUEDUREE] [nvarchar](1) NULL,
	[STATUTPERSONNE] [nvarchar](2) NULL,
	[CODEANTENNE] [nvarchar](20) NULL,
	[ANCIENSITE] [nvarchar](3) NULL,
	[ANCIENCODEANTENNE] [nvarchar](20) NULL,
	[DATECREATION] [datetime] NULL,
	[DATEMAJ] [datetime] NULL,
	[THELOGIN] [nvarchar](50) NULL,
	[MANAGER] [nvarchar](20) NULL,
PRIMARY KEY CLUSTERED
(
	[IMPORT_ROIID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]