CREATE TABLE [dbo].[IMPORT_RESA](
	[ID] [nvarchar](18) NULL,
	[DATESAISIE] [nvarchar](30) NULL,
	[RNOM] [nvarchar](30) NULL,
	[RPRENOM] [nvarchar](30) NULL,
	[RMATRICULE] [nvarchar](30) NULL,
	[INOM] [nvarchar](30) NULL,
	[IPRENOM] [nvarchar](30) NULL,
	[IMATRICULE] [nvarchar](30) NULL,
	[SALLE] [nvarchar](30) NULL,
	[DATERESA] [nvarchar](30) NULL,
	[HDEBUT] [nvarchar](30) NULL,
	[HFIN] [nvarchar](30) NULL,
	[STATUT] [nvarchar](30) NULL,
	[ROBSERVATION] [nvarchar](3000) NULL,
	[REFVISITOR] [nvarchar](30) NULL,
	[USERLOGIN] [nvarchar](30) NULL
) ON [PRIMARY]