CREATE TABLE [dbo].[IMPORT_VISITES_RESA](
	[ID] [nvarchar](18) NULL,
	[RNOM] [nvarchar](30) NULL,
	[RPRENOM] [nvarchar](30) NULL,
	[RMATRICULE] [nvarchar](30) NULL,
	[RCIVILITE] [nvarchar](30) NULL,
	[REMAIL] [nvarchar](70) NULL,
	[RSOCIETE] [nvarchar](30) NULL,
	[REFRESA] [nvarchar](30) NULL
) ON [PRIMARY]