CREATE TABLE [dbo].[INTER_RSERVICE](
	[INTERLOCUTEURID] [varchar](14) NULL,
	[RSERVICEID] [varchar](14) NULL,
	[RESIDANTID] [varchar](14) NULL,
 CONSTRAINT [UNIK_INTER_RSERVICE] UNIQUE NONCLUSTERED
(
	[INTERLOCUTEURID] ASC,
	[RSERVICEID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]