CREATE TABLE [dbo].[INTER_ACTION](
	[INTERACTIONID] [int] NOT NULL,
	[INTERLOCUTEURID] [nvarchar](14) NULL,
	[ACTION_NATURE] [nvarchar](35) NULL,
	[ACTEUR_NATURE] [nvarchar](35) NULL,
	[NOMACTEUR] [nvarchar](70) NULL,
	[ACTEURID] [nvarchar](14) NULL,
	[RES_ACTION] [nvarchar](4000) NULL,
	[NOM_CHAMP] [nvarchar](50) NULL,
	[RES_AVANT] [nvarchar](250) NULL,
	[RES_APRES] [nvarchar](250) NULL,
	[ACTION_DATE] [datetime] NOT NULL,
	[DATEMAJ] [datetime] NOT NULL,
	[DATECREATION] [datetime] NOT NULL,
	[DATESYNCHRO] [datetime] NULL,
PRIMARY KEY CLUSTERED
(
	[INTERACTIONID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]