CREATE TABLE [dbo].[INTERLOCUTEUR](
	[SOCIETEID] [nvarchar](14) NOT NULL,
	[INTERLOCUTEURID] [nvarchar](14) NOT NULL,
	[CODECIVILITE] [int] NULL,
	[CODEFONCTION] [int] NULL,
	[PHONKEY] [nvarchar](35) NULL,
	[EXTERNALID] [nvarchar](24) NULL,
	[PAYS] [nvarchar](35) NULL,
	[CIVILITE] [nvarchar](30) NULL,
	[SOCIETE] [nvarchar](35) NULL,
	[NOMPRENOM] [nvarchar](70) NULL,
	[CPNOM] [nvarchar](40) NULL,
	[NOM] [nvarchar](35) NULL,
	[PRENOM] [nvarchar](35) NULL,
	[IDENTITEID] [nvarchar](14) NULL,
	[FONCTION] [nvarchar](35) NULL,
	[TELEPHONE] [nvarchar](20) NULL,
	[EMAIL] [nvarchar](150) NULL,
	[GSM] [nvarchar](20) NULL,
	[FAX] [nvarchar](20) NULL,
	[CANDIDATMAILING] [int] NULL,
	[OBS] [nvarchar](200) NULL,
	[PHOTO] [image] NULL,
	[REFIMPORTATION] [nvarchar](48) NULL,
	[IMMATRICULATION] [nvarchar](15) NULL,
	[INTERDIT] [nvarchar](1) NULL,
	[DEBUTINTERDIT] [datetime] NULL,
	[FININTERDIT] [datetime] NULL,
	[NATUREID] [nvarchar](14) NULL,
	[DATENAISSANCE] [datetime] NULL,
	[LIEUNAISSANCE] [nvarchar](70) NULL,
	[NATIONALITEID] [nvarchar](14) NULL,
	[FINVALIDITEAUTO] [datetime] NULL,
	[DATEDERNVISITE] [datetime] NULL,
	[DATEMAJ] [datetime] NOT NULL,
	[DATECREATION] [datetime] NOT NULL,
	[DATESYNCHRO] [datetime] NULL,
	[NOMJEUNEFILLE] [nvarchar](35) NULL,
	[ADRESSE] [nvarchar](150) NULL,
	[CODEPOSTAL] [nvarchar](10) NULL,
	[VILLE] [nvarchar](35) NULL,
	[SITE_CREATION] [nvarchar](35) NULL,
	[SITE_MODIF] [nvarchar](35) NULL,
	[PAYS_ADRESSE] [nvarchar](50) NULL,
	[PAYS_NAISSANCE] [nvarchar](50) NULL,
	[ENQUETE_VE] [int] NULL,
	[ENQUETE_LPE] [int] NULL,
	[TAG] [nvarchar](30) NULL,
	[DOUBLON_TRAITE] [int] NULL,
	[OFICHIERID] [int] NULL,
	[NATIONALITE_ORIGINE] [nvarchar](50) NULL,
	[DEPFRID] [int] NULL,
	[SERVICEID] [nvarchar](14) NULL,
 CONSTRAINT [PK_INTERLOCUTEURID] PRIMARY KEY CLUSTERED
(
	[INTERLOCUTEURID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
ALTER TABLE [dbo].[INTERLOCUTEUR] ADD  DEFAULT ('1') FOR [PHONKEY]
GO
ALTER TABLE [dbo].[INTERLOCUTEUR] ADD  DEFAULT ((0)) FOR [ENQUETE_VE]
GO
ALTER TABLE [dbo].[INTERLOCUTEUR] ADD  DEFAULT ((0)) FOR [ENQUETE_LPE]
GO
ALTER TABLE [dbo].[INTERLOCUTEUR] ADD  DEFAULT ((0)) FOR [DOUBLON_TRAITE]