CREATE TABLE [dbo].[JOURNAL](
	[JOURNALID] [nvarchar](14) NOT NULL,
	[USERID] [nvarchar](14) NULL,
	[TYPEACTION] [nvarchar](10) NULL,
	[TABLEID] [nvarchar](30) NULL,
	[FICHEID] [nvarchar](14) NULL,
	[DATECREATION] [datetime] NOT NULL,
	[DATEMAJ] [datetime] NOT NULL,
	[DATESYNCHRO] [datetime] NULL,
	[RESA_REF] [nvarchar](15) NULL,
	[NOMPRENOM] [nvarchar](40) NULL,
	[SALLE_NO_LIB] [nvarchar](40) NULL,
	[RESA_DHDEBUT] [datetime] NULL,
	[RESA_DHFIN] [datetime] NULL,
	[RESA_CREATION] [datetime] NULL,
 CONSTRAINT [PK_JOURNALID] PRIMARY KEY CLUSTERED
(
	[JOURNALID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]