CREATE TABLE [dbo].[JOUR](
	[JOURID] [int] NOT NULL,
	[LIBELLE] [nvarchar](40) NULL,
	[TYPE_JOUR] [nvarchar](40) NULL,
	[CL] [int] NULL,
	[DEBUT_VALIDITE] [datetime] NULL,
	[FIN_VALIDITE] [datetime] NULL,
	[DATEMAJ] [datetime] NULL,
	[DATECREATION] [datetime] NULL,
	[DATESYNCHRO] [datetime] NULL,
	[DATEOFWEEK] [int] NULL,
PRIMARY KEY CLUSTERED
(
	[JOURID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]