CREATE TABLE [dbo].[JRAPPORTLOG](
	[OJOURNALID] [int] NULL,
	[RAPPORTID] [int] NULL,
	[RPTID] [int] NULL,
	[RPTNOM] [nvarchar](20) NULL,
	[REF] [nvarchar](20) NULL,
	[VERSION] [int] NULL,
	[PERSONNELID] [int] NULL,
	[SITEID] [nvarchar](14) NULL,
	[POSTEID] [int] NULL,
	[DATEMAJ] [datetime] NULL
) ON [PRIMARY]