CREATE TABLE [dbo].[JVACATION](
	[JVACATIONID] [int] NOT NULL,
	[VACATIONID] [int] NULL,
	[OUVERTUREID] [int] NULL,
	[OUVERTURE] [datetime] NULL,
	[FERMETUREID] [int] NULL,
	[FERMETURE] [datetime] NULL,
	[SITEID] [nvarchar](14) NULL,
	[POSTEID] [int] NULL,
 CONSTRAINT [PK_CJVACATIONID] PRIMARY KEY CLUSTERED
(
	[JVACATIONID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]