CREATE TABLE [dbo].[LGPARTICIPANT](
	[LGPARTICIPANTID] [nvarchar](14) NOT NULL,
	[CODELGRESERVATION] [nvarchar](14) NULL,
	[RESIDANTID] [nvarchar](14) NULL,
	[INTERLOCUTEURID] [nvarchar](14) NULL,
	[CIVILITE] [nvarchar](14) NULL,
	[NOM] [nvarchar](35) NULL,
	[PRENOM] [nvarchar](35) NULL,
	[SOCIETE] [nvarchar](35) NULL,
	[EMAIL] [nvarchar](150) NULL,
	[DATECREATION] [datetime] NOT NULL,
	[DATEMAJ] [datetime] NOT NULL,
	[DATESYNCHRO] [datetime] NULL,
	[LGPERSONNETYPE] [nvarchar](30) NULL,
	[RVEHICULE] [nvarchar](20) NULL,
	[RIMMAT] [nvarchar](20) NULL,
	[OPERSONNEID] [nvarchar](20) NULL,
	[RPHONE] [nvarchar](20) NULL,
	[RMOBILEPHONE] [nvarchar](20) NULL,
	[SESA] [nvarchar](20) NULL, 
    [ISNOTIFIED] INT NULL DEFAULT 1 
) ON [PRIMARY]