CREATE TABLE [dbo].[LIEU](
	[LIEUID] [int] NOT NULL,
	[LIBELLE] [varchar](40) NULL,
	[DATEMAJ] [datetime] NULL,
	[DATECREATION] [datetime] NULL,
	[DATESYNCHRO] [datetime] NULL,
	[SITEID] [varchar](14) NULL, 
    CONSTRAINT [PK_LIEU] PRIMARY KEY ([LIEUID])
) ON [PRIMARY]