CREATE TABLE [dbo].[LIEUPERMIS](
	[RESIDANTID] [nvarchar](14) NOT NULL,
	[CODESALLE] [nvarchar](14) NOT NULL,
	[DATECREATION] [datetime] NOT NULL,
	[DATEMAJ] [datetime] NOT NULL,
	[DATESYNCHRO] [datetime] NULL,
 CONSTRAINT [PK_RESIDANTIDCODESALLE] PRIMARY KEY CLUSTERED
(
	[RESIDANTID] ASC,
	[CODESALLE] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]