CREATE TABLE [dbo].[LIGNE_COMMANDE](
	[LIGNE_COMMANDEID] [bigint] IDENTITY(1,1) NOT NULL,
	[COMMANDEID] [bigint] NULL,
	[CODEARTICLE] [nvarchar](14) NULL,
	[STATUT] [nvarchar](14) NULL,
	[PRIXTOTAL] [nvarchar](50) NULL,
	[QUANTITE] [int] NULL,
	[BENEFICIAIREID] [nvarchar](14) NULL,
	[CREATEURID] [nvarchar](14) NULL,
	[DEBUT] [datetime] NULL,
	[FIN] [datetime] NULL,
	[REFERENCE] [nvarchar](50) NULL,
	[LIEU] [nvarchar](500) NULL,
	[DESCRIPTION] [nvarchar](1000) NULL,
	[COMMENTAIRE] [nvarchar](max) NULL,
	[TYPE] [nvarchar](50) NULL,
	[CDR] [nvarchar](1000) NULL,
	[DATECREATION] [datetime] NULL,
	[DATEMAJ] [datetime] NULL,
PRIMARY KEY CLUSTERED
(
	[LIGNE_COMMANDEID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]