CREATE TABLE [dbo].[LOCALISATION](
	[LOCALISATIONID] [int] NOT NULL,
	[LIBELLE] [nvarchar](100) NULL,
	[SITEID] [nvarchar](14) NULL,
	[SALLE_CAGE] [nvarchar](100) NULL,
	[BAIE] [nvarchar](100) NULL,
	[LOCALISATION_TYPE] [nvarchar](50) NULL,
	[CODE] [nvarchar](100) NULL,
	[EMPREINTE] [nvarchar](100) NULL,
	[DATECREATION] [datetime] NOT NULL,
	[DATEMAJ] [datetime] NOT NULL,
	[DATESYNCHRO] [datetime] NULL,
PRIMARY KEY CLUSTERED
(
	[LOCALISATIONID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]