CREATE TABLE [dbo].[LOGDB](
	[LOGDBID] [int] IDENTITY(1,1) NOT NULL,
	[QUI] [nvarchar](50) NULL,
	[IP] [nvarchar](50) NULL,
	[URL] [nvarchar](250) NULL,
	[QUAND] [datetime] NULL,
	[REQUETE] [nvarchar](4000) NULL,
	[LATABLE] [nvarchar](100) NULL,
	[ACTION] [nvarchar](100) NULL,
	[ID] [nvarchar](100) NULL,
	[DONNEES] [nvarchar](4000) NULL,
	[SITE] [nvarchar](50) NULL,
	[POSTE] [nvarchar](50) NULL,
PRIMARY KEY CLUSTERED
(
	[LOGDBID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]