CREATE TABLE [dbo].[MARQUE](
	[CODEMARQUE] [nvarchar](14) NOT NULL,
	[SOCIETEID] [nvarchar](14) NULL,
	[LIBELLE] [nvarchar](35) NULL,
	[REMARQUES] [image] NULL,
	[IMAGE] [image] NULL,
	[DATECREATION] [datetime] NOT NULL,
	[DATEMAJ] [datetime] NOT NULL,
	[DATESYNCHRO] [datetime] NULL,
 CONSTRAINT [PK_CODEMARQUE] PRIMARY KEY CLUSTERED
(
	[CODEMARQUE] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]