CREATE TABLE [dbo].[MENU_SERVICE](
	[MENU_SERVICEID] [int] IDENTITY(1,1) NOT NULL,
	[SITEID] [varchar](14) NULL,
	[LIBELLE_FR] [varchar](100) NULL,
	[LIBELLE_EN] [varchar](100) NULL,
	[ORDRE] [int] NULL,
PRIMARY KEY CLUSTERED
(
	[MENU_SERVICEID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]