CREATE TABLE [dbo].[NATURECOLIS](
	[NATURECOLISID] [int] NOT NULL,
	[LIBELLE] [varchar](50) NULL,
	[DATECREATION] [datetime] NOT NULL,
	[DATEMAJ] [datetime] NOT NULL,
	[LIBELLE_EN] [varchar](35) NULL,
PRIMARY KEY CLUSTERED
(
	[NATURECOLISID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]