CREATE TABLE [dbo].[OCHECKLIST](
	[OCHECKLISTID] [int] NOT NULL,
	[LIBELLE] [nvarchar](200) NULL,
	[NUMERO] [int] NULL,
	[PERSONNELID] [int] NULL,
	[UNOMPRENOM] [nvarchar](300) NULL,
	[ETAT] [nvarchar](1000) NULL,
	[DETAIL] [nvarchar](4000) NULL,
	[OBSERVATION] [nvarchar](4000) NULL,
	[CHKITEM] [nvarchar](4000) NULL,
	[SITEID] [nvarchar](14) NULL,
	[CHECKDATE] [datetime] NULL,
	[DATECREATION] [datetime] NULL,
	[DATEMAJ] [datetime] NULL,
PRIMARY KEY CLUSTERED
(
	[OCHECKLISTID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]