CREATE TABLE [dbo].[OCONSIGNE](
	[OCONSIGNEID] [int] NOT NULL,
	[LIBELLE] [nvarchar](500) NULL,
	[PAGE] [int] NULL,
	[DATECONS] [datetime] NULL,
	[DATEMAJ] [datetime] NULL,
	[DATECREATION] [datetime] NULL,
	[DATESYNCHRO] [datetime] NULL,
	[FILE_PDF] [nvarchar](250) NULL,
	[SITEID] [nvarchar](14) NULL,
	[POSTEID] [int] NULL,
 CONSTRAINT [PK_OCONSIGNEID] PRIMARY KEY CLUSTERED
(
	[OCONSIGNEID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]