CREATE TABLE [dbo].[ODROIT](
	[ODROITID] [int] NOT NULL,
	[LIBELLE] [nvarchar](50) NULL,
	[OMACCESS] [nvarchar](15) NULL,
	[DATEMAJ] [datetime] NULL,
	[DATECREATION] [datetime] NULL,
	[DATESYNCHRO] [datetime] NULL,
 CONSTRAINT [PK_ODROITID] PRIMARY KEY CLUSTERED
(
	[ODROITID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]