CREATE TABLE [dbo].[PARAMETRES](
	[PREENREG] [int] NULL,
	[SECURITE] [int] NULL,
	[I_PLAN] [int] NULL,
	[IMPRESSION] [int] NULL,
	[INFOBULLES] [int] NULL,
	[CHIMGVT] [nvarchar](4000) NULL,
	[DATESORTIVI] [datetime] NULL,
	[CHIMGRE] [nvarchar](4000) NULL,
	[DERNVISITE] [int] NULL,
	[CHIMGPL] [nvarchar](4000) NULL,
	[SORTIVI] [int] NULL,
	[PURGEVP] [int] NULL,
	[APPETEL] [int] NULL,
	[MONOSOC] [int] NOT NULL,
	[MODULE] [int] NULL,
	[GESPHOTO] [nvarchar](1) NULL,
	[TRCLUNIK] [int] NULL,
	[TYPEANNU] [nvarchar](1) NULL,
	[DATEIMP] [datetime] NULL,
	[IMPORTAUTO] [nvarchar](1) NULL,
	[GESTCASIER] [nvarchar](1) NULL,
	[NBESSAIS] [int] NOT NULL,
	[REFIMPORTATION] [nvarchar](48) NULL,
	[SORTIFINVI] [int] NULL,
	[DATECREATION] [datetime] NOT NULL,
	[DATEMAJ] [datetime] NOT NULL,
	[DATESYNCHRO] [datetime] NULL
) ON [PRIMARY]