CREATE TABLE [dbo].[PARKING](
	[SITEID] [nvarchar](14) NULL,
	[PARKINGID] [nvarchar](14) NOT NULL,
	[SOCIETEID] [nvarchar](14) NULL,
	[PARKING] [nvarchar](6) NULL,
	[STATUTPARKING] [nvarchar](20) NULL,
	[TYPE_PARKING] [nvarchar](30) NULL,
	[DATECREATION] [datetime] NOT NULL,
	[DATEMAJ] [datetime] NOT NULL,
	[DATESYNCHRO] [datetime] NULL,
	[CAPACITE] [int] NULL,
	[HEURE_SORTIE] [datetime] NULL,
 CONSTRAINT [PK_PARKINGID] PRIMARY KEY CLUSTERED
(
	[PARKINGID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[PARKING]  WITH CHECK ADD  CONSTRAINT [fk_park_siteid] FOREIGN KEY([SITEID])
REFERENCES [dbo].[SITE] ([SITEID])
GO

ALTER TABLE [dbo].[PARKING] CHECK CONSTRAINT [fk_park_siteid]