CREATE TABLE [dbo].[PASSAGERTAXI](
	[ID_PASSAGERTAXI] [int] NOT NULL,
	[ID_COURSE] [int] NULL,
	[RESIDANTID] [nvarchar](14) NULL,
	[INTERLOCUTEURID] [nvarchar](14) NULL,
	[CONTACT] [nvarchar](200) NULL,
	[HANDICAP] [nvarchar](200) NULL,
	[ANIMAL] [nvarchar](200) NULL,
	[ORDRE] [int] NULL,
	[DATECREATION] [datetime] NOT NULL,
	[DATEMAJ] [datetime] NOT NULL,
	[DATESYNCHRO] [datetime] NULL,
	[DEMANDEUR] [nvarchar](14) NULL,
PRIMARY KEY CLUSTERED
(
	[ID_PASSAGERTAXI] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]