CREATE TABLE [dbo].[PERIPHERIQUE_TRAITEMENT](
	[PERIPHERIQUE_TRAITEMENTID] [int] NOT NULL,
	[LIBELLE] [varchar](50) NULL,
	[FAMILLE] [int] NULL,
	[DATECREATION] [datetime] NOT NULL,
	[DATEMAJ] [datetime] NOT NULL,
PRIMARY KEY CLUSTERED
(
	[PERIPHERIQUE_TRAITEMENTID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]