CREATE TABLE [dbo].[PERSONNEL](
	[PERSONNELID] [int] NOT NULL,
	[THEPASSWORD] [nvarchar](250) NULL,
	[THELOGIN] [nvarchar](50) NULL,
	[NOM] [nvarchar](50) NULL,
	[PRENOM] [nvarchar](50) NULL,
	[DATE_NAISSANCE] [datetime] NULL,
	[DATE_EMBAUCHE] [datetime] NULL,
	[DATE_ARRIVEE] [datetime] NULL,
	[TEL] [nvarchar](10) NULL,
	[DEBUT_VALIDITE] [datetime] NULL,
	[FIN_VALIDITE] [datetime] NULL,
	[QUALIFID] [int] NULL,
	[CODEFONCTION] [int] NULL,
	[MEDICAL_LAST] [datetime] NULL,
	[MEDICAL_NEXT] [datetime] NULL,
	[ODROITID] [int] NULL,
	[SITEID] [nvarchar](14) NULL,
	[PHOTO] [image] NULL,
	[EMPPK] [image] NULL,
	[EMPPK_LEN] [int] NULL,
	[TAG] [nvarchar](30) NULL,
	[CSECURITENUM] [nvarchar](50) NULL,
	[CSECURITEFIN] [datetime] NULL,
	[CSECURITEACT] [nvarchar](10) NULL,
	[CSECURITEDEP] [nvarchar](100) NULL,
	[ACTIF] [int] NULL,
	[DATEMAJ] [datetime] NULL,
	[DATECREATION] [datetime] NULL,
	[DATESYNCHRO] [datetime] NULL,
	[EQUIPEID] [int] NULL,
 CONSTRAINT [PK_PERSONNELID] PRIMARY KEY CLUSTERED
(
	[PERSONNELID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
ALTER TABLE [dbo].[PERSONNEL] ADD  DEFAULT ((1)) FOR [ACTIF]