CREATE TABLE [dbo].[PERSONNE](
	[PERSONNEID] [int] NOT NULL,
	[LIBELLE] [nvarchar](100) NULL,
	[OBSERVATION] [nvarchar](250) NULL,
	[DATEMAJ] [datetime] NULL,
	[DATECREATION] [datetime] NULL,
	[DATESYNCHRO] [datetime] NULL,
	[SITEID] [nvarchar](14) NULL,
 CONSTRAINT [PK_PERSONNEID] PRIMARY KEY CLUSTERED
(
	[PERSONNEID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]