CREATE TABLE [dbo].[PERSONNE_ACX_LOG](
	[PERSONNEID] [int] IDENTITY(1,1) NOT NULL,
	[TYPEPERSONNE] [nvarchar](20) NULL,
	[NOM] [nvarchar](70) NULL,
	[PRENOM] [nvarchar](70) NULL,
	[SESA] [nvarchar](20) NULL,
	[JOURFIN] [int] NULL,
	[ACKNOWLEDGED] [int] NULL,
	[RECEIVED] [int] NULL,
	[MESSAGEFROMACX] [nvarchar](100) NULL,
	[SITEID] [nvarchar](14) NULL,
	[DATECREATION] [datetime] NULL,
	[DATEMAJ] [datetime] NULL,
	[DATEDEBUT] [datetime] NULL,
	[DATEFIN] [datetime] NULL,
	[NUMSITEACX] [nvarchar](10) NULL,
	[SITE] [nvarchar](40) NULL,
 CONSTRAINT [PK_PERSONNEACXLOGID] PRIMARY KEY CLUSTERED
(
	[PERSONNEID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[PERSONNE_ACX_LOG] ADD  DEFAULT ((0)) FOR [ACKNOWLEDGED]
GO
ALTER TABLE [dbo].[PERSONNE_ACX_LOG] ADD  DEFAULT ((0)) FOR [RECEIVED]