CREATE TABLE [dbo].[PLANS](
	[PLANID] [varchar](14) NOT NULL,
	[EXTERNALID] [varchar](24) NULL,
	[LIBELLE] [varchar](35) NULL,
	[IMAGE] [image] NULL,
	[OBSERVATION] [image] NULL,
	[DATECREATION] [datetime] NOT NULL,
	[DATEMAJ] [datetime] NOT NULL,
	[DATESYNCHRO] [datetime] NULL,
 CONSTRAINT [PK_PLANID] PRIMARY KEY CLUSTERED
(
	[PLANID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]