CREATE TABLE [dbo].[POSTE_CHECKLIST](
	[CHECKLISTID] [int] NOT NULL,
	[POSTEID] [int] NOT NULL,
PRIMARY KEY CLUSTERED
(
	[CHECKLISTID] ASC,
	[POSTEID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]