CREATE TABLE [dbo].[PROFIL_CTRL](
	[PROFIL_CTRLID] [int] NOT NULL,
	[PROFIL_CTRL] [nvarchar](100) NULL,
	[PROFILDEFAULT] [int] NULL,
	[SITEID] [nvarchar](14) NULL,
	[PROFIL_CTRLID_EXT] [nvarchar](50) NULL,
	[CODE_CLASSE] [int] NULL,
	[ASCENSEUR] [nvarchar](50) NULL,
	[DATECREATION] [datetime] NOT NULL,
	[DATEMAJ] [datetime] NOT NULL,
	[DATESYNCHRO] [datetime] NULL,
PRIMARY KEY CLUSTERED
(
	[PROFIL_CTRLID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[PROFIL_CTRL] ADD  DEFAULT ((0)) FOR [PROFILDEFAULT]