CREATE TABLE [dbo].[PROFIL_CTRL_LECTEUR](
	[PROFIL_CTRL_LECTEURID] [int] NOT NULL,
	[CTRLREADER] [nvarchar](50) NULL,
	[CTRLREADERID] [nvarchar](20) NULL,
	[PROFIL_CTRL] [nvarchar](100) NULL,
	[PROFIL_CTRLID_EXT] [nvarchar](50) NULL,
	[SITEID] [nvarchar](14) NULL,
	[DATECREATION] [datetime] NOT NULL,
	[DATEMAJ] [datetime] NOT NULL,
	[DATESYNCHRO] [datetime] NULL,
PRIMARY KEY CLUSTERED
(
	[PROFIL_CTRL_LECTEURID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]