CREATE TABLE [dbo].[QUALIF](
	[QUALIFID] [int] NOT NULL,
	[LIBELLE] [nvarchar](20) NULL,
	[DATEMAJ] [datetime] NULL,
	[DATECREATION] [datetime] NULL,
	[DATESYNCHRO] [datetime] NULL,
 CONSTRAINT [PK_QUALIFID] PRIMARY KEY CLUSTERED
(
	[QUALIFID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]