CREATE TABLE [dbo].[RAPPORT](
	[RAPPORTID] [int] NOT NULL,
	[LIBELLE] [nvarchar](40) NULL,
	[NOMTABLE] [nvarchar](50) NULL,
	[DETAILS] [nvarchar](6000) NULL,
	[AUTEURID] [int] NULL,
	[DATEMAJ] [datetime] NULL,
	[DATECREATION] [datetime] NULL,
	[DATESYNCHRO] [datetime] NULL,
	[SITEID] [nvarchar](14) NULL,
	[POSTEID] [int] NULL,
	[TYPERAPPORT] [int] NULL,
 CONSTRAINT [PK_RAPPORTID] PRIMARY KEY CLUSTERED
(
	[RAPPORTID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]