CREATE TABLE [dbo].[RAPPEL](
	[RAPPELID] [int] IDENTITY(1,1) NOT NULL,
	[CODELGRESERVATION] [nvarchar](14) NULL,
	[TEMPS] [nvarchar](50) NULL,
	[UNITE] [nvarchar](50) NULL,
	[DATERAPPEL] [datetime] NULL,
	[ETAT] [int] NULL,
	[DATECREATION] [datetime] NULL,
	[DATEMAJ] [datetime] NULL,
PRIMARY KEY CLUSTERED
(
	[RAPPELID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[RAPPEL] ADD  DEFAULT ((0)) FOR [ETAT]