CREATE TABLE [dbo].[REGLE_GRPVALIDEUR](
	[REGLEID] [int] NOT NULL,
	[GRPVALIDEURID] [int] NOT NULL,
 CONSTRAINT [PK_REGLE_GRPVALIDEUR] PRIMARY KEY CLUSTERED
(
	[REGLEID] ASC,
	[GRPVALIDEURID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]