CREATE TABLE [dbo].[REGLES](
	[REGLEID] [int] NOT NULL,
	[LIBELLE] [nvarchar](50) NULL,
	[RANGREGLE] [int] NULL,
	[TYPEVISITE] [int] NULL,
	[TYPEACTION] [int] NULL,
	[ACTIONBLOQUANTE] [int] NULL,
	[TYPEREGLE] [int] NULL,
	[FREE1] [nvarchar](35) NULL,
	[FREE2] [int] NULL,
	[FREE3] [nvarchar](35) NULL,
	[FREE4] [int] NULL,
	[FREE5] [int] NULL,
	[FREE6] [int] NULL,
	[FREE7] [nvarchar](35) NULL,
	[MESSAGE] [nvarchar](100) NULL,
	[FREE8] [nvarchar](100) NULL,
	[MESSAGEACC] [nvarchar](100) NULL,
	[SITEID] [nvarchar](14) NULL,
	[PERIODE] [nvarchar](35) NULL,
	[DUREE] [nvarchar](35) NULL,
	[FLAG_TIC] [int] NULL,
	[STATUT] [int] NULL,
	[NATUREVISITE] [nvarchar](14) NULL,
	[BYPASS] [int] NULL,
	[CATEGORIE] [nvarchar](30) NULL,
	[GRPVALIDEURID] [int] NULL,
	[DATECREATION] [datetime] NULL,
	[DATEMAJ] [datetime] NULL,
	[DATESYNCHRO] [datetime] NULL,
	[RANGREGLE_GES] [int] NULL,
PRIMARY KEY CLUSTERED
(
	[REGLEID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[REGLES] ADD  DEFAULT ((0)) FOR [FREE5]
GO
ALTER TABLE [dbo].[REGLES] ADD  DEFAULT ((0)) FOR [FREE6]
GO
ALTER TABLE [dbo].[REGLES] ADD  DEFAULT ((0)) FOR [FLAG_TIC]
GO
ALTER TABLE [dbo].[REGLES] ADD  DEFAULT ((1)) FOR [STATUT]
GO
ALTER TABLE [dbo].[REGLES] ADD  DEFAULT ('-2') FOR [NATUREVISITE]