CREATE TABLE [dbo].[REGLE_ACTION](
	[REGLEID] [int] NOT NULL,
	[ACTIONID] [int] NOT NULL,
 CONSTRAINT [PK_REGLE_ACTION] PRIMARY KEY CLUSTERED
(
	[REGLEID] ASC,
	[ACTIONID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]