CREATE TABLE [dbo].[RESERVATION](
	[CODERESERVATION] [nvarchar](14) NOT NULL,
	[CODETYPERESERVATION] [nvarchar](14) NULL,
	[PRIORITE] [int] NULL,
	[SOCIETEID] [nvarchar](14) NULL,
	[INTERLOCUTEURID] [nvarchar](14) NULL,
	[USERID] [nvarchar](14) NOT NULL,
	[CODEANIMATEUR] [nvarchar](14) NULL,
	[DATERETROCESSION] [datetime] NULL,
	[CODESTATUT] [nvarchar](14) NULL,
	[REFRESERVATION] [nvarchar](15) NULL,
	[NBPERSDEMANDE] [int] NULL,
	[NBPERSREEL] [int] NULL,
	[LIBELLE] [nvarchar](1000) NULL,
	[REMISE] [float] NULL,
	[PRIXRESERVATION] [float] NULL,
	[PRIXFACTUREE] [float] NULL,
	[COMMENTAIRE] [nvarchar](3000) NULL,
	[UPDATEDBY] [nvarchar](14) NULL,
	[DEVIS] [int] NULL,
	[FACTURE] [int] NULL,
	[DATECREATION] [datetime] NOT NULL,
	[DATEMAJ] [datetime] NOT NULL,
	[DATESYNCHRO] [datetime] NULL,
	[IMPUTATIONID] [nvarchar](14) NULL,
	[SALLE_VALIDEE] [int] NULL,
	[EMETTEUR] [nvarchar](200) NULL,
	[DEBUTFORMATION] [datetime] NULL,
	[FINFORMATION] [datetime] NULL,
	[HEUREFORMATION] [datetime] NULL,
	[TITREFORMATION] [nvarchar](500) NULL,
	[REFFORMATION] [nvarchar](200) NULL,
	[EMETTEURID] [nvarchar](14) NULL,
 CONSTRAINT [PK_CODERESERVATION] PRIMARY KEY CLUSTERED
(
	[CODERESERVATION] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[RESERVATION] ADD  DEFAULT ((0)) FOR [SALLE_VALIDEE]