CREATE TABLE [dbo].[RESERVATIONCELL](
	[CODERESERVATION] [nvarchar](14) NOT NULL,
	[CODELGRESERVATION] [nvarchar](14) NOT NULL,
	[CODERESERVATIONCELL] [nvarchar](14) NOT NULL,
	[CODESTATUT] [nvarchar](14) NULL,
	[CODESALLE] [nvarchar](14) NULL,
	[COLOR] [int] NULL,
	[CELLTYPE] [nvarchar](1) NULL,
	[HEUREDEBUT] [datetime] NULL,
	[HEUREFIN] [datetime] NULL,
	[RESERVATIONDATE] [datetime] NULL,
 CONSTRAINT [PK_CODERESALGRESARESACELL] PRIMARY KEY CLUSTERED
(
	[CODERESERVATION] ASC,
	[CODELGRESERVATION] ASC,
	[CODERESERVATIONCELL] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]