CREATE TABLE [dbo].[RESIDANT_SITE_PROFIL](
	[RESIDANTID] [varchar](14) NULL,
	[SITEID] [varchar](14) NULL,
	[PROFIL_CTRLID] [int] NULL,
	[DATECREATION] [datetime] NULL,
	[DATEMAJ] [datetime] NULL,
	[DATESYNCHRO] [datetime] NULL
) ON [PRIMARY]