CREATE TABLE [dbo].[RESIDANTS](
	[SOCIETEID] [nvarchar](14) NOT NULL,
	[RESIDANTID] [nvarchar](14) NOT NULL,
	[PLANID] [nvarchar](14) NULL,
	[BUREAUID] [nvarchar](250) NULL,
	[CODECIVILITE] [int] NULL,
	[CODEFONCTION] [int] NULL,
	[PHONKEY] [nvarchar](35) NULL,
	[EXTERNALID] [nvarchar](24) NULL,
	[SOCIETE] [nvarchar](35) NULL,
	[CIVILITE] [nvarchar](30) NULL,
	[NOMPRENOM] [nvarchar](70) NULL,
	[NOMJEUNEFILLE] [nvarchar](35) NULL,
	[CPNOM] [nvarchar](250) NULL,
	[NOM] [nvarchar](35) NULL,
	[PRENOM] [nvarchar](35) NULL,
	[FONCTION] [nvarchar](35) NULL,
	[SERVICEID] [nvarchar](14) NULL,
	[TELEPHONE] [nvarchar](20) NULL,
	[EMAIL] [nvarchar](150) NULL,
	[GSM] [nvarchar](20) NULL,
	[FAX] [nvarchar](20) NULL,
	[CANDIDATMAILING] [nvarchar](1) NULL,
	[MATRICULE] [nvarchar](50) NULL,
	[OBSERVATIONS] [image] NULL,
	[PHOTO] [image] NULL,
	[PERSOADRESSE] [image] NULL,
	[PERSOCP] [nvarchar](10) NULL,
	[PERSOVILLE] [nvarchar](35) NULL,
	[PERSOPROVINCE] [nvarchar](35) NULL,
	[PERSOPAYS] [nvarchar](35) NULL,
	[PERSOTELEPHONE] [nvarchar](20) NULL,
	[ISUSER] [nvarchar](10) NULL,
	[MUSTCHANGEPWD] [int] NULL,
	[THEPASSWORD] [nvarchar](250) NOT NULL,
	[THELOGIN] [nvarchar](50) NOT NULL,
	[USERTYPE] [int] NULL,
	[SHORTNAME] [int] NULL,
	[ENABLED] [nvarchar](1) NULL,
	[SITEID] [nvarchar](14) NULL,
	[SITE] [nvarchar](40) NULL,
	[SERVICE] [nvarchar](40) NULL,
	[DEPARTEMENT] [nvarchar](40) NULL,
	[PLANSLIBELLE] [nvarchar](40) NULL,
	[DEPTID] [nvarchar](14) NULL,
	[ETAGEID] [nvarchar](14) NULL,
	[BATIMENT] [nvarchar](60) NULL,
	[BATIMENTID] [nvarchar](14) NULL,
	[ETAGE] [nvarchar](7) NULL,
	[BUREAU] [nvarchar](15) NULL,
	[REFIMPORTATION] [nvarchar](48) NULL,
	[CODEACCES] [nvarchar](24) NULL,
	[DATEENTREE] [datetime] NULL,
	[DATESORTIE] [datetime] NULL,
	[BOITEPOSTALE] [nvarchar](7) NULL,
	[PARKING] [nvarchar](7) NULL,
	[HABILITATIONVISITE] [nvarchar](1) NULL,
	[LISTEROUGE] [nvarchar](1) NULL,
	[ISEXTERN] [nvarchar](1) NULL,
	[ISRESIDENT] [nvarchar](1) NULL,
	[ISACTIF] [nvarchar](1) NULL,
	[HARRIVEE] [datetime] NULL,
	[HDEPART] [datetime] NULL,
	[INTERDIT] [nvarchar](1) NULL,
	[DEBUTINTERDIT] [datetime] NULL,
	[FININTERDIT] [datetime] NULL,
	[NATUREID] [nvarchar](14) NULL,
	[DATENAISSANCE] [datetime] NULL,
	[LIEUNAISSANCE] [nvarchar](70) NULL,
	[NATIONALITEID] [nvarchar](14) NULL,
	[NBBDGIMPR] [int] NULL,
	[DIRECTIONID] [nvarchar](14) NULL,
	[DIRECTION] [nvarchar](35) NULL,
	[PASSWORD1] [nvarchar](250) NULL,
	[PASSWORD2] [nvarchar](250) NULL,
	[PASSWORD3] [nvarchar](250) NULL,
	[DATEFINVALPWD] [datetime] NULL,
	[IMMATRICULATION] [nvarchar](15) NULL,
	[TAG] [nvarchar](30) NULL,
	[DATEMAJ] [datetime] NOT NULL,
	[DATECREATION] [datetime] NOT NULL,
	[DATESYNCHRO] [datetime] NULL,
	[VERROU] [int] NULL,
	[VIP] [int] NULL,
	[ETRANGER] [int] NULL,
	[CONTRAT] [nvarchar](50) NULL,
	[BORNE_ELECTRIQUE] [nvarchar](10) NULL,
	[PAYSNAISSANCEID] [nvarchar](14) NULL,
	[PINCODE] [nvarchar](150) NULL,
 [ISNOTIFIED] INT NULL DEFAULT 1, 
    CONSTRAINT [PK_RESIDANTID] PRIMARY KEY CLUSTERED
(
	[RESIDANTID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
ALTER TABLE [dbo].[RESIDANTS]  WITH CHECK ADD  CONSTRAINT [fk_resi_servid] FOREIGN KEY([SERVICEID])
REFERENCES [dbo].[SERVICE] ([SERVICEID])
GO

ALTER TABLE [dbo].[RESIDANTS] CHECK CONSTRAINT [fk_resi_servid]
GO
ALTER TABLE [dbo].[RESIDANTS]  WITH CHECK ADD  CONSTRAINT [fk_resi_siteid] FOREIGN KEY([SITEID])
REFERENCES [dbo].[SITE] ([SITEID])
GO

ALTER TABLE [dbo].[RESIDANTS] CHECK CONSTRAINT [fk_resi_siteid]
GO
ALTER TABLE [dbo].[RESIDANTS]  WITH CHECK ADD  CONSTRAINT [fk_resi_socid] FOREIGN KEY([SOCIETEID])
REFERENCES [dbo].[SOCIETE] ([SOCIETEID])
GO

ALTER TABLE [dbo].[RESIDANTS] CHECK CONSTRAINT [fk_resi_socid]
GO
ALTER TABLE [dbo].[RESIDANTS] ADD  DEFAULT ('0') FOR [PHONKEY]
GO
ALTER TABLE [dbo].[RESIDANTS] ADD  DEFAULT ('1') FOR [ISRESIDENT]
GO
ALTER TABLE [dbo].[RESIDANTS] ADD  DEFAULT ((0)) FOR [VERROU]
GO
ALTER TABLE [dbo].[RESIDANTS] ADD  DEFAULT ((0)) FOR [VIP]
GO
ALTER TABLE [dbo].[RESIDANTS] ADD  DEFAULT ((0)) FOR [ETRANGER]
GO
ALTER TABLE [dbo].[RESIDANTS] ADD  DEFAULT ((0)) FOR [BORNE_ELECTRIQUE]