CREATE TABLE [dbo].[RESIDANT_CTRL](
	[RESIDANT_CTRLID] [int] NOT NULL,
	[RESIDANTID] [nvarchar](14) NULL,
	[ACTION] [int] NOT NULL,
	[SITEID] [nvarchar](14) NULL,
	[SITE] [nvarchar](80) NULL,
	[EMETTEUR] [nvarchar](80) NULL,
	[DH_POST] [datetime] NOT NULL,
	[DH_PROCEED] [datetime] NULL,
	[IDENT] [nvarchar](80) NOT NULL,
	[STATUT] [int] NULL,
	[TXT_ERR] [nvarchar](80) NULL,
	[DEB_VAL] [datetime] NULL,
	[FIN_VAL] [datetime] NULL,
	[NOM] [nvarchar](40) NULL,
	[PRENOM] [nvarchar](40) NULL,
	[SOCIETE] [nvarchar](40) NULL,
	[CODE_ANTENNE] [nvarchar](40) NULL,
	[MATRICULE] [nvarchar](40) NULL,
	[ANTI_RETOUR] [int] NULL,
	[CODE_CLASSE] [int] NULL,
	[DATA_01] [nvarchar](80) NULL,
	[DATA_02] [nvarchar](80) NULL,
	[DATA_03] [nvarchar](80) NULL,
	[DATA_04] [nvarchar](80) NULL,
	[DATA_05] [nvarchar](80) NULL,
	[DATA_06] [nvarchar](80) NULL,
	[DATA_07] [nvarchar](80) NULL,
	[DATA_08] [nvarchar](80) NULL,
	[DATA_09] [nvarchar](80) NULL,
	[DATA_10] [nvarchar](80) NULL,
	[ACCES_01] [nvarchar](4000) NULL,
	[ACCES_02] [nvarchar](4000) NULL,
	[ACCES_03] [nvarchar](4000) NULL,
	[ACCES_04] [nvarchar](4000) NULL,
	[ACCES_05] [nvarchar](4000) NULL,
	[ACCES_06] [nvarchar](4000) NULL,
	[ACCES_07] [nvarchar](4000) NULL,
	[ACCES_08] [nvarchar](4000) NULL,
	[ACCES_09] [nvarchar](4000) NULL,
	[ACCES_10] [nvarchar](4000) NULL,
PRIMARY KEY CLUSTERED
(
	[RESIDANT_CTRLID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]