CREATE TABLE [dbo].[RUE](
	[RUEID] [int] NOT NULL,
	[LIBELLE] [nvarchar](60) NULL,
	[DATEMAJ] [datetime] NULL,
	[DATECREATION] [datetime] NULL,
	[DATESYNCHRO] [datetime] NULL,
	[SITEID] [nvarchar](14) NULL,
 CONSTRAINT [PK_RUEID] PRIMARY KEY CLUSTERED
(
	[RUEID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]