CREATE TABLE [dbo].[SALLE](
	[SITEID] [nvarchar](14) NULL,
	[SOCIETEID] [nvarchar](14) NULL,
	[BATIMENTID] [nvarchar](14) NOT NULL,
	[CODESALLE] [nvarchar](14) NOT NULL,
	[LIBELLE] [nvarchar](35) NULL,
	[NOSALLE] [nvarchar](15) NULL,
	[SORTORDER] [int] NULL,
	[INDISPONIBLE] [int] NULL,
	[INDISPCAUSE] [image] NULL,
	[INDISPDEBUT] [datetime] NULL,
	[INDISPFIN] [datetime] NULL,
	[AMENAGFIXE] [int] NULL,
	[RAISONSOCIALE] [nvarchar](35) NULL,
	[ADRESSE] [image] NULL,
	[CP] [nvarchar](7) NULL,
	[VILLE] [nvarchar](35) NULL,
	[TELEPHONE] [nvarchar](20) NULL,
	[TELEPHONE2] [nvarchar](20) NULL,
	[OBSERVATIONS] [nvarchar](3000) NULL,
	[PLANACCES] [image] NULL,
	[IMAGE] [image] NULL,
	[PORTE_CLE] [nvarchar](50) NULL,
	[PORTE_OPTION] [nvarchar](300) NULL,
	[DATEMAJ] [datetime] NOT NULL,
	[DATECREATION] [datetime] NOT NULL,
	[DATESYNCHRO] [datetime] NULL,
	[EXTERNALID] [nvarchar](200) NULL,
	[PARTICIPANTS] [nvarchar](1) NULL,
	[CARDIBOXID] [nvarchar](15) NULL,
	[ICONTROLE] [nvarchar](50) NULL,
	[ICONTROLE_STATUS] [nvarchar](50) NULL,
	[ICONTROLE_DATE] [datetime] NULL,
	[EMAIL] [nvarchar](150) NULL,
	[TYPESALLE] [int] NULL,
 [ISSYNC] INT NULL DEFAULT 0, 
    CONSTRAINT [PK_CODESALLE] PRIMARY KEY CLUSTERED
(
	[CODESALLE] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
ALTER TABLE [dbo].[SALLE]  WITH CHECK ADD  CONSTRAINT [fk_salle_batid] FOREIGN KEY([BATIMENTID])
REFERENCES [dbo].[BATIMENT] ([BATIMENTID])
GO

ALTER TABLE [dbo].[SALLE] CHECK CONSTRAINT [fk_salle_batid]
GO
ALTER TABLE [dbo].[SALLE]  WITH CHECK ADD  CONSTRAINT [fk_salle_siteid] FOREIGN KEY([SITEID])
REFERENCES [dbo].[SITE] ([SITEID])
GO

ALTER TABLE [dbo].[SALLE] CHECK CONSTRAINT [fk_salle_siteid]