CREATE TABLE [dbo].[SECTEUR](
	[SECTEURID] [int] NOT NULL,
	[LIBELLE] [nvarchar](40) NULL,
	[DATEMAJ] [datetime] NULL,
	[DATECREATION] [datetime] NULL,
	[DATESYNCHRO] [datetime] NULL,
	[SITEID] [nvarchar](14) NULL,
 CONSTRAINT [PK_SECTEURID] PRIMARY KEY CLUSTERED
(
	[SECTEURID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]