CREATE TABLE [dbo].[SIGNDOCUMENT](
	[SIGNDOCUMENTID] [int] IDENTITY(1,1) NOT NULL,
	[SIGNDOCUMENT_TEMPLATEID] [int] NOT NULL,
	[LIBELLE] [nvarchar](500) NULL,
	[MESSAGE] [nvarchar](4000) NULL,
	[PERIOD] [int] NULL,
	[TARGETTYPE] [nvarchar](100) NULL,
	[TARGETID] [nvarchar](14) NULL,
	[OFICHIERID] [int] NULL,
	[SIGNATUREID] [int] NULL,
	[ISMUSTSIGNED] [int] NULL,
	[DATECREATION] [datetime] NOT NULL,
	[DATEMAJ] [datetime] NOT NULL,
	[DATESYNCHRO] [datetime] NULL,
	[DOCSIGNEDID] [int] NULL,
	[SITEID] [nvarchar](14) NULL,
	[SENDEMAIL] [int] NULL,
[ORDER] INT NULL, 
    PRIMARY KEY CLUSTERED
(
	[SIGNDOCUMENTID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[SIGNDOCUMENT] ADD  DEFAULT ((0)) FOR [ISMUSTSIGNED]
GO
ALTER TABLE [dbo].[SIGNDOCUMENT] ADD  DEFAULT ((0)) FOR [SENDEMAIL]