CREATE TABLE [dbo].[SITE](
	[SITEID] [nvarchar](14) NOT NULL,
	[LIBELLE] [nvarchar](35) NULL,
	[ADRESSE] [image] NULL,
	[CP] [nvarchar](10) NULL,
	[VILLE] [nvarchar](35) NULL,
	[PAYS] [nvarchar](35) NULL,
	[TELEPHONE] [nvarchar](20) NULL,
	[FAX] [nvarchar](20) NULL,
	[SORTORDER] [int] NULL,
	[PROVINCE] [nvarchar](35) NULL,
	[EXTERNALID] [nvarchar](24) NULL,
	[PLANID] [nvarchar](14) NULL,
	[IS_SECURED] [nvarchar](1) NULL,
	[PIECEOBLIGATOIRE] [int] NULL,
	[RECHTOLERANTE] [int] NULL,
	[OUVERTURE] [datetime] NULL,
	[FERMETURE] [datetime] NULL,
	[USERID] [nvarchar](50) NULL,
	[SMTP] [nvarchar](50) NULL,
	[FROMADDRESS] [nvarchar](50) NULL,
	[TOADDRESS] [nvarchar](1000) NULL,
	[CARBONCOPY] [nvarchar](1000) NULL,
	[ACTIF] [int] NULL,
	[SUPPRESSION] [nvarchar](5) NULL,
	[HEURESUPP] [nvarchar](10) NULL,
	[INTERVAL] [int] NULL,
	[OEMAILPARAM] [nvarchar](20) NULL,
	[TELEM_ACCESS] [nvarchar](50) NULL,
	[CTRL] [nvarchar](5) NULL,
	[WIFI_PRESENT] [int] NULL,
	[WIFI_LIB] [nvarchar](250) NULL,
	[WIFI_HOST] [nvarchar](250) NULL,
	[WIFI_LOGIN] [nvarchar](50) NULL,
	[WIFI_PWD] [nvarchar](50) NULL,
	[WIFI_GRP] [nvarchar](50) NULL,
	[WIFI_HFIN] [nvarchar](10) NULL,
	[TLMQ_SORTIE_FVISITE] [int] NULL,
	[TLMQ_SORTIE_JOUR] [int] NULL,
	[TLMQ_PURGE_PREENRG] [int] NULL,
	[TLMQ_HEURE_FIN] [nvarchar](50) NULL,
	[TLMQ_HEURE_EXEC] [nvarchar](50) NULL,
	[TLMQ_DERN_EXEC] [datetime] NULL,
	[BDG_GENERATION] [int] NULL,
	[BDG_DEBUT] [nvarchar](10) NULL,
	[BDG_MILIEU] [nvarchar](20) NULL,
	[BDG_FIN] [nvarchar](10) NULL,
	[BDG_MAX] [int] NULL,
	[BDG_GENERATIONR] [int] NULL,
	[BDG_DEBUTR] [nvarchar](20) NULL,
	[BDG_MILIEUR] [nvarchar](20) NULL,
	[BDG_FINR] [nvarchar](20) NULL,
	[BDG_MAXR] [int] NULL,
	[BDG_GENERATIONVEH] [int] NULL,
	[BDG_DEBUTVEH] [nvarchar](20) NULL,
	[BDG_MILIEUVEH] [nvarchar](20) NULL,
	[BDG_FINVEH] [nvarchar](20) NULL,
	[BDG_MAXVEH] [int] NULL,
	[DATEMAJ] [datetime] NOT NULL,
	[DATECREATION] [datetime] NOT NULL,
	[DATESYNCHRO] [datetime] NULL,
	[NUMSITECARDIBOX] [nvarchar](10) NULL,
	[NUMSITEACX] [nvarchar](10) NULL,
	[IS_SSR] [nvarchar](1) NULL,
 [TIMEZONE] NVARCHAR(10) NULL DEFAULT '+01:00', 
    CONSTRAINT [PK_SITEID] PRIMARY KEY CLUSTERED
(
	[SITEID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
ALTER TABLE [dbo].[SITE] ADD  DEFAULT ('0') FOR [IS_SSR]