CREATE TABLE [dbo].[SOCIETE](
	[SOCIETEID] [nvarchar](14) NOT NULL,
	[ISRESIDANT] [nvarchar](1) NULL,
	[EXTERNALID] [nvarchar](24) NULL,
	[GROUPEID] [nvarchar](14) NULL,
	[BADGEID] [nvarchar](14) NULL,
	[PLANID] [nvarchar](14) NULL,
	[USERID] [nvarchar](14) NULL,
	[NATUREID] [nvarchar](14) NULL,
	[NOM] [nvarchar](35) NOT NULL,
	[DEPARTEMENT] [nvarchar](35) NULL,
	[ADRESSE] [image] NULL,
	[ADRESSE2] [nvarchar](150) NULL,
	[CP] [nvarchar](10) NULL,
	[VILLE] [nvarchar](35) NULL,
	[PROVINCE] [nvarchar](35) NULL,
	[PAYS] [nvarchar](35) NULL,
	[TELEPHONE] [nvarchar](20) NULL,
	[FAX] [nvarchar](20) NULL,
	[EMAIL] [nvarchar](150) NULL,
	[WEB] [nvarchar](50) NULL,
	[PROSPECT] [int] NULL,
	[SIRET] [nvarchar](40) NULL,
	[APE] [nvarchar](5) NULL,
	[COMPTECLIENT] [nvarchar](10) NULL,
	[COMPTEFOURNISSEUR] [nvarchar](10) NULL,
	[DISTANCEKM] [float] NULL,
	[OBSERVATIONS] [image] NULL,
	[PHONKEY] [nvarchar](35) NULL,
	[REFIMPORTATION] [nvarchar](20) NULL,
	[INTERN] [int] NULL,
	[CLIENT] [int] NULL,
	[FOURNISSEUR] [int] NULL,
	[INTERDIT] [int] NULL,
	[DEBUTINTERDIT] [datetime] NULL,
	[FININTERDIT] [datetime] NULL,
	[DATEMAJ] [datetime] NOT NULL,
	[DATECREATION] [datetime] NOT NULL,
	[DATESYNCHRO] [datetime] NULL,
	[ESCORT] [int] NULL,
 CONSTRAINT [PK_SOCIETEID] PRIMARY KEY CLUSTERED
(
	[SOCIETEID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
ALTER TABLE [dbo].[SOCIETE] ADD  DEFAULT ('0') FOR [PHONKEY]