CREATE TABLE [dbo].[SOUSFAMILLE](
	[CODESOUSFAMILLE] [nvarchar](14) NOT NULL,
	[CODEFAMILLE] [nvarchar](14) NOT NULL,
	[SOUSFAMILLE] [nvarchar](35) NULL,
	[REMARQUES] [image] NULL,
	[LISTEPRIX] [int] NULL,
	[IMAGE] [image] NULL,
	[MARGE] [float] NULL,
	[DATECREATION] [datetime] NOT NULL,
	[DATEMAJ] [datetime] NOT NULL,
	[DATESYNCHRO] [datetime] NULL,
	[ORDRE] [int] NULL,
	[SOUSFAMILLEEN] [nvarchar](35) NULL,
 CONSTRAINT [PK_CODESOUSFAMILLECODEFAMILLE] PRIMARY KEY CLUSTERED
(
	[CODESOUSFAMILLE] ASC,
	[CODEFAMILLE] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]