CREATE TABLE [dbo].[SOUSMENU_SERVICE](
	[SOUSMENU_SERVICEID] [int] IDENTITY(1,1) NOT NULL,
	[SITEID] [nvarchar](14) NULL,
	[MENU_SERVICEID] [int] NULL,
	[LIBELLE_FR] [nvarchar](100) NULL,
	[LIBELLE_EN] [nvarchar](100) NULL,
	[ORDRE] [int] NULL,
	[TEXTE_FR] [nvarchar](max) NULL,
	[TEXTE_EN] [nvarchar](max) NULL,
PRIMARY KEY CLUSTERED
(
	[SOUSMENU_SERVICEID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]