CREATE TABLE [dbo].[STATUTPARKING](
	[CODE_STATUT] [nvarchar](1) NOT NULL,
	[STATUT_NAME] [nvarchar](25) NOT NULL, 
    CONSTRAINT [PK_STATUTPARKING] PRIMARY KEY ([CODE_STATUT], [STATUT_NAME])
) ON [PRIMARY]