CREATE TABLE [dbo].[STATUTCOLIS](
	[ID_STATUTCOLIS] [int] NOT NULL,
	[LIBELLE] [nvarchar](35) NULL,
	[COLOR] [int] NULL,
	[DATECREATION] [datetime] NOT NULL,
	[DATEMAJ] [datetime] NOT NULL,
	[DATESYNCHRO] [datetime] NULL,
	[LIBELLE_EN] [nvarchar](35) NULL,
PRIMARY KEY CLUSTERED
(
	[ID_STATUTCOLIS] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]