CREATE TABLE [dbo].[STATUTRESERVATION_ETAT](
	[ID] [int] NOT NULL,
	[TEXTE] [nvarchar](50) NULL,
	[DATECREATION] [datetime] NOT NULL,
	[DATEMAJ] [datetime] NOT NULL,
	[DATESYNCHRO] [datetime] NULL, 
    CONSTRAINT [PK_STATUTRESERVATION_ETAT] PRIMARY KEY ([ID])
) ON [PRIMARY]