CREATE TABLE [dbo].[STATUTRESERVATION_SET](
	[ID] [int] NOT NULL,
	[TEXTE] [nvarchar](50) NULL,
	[DATECREATION] [datetime] NOT NULL,
	[DATEMAJ] [datetime] NOT NULL,
	[DATESYNCHRO] [datetime] NULL, 
    CONSTRAINT [PK_STATUTRESERVATION_SET] PRIMARY KEY ([ID])
) ON [PRIMARY]