CREATE TABLE [dbo].[STATUTVISITE](
	[STATUTID] [int] NOT NULL,
	[STATUTVISITE] [nvarchar](50) NULL,
 CONSTRAINT [PK_STATUTID] PRIMARY KEY CLUSTERED
(
	[STATUTID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]