CREATE TABLE [dbo].[STATUTPARKING](
	[CODE_STATUT] [varchar](1) NOT NULL,
	[STATUT_NAME] [varchar](25) NOT NULL, 
    CONSTRAINT [PK_STATUTPARKING] PRIMARY KEY ([CODE_STATUT], [STATUT_NAME])
) ON [PRIMARY]