CREATE TABLE [dbo].[TACHE_LOG](
	[LOGID] [int] NOT NULL,
	[TACHEID] [int] NULL,
	[NUMSESSION] [int] NULL,
	[USERID] [nvarchar](14) NULL,
	[DATECREATION] [datetime] NULL,
	[FREEFLAG01] [int] NULL,
	[FREEFLAG02] [int] NULL,
	[FREEFLAG03] [int] NULL,
	[FREEFLAG04] [int] NULL,
	[IDLIGNE] [nvarchar](14) NULL,
	[NIVEAUSECU] [int] NULL,
	[ROLEUSER] [nvarchar](20) NULL,
	[COMMENTAIRE] [nvarchar](max) NULL,
PRIMARY KEY CLUSTERED
(
	[LOGID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
ALTER TABLE [dbo].[TACHE_LOG] ADD  DEFAULT ('USERS') FOR [ROLEUSER]