CREATE TABLE [dbo].[TEMPSOC2](
	[TMP2ID] [nvarchar](14) NOT NULL,
	[TMPNOM] [nvarchar](35) NOT NULL,
	[TMPRANG] [int] NULL,
	[TRAITE] [nvarchar](1) NULL,
 CONSTRAINT [PK_TMP2ID] PRIMARY KEY CLUSTERED
(
	[TMP2ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]