CREATE TABLE [dbo].[TMPIMPORT](
	[ID_TMPI] [int] NULL,
	[USERNEDAP] [nvarchar](20) NULL,
	[PASSNEDAP] [nvarchar](20) NULL,
	[NOM] [nvarchar](50) NULL,
	[PRENOM] [nvarchar](50) NULL,
	[TEL] [nvarchar](20) NULL,
	[SOCIETE] [nvarchar](50) NULL,
	[NOM2] [nvarchar](50) NULL,
	[DEBUT] [datetime] NULL,
	[FIN] [datetime] NULL,
	[PROFIL] [nvarchar](50) NULL,
	[T] [nvarchar](50) NULL,
	[CODEBARRE] [nvarchar](20) NULL,
	[SITEID] [nvarchar](20) NULL,
	[GUICHETID] [nvarchar](20) NULL,
	[BOITE] [nvarchar](20) NULL
) ON [PRIMARY]