CREATE TABLE [dbo].[TYPEIDENTITE](
	[TYPEIDENTITEID] [int] NOT NULL,
	[LIBELLE] [nvarchar](35) NULL,
	[DATEMAJ] [datetime] NOT NULL,
	[DATECREATION] [datetime] NOT NULL,
	[DATESYNCHRO] [datetime] NULL,
	[LIBELLE_EN] [nvarchar](35) NULL,
 CONSTRAINT [PK_TYPEIDENTITEID] PRIMARY KEY CLUSTERED
(
	[TYPEIDENTITEID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]