CREATE TABLE [dbo].[TYPEDEFAULT](
	[CODETYPEDEFAULT] [nvarchar](14) NOT NULL,
	[LIBELLE] [nvarchar](35) NULL,
	[DATECREATION] [datetime] NOT NULL,
	[DATEMAJ] [datetime] NOT NULL,
	[DATESYNCHRO] [datetime] NULL,
 CONSTRAINT [PK_CODETYPEDEFAULT] PRIMARY KEY CLUSTERED
(
	[CODETYPEDEFAULT] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]