CREATE TABLE [dbo].[TYPEUSER](
	[USERID] [int] NOT NULL,
	[LIBELLE] [nvarchar](50) NULL,
	[DATECREATION] [datetime] NOT NULL,
	[DATEMAJ] [datetime] NOT NULL,
	[DATESYNCHRO] [datetime] NULL, 
    CONSTRAINT [PK_TYPEUSER] PRIMARY KEY ([USERID])
) ON [PRIMARY]