CREATE TABLE [dbo].[TYPEVISDOC](
	[TYPEDOCUMENTID] [int] NOT NULL,
	[TYPEVISITEID] [int] NOT NULL,
 CONSTRAINT [PK_VISDOC] PRIMARY KEY CLUSTERED
(
	[TYPEDOCUMENTID] ASC,
	[TYPEVISITEID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]