CREATE TABLE [dbo].[VALIDATION_ENQUETE](
	[SITEID] [nvarchar](14) NULL,
	[EXTERNALID] [nvarchar](14) NOT NULL,
	[EXTERN_TYPE] [nvarchar](35) NOT NULL,
	[POLE] [nvarchar](100) NULL,
	[ECHANGES] [int] NULL,
	[CUMUL] [nvarchar](50) NULL,
	[CODEACTIVITE] [nvarchar](70) NULL,
	[TYPEVISITE] [nvarchar](35) NOT NULL,
	[VISITEID] [nvarchar](14) NULL,
	[DEBUTPREVU] [datetime] NULL,
	[FINPREVU] [datetime] NULL,
	[DATESAISIE] [datetime] NULL,
	[CENTRE] [nvarchar](35) NULL,
	[CIVILITE] [nvarchar](30) NULL,
	[NOM] [nvarchar](35) NULL,
	[PRENOM] [nvarchar](35) NULL,
	[NOMJEUNEFILLE] [nvarchar](25) NULL,
	[DATENAISSANCE] [datetime] NULL,
	[LIEUNAISSANCE] [nvarchar](70) NULL,
	[PAYSNAISSANCE] [nvarchar](50) NULL,
	[NATIONALITE] [nvarchar](35) NULL,
	[ADRESSE] [nvarchar](150) NULL,
	[VILLE] [nvarchar](35) NULL,
	[CP] [nvarchar](10) NULL,
	[FONCTION] [nvarchar](35) NULL,
	[SOCIETE] [nvarchar](35) NULL,
	[ENQUETE] [int] NULL,
	[ETAT] [int] NULL,
	[RETOUR] [int] NULL,
	[DATECREATION] [datetime] NULL,
	[DATERETOUR] [datetime] NULL,
 CONSTRAINT [PK_ENQUETE] PRIMARY KEY CLUSTERED
(
	[EXTERNALID] ASC,
	[EXTERN_TYPE] ASC,
	[TYPEVISITE] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[VALIDATION_ENQUETE] ADD  DEFAULT ((0)) FOR [ECHANGES]
GO
ALTER TABLE [dbo].[VALIDATION_ENQUETE] ADD  DEFAULT ((0)) FOR [ENQUETE]
GO
ALTER TABLE [dbo].[VALIDATION_ENQUETE] ADD  DEFAULT ((0)) FOR [ETAT]
GO
ALTER TABLE [dbo].[VALIDATION_ENQUETE] ADD  DEFAULT ((0)) FOR [RETOUR]