CREATE TABLE [dbo].[VEHICULE_DEMANDE](
	[VEHICULEID] [nvarchar](14) NULL,
	[RESIDANTID] [nvarchar](14) NULL,
	[DATEDEMANDE] [datetime] NULL,
	[IMMATRICULATION] [nvarchar](14) NULL,
	[MARQUE] [nvarchar](20) NULL,
	[MODELE] [nvarchar](40) NULL,
	[COTE] [int] NULL,
	[STATUT] [nvarchar](40) NULL,
	[DATECREATION] [datetime] NULL,
	[DATEMAJ] [datetime] NULL
) ON [PRIMARY]