CREATE TABLE [dbo].[VEHICULE](
	[VEHICULEID] [nvarchar](14) NOT NULL,
	[RESIDANTID] [nvarchar](14) NULL,
	[IMMATRICULATION] [nvarchar](15) NULL,
	[MARQUE] [nvarchar](20) NULL,
	[MODELE] [nvarchar](40) NULL,
	[TYPE] [nvarchar](50) NULL,
	[ENERGIE] [nvarchar](20) NULL,
	[DATELIMITE] [datetime] NULL,
	[NUMEROPASS] [nvarchar](40) NULL,
	[DATECREATION] [datetime] NOT NULL,
	[DATEMAJ] [datetime] NOT NULL,
	[DATESYNCHRO] [datetime] NULL,
 CONSTRAINT [PK_VEHICULEID] PRIMARY KEY CLUSTERED
(
	[VEHICULEID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[VEHICULE]  WITH CHECK ADD  CONSTRAINT [fk_vehi_resiid] FOREIGN KEY([RESIDANTID])
REFERENCES [dbo].[RESIDANTS] ([RESIDANTID])
GO

ALTER TABLE [dbo].[VEHICULE] CHECK CONSTRAINT [fk_vehi_resiid]