CREATE TABLE [dbo].[VERSION_SFW](
	[COMPATIBLE] [nvarchar](10) NULL,
	[SCHEMAS] [nvarchar](10) NULL,
	[INFO] [nvarchar](50) NULL,
	[DATECREATION] [datetime] NULL,
	[DATEMAJ] [datetime] NULL,
	[FORMATDATE] [nvarchar](10) NULL,
	[VERSION] [nvarchar](50) NULL
) ON [PRIMARY]