CREATE TABLE [dbo].[VISITES_ES](
	[VISITEID] [nvarchar](14) NOT NULL,
	[DATEHEUREENTREE] [datetime] NULL,
	[DATEHEURESORTIE] [datetime] NULL,
	[DATEHEUREENTREEPARKING] [datetime] NULL,
	[DATEHEURESORTIEPARKING] [datetime] NULL,
	[STATUTPARKING] [nvarchar](20) NULL,
	[PARKING] [nvarchar](35) NULL
) ON [PRIMARY]