CREATE TABLE [dbo].[VISITES](
	[VISITEID] [nvarchar](14) NOT NULL,
	[INTERLOCUTEURID] [nvarchar](14) NULL,
	[RESIDANTID] [nvarchar](14) NULL,
	[CODESALLE] [nvarchar](14) NULL,
	[SITEID] [nvarchar](14) NULL,
	[STATUTID] [int] NULL,
	[EXTERNALID] [nvarchar](24) NULL,
	[SOCIETERESID] [nvarchar](35) NULL,
	[NOMPRENOMRESID] [nvarchar](70) NULL,
	[SOCIETEVISIT] [nvarchar](35) NULL,
	[NOMPRENOMVISIT] [nvarchar](70) NULL,
	[DEBUTPREVU] [datetime] NULL,
	[FINPREVU] [datetime] NULL,
	[HDEBUTPREVU] [datetime] NULL,
	[HFINPREVU] [datetime] NULL,
	[NUMEROBADGE] [nvarchar](200) NULL,
	[NUMEROVISITE] [int] NULL,
	[DEBUTVISITE] [datetime] NULL,
	[FINVISITE] [datetime] NULL,
	[HDEBUT] [datetime] NULL,
	[HFIN] [datetime] NULL,
	[STATUTVISITE] [nvarchar](50) NULL,
	[TYPEVISITEID] [int] NULL,
	[BOITE] [nvarchar](6) NULL,
	[CASIER] [nvarchar](6) NULL,
	[OBJET] [nvarchar](200) NULL,
	[CASIERID] [int] NULL,
	[PIECE] [nvarchar](35) NULL,
	[NUMERO] [nvarchar](20) NULL,
	[VALIDITE] [datetime] NULL,
	[PARKING] [nvarchar](35) NULL,
	[IMMATRICULATION] [nvarchar](15) NULL,
	[GUICHETID] [nvarchar](14) NULL,
	[OBSERVATION] [nvarchar](200) NULL,
	[BUREAUID] [nvarchar](14) NULL,
	[LIEU] [nvarchar](50) NULL,
	[DATECREATION] [datetime] NOT NULL,
	[DATEMAJ] [datetime] NOT NULL,
	[DATESYNCHRO] [datetime] NULL,
	[ORIGINEVISITE] [int] NULL,
	[NBBDGIMPR] [int] NULL,
	[NBBDGIMPRTOTAL] [int] NULL,
	[FREE1] [nvarchar](50) NULL,
	[FREE2] [nvarchar](250) NULL,
	[FREE3] [nvarchar](50) NULL,
	[FREE4] [nvarchar](50) NULL,
	[FREE5] [nvarchar](50) NULL,
	[FREE6] [nvarchar](50) NULL,
	[FREE7] [nvarchar](50) NULL,
	[FREE8] [nvarchar](250) NULL,
	[FREE9] [nvarchar](250) NULL,
	[FREE10] [nvarchar](50) NULL,
	[MARQUE] [nvarchar](20) NULL,
	[MODELE] [nvarchar](40) NULL,
	[COTE] [int] NULL,
	[PREMIER] [int] NULL,
	[PREENREG] [int] NULL,
	[ECHANGES] [int] NULL,
	[ZONE] [nvarchar](1) NULL,
	[DESCENTE] [int] NULL,
	[BADGEPHYSIQUE] [nvarchar](50) NULL,
	[ATTENDU] [int] NULL,
	[ATTENDU_VENU] [int] NULL,
	[DATEHEUREENTREEPARKING] [datetime] NULL,
	[DATEHEURESORTIEPARKING] [datetime] NULL,
	[STATUTPARKING] [nvarchar](20) NULL,
	[DEBLOC] [int] NULL,
	[DEBLOC_USER] [nvarchar](50) NULL,
	[DEBLOC_USERID] [nvarchar](14) NULL,
	[DEBLOC_HEURE] [datetime] NULL,
	[IFONCTION] [nvarchar](35) NULL,
	[IDATENAISSANCE] [datetime] NULL,
	[ILIEUNAISSANCE] [nvarchar](70) NULL,
	[IPAYS] [nvarchar](35) NULL,
	[INOMJEUNEFILLE] [nvarchar](35) NULL,
	[MODIFICATION] [nvarchar](100) NULL,
	[ETATVISITE] [nvarchar](1) NULL,
	[VIP] [int] NULL,
	[ISTATUT] [nvarchar](35) NULL,
	[CODELGRESERVATION] [nvarchar](14) NULL,
	[TICKET] [nvarchar](50) NULL,
	[RONDIER] [nvarchar](50) NULL,
	[RONDIERID] [int] NULL,
	[CLE] [nvarchar](500) NULL,
	[PROFIL_CTRL] [nvarchar](4000) NULL,
	[PROFIL_CTRL2] [nvarchar](4000) NULL,
	[PROFIL_CTRL_ID] [nvarchar](4000) NULL,
	[WIFI_LOGIN] [nvarchar](50) NULL,
	[WIFI_PWD] [nvarchar](50) NULL,
	[ALERTE] [nvarchar](4000) NULL,
	[LAST_ACTION] [nvarchar](50) NULL,
	[RES_OS] [nvarchar](50) NULL,
	[RES_FINAL] [nvarchar](50) NULL,
	[RES_MOTEUR1] [nvarchar](50) NULL,
	[RES_MOTEUR2] [nvarchar](50) NULL,
	[INFO] [nvarchar](50) NULL,
	[SIGNATURE_ENTREE] [int] NULL,
	[SIGNATURE_SORTIE] [int] NULL,
	[REFIMPORTATION] [nvarchar](30) NULL,
	[ZRR_CODE] [nvarchar](25) NULL,
	[ZRR_LIB] [nvarchar](255) NULL,
	[ZRR_LS] [nvarchar](3) NULL,
	[FUSION] [int] NULL,
	[NATUREVISITE] [nvarchar](7) NULL,
	[MESSAGEVALIDEUR] [nvarchar](1000) NULL,
	[ACCOMPAGNATEURID] [nvarchar](14) NULL,
	[GRPVALIDEUR2] [nvarchar](50) NULL,
	[GRPVALIDEUR3] [nvarchar](50) NULL,
	[GRPVALIDEUR4] [nvarchar](50) NULL,
	[RANKLASTVAL] [int] NULL,
	[CATEGORIE] [nvarchar](30) NULL,
	[IDEPFR] [nvarchar](100) NULL,
	[RESTAURANT] [int] NULL,
	[OUBLI_BADGE_RESI] [int] NULL,
	[EMETTEUR ] [nvarchar](200) NULL,
	[USER_IN ] [nvarchar](200) NULL,
	[USER_OUT ] [nvarchar](200) NULL,
	[BATIMENTID] [nvarchar](14) NULL,
	[EMETTEURID] [nvarchar](14) NULL,
	[EMETTEURTYPE] [nvarchar](14) NULL,
	[SIGNATUREID] [int] NULL,
	[PDFOFICHIERID] [int] NULL,
	[ACCOMPAGNER_VISITEUR] [int] NULL,
 CONSTRAINT [PK_VISITEID] PRIMARY KEY CLUSTERED
(
	[VISITEID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[VISITES]  WITH CHECK ADD  CONSTRAINT [fk_visi_resiid] FOREIGN KEY([RESIDANTID])
REFERENCES [dbo].[RESIDANTS] ([RESIDANTID])
GO

ALTER TABLE [dbo].[VISITES] CHECK CONSTRAINT [fk_visi_resiid]
GO
ALTER TABLE [dbo].[VISITES]  WITH CHECK ADD  CONSTRAINT [fk_visi_siteid] FOREIGN KEY([SITEID])
REFERENCES [dbo].[SITE] ([SITEID])
GO

ALTER TABLE [dbo].[VISITES] CHECK CONSTRAINT [fk_visi_siteid]
GO
ALTER TABLE [dbo].[VISITES] ADD  DEFAULT ((0)) FOR [NBBDGIMPRTOTAL]
GO
ALTER TABLE [dbo].[VISITES] ADD  DEFAULT ((0)) FOR [PREENREG]
GO
ALTER TABLE [dbo].[VISITES] ADD  DEFAULT ((0)) FOR [ECHANGES]
GO
ALTER TABLE [dbo].[VISITES] ADD  DEFAULT ((0)) FOR [DESCENTE]
GO
ALTER TABLE [dbo].[VISITES] ADD  DEFAULT ((0)) FOR [ATTENDU]
GO
ALTER TABLE [dbo].[VISITES] ADD  DEFAULT ((0)) FOR [ATTENDU_VENU]
GO
ALTER TABLE [dbo].[VISITES] ADD  DEFAULT ('0') FOR [STATUTPARKING]
GO
ALTER TABLE [dbo].[VISITES] ADD  DEFAULT ((0)) FOR [VIP]
GO
ALTER TABLE [dbo].[VISITES] ADD  DEFAULT ('UNIS') FOR [REFIMPORTATION]
GO
ALTER TABLE [dbo].[VISITES] ADD  DEFAULT ('0') FOR [FUSION]
GO
ALTER TABLE [dbo].[VISITES] ADD  DEFAULT ('VISITE') FOR [NATUREVISITE]
GO
ALTER TABLE [dbo].[VISITES] ADD  DEFAULT ('0') FOR [RESTAURANT]
GO
ALTER TABLE [dbo].[VISITES] ADD  DEFAULT ('0') FOR [OUBLI_BADGE_RESI]
GO
ALTER TABLE [dbo].[VISITES] ADD  DEFAULT ((0)) FOR [ACCOMPAGNER_VISITEUR]