CREATE TABLE [dbo].[VISITES_EXT](
	[VISITES_EXTID] [nvarchar](14) NULL,
	[FREE1] [nvarchar](50) NULL,
	[FREE2] [nvarchar](50) NULL,
	[FREE3] [nvarchar](50) NULL,
	[FREE4] [nvarchar](50) NULL,
	[FREE5] [nvarchar](50) NULL,
	[FREE6] [nvarchar](50) NULL,
	[FREE7] [nvarchar](50) NULL,
	[FREE8] [nvarchar](50) NULL,
	[FREE9] [nvarchar](50) NULL,
	[FREE10] [nvarchar](50) NULL,
	[MARCHEID] [nvarchar](14) NULL
) ON [PRIMARY]