CREATE TABLE [dbo].[VISITES_EXT](
	[VISITES_EXTID] [varchar](14) NULL,
	[FREE1] [varchar](50) NULL,
	[FREE2] [varchar](50) NULL,
	[FREE3] [varchar](50) NULL,
	[FREE4] [varchar](50) NULL,
	[FREE5] [varchar](50) NULL,
	[FREE6] [varchar](50) NULL,
	[FREE7] [varchar](50) NULL,
	[FREE8] [varchar](50) NULL,
	[FREE9] [varchar](50) NULL,
	[FREE10] [varchar](50) NULL,
	[MARCHEID] [varchar](14) NULL
) ON [PRIMARY]