CREATE TABLE [dbo].[WEBPLANNING](
	[DATEBEGIN] [datetime] NOT NULL,
	[DATEEND] [datetime] NOT NULL,
	[IMAGEPATH] [nvarchar](80) NULL,
PRIMARY KEY CLUSTERED
(
	[DATEBEGIN] ASC,
	[DATEEND] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]