CREATE TABLE [dbo].[XANNEXE](
	[XANNEXEID] [nvarchar](14) NOT NULL,
	[XANNEXE_TYPEID] [int] NULL,
	[ORIGINEID] [nvarchar](14) NULL,
	[ORIGINE] [nvarchar](50) NULL,
	[OFICHIERID] [int] NULL,
	[STATUTID] [int] NULL,
	[DATEFIN] [datetime] NULL,
	[FREE01] [nvarchar](50) NULL,
	[FREE02] [nvarchar](50) NULL,
	[FREE03] [nvarchar](50) NULL,
	[FREE04] [nvarchar](50) NULL,
	[FREE05] [nvarchar](50) NULL,
	[FREE06] [nvarchar](50) NULL,
	[FREE07] [nvarchar](50) NULL,
	[FREE08] [nvarchar](50) NULL,
	[FREE09] [nvarchar](50) NULL,
	[FREEDATE01] [datetime] NULL,
	[FREEDATE02] [datetime] NULL,
	[INFORMATION_TYPEID] [int] NULL,
	[REFID] [nvarchar](14) NULL,
	[ETAT] [int] NULL,
	[DATERETOUR] [datetime] NULL,
	[DATECREATION] [datetime] NOT NULL,
	[DATEMAJ] [datetime] NOT NULL,
	[DATESYNCHRO] [datetime] NULL,
	[SITEID] [nvarchar](14) NULL,
PRIMARY KEY CLUSTERED
(
	[XANNEXEID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[XANNEXE] ADD  DEFAULT ('0') FOR [XANNEXE_TYPEID]
GO
ALTER TABLE [dbo].[XANNEXE] ADD  DEFAULT ((0)) FOR [STATUTID]
GO
ALTER TABLE [dbo].[XANNEXE] ADD  DEFAULT ((1)) FOR [ETAT]