CREATE TABLE [dbo].[ZCL07_BADGETYPE](
	[ZCL07_BADGETYPEID] [varchar](14) NULL,
	[NAME] [varchar](25) NULL,
	[CLASS] [int] NULL,
	[SERIE] [varchar](10) NULL,
	[CUSTOMERCODE] [varchar](10) NULL,
	[DEBUT] [int] NULL,
	[FIN] [int] NULL
) ON [PRIMARY]