CREATE TABLE [dbo].[ZCL02_DELPM](
	[ZCL02_DELPMID] [nvarchar](14) NOT NULL,
	[ID] [nvarchar](20) NULL,
	[PLAQUE] [nvarchar](20) NULL,
	[DENTREE] [nvarchar](20) NULL,
	[DSORTIE] [nvarchar](20) NULL,
	[TENTREE] [nvarchar](20) NULL,
	[TSORTIE] [nvarchar](20) NULL,
	[ETAT] [int] NULL,
	[LIEN] [nvarchar](20) NULL,
	[DATECREATION] [datetime] NOT NULL,
	[DATEMAJ] [datetime] NOT NULL,
PRIMARY KEY CLUSTERED
(
	[ZCL02_DELPMID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]