CREATE TABLE [dbo].[ZCL07_BADGETYPE](
	[ZCL07_BADGETYPEID] [nvarchar](14) NULL,
	[NAME] [nvarchar](25) NULL,
	[CLASS] [int] NULL,
	[SERIE] [nvarchar](10) NULL,
	[CUSTOMERCODE] [nvarchar](10) NULL,
	[DEBUT] [int] NULL,
	[FIN] [int] NULL
) ON [PRIMARY]