CREATE TABLE [dbo].[ZCL15_CPPA](
	[IDCPPA] [nvarchar](14) NULL,
	[REGLEID] [nvarchar](14) NULL,
	[SITEID] [nvarchar](14) NULL,
	[SITE] [nvarchar](35) NULL,
	[SOCIETEID] [nvarchar](14) NULL,
	[SOCIETE] [nvarchar](35) NULL,
	[PAYSID] [nvarchar](14) NULL,
	[PAYS] [nvarchar](35) NULL,
	[TYPEVISITEID] [int] NULL,
	[TYPEVISITE] [nvarchar](70) NULL,
	[ETAT] [nvarchar](3) NULL,
	[DATESYNCHRO] [datetime] NULL
) ON [PRIMARY]