CREATE TABLE [dbo].[ZCL27_WORKGROUP](
	[ID_WORKGROUP] [int] IDENTITY(1,1) NOT NULL,
	[WG_NAME] [nvarchar](40) NULL,
	[WG_ID] [nvarchar](20) NULL,
	[SITEID] [nvarchar](14) NULL,
	[DATECREATION] [datetime] NULL,
	[DATEMAJ] [datetime] NULL,
PRIMARY KEY CLUSTERED
(
	[ID_WORKGROUP] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]