CREATE TABLE [dbo].[ZCL27_BADGE](
	[ID_BADGE] [int] IDENTITY(1,1) NOT NULL,
	[B_CARD_NO] [nvarchar](20) NULL,
	[B_ASSIGNED] [int] NULL,
	[CARDQUALITY] [nvarchar](14) NULL,
	[SITEID] [nvarchar](14) NULL,
	[DATECREATION] [datetime] NULL,
	[DATEMAJ] [datetime] NULL,
PRIMARY KEY CLUSTERED
(
	[ID_BADGE] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]