CREATE TABLE [dbo].[ZCL20_MOUVEMENT](
	[ID] [nvarchar](14) NULL,
	[VISITEID] [nvarchar](14) NULL,
	[TYPE_ENREG] [nvarchar](20) NULL,
	[ENTREE_PARKING] [datetime] NULL,
	[VISITEUR] [nvarchar](70) NULL,
	[VISITEUR_SOCIETE] [nvarchar](70) NULL,
	[RESIDANT] [nvarchar](70) NULL,
	[RESIDANT_TROUVE] [nvarchar](1) NULL,
	[IMMATRICULATION] [nvarchar](15) NULL,
	[SORTIE_PARKING] [datetime] NULL,
	[REF_PARKING] [nvarchar](20) NULL,
	[POSTE_SAISIE] [nvarchar](20) NULL,
	[USER_TQ] [nvarchar](35) NULL,
	[OBSERVATION] [nvarchar](200) NULL,
	[SITEID] [nvarchar](35) NULL,
	[SITE] [nvarchar](35) NULL,
	[DATECREATION] [datetime] NULL
) ON [PRIMARY]