CREATE TABLE [dbo].[ZCL27_EMPLOYEE_LOG](
	[ID_EMPLOYEE_LOG] [int] IDENTITY(1,1) NOT NULL,
	[ID_EMPLOYEE] [int] NULL,
	[SITEID] [nvarchar](14) NULL,
	[INTERLOCUTEURID] [nvarchar](14) NULL,
	[E_CARDNUMBER] [nvarchar](20) NULL,
	[E_CARDASSIGNED] [int] NULL,
	[E_FIRSTNAME] [nvarchar](30) NULL,
	[E_LASTNAME] [nvarchar](30) NULL,
	[E_EMPLOYEEID] [int] NULL,
	[E_STARTDATE] [datetime] NULL,
	[E_STARTDATETIME] [datetime] NULL,
	[E_ENDDATE] [datetime] NULL,
	[E_ENDDATETIME] [datetime] NULL,
	[E_WG_ID] [nvarchar](20) NULL,
	[E_LASTUPDATEDTIME] [nvarchar](19) NULL,
	[E_REFERENCE] [int] NULL,
	[E_VISITOR] [int] NULL,
	[STATUT_ENTREE] [int] NULL,
	[STATUT_SORTIE] [int] NULL,
	[DATECREATION] [datetime] NULL,
	[DATEMAJ] [datetime] NULL,
	[DATELOG] [datetime] NULL,
PRIMARY KEY CLUSTERED
(
	[ID_EMPLOYEE_LOG] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]