CREATE TABLE [dbo].[ZCL30_TAG_TMP](
	[ZCL30_TAG_TMPID] [int] IDENTITY(1,1) NOT NULL,
	[BASE] [varchar](30) NULL,
	[PORTATIF] [varchar](30) NULL,
	[TAG] [varchar](30) NULL,
	[DATEHEURE] [datetime] NULL,
	[ORONDEID] [int] NULL,
 CONSTRAINT [PK_ZCL30_TAG_TMP] PRIMARY KEY CLUSTERED
(
	[ZCL30_TAG_TMPID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]