CREATE TABLE [dbo].[ZCL30_EVT](
	[ZCL30_EVTID] [int] IDENTITY(1,1) NOT NULL,
	[BASE] [nvarchar](30) NULL,
	[PORTATIF] [nvarchar](30) NULL,
	[CODE_EVT] [nvarchar](30) NULL,
	[DATEHEURE] [datetime] NULL,
 CONSTRAINT [PK_ZCL30_EVT] PRIMARY KEY CLUSTERED
(
	[ZCL30_EVTID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]