CREATE TABLE [dbo].[ZCTRL_FIL_EAU](
	[ID] [int] NOT NULL,
	[CTRLID] [nvarchar](30) NULL,
	[CTRLDATE] [datetime] NULL,
	[BADGE] [nvarchar](20) NULL,
	[CTRLDESC] [nvarchar](50) NULL,
	[CTRLREADER] [nvarchar](50) NULL,
	[CTRLEVENT] [nvarchar](50) NULL,
	[CTRLREADERID] [nvarchar](20) NULL,
	[CTRLPROFIL] [nvarchar](100) NULL,
	[INTERLOCUTEURID] [nvarchar](20) NULL,
	[NOMPRENOM] [nvarchar](100) NULL,
	[SOCIETE] [nvarchar](100) NULL,
	[INTERLOCUTEURSTATUT] [nvarchar](50) NULL,
	[RESIDANTSOCIETELIB] [nvarchar](100) NULL,
	[RESIDANTSOCIETEID] [nvarchar](20) NULL,
	[SITEID] [nvarchar](20) NULL,
	[SITELIBELLE] [nvarchar](50) NULL,
	[TICKET] [nvarchar](50) NULL,
	[LOCALISATION] [nvarchar](4000) NULL,
	[DATECREATION] [datetime] NOT NULL,
	[DATEMAJ] [datetime] NULL,
	[DATESYNCHRO] [datetime] NULL,
PRIMARY KEY CLUSTERED
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]