CREATE TABLE [dbo].[ZONE](
	[ZONEID] [nvarchar](14) NOT NULL,
	[ZONENOM] [nvarchar](20) NULL,
	[ZONERESPONSABLE] [nvarchar](30) NULL,
	[DATEMAJ] [datetime] NULL,
	[DATECREATION] [datetime] NULL,
	[DATESYNCHRO] [datetime] NULL, 
    CONSTRAINT [PK_ZONE] PRIMARY KEY ([ZONEID])
) ON [PRIMARY]