CREATE TABLE [dbo].[ZRR](
	[ID_ZRR] [int] NOT NULL,
	[CODE] [nvarchar](25) NULL,
	[LIBELLE] [nvarchar](255) NULL,
	[DEB_VALITE] [datetime] NULL,
	[FIN_VALIDITE] [datetime] NULL,
	[ACTIVE] [nvarchar](1) NULL,
	[ZONE_PARTENAIRE] [nvarchar](1) NULL,
	[CENTRE] [nvarchar](3) NULL,
	[SITEID] [nvarchar](14) NULL,
	[LOCAUX_SENSIBLES] [nvarchar](1) NULL,
	[UCREA] [nvarchar](8) NULL,
	[DCREA] [datetime] NULL,
	[UDERMAJ] [nvarchar](8) NULL,
	[DDERMAJ] [datetime] NULL,
 CONSTRAINT [PK_ZRR] PRIMARY KEY CLUSTERED
(
	[ID_ZRR] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]