UPDATE TQ_COMMUNE SET BDG_FREE1='GUICHET';
GO

UPDATE TQ_COMMUNE SET BDG_FREE2='FINPREVU';
GO

UPDATE TQ_COMMUNE SET BDG_FREE3='NUMEROVISITE';
GO

UPDATE TQ_COMMUNE SET BDG_FREE4='NUMEROBADGE';
GO

UPDATE TQ_COMMUNE SET BDG_FREE5='PIECE';
GO

UPDATE TQ_COMMUNE SET BDG_FREE6='HEUREVISIJOUR';
GO

UPDATE TQ_COMMUNE SET BDG_FREE7='IMMATRICULATION';
GO

UPDATE TQ_COMMUNE SET BDG_FREE8='TELR';
GO

UPDATE TQ_COMMUNE SET BDG_FREE9='BUREAUR';
GO