-- 2003_06_03
ALTER TABLE CFGGSALLESPARAM ADD (
  RESA_ORDRE_SALLE  INTEGER,
  RESA_PRESTA_STYLE INTEGER,
  FILTRE_ORDRE_TRI  INTEGER
);

UPDATE CFGGSALLESPARAM SET RESA_ORDRE_SALLE=0,RESA_PRESTA_STYLE=0,FILTRE_ORDRE_TRI=0;

UPDATE DROITS SET DATECREATION=SYSDATE,DATEMAJ=SYSDATE;

-- 2003_07_01
UPDATE ARTICLE SET CODEFAMILLE=(SELECT CODEFAMILLE FROM SOUSFAMILLE WHERE CODESOUSFAMILLE=ARTICLE.CODESOUSFAMILLE);

-- 2003_07_03
ALTER TABLE SOCIETE ADD (ADRESSE2 VARCHAR2(150));


COMMIT;

ALTER TABLE USERS ADD (
        PROFIL_ID_ORGA VARCHAR(14) NULL,
        PROFIL_ID_INTER VARCHAR(14) NULL,
        PROFIL_ID_SALLE VARCHAR(14) NULL,
        PROFIL_ID_BATIMENT VARCHAR(14) NULL,
        PROFIL_ID_SITE VARCHAR(14) NULL,
        PROFIL_ETAGE VARCHAR(14) NULL,
        PROFIL_SURBOOKING INTEGER,
        PROFIL_PARAMVALIDE VARCHAR(14) NULL,
        PROFIL_ID_STATUT VARCHAR(14) NULL
);

ALTER TABLE USERS ADD PROFIL_PARAMCOMPTE VARCHAR(14) NULL;

ALTER TABLE USERS ADD PHONKEY VARCHAR(50);

ALTER TABLE BATIMENT MODIFY ( NOBAT VARCHAR(15) );

ALTER TABLE LGPA MODIFY ( NOSALLE VARCHAR(15) );

ALTER TABLE LGRESERVATION MODIFY ( NOSALLE VARCHAR(15) );

ALTER TABLE LGPA ADD ( CODELGRESERVATION VARCHAR2(14) );

ALTER TABLE SALLE MODIFY ( NOSALLE VARCHAR(15) );

ALTER TABLE FACTURE ADD RESIDANTID VARCHAR2(14);


ALTER TABLE LGRESERVATION ADD CODESTATUT VARCHAR2(14);

ALTER TABLE JOURNAL ADD JOURNALID VARCHAR2(14);

ALTER TABLE JOURNAL MODIFY TABLEID VARCHAR2(30);


ALTER TABLE HLGRESERVATION ADD CODESALLEASS VARCHAR2 (14);

CREATE TABLE SALLEFUS (
   CODESALLEFUS VARCHAR2(14),
   LIBELLE  VARCHAR2(50),
   DECODESALLE VARCHAR2(14),
   DATECREATION DATE,
   DATEMAJ      DATE
);

CREATE TABLE SALLEFUS_COMP (
   CODESALLEFUS VARCHAR2(14),
   CODESALLE VARCHAR2(14)
);


COMMIT;
EXIT;
