CREATE TABLE ARMOIRE (
  ARMOIREID VARCHAR2(14) not null,
  LIBELLE VARCHAR2(35),
  NUMERO number,
  CAPACITE number,
  NBELEMENT number,
  ISACTIF number,
  SITEID VARCHAR2(14),
  DATECREATION date not null,
  DATEMAJ date
);

ALTER TABLE INTERLOCUTEUR ADD TAG VARCHAR2(30);

ALTER TABLE RESIDANTS ADD TAG VARCHAR2(30);

ALTER TABLE PERSONNEL ADD TAG VARCHAR2(30);

ALTER TABLE CLEFS ADD TAG VARCHAR2(30);


COMMIT;
EXIT;