-- 2006_04_21

CREATE TABLE GROUPEDEST (
  GROUPEDESTID     NUMBER(10, 0) PRIMARY KEY,
  LIBELLE          VARCHAR2(50),
  TOADDRESS         VARCHAR2(2000),
  DATECREATION     DATE,
  DATEMAJ          DATE
);

CREATE SEQUENCE SEQ_GROUPEDEST;

CREATE TABLE EVENEMENT_DEST_SITE (
  EVENEMENTID      NUMBER(10, 0),
  GROUPEDESTID     NUMBER(10, 0),
  SITEID           VARCHAR(14)
);

CREATE TABLE MAIL (
  MAILID       VARCHAR(14),
  APP          VARCHAR(10),
  SITEID       VARCHAR(14),
  SITE         VARCHAR(35),
  USERID       VARCHAR(50),
  SMTP         VARCHAR(50),
  FROMADDRESS  VARCHAR(50),
  TOADDRESS    VARCHAR(1000),
  CARBONCOPY   VARCHAR(1000),
  SUJET        VARCHAR(200),
  BODY         VARCHAR(4000),
  STATUT       INTEGER,
  ETAT         VARCHAR(50),
  DATECREATION DATE,
  DATEMAJ      DATE
);


ALTER TABLE SITE ADD (USERID       VARCHAR(50));
ALTER TABLE SITE ADD (SMTP         VARCHAR(50));
ALTER TABLE SITE ADD (FROMADDRESS  VARCHAR(50));
ALTER TABLE SITE ADD (TOADDRESS    VARCHAR(1000));
ALTER TABLE SITE ADD (CARBONCOPY   VARCHAR(1000));
ALTER TABLE SITE ADD (ACTIF        INTEGER);
ALTER TABLE SITE ADD (SUPPRESSION  VARCHAR(5));
ALTER TABLE SITE ADD (HEURESUPP    VARCHAR(10));
ALTER TABLE SITE ADD (INTERVAL INTEGER);
ALTER TABLE SITE ADD (OEMAILPARAM  VARCHAR(20));

ALTER TABLE MAIL ADD (QUIID   VARCHAR(50));
ALTER TABLE MAIL ADD (QUILIB  VARCHAR(50));


ALTER TABLE OMNI_PARAM ADD (OPTION_PASSWORD INTEGER);

ALTER TABLE PERSONNEL ADD (EMPPK BLOB);

ALTER TABLE EVENEMENT ADD ( COLOR NUMBER(10) );


ALTER TABLE VACATION ADD CL INT;

ALTER TABLE JOUR ADD CL INT;

UPDATE JOUR SET CL=1 WHERE TYPE_JOUR='LUNDI';
UPDATE JOUR SET CL=2 WHERE TYPE_JOUR='MARDI';
UPDATE JOUR SET CL=3 WHERE TYPE_JOUR='MERCREDI';
UPDATE JOUR SET CL=4 WHERE TYPE_JOUR='JEUDI';
UPDATE JOUR SET CL=5 WHERE TYPE_JOUR='VENDREDI';
UPDATE JOUR SET CL=6 WHERE TYPE_JOUR='SAMEDI';
UPDATE JOUR SET CL=7 WHERE TYPE_JOUR='DIMANCHE';

INSERT INTO EVENEMENT (EVENEMENTID,LIBELLE,RAPPORTID,CONSIGNEID,ISRAPPORT,DATEMAJ,DATECREATION,DATESYNCHRO) VALUES (-13,'PROBLEME MATERIEL',0,0,0,SYSDATE,SYSDATE,SYSDATE);

COMMIT;
EXIT;