-- 2005_03_30
ALTER TABLE OMNI_PARAM ADD (OPTION_AVMISS NUMBER(10));
ALTER TABLE OMNI_PARAM ADD (OPTION_TIMER_MISSION NUMBER(10));

-- 2005_04_18
ALTER TABLE RENSEIGNEMENT ADD (SITEID  VARCHAR2(14));
ALTER TABLE RENSEIGNEMENT ADD (POSTEID NUMBER(10));

ALTER TABLE SECTEUR ADD (SITEID  VARCHAR2(14));

ALTER TABLE RUE ADD (SITEID  VARCHAR2(14));

ALTER TABLE LIEU ADD (SITEID  VARCHAR2(14));

ALTER TABLE EVENEMENT ADD (SITEID  VARCHAR2(14));

ALTER TABLE VACATION ADD (SITEID  VARCHAR2(14));
ALTER TABLE VACATION ADD (POSTEID NUMBER(10));

ALTER TABLE MATERIEL ADD (SITEID  VARCHAR2(14));

ALTER TABLE PERSONNE ADD (SITEID  VARCHAR2(14));

ALTER TABLE SECOURS ADD (SITEID  VARCHAR2(14));

ALTER TABLE OCONSIGNE ADD (SITEID  VARCHAR2(14));
ALTER TABLE OCONSIGNE ADD (POSTEID NUMBER(10));

ALTER TABLE MISSION ADD (SITEID  VARCHAR2(14));
ALTER TABLE MISSION ADD (POSTEID NUMBER(10));

ALTER TABLE AGENDA_JOUR ADD (SITEID  VARCHAR2(14));

ALTER TABLE AGENDA_JOUR2 ADD (SITEID  VARCHAR2(14));

ALTER TABLE MISSIONTEMP ADD (SITEID  VARCHAR2(14));

ALTER TABLE TYPE_MISSION ADD (SITEID  VARCHAR2(14));
ALTER TABLE TYPE_MISSION ADD (POSTEID NUMBER(10));

ALTER TABLE RAPPORT ADD (SITEID  VARCHAR2(14));
ALTER TABLE RAPPORT ADD (POSTEID NUMBER(10));

ALTER TABLE POSTE ADD (LIBELLE2  VARCHAR2(40));

ALTER TABLE OMESSAGE ADD (SITEID  VARCHAR2(14));
ALTER TABLE OMESSAGE ADD (POSTEID NUMBER(10));

ALTER TABLE OJOURNAL ADD (SITEID  VARCHAR2(14));
ALTER TABLE OJOURNAL ADD (POSTEID NUMBER(10));

-- Requete pour mettre à jour sited et posteid du journal
UPDATE OJOURNAL SET SITEID='';
UPDATE OJOURNAL SET POSTEID=0;

COMMIT;

-- 2005_07_11
ALTER TABLE JVACATION ADD (SITEID  VARCHAR2(14));
ALTER TABLE JVACATION ADD (POSTEID NUMBER(10));

ALTER TABLE AGENTPRESENT ADD (SITEID  VARCHAR2(14));
ALTER TABLE AGENTPRESENT ADD (POSTEID NUMBER(10));

ALTER TABLE AGENTPRESENTLOG ADD (SITEID  VARCHAR2(14));
ALTER TABLE AGENTPRESENTLOG ADD (POSTEID NUMBER(10));

-- 2005_07_29
CREATE TABLE EVENEMENT_SITE (
  EVENEMENTID NUMBER(10, 0),
  SITEID VARCHAR2(14)
);


-- 2005_08_08

CREATE TABLE OJOURNALLOG (
  OJOURNALID  NUMBER(10,0),
  ACTION      NUMBER(5,0),
  PERSONNELID NUMBER(10,0),
  SITEID      VARCHAR2(14),
  POSTEID     NUMBER(10),
  OBSERVATION VARCHAR2(1000),
  DATEMAJ     DATE
);


CREATE TABLE JRAPPORTLOG (
  OJOURNALID  NUMBER(10,0),
  RAPPORTID   NUMBER(10,0),
  RPTID       NUMBER(10,0),
  RPTNOM      VARCHAR2(20),
  REF         VARCHAR2(20),
  VERSION     NUMBER(3,0),
  PERSONNELID NUMBER(10,0),
  SITEID      VARCHAR2(14),
  POSTEID     NUMBER(10),
  DATEMAJ     DATE
);

-- 2005_10_04

INSERT INTO ODROIT (ODROITID,LIBELLE,OMACCESS,DATEMAJ,DATECREATION) VALUES (1,'ADMINISTRATEUR',8191,SYSDATE,SYSDATE);
INSERT INTO PERSONNEL (PERSONNELID,THEPASSWORD,THELOGIN,NOM,PRENOM,DATE_NAISSANCE,DATE_EMBAUCHE,DATE_ARRIVEE,DEBUT_VALIDITE,FIN_VALIDITE,QUALIFID,CODEFONCTION,MEDICAL_LAST,MEDICAL_NEXT,ODROITID,SITEID,DATEMAJ,DATECREATION) VALUES (1,2206,'TAFFIN','TAFFIN','Jean-marie','01/01/1950','01/01/1950','01/01/1950','01/01/1950','01/01/1950',0,0,'01/01/1950','01/01/1950',1,'VPARDEFAUT',SYSDATE,SYSDATE);
INSERT INTO EVENEMENT (EVENEMENTID,LIBELLE,RAPPORTID,CONSIGNEID,ISRAPPORT,DATEMAJ,DATECREATION,DATESYNCHRO) VALUES (1,'INCIDENT',0,0,0,SYSDATE,SYSDATE,SYSDATE);


DROP SEQUENCE SEQ_EVENEMENT;
CREATE SEQUENCE SEQ_EVENEMENT START WITH 10;
DROP SEQUENCE SEQ_ODROIT;
CREATE SEQUENCE SEQ_ODROIT START WITH 10;
DROP SEQUENCE SEQ_PERSONNEL;
CREATE SEQUENCE SEQ_PERSONNEL START WITH 10;

COMMIT;

-- 2005_10_17

CREATE TABLE CONSTEMP_SITE (
  CONSIGNETEMPID NUMBER(10, 0),
  SITEID VARCHAR2(14)
);

-- 2005_10_26 Correction_en_fonction_du_site.sql

UPDATE AGENDA_JOUR SET SITEID='VPARDEFAUT' WHERE SITEID IS NULL;
UPDATE AGENDA_JOUR2 SET SITEID='VPARDEFAUT' WHERE SITEID IS NULL;

UPDATE AGENTPRESENTLOG SET SITEID='VPARDEFAUT' WHERE SITEID IS NULL;
UPDATE AGENTPRESENTLOG SET POSTEID=0 WHERE POSTEID IS NULL;

UPDATE OJOURNAL SET SITEID='VPARDEFAUT' WHERE SITEID IS NULL;
UPDATE OJOURNAL SET POSTEID=0 WHERE POSTEID IS NULL;

UPDATE OMESSAGE SET SITEID='VPARDEFAUT' WHERE SITEID IS NULL;
UPDATE OMESSAGE SET POSTEID=0 WHERE POSTEID IS NULL;

UPDATE CONSIGNETEMP SET SITEID='VPARDEFAUT' WHERE SITEID IS NULL;
UPDATE CONSIGNETEMP SET POSTEID=0 WHERE POSTEID IS NULL;

UPDATE CONSIGNETEMP2 SET SITEID='VPARDEFAUT' WHERE SITEID IS NULL;
UPDATE CONSIGNETEMP2 SET POSTEID=0 WHERE POSTEID IS NULL;

UPDATE POSTE SET SITEID='VPARDEFAUT' WHERE SITEID IS NULL;
UPDATE POSTE SET SOCIETEID='VPARDEFAUT' WHERE SOCIETEID IS NULL;
COMMIT;

INSERT INTO EVENEMENT_SITE (SELECT EVENEMENTID,'VPARDEFAUT' AS SITEID FROM EVENEMENT WHERE EVENEMENTID >0);

COMMIT;

-- 2005_10_27
CREATE TABLE CONSTEMP_POSTE (
  CONSIGNETEMPID NUMBER(10, 0),
  POSTEID NUMBER(10, 0)
);


CREATE TABLE CONSTEMP_QUALIF (
  CONSIGNETEMPID NUMBER(10, 0),
  QUALIFID NUMBER(10, 0)
);

-- 2005_10_31 Correction_en_fonction_du_site.sql

INSERT INTO CONSTEMP_SITE (CONSIGNETEMPID,SITEID) (SELECT CONSIGNETEMPID,SITEID FROM CONSIGNETEMP);
INSERT INTO CONSTEMP_POSTE (CONSIGNETEMPID,POSTEID) (SELECT CONSIGNETEMPID,POSTEID FROM CONSIGNETEMP);
INSERT INTO CONSTEMP_QUALIF (CONSIGNETEMPID,QUALIFID) (SELECT CONSIGNETEMPID,QUALIFID FROM CONSIGNETEMP);

COMMIT;

UPDATE CONSIGNETEMP SET SITEID='';
UPDATE CONSIGNETEMP SET POSTEID='';
UPDATE CONSIGNETEMP SET QUALIFID='';
COMMIT;

UPDATE CONSIGNETEMP2 SET SITEID='';
UPDATE CONSIGNETEMP2 SET POSTEID='';
UPDATE CONSIGNETEMP2 SET QUALIFID='';

COMMIT;

-- 2005_11_09
ALTER TABLE JRAPPORT ADD (CLOTURER    NUMBER(2, 0));

UPDATE JRAPPORT SET CLOTURER=0;
COMMIT;

-- 2005_11_10

CREATE TABLE OJOURNAL_PERSMVT (
  OJOURNALID       NUMBER(10, 0) PRIMARY KEY,
  TYPEPERSID       NUMBER(10, 0),
  NOMPRENOM        VARCHAR2(70),
  SOCIETE          VARCHAR2(35),
  INTERLOCUTEURID  VARCHAR2(14),
  VEHICULE         VARCHAR2(35),
  IMMATRICULATION  VARCHAR2(35),
  BADGE            VARCHAR2(20),
  CA               VARCHAR2(20),
  DESTINATION      VARCHAR2(50),
  OBSERVATION      VARCHAR2(2000),
  ENTREE           DATE,
  SORTIE           DATE,
  SITEID           VARCHAR2(14),
  POSTEID          NUMBER(10,0),
  PERSONNELDEBUTID NUMBER (10,0),
  PERSONNELFINID   NUMBER (10,0),
  DATECREATION     DATE
);

INSERT INTO EVENEMENT (EVENEMENTID,LIBELLE,RAPPORTID,CONSIGNEID,ISRAPPORT,DATEMAJ,DATECREATION,DATESYNCHRO) VALUES (-12,'MOUVEMENT',0,0,0,SYSDATE,SYSDATE,SYSDATE);

CREATE TABLE CONSTEMP_AGENT (
  CONSIGNETEMPID NUMBER(10, 0),
  PERSONNELID NUMBER(10, 0)
);

COMMIT;
EXIT;