ALTER TABLE RESIDANTS ADD (NBBDGIMPR NUMBER);

ALTER TABLE HVISITES ADD (
ORIGINEVISITE		NUMBER,
NBBDGIMPR		NUMBER,
NBBDGIMPRTOTAL		NUMBER
);

ALTER TABLE VISITES ADD (
FREE1  VARCHAR2(50),
FREE2  VARCHAR2(50),
FREE3  VARCHAR2(50),
FREE4  VARCHAR2(50),
FREE5  VARCHAR2(50),
FREE6  VARCHAR2(50),
FREE7  VARCHAR2(50),
FREE8  VARCHAR2(50),
FREE9  VARCHAR2(50),
FREE10 VARCHAR2(50)
);

ALTER TABLE INTERLOCUTEUR MODIFY PAYS VARCHAR2(250);

ALTER TABLE VISITES ADD ETATVISITE VARCHAR2(1);

CREATE INDEX ETATVISITE ON VISITES (ETATVISITE);

INSERT INTO RESIDANTS (SOCIETEID,RESIDANTID,PLANID,BUREAUID,CODEFONCTION,SERVICEID,THEPASSWORD,THELOGIN,SITEID,BATIMENTID,ISRESIDENT,ISACTIF,INTERDIT,NATUREID,NATIONALITEID,DATEMAJ,DATECREATION,NOMPRENOM,NOM,PRENOM,DEBUTINTERDIT,FININTERDIT)
              VALUES ('VPARDEFAUT','456','VPARDEFAUT','VPARDEFAUT',0,'VPARDEFAUT','RESIDANT','RESIDANT','VPARDEFAUT','VPARDEFAUT',1,1,0,'VPARDEFAUT','VPARDEFAUT',SYSDATE,SYSDATE,'RESIDANT Parking','RESIDANT','Parking',SYSDATE,SYSDATE+(100*365));




INSERT INTO INTERLOCUTEUR (SOCIETEID,INTERLOCUTEURID,CODECIVILITE,CODEFONCTION,PAYS,CIVILITE,NOMPRENOM,NOM,NOMJEUNEFILLE,PRENOM,
FONCTION,TELEPHONE,EMAIL,GSM,FAX,IMMATRICULATION,INTERDIT,DEBUTINTERDIT,FININTERDIT,NATUREID,NATIONALITEID,DATEMAJ,
DATECREATION,SOCIETE,DATENAISSANCE,FINVALIDITEAUTO)
VALUES
('VPARDEFAUT','123',1,0,'FRANCE','Mr','VISITEUR Parking','VISITEUR','','Parking','**********','01 25 46 85 92','','06 13 25 46 95',
'','','0',SYSDATE-1,SYSDATE+100*365,'VPARDEFAUT','VPARDEFAUT',SYSDATE,SYSDATE,'**********','05/08/1960',SYSDATE+365);


ALTER TABLE VISITES_ES ADD (DATEHEUREENTREEPARKING  DATE);
ALTER TABLE VISITES_ES ADD (DATEHEURESORTIEPARKING  DATE);

CREATE TABLE TABLEREFERENCE (
  TABLEREFERENCEID NUMBER(*, 0),
  ID NUMBER(*, 0),
  VALEUR NUMBER(*, 0),
  TEXTE VARCHAR2(50),
  DATECREATION DATE NOT NULL,
  DATEMAJ DATE NOT NULL,
  DATESYNCHRO DATE
);

---------------------------------------------------------------------
--------------------TABLES DU FICHIER TELEMAQ.INI--------------------
---------------------------------------------------------------------



CREATE TABLE TQ_COMMUNE
(
VALIDATION_RESID 			VARCHAR2(10),
NOM_IMG_DEF				VARCHAR2(100),
HAUTEUR					NUMBER,
LARGEUR					NUMBER,
PERMIS_TRAVAIL				NUMBER,
PARAM_ALTAIR				NUMBER,
TITRE					VARCHAR2(50),
BDG_FREE1  				VARCHAR2(20),
BDG_FREE2  				VARCHAR2(20),
BDG_FREE3  				VARCHAR2(20),
BDG_FREE4  				VARCHAR2(20),
BDG_FREE5  				VARCHAR2(20),
BDG_FREE6  				VARCHAR2(20),
BDG_FREE7  				VARCHAR2(20),
BDG_FREE8  				VARCHAR2(20),
BDG_FREE9  				VARCHAR2(20),
PLANS_FREE1  				VARCHAR2(20),
PLANS_FREE2  				VARCHAR2(20),
PLANS_FREE3  				VARCHAR2(20),
PLANS_FREE4  				VARCHAR2(20),
PLANS_FREE5  				VARCHAR2(20),
PLANS_FREE6  				VARCHAR2(20),
PLANS_FREE7  				VARCHAR2(20),
PLANS_FREE8  				VARCHAR2(20),
PLANS_FREE9  				VARCHAR2(20),
BDG_RESID_FREE1  			VARCHAR2(20),
BDG_RESID_FREE2  			VARCHAR2(20),
BDG_RESID_FREE3  			VARCHAR2(20),
BDG_RESID_FREE4  			VARCHAR2(20),
BDG_RESID_FREE5  			VARCHAR2(20),
BDG_RESID_FREE6  			VARCHAR2(20),
BDG_RESID_FREE7  			VARCHAR2(20),
BDG_RESID_FREE8  			VARCHAR2(20),
BDG_RESID_FREE9  			VARCHAR2(20)
);


----------------------------------------------------------
CREATE TABLE TQ_POSTE
(
NOM_POSTE		VARCHAR2(50),
CLE_CONNEXION		VARCHAR2(50),
NB_CAR_RECHERCHE	NUMBER,
DELAI_RECHERCHE		NUMBER,
SITEID			VARCHAR2(14),
SITE			VARCHAR2(50),
GUICHETID		VARCHAR2(14),
GUICHET 		VARCHAR2(50),
BOITE			VARCHAR2(50),
RESID_PAR_DEFAUT	VARCHAR2(20),
IMPR_BDG		VARCHAR2(100),
IMPR_LISTING		VARCHAR2(100),
IMPR_PLAN		VARCHAR2(100),
PHOTO_SRC_RESID		VARCHAR2(100),
PHOTO_DEST_RESID	VARCHAR2(100),
PHOTO_SRC_VISIT		VARCHAR2(100),
PHOTO_DEST_VISIT	VARCHAR2(100),
PHOTO_SRC_PLAN		VARCHAR2(100),
PHOTO_DEST_PLAN		VARCHAR2(100),
LOGO1			VARCHAR2(100),
LOGO2			VARCHAR2(100),
LOGO3			VARCHAR2(100),
LOGO4			VARCHAR2(100),
LOGO5			VARCHAR2(100),
FICHIER_IMPORTATION	VARCHAR2(10),
SEPARATEUR		VARCHAR2(5),
CHAMP1			VARCHAR2(20),
CHAMP2			VARCHAR2(20),
CHAMP3			VARCHAR2(20),
CHAMP4			VARCHAR2(20),
CHAMP5			VARCHAR2(20),
POS_CHAMP1		NUMBER,
POS_CHAMP2		NUMBER,
POS_CHAMP3		NUMBER,
POS_CHAMP4		NUMBER,
POS_CHAMP5		NUMBER,
MAJ_FICHIER		VARCHAR2(20),
MAJ_SITE		VARCHAR2(50),
MAJ_SOCIETE		VARCHAR2(50),
ESVEH_VIS_NOM		NUMBER,
ESVEH_VIS_RESID		NUMBER,
ESVEH_VIS_SOCVIS	NUMBER,
ESVEH_VIS_IMMATR	NUMBER,
ESVEH_VIS_BDG		NUMBER,
ESVEH_RESID_NOM		NUMBER,
ESVEH_RESID_IMMATR	NUMBER,
ESVEH_RESID_BDG		NUMBER,
SORTIE_OBL_ACCUEIL	NUMBER,
TYPE_CONTROL_ACCES		VARCHAR2(30),
BLOCAGE_HDEBUT_VISITE		NUMBER,
RESID_CTRL_HORAIRE_MSG		NUMBER,
RESID_CTRL_HORAIRE_VERROU	NUMBER,
RESID_HORAIRE_VERROU		NUMBER,
FERMETURE_FENETRE_APRES_BDG	NUMBER,
HISTORIQUE			NUMBER,
MODIF_CHAMPS_OBS		NUMBER,
MSG_ALERTEXJOUR_AVANTJ		NUMBER,
MSG_CONFIR_ES			NUMBER,
MSG_INFOR_FORMATIONS_PERIMEES	NUMBER,
AFFICHAGE_DATE_SI_STATUT_LONG	NUMBER,
BLOCAGE_SI_FORM_PERIMEE		NUMBER,
SELECT_MODEL_BDG		NUMBER,
SELECT_IMPR_BDG			NUMBER,
ELARGIR_PAR_DEFAUT		NUMBER,
TRACAGE				NUMBER,
FICHIER_TRACE			VARCHAR2(50),
ENVOI_BDG_MANUEL  		NUMBER,
ENVOI_BDG_AUTO  		NUMBER,
GENERATION_BDG  		NUMBER,
DEBUT_CODE  			NUMBER,
MILIEU_CHAMP  			VARCHAR2(20),
MILIEU_FORMAT  			VARCHAR2(20),
FIN_CODE   			NUMBER,
MODE_ES_VIS_RES  		VARCHAR2(40),
VISITEUR_CTRL_PLUS		VARCHAR2(4),
MATRA				VARCHAR2(30)
);

INSERT INTO TQ_COMMUNE (NOM_IMG_DEF,HAUTEUR,LARGEUR,PERMIS_TRAVAIL,PARAM_ALTAIR,TITRE,BDG_FREE1,BDG_FREE2,BDG_FREE3,BDG_FREE4,BDG_FREE5,BDG_FREE6,BDG_FREE7,BDG_FREE8,PLANS_FREE1,PLANS_FREE2,PLANS_FREE3,PLANS_FREE4,PLANS_FREE5,PLANS_FREE6,PLANS_FREE7,PLANS_FREE8,PLANS_FREE9) VALUES ('capture_webcam_telemaque2.bmp',198,150,0,0,'Telemaque C/S','CIVILITEV','CIVILITER','DATEFIN','nature','ABREGEN','ETAGE','PLANLIBELLE','SERVICER','CIVILITEV','CIVILITER','SITER','BATIMENT','ETAGE','BUREAUR','PLANLIBELLE','SERVICER','TELR');
INSERT INTO TQ_POSTE (NOM_POSTE,NB_CAR_RECHERCHE,DELAI_RECHERCHE,SEPARATEUR,CHAMP1,CHAMP2,CHAMP3,CHAMP4,CHAMP5,POS_CHAMP1,POS_CHAMP2,POS_CHAMP3,POS_CHAMP4,POS_CHAMP5,BLOCAGE_HDEBUT_VISITE,RESID_CTRL_HORAIRE_MSG,RESID_CTRL_HORAIRE_VERROU,RESID_HORAIRE_VERROU,FERMETURE_FENETRE_APRES_BDG,HISTORIQUE,MODIF_CHAMPS_OBS,MSG_ALERTEXJOUR_AVANTJ,MSG_CONFIR_ES,MSG_INFOR_FORMATIONS_PERIMEES,AFFICHAGE_DATE_SI_STATUT_LONG,BLOCAGE_SI_FORM_PERIMEE,SELECT_MODEL_BDG,SELECT_IMPR_BDG,ELARGIR_PAR_DEFAUT,TRACAGE,FICHIER_TRACE,ENVOI_BDG_MANUEL,ENVOI_BDG_AUTO,GENERATION_BDG,DEBUT_CODE,MILIEU_CHAMP,MILIEU_FORMAT,FIN_CODE,MODE_ES_VIS_RES,VISITEUR_CTRL_PLUS) VALUES ('VPARDEFAUT',1,700,'{Tab}','Civ','Nom','Prenom','Societe','Fonction',1,2,3,4,5,0,1,0,0,1,0,0,10,0,0,0,0,0,0,0,0,'Trace.log',0,0,0,1,'NUMEROVISITE','NUMBER/6',0,0,0);

ALTER TABLE TQ_COMMUNE ADD (IMPORTATION INTEGER);
ALTER TABLE VERSION_SFW ADD (VERSION VARCHAR2(50));
CREATE TABLE ZCL00 (NUMEROCLIENT VARCHAR2(50));

ALTER TABLE INTERLOCUTEUR ADD (
SITE_CREATION	VARCHAR2(35),
SITE_MODIF	VARCHAR2(35)
);

ALTER TABLE USERS ADD (
SITE	VARCHAR2(35)
);

CREATE TABLE VEHICULE_DEMANDE (
	VEHICULEID	VARCHAR2(14),
	RESIDANTID	VARCHAR2(14),
	DATEDEMANDE	DATE,
	IMMATRICULATION	VARCHAR2(14),
	MARQUE		VARCHAR2(20),
	MODELE		VARCHAR2(40),
	COTE		NUMBER,
	STATUT		VARCHAR2(40),
	DATECREATION	DATE
);

ALTER TABLE VISITES ADD	(
	MARQUE		VARCHAR2(20),
	MODELE		VARCHAR2(40),
	COTE		NUMBER
);

ALTER TABLE SITE DROP CONSTRAINT fk_site_planid;


ALTER TABLE BATIMENT DROP CONSTRAINT fk_bat_planid;

COMMIT;
EXIT;

