DERNIERE MODIFICATION : 23/09/2003
--------------------------------------------------------


--------------------------------------------------------
-- 2003_01_24
ALTER TABLE INTERLOCUTEUR ADD ADRESSE VARCHAR2(150);
ALTER TABLE INTERLOCUTEUR ADD CODEPOSTAL VARCHAR2(10);
ALTER TABLE INTERLOCUTEUR ADD VILLE VARCHAR2(35);

--------------------------------------------------------
-- 2003_02_26
ALTER TABLE COLISEMIS ADD PRIX NUMBER;
ALTER TABLE COLISEMIS ADD D_APROB DATE;
ALTER TABLE COLISEMIS ADD GENRE_PROB VARCHAR2(14);
ALTER TABLE COLISEMIS ADD GUICHETID VARCHAR2(14);

ALTER TABLE COLISRECU ADD LIEU VARCHAR2(14);
ALTER TABLE COLISRECU ADD GUICHETID VARCHAR2(14);

--------------------------------------------------------
-- 2003_03_26
ALTER TABLE ZCL01_ACTION ADD NSMI INTEGER;
ALTER TABLE ZCL01_CLASS_ACC ADD NSMI INTEGER;
ALTER TABLE ZCL01_FAMILLE  ADD NSMI INTEGER;
ALTER TABLE ZCL01_LECTEURS ADD NSMI INTEGER;
ALTER TABLE ZCL01_SERVICE ADD NSMI INTEGER;
ALTER TABLE ZCL01_ZH ADD NSMI INTEGER;
ALTER TABLE PROFILESMV ADD NSMI INTEGER;

--------------------------------------------------------
-- 2003_04_03
CREATE TABLE ZCL01_BA (
  NUMBDG  VARCHAR2 (14)  NOT NULL,
  CODSIT  VARCHAR2 (3),
  CODIND  VARCHAR2 (10),
  TYPSAI  VARCHAR2 (1));

CREATE TABLE ZCL01_US (
  NUMBDG     VARCHAR2 (14)  NOT NULL,
  NOM        VARCHAR2 (24),
  PRENOM     VARCHAR2 (24),
  TYPEV      VARCHAR2 (1),
  MATRIC     VARCHAR2 (15),
  SERVIC     VARCHAR2 (24),
  NOMSTE     VARCHAR2 (15),
  CH_EXPL01  VARCHAR2 (26),
  CH_EXPL02  VARCHAR2 (26),
  CH_EXPL03  VARCHAR2 (26),
  CH_EXPL04  VARCHAR2 (26),
  CH_EXPL05  VARCHAR2 (26),
  CH_EXPL06  VARCHAR2 (26),
  CH_EXPL07  VARCHAR2 (26),
  CH_EXPL08  VARCHAR2 (26),
  CH_EXPL09  VARCHAR2 (26),
  CH_EXPL10  VARCHAR2 (26),
  CH_EXPL11  VARCHAR2 (26),
  CH_EXPL12  VARCHAR2 (26),
  CH_EXPL13  VARCHAR2 (26),
  CH_EXPL14  VARCHAR2 (26),
  CH_EXPL15  VARCHAR2 (26),
  CH_EXPL16  VARCHAR2 (26),
  CH_EXPL17  VARCHAR2 (26),
  CH_EXPL18  VARCHAR2 (26),
  CH_EXPL19  VARCHAR2 (26),
  CH_EXPL20  VARCHAR2 (26),
  CONSTRAINT PK_NUMBDG PRIMARY KEY (NUMBDG) );

CREATE TABLE PROFILESMV (
  PROFILESMVID VARCHAR2(14) NOT NULL,
  CLASSID NUMBER(2,0),
  CLASSNAME VARCHAR2(24),
  ZHGLEC1 VARCHAR(2),
  ZHGLEC2 VARCHAR(2),
  ZHGLEC3 VARCHAR(2),
  ZHGLEC4 VARCHAR(2),
  ZHGLEC5 VARCHAR(2),
  ZHGLEC6 VARCHAR(2),
  ZHGLEC7 VARCHAR(2),
  ZHGLEC8 VARCHAR(2),
  NUMLEC1 VARCHAR(8),
  NUMLEC2 VARCHAR(8),
  ZH1     VARCHAR(2),
  ZH2     VARCHAR(2),
  ACTLEC1 VARCHAR(4),
  ACTLEC2 VARCHAR(4),
  ACTGRP1 VARCHAR(4),
  LIBELLE VARCHAR2(24),
  IFAMILLE VARCHAR2(24),
  IFAMILLEID VARCHAR2(24),
  ISERVICE VARCHAR2(24),
  SERVICE VARCHAR2(35),
  SERVICEID VARCHAR2(14),
  DEFAUT VARCHAR2(1),
  NSMI INTEGER,
  DATECREATION DATE,
  DATEMAJ DATE,
  DATESYNCHRO DATE,
  CONSTRAINT PK_PROFILESMVID PRIMARY KEY (PROFILESMVID)
  );
--------------------------------------------------------
-- 2003_04_11
ALTER TABLE VISITES ADD LIEU VARCHAR2(50);

--------------------------------------------------------
-- 2003_05_26
ALTER TABLE IDENTITES ADD INTERLOCUTEURID VARCHAR2(14);

UPDATE IDENTITES SET INTERLOCUTEURID='XXX'
WHERE IDENTITEID IN (SELECT IDENTITEID FROM INTERLOCUTEUR WHERE IDENTITEID IS NOT NULL );

DELETE FROM IDENTITES WHERE IDENTITEID IN (SELECT IDENTITEID FROM INTERLOCUTEUR HAVING COUNT(IDENTITEID)>1 GROUP BY IDENTITEID);


UPDATE INTERLOCUTEUR SET IDENTITEID='' WHERE IDENTITEID IN (SELECT IDENTITEID FROM INTERLOCUTEUR HAVING COUNT(IDENTITEID)>1  GROUP BY IDENTITEID);

UPDATE IDENTITES SET INTERLOCUTEURID=
(SELECT INTERLOCUTEURID FROM INTERLOCUTEUR WHERE IDENTITEID=IDENTITES.IDENTITEID )
WHERE INTERLOCUTEURID='XXX' AND IDENTITEID IN (SELECT IDENTITEID FROM INTERLOCUTEUR);
--------------------------------------------------------
-- 2003_06_03
ALTER TABLE CFGGSALLESPARAM ADD (
  RESA_ORDRE_SALLE  INTEGER,
  RESA_PRESTA_STYLE INTEGER,
  FILTRE_ORDRE_TRI  INTEGER
);

UPDATE CFGGSALLESPARAM SET RESA_ORDRE_SALLE=0,RESA_PRESTA_STYLE=0,FILTRE_ORDRE_TRI=0;

-- 2003_06_06
ALTER TABLE PASSAGER ADD (
  DATECREATION DATE,
  DATEMAJ      DATE,
  DATESYNCHRO  DATE);

UPDATE PASSAGER SET DATECREATION=SYSDATE,DATEMAJ=SYSDATE;

ALTER TABLE TYPECONSIGNE ADD (
  DATECREATION DATE,
  DATEMAJ      DATE,
  DATESYNCHRO  DATE);

UPDATE TYPECONSIGNE SET DATECREATION=SYSDATE,DATEMAJ=SYSDATE;

ALTER TABLE TYPEVISITE ADD (
  DATECREATION DATE,
  DATEMAJ      DATE,
  DATESYNCHRO  DATE);

UPDATE TYPEVISITE SET DATECREATION=SYSDATE,DATEMAJ=SYSDATE;

ALTER TABLE DROITS ADD (
  DATECREATION DATE,
  DATEMAJ      DATE,
  DATESYNCHRO  DATE);

UPDATE DROITS SET DATECREATION=SYSDATE,DATEMAJ=SYSDATE;

--  BTL - BTNE - BTNR

CREATE TABLE SN_SITES (
  SITEID               VARCHAR2 (14)  NOT NULL,
  ADRESSEIP            VARCHAR2 (14)  NOT NULL,
  NOM                  VARCHAR2 (35),
  LOGIN                VARCHAR2 (35)  NOT NULL,
  PASSWORD             VARCHAR2 (35)  NOT NULL,
  NUMERO               VARCHAR2 (35),
  DATEDERNIERESYNCHRO  DATE          NOT NULL,
  SERVERNAME_BL VARCHAR2(50),
  USERNAME_BL VARCHAR2(50),
  PASSWORD_BL VARCHAR2(50),
  SERVERNAME_BTL VARCHAR2(50),
  USERNAME_BTL VARCHAR2(50),
  PASSWORD_BTL VARCHAR2(50));

CREATE TABLE SN_SITE_ACTION (
  SITEID   VARCHAR2 (14)  NOT NULL,
  ACTION   VARCHAR2 (50)  NOT NULL,
  DATEMAJ  DATE,
  NOM_TABLE  VARCHAR2(50),
  ID		   varchar2(50));

CREATE TABLE SN_TRACES (
  TRACEID             VARCHAR2 (14)  NOT NULL,
  SITEID              VARCHAR2 (14)  NOT NULL,
  DATEECHECCONNEXION  DATE          NOT NULL,
  ADRESSE_IP          VARCHAR2 (50),
  NOM_MACHINE         VARCHAR2 (50),
  LOGIN               VARCHAR2 (50),
  PASSWORD            VARCHAR2 (50),
  NUMERO              VARCHAR2 (50),
  TYPE_TRACE          VARCHAR2 (50),
  CODE                NUMBER);

CREATE TABLE SN_TRANSFERT_IMMEDIAT (
  SITEID  VARCHAR2 (14),
  ACTION  VARCHAR2 (14),
  HMAJ    DATE,
  NOM_TABLE  VARCHAR2(50),
  ID	     VARCHAR2(50));

CREATE TABLE SN_TYPE_ACTION (
  ACTIONID  VARCHAR2 (14)  NOT NULL,
  ACTION    VARCHAR2 (50));

CREATE TABLE SN_TYPE_TRACE (
  CODE     NUMBER,
  LIBELLE  VARCHAR2 (50));

CREATE TABLE SN_DOUBLONS (
  DOUBLONID   VARCHAR2 (14),
  REMPLACEID  VARCHAR2 (14),
  NUMTABLE NUMBER);

--------------------------------------------------------
-- 2003_06_19
CREATE TABLE ZONE(
  ZONEID           VARCHAR2(14) NOT NULL,
  ZONENOM          VARCHAR2(20),
  ZONERESPONSABLE  VARCHAR2(30),
  DATEMAJ          DATE,
  DATECREATION     DATE,
  DATESYNCHRO      DATE);

CREATE TABLE ZCL01_VISITEZO (
   VISITEID VARCHAR2(14),
   ZONEID   VARCHAR2(14)
);

CREATE TABLE ZCL01_VISITERE (
   EXTERNALID VARCHAR2(14),
   RESIDANTID VARCHAR2(14)
);

CREATE TABLE ZCL01_EMISSION (
  EMI_COD    VARCHAR2 (14) NOT NULL,
  EMI_DEST1  VARCHAR2 (100),
  EMI_DEST2  VARCHAR2 (100),
  EMI_DEST3  VARCHAR2 (100),
  EMI_DEST4  VARCHAR2 (100),
  EMI_DEST5  VARCHAR2 (100),
  EMI_OBJET  VARCHAR2 (100),
  EMI_TEXTE  VARCHAR2 (500));

--------------------------------------------------------
-- 2003_07_01
UPDATE ARTICLE SET CODEFAMILLE=(SELECT CODEFAMILLE
FROM SOUSFAMILLE WHERE CODESOUSFAMILLE=ARTICLE.CODESOUSFAMILLE);

--------------------------------------------------------
-- 2003_07_03
ALTER TABLE SOCIETE ADD (ADRESSE2 VARCHAR2(150));

--------------------------------------------------------
-- 2003_07_18
ALTER TABLE PROFILESMV  ADD IFAMILLE2 VARCHAR2(24);
ALTER TABLE PROFILESMV  ADD IFAMILLEID2 VARCHAR2(24);
ALTER TABLE PROFILESMV  ADD CLASSID2 NUMBER(2,0);
ALTER TABLE PROFILESMV  ADD CLASSNAME2 VARCHAR2(24);
ALTER TABLE PROFILESMV  ADD ZHGLEC12 VARCHAR(2);
ALTER TABLE PROFILESMV  ADD ZHGLEC22 VARCHAR(2);
ALTER TABLE PROFILESMV  ADD ZHGLEC32 VARCHAR(2);
ALTER TABLE PROFILESMV  ADD ZHGLEC42 VARCHAR(2);
ALTER TABLE PROFILESMV  ADD ZHGLEC52 VARCHAR(2);
ALTER TABLE PROFILESMV  ADD ZHGLEC62 VARCHAR(2);
ALTER TABLE PROFILESMV  ADD ZHGLEC72 VARCHAR(2);
ALTER TABLE PROFILESMV  ADD ZHGLEC82 VARCHAR(2);
ALTER TABLE PROFILESMV  ADD NUMLEC12 VARCHAR(8);
ALTER TABLE PROFILESMV  ADD NUMLEC22 VARCHAR(8);
ALTER TABLE PROFILESMV  ADD ZH12     VARCHAR(2);
ALTER TABLE PROFILESMV  ADD ZH22     VARCHAR(2);
ALTER TABLE PROFILESMV  ADD ACTLEC12 VARCHAR(4);
ALTER TABLE PROFILESMV  ADD ACTLEC22 VARCHAR(4);
ALTER TABLE PROFILESMV  ADD ACTGRP12 VARCHAR(4);

ALTER TABLE PROFILESMV  ADD IFAMILLE3 VARCHAR2(24);
ALTER TABLE PROFILESMV  ADD IFAMILLEID3 VARCHAR2(24);
ALTER TABLE PROFILESMV  ADD CLASSID3 NUMBER(2,0);
ALTER TABLE PROFILESMV  ADD CLASSNAME3 VARCHAR2(24);
ALTER TABLE PROFILESMV  ADD ZHGLEC13 VARCHAR(2);
ALTER TABLE PROFILESMV  ADD ZHGLEC23 VARCHAR(2);
ALTER TABLE PROFILESMV  ADD ZHGLEC33 VARCHAR(2);
ALTER TABLE PROFILESMV  ADD ZHGLEC43 VARCHAR(2);
ALTER TABLE PROFILESMV  ADD ZHGLEC53 VARCHAR(2);
ALTER TABLE PROFILESMV  ADD ZHGLEC63 VARCHAR(2);
ALTER TABLE PROFILESMV  ADD ZHGLEC73 VARCHAR(2);
ALTER TABLE PROFILESMV  ADD ZHGLEC83 VARCHAR(2);
ALTER TABLE PROFILESMV  ADD NUMLEC13 VARCHAR(8);
ALTER TABLE PROFILESMV  ADD NUMLEC23 VARCHAR(8);
ALTER TABLE PROFILESMV  ADD ZH13     VARCHAR(2);
ALTER TABLE PROFILESMV  ADD ZH23     VARCHAR(2);
ALTER TABLE PROFILESMV  ADD ACTLEC13 VARCHAR(4);
ALTER TABLE PROFILESMV  ADD ACTLEC23 VARCHAR(4);
ALTER TABLE PROFILESMV  ADD ACTGRP13 VARCHAR(4);

ALTER TABLE PROFILESMV  ADD IFAMILLE4 VARCHAR2(24);
ALTER TABLE PROFILESMV  ADD IFAMILLEID4 VARCHAR2(24);
ALTER TABLE PROFILESMV  ADD CLASSID4 NUMBER(2,0);
ALTER TABLE PROFILESMV  ADD CLASSNAME4 VARCHAR2(24);
ALTER TABLE PROFILESMV  ADD ZHGLEC14 VARCHAR(2);
ALTER TABLE PROFILESMV  ADD ZHGLEC24 VARCHAR(2);
ALTER TABLE PROFILESMV  ADD ZHGLEC34 VARCHAR(2);
ALTER TABLE PROFILESMV  ADD ZHGLEC44 VARCHAR(2);
ALTER TABLE PROFILESMV  ADD ZHGLEC54 VARCHAR(2);
ALTER TABLE PROFILESMV  ADD ZHGLEC64 VARCHAR(2);
ALTER TABLE PROFILESMV  ADD ZHGLEC74 VARCHAR(2);
ALTER TABLE PROFILESMV  ADD ZHGLEC84 VARCHAR(2);
ALTER TABLE PROFILESMV  ADD NUMLEC14 VARCHAR(8);
ALTER TABLE PROFILESMV  ADD NUMLEC24 VARCHAR(8);
ALTER TABLE PROFILESMV  ADD ZH14     VARCHAR(2);
ALTER TABLE PROFILESMV  ADD ZH24     VARCHAR(2);
ALTER TABLE PROFILESMV  ADD ACTLEC14 VARCHAR(4);
ALTER TABLE PROFILESMV  ADD ACTLEC24 VARCHAR(4);
ALTER TABLE PROFILESMV  ADD ACTGRP14 VARCHAR(4);

ALTER TABLE PROFILESMV  ADD IFAMILLE5 VARCHAR2(24);
ALTER TABLE PROFILESMV  ADD IFAMILLEID5 VARCHAR2(24);
ALTER TABLE PROFILESMV  ADD CLASSID5 NUMBER(2,0);
ALTER TABLE PROFILESMV  ADD CLASSNAME5 VARCHAR2(24);
ALTER TABLE PROFILESMV  ADD ZHGLEC15 VARCHAR(2);
ALTER TABLE PROFILESMV  ADD ZHGLEC25 VARCHAR(2);
ALTER TABLE PROFILESMV  ADD ZHGLEC35 VARCHAR(2);
ALTER TABLE PROFILESMV  ADD ZHGLEC45 VARCHAR(2);
ALTER TABLE PROFILESMV  ADD ZHGLEC55 VARCHAR(2);
ALTER TABLE PROFILESMV  ADD ZHGLEC65 VARCHAR(2);
ALTER TABLE PROFILESMV  ADD ZHGLEC75 VARCHAR(2);
ALTER TABLE PROFILESMV  ADD ZHGLEC85 VARCHAR(2);
ALTER TABLE PROFILESMV  ADD NUMLEC15 VARCHAR(8);
ALTER TABLE PROFILESMV  ADD NUMLEC25 VARCHAR(8);
ALTER TABLE PROFILESMV  ADD ZH15     VARCHAR(2);
ALTER TABLE PROFILESMV  ADD ZH25     VARCHAR(2);
ALTER TABLE PROFILESMV  ADD ACTLEC15 VARCHAR(4);
ALTER TABLE PROFILESMV  ADD ACTLEC25 VARCHAR(4);
ALTER TABLE PROFILESMV  ADD ACTGRP15 VARCHAR(4);

ALTER TABLE PROFILESMV  ADD IFAMILLE6 VARCHAR2(24);
ALTER TABLE PROFILESMV  ADD IFAMILLEID6 VARCHAR2(24);
ALTER TABLE PROFILESMV  ADD CLASSID6 NUMBER(2,0);
ALTER TABLE PROFILESMV  ADD CLASSNAME6 VARCHAR2(24);
ALTER TABLE PROFILESMV  ADD ZHGLEC16 VARCHAR(2);
ALTER TABLE PROFILESMV  ADD ZHGLEC26 VARCHAR(2);
ALTER TABLE PROFILESMV  ADD ZHGLEC36 VARCHAR(2);
ALTER TABLE PROFILESMV  ADD ZHGLEC46 VARCHAR(2);
ALTER TABLE PROFILESMV  ADD ZHGLEC56 VARCHAR(2);
ALTER TABLE PROFILESMV  ADD ZHGLEC66 VARCHAR(2);
ALTER TABLE PROFILESMV  ADD ZHGLEC76 VARCHAR(2);
ALTER TABLE PROFILESMV  ADD ZHGLEC86 VARCHAR(2);
ALTER TABLE PROFILESMV  ADD NUMLEC16 VARCHAR(8);
ALTER TABLE PROFILESMV  ADD NUMLEC26 VARCHAR(8);
ALTER TABLE PROFILESMV  ADD ZH16     VARCHAR(2);
ALTER TABLE PROFILESMV  ADD ZH26     VARCHAR(2);
ALTER TABLE PROFILESMV  ADD ACTLEC16 VARCHAR(4);
ALTER TABLE PROFILESMV  ADD ACTLEC26 VARCHAR(4);
ALTER TABLE PROFILESMV  ADD ACTGRP16 VARCHAR(4);

ALTER TABLE PROFILESMV  ADD IFAMILLE7 VARCHAR2(24);
ALTER TABLE PROFILESMV  ADD IFAMILLEID7 VARCHAR2(24);
ALTER TABLE PROFILESMV  ADD CLASSID7 NUMBER(2,0);
ALTER TABLE PROFILESMV  ADD CLASSNAME7 VARCHAR2(24);
ALTER TABLE PROFILESMV  ADD ZHGLEC17 VARCHAR(2);
ALTER TABLE PROFILESMV  ADD ZHGLEC27 VARCHAR(2);
ALTER TABLE PROFILESMV  ADD ZHGLEC37 VARCHAR(2);
ALTER TABLE PROFILESMV  ADD ZHGLEC47 VARCHAR(2);
ALTER TABLE PROFILESMV  ADD ZHGLEC57 VARCHAR(2);
ALTER TABLE PROFILESMV  ADD ZHGLEC67 VARCHAR(2);
ALTER TABLE PROFILESMV  ADD ZHGLEC77 VARCHAR(2);
ALTER TABLE PROFILESMV  ADD ZHGLEC87 VARCHAR(2);
ALTER TABLE PROFILESMV  ADD NUMLEC17 VARCHAR(8);
ALTER TABLE PROFILESMV  ADD NUMLEC27 VARCHAR(8);
ALTER TABLE PROFILESMV  ADD ZH17     VARCHAR(2);
ALTER TABLE PROFILESMV  ADD ZH27     VARCHAR(2);
ALTER TABLE PROFILESMV  ADD ACTLEC17 VARCHAR(4);
ALTER TABLE PROFILESMV  ADD ACTLEC27 VARCHAR(4);
ALTER TABLE PROFILESMV  ADD ACTGRP17 VARCHAR(4);

ALTER TABLE PROFILESMV  ADD IFAMILLE8 VARCHAR2(24);
ALTER TABLE PROFILESMV  ADD IFAMILLEID8 VARCHAR2(24);
ALTER TABLE PROFILESMV  ADD CLASSID8 NUMBER(2,0);
ALTER TABLE PROFILESMV  ADD CLASSNAME8 VARCHAR2(24);
ALTER TABLE PROFILESMV  ADD ZHGLEC18 VARCHAR(2);
ALTER TABLE PROFILESMV  ADD ZHGLEC28 VARCHAR(2);
ALTER TABLE PROFILESMV  ADD ZHGLEC38 VARCHAR(2);
ALTER TABLE PROFILESMV  ADD ZHGLEC48 VARCHAR(2);
ALTER TABLE PROFILESMV  ADD ZHGLEC58 VARCHAR(2);
ALTER TABLE PROFILESMV  ADD ZHGLEC68 VARCHAR(2);
ALTER TABLE PROFILESMV  ADD ZHGLEC78 VARCHAR(2);
ALTER TABLE PROFILESMV  ADD ZHGLEC88 VARCHAR(2);
ALTER TABLE PROFILESMV  ADD NUMLEC18 VARCHAR(8);
ALTER TABLE PROFILESMV  ADD NUMLEC28 VARCHAR(8);
ALTER TABLE PROFILESMV  ADD ZH18     VARCHAR(2);
ALTER TABLE PROFILESMV  ADD ZH28     VARCHAR(2);
ALTER TABLE PROFILESMV  ADD ACTLEC18 VARCHAR(4);
ALTER TABLE PROFILESMV  ADD ACTLEC28 VARCHAR(4);
ALTER TABLE PROFILESMV  ADD ACTGRP18 VARCHAR(4);

ALTER TABLE PROFILESMV  ADD IFAMILLE9 VARCHAR2(24);
ALTER TABLE PROFILESMV  ADD IFAMILLEID9 VARCHAR2(24);
ALTER TABLE PROFILESMV  ADD CLASSID9 NUMBER(2,0);
ALTER TABLE PROFILESMV  ADD CLASSNAME9 VARCHAR2(24);
ALTER TABLE PROFILESMV  ADD ZHGLEC19 VARCHAR(2);
ALTER TABLE PROFILESMV  ADD ZHGLEC29 VARCHAR(2);
ALTER TABLE PROFILESMV  ADD ZHGLEC39 VARCHAR(2);
ALTER TABLE PROFILESMV  ADD ZHGLEC49 VARCHAR(2);
ALTER TABLE PROFILESMV  ADD ZHGLEC59 VARCHAR(2);
ALTER TABLE PROFILESMV  ADD ZHGLEC69 VARCHAR(2);
ALTER TABLE PROFILESMV  ADD ZHGLEC79 VARCHAR(2);
ALTER TABLE PROFILESMV  ADD ZHGLEC89 VARCHAR(2);
ALTER TABLE PROFILESMV  ADD NUMLEC19 VARCHAR(8);
ALTER TABLE PROFILESMV  ADD NUMLEC29 VARCHAR(8);
ALTER TABLE PROFILESMV  ADD ZH19     VARCHAR(2);
ALTER TABLE PROFILESMV  ADD ZH29     VARCHAR(2);
ALTER TABLE PROFILESMV  ADD ACTLEC19 VARCHAR(4);
ALTER TABLE PROFILESMV  ADD ACTLEC29 VARCHAR(4);
ALTER TABLE PROFILESMV  ADD ACTGRP19 VARCHAR(4);

ALTER TABLE PROFILESMV  ADD IFAMILLE10 VARCHAR2(24);
ALTER TABLE PROFILESMV  ADD IFAMILLEID10 VARCHAR2(24);
ALTER TABLE PROFILESMV  ADD CLASSID10 NUMBER(2,0);
ALTER TABLE PROFILESMV  ADD CLASSNAME10 VARCHAR2(24);
ALTER TABLE PROFILESMV  ADD ZHGLEC110 VARCHAR(2);
ALTER TABLE PROFILESMV  ADD ZHGLEC210 VARCHAR(2);
ALTER TABLE PROFILESMV  ADD ZHGLEC310 VARCHAR(2);
ALTER TABLE PROFILESMV  ADD ZHGLEC410 VARCHAR(2);
ALTER TABLE PROFILESMV  ADD ZHGLEC510 VARCHAR(2);
ALTER TABLE PROFILESMV  ADD ZHGLEC610 VARCHAR(2);
ALTER TABLE PROFILESMV  ADD ZHGLEC710 VARCHAR(2);
ALTER TABLE PROFILESMV  ADD ZHGLEC810 VARCHAR(2);
ALTER TABLE PROFILESMV  ADD NUMLEC110 VARCHAR(8);
ALTER TABLE PROFILESMV  ADD NUMLEC210 VARCHAR(8);
ALTER TABLE PROFILESMV  ADD ZH110     VARCHAR(2);
ALTER TABLE PROFILESMV  ADD ZH210     VARCHAR(2);
ALTER TABLE PROFILESMV  ADD ACTLEC110 VARCHAR(4);
ALTER TABLE PROFILESMV  ADD ACTLEC210 VARCHAR(4);
ALTER TABLE PROFILESMV  ADD ACTGRP110 VARCHAR(4);

ALTER TABLE PROFILESMV  ADD IFAMILLE11 VARCHAR2(24);
ALTER TABLE PROFILESMV  ADD IFAMILLEID11 VARCHAR2(24);
ALTER TABLE PROFILESMV  ADD CLASSID11 NUMBER(2,0);
ALTER TABLE PROFILESMV  ADD CLASSNAME11 VARCHAR2(24);
ALTER TABLE PROFILESMV  ADD ZHGLEC111 VARCHAR(2);
ALTER TABLE PROFILESMV  ADD ZHGLEC211 VARCHAR(2);
ALTER TABLE PROFILESMV  ADD ZHGLEC311 VARCHAR(2);
ALTER TABLE PROFILESMV  ADD ZHGLEC411 VARCHAR(2);
ALTER TABLE PROFILESMV  ADD ZHGLEC511 VARCHAR(2);
ALTER TABLE PROFILESMV  ADD ZHGLEC611 VARCHAR(2);
ALTER TABLE PROFILESMV  ADD ZHGLEC711 VARCHAR(2);
ALTER TABLE PROFILESMV  ADD ZHGLEC811 VARCHAR(2);
ALTER TABLE PROFILESMV  ADD NUMLEC111 VARCHAR(8);
ALTER TABLE PROFILESMV  ADD NUMLEC211 VARCHAR(8);
ALTER TABLE PROFILESMV  ADD ZH111     VARCHAR(2);
ALTER TABLE PROFILESMV  ADD ZH211     VARCHAR(2);
ALTER TABLE PROFILESMV  ADD ACTLEC111 VARCHAR(4);
ALTER TABLE PROFILESMV  ADD ACTLEC211 VARCHAR(4);
ALTER TABLE PROFILESMV  ADD ACTGRP111 VARCHAR(4);

ALTER TABLE PROFILESMV  ADD IFAMILLE12 VARCHAR2(24);
ALTER TABLE PROFILESMV  ADD IFAMILLEID12 VARCHAR2(24);
ALTER TABLE PROFILESMV  ADD CLASSID12 NUMBER(2,0);
ALTER TABLE PROFILESMV  ADD CLASSNAME12 VARCHAR2(24);
ALTER TABLE PROFILESMV  ADD ZHGLEC112 VARCHAR(2);
ALTER TABLE PROFILESMV  ADD ZHGLEC212 VARCHAR(2);
ALTER TABLE PROFILESMV  ADD ZHGLEC312 VARCHAR(2);
ALTER TABLE PROFILESMV  ADD ZHGLEC412 VARCHAR(2);
ALTER TABLE PROFILESMV  ADD ZHGLEC512 VARCHAR(2);
ALTER TABLE PROFILESMV  ADD ZHGLEC612 VARCHAR(2);
ALTER TABLE PROFILESMV  ADD ZHGLEC712 VARCHAR(2);
ALTER TABLE PROFILESMV  ADD ZHGLEC812 VARCHAR(2);
ALTER TABLE PROFILESMV  ADD NUMLEC112 VARCHAR(8);
ALTER TABLE PROFILESMV  ADD NUMLEC212 VARCHAR(8);
ALTER TABLE PROFILESMV  ADD ZH112     VARCHAR(2);
ALTER TABLE PROFILESMV  ADD ZH212     VARCHAR(2);
ALTER TABLE PROFILESMV  ADD ACTLEC112 VARCHAR(4);
ALTER TABLE PROFILESMV  ADD ACTLEC212 VARCHAR(4);
ALTER TABLE PROFILESMV  ADD ACTGRP112 VARCHAR(4);

ALTER TABLE PROFILESMV  ADD IFAMILLE13 VARCHAR2(24);
ALTER TABLE PROFILESMV  ADD IFAMILLEID13 VARCHAR2(24);
ALTER TABLE PROFILESMV  ADD CLASSID13 NUMBER(2,0);
ALTER TABLE PROFILESMV  ADD CLASSNAME13 VARCHAR2(24);
ALTER TABLE PROFILESMV  ADD ZHGLEC113 VARCHAR(2);
ALTER TABLE PROFILESMV  ADD ZHGLEC213 VARCHAR(2);
ALTER TABLE PROFILESMV  ADD ZHGLEC313 VARCHAR(2);
ALTER TABLE PROFILESMV  ADD ZHGLEC413 VARCHAR(2);
ALTER TABLE PROFILESMV  ADD ZHGLEC513 VARCHAR(2);
ALTER TABLE PROFILESMV  ADD ZHGLEC613 VARCHAR(2);
ALTER TABLE PROFILESMV  ADD ZHGLEC713 VARCHAR(2);
ALTER TABLE PROFILESMV  ADD ZHGLEC813 VARCHAR(2);
ALTER TABLE PROFILESMV  ADD NUMLEC113 VARCHAR(8);
ALTER TABLE PROFILESMV  ADD NUMLEC213 VARCHAR(8);
ALTER TABLE PROFILESMV  ADD ZH113     VARCHAR(2);
ALTER TABLE PROFILESMV  ADD ZH213     VARCHAR(2);
ALTER TABLE PROFILESMV  ADD ACTLEC113 VARCHAR(4);
ALTER TABLE PROFILESMV  ADD ACTLEC213 VARCHAR(4);
ALTER TABLE PROFILESMV  ADD ACTGRP113 VARCHAR(4);

ALTER TABLE PROFILESMV  ADD IFAMILLE14 VARCHAR2(24);
ALTER TABLE PROFILESMV  ADD IFAMILLEID14 VARCHAR2(24);
ALTER TABLE PROFILESMV  ADD CLASSID14 NUMBER(2,0);
ALTER TABLE PROFILESMV  ADD CLASSNAME14 VARCHAR2(24);
ALTER TABLE PROFILESMV  ADD ZHGLEC114 VARCHAR(2);
ALTER TABLE PROFILESMV  ADD ZHGLEC214 VARCHAR(2);
ALTER TABLE PROFILESMV  ADD ZHGLEC314 VARCHAR(2);
ALTER TABLE PROFILESMV  ADD ZHGLEC414 VARCHAR(2);
ALTER TABLE PROFILESMV  ADD ZHGLEC514 VARCHAR(2);
ALTER TABLE PROFILESMV  ADD ZHGLEC614 VARCHAR(2);
ALTER TABLE PROFILESMV  ADD ZHGLEC714 VARCHAR(2);
ALTER TABLE PROFILESMV  ADD ZHGLEC814 VARCHAR(2);
ALTER TABLE PROFILESMV  ADD NUMLEC114 VARCHAR(8);
ALTER TABLE PROFILESMV  ADD NUMLEC214 VARCHAR(8);
ALTER TABLE PROFILESMV  ADD ZH114     VARCHAR(2);
ALTER TABLE PROFILESMV  ADD ZH214     VARCHAR(2);
ALTER TABLE PROFILESMV  ADD ACTLEC114 VARCHAR(4);
ALTER TABLE PROFILESMV  ADD ACTLEC214 VARCHAR(4);
ALTER TABLE PROFILESMV  ADD ACTGRP114 VARCHAR(4);

ALTER TABLE PROFILESMV  ADD IFAMILLE15 VARCHAR2(24);
ALTER TABLE PROFILESMV  ADD IFAMILLEID15 VARCHAR2(24);
ALTER TABLE PROFILESMV  ADD CLASSID15 NUMBER(2,0);
ALTER TABLE PROFILESMV  ADD CLASSNAME15 VARCHAR2(24);
ALTER TABLE PROFILESMV  ADD ZHGLEC115 VARCHAR(2);
ALTER TABLE PROFILESMV  ADD ZHGLEC215 VARCHAR(2);
ALTER TABLE PROFILESMV  ADD ZHGLEC315 VARCHAR(2);
ALTER TABLE PROFILESMV  ADD ZHGLEC415 VARCHAR(2);
ALTER TABLE PROFILESMV  ADD ZHGLEC515 VARCHAR(2);
ALTER TABLE PROFILESMV  ADD ZHGLEC615 VARCHAR(2);
ALTER TABLE PROFILESMV  ADD ZHGLEC715 VARCHAR(2);
ALTER TABLE PROFILESMV  ADD ZHGLEC815 VARCHAR(2);
ALTER TABLE PROFILESMV  ADD NUMLEC115 VARCHAR(8);
ALTER TABLE PROFILESMV  ADD NUMLEC215 VARCHAR(8);
ALTER TABLE PROFILESMV  ADD ZH115     VARCHAR(2);
ALTER TABLE PROFILESMV  ADD ZH215     VARCHAR(2);
ALTER TABLE PROFILESMV  ADD ACTLEC115 VARCHAR(4);
ALTER TABLE PROFILESMV  ADD ACTLEC215 VARCHAR(4);
ALTER TABLE PROFILESMV  ADD ACTGRP115 VARCHAR(4);

ALTER TABLE PROFILESMV  ADD IFAMILLE16 VARCHAR2(24);
ALTER TABLE PROFILESMV  ADD IFAMILLEID16 VARCHAR2(24);
ALTER TABLE PROFILESMV  ADD CLASSID16 NUMBER(2,0);
ALTER TABLE PROFILESMV  ADD CLASSNAME16 VARCHAR2(24);
ALTER TABLE PROFILESMV  ADD ZHGLEC116 VARCHAR(2);
ALTER TABLE PROFILESMV  ADD ZHGLEC216 VARCHAR(2);
ALTER TABLE PROFILESMV  ADD ZHGLEC316 VARCHAR(2);
ALTER TABLE PROFILESMV  ADD ZHGLEC416 VARCHAR(2);
ALTER TABLE PROFILESMV  ADD ZHGLEC516 VARCHAR(2);
ALTER TABLE PROFILESMV  ADD ZHGLEC616 VARCHAR(2);
ALTER TABLE PROFILESMV  ADD ZHGLEC716 VARCHAR(2);
ALTER TABLE PROFILESMV  ADD ZHGLEC816 VARCHAR(2);
ALTER TABLE PROFILESMV  ADD NUMLEC116 VARCHAR(8);
ALTER TABLE PROFILESMV  ADD NUMLEC216 VARCHAR(8);
ALTER TABLE PROFILESMV  ADD ZH116     VARCHAR(2);
ALTER TABLE PROFILESMV  ADD ZH216     VARCHAR(2);
ALTER TABLE PROFILESMV  ADD ACTLEC116 VARCHAR(4);
ALTER TABLE PROFILESMV  ADD ACTLEC216 VARCHAR(4);
ALTER TABLE PROFILESMV  ADD ACTGRP116 VARCHAR(4);

--------------------------------------------------------
-- 2003_05_26
ALTER TABLE INTERLOCUTEUR DROP CONSTRAINT fk_inter_identiteid;

--------------------------------------------------------
-- 2003_08_21
UPDATE LGRESERVATION SET LIBELLESALLE=(SELECT NOSALLE||' - '||LIBELLE FROM SALLE WHERE CODESALLE=LGRESERVATION.CODESALLE);
UPDATE LGPA SET LIBELLESALLE=(SELECT NOSALLE||' - '||LIBELLE FROM SALLE WHERE CODESALLE=LGPA.CODESALLE);
--------------------------------------------------------
-- 2003_09_18
ALTER TABLE AMENAGSALLE ADD SORTORDER INTEGER;
UPDATE AMENAGSALLE SET SORTORDER=0;

--------------------------------------------------------
-- 2003_10_02
--  Table HRESERVATION
DROP TABLE HRESERVATION;
CREATE TABLE HRESERVATION (
  CODERESERVATION     VARCHAR2(14),
  CODETYPERESERVATION VARCHAR2(14),
  PRIORITE            NUMBER(*),
  SOCIETEID           VARCHAR2(14),
  INTERLOCUTEURID     VARCHAR2(14),
  USERID              VARCHAR2(14),
  CODEANIMATEUR       VARCHAR2(14),
  DATERETROCESSION    DATE,
  CODESTATUT          VARCHAR2(14),
  REFRESERVATION      VARCHAR2(15),
  NBPERSDEMANDE       NUMBER(*, 0),
  NBPERSREEL          NUMBER(*, 0),
  LIBELLE             VARCHAR2(35),
  REMISE              FLOAT,
  PRIXRESERVATION     FLOAT,
  PRIXFACTUREE        FLOAT,
  COMMENTAIRE         BLOB,
  UPDATEDBY           VARCHAR2(14),
  DEVIS               NUMBER(*),
  FACTURE             NUMBER(*),
  DATECREATION        DATE,
  DATEMAJ             DATE,
  DATESYNCHRO         DATE,
  IMPUTATIONID        VARCHAR2(14),
  TYPERESERVATION     VARCHAR2(35),
  STATUTRESERVATION   VARCHAR2(35),
  IMPUTATION          VARCHAR2(35),
  TYPEIMPUTATION      VARCHAR2(35),
  SOCIETE             VARCHAR2(35),
  INTER_NOMP          VARCHAR2(70),
  INTER_DEPTSERV      VARCHAR2(70),
  INTER_TEL           VARCHAR2(20),
  INTER_EMAIL         VARCHAR2(100),
  ANIMATEUR_NOMP      VARCHAR2(70),
  ANIMATEUR_SOCIETE   VARCHAR2(35),
  USER_FULLNAME       VARCHAR2(50)
);

--  Table HLGRESERVATION
DROP TABLE HLGRESERVATION;
CREATE TABLE HLGRESERVATION (
  CODERESERVATION     VARCHAR2(14),
  CODESALLE           VARCHAR2(14),
  CODESTATUT          VARCHAR2(14),
  CODELGRESERVATION   VARCHAR2(14),
  CODEAMMENAGEMENT    VARCHAR2(14),
  DATEDEBUT           DATE,
  DATEFIN             DATE,
  NBJOURS             NUMBER(*),
  PRIX                FLOAT,
  CODETYPETARIF       VARCHAR2(14),
  HEUREDEBUT          DATE,
  HEUREFIN            DATE,
  HEURECONTINU        NUMBER(*),
  REMISE              FLOAT,
  LIBELLESALLE        VARCHAR2(35),
  NOSALLE             VARCHAR2(15),
  PRIXCLIENT          FLOAT,
  WIZARD              NUMBER(*),
  CAPACITE            NUMBER(*),
  DATECREATION        DATE,
  DATEMAJ             DATE,
  DATESYNCHRO         DATE,
  AMENAGEMENT         VARCHAR2(35),
  TYPETARIF           VARCHAR2(35)
);

--  Table HLGPA
DROP TABLE HLGPA;
CREATE TABLE HLGPA (
  CODERESERVATION     VARCHAR2(14),
  CODELGRESERVATION   VARCHAR2(14),
  CODESALLE           VARCHAR2(14),
  CODELGPA            VARCHAR2(14),
  CODEARTICLE         VARCHAR2(14),
  DATEDEBUT           DATE,
  DATEFIN             DATE,
  QUANTITE            FLOAT,
  PRIX                FLOAT,
  CODETVA             VARCHAR2(14),
  TAUXTVA             FLOAT,
  HEUREDEBUT          DATE,
  HEUREFIN            DATE,
  HEURECONTINU        NUMBER(*),
  REMISE              FLOAT,
  LIBELLESALLE        VARCHAR2(35),
  NOSALLE             VARCHAR2(15),
  PRIXCLIENT          FLOAT,
  WIZARD              NUMBER(*),
  DATECREATION        DATE,
  DATEMAJ             DATE,
  DATESYNCHRO         DATE,
  COMMENTAIRE         BLOB,
  CONFIRMER           INTEGER,
  ARTICLE             VARCHAR2(50),
  TVA                 VARCHAR2(30)
);

--  Table HLGPARTICIPANT
DROP TABLE HLGPARTICIPANT;
CREATE TABLE HLGPARTICIPANT (
  LGPARTICIPANTID     VARCHAR2(14),
  CODELGRESERVATION   VARCHAR2(14),
  RESIDANTID          VARCHAR2(14),
  INTERLOCUTEURID     VARCHAR2(14),
  CIVILITE            VARCHAR2(14),
  NOM                 VARCHAR2(35),
  PRENOM              VARCHAR2(35),
  SOCIETE             VARCHAR2(35),
  EMAIL               VARCHAR2(50),
  DATECREATION        DATE,
  DATEMAJ             DATE,
  DATESYNCHRO         DATE
);

--------------------------------------------------------
-- 2003_10_17
CREATE TABLE ZCL01_VISITE_L (
VISITEID_ANCIEN  VARCHAR2(14),
VISITEID_NOUVEAU VARCHAR2(14));

UPDATE NATURE SET TVISITE = '0' where TVISITE IS NULL;

CREATE TABLE VISITES_EXT (
  VISITES_EXTID	VARCHAR2(14),
  FREE1		VARCHAR2(50),
  FREE2		VARCHAR2(50),
  FREE3		VARCHAR2(50),
  FREE4		VARCHAR2(50),
  FREE5		VARCHAR2(50),
  FREE6		VARCHAR2(50),
  FREE7		VARCHAR2(50),
  FREE8		VARCHAR2(50),
  FREE9		VARCHAR2(50),
  FREE10	VARCHAR2(50)
);

CREATE TABLE VISITES_EXT_L (
  VISITEID_ANCIEN	VARCHAR2(14),
  VISITEID_NOUVEAU 	VARCHAR2(14)
);

CREATE TABLE VISITES_EXT_ZO (
  VISITEID	VARCHAR2(14),
  ZONEID 	VARCHAR2(14)
);

ALTER TABLE VISITES_EXT_ZO ADD ZONEID VARCHAR2(14);

ALTER TABLE PARAMETRES MODIFY (CHIMGVT VARCHAR2(4000));
ALTER TABLE PARAMETRES MODIFY (CHIMGRE VARCHAR2(4000));
ALTER TABLE PARAMETRES MODIFY (CHIMGPL VARCHAR2(4000));

COMMIT;
EXIT;


