declare
	counter integer;
begin
-- IMPUTATION_TYPEID='VPARDEFAUT'
	select count(*) into counter
	from IMPUTATION_TYPE
	where IMPUTATION_TYPEID='VPARDEFAUT';
	if counter=0 then
		INSERT INTO IMPUTATION_TYPE (IMPUTATION_TYPEID,LIBELLE) VALUES ('VPARDEFAUT','Code Imputation');
	end if;
--
-- IMPUTATION_TYPEID='1'
	select count(*) into counter
	from IMPUTATION_TYPE
	where IMPUTATION_TYPEID='1';
	if counter=0 then
		INSERT INTO IMPUTATION_TYPE (IMPUTATION_TYPEID,LIBELLE) VALUES ('1','Code projet');
	end if;
--
-- STATUTRESERVATION_ETAT=0
	select count(*) into counter
	from STATUTRESERVATION_ETAT
	where ID=0;
	if counter=0 then
		INSERT INTO STATUTRESERVATION_ETAT VALUES (0,'Apres demande de réservation',SYSDATE,SYSDATE,NULL);
	end if;
--
-- STATUTRESERVATION_ETAT=1
	select count(*) into counter
	from STATUTRESERVATION_ETAT
	where ID=1;
	if counter=0 then
		INSERT INTO STATUTRESERVATION_ETAT VALUES (1,'avant réunion',SYSDATE,SYSDATE,NULL);
	end if;
--
-- STATUTRESERVATION_SET=0
	select count(*) into counter
	from STATUTRESERVATION_SET
	where ID=0;
	if counter=0 then
		INSERT INTO STATUTRESERVATION_SET VALUES (0,'Pas de relance',SYSDATE,SYSDATE,NULL);
	end if;
--
-- STATUTRESERVATION_SET=1
	select count(*) into counter
	from STATUTRESERVATION_SET
	where ID=1;
	if counter=0 then
		INSERT INTO STATUTRESERVATION_SET VALUES (1,'Relance',SYSDATE,SYSDATE,NULL);
	end if;
--
-- STATUTRESERVATION_SET=2
	select count(*) into counter
	from STATUTRESERVATION_SET
	where ID=2;
	if counter=0 then
		INSERT INTO STATUTRESERVATION_SET VALUES (2,'Confirmer',SYSDATE,SYSDATE,NULL);
	end if;
--
-- NATURE='EXTERIEUR'
	select count(*) into counter
	from NATURE
	where NATUREID='EXTERIEUR';
	if counter=0 then
		INSERT INTO NATURE (NATUREID,LIBELLE,ABREGE,TVISITE,INTERDIT,DEBUTINTERDIT,FININTERDIT,DATECREATION,DATEMAJ) VALUES ('EXTERIEUR','EXTERIEUR','EXT','1','0',SYSDATE-1,SYSDATE+36000,SYSDATE,SYSDATE);
	end if;
--
-- ZONE='VPARDEFAUT'
	select count(*) into counter
	from ZONE
	where ZONEID='VPARDEFAUT';
	if counter=0 then
		INSERT INTO ZONE (ZONEID, ZONENOM, ZONERESPONSABLE, DATEMAJ, DATECREATION) VALUES ('VPARDEFAUT','TOUTES ZONES','**********',SYSDATE, SYSDATE);
	end if;
--
	COMMIT;
end;
/

ALTER TABLE IMPUTATION ADD LIBELLE2 VARCHAR2(35);

UPDATE VISITES SET EXTERNALID=RESIDANTID WHERE EXTERNALID IS NULL;

UPDATE ZCL01_VISITE SET ACCES=FREQUENCE WHERE FREQUENCE='VI';

-- 2004_02_06
CREATE SEQUENCE SEQ_AGENTPRESENTLOG;
CREATE SEQUENCE SEQ_CONS_ETAT;
CREATE SEQUENCE SEQ_EVENEMENT_TYPE;
CREATE SEQUENCE SEQ_EVTPERSONNEL;
CREATE SEQUENCE SEQ_JMATERIEL;
CREATE SEQUENCE SEQ_JPERSONNE;
CREATE SEQUENCE SEQ_JRAPPORT;
CREATE SEQUENCE SEQ_JSECOURS;
CREATE SEQUENCE SEQ_JVACATION;
CREATE SEQUENCE SEQ_OCONSIGNE;
CREATE SEQUENCE SEQ_ODROIT;
CREATE SEQUENCE SEQ_OJOURNAL;
CREATE SEQUENCE SEQ_OMESSAGE;
CREATE SEQUENCE SEQ_PERSONNE;
CREATE SEQUENCE SEQ_PERSONNEL;
CREATE SEQUENCE SEQ_REFERENCE;
CREATE SEQUENCE SEQ_RPT_0002;
CREATE SEQUENCE SEQ_RPT_0005;
CREATE SEQUENCE SEQ_RUE;
CREATE SEQUENCE SEQ_SECOURS;
CREATE SEQUENCE SEQ_SECTEUR;
CREATE SEQUENCE SEQ_SERVICE;

DROP SEQUENCE SEQ_jour;
CREATE SEQUENCE SEQ_jour START WITH 100 ;

DROP SEQUENCE SEQ_JVACATION;
CREATE SEQUENCE SEQ_JVACATION START WITH 1000000000;
DROP SEQUENCE SEQ_MISSIONTEMP;
CREATE SEQUENCE SEQ_MISSIONTEMP START WITH 10000;
DROP SEQUENCE SEQ_OMESSAGE;
CREATE SEQUENCE SEQ_OMESSAGE START WITH 1000000000;
DROP SEQUENCE SEQ_REFERENCE;
CREATE SEQUENCE SEQ_REFERENCE START WITH 10000000 ;
CREATE SEQUENCE SEQ_TYPERAPPORT;

CREATE SEQUENCE SEQ_VSERVICE;

INSERT INTO TYPE_MISSION (TYPE_MISSIONID, LIBELLE, DATEMAJ, DATECREATION, DATESYNCHRO) VALUES (-1,'PRISE DE POSTE',SYSDATE,SYSDATE,SYSDATE);
INSERT INTO TYPE_MISSION (TYPE_MISSIONID, LIBELLE, DATEMAJ, DATECREATION, DATESYNCHRO) VALUES (-2,'FIN DE POSTE',SYSDATE,SYSDATE,SYSDATE);
INSERT INTO TYPE_MISSION (TYPE_MISSIONID, LIBELLE, DATEMAJ, DATECREATION, DATESYNCHRO) VALUES (-3,'SANS FIN',SYSDATE,SYSDATE,SYSDATE);

INSERT INTO VSERVICE (VSERVICEID, LIBELLE, DATEMAJ, DATECREATION, DATESYNCHRO) VALUES (0,'**********',SYSDATE,SYSDATE,SYSDATE);
INSERT INTO OCONSIGNE (OCONSIGNEID,LIBELLE) VALUES (0,'**********');
INSERT INTO QUALIF (QUALIFID, LIBELLE, DATEMAJ, DATECREATION, DATESYNCHRO) VALUES (0,'**********',SYSDATE,SYSDATE,SYSDATE);
INSERT INTO RAPPORT (RAPPORTID, LIBELLE, NOMTABLE, DETAILS, AUTEURID, DATEMAJ, DATECREATION, DATESYNCHRO) VALUES (0,'**********','*','*',0,SYSDATE,SYSDATE,SYSDATE);
INSERT INTO POSTE (POSTEID,LIBELLE,DATECREATION,DATEMAJ) VALUES (0,'**********',SYSDATE,SYSDATE);
INSERT INTO PERSONNEL (PERSONNELID,THELOGIN,NOM,PRENOM,DATECREATION,DATEMAJ) VALUES (-1,'Ommnigarde','***','***',SYSDATE,SYSDATE);

INSERT INTO EVENEMENT (EVENEMENTID,LIBELLE,RAPPORTID,CONSIGNEID,ISRAPPORT,DATEMAJ,DATECREATION,DATESYNCHRO) VALUES (-1,'PRISE DE POSTE',0,0,0,SYSDATE,SYSDATE,SYSDATE);
INSERT INTO EVENEMENT (EVENEMENTID,LIBELLE,RAPPORTID,CONSIGNEID,ISRAPPORT,DATEMAJ,DATECREATION,DATESYNCHRO) VALUES (-2,'FIN DE POSTE',0,0,0,SYSDATE,SYSDATE,SYSDATE);
INSERT INTO EVENEMENT (EVENEMENTID,LIBELLE,RAPPORTID,CONSIGNEID,ISRAPPORT,DATEMAJ,DATECREATION,DATESYNCHRO) VALUES (-3,'MISSION',0,0,0,SYSDATE,SYSDATE,SYSDATE);
INSERT INTO EVENEMENT (EVENEMENTID,LIBELLE,RAPPORTID,CONSIGNEID,ISRAPPORT,DATEMAJ,DATECREATION,DATESYNCHRO) VALUES (-4,'MISSION RETARD',0,0,0,SYSDATE,SYSDATE,SYSDATE);
INSERT INTO EVENEMENT (EVENEMENTID,LIBELLE,RAPPORTID,CONSIGNEID,ISRAPPORT,DATEMAJ,DATECREATION,DATESYNCHRO) VALUES (-5,'OUVERTURE APPLI',0,0,0,SYSDATE,SYSDATE,SYSDATE);
INSERT INTO EVENEMENT (EVENEMENTID,LIBELLE,RAPPORTID,CONSIGNEID,ISRAPPORT,DATEMAJ,DATECREATION,DATESYNCHRO) VALUES (-6,'FERMETURE APPLI',0,0,0,SYSDATE,SYSDATE,SYSDATE);
INSERT INTO EVENEMENT (EVENEMENTID,LIBELLE,RAPPORTID,CONSIGNEID,ISRAPPORT,DATEMAJ,DATECREATION,DATESYNCHRO) VALUES (-7,'CONNEXION',0,0,0,SYSDATE,SYSDATE,SYSDATE);
INSERT INTO EVENEMENT (EVENEMENTID,LIBELLE,RAPPORTID,CONSIGNEID,ISRAPPORT,DATEMAJ,DATECREATION,DATESYNCHRO) VALUES (-8,'MESSAGE PONCTUEL',0,0,0,SYSDATE,SYSDATE,SYSDATE);
INSERT INTO EVENEMENT (EVENEMENTID,LIBELLE,RAPPORTID,CONSIGNEID,ISRAPPORT,DATEMAJ,DATECREATION,DATESYNCHRO) VALUES (-9,'MISSION SUPPRIMEE',0,0,0,SYSDATE,SYSDATE,SYSDATE);
INSERT INTO EVENEMENT (EVENEMENTID,LIBELLE,RAPPORTID,CONSIGNEID,ISRAPPORT,DATEMAJ,DATECREATION,DATESYNCHRO) VALUES (-10,'MISSION SUSPENDUE',0,0,0,SYSDATE,SYSDATE,SYSDATE);
INSERT INTO EVENEMENT (EVENEMENTID,LIBELLE,RAPPORTID,CONSIGNEID,ISRAPPORT,DATEMAJ,DATECREATION,DATESYNCHRO) VALUES (-11,'AGENT',0,0,0,SYSDATE,SYSDATE,SYSDATE);

INSERT INTO JOUR (JOURID, LIBELLE, TYPE_JOUR, DEBUT_VALIDITE, FIN_VALIDITE, DATEMAJ, DATECREATION) VALUES (1,'DIMANCHE','DIMANCHE',SYSDATE,'01/01/2110',SYSDATE,SYSDATE);
INSERT INTO JOUR (JOURID, LIBELLE, TYPE_JOUR, DEBUT_VALIDITE, FIN_VALIDITE, DATEMAJ, DATECREATION) VALUES (2,'LUNDI','LUNDI',SYSDATE,'01/01/2110',SYSDATE,SYSDATE);
INSERT INTO JOUR (JOURID, LIBELLE, TYPE_JOUR, DEBUT_VALIDITE, FIN_VALIDITE, DATEMAJ, DATECREATION) VALUES (3,'MARDI','MARDI',SYSDATE,'01/01/2110',SYSDATE,SYSDATE);
INSERT INTO JOUR (JOURID, LIBELLE, TYPE_JOUR, DEBUT_VALIDITE, FIN_VALIDITE, DATEMAJ, DATECREATION) VALUES (4,'MERCREDI','MERCREDI',SYSDATE,'01/01/2110',SYSDATE,SYSDATE);
INSERT INTO JOUR (JOURID, LIBELLE, TYPE_JOUR, DEBUT_VALIDITE, FIN_VALIDITE, DATEMAJ, DATECREATION) VALUES (5,'JEUDI','JEUDI',SYSDATE,'01/01/2110',SYSDATE,SYSDATE);
INSERT INTO JOUR (JOURID, LIBELLE, TYPE_JOUR, DEBUT_VALIDITE, FIN_VALIDITE, DATEMAJ, DATECREATION) VALUES (6,'VENDREDI','VENDREDI',SYSDATE,'01/01/2110',SYSDATE,SYSDATE);
INSERT INTO JOUR (JOURID, LIBELLE, TYPE_JOUR, DEBUT_VALIDITE, FIN_VALIDITE, DATEMAJ, DATECREATION) VALUES (7,'SAMEDI','SAMEDI',SYSDATE,'01/01/2110',SYSDATE,SYSDATE);

DROP INDEX ACTIONCONTACT0;
DROP INDEX RAR_CODEART;
DROP INDEX ACTIONCONTACT_LIBELLE;
DROP INDEX ADRESSE_NDX;
DROP INDEX ART_REFCONSTRUCTEUR;
DROP INDEX ART_REFERENCE;
DROP INDEX ARTDEF_TDSORTORDER;
DROP INDEX ART_PHONKEY;
DROP INDEX CONTACT_DATECONTACT;
DROP INDEX EXTERNAL_ID;
DROP INDEX EXTERNALID;
DROP INDEX BAT_SORTORDER;

DROP INDEX INTERLOCUTEUR_FONKEY;
DROP INDEX ORRIGINECONTACT_LIBELLE;
DROP INDEX DEBUT_RESID;
DROP INDEX DEVIS_AFFAIRE;
DROP INDEX DEVIS_CLIENT;
DROP INDEX FACTURE_CLIENTDATE;
DROP INDEX GROUPE;
DROP INDEX GROUPE_INTERDIT;
DROP INDEX INTERDIT;
DROP INDEX IS_SECURED;
DROP INDEX IS_ACTIF;
DROP INDEX IS_PRESTATAIRE;
DROP INDEX IS_RESIDENT;
DROP INDEX LGFACTURE_PRODUIT;
DROP INDEX NUMVISITE_SITE;
DROP INDEX PAYS_INTERDIT;
DROP INDEX PRODUIT_CODEREF;
DROP INDEX RAR_LIBELLE;
DROP INDEX RESACELL_LGRESA;
DROP INDEX RESIDANT_SITE;
DROP INDEX RESIDANTS_NOMPRENOM;
DROP INDEX SALLE;
DROP INDEX SITE_SOC_PARK;
DROP INDEX SOCIETE_INTERDIT;
DROP INDEX SOCIETE_RESID_NOM;
DROP INDEX USER_EXTERNAL;
DROP INDEX VILLE_CP;
DROP INDEX VILLE_PHONKEY;
DROP INDEX VISIT_NOMPRENOM;


DROP INDEX RESIDANTS_FONKEY;
DROP INDEX RESIDANTS_IMPORT;
DROP INDEX RESIDANTS_OUTLOOKENTRYID;
DROP INDEX SOCIETE_IMPORT;
DROP INDEX SOCIETE_OUTLOOKENTRYID;
DROP INDEX VISIT_IMPORT;
DROP INDEX VISIT_OUTLOOKENTRYID;


ALTER TABLE INTERLOCUTEUR DROP CONSTRAINT fk_inter_identiteid;
ALTER TABLE SOCIETE DROP CONSTRAINT fk_soc_groupeid;
ALTER TABLE VISITES DROP CONSTRAINT fk_visi_codesalle;
ALTER TABLE SOCIETE DROP CONSTRAINT FK_SOC_PLANID;
ALTER TABLE SOCIETE DROP CONSTRAINT FK_SOC_BADGEID;
ALTER TABLE SALLE DROP CONSTRAINT fk_salle_socid;
ALTER TABLE PARKING DROP CONSTRAINT fk_park_sociid;

--
CREATE INDEX VISIT_NOMPRENOM ON INTERLOCUTEUR(NOMPRENOM);
CREATE INDEX RESI_NOMPRENOM ON RESIDANTS(NOMPRENOM);


ALTER TABLE SN_SITES ADD (ETAT_BATCH VARCHAR(14));

ALTER TABLE INTERLOCUTEUR DROP CONSTRAINT fk_inter_pays;
ALTER TABLE INTERLOCUTEUR DROP CONSTRAINT fk_inter_socid;
ALTER TABLE INTERLOCUTEUR DROP CONSTRAINT fk_inter_natureid;

ALTER TABLE VISITES DROP CONSTRAINT fk_visi_interid;

ALTER TABLE CONSIGNE DROP CONSTRAINT fk_cons_interid;

ALTER TABLE COLISEMIS DROP CONSTRAINT fk_dole_interid;

ALTER TABLE COLISRECU DROP CONSTRAINT fk_colr_interid;


ALTER TABLE SN_SITES ADD (ETAT_BATCH VARCHAR(14));

CREATE UNIQUE INDEX U_INTERID ON INTERLOCUTEUR(INTERLOCUTEURID);
CREATE UNIQUE INDEX U_SOCIETEID ON SOCIETE(SOCIETEID);
CREATE UNIQUE INDEX U_RESIDANTID ON RESIDANTS(RESIDANTID);

ALTER TABLE CONSIGNE DROP CONSTRAINT FK_CONS_INTERID;
ALTER TABLE CONSIGNE DROP CONSTRAINT FK_CONS_RESIID;

DROP INDEX VISTE_STATUT;

CREATE INDEX VISITEUR_SUR_SITE ON VISITES(SITEID,INTERLOCUTEURID,STATUTID);

INSERT INTO ADRESSE (ADRESSEID,TYPEADRESSEID,SOCIETE,NOM,DATECREATION,DATEMAJ) VALUES ('VPARDEFAUT',0,'********','********',SYSDATE,SYSDATE);

UPDATE BADGES SET OBSERVATION='';

ALTER TABLE PARAMETRES DROP COLUMN CHIMGPL;
ALTER TABLE PARAMETRES ADD (CHIMGPL IMAGE);
ALTER TABLE PARAMETRES DROP COLUMN CHIMGRE;
ALTER TABLE PARAMETRES ADD (CHIMGRE IMAGE);
ALTER TABLE PARAMETRES DROP COLUMN CHIMGVT;
ALTER TABLE PARAMETRES ADD (CHIMGVT IMAGE);

CREATE INDEX SORTIE_VISITEUR ON VISITES(STATUTID, SITEID, NUMEROBADGE);

CREATE INDEX RESIDANT ON VISITES(SITEID, RESIDANTID, STATUTID);

CREATE TABLE ZCL07_BADGETYPE
(
 ZCL07_BADGETYPEID VARCHAR(14),
 NAME VARCHAR(25),
 CLASS INTEGER,
 SERIE VARCHAR(10),
 CUSTOMERCODE VARCHAR(10),
 DEBUT INTEGER,
 FIN INTEGER
);

------------------------------------------------------------
------------Paramétrable en fonction du site----------------
------------------------------------------------------------

INSERT INTO ZCL07_BADGETYPE VALUES ('1','Badge',1,'5','15a',0,2000);

ALTER TABLE USERS ADD (USERTYPE NUMBER(*));

CREATE TABLE BADGEIMPRIME
(
   NOUVEAUNUMERO	VARCHAR(14),
   STATUT		VARCHAR(20),
   DATEMAJ		DATE
);

CREATE INDEX VISIT_NOM ON INTERLOCUTEUR(NOM);
CREATE INDEX VISIT_INTER ON VISITES(SITEID,INTERLOCUTEURID,STATUTID,DEBUTPREVU,FINPREVU);

CREATE INDEX VISIT_RES ON RESIDANTS(ISACTIF,NOM);
CREATE INDEX VISIT_RES_SITE ON RESIDANTS(SITEID,ISACTIF,NOM);

CREATE INDEX INTER_NATURE ON INTERLOCUTEUR(INTERLOCUTEURID,NATUREID);
CREATE INDEX VISIT_INTERID ON VISITES(INTERLOCUTEURID);
CREATE INDEX NATURE_NATUREID ON NATURE(TVISITE,NATUREID);
CREATE INDEX VISIT_NUMEROVISITE ON VISITES(NUMEROVISITE);
CREATE INDEX VISIT_NUMEROVISITE1 ON VISITES(NUMEROVISITE,INTERLOCUTEURID);

CREATE TABLE VISITES_ES
(
VISITEID	VARCHAR2(14)	NOT NULL,
DATEHEUREENTREE	DATE,
DATEHEURESORTIE	DATE
);

UPDATE INTERLOCUTEUR SET NATUREID = 'VPARDEFAUT' WHERE NATUREID IS NULL;

ALTER TABLE VISITES ADD (
ORIGINEVISITE		NUMBER,
NBBDGIMPR		NUMBER,
NBBDGIMPRTOTAL		NUMBER
);

CREATE TABLE SALLEFUS (
   CODESALLEFUS VARCHAR2(14),
   LIBELLE  VARCHAR2(50),
   DECODESALLE VARCHAR2(14),
   DATECREATION DATE,
   DATEMAJ      DATE
);

CREATE TABLE SALLEFUS_COMP (
   CODESALLEFUS VARCHAR2(14),
   CODESALLE VARCHAR2(14)
);

ALTER TABLE PARAMETRES ADD (REFIMPORTATION VARCHAR2(48));
UPDATE PARAMETRES SET REFIMPORTATION='1';

UPDATE INTERLOCUTEUR SET PHONKEY='1' WHERE PHONKEY IS NULL;
ALTER TABLE INTERLOCUTEUR MODIFY PHONKEY VARCHAR2(35) DEFAULT '1';
ALTER TABLE RESIDANTS MODIFY ISRESIDENT VARCHAR2(1) DEFAULT '1';


CREATE TABLE VISITE_CONTROLE (
 VISITEID VARCHAR2(14),
 NUMEROVISITE NUMBER,
 RESIDANTID VARCHAR2(14),
 DATEVISITE DATE
);


ALTER TABLE INTER_RSERVICE ADD (RESIDANTID VARCHAR2(14));


CREATE INDEX INTERLOCUTEUR_DELEGUE ON INTERLOCUTEUR (NOMPRENOM, PHONKEY);

DROP INDEX INT_FONKEY;

ALTER TABLE SOCIETE ADD (NATUREID VARCHAR2(14));

UPDATE SOCIETE SET NATUREID='VPARDEFAUT';

ALTER TABLE GUICHET MODIFY POSTE NULL;


COMMIT;
EXIT;