ALTER TABLE ARTICLE ADD SITEID VARCHAR(14);
COMMIT;

--UPDATE ARTICLE SET SITEID='VPARDEFAUT';
--COMMIT;

CREATE TABLE JOUR_FERIE (
    JOUR_FERIEID INT PRIMARY KEY,
    LIBELLE VARCHAR2(100),
    DEBUT DATE,
    FIN DATE,
    DATECREATION DATE NOT NULL,
    DATEMAJ DATE NOT NULL
);
COMMIT;