ALTER TABLE DROITSTELEM ADD ETRANGER INTEGER DEFAULT 0;
COMMIT;

ALTER TABLE RESIDANTS ADD ETRANGER INTEGER DEFAULT 0;
COMMIT;

UPDATE DROITSTELEM SET ETRANGER=0;
COMMIT;
UPDATE RESIDANTS SET ETRANGER=0;
COMMIT;