ALTER TABLE COLISRECU ADD POIDS VARCHAR2(10 CHAR);
COMMIT;

ALTER TABLE COLISRECU ADD SERVICEID VARCHAR2(14 CHAR);
COMMIT;
ALTER TABLE COLISEMIS ADD SERVICEID VARCHAR2(14 CHAR);
COMMIT;

UPDATE COLISRECU SET SERVICEID='VPARDEFAUT';
COMMIT;
UPDATE COLISEMIS SET SERVICEID='VPARDEFAUT';
COMMIT;

ALTER TABLE COLISEMIS ADD VALEUR VARCHAR2(10 CHAR);
COMMIT;

ALTER TABLE COLISRECU ADD NATURECOLISID INTEGER;
COMMIT;
ALTER TABLE COLISEMIS ADD NATURECOLISID INTEGER;
COMMIT;

UPDATE COLISRECU SET NATURECOLISID='0';
COMMIT;
UPDATE COLISEMIS SET NATURECOLISID='0';
COMMIT;
UPDATE COLISEMIS SET NATURECOLISID='-1' WHERE LETTRECOLIS='2';
COMMIT;

CREATE TABLE NATURECOLIS (
  NATURECOLISID INTEGER PRIMARY KEY,
  LIBELLE VARCHAR2(50 CHAR),
  DATECREATION DATE NOT NULL,
  DATEMAJ DATE NOT NULL);
COMMIT;

INSERT INTO NATURECOLIS (NATURECOLISID,LIBELLE,DATECREATION,DATEMAJ) VALUES (0,'LETTRE',SYSDATE,SYSDATE);
INSERT INTO NATURECOLIS (NATURECOLISID,LIBELLE,DATECREATION,DATEMAJ) VALUES (-1,'COLIS',SYSDATE,SYSDATE);
INSERT INTO NATURECOLIS (NATURECOLISID,LIBELLE,DATECREATION,DATEMAJ) VALUES (-2,'PAQUET',SYSDATE,SYSDATE);
INSERT INTO NATURECOLIS (NATURECOLISID,LIBELLE,DATECREATION,DATEMAJ) VALUES (-3,'PALETTE',SYSDATE,SYSDATE);
COMMIT;

ALTER TABLE RESIDANTS ADD CONTRAT VARCHAR2(50 CHAR);
COMMIT;

DROP PROCEDURE PS_REGLE_TRT;
COMMIT;

ALTER TABLE TYPEDOCUMENT ADD INTER_EFFECT INT DEFAULT (2);
COMMIT;
UPDATE TYPEDOCUMENT SET INTER_EFFECT='2';
COMMIT;
