ALTER TABLE VISITES ADD EMETTEUR VARCHAR2(200);
ALTER TABLE VISITES ADD USER_IN VARCHAR2(200);
ALTER TABLE VISITES ADD USER_OUT VARCHAR2(200);
COMMIT;

UPDATE VISITES SET EMETTEUR=(SELECT NOMPRENOM FROM RESIDANTS WHERE RESIDANTS.RESIDANTID=VISITES.EXTERNALID) WHERE EMETTEUR IS NULL;
COMMIT;