CREATE OR REPLACE FUNCTION F_GET_ASSOCIATION (MYcodesalle VARCHAR2)
RETURN VARCHAR2
IS
    MYWork VARCHAR2(1000);
	MYCOMBI VARCHAR2(150);
	MYSALLE VARCHAR2(150);
    CURSOR CURSEUR
    IS
    SELECT SF.LIBELLE COMBI,S.LIBELLE SALLE FROM SALLEFUS SF,SALLEFUS_COMP SFC,SALLE S
	WHERE SF.CODESALLEFUS=SFC.CODESALLEFUS AND DECODESALLE=S.CODESALLE
	AND SF.CODESALLEFUS IN (SELECT SF.CODESALLEFUS FROM SALLEFUS SF,SALLEFUS_COMP SFC WHERE SF.CODESALLEFUS=SFC.CODESALLEFUS AND (DECODESALLE=MYcodesalle OR SFC.CODESALLE=MYcodesalle))
	UNION SELECT SF.LIBELLE COMBI,S.LIBELLE SALLE FROM SALLEFUS SF,SALLEFUS_COMP SFC,SALLE S
	WHERE SF.CODESALLEFUS=SFC.CODESALLEFUS AND SFC.CODESALLE=S.CODESALLE
	AND SF.CODESALLEFUS IN (SELECT SF.CODESALLEFUS FROM SALLEFUS SF,SALLEFUS_COMP SFC WHERE SF.CODESALLEFUS=SFC.CODESALLEFUS AND (DECODESALLE=MYcodesalle OR SFC.CODESALLE=MYcodesalle)) ORDER BY COMBI,SALLE;

	BEGIN

	MYwork := '';

	OPEN CURSEUR;
	LOOP
		FETCH CURSEUR
		INTO MYCOMBI,MYSALLE;

		Exit When CURSEUR%NOTFOUND;
		MYwork := MYwork||';'||MYCOMBI||'|'||MYSALLE;
	End loop ;

	CLOSE CURSEUR;


    RETURN MYwork;
END;
/
COMMIT;

CREATE OR REPLACE FUNCTION F_GET_AMENAGEMENT (MYcodesalle VARCHAR2)
RETURN VARCHAR2
IS
    MYWork VARCHAR2(1000);
	MYLIBELLE VARCHAR2(150);
	MYCAPACITE VARCHAR2(150);
	MYPREPA VARCHAR2(150);
	MYRANG VARCHAR2(150);
    CURSOR CURSEUR
    IS
    SELECT NVL(LIBELLE,'') LIBELLE,NVL(CAPACITE,'') CAPACITE,NVL(TO_CHAR(PREPARATION,'HH24:MI'),'') PREPA,NVL(TO_CHAR(RANGEMENT,'HH24:MI'),'') RANG FROM AMENAGEMENT,AMENAGSALLE WHERE AMENAGEMENT.CODEAMENAGEMENT=AMENAGSALLE.CODEAMENAGEMENT AND CODESALLE=MYcodesalle ORDER BY LIBELLE;

	BEGIN

	MYwork := '';

	OPEN CURSEUR;
	LOOP
		FETCH CURSEUR
		INTO MYLIBELLE,MYCAPACITE,MYPREPA,MYRANG;

		Exit When CURSEUR%NOTFOUND;
		MYwork := MYwork||';'||MYLIBELLE||'|'||MYCAPACITE||'|'||MYPREPA||'|'||MYRANG;
	End loop ;
	CLOSE CURSEUR;


    RETURN MYwork;
END;
/
COMMIT;