
--DROP TABLE ESVISITES_LOG;
CREATE TABLE ESVISITES_LOG (
  ESVISITES_LOGID VARCHAR(14) NOT NULL,
  QUIID VARCHAR(14),
  QUITYPE VARCHAR(40),
  NOMPRENOM VARCHAR(70),
  SOCIETE  VARCHAR(70),
  NUMBADGE VARCHAR(20),
  SENS     VARCHAR(50),
  ETAT     VARCHAR(50),
  DETAILS  VARCHAR(200),
  PASSAGE DATE,
  TYPEINSERT VARCHAR(14),
  REMOTEDATE VARCHAR(20),
  SITEID VARCHAR(14),
  GUICHETID VARCHAR(14),
  POSTE     VARCHAR(50),
  DATECREATION DATE NOT NULL,
  DATEMAJ DATE NOT NULL,
  DATESYNCHRO	 DATE
);

INSERT INTO ETATAPP (ETATID,ETATNOM,VISIBLE,REQUETE,FILTRE,APP,DATECREATION,DATEMAJ) VALUES ('ETAT_ESVISITE_LOG', 'ListePassagesES', 1, '', '', 'TQ', SYSDATE, SYSDATE);

COMMIT;


ALTER TABLE TQ_POSTE ADD GENERATION_BDGEXT INTEGER;
ALTER TABLE TQ_POSTE ADD DEBUT_CODEEXT VARCHAR(20);
ALTER TABLE TQ_POSTE ADD MILIEU_FORMATEXT VARCHAR(20);
ALTER TABLE TQ_POSTE ADD FIN_CODEEXT VARCHAR(20);

COMMIT;


CREATE SEQUENCE SEQ_NUM_BDG_RES;
CREATE SEQUENCE SEQ_NUM_BDG_VEH;
CREATE SEQUENCE SEQ_NUM_BDG_EXT;

COMMIT;
EXIT;

