ALTER TABLE INTERLOCUTEUR ADD DOUBLON_TRAITE INT DEFAULT 0;
UPDATE INTERLOCUTEUR SET DOUBLON_TRAITE=0 WHERE DOUBLON_TRAITE IS NULL;
ALTER TABLE TQ_POSTE ADD COCHER_PHS INT DEFAULT 0;
UPDATE TQ_POSTE SET COCHER_PHS=0 WHERE COCHER_PHS IS NULL;
COMMIT;

ALTER TABLE RESIDANTS ADD VIP INTEGER DEFAULT 0;
UPDATE RESIDANTS SET VIP=0 WHERE VIP IS NULL;
ALTER TABLE VISITES ADD VIP INTEGER DEFAULT 0;
UPDATE VISITES SET VIP=0 WHERE VIP IS NULL;
COMMIT;

CREATE TABLE GRPSITE(
   GRPSITEID    VARCHAR2(14),
   LIBELLE      VARCHAR2(50),
   DATECREATION DATE,
   DATEMAJ      DATE
);
COMMIT;

CREATE TABLE GRPSITE_SITE(
   GRPSITEID   VARCHAR2(14),
   SITEID      VARCHAR2(14)
);
COMMIT;


ALTER TABLE ROLE_AUTRES ADD GRPSITE INT DEFAULT 0;
UPDATE ROLE_AUTRES SET GRPSITE=0 WHERE GRPSITE IS NULL;
ALTER TABLE TQ_COMMUNE ADD VISITE_SITERESID INT DEFAULT 0;
UPDATE TQ_COMMUNE SET VISITE_SITERESID=0 WHERE VISITE_SITERESID IS NULL;
COMMIT;

ALTER TABLE PARKING ADD CAPACITE INT;
UPDATE PARKING SET CAPACITE=0 WHERE CAPACITE IS NULL;
COMMIT;
EXIT;

