ALTER TABLE PROFILESMV MODIFY LIBELLE VARCHAR2(200);
COMMIT;

ALTER TABLE ZCL01_BA MODIFY NUMBDG VARCHAR2(200);
COMMIT;

ALTER TABLE ZCL01_VISITE MODIFY BADGE VARCHAR2(200);
COMMIT;

ALTER TABLE VISITES MODIFY NUMEROBADGE VARCHAR2(200);
COMMIT;

EXIT;
