ALTER TABLE EVENEMENT ADD PRIMARY KEY (EVENEMENTID);
COMMIT;
ALTER TABLE GRPEVENEMENT ADD PRIMARY KEY (GRPEVENEMENTID);
COMMIT;
ALTER TABLE LIEU ADD PRIMARY KEY (LIEUID);
COMMIT;
ALTER TABLE JOUR ADD PRIMARY KEY (JOURID);
COMMIT;

INSERT INTO GRPEVENEMENT (GRPEVENEMENTID, LIBELLE, DATECREATION, DATEMAJ) VALUES (-1, 'SYSTEME', SYSDATE, SYSDATE);
COMMIT;
UPDATE EVENEMENT SET GRPEVENEMENTID=-1 WHERE GRPEVENEMENTID='' OR GRPEVENEMENTID IS NULL;
COMMIT;

CREATE TABLE OTACHE (
OTACHEID	INTEGER PRIMARY KEY,
TYPEJOUR	VARCHAR2(20),
HEUREEXECUTION	DATE,
ACTION	VARCHAR2(20),
HEUREDEBUT	DATE,
HEUREFIN	DATE,
NBJOURMOINS	INTEGER DEFAULT 0,
MODEA	INTEGER DEFAULT 0,
ACTIF	INTEGER DEFAULT 1,
PROCHAINEEXECUTION DATE,
DERNIEREEXECUTION DATE,
DERNIERRESULTAT	INTEGER DEFAULT 0,
SITEID	VARCHAR2(20),
GROUPEDESTID	INTEGER,
DATECREATION DATE NOT NULL,
DATEMAJ DATE
);
COMMIT;

INSERT INTO OTACHE (OTACHEID,TYPEJOUR,HEUREEXECUTION,ACTION,HEUREDEBUT,HEUREFIN,NBJOURMOINS,SITEID,GROUPEDESTID,DATECREATION) VALUES (1,'0:0',TO_DATE('30/12/1899 08:00','DD/MM/YYYY HH24:MI'),'MAINCOURANTE',TO_DATE('30/12/1899 07:00','DD/MM/YYYY HH24:MI'),TO_DATE('30/12/1899 07:00','DD/MM/YYYY HH24:MI'),-1,'VPARDEFAULT',1865,SYSDATE);
COMMIT;

ALTER TABLE OFICHIER ADD CONTENTTYPE VARCHAR2(50);
ALTER TABLE OFICHIER ADD DATASIZE INTEGER;
COMMIT;

EXIT;