CREATE TABLE TAG
(
TAGID	INT	PRIMARY KEY,
TAG	VARCHAR2(35),
DESCRIPTION	VARCHAR2(100),
TYPE_TAG	INT,
SITEID	VARCHAR2(14),
DATECREATION	DATE	NOT NULL,
DATEMAJ	DATE	NOT NULL
);
COMMIT;

CREATE TABLE TAG_RONDE
(
TAGID	INT	NOT NULL,
RONDEID	INT	NOT NULL,
ORDRE	INT
);
COMMIT;


CREATE TABLE ZCL30_TAG_TMP
(
ZCL30_TAG_TMPID NUMBER(*, 0) NOT NULL,
BASE VARCHAR2(30),
PORTATIF VARCHAR2(30),
TAG VARCHAR2(30),
DATEHEURE DATE,
ORONDEID INT,
CONSTRAINT PK_ZCL30_TAG_TMP PRIMARY KEY (ZCL30_TAG_TMPID)
);

CREATE SEQUENCE SEQ_ZCL30_TAG_TMP
	START WITH 1
	INCREMENT BY 1
	NOMAXVALUE;

CREATE TABLE ZCL30_EVT
(
ZCL30_EVTID NUMBER(*, 0) NOT NULL,
BASE VARCHAR2(30),
PORTATIF VARCHAR2(30),
CODE_EVT VARCHAR2(30),
DATEHEURE DATE,
CONSTRAINT PK_ZCL30_EVT PRIMARY KEY (ZCL30_EVTID)
);

CREATE SEQUENCE SEQ_ZCL30_EVT
	START WITH 1
	INCREMENT BY 1
	NOMAXVALUE;

COMMIT;
EXIT;