
CREATE TABLE PARAMETRAGE (
	LIBELLE VARCHAR2(50),
	VALEUR VARCHAR2(4000),
	SITEID VARCHAR2(14),
	DATECREATION DATE NOT NULL,
	DATEMAJ DATE NOT NULL,
	DATESYNCHRO DATE,
	CONSTRAINT PARAMETRAGE_PK PRIMARY KEY (LIBELLE,SITEID)
);
COMMIT;

CREATE TABLE STATUTCOLIS (
	ID_STATUTCOLIS INTEGER PRIMARY KEY,
	LIBELLE VARCHAR2(35),
	COLOR INTEGER,
	DATECREATION DATE NOT NULL,
	DATEMAJ DATE NOT NULL,
	DATESYNCHRO DATE
);
COMMIT;

CREATE TABLE EVENEMENTCOLIS (
	ID_EVENEMENTCOLIS INTEGER PRIMARY KEY,
	COLISID VARCHAR2(14),
	LIBELLE VARCHAR2(200),
	DATEHEURE DATE,
	USERID VARCHAR2(14),
	DATECREATION DATE NOT NULL,
	DATEMAJ DATE NOT NULL,
	DATESYNCHRO DATE
);
COMMIT;

ALTER TABLE COLISRECU ADD ID_STATUTCOLIS INTEGER;
COMMIT;
ALTER TABLE COLISEMIS ADD ID_STATUTCOLIS INTEGER;
COMMIT;

ALTER TABLE COLISRECU ADD TRACKING VARCHAR2(500);
COMMIT;
ALTER TABLE COLISEMIS ADD TRACKING VARCHAR2(500);
COMMIT;

ALTER TABLE COLISRECU DROP COLUMN TICKET;
ALTER TABLE COLISRECU ADD TICKET VARCHAR2(50);
COMMIT;
ALTER TABLE COLISEMIS DROP COLUMN TICKET;
ALTER TABLE COLISEMIS ADD TICKET VARCHAR2(50);
COMMIT;

ALTER TABLE COLISRECU ADD OFICHIERID INTEGER;
COMMIT;
ALTER TABLE COLISEMIS ADD OFICHIERID INTEGER;
COMMIT;

ALTER TABLE COLISEMIS ADD LIEU VARCHAR2(50);
COMMIT;

ALTER TABLE COLISRECU MODIFY LIEU VARCHAR2(50);
COMMIT;

ALTER TABLE INTERLOCUTEUR ADD OFICHIERID INTEGER;
COMMIT;

DELETE FROM STATUTCOLIS;
INSERT INTO STATUTCOLIS (ID_STATUTCOLIS, LIBELLE, COLOR, DATECREATION, DATEMAJ) VALUES (-1, 'Enregistré', 65535, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO STATUTCOLIS (ID_STATUTCOLIS, LIBELLE, COLOR, DATECREATION, DATEMAJ) VALUES (-2, 'En attente', 42495, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO STATUTCOLIS (ID_STATUTCOLIS, LIBELLE, COLOR, DATECREATION, DATEMAJ) VALUES (-3, 'En stock', 16711680, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO STATUTCOLIS (ID_STATUTCOLIS, LIBELLE, COLOR, DATECREATION, DATEMAJ) VALUES (-4, 'En stock partiel', 16711680, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO STATUTCOLIS (ID_STATUTCOLIS, LIBELLE, COLOR, DATECREATION, DATEMAJ) VALUES (-5, 'Traité', 32768, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO STATUTCOLIS (ID_STATUTCOLIS, LIBELLE, COLOR, DATECREATION, DATEMAJ) VALUES (-6, 'Refusé', 255, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
COMMIT;

ALTER TABLE BADGES ADD STATUT INTEGER;
COMMIT;
UPDATE BADGES SET STATUT=1 WHERE STATUT IS NULL;
COMMIT;
ALTER TABLE BADGES ADD STATUTVISITEURID VARCHAR2(14);
COMMIT;
ALTER TABLE BADGES ADD SITEID VARCHAR2(14);
COMMIT;

ALTER TABLE MAIL MODIFY BODY VARCHAR2(4000);
COMMIT;

ALTER TABLE OJOURNAL MODIFY OBSERVATION VARCHAR2(4000);
COMMIT;
ALTER TABLE OJOURNAL_PERSMVT MODIFY OBSERVATION VARCHAR2(4000);
COMMIT;

ALTER TABLE BADGES_ELEMENTS ADD BACKGROUND_COLOR INTEGER;
COMMIT;
ALTER TABLE BADGES_ELEMENTS_TMP ADD BACKGROUND_COLOR INTEGER;
COMMIT;

CREATE TABLE LOCALISATION (
	LOCALISATIONID INTEGER PRIMARY KEY,
	LIBELLE VARCHAR2(100),
	SITEID VARCHAR2(14),
	SALLE_CAGE VARCHAR2(100),
	BAIE VARCHAR2(100),
	LOCALISATION_TYPE VARCHAR2(50),
	CODE VARCHAR2(100),
	EMPREINTE VARCHAR2(100),
	DATECREATION DATE NOT NULL,
	DATEMAJ DATE NOT NULL,
	DATESYNCHRO DATE
);
COMMIT;

CREATE TABLE CLEFS_LOCALISATION (
	CLEID VARCHAR2(14),
	LOCALISATIONID INTEGER
);
COMMIT;

CREATE TABLE PROFIL_CTRL_LOCALISATION (
	PROFIL_CTRLID INTEGER,
	LOCALISATIONID INTEGER
);
COMMIT;

CREATE TABLE VISITES_LOCALISATION (
	VISITEID VARCHAR2(14),
	LOCALISATIONID INTEGER
);
COMMIT;

CREATE TABLE SOCIETE_LOCALISATION (
	SOCIETEID VARCHAR2(14),
	LOCALISATIONID INTEGER
);
COMMIT;

CREATE TABLE PROFIL_CTRL (
	PROFIL_CTRLID INTEGER PRIMARY KEY,
	PROFIL_CTRL VARCHAR2(100),
	SITEID VARCHAR2(14),
	DATECREATION DATE NOT NULL,
	DATEMAJ DATE NOT NULL,
	DATESYNCHRO DATE
);
COMMIT;

ALTER TABLE VISITES ADD TICKET VARCHAR2(50);
COMMIT;
ALTER TABLE VISITES ADD RONDIER VARCHAR2(50);
COMMIT;
ALTER TABLE VISITES ADD RONDIERID INTEGER;
COMMIT;
ALTER TABLE VISITES ADD OFICHIERID INTEGER;
COMMIT;
ALTER TABLE VISITES ADD CLE VARCHAR2(500);
COMMIT;
ALTER TABLE VISITES ADD PROFIL_CTRL VARCHAR2(500);
COMMIT;

ALTER TABLE RONDIER ADD ETAT INTEGER;
COMMIT;

INSERT INTO EVENEMENT (EVENEMENTID,LIBELLE,RAPPORTID,CONSIGNEID,ISRAPPORT,DATEMAJ,DATECREATION,DATESYNCHRO) VALUES (-16,'VISITEUR NON PREVU',0,0,0,SYSDATE,SYSDATE,SYSDATE);
COMMIT;
INSERT INTO EVENEMENT (EVENEMENTID,LIBELLE,RAPPORTID,CONSIGNEID,ISRAPPORT,DATEMAJ,DATECREATION,DATESYNCHRO) VALUES (-17,'COLIS NON PREVU',0,0,0,SYSDATE,SYSDATE,SYSDATE);
COMMIT;
INSERT INTO EVENEMENT (EVENEMENTID,LIBELLE,RAPPORTID,CONSIGNEID,ISRAPPORT,DATEMAJ,DATECREATION,DATESYNCHRO) VALUES (-18,'OBJET PERDU',0,0,0,SYSDATE,SYSDATE,SYSDATE);
COMMIT;
EXIT;