CREATE TABLE CORRESPONDANCE ( 
  CORRESID       NUMBER        NOT NULL, 
  LIBSSRC        VARCHAR2 (240), 
  RANGSSRC       VARCHAR2 (20), 
  LIBDST         VARCHAR2 (80), 
  CFG_FICHIERID  NUMBER, 
  CORRES_RANG    NUMBER, 
  DATEMAJ        DATE, 
  DATECREATION   DATE, 
  PRIMARY KEY ( CORRESID ) ) ;

COMMIT;

CREATE TABLE TACHE_LOG(
	logid NUMBER NOT NULL,
	tacheid NUMBER ,
	numsession NUMBER ,
	userid varchar2(14),
	datecreation DATE,
	freeflag01 NUMBER,
	freeflag02 NUMBER,
	freeflag03 NUMBER,
	freeflag04 NUMBER,
	idligne varchar2(14),
	niveausecu NUMBER,
	commentaire varchar2(4000),
	PRIMARY KEY (logid) );
COMMIT;

ALTER TABLE TACHE ADD NUMSESSIONPROCHAINEEXECUTION INTEGER ;
COMMIT;
UPDATE TACHE SET NUMSESSIONPROCHAINEEXECUTION=0 WHERE NUMSESSIONPROCHAINEEXECUTION IS NULL ;
COMMIT;
ALTER TABLE CFG_FICHIER ADD STATUT INTEGER;
ALTER TABLE CFG_FICHIER MODIFY STATUT INTEGER DEFAULT(1);
UPDATE CFG_FICHIER SET STATUT=1 WHERE STATUT IS NULL ;
COMMIT;

CREATE TABLE OCONSIGNE_ODROIT (
  OCONSIGNEID INT NOT NULL,
  ODROITID INT NOT NULL
);
COMMIT;

CREATE TABLE OCONSIGNE_POSTE (
  OCONSIGNEID INT NOT NULL,
  POSTEID INT NOT NULL
);
COMMIT;

ALTER TABLE VISITES ADD PROFIL_CTRL_ID VARCHAR2(500);
COMMIT;

DROP TABLE ETATS;

CREATE TABLE ETATS
(
ETATID		INT	PRIMARY KEY,
LIBELLE		VARCHAR2(100 CHAR),
REQUETE_MSSQL		VARCHAR2(4000 CHAR),
REQUETE_ORACLE		VARCHAR2(4000 CHAR),
MODIFICATION	VARCHAR2(1000 CHAR),
MODIFICATION_OPERATEUR	VARCHAR2(1000 CHAR),
MODIFICATION_VALEUR	VARCHAR2(1000 CHAR),
DATECREATION	DATE NOT NULL,
DATEMAJ			DATE NOT NULL
);
COMMIT;
ALTER TABLE VISITES MODIFY PIECE VARCHAR2(35);
COMMIT;

CREATE TABLE VISITE_ACTION (
  VISITEACTIONID INTEGER NOT NULL,
  VISITEID VARCHAR2(14 CHAR),
  ACTION_NATURE VARCHAR2(35 CHAR),
  ACTEUR_NATURE VARCHAR2(35 CHAR),
  NOMACTEUR VARCHAR2(70 CHAR),
  ACTEURID VARCHAR2(14 CHAR),
  RES_ACTION VARCHAR2(4000 CHAR),
  NOM_CHAMP VARCHAR2(50 CHAR),
  RES_AVANT VARCHAR2(250 CHAR),
  RES_APRES VARCHAR2(250 CHAR),
  ACTION_DATE DATE NOT NULL,
  DATEMAJ DATE NOT NULL,
  DATECREATION DATE NOT NULL,
  DATESYNCHRO DATE,
CONSTRAINT PK_VISITEACTIONID PRIMARY KEY (VISITEACTIONID));

CREATE SEQUENCE SEQ_VISITE_ACTION;
COMMIT;

CREATE TABLE INTER_ACTION (
  INTERACTIONID INTEGER NOT NULL,
  INTERLOCUTEURID VARCHAR2(14 CHAR),
  ACTION_NATURE VARCHAR2(35 CHAR),
  ACTEUR_NATURE VARCHAR2(35 CHAR),
  NOMACTEUR VARCHAR2(70 CHAR),
  ACTEURID VARCHAR2(14 CHAR),
  RES_ACTION VARCHAR2(4000 CHAR),
  NOM_CHAMP VARCHAR2(50 CHAR),
  RES_AVANT VARCHAR2(250 CHAR),
  RES_APRES VARCHAR2(250 CHAR),
  ACTION_DATE DATE NOT NULL,
  DATEMAJ DATE NOT NULL,
  DATECREATION DATE NOT NULL,
  DATESYNCHRO DATE,
CONSTRAINT PK_INTERACTIONID PRIMARY KEY (INTERACTIONID));

CREATE SEQUENCE SEQ_INTER_ACTION;
COMMIT;

CREATE TABLE SOCIETE_ACTION (
  SOCACTIONID INTEGER NOT NULL,
  SOCIETEID VARCHAR2(14 CHAR),
  ACTION_NATURE VARCHAR2(35 CHAR),
  ACTEUR_NATURE VARCHAR2(35 CHAR),
  NOMACTEUR VARCHAR2(70 CHAR),
  ACTEURID VARCHAR2(14 CHAR),
  RES_ACTION VARCHAR2(4000 CHAR),
  NOM_CHAMP VARCHAR2(50 CHAR),
  RES_AVANT VARCHAR2(250 CHAR),
  RES_APRES VARCHAR2(250 CHAR),
  ACTION_DATE DATE NOT NULL,
  DATEMAJ DATE NOT NULL,
  DATECREATION DATE NOT NULL,
  DATESYNCHRO DATE,
CONSTRAINT PK_SOCACTIONID PRIMARY KEY (SOCACTIONID));

CREATE SEQUENCE SEQ_SOCIETE_ACTION;
COMMIT;



UPDATE XANNEXE SET ETAT=-2 WHERE ETAT IS NULL AND XANNEXE_TYPEID=-1 AND ORIGINE='VISITES';
COMMIT;

DROP function getaction;
DROP PROCEDURE PS_REGLES_MCOMPENSATOIRES ;

COMMIT;

--DROP TABLE VISITE_REGLE;
COMMIT;
CREATE TABLE VISITE_REGLE(
	VISITEID VARCHAR2(14) ,
	REGLEID NUMBER,
	ARBITRAGE NUMBER,
	ACTIONBLOQUANTE NUMBER,
	RANGREGLE NUMBER,
	MES_RESI VARCHAR2(100),
	MES_VALI VARCHAR2(100),
	MES_ACC VARCHAR2(100),
	DATEMAJ DATE NOT NULL,
	DATECREATION DATE NOT NULL,
	DATESYNCHRO DATE,
	CONSTRAINT PK_VISREGID PRIMARY KEY (VISITEID,REGLEID)
);

COMMIT;

ALTER TABLE REGLES ADD PERIODE VARCHAR2(35);
ALTER TABLE REGLES ADD DUREE VARCHAR2(35);
ALTER TABLE REGLES ADD FLAG_TIC NUMBER DEFAULT(0);
COMMIT;
UPDATE REGLES SET FLAG_TIC=0 WHERE TYPEREGLE<>-1;
UPDATE REGLES SET FLAG_TIC=1 WHERE TYPEREGLE=-1 ;
COMMIT;

CREATE TABLE REGLE_ACTION (
 REGLEID NUMBER,
 ACTIONID NUMBER);
 COMMIT; 

 CREATE SEQUENCE SEQ_ZCL37_CTPUSER;
 
 CREATE SEQUENCE SEQ_ZCL37_CPTPWD;
COMMIT;
EXIT;
