ALTER TABLE USERS MODIFY GSACCESS DEFAULT (0);
COMMIT;

UPDATE USERS SET GSACCESS=0 WHERE GSACCESS IS NULL;
UPDATE USERS SET GSACCESS=1 WHERE THELOGIN='TAFFIN';
UPDATE USERS SET GSACCESS=1 WHERE THELOGIN='ADM';
COMMIT;

UPDATE USERS SET ENABLED=1 WHERE ENABLED IS NULL;
COMMIT;


ALTER TABLE CFG_FICHIER ADD TYPECFG VARCHAR2(20);
COMMIT;
UPDATE CFG_FICHIER SET TYPECFG='IMPORT' WHERE TYPEID=-1;
COMMIT;
UPDATE CFG_FICHIER SET TYPECFG='ETAT' WHERE TYPEID=-2;
COMMIT;

ALTER TABLE CFG_FICHIER DROP COLUMN TYPEID;
COMMIT;

ALTER TABLE GRPSALLE ADD SITEID VARCHAR2(14);
UPDATE GRPSALLE SET SITEID='ALL';
COMMIT;

CREATE TABLE FORMULAIRE_MODELE (
  FORMULAIRE_MODELEID INT PRIMARY KEY,
  LIBELLE VARCHAR2(50),
  XML VARCHAR2(4000),
  OFICHIERID_WORD INT,
  OFICHIERID_EXCEL INT,
  SITEID VARCHAR2(14),
  TYPEVISITEID INT,
  DATECREATION DATE NOT NULL,
  DATEMAJ DATE NOT NULL,
  DATESYNCHRO DATE
);
COMMIT;

CREATE TABLE FORMULAIRE (
  FORMULAIREID INT PRIMARY KEY,
  FORMULAIRE_MODELEID INT NOT NULL,
  REFERENCE INT,
  VERSION INT,
  LIBELLE VARCHAR2(50),
  XML CLOB,
  AUTEUR VARCHAR2(100),
  DATECREATION DATE NOT NULL,
  DATEMAJ DATE NOT NULL,
  DATESYNCHRO DATE
);
COMMIT;

CREATE TABLE FORMULAIRE_VISITE (
  FORMULAIREID INT,
  VISITEID VARCHAR2(14)
);
COMMIT;

ALTER TABLE VISITES ADD SIGNATURE_ENTREE INT;
COMMIT;
ALTER TABLE VISITES ADD SIGNATURE_SORTIE INT;
COMMIT;
UPDATE VISITES SET SIGNATURE_ENTREE=OFICHIERID;
COMMIT;

ALTER TABLE INDCLE ADD SIGNATURE_ENTREE INT;
COMMIT;
ALTER TABLE INDCLE ADD SIGNATURE_SORTIE INT;
COMMIT;
UPDATE INDCLE SET SIGNATURE_ENTREE=OFICHIERID;
COMMIT;

ALTER TABLE MAIL ADD ICALENDAR VARCHAR2(4000);
COMMIT;

ALTER TABLE DROITSTELEM ADD SITE_RESIDANT INT;
ALTER TABLE DROITSTELEM ADD SITE_PREENREG INT;
COMMIT;
EXIT;