ALTER TABLE PROFIL_CTRL ADD PROFIL_CTRLID_EXT VARCHAR(50) ;
COMMIT;

UPDATE PROFIL_CTRL SET PROFIL_CTRLID_EXT=PROFIL_CTRLID;
COMMIT;

UPDATE PROFIL_CTRL SET PROFIL_CTRLID_EXT=PROFIL_CTRLID ;
COMMIT;

CREATE TABLE PROFIL_CTRL_LECTEUR (
	PROFIL_CTRL_LECTEURID INTEGER PRIMARY KEY,
	CTRLREADER VARCHAR2(50),
	CTRLREADERID VARCHAR2(20),
	PROFIL_CTRL VARCHAR2(100),
	PROFIL_CTRLID_EXT VARCHAR2(50),
	SITEID VARCHAR2(14),
	DATECREATION DATE NOT NULL,
	DATEMAJ DATE NOT NULL,
	DATESYNCHRO DATE
);
COMMIT;


CREATE TABLE ZCTRL_FIL_EAU (
	ID INT PRIMARY KEY NOT NULL,
	CTRLID VARCHAR2(30),
	CTRLDATE DATE,
	BADGE VARCHAR2(20),
	CTRLDESC VARCHAR2(50),
	CTRLREADER VARCHAR2(50),
	CTRLEVENT VARCHAR2(50),
	CTRLREADERID VARCHAR2(20),
	CTRLPROFIL VARCHAR2(100),
	INTERLOCUTEURID VARCHAR2(20),
	NOMPRENOM VARCHAR2(100),
	SOCIETE VARCHAR2(100),
	INTERLOCUTEURSTATUT VARCHAR2(50),
	RESIDANTSOCIETELIB VARCHAR2(100),
	RESIDANTSOCIETEID VARCHAR2(20),
	SITEID VARCHAR2(20),
	SITELIBELLE VARCHAR2(50),
	TICKET VARCHAR2(50),
	LOCALISATION VARCHAR2(4000),
	DATECREATION DATE NOT NULL,
	DATEMAJ  DATE,
	DATESYNCHRO  DATE
);
COMMIT;
EXIT;
