ALTER TABLE TACHE ADD OWNERID VARCHAR2(14) DEFAULT('VPARDEFAUT');
COMMIT;
ALTER TABLE TACHE ADD ROLEOWNER VARCHAR2(20) DEFAULT('USERS');
COMMIT;

UPDATE TACHE SET OWNERID='VPARDEFAUT', ROLEOWNER='USERS';
COMMIT;
ALTER TABLE TACHE_LOG ADD ROLEUSER VARCHAR2(20) DEFAULT ('USERS');
COMMIT;
UPDATE TACHE_LOG SET ROLEUSER='USERS', USERID='VPARDEFAUT' ;
COMMIT;

CREATE INDEX INDEX_ORIGINEVISITE ON VISITES (ORIGINEVISITE);
CREATE INDEX INDEX_BUREAUID ON VISITES (BUREAUID);

COMMIT;
EXIT;
