ALTER TABLE SITE ADD BDG_GENERATION INT;
ALTER TABLE SITE ADD BDG_DEBUT VARCHAR2(10);
ALTER TABLE SITE ADD BDG_MILIEU VARCHAR2(20);
ALTER TABLE SITE ADD BDG_FIN VARCHAR2(10);
ALTER TABLE SITE ADD BDG_MAX INT;
COMMIT;

UPDATE SITE SET BDG_GENERATION=0;
COMMIT;


ALTER TABLE SOCIETE ADD ESCORT INT ;
COMMIT;

ALTER TABLE OJOURNALLOG MODIFY OBSERVATION VARCHAR2(4000);
COMMIT;
EXIT;
