ALTER TABLE SITE ADD BDG_GENERATIONR INT;
COMMIT;
ALTER TABLE SITE ADD BDG_DEBUTR VARCHAR2(20);
COMMIT;
ALTER TABLE SITE ADD BDG_MILIEUR VARCHAR2(20);
COMMIT;
ALTER TABLE SITE ADD BDG_FINR VARCHAR2(20);
COMMIT;
ALTER TABLE SITE ADD BDG_MAXR INT;
COMMIT;

ALTER TABLE SITE ADD BDG_GENERATIONVEH INT;
COMMIT;
ALTER TABLE SITE ADD BDG_DEBUTVEH VARCHAR2(20);
COMMIT;
ALTER TABLE SITE ADD BDG_MILIEUVEH VARCHAR2(20);
COMMIT;
ALTER TABLE SITE ADD BDG_FINVEH VARCHAR2(20);
COMMIT;
ALTER TABLE SITE ADD BDG_MAXVEH INT;
COMMIT;

ALTER TABLE TQ_POSTE ADD GENERATION_BDG_MAX INT;
COMMIT;
ALTER TABLE TQ_POSTE ADD GENERATION_BDGR_MAX INT;
COMMIT;
ALTER TABLE TQ_POSTE ADD GENERATION_BDGVEH_MAX INT;
COMMIT;
EXIT;