ALTER TABLE ESVISITES_LOG ADD  TYPELECTEUR VARCHAR2(40);
COMMIT;
ALTER TABLE VISITES_RESIDANTS ADD SITEID VARCHAR2(14);
COMMIT;
ALTER TABLE VISITES_RESIDANTS ADD NOMPRENOM VARCHAR2(70);
COMMIT;

CREATE SEQUENCE SEQ_ESVISITES_LOG
	START WITH 1
	INCREMENT BY 1
	NOMAXVALUE;
COMMIT;	
	
CREATE SEQUENCE SEQ_VISITES
	START WITH 1
	INCREMENT BY 1
	NOMAXVALUE;
COMMIT;
	
CREATE SEQUENCE SEQ_VISITES_RESIDANTS
	START WITH 1
	INCREMENT BY 1
	NOMAXVALUE;
COMMIT;


ALTER TABLE REGLES ADD FREE5 NUMBER DEFAULT(0);
COMMIT;
ALTER TABLE REGLES ADD FREE6 NUMBER DEFAULT(0);
COMMIT;
ALTER TABLE REGLES ADD FREE7 VARCHAR2(35);

COMMIT;
EXIT;