ALTER TABLE LGRESERVATION ADD PAYANT INT DEFAULT 0;
UPDATE LGRESERVATION SET PAYANT=0;
COMMIT;

ALTER TABLE GRPUSER ADD PAYANT INT DEFAULT 0;
UPDATE GRPUSER SET PAYANT=0;
COMMIT;

ALTER TABLE BADGES_ELEMENTS_TMP ADD RANG INT;
COMMIT;
UPDATE BADGES_ELEMENTS_TMP SET RANG=0;
COMMIT;
ALTER TABLE BADGES_ELEMENTS ADD RANG INT;
COMMIT;
UPDATE BADGES_ELEMENTS SET RANG=0;
COMMIT;

ALTER TABLE BADGES_ELEMENTS_TMP ADD TRANSPARENT INT;
COMMIT;
UPDATE BADGES_ELEMENTS_TMP SET TRANSPARENT=0;
COMMIT;
ALTER TABLE BADGES_ELEMENTS ADD TRANSPARENT INT;
COMMIT;
UPDATE BADGES_ELEMENTS SET TRANSPARENT=0;
COMMIT;

CREATE TABLE FILTRE (
	LIBELLE VARCHAR2(50 CHAR),
	VALEUR VARCHAR2(4000 CHAR),
	SITEID VARCHAR2(14 CHAR),
	DATECREATION DATE NOT NULL,
	DATEMAJ DATE NOT NULL,
	DATESYNCHRO DATE,
	CONSTRAINT FILTRE_PK PRIMARY KEY (LIBELLE,SITEID)
);
COMMIT;

--ORACLE
CREATE TABLE RAPPEL (
   RAPPELID INT PRIMARY KEY,
   CODELGRESERVATION  VARCHAR2(14),
   TEMPS VARCHAR2(50),
   UNITE VARCHAR2(50),
   DATERAPPEL DATE,
   ETAT INT DEFAULT 0,
   DATECREATION DATE,
   DATEMAJ      DATE
);
COMMIT;

CREATE SEQUENCE SEQ_RAPPEL
	START WITH 1
	INCREMENT BY 1
	NOMAXVALUE;

COMMIT;