CREATE TABLE ZCL15_CPPA(
	IDCPPA varchar2(14) NULL,
	REGLEID varchar2(14) NULL,
	SITEID varchar2(14) NULL,
	SITE varchar2(35) NULL,
	SOCIETEID varchar2(14) NULL,
	SOCIETE varchar2(35) NULL,
	PAYSID varchar2(14) NULL,
	PAYS varchar2(35) NULL,
	TYPEVISITEID int NULL,
	TYPEVISITE varchar2(70) NULL,
	ETAT varchar2(3) NULL,
	DATESYNCHRO DATE NULL
);
COMMIT;

CREATE TABLE ZRR(
ID_ZRR int NOT NULL PRIMARY KEY,
CODE varchar2(25) NULL,
LIBELLE varchar2(255) NULL,
DEB_VALITE date NULL,
FIN_VALIDITE date NULL,
ACTIVE varchar2(1) NULL,
ZONE_PARTENAIRE varchar2(1) NULL,
CENTRE varchar2(3) NULL,
SITEID varchar2(14) NULL,
LOCAUX_SENSIBLES varchar2(1) NULL,
UCREA varchar2(8) NULL,
DCREA date NULL,
UDERMAJ varchar2(8) NULL,
DDERMAJ date NULL);
COMMIT;
 
 
 
 
ALTER TABLE MAIL MODIFY  TOADDRESS VARCHAR2(4000);
COMMIT;
 
INSERT INTO ZRR (ID_ZRR,CODE,LIBELLE,DEB_VALITE,FIN_VALIDITE,ACTIVE,ZONE_PARTENAIRE,SITEID,CENTRE,LOCAUX_SENSIBLES,DCREA,DDERMAJ) VALUES (0,'**********','********** Libelle','01/05/2014','01/03/2113','O','N','VPARDEFAUT','','N',SYSDATE,SYSDATE) ;

ALTER TABLE VISITES ADD ZRR_CODE VARCHAR2(25);
ALTER TABLE VISITES ADD ZRR_LIB VARCHAR2(255);
ALTER TABLE VISITES ADD ZRR_LS VARCHAR2(3);
COMMIT;
 
ALTER TABLE TYPEVISITE MODIFY TYPEVISITE VARCHAR2(70)

--SUPPRIMER LES CODES ACTIVITES  RESIDANTS, TRAVAIL


INSERT INTO TYPECONSIGNE (TYPECONSIGNEID,TYPECONSIGNE,DATECREATION,DATEMAJ) VALUES (-3,'DEMANDE LPE',SYSDATE,SYSDATE);
COMMIT;

ALTER TABLE CONSIGNE ADD SITEID VARCHAR2(14);
COMMIT;

ALTER TABLE CONSIGNE ADD EMETTEUR_NOM VARCHAR2(70);
COMMIT;

ALTER TABLE CONSIGNE ADD EMETTEUR_PROFIL VARCHAR2(50);
COMMIT;

ALTER TABLE CONSIGNE ADD TYPEOBJET INT;
COMMIT;


CREATE TABLE ZCL15_DEMANDE_LPE(
	ZCL15_DEMANDE_LPEID varchar2(14) NOT NULL PRIMARY KEY,
	CONSIGNE1_ID varchar2(14) NULL,
	CONSIGNE2_ID varchar2(14) NULL,
	INTERLOCUTEURID varchar2(14) NULL,
	EME_SITEID varchar2(14) NULL,
	REM_SITEID varchar2(14) NULL,
	REC_SITEID varchar2(14) NULL,
	LPE_SAISIE_DCS DATE NULL,
	LPE_SAISIE_CACS DATE NULL,
	LPE_REMISE DATE NULL,
	LPE_ENVOI DATE NULL,
	LPE_INTERDICTION int NULL,
	DATECREATION DATE NULL,
	DATEMAJ DATE NULL
 );
 
 COMMIT;
 
ALTER TABLE DROITSTELEM ADD VISITEUR VARCHAR2(500);
COMMIT;