ALTER TABLE VISITES ADD FUSION INT DEFAULT '0';
COMMIT;

UPDATE VISITES SET FUSION=0;
COMMIT;


CREATE TABLE TEMPO_IMPRESID (
RESIDANTID VARCHAR2(14),
SITEID VARCHAR2(50)
);
COMMIT;

ALTER TABLE GRPSITE ADD DUPLIQUE INT DEFAULT '0';
COMMIT;

UPDATE GRPSITE SET DUPLIQUE=0;
COMMIT;