CREATE TABLE GRPUSER_TYPEDOCUMENT
( GRPUSERID VARCHAR2(14) NOT NULL,
  TYPEDOCUMENTID NUMBER NOT NULL,
  CONSTRAINT PK_GRPUSER_TYPDOC PRIMARY KEY (GRPUSERID, TYPEDOCUMENTID));
 COMMIT;
 
CREATE TABLE OBJVISITE
( OBJVISITEID NUMBER NOT NULL PRIMARY KEY,
  LIBELLE VARCHAR(100),
  DATECREATION DATE,
  DATEMAJ DATE,
  DATESYNCHRO DATE);
  
 INSERT INTO OBJVISITE (OBJVISITEID,LIBELLE,DATEMAJ,DATECREATION) VALUES (0,'**********',SYSDATE,SYSDATE);

 ALTER TABLE TYPEDOCUMENT ADD ISMULTISITE  NUMBER DEFAULT 1 ;
 
 COMMIT;
 
  ALTER TABLE XANNEXE ADD SITEID VARCHAR2(14) NULL;
 
 COMMIT;

CREATE INDEX XANNEXE_ORIGINEID ON XANNEXE (XANNEXEID,ORIGINEID);
CREATE INDEX X_SITEID ON XANNEXE (SITEID);
CREATE INDEX X_ORIGINEID ON XANNEXE (ORIGINEID);
CREATE INDEX X_INFORMATION_TYPEID ON XANNEXE (INFORMATION_TYPEID);
CREATE INDEX X_ORIGINEID_ORIGINE ON XANNEXE (ORIGINEID,ORIGINE);


ALTER TABLE DROITSTELEM ADD TIMEOUT INT;
COMMIT;

ALTER TABLE PROFIL_CTRL ADD CODE_CLASSE NUMBER(10, 0);
COMMIT;
ALTER TABLE PROFIL_CTRL ADD ASCENSEUR VARCHAR2(50 CHAR);
COMMIT;

ALTER TABLE VISITES ADD MESSAGEVALIDEUR VARCHAR2(1000 CHAR);
COMMIT;
ALTER TABLE VISITES ADD ACCOMPAGNATEURID VARCHAR2(14 CHAR);
COMMIT;

ALTER TABLE IMPORT_ROI ADD THELOGIN VARCHAR2(50 CHAR);
COMMIT;