CREATE TABLE GRPVALIDEUR (
  GRPVALIDEURID INT NOT NULL,
  GRPVALIDEURN VARCHAR2(100),
  RANGVALIDEUR INTEGER DEFAULT (0),
  AVIS INTEGER DEFAULT (0),
  DATECREATION DATE NOT NULL,
  DATEMAJ DATE NOT NULL,
  DATESYNCHRO DATE,
CONSTRAINT PK_GRPVALIDEURID PRIMARY KEY (GRPVALIDEURID));
COMMIT;

INSERT INTO GRPVALIDEUR (GRPVALIDEURID,GRPVALIDEURN,RANGVALIDEUR,DATECREATION,DATEMAJ) VALUES ('-1','GRPVALIDEUR1',1,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
COMMIT;
INSERT INTO GRPVALIDEUR (GRPVALIDEURID,GRPVALIDEURN,RANGVALIDEUR,DATECREATION,DATEMAJ) VALUES ('-2','GRPVALIDEUR2',2,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
COMMIT;
INSERT INTO GRPVALIDEUR (GRPVALIDEURID,GRPVALIDEURN,RANGVALIDEUR,DATECREATION,DATEMAJ) VALUES ('-3','GRPVALIDEUR3',3,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
COMMIT;
INSERT INTO GRPVALIDEUR (GRPVALIDEURID,GRPVALIDEURN,RANGVALIDEUR,DATECREATION,DATEMAJ) VALUES ('-4','GRPVALIDEUR4',4,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
COMMIT;


ALTER TABLE DROITSTELEM ADD GRPVALIDEURID INT NULL;
COMMIT;

ALTER TABLE VISITES ADD GRPVALIDEUR2 VARCHAR2(50) NULL;
COMMIT;
ALTER TABLE VISITES ADD GRPVALIDEUR3 VARCHAR2(50) NULL;
COMMIT;
ALTER TABLE VISITES ADD GRPVALIDEUR4 VARCHAR2(50) NULL;
COMMIT;
ALTER TABLE VISITES ADD RANKLASTVAL INT NULL;
COMMIT;

CREATE TABLE REGLE_GRPVALIDEUR (
  REGLEID INT NOT NULL,
  GRPVALIDEURID INT NOT NULL,
CONSTRAINT PK_REGLE_GRPVALIDEUR PRIMARY KEY (REGLEID,GRPVALIDEURID));
COMMIT;

CREATE TABLE LOCALISATION_USER (
  LOCALISATIONID INT NOT NULL,
  USERID VARCHAR2(14) NOT NULL,
CONSTRAINT PK_LOCALISATION_USER PRIMARY KEY (USERID,LOCALISATIONID));
COMMIT ;



 CREATE TABLE POSTE_TYPEVISITE (
  NOM_POSTE VARCHAR2(50),
  TYPEVISITEID INT);
COMMIT;

ALTER TABLE REGLES ADD BYPASS INT DEFAULT(0);
COMMIT;
UPDATE REGLES SET BYPASS=0;

ALTER TABLE REGLES ADD CATEGORIE VARCHAR2(30) NULL;
COMMIT;

ALTER TABLE REGLES ADD GRPVALIDEURID INT NULL;
COMMIT;

--FAIRE UPDATE
ALTER TABLE VISITE_REGLE ADD CATEGORIE VARCHAR2(30);
COMMIT;

ALTER TABLE VISITES ADD CATEGORIE VARCHAR2(30);
COMMIT;

ALTER TABLE INTERLOCUTEUR ADD DEPFRID INT NULL ;
COMMIT;

ALTER TABLE VISITES ADD IDEPFR VARCHAR2(100);
COMMIT;

UPDATE TYPEDOCUMENT SET ISMULTISITE='1';
COMMIT;

