CREATE VIEW [dbo].[V_LISTE_GRPSITE] AS (
SELECT GS.GRPSITEID,GS.LIBELLE AS GROUPE,S.SITEID,S.LIBELLE AS SITE,'GROUPE' AS GRP FROM GRPSITE GS, GRPSITE_SITE GSS, SITE S WHERE GSS.GRPSITEID=GS.GRPSITEID AND GSS.SITEID=S.SITEID
UNION
SELECT SITEID AS GRPSITEID,LIBELLE AS GROUPE, SITEID, LIBELLE AS SITE, 'SITE' AS GRP FROM SITE
)