CREATE VIEW [dbo].[VISITES_SORTIE_JOUR] (
	VISITEID, NUMEROBADGE, FINVISITE, SITEID) AS
	(
		SELECT V.VISITEID, V.NUMEROBADGE, V.FINVISITE, V.SITEID
		FROM VISITES V, SITE S, TYPEVISITE T
		WHERE S.SITEID=V.SITEID
		AND T.TYPEVISITEID=V.TYPEVISITEID
		AND V.STATUTID IN (1,8,33,34)
		AND S.TLMQ_SORTIE_JOUR=1
		AND T.TYPESORTIE=1
	)