CREATE VIEW [dbo].[VISITES_EN_FIN] (
	VISITEID, NUMEROBADGE, FINVISITE, SITEID) AS
	(
		SELECT VISITEID, NUMEROBADGE, FINVISITE, SITEID
		FROM VISITES
		WHERE STATUTID IN (1,8,33,34)
		AND FINVISITE<=GETDATE()
	)