--Réservations
SELECT * FROM LGRESERVATION WHERE CODERESERVATION NOT IN (SELECT CODERESERVATION FROM RESERVATION)

SELECT * FROM RESERVATION WHERE CODERESERVATION NOT IN (SELECT CODERESERVATION FROM LGRESERVATION)

SELECT * FROM RESERVATION WHERE CODEANIMATEUR NOT IN (SELECT RESIDANTID FROM RESIDANTS)

SELECT * FROM RESERVATION WHERE INTERLOCUTEURID NOT IN (SELECT RESIDANTID FROM RESIDANTS)
--UPDATE RESERVATION SET INTERLOCUTEURID=CODEANIMATEUR WHERE CODERESERVATION IN (SELECT CODERESERVATION FROM RESERVATION WHERE INTERLOCUTEURID NOT IN (SELECT RESIDANTID FROM RESIDANTS))

SELECT * FROM RESERVATION WHERE CODESTATUT NOT IN (SELECT CODESTATUT FROM STATUTRESERVATION)

SELECT * FROM RESERVATION WHERE CODETYPERESERVATION NOT IN (SELECT CODETYPERESERVATION FROM TYPERESERVATION)

SELECT * FROM LGRESERVATION LG WHERE CODEAMMENAGEMENT NOT IN (SELECT CODEAMENAGEMENT FROM AMENAGSALLE WHERE CODESALLE=LG.CODESALLE)


--Résidants
SELECT * FROM USERS WHERE PROFIL_ID_ORGA NOT IN (SELECT RESIDANTID FROM RESIDANTS) AND PROFIL_ID_ORGA IS NOT NULL AND PROFIL_ID_ORGA<>''

SELECT * FROM USERS WHERE PROFIL_ID_INTER NOT IN (SELECT RESIDANTID FROM RESIDANTS) AND PROFIL_ID_INTER IS NOT NULL AND PROFIL_ID_INTER<>''

SELECT * FROM USERS WHERE EXTERNALID NOT IN (SELECT RESIDANTID FROM RESIDANTS) AND EXTERNALID IS NOT NULL AND EXTERNALID<>''