CREATE FUNCTION [dbo].[F_DEDUP_COMMPREFIXELENGTH]
(
    @MYSTRDN NVARCHAR(4000),
    @MYSTRUP NVARCHAR(4000)

)
RETURNS INTEGER
AS
BEGIN
	DECLARE @locnbr INTEGER
	DECLARE @distancemin INT
	DECLARE @i INT;
	DECLARE @strindex NVARCHAR(4000);
	DECLARE @STRUP NVARCHAR(4000);
	DECLARE @STRDN NVARCHAR(4000);
	DECLARE @STRDNC NVARCHAR(1);
	DECLARE @STRUPC NVARCHAR(1);
	DECLARE @maxlength int;
	SET @locnbr=0
	SET @STRDN=REPLACE(@MYSTRDN,' ','')
	SET @STRUP=REPLACE(@MYSTRUP,' ','')
	SET @i= 0;
	SET @maxlength = (SELECT MIN(A) from (SELECT ISNULL(LEN(@STRUP),0) AS A UNION SELECT ISNULL (LEN(@STRDN),0) AS A UNION SELECT 4 AS A) B)

	WHILE (@i < @maxlength) BEGIN
		if (SUBSTRING(@STRUP,@i+1,1)=SUBSTRING(@STRDN,@i+1,1)) BEGIN
			SET @locnbr=@locnbr+1
			END  ELSE BEGIN
			BREAK
			END
		SET @i=@i+1
	END
	RETURN @locnbr
END