CREATE FUNCTION [dbo].[F_GET_STATUTVISITE](@STATUTID INT) RETURNS NVARCHAR(50)
AS
BEGIN
	DECLARE @RET NVARCHAR(40)
	SET @RET = (SELECT STATUTVISITE FROM STATUTVISITE WHERE STATUTID=@STATUTID )
	RETURN @RET
END