CREATE FUNCTION [dbo].[F_GET_EQUIPEMENT](@CODESALLE VARCHAR(14)) RETURNS VARCHAR(8000)
AS
BEGIN
DECLARE @EQUIPEMENTFIXE VARCHAR(8000)
SELECT @EQUIPEMENTFIXE = COALESCE(@EQUIPEMENTFIXE + ', ', '') +
	ISNULL(EQ.LIBELLE, '')
	FROM SALLE SAL
	LEFT OUTER JOIN LGSALLE EQS ON EQS.CODESALLE=SAL.CODESALLE
	LEFT OUTER JOIN EQUIPEMENTFIXE EQ ON EQS.CODEEQUIPEMENTFIXE=EQ.CODEEQUIPEMENTFIXE WHERE SAL.CODESALLE=@CODESALLE

	RETURN (SELECT SUBSTRING(@EQUIPEMENTFIXE,1,8000))
END