CREATE FUNCTION [dbo].[F_GET_STATUTPERSONNE](@STATUT VARCHAR,@RESIDANTID VARCHAR,@INTERLOCUTEURID VARCHAR) RETURNS NVARCHAR(1)
AS
BEGIN
	DECLARE @RET NVARCHAR(40)
	IF @RESIDANTID<>'' AND @RESIDANTID IS NOT NULL BEGIN
	 SET @RET = (SELECT N.LIBELLE FROM  RESIDANTS R, LGPARTICIPANT LG, NATURE N WHERE LG.RESIDANTID=R.RESIDANTID AND R.NATUREID=N.NATUREID AND R.RESIDANTID=@RESIDANTID)
	END ELSE BEGIN
	 SET @RET = (SELECT N.LIBELLE FROM  INTERLOCUTEUR I, LGPARTICIPANT LG,  NATURE N WHERE LG.RESIDANTID=I.INTERLOCUTEURID AND I.NATUREID=N.NATUREID AND I.INTERLOCUTEURID=@INTERLOCUTEURID)
	END
	RETURN @RET
END