CREATE FUNCTION [dbo].[F_GET_SALLEFUS](@CODESALLE NVARCHAR(14)) RETURNS NVARCHAR(8000)
AS
BEGIN
DECLARE @SALLEFUS NVARCHAR(8000)
SELECT @SALLEFUS = COALESCE(@SALLEFUS + ', ', '') +
	ISNULL(S2.LIBELLE, '')
	FROM SALLE SAL
	LEFT OUTER JOIN SALLEFUS FUS ON FUS.DECODESALLE=SAL.CODESALLE
	LEFT OUTER JOIN SALLEFUS_COMP FUSCOMP ON FUS.CODESALLEFUS=FUSCOMP.CODESALLEFUS
	LEFT OUTER JOIN SALLE S2 ON FUSCOMP.CODESALLE =S2.CODESALLE WHERE SAL.CODESALLE=@CODESALLE
	RETURN (SELECT SUBSTRING(@SALLEFUS,1,8000))
END