CREATE FUNCTION [dbo].[F_ISMISSION_READY](@TOLERANCE DATETIME,@HEURE DATETIME,@ANTICIPE INT,@HEUREJOUR DATETIME) RETURNS VARCHAR(1)
AS
BEGIN
DECLARE @RET VARCHAR(1)
   IF DATEADD(mi,@ANTICIPE,@HEUREJOUR) >  CONVERT(DATETIME,@HEURE-@TOLERANCE,103) BEGIN
	SET @RET='1'
   END ELSE BEGIN
   SET @RET='0'
   END
   RETURN @RET
END