CREATE FUNCTION [dbo].[F_REGLE_LIMITE_DATE](@DATE1 DATETIME,@DATE2 DATETIME, @FLAG INTEGER) RETURNS DATETIME
AS
BEGIN
DECLARE @DATE_LIMIT DATETIME
	IF @FLAG=0 BEGIN
		IF @DATE1<=@DATE2 BEGIN
			SET @DATE_LIMIT=@DATE1
		END
		ELSE BEGIN
			SET @DATE_LIMIT=@DATE2
		END
	END
	ELSE
		IF @DATE1<=@DATE2 BEGIN
			SET @DATE_LIMIT=@DATE2
		END
		ELSE
			SET @DATE_LIMIT=@DATE1
	RETURN @DATE_LIMIT
END