CREATE FUNCTION [dbo].[GET_GRPVALIDEUR](@VISITEID VARCHAR(14)) RETURNS  VARCHAR(200)
AS
BEGIN
	DECLARE @TMP VARCHAR(4000)
	DECLARE @TMP2 VARCHAR(4000)
	SELECT @TMP=COALESCE(@TMP+',','')+CAST(ISNULL(GV.GRPVALIDEURID,'')AS VARCHAR(200)) FROM REGLE_GRPVALIDEUR GV , VISITE_REGLE VR
	WHERE  GV.REGLEID=VR.REGLEID AND VR.VISITEID=@VISITEID --AND GV.GRPVALIDEURID=@GRPVALIDEURID
	SET @TMP2=@TMP
	RETURN @TMP2
END