CREATE FUNCTION [dbo].[GET_CONSIGNE](@INTERLOCUTEURID NVARCHAR(14)) RETURNS  NVARCHAR(14)
AS
BEGIN
	DECLARE  @O_RESIDANTID NVARCHAR(14)
   	SET @O_RESIDANTID=(SELECT TOP 1 ISNULL(INTERLOCUTEURID,'') FROM CONSIGNE WHERE INTERLOCUTEURID=@INTERLOCUTEURID AND RESIDANTID='VISITEUR' OR RESIDANTID IS NULL ORDER BY DATEMAJ)
	RETURN  @O_RESIDANTID
END