CREATE  FUNCTION [dbo].[GET_STATUTVISITE](@MYACTION INT) RETURNS NVARCHAR(50)
AS
BEGIN
    DECLARE @LOCSTATUTVISITE NVARCHAR(50)
	SET @LOCSTATUTVISITE=''
    SET @LOCSTATUTVISITE= CASE
		WHEN @MYACTION=-2 THEN 'WEB INTERDIT'
		WHEN @MYACTION=-3 THEN 'WEB INCOMPLET'
		WHEN @MYACTION=-4 THEN 'WEB EN ATTENTE'
		WHEN @MYACTION=-5 THEN 'WEB ACCOMPAGNER'
		WHEN @MYACTION=-6 THEN 'WEB OK'
		ELSE 'WEB OK'
	END
	RETURN  @LOCSTATUTVISITE;
END