CREATE FUNCTION [dbo].[GET_LOCALISATIONBYVISITE](@MYVISITEID  NVARCHAR(14)) RETURNS NVARCHAR(4000)
AS

BEGIN
	DECLARE @TMP NVARCHAR(4000)
	DECLARE @TMP2 NVARCHAR(4000)

	SELECT @TMP=COALESCE(@TMP+',','')+ISNULL(L.LIBELLE,'') FROM LOCALISATION L,VISITES_LOCALISATION VL WHERE VL.LOCALISATIONID=L.LOCALISATIONID AND VL.VISITEID=@MYVISITEID
	SET @TMP2=@TMP
	RETURN @TMP2
END