CREATE FUNCTION [dbo].[GET_VISITE_TRAVAIL](@VISITEID NVARCHAR(14)) RETURNS NVARCHAR(1)
AS
BEGIN
	DECLARE @WK NVARCHAR(1)
    SET @WK=(SELECT ISNULL(NATUREVISITE,'-2') FROM VISITES WHERE VISITEID=@VISITEID)
	RETURN @WK
END