CREATE FUNCTION [dbo].[GET_CONSIGNE](@INTERLOCUTEURID VARCHAR(14)) RETURNS  VARCHAR(14)
AS
BEGIN
	DECLARE  @O_RESIDANTID VARCHAR(14)
   	SET @O_RESIDANTID=(SELECT TOP 1 ISNULL(INTERLOCUTEURID,'') FROM CONSIGNE WHERE INTERLOCUTEURID=@INTERLOCUTEURID AND RESIDANTID='VISITEUR' OR RESIDANTID IS NULL ORDER BY DATEMAJ)
	RETURN  @O_RESIDANTID
END