CREATE FUNCTION [dbo].[GET_VAL_VIS_LOC](@VISITEID NVARCHAR(14),@USERID NVARCHAR(14)) RETURNS  NVARCHAR(1)
AS
BEGIN
	DECLARE @TMP NVARCHAR(1)
	SET @TMP='1'
	IF EXISTS (SELECT LOCALISATIONID FROM LOCALISATION_USER WHERE USERID=@USERID) BEGIN
	SET @TMP=(SELECT CAST(COUNT(*) AS NVARCHAR(1)) FROM VISITES_LOCALISATION L, LOCALISATION_USER LU WHERE LU.LOCALISATIONID=L.LOCALISATIONID AND L.VISITEID=@VISITEID  AND LU.USERID=@USERID )
	END
	RETURN @TMP
END