CREATE FUNCTION [dbo].[GET_VAL_VIS_LOC](@VISITEID VARCHAR(14),@USERID VARCHAR(14)) RETURNS  VARCHAR(1)
AS
BEGIN
	DECLARE @TMP VARCHAR(1)
	SET @TMP='1'
	IF EXISTS (SELECT LOCALISATIONID FROM LOCALISATION_USER WHERE USERID=@USERID) BEGIN
	SET @TMP=(SELECT CAST(COUNT(*) AS VARCHAR(1)) FROM VISITES_LOCALISATION L, LOCALISATION_USER LU WHERE LU.LOCALISATIONID=L.LOCALISATIONID AND L.VISITEID=@VISITEID  AND LU.USERID=@USERID )
	END
	RETURN @TMP
END