CREATE FUNCTION [dbo].[GET_WEEK_END_DATE](@MYDATE DATETIME) RETURNS  DATETIME
AS

BEGIN
 DECLARE @REPORT_DATE DATETIME
SELECT @REPORT_DATE = CONVERT(DATETIME,CONVERT(VARCHAR(10),@MYDATE,103),103)

DECLARE @WEEK_END_DATE DATETIME
--GET THE WEEK END DATE
SELECT  @WEEK_END_DATE = @REPORT_DATE + (7 - DATEPART(DW,  @REPORT_DATE))
RETURN CONVERT(DATETIME, @WEEK_END_DATE,103)
END