CREATE FUNCTION [dbo].[GET_GRPVALIDEUR](@VISITEID NVARCHAR(14)) RETURNS  NVARCHAR(200)
AS
BEGIN
	DECLARE @TMP NVARCHAR(4000)
	DECLARE @TMP2 NVARCHAR(4000)
	SELECT @TMP=COALESCE(@TMP+',','')+CAST(ISNULL(GV.GRPVALIDEURID,'')AS NVARCHAR(200)) FROM REGLE_GRPVALIDEUR GV , VISITE_REGLE VR
	WHERE  GV.REGLEID=VR.REGLEID AND VR.VISITEID=@VISITEID --AND GV.GRPVALIDEURID=@GRPVALIDEURID
	SET @TMP2=@TMP
	RETURN @TMP2
END