CREATE FUNCTION [dbo].[isVehiculeInterdit](@vehiculeid NVARCHAR(14),@dt DATETIME) RETURNS varchar AS
 BEGIN
    DECLARE @IdVeh NVARCHAR(14)
    DECLARE @Retour NVARCHAR(50)
    set @IdVeh ='0'
	Set @IdVeh=(SELECT VEHICULEID FROM RESIDANTS R, VEHICULE V WHERE  R.RESIDANTID=V.RESIDANTID  AND (CONVERT(DATETIME,@dt,103) <CONVERT(DATETIME,DATELIMITE,103)) AND V.VEHICULEID=@vehiculeid)
	IF @IdVeh<>'' and @IdVeh is not null BEGIN
		Set @Retour ='0'
	END
	ELSE set @Retour ='1'
    RETURN @Retour
 END