CREATE FUNCTION [dbo].[IsVisiteurRestreint]
(
    @IntelocuteurID NVARCHAR(14)
)
RETURNS NVARCHAR(64)
AS
BEGIN
    DECLARE @NatureID NVARCHAR(14)
    DECLARE @PaysID NVARCHAR(14)
    DECLARE @SocieteID NVARCHAR(14)

    DECLARE @IdNature NVARCHAR(14)
    DECLARE @IdPays NVARCHAR(14)
    DECLARE @IdSociete NVARCHAR(14)
    DECLARE @Retour NVARCHAR(50)
    set @Retour ='0'
	IF NOT EXISTS(SELECT INTERLOCUTEURID FROM INTERLOCUTEUR WHERE INTERDIT='2' AND INTERLOCUTEURID=@IntelocuteurID) BEGIN
		Set @NatureID=(SELECT top 1 NATUREID FROM INTERLOCUTEUR WHERE INTERLOCUTEURID=@IntelocuteurID)
		Set @PaysID=(SELECT top 1 NATIONALITEID FROM INTERLOCUTEUR WHERE INTERLOCUTEURID=@IntelocuteurID)
		Set @SocieteID=(SELECT top 1 SOCIETEID FROM INTERLOCUTEUR WHERE INTERLOCUTEURID=@IntelocuteurID)
		IF  NOT EXISTS (SELECT TOP 1 NATUREID FROM NATURE WHERE INTERDIT='2' AND NATUREID=@NatureID) BEGIN
			IF  NOT EXISTS (SELECT TOP 1 PAYSID FROM PAYS WHERE INTERDIT='2' AND PAYSID=@PAYSID) BEGIN
				IF  NOT EXISTS (SELECT TOP 1 SOCIETEID FROM SOCIETE WHERE INTERDIT='2' AND SOCIETEID=@SOCIETEID) BEGIN
					set @Retour ='1'
 				END
				ELSE set @Retour ='-4'
			END
			ELSE set @Retour ='-3'
		END
		ELSE set @Retour ='-2'
	END
	ELSE set @Retour ='-1'

    RETURN @Retour
END