CREATE FUNCTION [dbo].[IsVisiteurInterdit]
(
    @IntelocuteurID NVARCHAR(14),
    @dt datetime

)
RETURNS NVARCHAR(64)
AS
BEGIN
    DECLARE @NatureID NVARCHAR(14)
    DECLARE @PaysID NVARCHAR(14)
    DECLARE @SocieteID NVARCHAR(14)
    DECLARE @IdInter NVARCHAR(14)
    DECLARE @IdNature NVARCHAR(14)
    DECLARE @IdPays NVARCHAR(14)
    DECLARE @IdSociete NVARCHAR(14)
    DECLARE @Retour NVARCHAR(50)

    set @Retour ='0'
	Set @IdInter=(SELECT INTERLOCUTEURID FROM INTERLOCUTEUR WHERE ((INTERDIT=0 AND (@dt BETWEEN DEBUTINTERDIT AND FININTERDIT)) OR INTERDIT='2') AND INTERLOCUTEURID=@IntelocuteurID)
	IF @IdInter<>'' BEGIN
		Set @NatureID=(SELECT top 1 NATUREID FROM INTERLOCUTEUR WHERE INTERLOCUTEURID=@IntelocuteurID)
		Set @PaysID=(SELECT top 1 NATIONALITEID FROM INTERLOCUTEUR WHERE INTERLOCUTEURID=@IntelocuteurID)
		Set @SocieteID=(SELECT top 1 SOCIETEID FROM INTERLOCUTEUR WHERE INTERLOCUTEURID=@IntelocuteurID)
		Set @IdNature=(SELECT NATUREID FROM NATURE WHERE ((INTERDIT=0 AND (@dt BETWEEN DEBUTINTERDIT AND FININTERDIT)) OR INTERDIT='2') AND NATUREID=@NatureID)
		IF  @IdNature <> '' BEGIN
			Set @PaysID=(SELECT PAYSID FROM PAYS WHERE ((INTERDIT=0 AND (@dt BETWEEN DEBUTINTERDIT AND FININTERDIT)) OR INTERDIT='2') AND PAYSID=@PAYSID)
			IF  @PaysID <> '' BEGIN
				Set @SocieteID=(SELECT SOCIETEID FROM SOCIETE WHERE ((INTERDIT=0 AND (@dt BETWEEN DEBUTINTERDIT AND FININTERDIT)) OR INTERDIT='2') AND SOCIETEID=@SOCIETEID)
				IF  @SocieteID <> ''
					set @Retour ='1'
 				ELSE set @Retour ='-4'
			END
			ELSE set @Retour ='-3'
		END
		ELSE set @Retour ='-2'
	END
	ELSE set @Retour ='-1'

    RETURN @Retour
END