CREATE PROCEDURE [dbo].[GETMEETING_UNE_SALLE_INNES]

	@SALLE NVARCHAR(30),
    @STARTDATE NVARCHAR(10),
	@STARTHOUR NVARCHAR(12),
    @ENDDATE NVARCHAR(10),
	@ENDHOUR NVARCHAR(12)

AS


BEGIN



	SELECT CONVERT(VARCHAR, DATEDEBUT, 120) DDEBUT, CONVERT(VARCHAR, DATEFIN, 120) DFIN,
	CONVERT(VARCHAR, HEUREDEBUT, 120) HDEBUT, CONVERT(VARCHAR, HEUREFIN, 120) HFIN, CODESALLE,
	LGRESERVATION.CODERESERVATION, RESERVATION.CODERESERVATION, CODELGRESERVATION,
	LIBELLESALLE, LIBELLE, COMMENTAIRE, NOSALLE
	FROM LGRESERVATION, RESERVATION

	WHERE LIBELLESALLE=@SALLE  AND RESERVATION.CODERESERVATION= LGRESERVATION.CODERESERVATION

	AND
	(
		((CONVERT(varchar, HEUREDEBUT, 108)< @ENDHOUR )		AND (CONVERT(varchar, HEUREFIN, 108)> @STARTHOUR ))
	OR	((CONVERT(varchar, HEUREDEBUT, 108)< @STARTHOUR )	AND (CONVERT(varchar, HEUREFIN, 108)> @ENDHOUR ))
	OR	((CONVERT(varchar, HEUREDEBUT, 108)< @ENDHOUR )		AND (CONVERT(varchar, HEUREFIN, 108)> @STARTHOUR ))
	OR	((CONVERT(varchar, HEUREDEBUT, 108)< @ENDHOUR )		AND (CONVERT(varchar, HEUREFIN, 108)> @ENDHOUR ))
	)

	AND (DATEDEBUT >= CONVERT(DATETIME, @STARTDATE+' 00:00:00', 120))
	AND (DATEFIN <= CONVERT(DATETIME, @ENDDATE+' 00:00:00', 120))

	ORDER BY DATEDEBUT DESC




END











/****** Objet :  StoredProcedure [dbo].[MODMEETING_INNES]    Date de génération du script : 06/16/2014 10:09:54 ******/
SET ANSI_NULLS ON