CREATE PROCEDURE [dbo].[IMPORT_PROFIL_CTRL]
	@ID NVARCHAR(30),
	@PROFIL_CTRL NVARCHAR(100),
	@SITEID NVARCHAR(50)
AS
	DECLARE @IID NVARCHAR(14)
	DECLARE @FLAG NVARCHAR(14)
	DECLARE @IDENTITY NVARCHAR(14)
BEGIN
	IF NOT EXISTS (SELECT PROFIL_CTRL FROM PROFIL_CTRL WHERE PROFIL_CTRLID_EXT=@ID AND SITEID=@SITEID) BEGIN
		INSERT INTO SEQ_IDENTITY(LIBELLE) VALUES ('OK')
		SET @IDENTITY = (SELECT @@IDENTITY AS ID)
		SET @FLAG = (SELECT SUBSTRING(VERSION, 1, 3) FROM VERSION_SFW)
		SET @IID = @FLAG + @IDENTITY

		INSERT INTO PROFIL_CTRL (PROFIL_CTRLID,PROFIL_CTRL,PROFIL_CTRLID_EXT,SITEID,DATECREATION,DATEMAJ)
		VALUES(@IID,@PROFIL_CTRL,@ID,@SITEID,CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
	END
	ELSE BEGIN
		UPDATE PROFIL_CTRL SET PROFIL_CTRL=@PROFIL_CTRL,Datemaj=CURRENT_TIMESTAMP WHERE PROFIL_CTRLID_EXT=@ID AND SITEID=@SITEID
	END
END