CREATE PROCEDURE [dbo].[IMPORT_FROM_CTRL]
	@ID NVARCHAR(30),
	@DATEHEURE NVARCHAR(35),
	@LECTEUR NVARCHAR(50),
	@LECTEURID NVARCHAR(20),
	@DESC NVARCHAR(50),
	@CTRLEVENT NVARCHAR(50),
	@CTRL_PROFIL NVARCHAR(100),
	@CTRL_SOCIETE NVARCHAR(50),
	@CTRL_NOM NVARCHAR(50),
	@CTRL_PRENOM NVARCHAR(50),
	@CARDCODE NVARCHAR(50),
	@EXINTERLOCUTEURID NVARCHAR(50),
	@SITEID NVARCHAR(50)
AS
	DECLARE @IID NVARCHAR(14)
	DECLARE @FLAG NVARCHAR(14)
	DECLARE @IDENTITY NVARCHAR(14)
	DECLARE @NOMPRENOM NVARCHAR(100)
	DECLARE @SOCIETE NVARCHAR(100)
	DECLARE @INTERSTATUT NVARCHAR(100)
	DECLARE @BADGE NVARCHAR(100)
	DECLARE @RESIDANTSOCIETELIB NVARCHAR(100)
	DECLARE @RESIDANTSOCIETEID NVARCHAR(100)
	DECLARE @SITELIBELLE NVARCHAR(100)
	DECLARE @VISITEID NVARCHAR(100)
	DECLARE @TICKET NVARCHAR(50)
	DECLARE @LOCALISATION NVARCHAR(3990)
	DECLARE @DATEACTION NVARCHAR(20)
BEGIN
	IF NOT EXISTS (SELECT CTRLID FROM ZCTRL_FIL_EAU WHERE CTRLID = @ID) BEGIN

		--SET @DATEACTION=@DATEHEURE
		--SET @DATEACTION=LEFT(CONVERT(VARCHAR,CONVERT(DATETIME,@DATEHEURE,101),120),19)
		SET @DATEACTION=SUBSTRING(@DATEHEURE,7,4)+'-'+SUBSTRING(@DATEHEURE,4,2)+'-'+SUBSTRING(@DATEHEURE,1,2)+' '+SUBSTRING(@DATEHEURE,12,8)

		--LEFT(CONVERT(VARCHAR,CONVERT(DATETIME,@DATEHEURE,101),120),19)

		INSERT INTO SEQ_IDENTITY(LIBELLE) VALUES ('OK')
		SET @IDENTITY = (SELECT @@IDENTITY AS ID)
		SET @FLAG = (SELECT SUBSTRING(VERSION, 1, 3) FROM VERSION_SFW)
		SET @IID = @FLAG + @IDENTITY

		SET @SITELIBELLE=(SELECT LIBELLE FROM SITE WHERE SITEID=@SITEID)
		SET @LOCALISATION = ''

		IF (@EXINTERLOCUTEURID<>'') BEGIN
			IF EXISTS (SELECT TOP 1 INTERLOCUTEURID FROM INTERLOCUTEUR WHERE INTERLOCUTEURID = @EXINTERLOCUTEURID) BEGIN
				SET @NOMPRENOM = (SELECT TOP 1 NOMPRENOM FROM INTERLOCUTEUR WHERE INTERLOCUTEURID = @EXINTERLOCUTEURID)
				SET @SOCIETE = (SELECT TOP 1 SOCIETE FROM INTERLOCUTEUR WHERE INTERLOCUTEURID = @EXINTERLOCUTEURID)
				SET @INTERSTATUT = (SELECT TOP 1 NATURE.LIBELLE FROM INTERLOCUTEUR,NATURE WHERE INTERLOCUTEUR.NATUREID=NATURE.NATUREID AND INTERLOCUTEURID = @EXINTERLOCUTEURID)

				IF EXISTS (SELECT TOP 1 VISITEID FROM VISITES WHERE SITEID=@SITEID AND INTERLOCUTEURID=@EXINTERLOCUTEURID AND ((STATUTID=16 AND ( @DATEACTION  BETWEEN LEFT(CONVERT(VARCHAR,DEBUTVISITE,120),19) AND LEFT(CONVERT(VARCHAR,FINVISITE,120),19)))  OR (STATUTID=8 AND ( @DATEACTION >= LEFT(CONVERT(VARCHAR,DEBUTVISITE,120),19))))) BEGIN
					SET @VISITEID = (SELECT TOP 1 VISITEID FROM VISITES WHERE SITEID=@SITEID AND INTERLOCUTEURID=@EXINTERLOCUTEURID AND ((STATUTID=16 AND (@DATEACTION  BETWEEN LEFT(CONVERT(VARCHAR,DEBUTVISITE,120),19) AND LEFT(CONVERT(VARCHAR,FINVISITE,120),19)))  OR (STATUTID=8 AND (@DATEACTION >= LEFT(CONVERT(VARCHAR,DEBUTVISITE,120),19)))))

					SET @BADGE=(SELECT NUMEROBADGE FROM VISITES WHERE VISITEID=@VISITEID)
					SET @RESIDANTSOCIETELIB=(SELECT SOCIETERESID FROM VISITES WHERE VISITEID=@VISITEID)
					SET @RESIDANTSOCIETEID=(SELECT SOCIETEID FROM VISITES,RESIDANTS WHERE VISITES.RESIDANTID=RESIDANTS.RESIDANTID AND VISITEID=@VISITEID)
					SET @TICKET=(SELECT TICKET FROM VISITES WHERE VISITEID=@VISITEID)

					SELECT @LOCALISATION = @LOCALISATION + ';'+LOCALISATION
					FROM (
							SELECT DISTINCT L.LIBELLE AS LOCALISATION FROM  LOCALISATION L,PROFIL_CTRL PC,PROFIL_CTRL_LOCALISATION PCL,PROFIL_CTRL_LECTEUR CL,VISITES_LOCALISATION VL WHERE  PCL.PROFIL_CTRLID=PC.PROFIL_CTRLID AND PCL.LOCALISATIONID=L.LOCALISATIONID
							AND CL.PROFIL_CTRLID_EXT=PC.PROFIL_CTRLID_EXT AND VL.LOCALISATIONID=L.LOCALISATIONID
							AND VL.VISITEID=@VISITEID AND CL.CTRLREADERID=@LECTEURID
					) TAB_LOC
					SET @LOCALISATION=SUBSTRING(@LOCALISATION,2,4000)
					--SELECT  @LOCALISATION
				END
			END
			ELSE BEGIN
				SET @EXINTERLOCUTEURID = ''
				SET @NOMPRENOM =  @CTRL_NOM+' '+@CTRL_PRENOM
				SET @SOCIETE = @CTRL_SOCIETE
				SET @TICKET=''
			END
		END
		ELSE BEGIN
			SET @NOMPRENOM =  @CTRL_NOM+' '+@CTRL_PRENOM
			SET @SOCIETE = @CTRL_SOCIETE
		END

		IF  (@CARDCODE<>'') BEGIN
			SET @BADGE=@CARDCODE
		END;

		INSERT INTO ZCTRL_FIL_EAU (ID,CTRLID,CTRLDATE,CTRLREADER,CTRLDESC,CTRLEVENT,CTRLREADERID,BADGE,INTERLOCUTEURID,NOMPRENOM,SOCIETE,INTERLOCUTEURSTATUT,RESIDANTSOCIETELIB,RESIDANTSOCIETEID,SITEID,SITELIBELLE,DATECREATION,DATEMAJ,TICKET,LOCALISATION,CTRLPROFIL)
		VALUES(@IID,@ID,@DATEHEURE,@LECTEUR,@DESC,@CTRLEVENT,@LECTEURID,@BADGE,@EXINTERLOCUTEURID,@NOMPRENOM,@SOCIETE,@INTERSTATUT,@RESIDANTSOCIETELIB,@RESIDANTSOCIETEID,@SITEID,@SITELIBELLE,CURRENT_TIMESTAMP, CURRENT_TIMESTAMP,@TICKET,@LOCALISATION,@CTRL_PROFIL)
	END
END