CREATE PROCEDURE [dbo].[MODMEETING_INNES]

	@UNID NVARCHAR(20),
    @STARTDATE NVARCHAR(10),
	@STARTHOUR NVARCHAR(12),
    @ENDDATE NVARCHAR(10),
	@ENDHOUR NVARCHAR(12),
	@RETOUR INT OUTPUT

AS


BEGIN


	UPDATE LGRESERVATION SET
	DATEDEBUT= CONVERT(DATETIME, @STARTDATE + ' 00:00:00', 120),
	HEUREDEBUT=CONVERT(DATETIME, '1900-01-01 '+@STARTHOUR, 120),
	DATEFIN=CONVERT(DATETIME, @ENDDATE + ' 00:00:00', 120),
	HEUREFIN=CONVERT(DATETIME, '1900-01-01 '+@ENDHOUR, 120)

	WHERE CODELGRESERVATION =@UNID
	SET @RETOUR = @@ROWCOUNT

END