CREATE PROCEDURE [dbo].[PS_ACX_CREATE_ACCESS]
	@NOM NVARCHAR(70),
	@PRENOM NVARCHAR(70),
	@DATE1 NVARCHAR(20),
	@DATE2 NVARCHAR(20),
	@numeroJourFin int,
	@MATRICULE NVARCHAR(20),
	@ACXSITEID NVARCHAR(14)
AS
	DECLARE @ACXSITE NVARCHAR(40)
	DECLARE @NUMSITEACX NVARCHAR(20)
BEGIN
	SET @ACXSITE =(SELECT ISNULL(LIBELLE,'Le Hive') FROM SITE WHERE SITEID=@ACXSITEID)
	IF @ACXSITE='Le Hive' BEGIN
	 SET @ACXSITE='Le Hive | art&fact'
	END
	SET @NUMSITEACX =(SELECT ISNULL(NUMSITEACX,'1') FROM SITE WHERE SITEID=@ACXSITEID)
	INSERT INTO PERSONNE_ACX (RETOURACX,NUMSITEACX,TYPEPERSONNE,NOM,PRENOM,SESA,DATEDEBUT,DATEFIN,JOURFIN,SITEID,SITE,DATECREATION,DATEMAJ)
	VALUES ('-5',@NUMSITEACX,'RESIDANT',@NOM,@PRENOM,@MATRICULE,CONVERT(DATETIME,@DATE1,103),CONVERT(DATETIME,@DATE2,103),@numeroJourFin,@acxsiteid,@acxsite,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP)
	INSERT INTO PERSONNE_ACX_LOG (NUMSITEACX,TYPEPERSONNE,NOM,PRENOM,SESA,DATEDEBUT,DATEFIN,JOURFIN,SITEID,SITE,DATECREATION,DATEMAJ)
	VALUES (@numsiteacx,'RESIDANT',@NOM,@PRENOM,@MATRICULE,CONVERT(DATETIME,@DATE1,103),CONVERT(DATETIME,@DATE2,103),@numeroJourFin,@acxsiteid,@acxsite,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP)
END