CREATE PROCEDURE [dbo].[PS_CIVILITE]
	@FLAGIN INT,
	@CHAMPCTRL NVARCHAR(80),
	@CIVILITE NVARCHAR(30),
	@LIBELLECOURT NVARCHAR(5),
	@ID NVARCHAR(18) OUTPUT
AS
	DECLARE @FLAG NVARCHAR(14)
	DECLARE @IDENTITY NVARCHAR(14)
BEGIN
	IF ISNUMERIC(@CIVILITE)=1 AND EXISTS (SELECT * FROM CIVILITE WHERE CODECIVILITE = CAST(@CIVILITE AS INT)) BEGIN
		SET @ID = @CIVILITE + ',0,0'
	END
	ELSE BEGIN
		IF ((@CIVILITE IS NULL) OR LTRIM(@CIVILITE) = '') AND ((@LIBELLECOURT IS NULL) OR LTRIM(@LIBELLECOURT) = '') BEGIN
			SET @ID = '0,0,0'
		END
		ELSE BEGIN
			--SET @CIVILITE = UPPER(@CIVILITE)
			--SET @LIBELLECOURT = UPPER(@LIBELLECOURT)
			IF EXISTS (SELECT * FROM CIVILITE WHERE (UPPER(CIVILITE) = UPPER(@CIVILITE) OR UPPER(LIBELLECOURT) = UPPER(@LIBELLECOURT))) BEGIN
				SET @ID = (SELECT TOP 1 CAST(CODECIVILITE AS VARCHAR) FROM CIVILITE WHERE UPPER(CIVILITE) = UPPER(@CIVILITE) OR UPPER(LIBELLECOURT) = UPPER(@LIBELLECOURT))
				SET @ID = @ID + ',0,0'
			END
			ELSE BEGIN
				IF EXISTS (SELECT * FROM CIVILITE WHERE UPPER(CIVILITE) =UPPER(@CIVILITE)) BEGIN
					SET @ID = (SELECT TOP 1 CAST(CODECIVILITE AS VARCHAR) FROM CIVILITE WHERE UPPER(CIVILITE) = UPPER(@CIVILITE))
					--UPDATE CIVILITE SET LIBELLECOURT = @LIBELLECOURT, DATEMAJ = CURRENT_TIMESTAMP WHERE CODECIVILITE = CAST (@ID AS INT)
					SET @ID = @ID + ',0,1'
				END
				ELSE BEGIN
					IF EXISTS (SELECT * FROM CIVILITE WHERE UPPER(LIBELLECOURT) =  UPPER(@LIBELLECOURT)) BEGIN
						SET @ID = (SELECT TOP 1 CAST(CODECIVILITE AS VARCHAR) FROM CIVILITE WHERE UPPER(LIBELLECOURT) = UPPER(@LIBELLECOURT))
						--UPDATE CIVILITE SET CIVILITE = @CIVILITE, DATEMAJ = CURRENT_TIMESTAMP WHERE CODECIVILITE = CAST (@ID AS INT)
						SET @ID = @ID + ',0,1'
					END
					ELSE BEGIN
						INSERT INTO SEQ_IDENTITY(LIBELLE) VALUES ('OK')
						SET @IDENTITY = (SELECT @@IDENTITY AS ID)
						SET @FLAG = (SELECT SUBSTRING(VERSION, 1, 3) FROM VERSION_SFW)
						SET @ID = @FLAG + @IDENTITY

						INSERT INTO CIVILITE(CODECIVILITE, CIVILITE, LIBELLECOURT, DATECREATION, DATEMAJ)
							VALUES(CAST(@ID AS INT), @CIVILITE, @LIBELLECOURT, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
						SET @ID = @ID + ',1,0'
					END
				END
			END
		END
	END
END