CREATE PROCEDURE [dbo].[PS_CORRESPONDANCE]
	@FLAGIN INT,
	@CHAMPCTRL NVARCHAR(80),

	@LIBSSRC NVARCHAR(240),--LIBSRC1,LIBSRC2,LIBSRC3...
	@RANGSSRC NVARCHAR(20),--RANG(LIBSRC1),RANG(LIBSRC2),RANG(LIBSRC3)...
	@LIBDST NVARCHAR(80),
	@CFG_FICHIER NVARCHAR(200),
	@CORRES_RANG INT,

	@ID NVARCHAR(18) OUTPUT
AS
	DECLARE @CORRESID INT
	DECLARE @CFG_FICHIERID INT
BEGIN
	IF(ISNUMERIC(@CFG_FICHIER)=1)BEGIN
		IF(EXISTS(SELECT * FROM CFG_FICHIER WHERE CFG_FICHIERID=CAST(@CFG_FICHIER AS INT)))BEGIN
			SET @CFG_FICHIERID = CAST(@CFG_FICHIER AS INT)
		END
		ELSE BEGIN
			IF(EXISTS(SELECT * FROM CFG_FICHIER WHERE LIBELLE=@CFG_FICHIER))BEGIN
				SET @CFG_FICHIERID = (SELECT TOP 1 CFG_FICHIERID FROM CFG_FICHIER WHERE LIBELLE=@CFG_FICHIER)
			END
			ELSE BEGIN
				SET @CFG_FICHIERID = -1
			END
		END
	END
	ELSE BEGIN
		IF(EXISTS(SELECT * FROM CFG_FICHIER WHERE LIBELLE=@CFG_FICHIER))BEGIN
			SET @CFG_FICHIERID = (SELECT TOP 1 CFG_FICHIERID FROM CFG_FICHIER WHERE LIBELLE=@CFG_FICHIER)
		END
		ELSE BEGIN
			SET @CFG_FICHIERID = -1
		END
	END

	IF(@CFG_FICHIERID<>-1)BEGIN
		IF(EXISTS(SELECT * FROM CORRESPONDANCE WHERE CORRESID = CAST(@ID AS INT)))BEGIN

			UPDATE CORRESPONDANCE
			SET LIBSSRC=@LIBSSRC,RANGSSRC=@RANGSSRC,LIBDST=@LIBDST,CFG_FICHIERID=@CFG_FICHIERID,CORRES_RANG = @CORRES_RANG,DATEMAJ=CURRENT_TIMESTAMP
			WHERE CORRESID = CAST(@ID AS INT)

			SET @ID = @ID + ',0,1'
		END
		ELSE BEGIN
			IF(EXISTS(SELECT * FROM CORRESPONDANCE WHERE CFG_FICHIERID=@CFG_FICHIERID AND LIBSSRC=@LIBSSRC AND RANGSSRC = @RANGSSRC AND LIBDST=@LIBDST AND CORRES_RANG=@CORRES_RANG))BEGIN

				SET @ID = CAST((SELECT TOP 1 CORRESID FROM CORRESPONDANCE WHERE CFG_FICHIERID=@CFG_FICHIERID AND LIBSSRC=@LIBSSRC AND RANGSSRC = @RANGSSRC AND LIBDST=@LIBDST AND CORRES_RANG=@CORRES_RANG) AS VARCHAR)
				SET @ID = @ID + ',0,0'
			END
			ELSE BEGIN

				SET @CORRESID = (SELECT MAX(CORRESID) FROM CORRESPONDANCE)
				IF(@CORRESID IS NULL)BEGIN
					SET @CORRESID = 0
				END
				SET @CORRESID = @CORRESID+1
				INSERT INTO CORRESPONDANCE(CORRESID,LIBSSRC,RANGSSRC,LIBDST,CFG_FICHIERID,CORRES_RANG,DATEMAJ,DATECREATION)
				VALUES(@CORRESID,@LIBSSRC,@RANGSSRC,@LIBDST,@CFG_FICHIERID,@CORRES_RANG,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP)

				SET @ID = CAST(@CORRESID AS VARCHAR) + ',1,0'
			END
		END
	END
	ELSE BEGIN
		SET @ID = '-1,0,0'
	END
END