CREATE PROCEDURE [dbo].[PS_DEPARTEMENT]
	@FLAGIN INT,
	@CHAMPCTRL VARCHAR(80),
	@SOCIETEID VARCHAR(35),
	@LIBELLE VARCHAR(40),
	@ID VARCHAR(18) OUTPUT

AS
	DECLARE @FLAG VARCHAR(14)
	DECLARE @IDENTITY VARCHAR(14)
	DECLARE @LIBEL VARCHAR(40)
	DECLARE @IDSOCIETE VARCHAR(35)
	DECLARE @NBUPDATE INT
	DECLARE @NBINSERT INT
BEGIN
	SET @NBUPDATE = 0
	SET @NBINSERT = 0

	IF EXISTS (SELECT * FROM DEPARTEMENT WHERE DEPTID = @LIBELLE)
		BEGIN
			SET @ID=@LIBELLE +',0,0'
		END
	ELSE
	BEGIN
		SET @IDSOCIETE = @SOCIETEID

		EXEC PS_SOCIETE 1,'','',@IDSOCIETE,'','','','','','','','','','','','1',@IDSOCIETE OUTPUT

		SET @NBUPDATE = @NBUPDATE + CAST( (SELECT [DATA] FROM SPLIT(@IDSOCIETE,',') WHERE [ID] = 3) AS INT)
	 	SET @NBINSERT = @NBINSERT + CAST( (SELECT [DATA] FROM SPLIT(@IDSOCIETE,',') WHERE [ID] = 2) AS INT)

		SET @IDSOCIETE = (SELECT [DATA] FROM SPLIT(@IDSOCIETE,',') WHERE [ID] = 1)


		SET @LIBEL=@LIBELLE
		IF EXISTS (	SELECT * FROM DEPARTEMENT WHERE UPPER(LIBELLE) = UPPER(@LIBELLE) AND SOCIETEID=@IDSOCIETE )
		BEGIN
			SET @ID=(SELECT TOP(1) DEPTID FROM DEPARTEMENT WHERE UPPER(LIBELLE) = UPPER(@LIBELLE) AND SOCIETEID=@IDSOCIETE)
			SET @ID = @ID + ',' + CAST(@NBINSERT AS VARCHAR) + ',' + CAST(@NBUPDATE AS VARCHAR)
		END
		ELSE
			BEGIN
				IF (@LIBEL IS NOT NULL) AND (LTRIM(@LIBEL) IS NOT NULL) AND LTRIM(@LIBEL)<>'' BEGIN
					INSERT INTO SEQ_IDENTITY(LIBELLE) VALUES ('OK')
					SET @IDENTITY = (SELECT @@IDENTITY AS ID)
					SET @FLAG = (SELECT SUBSTRING(VERSION, 1, 3) FROM VERSION_SFW)
					SET @ID = @FLAG + @IDENTITY
					INSERT INTO DEPARTEMENT (DEPTID,LIBELLE,SOCIETEID,DATECREATION,DATEMAJ) VALUES (@ID,@LIBEL,@IDSOCIETE,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
					SET @NBINSERT=@NBINSERT+1;
					SET @ID = @ID + ',' + CAST(@NBINSERT AS VARCHAR) + ',' + CAST(@NBUPDATE AS VARCHAR)

					END
				ELSE BEGIN
					SET @ID='VPARDEFAUT'
					SET @ID = @ID + ',' + CAST(@NBINSERT AS VARCHAR) + ',' + CAST(@NBUPDATE AS VARCHAR)
				END
			END

	END
END