CREATE PROCEDURE [dbo].[PS_ESVISITES_OUTINT]
	@visiteid NVARCHAR(14),
    @actionDate NVARCHAR(20)
AS

BEGIN

	UPDATE VISITES SET STATUTID='16',DATEMAJ=CONVERT(DATETIME,@actionDate,103),FINVISITE=CONVERT(DATETIME,CONVERT(VARCHAR(10),@actionDate,103),103), HFIN=CONVERT(DATETIME,SUBSTRING(CONVERT(VARCHAR,@actionDate,103),12,5),108) WHERE VISITEID=@visiteid
END