CREATE PROCEDURE [dbo].[PS_ESVISITES_LOG_INS]
	@quiid NVARCHAR(14),
	@quitype  NVARCHAR(40),
    @nomprenom NVARCHAR(70),
	@societe NVARCHAR(70),
	@numbadge NVARCHAR(200),
	@sens NVARCHAR(50),
	@etat NVARCHAR(50),
	@details NVARCHAR(2000),
	@datepassage NVARCHAR(20),
	@typeinsert NVARCHAR(14),
	@remotedate NVARCHAR(20),
	@siteid NVARCHAR(14),
	@guichetid NVARCHAR(14),
	@poste NVARCHAR(50),
	@typeLecteur NVARCHAR(40)


AS
	DECLARE @FLUXID NVARCHAR(14)
	DECLARE @FLAG NVARCHAR(14)
	DECLARE @IDENTITY NVARCHAR(14)
    BEGIN
	INSERT INTO SEQ_IDENTITY(LIBELLE) VALUES ('OK')
	SET @IDENTITY = (SELECT @@IDENTITY AS ID)
	SET @FLAG = (SELECT TOP 1 SUBSTRING(VERSION, 1, 3) FROM VERSION_SFW)
	SET @FLUXID = @FLAG + @IDENTITY
	INSERT INTO ESVISITES_LOG (ESVISITES_LOGID,QUIID,QUITYPE,NOMPRENOM,SOCIETE,NUMBADGE,SENS,ETAT,DETAILS,PASSAGE,TYPEINSERT,REMOTEDATE,SITEID,GUICHETID,POSTE,TYPELECTEUR,DATECREATION,DATEMAJ) VALUES
	(@FLUXID,@quiid,@quitype,@nomprenom,@societe,@numbadge,@sens,@etat,@details,CONVERT(DATETIME,@datepassage,103),@typeinsert,@remotedate,@siteid,@guichetid,@poste,@typeLecteur,CURRENt_TIMESTAMP,CURRENT_TIMESTAMP)
END