CREATE PROCEDURE [dbo].[PS_ESVISITES_OUTVEHICULE]
	@residantid NVARCHAR(14),
	@guichetid  NVARCHAR(14),
    @actionDate NVARCHAR(20),
	@badge NVARCHAR(34),
	@PASSAGERID NVARCHAR(14)
AS
DECLARE @TMP   int
BEGIN
	SET @tmp=1
END