CREATE PROCEDURE [dbo].[PS_FONCTION]
	@FLAGIN INT,
	@CHAMPCTRL VARCHAR(80),
	@LIBELLE VARCHAR(30),
	@ID VARCHAR(18) OUTPUT
AS
	DECLARE @FLAG VARCHAR(14)
	DECLARE @IDENTITY VARCHAR(14)

BEGIN
	IF ISNUMERIC(@LIBELLE) = 1 AND EXISTS (SELECT * FROM FONCTION WHERE CODEFONCTION = CAST(@LIBELLE AS INT)) BEGIN
		SET @ID = @LIBELLE + ',0,0'
	END
	ELSE BEGIN
		IF EXISTS (SELECT * FROM FONCTION WHERE LIBELLE = @LIBELLE) BEGIN
			SET @ID = CAST((SELECT TOP 1 CODEFONCTION FROM FONCTION WHERE LIBELLE = @LIBELLE) AS VARCHAR) + ',0,0'
		END
		ELSE BEGIN
			IF (@LIBELLE IS NULL) OR LTRIM(@LIBELLE) = '' BEGIN
				SET @ID = '0,0,0'
			END
			ELSE BEGIN
				SET @LIBELLE = UPPER(@LIBELLE)
				IF EXISTS (SELECT * FROM FONCTION WHERE UPPER(LIBELLE) = @LIBELLE ) BEGIN
					SET @ID = (SELECT TOP 1 CONVERT(VARCHAR,CODEFONCTION) FROM FONCTION WHERE UPPER(LIBELLE) = @LIBELLE)
					SET @ID = @ID + ',0,0'
				END
				ELSE BEGIN
					INSERT INTO SEQ_IDENTITY(LIBELLE) VALUES ('OK')
					SET @IDENTITY = (SELECT @@IDENTITY AS ID)
					SET @FLAG = (SELECT SUBSTRING(VERSION, 1, 3) FROM VERSION_SFW)
					SET @ID = @FLAG + @IDENTITY

					INSERT INTO FONCTION(CODEFONCTION, LIBELLE, DATECREATION, DATEMAJ)
						VALUES(@ID , @LIBELLE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
					SET @ID = @ID + ',1,0'
				END
			END
		END
	END
END