CREATE PROCEDURE [dbo].[PS_IMPORT_DELETE_RESA_OPENPORTAL]

    @REFVISITOR NVARCHAR(30)
AS

BEGIN
    DELETE FROM LGPARTICIPANT WHERE CODELGRESERVATION IN (SELECT CODELGRESERVATION FROM LGRESERVATION WHERE CODERESERVATION IN (SELECT CODERESERVATION FROM RESERVATION WHERE PRIORITE='-177' AND SUBSTRING(REFRESERVATION,7,LEN(REFRESERVATION))=@REFVISITOR))
	DELETE FROM VISITES WHERE VISITEID IN (SELECT VISITEID FROM VISITES WHERE CODELGRESERVATION IN (SELECT CODELGRESERVATION FROM LGRESERVATION WHERE CODERESERVATION IN (SELECT CODERESERVATION FROM RESERVATION WHERE PRIORITE='-177' AND SUBSTRING(REFRESERVATION,7,LEN(REFRESERVATION))=@REFVISITOR)))
	DELETE FROM LGRESERVATION WHERE CODERESERVATION IN (SELECT CODERESERVATION FROM RESERVATION WHERE PRIORITE='-177' AND SUBSTRING(REFRESERVATION,7,LEN(REFRESERVATION))=@REFVISITOR)
    DELETE FROM RESERVATION WHERE CODERESERVATION IN(SELECT CODERESERVATION FROM RESERVATION WHERE PRIORITE='-177' AND SUBSTRING(REFRESERVATION,7,LEN(REFRESERVATION))=@REFVISITOR)

END