CREATE PROCEDURE [dbo].[PS_IMPORT_RESA]
    @flagin int,
    @champctrl NVARCHAR(80),
    @DATESAISIE NVARCHAR(30),
    @RNOM NVARCHAR(30),
    @RPRENOM NVARCHAR(30),
    @RMATRICULE NVARCHAR(30),
    @INOM NVARCHAR(30),
    @IPRENOM NVARCHAR(30),
    @IMATRICULE NVARCHAR(30),
    @SALLE NVARCHAR(30),
    @DATERESA NVARCHAR(30),
    @HDEBUT NVARCHAR(30),
    @HFIN NVARCHAR(30),
    @STATUT NVARCHAR(30),
    @USERLOGIN NVARCHAR(30),
    @REFVISITOR NVARCHAR(30),
    @ROBSERVATION NVARCHAR(3000),
    @ID NVARCHAR(18) OUTPUT
AS
    DECLARE @FLAG NVARCHAR(14)
    DECLARE @IDENTITY NVARCHAR(14)
    DECLARE @NOMPRENOM NVARCHAR(30)
    DECLARE @SOCIETE NVARCHAR(30)
    DECLARE @CODEANIMATEUR NVARCHAR(30)
    DECLARE @SOCIETEID NVARCHAR(30)
    DECLARE @INTERLOCUTEURID NVARCHAR(30)
    DECLARE @CODESTATUT NVARCHAR(30)
    DECLARE @DATECREATION DATETIME
    DECLARE @REFRESERVATION NVARCHAR(30)
    DECLARE @CODERESERVATION NVARCHAR(30)
    DECLARE @CODELGRESERVATION NVARCHAR(30)
    DECLARE @USERID NVARCHAR(30)
    DECLARE @DATEDEBUT DATETIME
    DECLARE @HEUREDEBUT NVARCHAR(30)
    DECLARE @HEUREFIN NVARCHAR(30)
    DECLARE @CODESALLE NVARCHAR(30)
    DECLARE @LIBELLESALLE NVARCHAR(30)
    DECLARE @NOSALLE NVARCHAR(30)
    DECLARE @CODEAMENAGEMENT NVARCHAR(30)
    DECLARE @EMETTEUR NVARCHAR(100)
    DECLARE @MYREFVISITOR NVARCHAR(30)
    DECLARE @LOCID INT
BEGIN
	SET @ID='0,0,0'
    SET @CODEANIMATEUR= (SELECT TOP 1 RESIDANTID FROM RESIDANTS WHERE MATRICULE=RTRIM(LTRIM(@RMATRICULE)))
    IF (@CODEANIMATEUR='' OR @CODEANIMATEUR IS NULL) BEGIN
		SET @CODEANIMATEUR= (SELECT TOP 1 RESIDANTID FROM RESIDANTS WHERE UPPER(NOM)=UPPER(@RNOM) AND UPPER(PRENOM)=UPPER(@RPRENOM))
    END
   -- IF (@CODEANIMATEUR='' OR @CODEANIMATEUR IS NULL) BEGIN
	--	SET @CODEANIMATEUR= (SELECT TOP 1 RESIDANTID FROM RESIDANTS WHERE MATRICULE='SESA45589')
  --  END
    IF (@CODEANIMATEUR<>'' AND @CODEANIMATEUR IS NOT NULL) BEGIN
		SET @CODESALLE= (SELECT TOP 1 CODESALLE FROM SALLE WHERE UPPER(LIBELLE)='BULLE-'+UPPER(@SALLE))
		SET @LIBELLESALLE=(SELECT TOP 1 LIBELLE FROM SALLE WHERE CODESALLE=@CODESALLE)
		SET @NOSALLE=(SELECT TOP 1 NOSALLE FROM SALLE WHERE CODESALLE=@CODESALLE)
		SET @MYREFVISITOR=(CAST(YEAR(CURRENT_TIMESTAMP)AS VARCHAR)+'I-'+@REFVISITOR)
		IF EXISTS (SELECT TOP 1 NOSALLE FROM SALLE WHERE CODESALLE=@CODESALLE) BEGIN
			IF NOT EXISTS (SELECT REFRESERVATION FROM RESERVATION WHERE REFRESERVATION=@MYREFVISITOR) BEGIN
				SET @SOCIETEID = (SELECT TOP 1 SOCIETEID FROM RESIDANTS WHERE RESIDANTID = @CODEANIMATEUR)
				SET @INTERLOCUTEURID= (SELECT TOP 1 RESIDANTID FROM RESIDANTS WHERE RESIDANTID= @CODEANIMATEUR)
				SET @CODESTATUT= (SELECT TOP 1 CODESTATUT FROM STATUTRESERVATION WHERE UPPER(LIBELLE)=UPPER(@STATUT))
				SET @USERID= (SELECT TOP 1 USERID FROM USERS WHERE UPPER(THELOGIN)=UPPER(@USERLOGIN))
				SET @DATECREATION=CONVERT(DATETIME,CURRENT_TIMESTAMP,103)
				INSERT INTO SEQ_IDENTITY(LIBELLE) VALUES ('OK')
				SET @IDENTITY = (SELECT @@IDENTITY AS ID)
				SET @FLAG = (SELECT SUBSTRING(VERSION, 1, 3) FROM VERSION_SFW)
				SET @CODERESERVATION = @FLAG + @IDENTITY
				SET @REFRESERVATION = @MYREFVISITOR
				SET @EMETTEUR=(SELECT NOMPRENOM FROM RESIDANTS WHERE RESIDANTID=@CODEANIMATEUR)
				INSERT INTO RESERVATION (CODERESERVATION,CODETYPERESERVATION,SOCIETEID,INTERLOCUTEURID,USERID,CODEANIMATEUR,CODESTATUT,REFRESERVATION,NBPERSDEMANDE,IMPUTATIONID,SALLE_VALIDEE,EMETTEUR,COMMENTAIRE,DATECREATION,DATEMAJ) VALUES (@CODERESERVATION,'VPARDEFAUT',@SOCIETEID,@INTERLOCUTEURID,@USERID,@CODEANIMATEUR,@CODESTATUT,@REFRESERVATION,1,'VPARDEFAUT',0,@EMETTEUR,@ROBSERVATION,@DATECREATION,CURRENT_TIMESTAMP)

				 --SET @CODESALLE= (SELECT TOP 1 CODESALLE FROM SALLE WHERE UPPER(LIBELLE)=UPPER(@SALLE))
				 --SET @LIBELLESALLE=(SELECT TOP 1 LIBELLE FROM SALLE WHERE CODESALLE=@CODESALLE)
				 --SET @NOSALLE=(SELECT TOP 1 NOSALLE FROM SALLE WHERE CODESALLE=@CODESALLE)

			--SET @DATEDEBUT=CONVERT(VARCHAR,CONVERT(DATETIME,@DATERESA,103),120)
				 SET @DATEDEBUT=CONVERT(DATETIME,CONVERT(VARCHAR(24),CONVERT(DATETIME,@DATERESA,120),103),103)  --yyyy-mm-dd hh:mi:ss.fff

				 SET @HEUREDEBUT=CONVERT(DATETIME,'01/01/1901 '+SUBSTRING(@HDEBUT,12,5)+':00',103)
				  -- SET @HEUREDEBUT=CONVERT(DATETIME,@HDEBUT+':00',103)
				 --SET @HEUREDEBUT=CURRENT_TIMESTAMP

				-- SET @HEUREFIN=CONVERT(DATETIME,'01/01/1901 '+SUBSTRING(@HFIN,12,5)+':00',103) SI @HFIN DATETIME FORMAT
				 SET @HEUREFIN= DATEADD(mi,CAST(@HFIN AS INT),@HEUREDEBUT) --SI @HFIN MINUTES
				 --SET @HEUREFIN=CURRENT_TIMESTAMP

				 INSERT INTO SEQ_IDENTITY(LIBELLE) VALUES ('OK')
				 SET @IDENTITY = (SELECT @@IDENTITY AS ID)
				 SET @FLAG = (SELECT SUBSTRING(VERSION, 1, 3) FROM VERSION_SFW)
				 SET @CODELGRESERVATION = @FLAG + @IDENTITY
				SET @CODEAMENAGEMENT=(SELECT TOP 1 CODEAMENAGEMENT FROM AMENAGSALLE  WHERE CODESALLE=@CODESALLE)
				 INSERT INTO LGRESERVATION (CODERESERVATION,CODESALLE,CODESTATUT,CODELGRESERVATION,CODEAMMENAGEMENT,DATEDEBUT,DATEFIN,HEUREDEBUT,HEUREFIN,HEURECONTINU,LIBELLESALLE,WIZARD,NOSALLE,DATECREATION,DATEMAJ) VALUES
				(@CODERESERVATION,@CODESALLE,@CODESTATUT,@CODELGRESERVATION,@CODEAMENAGEMENT,dbo.TRUNC(@DATEDEBUT),dbo.TRUNC(@DATEDEBUT),@HEUREDEBUT,@HEUREFIN,1,@LIBELLESALLE,'1',@NOSALLE,@DATECREATION,CURRENT_TIMESTAMP)

				SET @ID='0,1,0'
			END ELSE BEGIN
				SET @LOCID=(SELECT MAX(ALARMEID)+1 FROM ALARME)
				IF @LOCID IS NULL BEGIN
					SET @LOCID=0
				END
				INSERT INTO ALARME (ALARMEID,LIBELLE,DATEMAJ,DATECREATION,DATESYNCHRO) VALUES(@LOCID,'REFERENCE DEJA PRESENTE '+@MYREFVISITOR,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP)
			END
		END ELSE  BEGIN
			SET @LOCID=(SELECT MAX(ALARMEID)+1 FROM ALARME)
			IF @LOCID IS NULL BEGIN
				SET @LOCID=0
			END
			IF @SALLE IS NULL OR @SALLE='' BEGIN
			SET @SALLE='Vide'
			END
			INSERT INTO ALARME (ALARMEID,LIBELLE,DATEMAJ,DATECREATION,DATESYNCHRO) VALUES(@LOCID,'SALLE NON TROUVEE '+@SALLE+':'+@MYREFVISITOR,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP)
		END
	END
	IF (@CODEANIMATEUR='' AND @CODEANIMATEUR IS NULL) BEGIN
		SET @LOCID=(SELECT MAX(ALARMEID)+1 FROM ALARME)
		IF @LOCID IS NULL BEGIN
			SET @LOCID=0
		END
		INSERT INTO ALARME (ALARMEID,LIBELLE,DATEMAJ,DATECREATION,DATESYNCHRO) VALUES(@LOCID,'SESA NON TROUVE '+@RMATRICULE,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP)
	END
END