CREATE PROCEDURE [dbo].[PS_IDENTITE_CRITERES_DEUX]
	@NOM VARCHAR(35),
	@PRENOM VARCHAR(35),
	@DATENAISSANCE DATETIME
AS
BEGIN
	IF EXISTS (SELECT INTERLOCUTEURID FROM INTERLOCUTEUR WHERE ((UPPER(NOM) = @NOM OR UPPER(NOMJEUNEFILLE) = @NOM) AND (UPPER(PRENOM) LIKE(@PRENOM+'%'))) OR ((UPPER(NOM) = @NOM OR UPPER(NOMJEUNEFILLE) = @NOM) AND dbo.TRUNC(DATENAISSANCE) = @DATENAISSANCE)) BEGIN
		SELECT INTERLOCUTEURID FROM INTERLOCUTEUR WHERE ((UPPER(NOM) = @NOM OR UPPER(NOMJEUNEFILLE) = @NOM) AND (UPPER(PRENOM) LIKE(@PRENOM+'%'))) OR ((UPPER(NOM) = @NOM OR UPPER(NOMJEUNEFILLE) = @NOM) AND dbo.TRUNC(DATENAISSANCE) = @DATENAISSANCE)
	END
	ELSE BEGIN
		SELECT '-1' AS INTERLOCUTEURID
	END
END