CREATE PROCEDURE [dbo].[PS_IDENTITES]
	@FLAGIN INT,
	@CHAMPCTRL NVARCHAR(80),

	@TYPEIDENTITE NVARCHAR(35),
	@DELIVREPAR NVARCHAR(80),
	@FINVALIDITE DATETIME,
	@NUMERO NVARCHAR(20),
	@IMAGE IMAGE,
	@INTERLOCUTEURID NVARCHAR(14),

	@ID NVARCHAR(18) OUTPUT
AS
	DECLARE @FLAG NVARCHAR(14)
	DECLARE @IDENTITY NVARCHAR(14)
	DECLARE @TYPEIDENTITEID INT
	DECLARE @NBUPDATE INT
	DECLARE @NBINSERT INT
BEGIN
	SET @NBUPDATE = 0
	SET @NBINSERT = 0
	IF (@INTERLOCUTEURID IS NOT NULL) AND LTRIM(@INTERLOCUTEURID) IS NOT NULL AND LTRIM(@INTERLOCUTEURID)<>'' AND @NUMERO IS NOT NULL AND LTRIM(@NUMERO)<>''	BEGIN
	SET @TYPEIDENTITEID = (SELECT TOP 1 TYPEIDENTITEID FROM TYPEIDENTITE WHERE UPPER(LIBELLE) = UPPER(@TYPEIDENTITE))
	IF(@TYPEIDENTITEID IS NULL AND ISNUMERIC(@TYPEIDENTITE)=1)BEGIN
		SET @TYPEIDENTITEID = (SELECT TOP 1 TYPEIDENTITEID FROM TYPEIDENTITE WHERE TYPEIDENTITEID = CAST(@TYPEIDENTITE AS INT))
	END
	IF(@TYPEIDENTITEID IS NULL)BEGIN
		SET @TYPEIDENTITEID = (SELECT MIN(TYPEIDENTITEID) FROM TYPEIDENTITE)
		SET @TYPEIDENTITEID = @TYPEIDENTITEID - 1
		INSERT INTO TYPEIDENTITE(TYPEIDENTITEID,LIBELLE,DATEMAJ,DATECREATION)
			VALUES(@TYPEIDENTITEID,@TYPEIDENTITE,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP)
		SET @NBINSERT = @NBINSERT + 1
	END

		IF(EXISTS(SELECT TOP 1 * FROM IDENTITES WHERE TYPEIDENTITEID = @TYPEIDENTITEID AND INTERLOCUTEURID=@INTERLOCUTEURID))BEGIN

			IF(EXISTS(SELECT TOP 1 * FROM IDENTITES WHERE TYPEIDENTITEID = @TYPEIDENTITEID AND INTERLOCUTEURID=@INTERLOCUTEURID AND NUMERO = @NUMERO))BEGIN
				SET @ID = (SELECT TOP 1 IDENTITEID FROM IDENTITES WHERE TYPEIDENTITEID = @TYPEIDENTITEID AND INTERLOCUTEURID=@INTERLOCUTEURID AND NUMERO = @NUMERO)
				SET @ID = @ID + ',' + CAST(@NBINSERT AS VARCHAR) + ',' + CAST(@NBUPDATE AS VARCHAR)
			END
			ELSE BEGIN
				UPDATE IDENTITES
				SET DELIVREPAR = @DELIVREPAR,FINVALIDITE = @FINVALIDITE,NUMERO = @NUMERO,IMAGE=@IMAGE
				WHERE TYPEIDENTITEID = @TYPEIDENTITEID
				AND INTERLOCUTEURID=@INTERLOCUTEURID

				SET @ID = (SELECT TOP 1 IDENTITEID FROM IDENTITES WHERE TYPEIDENTITEID = @TYPEIDENTITEID AND INTERLOCUTEURID=@INTERLOCUTEURID)
				SET @NBUPDATE = @NBUPDATE + 1
				SET @ID = @ID + ',' + CAST(@NBINSERT AS VARCHAR) + ',' + CAST(@NBUPDATE AS VARCHAR)
			END
		END
		ELSE BEGIN
			IF(@FLAGIN=1)BEGIN
				INSERT INTO SEQ_IDENTITY(LIBELLE) VALUES ('OK')
				SET @IDENTITY = (SELECT @@IDENTITY AS ID)
				SET @FLAG = (SELECT SUBSTRING(VERSION, 1, 3) FROM VERSION_SFW)
				SET @ID = @FLAG + @IDENTITY

				INSERT INTO IDENTITES(TYPEIDENTITEID,DELIVREPAR,FINVALIDITE,NUMERO,IMAGE,INTERLOCUTEURID,IDENTITEID,DATECREATION,DATEMAJ)
					VALUES(@TYPEIDENTITEID ,@DELIVREPAR,@FINVALIDITE,@NUMERO,@IMAGE,@INTERLOCUTEURID,@ID,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP)
				SET @NBINSERT = @NBINSERT + 1
				SET @ID = @ID + ',' + CAST(@NBINSERT AS VARCHAR) + ',' + CAST(@NBUPDATE AS VARCHAR)
			END
			ELSE BEGIN
				SET @ID = '0,' + CAST(@NBINSERT AS VARCHAR) + ',' + CAST(@NBUPDATE AS VARCHAR)
			END
		END
	END
	ELSE BEGIN
		SET @ID = '0,' + CAST(@NBINSERT AS VARCHAR) + ',' + CAST(@NBUPDATE AS VARCHAR)
	END
END