CREATE PROCEDURE [dbo].[PS_MODULE_PURGE]
    --INTERLOCUTEUR
	@INTSANSVISITES NVARCHAR(10),
    @INTSANSVISITESNBJOURS NVARCHAR(10),
    @INTSANSVISITESDATE NVARCHAR(20),
    @INTSESVISITES NVARCHAR(10),
	@INTANONYMEVISITES NVARCHAR(10),
	@INTNONINTERDIT NVARCHAR(10),
    @INTSESCOLIS NVARCHAR(10),
	@INTSESCONSIGNESETMESSAGES NVARCHAR(10),
	@INTSESCOURSTAXIS NVARCHAR(10),
	@INTCONSIGNE NVARCHAR(10),
	--RESIDANTS
	@RESNONACTIF NVARCHAR(10),
    @RESSESVISITES NVARCHAR(10),
    @RESNONMAJNBJOURS NVARCHAR(10),
    @RESNONMAJDATE NVARCHAR(20),

	--VISITEUR
	@VISDATANTDEPLUSNBJOUR NVARCHAR(10),
	@VISANTERIEURDATE NVARCHAR(20),
	@VISANONYMEVISITES NVARCHAR(10),
	--SOCIETE
	@SOCNONUTILISE NVARCHAR(10),

	--CONSIGNE
	@CONSUPMESSAGESLUS NVARCHAR(10),

	--COLISEMIS/COLISRECU
	@COLCOLIS NVARCHAR(10),

	--TACHE_LOG
	@TALPURGE NVARCHAR(10),

	--TACHE
	@TACEXECUTEOUINACTIVE NVARCHAR(10),
	@TACSESCONFIGS NVARCHAR(10),

	--MAIL
	@MAIENVOYE NVARCHAR(10),

	--AGENDA_JOUR2
	@AJ2TERMINE NVARCHAR(10),

	--RESERVATION/LGRESERVATION
	@LGRTERMINEEDEPUISNBJOURS NVARCHAR(10),
	@LGRTERMINEEDEPUISDATE NVARCHAR(20),

    @ID NVARCHAR(18) OUTPUT
AS
BEGIN
DECLARE @NBVISPURGE INT
DECLARE @NBPURGE INT
DECLARE @NBRESPURGE INT
DECLARE @NBINTPURGE INT
SET  @NBVISPURGE=0
SET  @NBPURGE=0
	SELECT INTERLOCUTEURID INTO #MYINTERLOCUTEUR FROM INTERLOCUTEUR I WHERE
		  (
	   I.INTERLOCUTEURID<>'VPARDEFAUT'
	   )
	   AND
	   0=(SELECT COUNT(INTERLOCUTEURID) FROM VISITES WHERE INTERLOCUTEURID=I.INTERLOCUTEURID AND STATUTID IN (8,1,33,34))
	   AND
		(	((
				(
				@INTSANSVISITES<>'' AND @INTSANSVISITES IS NOT NULL AND (0=(SELECT COUNT(INTERLOCUTEURID) FROM VISITES WHERE INTERLOCUTEURID=I.INTERLOCUTEURID AND STATUTID IN (2,16,32,35)))
				)
			)
			OR
			(
				@INTSANSVISITESNBJOURS<>'' AND @INTSANSVISITESNBJOURS IS NOT NULL AND 0=(SELECT COUNT(INTERLOCUTEURID) FROM VISITES WHERE
				(DATEADD(DD,CAST (@INTSANSVISITESNBJOURS AS INT) ,CONVERT(DATETIME,FINVISITE,103))>CONVERT(DATETIME,CURRENT_TIMESTAMP,103) AND STATUTID IN (16,35)
				OR
				(DATEADD(DD,CAST (@INTSANSVISITESNBJOURS AS INT),CONVERT(DATETIME,FINPREVU,103))>CONVERT(DATETIME,CURRENT_TIMESTAMP,103) AND STATUTID IN (2,32))
				) 	AND (I.INTERLOCUTEURID=INTERLOCUTEURID)
				)
			)
			OR
			(
				@INTSANSVISITESDATE<>'' AND @INTSANSVISITESDATE IS NOT NULL AND 0=(SELECT COUNT(INTERLOCUTEURID) FROM VISITES WHERE
				(CONVERT(DATETIME,FINVISITE,103)>CONVERT(DATETIME,@INTSANSVISITESDATE,103) AND STATUTID IN (16,35)
				OR
				CONVERT(DATETIME,FINPREVU,103)>CONVERT(DATETIME,@INTSANSVISITESDATE,103) AND STATUTID IN(2,32)
				)
				AND (I.INTERLOCUTEURID=INTERLOCUTEURID)
				)

			)
		)
		AND
			(
				(@INTNONINTERDIT<>'' AND @INTNONINTERDIT IS NOT NULL)
				OR
				(
				( (@INTNONINTERDIT='' OR @INTNONINTERDIT IS  NULL) AND (I.INTERDIT='0' OR I.INTERDIT IS NULL) )
				)
			)
		AND
			(
				(@INTCONSIGNE<>'' AND @INTCONSIGNE IS NOT NULL)
				OR
				(
				(@INTCONSIGNE='' OR @INTCONSIGNE IS  NULL) AND
				( 0=(SELECT COUNT(CONSIGNEID) FROM CONSIGNE WHERE RESIDANTID='VISITEUR' AND INTERLOCUTEURID=I.INTERLOCUTEURID))

				)

			)
		)
			SET  @NBVISPURGE =(SELECT COUNT(VISITEID) FROM VISITES WHERE STATUTID=-1 OR (
			STATUTID NOT IN (1,8,33,34) AND
				(
					(@VISDATANTDEPLUSNBJOUR<>''  AND @VISDATANTDEPLUSNBJOUR IS NOT NULL
					 AND
						(
							(DATEADD(DD,CAST (@VISDATANTDEPLUSNBJOUR AS INT) ,CONVERT(DATETIME,FINVISITE,103))<CONVERT(DATETIME,CURRENT_TIMESTAMP,103) AND STATUTID IN (16,35) )
							OR
							(DATEADD(DD,CAST (@VISDATANTDEPLUSNBJOUR AS INT) ,CONVERT(DATETIME,FINPREVU,103))<CONVERT(DATETIME,CURRENT_TIMESTAMP,103)	AND STATUTID IN (2,32))
						 )
					)
					OR
					(@VISANTERIEURDATE<>'' AND @VISANTERIEURDATE IS NOT NULL
					AND
						(
							(CONVERT(DATETIME,FINVISITE,103)<CONVERT(DATETIME,@VISANTERIEURDATE,103) AND STATUTID IN (16,35) )
							OR
							(CONVERT(DATETIME,FINPREVU,103)<CONVERT(DATETIME,@VISANTERIEURDATE,103) AND STATUTID IN (2,32) )
						)
					)
				)))

		IF @VISANONYMEVISITES<>'' AND @VISANONYMEVISITES IS NOT NULL BEGIN


		UPDATE VISITES SET INTERLOCUTEURID='VPARDEFAUT',NOMPRENOMVISIT=(SELECT NOMPRENOM FROM INTERLOCUTEUR WHERE INTERLOCUTEURID='VPARDEFAUT') WHERE
			STATUTID=-1 OR (STATUTID NOT IN (1,8,33,34) AND

				(
					(@VISDATANTDEPLUSNBJOUR<>''  AND @VISDATANTDEPLUSNBJOUR IS NOT NULL
					 AND
						(
							(DATEADD(DD,CAST (@VISDATANTDEPLUSNBJOUR AS INT) ,CONVERT(DATETIME,FINVISITE,103))<CONVERT(DATETIME,CURRENT_TIMESTAMP,103) AND STATUTID IN (16,35) )
							OR
							(DATEADD(DD,CAST (@VISDATANTDEPLUSNBJOUR AS INT) ,CONVERT(DATETIME,FINPREVU,103))<CONVERT(DATETIME,CURRENT_TIMESTAMP,103)	AND STATUTID IN (2,32))
						 )
					)
					OR
					(@VISANTERIEURDATE<>'' AND @VISANTERIEURDATE IS NOT NULL
					AND
						(
							(CONVERT(DATETIME,FINVISITE,103)<CONVERT(DATETIME,@VISANTERIEURDATE,103) AND STATUTID IN (16,35) )
							OR
							(CONVERT(DATETIME,FINPREVU,103)<CONVERT(DATETIME,@VISANTERIEURDATE,103) AND STATUTID IN (2,32) )
						)
					)
				)
			)
		END ELSE BEGIN
			DELETE FROM VISITES  WHERE
			STATUTID=-1 OR (
			STATUTID NOT IN (1,8,33,34) AND

				(
					(@VISDATANTDEPLUSNBJOUR<>''  AND @VISDATANTDEPLUSNBJOUR IS NOT NULL
					 AND
						(
							(DATEADD(DD,CAST (@VISDATANTDEPLUSNBJOUR AS INT) ,CONVERT(DATETIME,FINVISITE,103))<CONVERT(DATETIME,CURRENT_TIMESTAMP,103) AND STATUTID IN (16,35) )
							OR
							(DATEADD(DD,CAST (@VISDATANTDEPLUSNBJOUR AS INT) ,CONVERT(DATETIME,FINPREVU,103))<CONVERT(DATETIME,CURRENT_TIMESTAMP,103)	AND STATUTID IN (2,32))
						 )
					)
					OR
					(@VISANTERIEURDATE<>'' AND @VISANTERIEURDATE IS NOT NULL
					AND
						(
							(CONVERT(DATETIME,FINVISITE,103)<CONVERT(DATETIME,@VISANTERIEURDATE,103) AND STATUTID IN (16,35) )
							OR
							(CONVERT(DATETIME,FINPREVU,103)<CONVERT(DATETIME,@VISANTERIEURDATE,103) AND STATUTID IN (2,32) )
						)
					)
				))
	END

	IF @INTANONYMEVISITES<>'' AND @INTANONYMEVISITES IS NOT NULL AND @INTSESVISITES<>'' BEGIN
		UPDATE VISITES SET INTERLOCUTEURID='VPARDEFAUT',NOMPRENOMVISIT=(SELECT NOMPRENOM FROM INTERLOCUTEUR WHERE INTERLOCUTEURID='VPARDEFAUT') WHERE  STATUTID NOT IN (1,8,33,34) AND INTERLOCUTEURID IN (  SELECT INTERLOCUTEURID FROM #MYINTERLOCUTEUR)
	END
	IF @INTSESVISITES<>'' AND (@INTANONYMEVISITES='' OR @INTANONYMEVISITES IS NULL)   BEGIN
		DELETE FROM VISITES WHERE  STATUTID NOT IN (1,8,33,34) AND INTERLOCUTEURID IN ( SELECT INTERLOCUTEURID FROM #MYINTERLOCUTEUR )
	END
	DELETE FROM VISITE_ACTION WHERE (SELECT COUNT(VISITEID) FROM VISITES WHERE VISITEID=VISITE_ACTION.VISITEID)=0
	DELETE FROM VISITE_REGLE WHERE (SELECT COUNT(VISITEID) FROM VISITES WHERE VISITEID=VISITE_REGLE.VISITEID)=0

	DELETE FROM LGPARTICIPANT WHERE INTERLOCUTEURID IN (SELECT INTERLOCUTEURID FROM #MYINTERLOCUTEUR)

	DELETE FROM IDENTITES WHERE  INTERLOCUTEURID IN ( SELECT INTERLOCUTEURID FROM #MYINTERLOCUTEUR )
	DELETE FROM XANNEXE WHERE ORIGINE='INTERLOCUTEUR' AND ORIGINEID IN (SELECT INTERLOCUTEURID FROM #MYINTERLOCUTEUR)
	DELETE FROM INTER_ACTION WHERE (SELECT COUNT(INTERLOCUTEURID) FROM INTERLOCUTEUR WHERE INTERLOCUTEURID=INTER_ACTION.INTERLOCUTEURID)=0
	DELETE FROM INTERLOCUTEUR  WHERE INTERLOCUTEURID IN ( SELECT INTERLOCUTEURID FROM #MYINTERLOCUTEUR )

	IF @INTSESCOLIS<>'' AND @INTSESCOLIS IS NOT NULL BEGIN
		DELETE FROM COLISEMIS WHERE INTERLOCUTEURID IN ( SELECT INTERLOCUTEURID FROM #MYINTERLOCUTEUR )
		DELETE FROM COLISRECU WHERE INTERLOCUTEURID IN ( SELECT INTERLOCUTEURID FROM #MYINTERLOCUTEUR )
	END
	IF(@INTSESCONSIGNESETMESSAGES<>'')BEGIN
		DELETE FROM CONSIGNE WHERE INTERLOCUTEURID IN ( SELECT INTERLOCUTEURID FROM #MYINTERLOCUTEUR )
	END
	IF @INTSESCOURSTAXIS<>'' AND @INTSESCOURSTAXIS IS NOT NULL BEGIN
	DELETE FROM COURSE WHERE ID_COURSE IN (SELECT ID_COURSE FROM PASSAGERTAXI WHERE INTERLOCUTEURID IN ( SELECT INTERLOCUTEURID FROM #MYINTERLOCUTEUR ))
	DELETE FROM PASSAGERTAXI WHERE INTERLOCUTEURID IN ( SELECT INTERLOCUTEURID FROM #MYINTERLOCUTEUR )

	END

	SELECT RESIDANTID INTO #MYRESIDANT
	   FROM RESIDANTS
		WHERE
		(RESIDANTID<>'VPARDEFAUT') AND
		((@RESNONMAJNBJOURS<>'' AND @RESNONMAJNBJOURS IS NOT NULL AND DATEMAJ<CURRENT_TIMESTAMP-CAST(@RESNONMAJNBJOURS AS INT)) OR
		(@RESNONMAJDATE <>'' AND @RESNONMAJDATE IS NOT NULL AND DATEDIFF(D,DATEMAJ,CAST(@RESNONMAJDATE AS DATETIME))<0) OR
		(@RESNONACTIF<>'' AND @RESNONACTIF IS NOT NULL AND ISACTIF='0')
		AND (
		(@INTNONINTERDIT<>'' AND @INTNONINTERDIT IS NOT NULL)
			OR
			(
			(@INTNONINTERDIT='' OR @INTNONINTERDIT IS  NULL) AND (INTERDIT='0' OR INTERDIT IS NULL)
			)
		))

			DELETE FROM HVISITES WHERE  RESIDANTID IN (SELECT RESIDANTID FROM #MYRESIDANT)
			DELETE FROM HVISITES WHERE  RESIDANTID IN (SELECT RESIDANTID FROM #MYRESIDANT)
			DELETE FROM PASSAGER WHERE  RESIDANTID IN (SELECT RESIDANTID FROM #MYRESIDANT)
			DELETE FROM PASSAGERTAXI WHERE RESIDANTID IN (SELECT RESIDANTID FROM #MYRESIDANT)
			DELETE FROM LGPARTICIPANT WHERE  RESIDANTID IN (SELECT RESIDANTID FROM #MYRESIDANT)
			DELETE FROM HLGPARTICIPANT WHERE RESIDANTID IN (SELECT RESIDANTID FROM #MYRESIDANT)
			DELETE FROM SECRETARIAT WHERE RESIDANTID IN (SELECT RESIDANTID FROM #MYRESIDANT) OR RESIDANTID2 IN (SELECT RESIDANTID FROM #MYRESIDANT)
			DELETE FROM LIEUPERMIS WHERE  RESIDANTID IN (SELECT RESIDANTID FROM #MYRESIDANT)
			DELETE FROM USERS WHERE EXTERNALID IN (SELECT RESIDANTID FROM #MYRESIDANT)
			DELETE FROM VEHICULE WHERE  RESIDANTID IN (SELECT RESIDANTID FROM #MYRESIDANT)
			DELETE FROM COLISEMIS WHERE  RESIDANTID IN (SELECT RESIDANTID FROM #MYRESIDANT)
			DELETE FROM COLISRECU WHERE  RESIDANTID IN (SELECT RESIDANTID FROM #MYRESIDANT)
			DELETE FROM CONSIGNE WHERE RESIDANTID IN (SELECT RESIDANTID FROM #MYRESIDANT)
			DELETE FROM EVENEMENTCOLIS WHERE  RESIDANTID IN (SELECT RESIDANTID FROM #MYRESIDANT)
			DELETE FROM FACTURE WHERE  RESIDANTID IN (SELECT RESIDANTID FROM #MYRESIDANT)
			DELETE FROM DROITS WHERE  RESIDANTID IN (SELECT RESIDANTID FROM #MYRESIDANT)
			DELETE FROM VEHICULE_DEMANDE WHERE  RESIDANTID IN (SELECT RESIDANTID FROM #MYRESIDANT)
			DELETE FROM INTER_RSERVICE WHERE  RESIDANTID IN (SELECT RESIDANTID FROM #MYRESIDANT)

			IF   (@RESSESVISITES IS NOT NULL AND @RESSESVISITES<>'')  BEGIN
					DELETE FROM VISITE_CONTROLE WHERE RESIDANTID IN (SELECT RESIDANTID FROM #MYRESIDANT)
					DELETE FROM VISITES_RESIDANTS WHERE RESIDANTID IN (SELECT RESIDANTID FROM #MYRESIDANT)
					DELETE FROM VISITES_TEMP WHERE RESIDANTID IN (SELECT RESIDANTID FROM #MYRESIDANT)
					DELETE FROM ZCL01_VISITERE WHERE RESIDANTID IN (SELECT RESIDANTID FROM #MYRESIDANT)
					DELETE FROM VISITES WHERE RESIDANTID IN (SELECT RESIDANTID FROM #MYRESIDANT)

			END ELSE BEGIN
					UPDATE VISITE_CONTROLE  SET RESIDANTID='VPARDEFAUT'  WHERE RESIDANTID IN (SELECT RESIDANTID FROM #MYRESIDANT)
					UPDATE VISITES_RESIDANTS  SET RESIDANTID='VPARDEFAUT'  WHERE RESIDANTID IN (SELECT RESIDANTID FROM #MYRESIDANT) ;
					UPDATE VISITES_TEMP  SET RESIDANTID='VPARDEFAUT'  WHERE RESIDANTID IN (SELECT RESIDANTID FROM #MYRESIDANT)
					UPDATE ZCL01_VISITERE  SET RESIDANTID='VPARDEFAUT'  WHERE RESIDANTID IN (SELECT RESIDANTID FROM #MYRESIDANT)
					UPDATE VISITES SET RESIDANTID='VPARDEFAUT', NOMPRENOMRESID=(SELECT NOM+' '+PRENOM FROM RESIDANTS WHERE RESIDANTID='VPARDEFAUT') WHERE RESIDANTID IN (SELECT RESIDANTID FROM #MYRESIDANT)
			END

	DELETE FROM RESIDANTS WHERE RESIDANTID IN (SELECT RESIDANTID FROM #MYRESIDANT) AND RESIDANTID NOT IN (SELECT RESIDANTID FROM VISITES)
	DELETE FROM VALIDATION_ENQUETE WHERE VISITEID NOT IN (SELECT VISITEID FROM VISITES)
	DELETE FROM VISITE_REGLE WHERE VISITEID NOT IN (SELECT VISITEID FROM VISITES)
	DELETE FROM TACHE WHERE @TACEXECUTEOUINACTIVE<>'' AND @TACEXECUTEOUINACTIVE IS NOT NULL AND ACTIF<0
	DELETE FROM CFG_FICHIER WHERE  @TACSESCONFIGS<>'' AND CFG_FICHIERID IN (SELECT ACT_PARAM FROM TACHE WHERE @TACEXECUTEOUINACTIVE<>'' AND @TACEXECUTEOUINACTIVE IS NOT NULL AND ACTIF<0)
	DELETE FROM TACHE_LOG WHERE @TALPURGE<>''
	DELETE FROM MAIL WHERE STATUT<>-1 AND @MAIENVOYE<>''
	DELETE FROM AGENDA_JOUR2 WHERE STATUT=5 AND (@AJ2TERMINE<>'')
	DELETE FROM COLISEMIS WHERE  (@COLCOLIS<>'')
	DELETE FROM COLISRECU WHERE  (@COLCOLIS<>'')
	DELETE FROM CONSIGNE WHERE TYPECONSIGNE='MESSAGES' AND DATELU IS NOT NULL AND (@CONSUPMESSAGESLUS<>'')
	DELETE FROM SOCIETE WHERE (@SOCNONUTILISE<>'') AND SOCIETEID IN ( SELECT SOCIETEID FROM SOCIETE I WHERE
	 0=(SELECT COUNT(SOCIETEID) FROM INTERLOCUTEUR WHERE SOCIETEID=I.SOCIETEID) AND 0=(SELECT COUNT(SOCIETEID) FROM RESIDANTS WHERE SOCIETEID=I.SOCIETEID)) AND SOCIETEID<>'VPARDEFAUT'
	DELETE FROM RESERVATION WHERE CODERESERVATION IN (SELECT CODERESERVATION FROM LGRESERVATION WHERE CODERESERVATION IN (SELECT CODELGRESERVATION
	   FROM LGRESERVATION
	   WHERE
		(@LGRTERMINEEDEPUISNBJOURS<>'' AND @LGRTERMINEEDEPUISNBJOURS IS NOT NULL AND DATEADD(DD, CAST(@LGRTERMINEEDEPUISNBJOURS AS INT),CONVERT(DATETIME,DATEFIN,103))<CONVERT(DATETIME,CURRENT_TIMESTAMP,103)))
		OR
		(@LGRTERMINEEDEPUISDATE<>'' AND @LGRTERMINEEDEPUISDATE IS NOT NULL AND CONVERT(DATETIME,DATEFIN,103)<CONVERT(DATETIME,@LGRTERMINEEDEPUISDATE,103)))

	DELETE FROM LGRESERVATION WHERE  CODELGRESERVATION IN (SELECT CODELGRESERVATION
	   FROM LGRESERVATION
	   WHERE
		(@LGRTERMINEEDEPUISNBJOURS<>'' AND @LGRTERMINEEDEPUISNBJOURS IS NOT NULL AND DATEADD(DD, CAST(@LGRTERMINEEDEPUISNBJOURS AS INT),CONVERT(DATETIME,DATEFIN,103))<CONVERT(DATETIME,CURRENT_TIMESTAMP,103)))
		OR
		(@LGRTERMINEEDEPUISDATE<>'' AND @LGRTERMINEEDEPUISDATE IS NOT NULL AND CONVERT(DATETIME,DATEFIN,103)<CONVERT(DATETIME,@LGRTERMINEEDEPUISDATE,103))
	SET @NBRESPURGE=(SELECT COUNT(*) FROM #MYRESIDANT)
	SET @NBINTPURGE=(SELECT COUNT(*) FROM #MYINTERLOCUTEUR)
	SET @NBPURGE=@NBINTPURGE+@NBRESPURGE+@NBVISPURGE;
	SET @ID=SUBSTRING(CAST (@NBPURGE AS VARCHAR)+','+CAST(@NBRESPURGE AS VARCHAR)+','+CAST( @NBINTPURGE AS VARCHAR)+','+CAST (@NBVISPURGE AS VARCHAR),0,17)
	DROP TABLE #MYINTERLOCUTEUR
	DROP TABLE #MYRESIDANT
END