CREATE PROCEDURE [dbo].[PS_MAJ_LGRESA]

    @codelgreservation VARCHAR(14),
    @porte_code VARCHAR(50)
AS

BEGIN
	IF EXISTS (SELECT * FROM LGRESERVATION WHERE CODELGRESERVATION = @codelgreservation) BEGIN

        UPDATE LGRESERVATION SET PORTE_CODE=@porte_code WHERE CODELGRESERVATION = @codelgreservation
		RETURN @@ROWCOUNT
	END ELSE BEGIN
      RETURN -1
    END
END