CREATE PROCEDURE [dbo].[PS_NATURE]
	@FLAGIN INT,
	@CHAMPCTRL VARCHAR(80),
	@LIBELLE VARCHAR(35),
	@ABREGE VARCHAR(6),
	@TVISITE VARCHAR(1),
	@INTERDIT VARCHAR(1),
	@ID VARCHAR(18) OUTPUT
AS
	DECLARE @FLAG VARCHAR(14)
	DECLARE @IDENTITY VARCHAR(14)
	DECLARE @INTERD VARCHAR(1)
BEGIN


	IF EXISTS (SELECT * FROM NATURE WHERE NATUREID = @LIBELLE) BEGIN
		SET @ID = @LIBELLE + ',0,0'
	END
	ELSE BEGIN
		IF (@LIBELLE IS NULL) OR LTRIM(@LIBELLE) = '' BEGIN
			SET @ID = 'VPARDEFAUT,0,0'

		END
		ELSE BEGIN
				SET @LIBELLE = UPPER(@LIBELLE)
				IF EXISTS (SELECT * FROM NATURE WHERE UPPER(LIBELLE) = @LIBELLE) BEGIN
					SET @ID = (SELECT TOP 1 NATUREID FROM NATURE WHERE LIBELLE = @LIBELLE)
					SET @ID = @ID + ',0,0'
				END	ELSE BEGIN
					IF (@FLAGIN=1) BEGIN
						INSERT INTO SEQ_IDENTITY(LIBELLE) VALUES ('OK')
						SET @IDENTITY = (SELECT @@IDENTITY AS ID)
						SET @FLAG = (SELECT SUBSTRING(VERSION, 1, 3) FROM VERSION_SFW)
						SET @ID = @FLAG + @IDENTITY

						SET @INTERD = @INTERDIT
						IF (@INTERD IS NULL) OR LTRIM(@INTERD) = '' BEGIN
							SET @INTERD = 0
						END

						INSERT INTO NATURE(NATUREID, LIBELLE,ABREGE,TVISITE, INTERDIT, DEBUTINTERDIT, FININTERDIT, DATECREATION, DATEMAJ)
							VALUES(@ID, @LIBELLE,@ABREGE,@TVISITE,@INTERD, CONVERT(DATETIME,CONVERT(VARCHAR,CURRENT_TIMESTAMP,103),103) , CURRENT_TIMESTAMP + 36525, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
						SET @ID = @ID + ',1,0'
					END
					ELSE BEGIN
						SET @ID = 'VPARDEFAUT,0,0'
					END
				END
		END
	END
END