CREATE PROCEDURE [dbo].[PS_PAYS]

	@FLAGIN INT,
	@CHAMPCTRL NVARCHAR(80),

	@LIBELLE NVARCHAR(35),
	@LIBELLEGR NVARCHAR(50),

	@LIBELLEUS NVARCHAR(35),
	@NATIONALITE NVARCHAR(50),
	@CODEISO1 NVARCHAR(2),
	@CODEISO2 NVARCHAR(3),
	@CODEISO3 NVARCHAR(3),
	@INDICATIF NVARCHAR(5),
	@SHORTLIB NVARCHAR(3),
	@DEVISE NVARCHAR(3),
	@DEVISELIBELLE NVARCHAR(35),
	@INTERDIT NVARCHAR(1),
	@DEBUTINTERDIT DATETIME,
	@FININTERDIT DATETIME,

	@ENQUETE1 NVARCHAR(10),
	@STATUT1 NVARCHAR(10),
	@ENQUETE2 NVARCHAR(10),
	@STATUT2 NVARCHAR(10),
	@ENQUETE3 NVARCHAR(10),
	@STATUT3 NVARCHAR(10),
	@ID NVARCHAR(18) OUTPUT
AS
	DECLARE @FLAG NVARCHAR(14)
	DECLARE @IDENTITY NVARCHAR(14)
BEGIN
	IF EXISTS (SELECT * FROM PAYS WHERE PAYSID =
				CASE
					WHEN @CHAMPCTRL = 'LIBELLE' THEN @LIBELLE
					WHEN @CHAMPCTRL = 'LIBELLEGR' THEN @LIBELLEGR
					ELSE @LIBELLE
				END
	) BEGIN
		SET @ID = CASE
					WHEN @CHAMPCTRL = 'LIBELLE' THEN @LIBELLE
					WHEN @CHAMPCTRL = 'LIBELLEGR' THEN @LIBELLEGR
					ELSE @LIBELLE
				END
		SET @ID = @ID + ',0,0'
	END
	ELSE BEGIN
		IF (@LIBELLE IS NULL) OR LTRIM(@LIBELLE) = '' BEGIN
			SET @ID = 'VPARDEFAUT,0,0'
		END
		ELSE BEGIN
			SET @LIBELLE = UPPER(@LIBELLE)
			IF EXISTS (SELECT * FROM PAYS WHERE UPPER(LIBELLE) = UPPER(@LIBELLE)) BEGIN
				SET @ID = (SELECT TOP 1 PAYSID FROM PAYS WHERE UPPER(LIBELLE) = UPPER(@LIBELLE))
				UPDATE PAYS SET LIBELLE = @LIBELLE, LIBELLEGR = @LIBELLEGR, LIBELLEUS = @LIBELLEUS, NATIONALITE = @NATIONALITE, CODEISO2 = @CODEISO2, CODEISO3 = @CODEISO3, INDICATIF = @INDICATIF, DEVISELIBELLE = @DEVISELIBELLE, DATEMAJ = CURRENT_TIMESTAMP WHERE PAYSID = @ID
				SET @ID = @ID + ',0,1'
			END
			ELSE BEGIN
				IF EXISTS (SELECT * FROM PAYS WHERE UPPER(NATIONALITE) = UPPER(@NATIONALITE)) BEGIN
					SET @ID = (SELECT TOP 1 PAYSID FROM PAYS WHERE UPPER(NATIONALITE) = UPPER(@NATIONALITE))
					SET @ID = @ID + ',0,0'
				END
				ELSE BEGIN
					IF EXISTS (SELECT TOP 1 PAYSID FROM PAYS WHERE UPPER(LIBELLE) ='INCONNU') BEGIN
						SET @ID = (SELECT TOP 1 PAYSID FROM PAYS WHERE UPPER(LIBELLE) ='INCONNU')
						SET @ID = @ID + ',0,0'
					END
					ELSE BEGIN
						IF @FLAGIN=1 BEGIN
							INSERT INTO SEQ_IDENTITY(LIBELLE) VALUES ('OK')
							SET @IDENTITY = (SELECT @@IDENTITY AS ID)
							SET @FLAG = (SELECT SUBSTRING(VERSION, 1, 3) FROM VERSION_SFW)
							SET @ID = @FLAG + @IDENTITY
							INSERT INTO PAYS (PAYSID, LIBELLE, LIBELLEGR, LIBELLEUS, NATIONALITE, CODEISO1,CODEISO2, CODEISO3, INDICATIF, SHORTLIB,DEVISE,DEVISELIBELLE,INTERDIT, DEBUTINTERDIT, FININTERDIT, ENQUETE1,STATUT1,ENQUETE2,STATUT2,ENQUETE3,STATUT3,DATECREATION, DATEMAJ)
							VALUES(@ID, @LIBELLE, @LIBELLEGR,@LIBELLEUS, @NATIONALITE, @CODEISO1,@CODEISO2, @CODEISO3,@INDICATIF,@SHORTLIB,@DEVISE,@DEVISELIBELLE,0, CONVERT(DATETIME,CONVERT(VARCHAR,CURRENT_TIMESTAMP,103),103) , CURRENT_TIMESTAMP + 36525, @ENQUETE1,@STATUT1,@ENQUETE2,@STATUT2,@ENQUETE3,@STATUT3,CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
							SET @ID = @ID + ',1,0'
						END
						ELSE
						SET @ID='VPARDEFAUT,0,0'
					END
				END
			END
		END
	END
END