CREATE PROCEDURE [dbo].[PS_REORDER_SITE]
AS
	DECLARE @siteid varchar(14)
BEGIN
	DECLARE CURSEUR CURSOR
	FOR SELECT SITEID FROM SITE WHERE (SORTORDER='' OR SORTORDER IS NULL)

	OPEN CURSEUR
	FETCH NEXT FROM CURSEUR
	INTO @siteid

	WHILE @@FETCH_STATUS = 0
	BEGIN
		UPDATE SITE SET SORTORDER=(SELECT (ISNULL(MAX(SORTORDER),0))+1 FROM SITE) WHERE SITEID=@siteid;
		FETCH NEXT FROM CURSEUR
		INTO @siteid
	END
	CLOSE CURSEUR
	DEALLOCATE CURSEUR
END