CREATE PROCEDURE [dbo].[PS_REGLE_ZONE_ACCES]
		@MYVISITEID NVARCHAR(14),
	@MYREGLEID INT,
	@MYACTION  INT OUTPUT,
	@MYMESSAGE  NVARCHAR(500) OUTPUT,
	@MYACTIONBLOQUANTE  INT OUTPUT
AS
BEGIN
	SET @MYACTION=0
	SET @MYMESSAGE=''
	IF  EXISTS (SELECT REGLEID FROM REGLES TREG WHERE TREG.REGLEID=@MYREGLEID  AND TREG.FREE1=(SELECT TOP (1) BATIMENTID FROM BATIMENT WHERE LIBELLE =(SELECT LIEU FROM VISITES WHERE VISITEID=@MYVISITEID)) )
	BEGIN
		EXEC PS_REGLES_EXEC_ACTIONS @MYREGLEID,@MYVISITEID
		SET @MYACTION=(SELECT TYPEACTION FROM REGLES WHERE REGLEID=@MYREGLEID )
		SET @MYMESSAGE=(SELECT MESSAGE FROM REGLES WHERE REGLEID=@MYREGLEID)
		SET @MYACTIONBLOQUANTE=(SELECT ACTIONBLOQUANTE FROM REGLES WHERE REGLEID=@MYREGLEID)
	END
END