CREATE PROCEDURE [dbo].[PS_SECRETARIAT]

	@IDRES NVARCHAR(14),
	@IDRESAJOINDRE NVARCHAR(14),
	@insertion int output

AS

BEGIN

	IF not EXISTS (SELECT * FROM SECRETARIAT WHERE RESIDANTID = @IDRES and RESIDANTID2 = @IDRESAJOINDRE) BEGIN
		INSERT INTO SECRETARIAT(RESIDANTID,RESIDANTID2,RELATION,DATECREATION,DATEMAJ)
		VALUES(@IDRES,@IDRESAJOINDRE,'A JOINDRE',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP)
		SET @insertion = @insertion+1
	END

END