CREATE PROCEDURE [dbo].[PS_SORTIE_VISITES_RESIDANTS]
AS
BEGIN
 UPDATE VISITES_RESIDANTS SET SORTIE=GETDATE(), OBSERVATION=OBSERVATION + ' | Sortie automatique', DATEMAJ=GETDATE(), DATESYNCHRO=GETDATE(), GUICHET_S='TLMQ SERVEUR' WHERE SORTIE IS NULL
END