CREATE PROCEDURE [dbo].[PS_SOCIETE]
	@FLAGIN INT,
	@CHAMPCTRL NVARCHAR(80),
	@NATUREID NVARCHAR(14),
	@NOM NVARCHAR(35),
	@SIRET NVARCHAR(20),
	@DEPARTEMENT NVARCHAR(35),
	@ADRESSE2 NVARCHAR(150),
	@CP NVARCHAR(10),
	@VILLE NVARCHAR(35),
	@PAYS NVARCHAR(50),
	@PROVINCE NVARCHAR(35),
	@TELEPHONE NVARCHAR(20),
	@FAX NVARCHAR(20),
	@EMAIL NVARCHAR(150),
	@WEB NVARCHAR(50),
	@ISRESIDANT NVARCHAR(1),

	@ID NVARCHAR(18) OUTPUT
AS
	DECLARE @NBUPDATE INT
	DECLARE @NBINSERT INT
	DECLARE @FLAG NVARCHAR(14)
	DECLARE @IDENTITY NVARCHAR(14)

	DECLARE @INTERDIT INT
	DECLARE @EXTERNALID NVARCHAR(24)
BEGIN
	SET @NBUPDATE =0
	SET @NBINSERT =0
	SET @INTERDIT= 0
	SET @EXTERNALID= 'VPARDEFAUT'
	IF EXISTS (SELECT * FROM SOCIETE WHERE (SOCIETEID = @NOM OR NOM=@NOM) AND ISRESIDANT=@ISRESIDANT) BEGIN
		SET @ID = (SELECT TOP 1 SOCIETEID FROM SOCIETE WHERE (SOCIETEID = @NOM OR NOM=@NOM) AND ISRESIDANT=@ISRESIDANT) + ',0,0'
	END
	ELSE BEGIN
		IF (@NOM IS NULL) OR LTRIM(@NOM) IS NULL OR LTRIM(@NOM) = '' BEGIN
			SET @ID = 'VPARDEFAUT,0,0'
		END
		ELSE BEGIN
			--SET @NOM = UPPER(@NOM)

			IF(@FLAGIN=1)BEGIN

				EXEC PS_NATURE 1,'',@NATUREID,'','','',@NATUREID OUTPUT

				SET @NBUPDATE = @NBUPDATE + CAST( (SELECT [DATA] FROM SPLIT(@NATUREID,',') WHERE [ID] = 3) AS INT)
				SET @NBINSERT = @NBINSERT + CAST( (SELECT [DATA] FROM SPLIT(@NATUREID,',') WHERE [ID] = 2) AS INT)
				SET @NATUREID = (SELECT [DATA] FROM SPLIT(@NATUREID,',') WHERE [ID] = 1)

				IF EXISTS (SELECT * FROM SOCIETE WHERE UPPER(NOM) = UPPER(@NOM) AND ISRESIDANT=@ISRESIDANT) BEGIN
					SET @ID = (SELECT TOP 1 SOCIETEID FROM SOCIETE WHERE UPPER(NOM) = UPPER(@NOM) AND ISRESIDANT=@ISRESIDANT)
					UPDATE SOCIETE SET SIRET = @SIRET, DEPARTEMENT = @DEPARTEMENT, ADRESSE2 = @ADRESSE2, CP = @CP, VILLE = @VILLE, PAYS = @PAYS, NATUREID = @NATUREID, TELEPHONE = @TELEPHONE, FAX = @FAX, EMAIL = @EMAIL, WEB = @WEB,PROVINCE = @PROVINCE WHERE SOCIETEID = @ID
					SET @ID = @ID + ',' + CAST(@NBINSERT AS VARCHAR) + ',' + CAST(@NBUPDATE+1 AS VARCHAR)
				END
				ELSE BEGIN

					INSERT INTO SEQ_IDENTITY(LIBELLE) VALUES ('OK')
					SET @IDENTITY = (SELECT @@IDENTITY AS ID)
					SET @FLAG = (SELECT SUBSTRING(VERSION, 1, 3) FROM VERSION_SFW)
					SET @ID =@FLAG + @IDENTITY

					INSERT INTO SOCIETE(SOCIETEID, NOM, INTERDIT, ISRESIDANT,EXTERNALID, DEBUTINTERDIT, FININTERDIT, DATECREATION, DATEMAJ,FAX,EMAIL,WEB,NATUREID,ADRESSE2,CP,VILLE,PAYS,PROVINCE,TELEPHONE)
						VALUES(@ID, @NOM, @INTERDIT,@ISRESIDANT,@EXTERNALID, CURRENT_TIMESTAMP - 1, CURRENT_TIMESTAMP + 36525, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP,@FAX,@EMAIL,@WEB,@NATUREID,@ADRESSE2,@CP,@VILLE,@PAYS,@PROVINCE,@TELEPHONE)
					SET @NBINSERT=@NBINSERT+1
					SET @ID = @ID + ',' + CAST(@NBINSERT AS VARCHAR) + ',' + CAST(@NBUPDATE AS VARCHAR)

				END
			END
			ELSE BEGIN
				SET @ID = 'VPARDEFAUT,' + CAST(@NBINSERT AS VARCHAR) + ',' + CAST(@NBUPDATE AS VARCHAR)
			END
		END
	END
END