CREATE PROCEDURE [dbo].[PS_SETRESA]
    @SALLEID NVARCHAR(30),
    @DEBUTRESA DATETIME,
    @FINRESA DATETIME,
	@LIBELLE NVARCHAR(35),
	@THELOGIN NVARCHAR(50),
	@SITELIB NVARCHAR(50),
	@REFRESERVATION NVARCHAR(30),
    @ID NVARCHAR(18) OUTPUT
AS
    DECLARE @FLAG NVARCHAR(14)
    DECLARE @IDENTITY NVARCHAR(14)
    DECLARE @NOMPRENOM NVARCHAR(30)
    DECLARE @SOCIETE NVARCHAR(30)
    DECLARE @CODEANIMATEUR NVARCHAR(30)
    DECLARE @SOCIETEID NVARCHAR(30)
    DECLARE @INTERLOCUTEURID NVARCHAR(30)
    DECLARE @CODESTATUT NVARCHAR(30)
    DECLARE @DATECREATION NVARCHAR(30)

    DECLARE @CODERESERVATION NVARCHAR(30)
    DECLARE @CODELGRESERVATION NVARCHAR(30)
    DECLARE @USERID NVARCHAR(30)
    DECLARE @DATEDEBUT DATETIME
    DECLARE @HEUREDEBUT DATETIME
	DECLARE @DATEFIN DATETIME
    DECLARE @HEUREFIN DATETIME
    DECLARE @CODESALLE NVARCHAR(30)
    DECLARE @LIBELLESALLE NVARCHAR(30)
    DECLARE @NOSALLE NVARCHAR(30)
    DECLARE @COMMENTAIRE NVARCHAR(30)
    DECLARE @EMETTEUR NVARCHAR(150)
	DECLARE @CODEAMENAGEMENT NVARCHAR(15)
BEGIN
    SET @CODEANIMATEUR= (SELECT TOP 1 RESIDANTID FROM RESIDANTS WHERE @THELOGIN=THELOGIN)
	SET @EMETTEUR= (SELECT TOP 1 NOMPRENOM FROM RESIDANTS WHERE @THELOGIN=THELOGIN)
    SET @SOCIETEID = (SELECT TOP 1 SOCIETEID FROM RESIDANTS WHERE RESIDANTID = @CODEANIMATEUR)
    SET @INTERLOCUTEURID= (SELECT TOP 1 RESIDANTID FROM RESIDANTS WHERE @THELOGIN=THELOGIN)
    SET @CODESTATUT= (SELECT TOP 1 CODESTATUT FROM STATUTRESERVATION WHERE CODESTATUT='VPARDEFAUT')
    SET @USERID= (SELECT TOP 1 USERID FROM USERS WHERE UPPER(THELOGIN)='INTRANET_'+@SITELIB)
    SET @CODEAMENAGEMENT = (SELECT CODEAMENAGEMENT FROM AMENAGSALLE WHERE CODESALLE=@SALLEID)
    INSERT INTO SEQ_IDENTITY(LIBELLE) VALUES ('OK')
    SET @IDENTITY = (SELECT @@IDENTITY AS ID)
    SET @FLAG = (SELECT SUBSTRING(VERSION, 1, 3) FROM VERSION_SFW)
    SET @CODERESERVATION = @FLAG + @IDENTITY
    --SET @REFRESERVATION=@CODERESERVATION

    SET @COMMENTAIRE='PS'

    INSERT INTO RESERVATION (CODERESERVATION,CODETYPERESERVATION,SOCIETEID,INTERLOCUTEURID,USERID,CODEANIMATEUR,CODESTATUT,REFRESERVATION,NBPERSDEMANDE,IMPUTATIONID,SALLE_VALIDEE,LIBELLE,EMETTEUR,COMMENTAIRE,DATECREATION,DATEMAJ) VALUES (@CODERESERVATION,'VPARDEFAUT',@SOCIETEID,@INTERLOCUTEURID,@USERID,@CODEANIMATEUR,@CODESTATUT,@REFRESERVATION,1,'VPARDEFAUT',0,@LIBELLE,@EMETTEUR,@COMMENTAIRE,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP)


    SET @LIBELLESALLE=(SELECT TOP 1 LIBELLE FROM SALLE WHERE CODESALLE=@SALLEID)
    SET @NOSALLE=(SELECT TOP 1 NOSALLE FROM SALLE WHERE CODESALLE=@SALLEID)

	INSERT INTO SEQ_IDENTITY(LIBELLE) VALUES ('OK')
    SET @IDENTITY = (SELECT @@IDENTITY AS ID)
    SET @FLAG = (SELECT SUBSTRING(VERSION, 1, 3) FROM VERSION_SFW)
    SET @CODELGRESERVATION = @FLAG + @IDENTITY
	--INSERT INTO ALARME (ALARMEID,LIBELLE,DATEMAJ,DATECREATION) VALUES(@IDENTITY,'0',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP)
    SET @DATEDEBUT=CONVERT(DATETIME,CONVERT(VARCHAR(10),@DEBUTRESA,120)+' 00:00:00', 120)
	--INSERT INTO ALARME (ALARMEID,LIBELLE,DATEMAJ,DATECREATION) VALUES(@IDENTITY+1,CONVERT(VARCHAR,@DATEDEBUT,102),CURRENT_TIMESTAMP,CURRENT_TIMESTAMP)
    SET @HEUREDEBUT=CONVERT(DATETIME, '1900-01-01 ' +CONVERT(VARCHAR,@DEBUTRESA,108), 120)
	--INSERT INTO ALARME (ALARMEID,LIBELLE,DATEMAJ,DATECREATION) VALUES(@IDENTITY+2,CONVERT(VARCHAR,@HEUREDEBUT,102),CURRENT_TIMESTAMP,CURRENT_TIMESTAMP)
	SET @DATEFIN =CONVERT(DATETIME, CONVERT(VARCHAR(10),@FINRESA,120)+' 00:00:00', 120)
	--INSERT INTO ALARME (ALARMEID,LIBELLE,DATEMAJ,DATECREATION) VALUES(@IDENTITY+3,CONVERT(VARCHAR,@DATEFIN,102),CURRENT_TIMESTAMP,CURRENT_TIMESTAMP)
    SET @HEUREFIN = CONVERT(DATETIME, '1900-01-01 ' +CONVERT(VARCHAR,@FINRESA,108), 120)
   -- INSERT INTO ALARME (ALARMEID,LIBELLE,DATEMAJ,DATECREATION) VALUES(@IDENTITY+4,CONVERT(VARCHAR,@HEUREFIN,102),CURRENT_TIMESTAMP,CURRENT_TIMESTAMP)


    INSERT INTO LGRESERVATION (CODERESERVATION,CODESALLE,CODESTATUT,CODELGRESERVATION,CODEAMMENAGEMENT,DATEDEBUT,DATEFIN,HEUREDEBUT,HEUREFIN,HEURECONTINU,LIBELLESALLE,NOSALLE,DATECREATION,DATEMAJ) VALUES
    (@CODERESERVATION,@SALLEID,@CODESTATUT,@CODELGRESERVATION,@CODEAMENAGEMENT,@DATEDEBUT,@DATEFIN,@HEUREDEBUT,@HEUREFIN,1,@LIBELLESALLE,@NOSALLE,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP)

    SET @ID=@CODELGRESERVATION
END