CREATE PROCEDURE [dbo].[PS_TACHE_UPDOWN]
@UPDOWN_ID INT,
@SENS NVARCHAR(14)
AS
DECLARE @rg INT
DECLARE @rulecount INT
BEGIN
 SET @rulecount=(SELECT COUNT(*) FROM TACHE WHERE ACTIF<>-2 )

 SET @rg = (SELECT TACHE_RANG FROM TACHE WHERE TACHEID=@UPDOWN_ID )

 IF (@SENS='UP') AND (@rg>0)  BEGIN
    UPDATE TACHE SET TACHE_RANG=@rg WHERE TACHE_RANG=@rg-1
    UPDATE TACHE SET TACHE_RANG=@rg-1 WHERE TACHEID=@UPDOWN_ID
 END
 ELSE IF (@SENS='DOWN') AND (@rg<@rulecount-1)
 BEGIN
   UPDATE TACHE SET TACHE_RANG=@rg WHERE TACHE_RANG=@rg+1
   UPDATE TACHE SET TACHE_RANG=@rg+1 WHERE TACHEID=@UPDOWN_ID
 END
END