CREATE PROCEDURE [dbo].[PS_TAXI_CREATIONCOURSE]
	@USERID NVARCHAR(14),
	@ENLEVEMENTPREVU DATETIME,
	@LIEUDEPART NVARCHAR(40),
	@OBJET NVARCHAR(200),
	@MOYENPAIEMENT NVARCHAR(50),
	@CODECLIENT NVARCHAR(10),
	@IMPUTATION NVARCHAR(35),
	@ID_TYPEVEHICULE INT,
	@SITEID NVARCHAR(14),
	@ID INT OUTPUT
AS
	DECLARE @NOW DATETIME
	DECLARE @SITE NVARCHAR(35)
	DECLARE @EID NVARCHAR(14)
	DECLARE @IMPUTATIONID NVARCHAR(14)
	DECLARE @EVNMT NVARCHAR(200)
	DECLARE @FLAG NVARCHAR(14)
	DECLARE @IDENTITY NVARCHAR(14)
BEGIN
	EXEC PS_TAXI_CREATIONIMPUTATION @IMPUTATION, @IMPUTATIONID OUTPUT

	SET @NOW = CURRENT_TIMESTAMP

	--SET @SITEID = (SELECT SITEID FROM USERS WHERE USERID = @USERID)

	INSERT INTO SEQ_IDENTITY(LIBELLE) VALUES ('OK')
	SET @IDENTITY = (SELECT @@IDENTITY AS ID)
	SET @FLAG = (SELECT SUBSTRING(VERSION, 1, 3) FROM VERSION_SFW)
	SET @ID = CAST(@FLAG AS INT) + CAST(@IDENTITY AS INT)

	INSERT INTO COURSE(ID_COURSE, SITEID, ID_STATUTCOURSE, DATEHEUREDEMANDE, LIEUDEPART, DATEHEUREDEPART, ID_TYPEVEHICULE, OBJET, MOYENPAIEMENT, IMPUTATIONID, CODECLIENT, DATECREATION, DATEMAJ)
		VALUES (@ID, @SITEID, -1, @NOW, @LIEUDEPART, @ENLEVEMENTPREVU, @ID_TYPEVEHICULE, @OBJET, @MOYENPAIEMENT, @IMPUTATIONID, @CODECLIENT, @NOW, @NOW)

	SET @EVNMT = 'CREATION COURSE'
	EXEC PS_TAXI_CREATIONEVENEMENT @ID, @EVNMT, @NOW, @USERID, @EID OUTPUT
END