CREATE PROCEDURE [dbo].[PS_TAXI_CHANGEMENTSTATUTCOURSE]
	@ID_COURSE INT,
	@ID_STATUTCOURSE INT,
	@USERID NVARCHAR(14)
AS
	DECLARE @STATUTCOURSE NVARCHAR(35)
	DECLARE @NOW DATETIME
	DECLARE @EID NVARCHAR(14)
	DECLARE @EVNMT NVARCHAR(200)
BEGIN
	SET @NOW = CURRENT_TIMESTAMP

	UPDATE COURSE SET ID_STATUTCOURSE = @ID_STATUTCOURSE, DATEMAJ = @NOW WHERE ID_COURSE = @ID_COURSE
	SET @STATUTCOURSE = (SELECT LIBELLE FROM STATUTCOURSE WHERE ID_STATUTCOURSE = @ID_STATUTCOURSE)
	SET @EVNMT = 'CHANGEMENT STATUT COURSE A '+@STATUTCOURSE
	EXEC PS_TAXI_CREATIONEVENEMENT @ID_COURSE, @EVNMT, @NOW, @USERID, @EID OUTPUT
END