CREATE PROCEDURE [dbo].[PS_TAXI_ARRIVEETAXI]
	@ID_COURSE INT,
	@USERID NVARCHAR(14)
AS
	DECLARE @NOW DATETIME
	DECLARE @EID NVARCHAR(14)
	DECLARE @EVNMT NVARCHAR(200)
BEGIN
	SET @NOW = CURRENT_TIMESTAMP
	SET @EVNMT = 'ARRIVEE DU TAXI'
	EXEC PS_TAXI_CREATIONEVENEMENT @ID_COURSE, @EVNMT, @NOW, @USERID, @EID OUTPUT

	UPDATE COURSE SET ID_STATUTCOURSE = -3, DATEMAJ = @NOW, DATEHEUREFIN = @NOW WHERE ID_COURSE = @ID_COURSE
END