CREATE PROCEDURE [dbo].[PS_TLQM_VERIF]
AS
BEGIN
	UPDATE SITE SET TLMQ_HEURE_FIN='23:30' WHERE TLMQ_HEURE_FIN=':';
	UPDATE SITE SET TLMQ_HEURE_EXEC='23:00' WHERE TLMQ_HEURE_FIN=':';
	UPDATE SITE SET TLMQ_DERN_EXEC=GETDATE()-1 WHERE TLMQ_DERN_EXEC IS NULL;
END