CREATE PROCEDURE [dbo].[PS_TAXI_REFUSCOURSE]
	@ID_COURSE INT,
	@USERID NVARCHAR(14),
	@ADRESSEID NVARCHAR(14)
AS
	DECLARE @COMPAGNIE NVARCHAR(80)
	DECLARE @NOW DATETIME
	DECLARE @EID NVARCHAR(14)
	DECLARE @EVNMT NVARCHAR(200)
BEGIN
	SET @NOW = CURRENT_TIMESTAMP
	SET @COMPAGNIE = (SELECT SOCIETE FROM ADRESSE WHERE ADRESSEID = @ADRESSEID)
	SET @EVNMT = 'COURSE REFUSEE PAR LA COMPAGNIE '+@COMPAGNIE
	EXEC PS_TAXI_CREATIONEVENEMENT @ID_COURSE, @EVNMT, @NOW, @USERID, @EID OUTPUT
END