CREATE PROCEDURE [dbo].[PS_TAXI_CREATIONPASSAGER]
	@ID_COURSE INT,
	@RESIDANTID NVARCHAR(14),
	@INTERLOCUTEURID NVARCHAR(14),
	@CONTACT NVARCHAR(200),
	@DEMANDEUR NVARCHAR(14),
	@HANDICAP NVARCHAR(200),
	@ANIMAL NVARCHAR(200),
	@ID INT OUTPUT
AS
	DECLARE @ORDRE INT
	DECLARE @FLAG NVARCHAR(14)
	DECLARE @IDENTITY NVARCHAR(14)
BEGIN
	SET @ORDRE = (SELECT MAX(ORDRE) FROM PASSAGERTAXI WHERE ID_COURSE = @ID_COURSE)
	IF @ORDRE IS NULL
		SET @ORDRE = 0
	ELSE
		SET @ORDRE = @ORDRE + 1

	INSERT INTO SEQ_IDENTITY(LIBELLE) VALUES ('OK')
	SET @IDENTITY = (SELECT @@IDENTITY AS ID)
	SET @FLAG = (SELECT SUBSTRING(VERSION, 1, 3) FROM VERSION_SFW)
	SET @ID = CAST(@FLAG AS INT) + CAST(@IDENTITY AS INT)

	INSERT INTO PASSAGERTAXI(ID_PASSAGERTAXI, ID_COURSE, RESIDANTID, INTERLOCUTEURID, CONTACT,DEMANDEUR,HANDICAP, ANIMAL, ORDRE, DATECREATION, DATEMAJ)
		VALUES (@ID, @ID_COURSE, @RESIDANTID, @INTERLOCUTEURID, @CONTACT, @DEMANDEUR,@HANDICAP, @ANIMAL, @ORDRE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
END