CREATE PROCEDURE [dbo].[PS_TAXI_MODIFCOURSE]
	@ID_COURSE INT,
	@USERID NVARCHAR(14),
	@NUMCOURSE NVARCHAR(35),
	@REFERENCESTAXI NVARCHAR(200)
AS
	DECLARE @COMPAGNIE NVARCHAR(80)
	DECLARE @NOW DATETIME
	DECLARE @EID NVARCHAR(14)
	DECLARE @EVNMT NVARCHAR(200)
BEGIN
	SET @NOW = CURRENT_TIMESTAMP

	UPDATE COURSE SET DATEMAJ = @NOW, NUMCOURSE = @NUMCOURSE, REFERENCESTAXI = @REFERENCESTAXI WHERE ID_COURSE = @ID_COURSE
	SET @EVNMT = 'COURSE MODIFIEE'
	EXEC PS_TAXI_CREATIONEVENEMENT @ID_COURSE, @EVNMT, @NOW, @USERID, @EID OUTPUT
END