------------------------------
CREATE PROCEDURE [dbo].[PS_VEHICULE]

	@RESIDANTID VARCHAR(14),
	@IMMATRICULATION VARCHAR(15),
	@MARQUE VARCHAR(20),
	@MODELE VARCHAR(40),
	@DATELIMITE DATETIME,
	@NUMEROPASS VARCHAR(40),
	@ID VARCHAR(18) OUTPUT

AS

	DECLARE @FLAG VARCHAR(14)
	DECLARE @IDENTITY VARCHAR(14)

BEGIN

	IF(EXISTS (SELECT * FROM VEHICULE WHERE IMMATRICULATION = @IMMATRICULATION)) BEGIN
		SET @ID = (SELECT TOP 1 VEHICULEID FROM VEHICULE WHERE IMMATRICULATION = @IMMATRICULATION)
		SET @ID = @ID + ',0,0'
	END
	ELSE BEGIN
		IF LTRIM(@IMMATRICULATION) != '' BEGIN
			INSERT INTO SEQ_IDENTITY(LIBELLE) VALUES ('OK')
			SET @IDENTITY = (SELECT @@IDENTITY AS ID)
			SET @FLAG = (SELECT SUBSTRING(VERSION, 1, 3) FROM VERSION_SFW)
			SET @ID = @FLAG + @IDENTITY

			INSERT INTO VEHICULE(RESIDANTID,IMMATRICULATION,MARQUE,MODELE,DATELIMITE,NUMEROPASS,VEHICULEID,DATECREATION,DATEMAJ) VALUES(@RESIDANTID,@IMMATRICULATION,@MARQUE,@MODELE,@DATELIMITE,@NUMEROPASS,@ID,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP)
			SET @ID = @ID + ',1,0'
		END
		ELSE BEGIN
		SET @ID='-1,0,0'
		END
	END
END