CREATE PROCEDURE [dbo].[PS_VISITES]
	@FLAGIN INT,
	@CHAMPCTRL NVARCHAR(80),
	@NOMINT NVARCHAR(35),
	@PRENOMINT NVARCHAR(35),
	@NOMRES NVARCHAR(35),
	@PRENOMRES NVARCHAR(35),
	@SOCIETERESID NVARCHAR(35),
	@SOCIETEVISIT NVARCHAR(35),
	@IFONCTION NVARCHAR(35),
	@IDATENAISSANCE DATETIME,
	@ILIEUNAISSANCE NVARCHAR(70),
	@IPAYS NVARCHAR(35),
	@INOMJEUNEFILLE NVARCHAR(35),
	@VIP INT,
	@ISTATUT NVARCHAR(35),
	@DEBUTPREVU DATETIME,
	@FINPREVU DATETIME,
	@HDEBUTPREVU DATETIME,
	@HFINPREVU DATETIME,
	@NUMEROBADGE NVARCHAR(200),
	@NUMEROVISITE INT,
	@DEBUTVISITE DATETIME,
	@FINVISITE DATETIME,
	@HDEBUT DATETIME,
	@HFIN DATETIME,
	@STATUTVISITE NVARCHAR(50),
	@BOITE NVARCHAR(6),
	@CASIER NVARCHAR(6),
	@OBJET NVARCHAR(200),
	@PIECE NVARCHAR(20),
	@NUMERO NVARCHAR(20),
	@VALIDITE DATETIME,
	@PARKING NVARCHAR(35),
	@IMMATRICULATION NVARCHAR(15),
	@OBSERVATION NVARCHAR(200),
	@LIEU NVARCHAR(50),
	@ORIGINEVISITE INT,
	@MARQUE NVARCHAR(20),
	@MODELE NVARCHAR(40),
	@PREENREG INT,
	@CLE NVARCHAR(500),
	@SITE NVARCHAR(35),
	@LAST_ACTION NVARCHAR(50),
	@RES_FINAL NVARCHAR(50),
	@RES_MOTEUR1 NVARCHAR(50),
	@RES_MOTEUR2 NVARCHAR(50),
	@RES_OS NVARCHAR(50),
	@INFO NVARCHAR(50),
	@ALERTE NVARCHAR(50),
	@PROFIL_CTRL_ID NVARCHAR(4000),
	@PROFIL_CTRL2 NVARCHAR(4000),
	@SIGNATURE_ENTREE NVARCHAR(2),
	@SIGNATURE_SORTIE NVARCHAR(2),
	@TYPEVISITEID INT,
	@ID NVARCHAR(18) OUTPUT
AS

	DECLARE @FLAG NVARCHAR(14)
	DECLARE @IDENTITY NVARCHAR(14)
	DECLARE @IDRES NVARCHAR(18)
	DECLARE @IDINT NVARCHAR(18)
	DECLARE @CODESALLE NVARCHAR(18)
	DECLARE @SITEID NVARCHAR(14)
	DECLARE @STATUTVISITEID INT
	DECLARE @NBUPDATE INT
	DECLARE @NBINSERT INT
	DECLARE @NOMPRENOMRESID NVARCHAR(70)
	DECLARE @NOMPRENOMVISIT NVARCHAR(70)
	DECLARE @IDTYPEVISITE NVARCHAR(20)
BEGIN
	SET @NBUPDATE = 0
	SET @NBINSERT = 0
	IF(@VALIDITE='')BEGIN
		SET @VALIDITE=NULL
	END
	IF(@IDATENAISSANCE='')BEGIN
		SET @IDATENAISSANCE=NULL
	END
	IF(@DEBUTPREVU ='')BEGIN
		SET @DEBUTPREVU = NULL
	END
	IF(@FINPREVU ='')BEGIN
		SET @FINPREVU = NULL
	END
	IF(@HDEBUTPREVU ='')BEGIN
		SET @HDEBUTPREVU = NULL
	END
	IF(@DEBUTVISITE ='')BEGIN
		SET @DEBUTVISITE = NULL
	END
	IF(@FINVISITE ='')BEGIN
		SET @FINVISITE = NULL
	END
	IF(@HDEBUT ='')BEGIN
		SET @HDEBUT = NULL
	END
	IF(@HFIN ='')BEGIN
		SET @HFIN = NULL
	END
	IF(@HFINPREVU ='')BEGIN
		SET @HFINPREVU = NULL
	END

	IF(@NOMINT='##')BEGIN
		SET @NOMINT=''
	END
	IF(@PRENOMINT='##')BEGIN
		SET @PRENOMINT=''
	END
	IF(@NOMRES='##')BEGIN
		SET @NOMRES=''
	END
	IF(@PRENOMRES ='##')BEGIN
		SET @PRENOMRES =''
	END
	IF(@SOCIETERESID ='##')BEGIN
		SET @SOCIETERESID =''
	END
	IF(@SOCIETEVISIT ='##')BEGIN
		SET @SOCIETEVISIT =''
	END
	IF(@IFONCTION ='##')BEGIN
		SET @IFONCTION =''
	END
	IF(@ILIEUNAISSANCE ='##')BEGIN
		SET @ILIEUNAISSANCE =''
	END
	IF(@IPAYS ='##')BEGIN
		SET @IPAYS =''
	END
	IF(@INOMJEUNEFILLE ='##')BEGIN
		SET @INOMJEUNEFILLE =''
	END
	IF(@ISTATUT ='##')BEGIN
		SET @ISTATUT =''
	END
	IF(@NUMEROBADGE ='##')BEGIN
		SET @NUMEROBADGE =''
	END
	IF(@STATUTVISITE ='##')BEGIN
		SET @STATUTVISITE =''
	END
	IF(@BOITE ='##')BEGIN
		SET @BOITE =''
	END
	IF(@CASIER ='##')BEGIN
		SET @CASIER =''
	END
	IF(@OBJET ='##')BEGIN
		SET @OBJET =''
	END
	IF(@PIECE ='##')BEGIN
		SET @PIECE =''
	END
	IF(@NUMERO ='##')BEGIN
		SET @NUMERO =''
	END
	IF(@PARKING ='##')BEGIN
		SET @PARKING =''
	END
	IF(@IMMATRICULATION ='##')BEGIN
		SET @IMMATRICULATION =''
	END
	IF(@OBSERVATION ='##')BEGIN
		SET @OBSERVATION =''
	END
	IF(@LIEU ='##')BEGIN
		SET @LIEU =''
	END
	IF(@MARQUE ='##')BEGIN
		SET @MARQUE =''
	END
	IF(@MODELE ='##')BEGIN
		SET @MODELE =''
	END
	IF(@CLE ='##')BEGIN
		SET @CLE =''
	END
	IF(@SITE ='##')BEGIN
		SET @SITE =''
	END
	IF  (@TYPEVISITEID IS NULL) OR (ISNUMERIC(@TYPEVISITEID)<>1) BEGIN
		SET @TYPEVISITEID=0
	END
	IF(@VIP IS NULL) BEGIN
		SET @VIP =0
	END
	SET @IDTYPEVISITE=CAST(@TYPEVISITEID AS VARCHAR)
	EXEC PS_TYPEVISITE 0,'',@IDTYPEVISITE,@IDTYPEVISITE OUT
	--SET @NUMEROVISITE = (SELECT MAX(NUMEROVISITE) FROM VISITES)
	IF(@NUMEROVISITE IS NULL OR @NUMEROVISITE=0) BEGIN
		SET @NUMEROVISITE = (SELECT DERNVISITE FROM PARAMETRES)
		UPDATE PARAMETRES SET DERNVISITE=DERNVISITE+1
	END
	IF(@ORIGINEVISITE IS NULL OR @ORIGINEVISITE=0) BEGIN
		SET @ORIGINEVISITE = @NUMEROVISITE
	END
	SET @NOMPRENOMRESID = UPPER(@NOMRES) + ' ' + UPPER(@PRENOMRES)
	SET @NOMPRENOMVISIT = UPPER(@NOMINT) + ' ' + UPPER(@PRENOMINT)

	IF(@NOMPRENOMRESID IS NOT NULL AND LTRIM(@NOMPRENOMRESID)<>'') BEGIN

		EXEC PS_RESIDANTS 1,'NOMPRENOM',@SOCIETERESID,NULL,NULL,@NOMRES,@PRENOMRES,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'1',NULL,'0', @IDRES OUTPUT

		SET @NBUPDATE = @NBUPDATE + CAST( (SELECT [DATA] FROM SPLIT(@IDRES,',') WHERE [ID] = 3) AS INT)
		SET @NBINSERT = @NBINSERT + CAST( (SELECT [DATA] FROM SPLIT(@IDRES,',') WHERE [ID] = 2) AS INT)
		SET @IDRES = (SELECT TOP 1 DATA FROM SPLIT(@IDRES,',') WHERE [ID] = 1)

		IF(@NOMPRENOMVISIT IS NOT NULL AND LTRIM(@NOMPRENOMVISIT)<>'')BEGIN

			EXEC PS_INTERLOCUTEUR 1,'NOMPRENOM',NULL,@NOMINT,@PRENOMINT,@INOMJEUNEFILLE,@IDATENAISSANCE,@ILIEUNAISSANCE,@IPAYS,@SOCIETEVISIT,@IFONCTION,@ISTATUT,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'0',NULL,NULL,@IDINT OUTPUT

			SET @NBUPDATE = @NBUPDATE + CAST( (SELECT [DATA] FROM SPLIT(@IDINT,',') WHERE [ID] = 3) AS INT)
			SET @NBINSERT = @NBINSERT + CAST( (SELECT [DATA] FROM SPLIT(@IDINT,',') WHERE [ID] = 2) AS INT)
			SET @IDINT = (SELECT [DATA] FROM SPLIT(@IDINT,',') WHERE [ID] = 1)

			IF @IDTYPEVISITE='-1'  AND EXISTS(SELECT TOP 1 RESIDANTID FROM RESIDANTS WHERE NOMPRENOM=@NOMINT+' '+@PRENOMINT AND SOCIETE=@SOCIETERESID) BEGIN

			UPDATE INTERLOCUTEUR SET EXTERNALID=(SELECT TOP 1 RESIDANTID FROM RESIDANTS WHERE NOMPRENOM=@NOMINT+' '+@PRENOMINT AND SOCIETE=@SOCIETERESID)
			WHERE INTERLOCUTEURID=@IDINT
			END

			IF(EXISTS(SELECT STATUTID FROM STATUTVISITE WHERE STATUTVISITE = @STATUTVISITE))BEGIN
				SET @STATUTVISITEID = (SELECT TOP 1 STATUTID FROM STATUTVISITE WHERE STATUTVISITE = @STATUTVISITE)
				SET @STATUTVISITE = (SELECT TOP 1 STATUTVISITE FROM STATUTVISITE WHERE STATUTVISITE = @STATUTVISITE)
				SET @PREENREG =0
			END
			ELSE BEGIN
				SET @PREENREG =1
				SET @STATUTVISITEID = 2
				SET @STATUTVISITE = (SELECT TOP 1 STATUTVISITE FROM STATUTVISITE WHERE STATUTID=@STATUTVISITEID)
			END
			EXEC PS_SITE 0,'',@SITE,@SITEID OUTPUT

			IF EXISTS (
		   SELECT TOP(1) VISITEID FROM VISITES WHERE STATUTID=@STATUTVISITEID AND UPPER(LTRIM(NOMPRENOMRESID))=UPPER(LTRIM(@NOMPRENOMRESID)) AND LTRIM(UPPER(NOMPRENOMVISIT))=LTRIM(UPPER(@NOMPRENOMVISIT)) AND (DEBUTPREVU = @DEBUTPREVU OR (DEBUTPREVU IS NULL AND @DEBUTPREVU IS NULL)) AND (FINPREVU = @FINPREVU OR (FINPREVU IS NULL AND @FINPREVU IS NULL)) AND (HDEBUTPREVU = @HDEBUTPREVU OR (HDEBUTPREVU IS NULL AND @HDEBUTPREVU IS NULL)) AND (HFINPREVU=@HFINPREVU OR (HFINPREVU IS NULL AND @HFINPREVU IS NULL)) AND (DEBUTVISITE = @DEBUTVISITE OR (DEBUTVISITE IS NULL AND @DEBUTVISITE IS NULL)) AND (FINVISITE=@FINVISITE OR (FINVISITE IS NULL AND @FINVISITE IS NULL)) AND (HDEBUT=@HDEBUT OR (HDEBUT IS NULL AND @HDEBUT IS NULL)) AND (HFIN = @HFIN OR(HFIN IS NULL AND @HFIN IS NULL)) AND
			  CASE
					WHEN  @CHAMPCTRL='' THEN 1
					WHEN  @CHAMPCTRL='NOMPRENOM' THEN 1
					WHEN  @CHAMPCTRL='SOCIETE' AND UPPER(SOCIETERESID)=UPPER(@SOCIETERESID) AND UPPER(LTRIM(SOCIETEVISIT))=UPPER(@SOCIETEVISIT) THEN 1
					ELSE 0
			  END=1)

			BEGIN --UPDATE
				SET @ID=(SELECT TOP(1) VISITEID FROM VISITES WHERE STATUTID=@STATUTVISITEID AND UPPER(LTRIM(NOMPRENOMRESID))=UPPER(LTRIM(@NOMPRENOMRESID)) AND LTRIM(UPPER(NOMPRENOMVISIT))=LTRIM(UPPER(@NOMPRENOMVISIT)) AND (DEBUTPREVU = @DEBUTPREVU OR (DEBUTPREVU IS NULL AND @DEBUTPREVU IS NULL)) AND (FINPREVU = @FINPREVU OR (FINPREVU IS NULL AND @FINPREVU IS NULL)) AND (HDEBUTPREVU = @HDEBUTPREVU OR (HDEBUTPREVU IS NULL AND @HDEBUTPREVU IS NULL)) AND (HFINPREVU=@HFINPREVU OR (HFINPREVU IS NULL AND @HFINPREVU IS NULL)) AND (DEBUTVISITE = @DEBUTVISITE OR (DEBUTVISITE IS NULL AND @DEBUTVISITE IS NULL)) AND (FINVISITE=@FINVISITE OR (FINVISITE IS NULL AND @FINVISITE IS NULL)) AND (HDEBUT=@HDEBUT OR (HDEBUT IS NULL AND @HDEBUT IS NULL)) AND (HFIN = @HFIN OR(HFIN IS NULL AND @HFIN IS NULL)) AND
			  CASE
					WHEN  @CHAMPCTRL='' THEN 1
					WHEN  @CHAMPCTRL='NOMPRENOM' THEN 1
					WHEN  @CHAMPCTRL='SOCIETE' AND UPPER(SOCIETERESID)=UPPER(@SOCIETERESID) AND UPPER(LTRIM(SOCIETEVISIT))=UPPER(LTRIM(@SOCIETEVISIT)) THEN 1
					ELSE 0
			  END=1)

				UPDATE VISITES
				SET SOCIETERESID=UPPER(@SOCIETERESID),NOMPRENOMRESID=@NOMPRENOMRESID,SOCIETEVISIT=UPPER(@SOCIETEVISIT),NOMPRENOMVISIT=@NOMPRENOMVISIT,IFONCTION=@IFONCTION,IDATENAISSANCE=@IDATENAISSANCE,ILIEUNAISSANCE=@ILIEUNAISSANCE,IPAYS=@IPAYS,INOMJEUNEFILLE=@INOMJEUNEFILLE,VIP=@VIP,ISTATUT=@ISTATUT,DEBUTPREVU=@DEBUTPREVU,FINPREVU=@FINPREVU,HDEBUTPREVU=@HDEBUTPREVU,HFINPREVU=@HFINPREVU,NUMEROBADGE=@NUMEROBADGE,NUMEROVISITE=@NUMEROVISITE,DEBUTVISITE=@DEBUTVISITE,FINVISITE=@FINVISITE,HDEBUT=@HDEBUT,HFIN=@HFIN,STATUTVISITE=@STATUTVISITE,BOITE=@BOITE,CASIER=@CASIER,OBJET=@OBJET,PIECE=@PIECE,NUMERO=@NUMERO,VALIDITE=@VALIDITE,PARKING=@PARKING,IMMATRICULATION=@IMMATRICULATION,OBSERVATION=@OBSERVATION,LIEU=@LIEU,ORIGINEVISITE=@ORIGINEVISITE,MARQUE=@MARQUE,MODELE=@MODELE,PREENREG=@PREENREG,CLE=@CLE,INTERLOCUTEURID = @IDINT,RESIDANTID = @IDRES,SITEID=@SITEID,STATUTID=@STATUTVISITEID,DATEMAJ=CURRENT_TIMESTAMP
				WHERE VISITEID = @ID
				IF (@ISTATUT IS NOT NULL) AND (@ISTATUT<>'') BEGIN
					UPDATE VISITES SET ISTATUT=(SELECT LIBELLE FROM NATURE WHERE NATUREID =(SELECT NATUREID FROM INTERLOCUTEUR WHERE INTERLOCUTEURID=@IDINT)) WHERE VISITEID=@ID
				END
				IF (@DEBUTPREVU IS NULL) BEGIN
					UPDATE VISITES SET DEBUTPREVU=CONVERT(DATETIME,CURRENT_TIMESTAMP,103), FINPREVU=CONVERT(DATETIME,CURRENT_TIMESTAMP,103) WHERE VISITEID=@ID
				END
				IF (@FINPREVU IS NULL) BEGIN
					UPDATE VISITES SET FINPREVU=CONVERT(DATETIME,CURRENT_TIMESTAMP,103) WHERE VISITEID=@ID
				END
				IF (@HDEBUTPREVU IS NULL) BEGIN
					UPDATE VISITES SET HDEBUTPREVU=CONVERT(DATETIME,CURRENT_TIMESTAMP,108) WHERE VISITEID=@ID
				END
				IF (@HFINPREVU IS NULL) BEGIN
					UPDATE VISITES SET HDEBUTPREVU=CONVERT(DATETIME,'23:00',108) WHERE VISITEID=@ID
				END

				UPDATE VISITES SET TYPEVISITEID=CAST(@IDTYPEVISITE AS INT) WHERE VISITEID=@ID

				SET @ID = @ID + ',' + CAST(@NBINSERT AS VARCHAR) + ',' + CAST(@NBUPDATE+1 AS VARCHAR)
			END
			ELSE BEGIN --INSERT

				IF(@FLAGIN = 1)BEGIN

					INSERT INTO SEQ_IDENTITY(LIBELLE) VALUES ('OK')
					SET @IDENTITY = (SELECT @@IDENTITY AS ID)
					SET @FLAG = (SELECT SUBSTRING(VERSION, 1, 3) FROM VERSION_SFW)
					SET @ID = @FLAG + @IDENTITY

					INSERT INTO VISITES(VISITEID,SOCIETERESID ,NOMPRENOMRESID,SOCIETEVISIT,NOMPRENOMVISIT,IFONCTION,IDATENAISSANCE,ILIEUNAISSANCE,IPAYS,INOMJEUNEFILLE,ISTATUT,DEBUTPREVU,FINPREVU,HDEBUTPREVU,HFINPREVU,NUMEROBADGE,NUMEROVISITE,DEBUTVISITE,FINVISITE,HDEBUT,HFIN,STATUTVISITE,BOITE,CASIER,OBJET,PIECE,NUMERO,VALIDITE,PARKING,IMMATRICULATION,OBSERVATION,LIEU,ORIGINEVISITE,MARQUE,MODELE,PREENREG,CLE,INTERLOCUTEURID,RESIDANTID,SITEID,STATUTID,DATECREATION,DATEMAJ,EXTERNALID,TYPEVISITEID,NBBDGIMPRTOTAL,BUREAUID)
					VALUES(@ID,UPPER(@SOCIETERESID),@NOMPRENOMRESID,UPPER(@SOCIETEVISIT),@NOMPRENOMVISIT,@IFONCTION,@IDATENAISSANCE,@ILIEUNAISSANCE,@IPAYS,@INOMJEUNEFILLE,@ISTATUT,@DEBUTPREVU,@FINPREVU,@HDEBUTPREVU,@HFINPREVU,@NUMEROBADGE,@NUMEROVISITE,@DEBUTVISITE,@FINVISITE,@HDEBUT,@HFIN,@STATUTVISITE,@BOITE,@CASIER,@OBJET,@PIECE,@NUMERO,@VALIDITE,@PARKING,@IMMATRICULATION,@OBSERVATION,@LIEU,@NUMEROVISITE,@MARQUE,@MODELE,@PREENREG,@CLE,@IDINT,@IDRES,@SITEID,@STATUTVISITEID,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,@IDRES,@IDTYPEVISITE,0,@NUMEROVISITE)
					IF (@VIP IS NOT NULL) BEGIN
   					    UPDATE VISITES SET VIP=@VIP WHERE VISITEID=@ID
					 END
					IF (@DEBUTPREVU IS NULL) BEGIN
						UPDATE VISITES SET DEBUTPREVU=CONVERT(DATETIME,CURRENT_TIMESTAMP,103), FINPREVU=CONVERT(DATETIME,CURRENT_TIMESTAMP,103) WHERE VISITEID=@ID
					END
					IF (@FINPREVU IS NULL) BEGIN
						UPDATE VISITES SET FINPREVU=CONVERT(DATETIME,CURRENT_TIMESTAMP,103) WHERE VISITEID=@ID
					END
					IF (@HDEBUTPREVU IS NULL) BEGIN
						UPDATE VISITES SET HDEBUTPREVU=CONVERT(DATETIME,CURRENT_TIMESTAMP,108) WHERE VISITEID=@ID
					END
					IF (@HFINPREVU IS NULL) BEGIN
						UPDATE VISITES SET HDEBUTPREVU=CONVERT(DATETIME,'23:00',108) WHERE VISITEID=@ID
					END
					UPDATE VISITES SET IFONCTION=(SELECT LIBELLE FROM FONCTION WHERE CODEFONCTION=(SELECT CODEFONCTION FROM INTERLOCUTEUR WHERE INTERLOCUTEURID=@IDINT)),ISTATUT=(SELECT LIBELLE FROM NATURE WHERE NATUREID=(SELECT NATUREID FROM INTERLOCUTEUR WHERE INTERLOCUTEURID=@IDINT)),IDATENAISSANCE=(SELECT DATENAISSANCE FROM INTERLOCUTEUR WHERE INTERLOCUTEURID=@IDINT),INOMJEUNEFILLE=(SELECT NOMJEUNEFILLE FROM INTERLOCUTEUR WHERE INTERLOCUTEURID=@IDINT) WHERE VISITEID=@ID
					SET @NBINSERT = @NBINSERT+1
				END
				ELSE BEGIN
					SET @ID = '0'
				END
				SET @ID = @ID + ',' + CAST(@NBINSERT AS VARCHAR) + ',' + CAST(@NBUPDATE AS VARCHAR)
			END
		END
		ELSE BEGIN
			SET @ID = '0,' + CAST(@NBINSERT AS VARCHAR) + ',' + CAST(@NBUPDATE AS VARCHAR)
		END
	END
	ELSE BEGIN
		SET @ID = '0,' + CAST(@NBINSERT AS VARCHAR) + ',' + CAST(@NBUPDATE AS VARCHAR)
	END
END