CREATE PROCEDURE [dbo].[PS_ZCL25_CREATIONVISITE]
	/* VISITE (RESIDANTS) */
	@RM NVARCHAR(1), /* SI 0 PAS D'UPDATE DE RESIDANT */
	@RCTRL NVARCHAR(50),
	@RMATRICULE NVARCHAR(50),
	@RSOCIETE NVARCHAR(200),
	@RCIVILITE NVARCHAR(30),
	@RNOM NVARCHAR(35),
	@RPRENOM NVARCHAR(35),
	@RTEL NVARCHAR(20),
	@RSITE NVARCHAR(35),
	@RETAGE NVARCHAR(7),
	@RBUREAU NVARCHAR(15),
	@RFONCTION NVARCHAR(35),
	@RSERVICE NVARCHAR(35),
	@RLOGIN NVARCHAR(20),
	@RPASSWORD NVARCHAR(250),
	@RHABILITATIONVISITE NVARCHAR(1),
	@RLISTEROUGE NVARCHAR(1),
	@RISEXTERN NVARCHAR(1),
	@RISACTIF NVARCHAR(1),
	@ISRESIDENT NVARCHAR(1),
	@RINTERDIT NVARCHAR(1),
	@RDEBUTINTERDIT DATETIME,
	@RFININTERDIT DATETIME,

	/* RDV (VISITE)*/
	@VOBJET NVARCHAR(35),
	@VTYPE NVARCHAR(35),
	@VLIEU NVARCHAR(50),
	@VCOMMENTAIRE NVARCHAR(200),
	@VDATE DATETIME,
	@VHEURE DATETIME,
	@VFDATE DATETIME,
	@VFHEURE DATETIME,

	/* VISITEUR (INTERLOCUTEUR) */
	@ICIVILITE NVARCHAR(30),
	@INOM NVARCHAR(35),
	@IPRENOM NVARCHAR(35),
	@ISOCIETE NVARCHAR(200),
	@ITEL NVARCHAR(20),
	@IINTERDIT NVARCHAR(1),
	@IDEBUTINTERDIT DATETIME,
	@IFININTERDIT DATETIME,
	@IPAYS NVARCHAR(35),
	@IFONCTION NVARCHAR(35),
	@INATURE NVARCHAR(35),
	@INATIONALITE NVARCHAR(50),

	/* RETOUR */
	@VID NVARCHAR(14) OUTPUT

AS
	DECLARE @NUMVISITE INT
	DECLARE @SOCIETERESID NVARCHAR(35)
	DECLARE @NOMPRENOMRESID NVARCHAR(70)
	DECLARE @RID NVARCHAR(14)
	DECLARE @IID NVARCHAR(14)
	DECLARE @SID NVARCHAR(14)
	DECLARE @BID NVARCHAR(14)
	DECLARE @TYPEID INT
	DECLARE @VSTATUT NVARCHAR(20)
	DECLARE @FLAG NVARCHAR(14)
	DECLARE @IDENTITY NVARCHAR(14)
BEGIN
	EXEC PS_ZCL25_SELECTIONTYPEVISITE @VTYPE, @TYPEID OUTPUT
	EXEC PS_ZCL25_CREATIONINTERLOCUTEUR @ICIVILITE, @INOM, @IPRENOM, @ISOCIETE, @ITEL, @IINTERDIT, @IDEBUTINTERDIT, @IFININTERDIT, @IPAYS, @IFONCTION, @INATURE, @INATIONALITE, @IID OUTPUT

	EXEC PS_ZCL25_CREATIONRESIDANT @RM, @RCTRL, @RMATRICULE, @RSOCIETE, @RCIVILITE, @RNOM, @RPRENOM, @RTEL, @RSITE, @RETAGE, @RBUREAU, @RFONCTION, @RSERVICE, @RLOGIN, @RPASSWORD, @RHABILITATIONVISITE, @RLISTEROUGE, @RISEXTERN, @RISACTIF, @ISRESIDENT, @RINTERDIT, @RDEBUTINTERDIT, @RFININTERDIT, @RID OUTPUT
	SET @SID = (SELECT SITEID FROM RESIDANTS WHERE RESIDANTID = @RID)
	SET @BID = (SELECT BUREAUID FROM RESIDANTS WHERE RESIDANTID = @RID)

	SET @VSTATUT = (SELECT STATUTVISITE FROM STATUTVISITE WHERE STATUTID = 2)

	SET @NUMVISITE = (SELECT DERNVISITE FROM PARAMETRES)
	SET @NUMVISITE = @NUMVISITE + 1
	UPDATE PARAMETRES SET DERNVISITE = @NUMVISITE

	SET @SOCIETERESID = (SELECT SOCIETE FROM RESIDANTS WHERE RESIDANTID = @RID)
	SET @NOMPRENOMRESID = (SELECT NOMPRENOM FROM RESIDANTS WHERE RESIDANTID = @RID)

	INSERT INTO SEQ_IDENTITY(LIBELLE) VALUES ('OK')
	SET @IDENTITY = (SELECT @@IDENTITY AS ID)
	SET @FLAG = (SELECT SUBSTRING(VERSION, 1, 3) FROM VERSION_SFW)
	SET @VID = @FLAG + @IDENTITY

	INSERT INTO VISITES (VISITEID, CASIERID, PREMIER, NBBDGIMPR, NBBDGIMPRTOTAL, NUMEROVISITE, ORIGINEVISITE, EXTERNALID, INTERLOCUTEURID, RESIDANTID, SITEID, STATUTID, SOCIETERESID, NOMPRENOMRESID, SOCIETEVISIT, NOMPRENOMVISIT, DEBUTPREVU, HDEBUTPREVU, FINPREVU, HFINPREVU, STATUTVISITE, OBJET, TYPEVISITEID, LIEU, OBSERVATION, BUREAUID, PREENREG, DATECREATION, DATEMAJ)
		VALUES (@VID, 0, 0, 0, 0, @NUMVISITE, @NUMVISITE, 'VPARDEFAUT', @IID, @RID, @SID, 2, @SOCIETERESID, @NOMPRENOMRESID, @ISOCIETE, @INOM + ' ' + @IPRENOM, @VDATE, @VHEURE, @VFDATE, @VFHEURE, @VSTATUT, @VOBJET, @TYPEID, @VLIEU, @VCOMMENTAIRE, @BID, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
END