CREATE PROCEDURE [dbo].[PS_ZCL25_CREATIONRESIDANT]
	@RM NVARCHAR(1), /* SI 1 RESIDANT UPDATE, SI 0 RESIDANT PAS UPDATE */
	@RCTRL NVARCHAR(50), /* CLÉ 1 SI MATRICULE, 2 SI NOM+PRENOM+TEL*/
	@RMATRICULE NVARCHAR(50),
	@RSOCIETE NVARCHAR(200),
	@RCIVILITE NVARCHAR(30),
	@RNOM NVARCHAR(35),
	@RPRENOM NVARCHAR(35),
	@RTEL NVARCHAR(20),
	@RSITE NVARCHAR(35),
	@RETAGE NVARCHAR(7),
	@RBUREAU NVARCHAR(15),
	@RFONCTION NVARCHAR(35),
	@RSERVICE NVARCHAR(35),
	@RLOGIN NVARCHAR(20),
	@RPASSWORD NVARCHAR(250),
	@RHABILITATIONVISITE NVARCHAR(1),
	@RLISTEROUGE NVARCHAR(1),
	@RISEXTERN NVARCHAR(1),
	@RISACTIF NVARCHAR(1),
	@RISRESIDENT NVARCHAR(1),
	@RINTERDIT NVARCHAR(1),
	@RDEBUTINTERDIT DATETIME,
	@RFININTERDIT DATETIME,
	@RID NVARCHAR(14) OUTPUT
AS
	DECLARE @CIVID INT
	DECLARE @SITEID NVARCHAR(14)
	DECLARE @SOCID NVARCHAR(14)
	DECLARE @ETAGEID NVARCHAR(14)
	DECLARE @BUREAUID NVARCHAR(14)
	DECLARE @FCTID INT
	DECLARE @SERID NVARCHAR(14)
	DECLARE @FLAG NVARCHAR(14)
	DECLARE @IDENTITY NVARCHAR(14)
BEGIN
	SET @RNOM = UPPER(@RNOM)
	SET @RPRENOM = UPPER(@RPRENOM)
	SET @RMATRICULE = UPPER(@RMATRICULE)
	EXEC PS_ZCL25_CREATIONSOCIETE @RSOCIETE, 1, @SOCID OUTPUT
	EXEC PS_ZCL25_SELECTIONCIVILITE @RCIVILITE, @CIVID OUTPUT
	EXEC PS_ZCL25_CREATIONSITE @RSITE, @SITEID OUTPUT
	EXEC PS_ZCL25_CREATIONETAGE @RETAGE, '', @ETAGEID OUTPUT
	EXEC PS_ZCL25_CREATIONBUREAU @RBUREAU, @ETAGEID, @BUREAUID OUTPUT
	EXEC PS_ZCL25_CREATIONFONCTION @RFONCTION, @FCTID OUTPUT
	EXEC PS_ZCL25_CREATIONSERVICE @RSERVICE, @SERID OUTPUT

	IF @RMATRICULE = ''
		SET @RMATRICULE = @RNOM + @RPRENOM

	IF (@RCTRL = '1')  AND (EXISTS (SELECT * FROM RESIDANTS WHERE MATRICULE = @RMATRICULE)) BEGIN
		SET @RID = (SELECT RESIDANTID FROM RESIDANTS WHERE MATRICULE = @RMATRICULE)
		IF @RM = '1'
			UPDATE RESIDANTS SET CODECIVILITE = @CIVID, CIVILITE = @RCIVILITE, NOM = @RNOM, PRENOM = @RPRENOM, NOMPRENOM = @RNOM + ' ' + @RPRENOM, TELEPHONE = @RTEL, SITE = @RSITE, SITEID = @SITEID, ETAGE = @RETAGE, ETAGEID = @ETAGEID, BUREAU = @RBUREAU, BUREAUID = @BUREAUID, DATEMAJ = CURRENT_TIMESTAMP WHERE RESIDANTID = @RID
	END
	ELSE BEGIN
		IF (@RCTRL = '2')  AND (EXISTS (SELECT * FROM RESIDANTS WHERE UPPER(NOM) = @RNOM AND UPPER(PRENOM) = @RPRENOM AND UPPER(TELEPHONE) = @RTEL)) BEGIN
			SET @RID = (SELECT RESIDANTID FROM RESIDANTS WHERE UPPER(NOM) = @RNOM AND UPPER(PRENOM) = @RPRENOM AND UPPER(TELEPHONE) = @RTEL)
			IF @RM = '1'
				UPDATE RESIDANTS SET CODECIVILITE = @CIVID, CIVILITE = @RCIVILITE, NOM = @RNOM, PRENOM = @RPRENOM, NOMPRENOM = @RNOM + ' ' + @RPRENOM, TELEPHONE = @RTEL, SITE = @RSITE, SITEID = @SITEID, ETAGE = @RETAGE, ETAGEID = @ETAGEID, BUREAU = @RBUREAU, BUREAUID = @BUREAUID, DATEMAJ = CURRENT_TIMESTAMP WHERE RESIDANTID = @RID
		END
		ELSE BEGIN
			INSERT INTO SEQ_IDENTITY(LIBELLE) VALUES ('OK')
			SET @IDENTITY = (SELECT @@IDENTITY AS ID)
			SET @FLAG = (SELECT SUBSTRING(VERSION, 1, 3) FROM VERSION_SFW)
			SET @RID = @FLAG + @IDENTITY

			INSERT INTO RESIDANTS (RESIDANTID, SOCIETE, SOCIETEID, PLANID,	EXTERNALID, CODEFONCTION, FONCTION, SERVICEID, SERVICE, NOM, PRENOM, NOMPRENOM, MATRICULE, THELOGIN, THEPASSWORD, CODECIVILITE, CIVILITE, TELEPHONE, SITE, SITEID, ETAGE, ETAGEID, BUREAU, BUREAUID, HABILITATIONVISITE, LISTEROUGE, ISEXTERN, ISRESIDENT, ISACTIF, INTERDIT, DEBUTINTERDIT, FININTERDIT, DATECREATION, DATEMAJ)
				VALUES (@RID, @RSOCIETE, @SOCID, 'VPARDEFAUT', 'VPARDEFAUT', @FCTID, @RFONCTION, @SERID, @RSERVICE, @RNOM, @RPRENOM, @RNOM+' '+@RPRENOM, @RMATRICULE, @RLOGIN, @RPASSWORD, @CIVID, @RCIVILITE, @RTEL, @RSITE, @SITEID, @RETAGE, @ETAGEID, @RBUREAU, @BUREAUID, @RHABILITATIONVISITE, @RLISTEROUGE, @RISEXTERN, @RISACTIF, @RISRESIDENT, @RINTERDIT, @RDEBUTINTERDIT, @RFININTERDIT, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
		END
	END
END