CREATE PROCEDURE [dbo].[PS_ZCL25_APPELCREATIONVISITE]
	/* VISITE (RESIDANTS) */
	@RM NVARCHAR(1), /* SI 0 PAS D'UPDATE DE RESIDANT */
	@RMATRICULE NVARCHAR(50),
	@RCIVILITE NVARCHAR(30),
	@RNOM NVARCHAR(35),
	@RPRENOM NVARCHAR(35),
	@RTEL NVARCHAR(20),
	@RSITE NVARCHAR(35),
	@RETAGE NVARCHAR(7),
	@RBUREAU NVARCHAR(15),

	/* RDV (VISITE)*/
	@VOBJET NVARCHAR(35),
	@VLIEU NVARCHAR(50),
	@VCOMMENTAIRE NVARCHAR(200),
	@VDATE DATETIME,
	@VHEURE DATETIME,

	/* VISITEUR (INTERLOCUTEUR) */
	@ICIVILITE NVARCHAR(30),
	@INOM NVARCHAR(35),
	@IPRENOM NVARCHAR(35),
	@ISOCIETE NVARCHAR(200),
	@ITEL NVARCHAR(20)
AS
	DECLARE @VID NVARCHAR(14)
	DECLARE @RCTRL NVARCHAR(50)
	DECLARE @RSOCIETE NVARCHAR(35)
	DECLARE @RFONCTION NVARCHAR(35)
	DECLARE @RSERVICE NVARCHAR(35)
	DECLARE @RLOGIN NVARCHAR(20)
	DECLARE @RPASSWORD NVARCHAR(250)
	DECLARE @RHABILITATIONVISITE NVARCHAR(1)
	DECLARE @RLISTEROUGE NVARCHAR(1)
	DECLARE @RISEXTERN NVARCHAR(1)
	DECLARE @RISACTIF NVARCHAR(1)
	DECLARE @RISRESIDENT NVARCHAR(1)
	DECLARE @RINTERDIT NVARCHAR(1)
	DECLARE @RDEBUTINTERDIT DATETIME
	DECLARE @RFININTERDIT DATETIME
	DECLARE @IINTERDIT NVARCHAR(1)
	DECLARE @IDEBUTINTERDIT DATETIME
	DECLARE @IFININTERDIT DATETIME
	DECLARE @IPAYS NVARCHAR(35)
	DECLARE @IFONCTION NVARCHAR(35)
	DECLARE @INATURE NVARCHAR(35)
	DECLARE @INATIONALITE NVARCHAR(50)
	DECLARE @VTYPE NVARCHAR(35)
	DECLARE @VFDATE DATETIME
	DECLARE @VFHEURE DATETIME
BEGIN
	SET @RCTRL = '2'
	SET @RSOCIETE = '**********'
	SET @RFONCTION = '**********'
	SET @RSERVICE = '**********'
	SET @RLOGIN = UPPER(@RNOM)
	SET @RPASSWORD = UPPER(@RPRENOM)
	SET @RHABILITATIONVISITE = '1'
	SET @RLISTEROUGE = '0'
	SET @RISEXTERN = '0'
	SET @RISACTIF = '1'
	SET @RISRESIDENT = '1'
	SET @RINTERDIT = '0'
	SET @RDEBUTINTERDIT = CONVERT(DATETIME,CONVERT(VARCHAR,CURRENT_TIMESTAMP,103),103)
	SET @RFININTERDIT = CURRENT_TIMESTAMP + (360*100)
	SET @IINTERDIT = '0'
	SET @IDEBUTINTERDIT = CONVERT(DATETIME,CONVERT(VARCHAR,CURRENT_TIMESTAMP,103),103)
	SET @IFININTERDIT = CURRENT_TIMESTAMP + (360*100)
	SET @IPAYS = 'FRANCE'
	SET @IFONCTION = '**********'
	SET @INATURE = 'VISITEUR'
	SET @INATIONALITE = 'FRANCAIS'
	SET @VTYPE = ''
	SET @VFDATE = @VDATE
	SET @VFHEURE = '15/09/1986 18:00'

	EXEC PS_ZCL25_CREATIONVISITE @RM, @RCTRL, @RMATRICULE, @RSOCIETE, @RCIVILITE, @RNOM, @RPRENOM, @RTEL, @RSITE, @RETAGE, @RBUREAU, @RFONCTION, @RSERVICE, @RLOGIN, @RPASSWORD, @RHABILITATIONVISITE, @RLISTEROUGE, @RISEXTERN, @RISACTIF, @RISRESIDENT, @RINTERDIT, @RDEBUTINTERDIT, @RFININTERDIT, @VOBJET, @VTYPE, @VLIEU, @VCOMMENTAIRE, @VDATE, @VHEURE, @VFDATE, @VFHEURE, @ICIVILITE, @INOM, @IPRENOM, @ISOCIETE, @ITEL, @IINTERDIT, @IDEBUTINTERDIT, @IFININTERDIT, @IPAYS, @IFONCTION, @INATURE, @INATIONALITE, @VID OUTPUT
	SELECT @VID
END