CREATE PROCEDURE [dbo].[PS_ZCL25_UPDATEVISITE]
	@VID NVARCHAR(14),
	@GUICHET NVARCHAR(40)

AS
	DECLARE @FLAG NVARCHAR(14)
	DECLARE @IDENTITY NVARCHAR(14)
	DECLARE @VISITEID NVARCHAR(14)
	DECLARE @GUICHETID NVARCHAR(14)
	DECLARE @NUMVISITE INT
BEGIN
	INSERT INTO SEQ_IDENTITY(LIBELLE) VALUES ('OK')
	SET @IDENTITY = (SELECT @@IDENTITY AS ID)
	SET @FLAG = (SELECT SUBSTRING(VERSION, 1, 3) FROM VERSION_SFW)
	SET @VISITEID = @FLAG + @IDENTITY

	SET @NUMVISITE = (SELECT DERNVISITE FROM PARAMETRES)
	SET @NUMVISITE = @NUMVISITE + 1
	UPDATE PARAMETRES SET DERNVISITE = @NUMVISITE

	IF @GUICHET = ''
		SET @GUICHET = 'TELEM_IMP'

	IF EXISTS (SELECT * FROM GUICHET WHERE GUICHET = @GUICHET)
		SET @GUICHETID = (SELECT TOP 1 GUICHETID FROM GUICHET WHERE GUICHET = @GUICHET)
	ELSE
		SET @GUICHETID = 'VPARDEFAUT'

	INSERT INTO VISITES (VISITEID,INTERLOCUTEURID, RESIDANTID, CODESALLE, SITEID, STATUTID, EXTERNALID, SOCIETERESID, NOMPRENOMRESID, SOCIETEVISIT, NOMPRENOMVISIT, DEBUTPREVU, FINPREVU, HDEBUTPREVU, HFINPREVU, NUMEROBADGE, NUMEROVISITE, DEBUTVISITE, FINVISITE, HDEBUT, HFIN, STATUTVISITE, TYPEVISITEID, BOITE, CASIER, OBJET, CASIERID, PIECE, NUMERO, VALIDITE, PARKING, IMMATRICULATION, GUICHETID, OBSERVATION, BUREAUID, LIEU, DATECREATION, DATEMAJ, DATESYNCHRO, ORIGINEVISITE, NBBDGIMPR, NBBDGIMPRTOTAL, FREE1, FREE2, FREE3, FREE4, FREE5, FREE6, FREE7, FREE8, FREE9, FREE10, MARQUE, MODELE, COTE, PREMIER, PREENREG, ZONE, DESCENTE, ECHANGES, BADGEPHYSIQUE, ATTENDU, ATTENDU_VENU, DATEHEUREENTREEPARKING, DATEHEURESORTIEPARKING, STATUTPARKING) SELECT @VISITEID, INTERLOCUTEURID, RESIDANTID, CODESALLE, SITEID, STATUTID, EXTERNALID, SOCIETERESID, NOMPRENOMRESID, SOCIETEVISIT, NOMPRENOMVISIT, DEBUTPREVU, FINPREVU, HDEBUTPREVU, HFINPREVU, NUMEROBADGE, NUMEROVISITE, DEBUTVISITE, FINVISITE, HDEBUT, HFIN, STATUTVISITE, TYPEVISITEID, BOITE, CASIER, OBJET, CASIERID, PIECE, NUMERO, VALIDITE, PARKING, IMMATRICULATION, GUICHETID, OBSERVATION, BUREAUID, LIEU, DATECREATION, DATEMAJ, DATESYNCHRO, ORIGINEVISITE, NBBDGIMPR, NBBDGIMPRTOTAL, FREE1, FREE2, FREE3, FREE4, FREE5, FREE6, FREE7, FREE8, FREE9, FREE10, MARQUE, MODELE, COTE, PREMIER, PREENREG, ZONE, DESCENTE, ECHANGES, BADGEPHYSIQUE, ATTENDU, ATTENDU_VENU, DATEHEUREENTREEPARKING, DATEHEURESORTIEPARKING, STATUTPARKING FROM VISITES WHERE VISITEID = @VID
	UPDATE VISITES SET GUICHETID = @GUICHETID, STATUTID = 8, STATUTVISITE = 'EN COURS', DATECREATION = CURRENT_TIMESTAMP, DATEMAJ = CURRENT_TIMESTAMP, DEBUTVISITE = CURRENT_TIMESTAMP, HDEBUT = CURRENT_TIMESTAMP, FINVISITE = FINPREVU, NUMEROVISITE = @NUMVISITE WHERE VISITEID = @VISITEID

	INSERT INTO ZCL25_VISITES VALUES (@VISITEID, 0)
END