CREATE PROCEDURE [dbo].[PS_ZCL25_SELECTIONTYPEVISITE]
	@LIBELLE NVARCHAR(30),
	@ID INT OUTPUT
AS
	DECLARE @FLAG NVARCHAR(14)
	DECLARE @IDENTITY NVARCHAR(14)
BEGIN
	SET @LIBELLE = UPPER(@LIBELLE)
	IF EXISTS (SELECT * FROM TYPEVISITE WHERE UPPER(TYPEVISITE) = @LIBELLE) BEGIN
		SET @ID = (SELECT TYPEVISITEID FROM TYPEVISITE WHERE UPPER(TYPEVISITE) = @LIBELLE)
	END
	ELSE
		SET @ID = 0
END