CREATE PROCEDURE [dbo].[PS_ZCL25_SELECTIONNATIONALITE]
	@LIBELLE NVARCHAR(50),
	@ID NVARCHAR(35) OUTPUT
AS

BEGIN
	SET @LIBELLE = UPPER(@LIBELLE)

	IF EXISTS (SELECT * FROM PAYS WHERE UPPER(NATIONALITE) = @LIBELLE) BEGIN
		SET @ID = (SELECT PAYSID FROM PAYS WHERE UPPER(NATIONALITE) = @LIBELLE)
	END
	ELSE BEGIN
		SET @ID = 'VPARDEFAUT'
	END
END