CREATE PROCEDURE [dbo].[PS_ZCL25_CREATIONBUREAU]
	@BUREAU NVARCHAR(15),
	@ETAGEID NVARCHAR(14),
	@ID NVARCHAR(14) OUTPUT
AS
	DECLARE @FLAG NVARCHAR(14)
	DECLARE @IDENTITY NVARCHAR(14)
BEGIN
	SET @BUREAU = UPPER(@BUREAU)
	IF @ETAGEID = ''
		SET @ETAGEID = 'VPARDEFAUT'

	IF EXISTS (SELECT * FROM BUREAUX WHERE UPPER(BUREAU) = @BUREAU AND ETAGEID  = @ETAGEID)
		SET @ID = (SELECT BUREAUID FROM BUREAUX WHERE UPPER(BUREAU) = @BUREAU AND ETAGEID  = @ETAGEID)
	ELSE BEGIN
		INSERT INTO SEQ_IDENTITY(LIBELLE) VALUES ('OK')
		SET @IDENTITY = (SELECT @@IDENTITY AS ID)
		SET @FLAG = (SELECT SUBSTRING(VERSION, 1, 3) FROM VERSION_SFW)
		SET @ID = @FLAG + @IDENTITY
		INSERT INTO BUREAUX (BUREAUID, ETAGEID, BUREAU, DATECREATION, DATEMAJ)
			VALUES (@ID, @ETAGEID, @BUREAU, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
	END
END