CREATE PROCEDURE [dbo].[PS_ZCL27_NEXTPWD]
    @RET NVARCHAR(10) OUTPUT
AS
    DECLARE @MAX INTEGER
    DECLARE @NUM INTEGER
    DECLARE @OFFSET INTEGER

    SET @OFFSET = 109654
    SET @MAX = 100000

    INSERT INTO SEQ_ZCL37_CPTPWD(LIBELLE) VALUES ('OK')
    SET @NUM = (SELECT @@IDENTITY AS NUMVAL)

    IF @NUM >= @MAX BEGIN
        TRUNCATE TABLE SEQ_ZCL37_CPTPWD
        INSERT INTO SEQ_ZCL37_CPTPWD(LIBELLE) VALUES ('OK')
        SET @NUM = (SELECT @@IDENTITY AS NUMVAL)
    END

    SET @RET = @OFFSET+@NUM
    RETURN