CREATE PROCEDURE [dbo].[PURGE]
	@SITEID NVARCHAR(14),
	@FINVISITE DATETIME
AS
BEGIN
    UPDATE VISITES SET STATUTID=-2,STATUTVISITE='AUTO-DELETE',DATEMAJ=GETDATE() WHERE SITEID = @SITEID AND STATUTID IN (2, 4, 32 ) AND FINPREVU<GETDATE() AND ORIGINEVISITE NOT IN (SELECT DISTINCT ORIGINEVISITE FROM VISITES WHERE (STATUTID=16 OR STATUTID=8) AND ORIGINEVISITE IS NOT NULL)
    UPDATE VISITES SET STATUTID=-1,STATUTVISITE='AUTO-DELETE',DATEMAJ=GETDATE() WHERE SITEID = @SITEID AND STATUTID IN (2, 4, 32 ) AND FINPREVU<GETDATE()
END