CREATE PROCEDURE [dbo].[ZCL27_ENREGSITE]
	@SiteID NVARCHAR(14),
	@ServiceUrl NVARCHAR(300)
AS
	IF EXISTS (SELECT * FROM ZCL27_SITE WHERE SITEID = @SiteID)
		UPDATE ZCL27_SITE SET SERVICEURL = @ServiceUrl, DATEMAJ = CURRENT_TIMESTAMP WHERE SITEID = @SiteID
	ELSE
		INSERT INTO ZCL27_SITE (SITEID, SERVICEURL, DATECREATION, DATEMAJ)
			VALUES (@SiteID, @ServiceUrl, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)

	IF @ServiceUrl = ''
		DELETE FROM ZCL27_SITE WHERE SITEID = @SiteID