CREATE PROCEDURE [dbo].[ZCL27_ENREGBADGE]
	@Num NVARCHAR(20),
	@Val INT,
	@SiteID NVARCHAR(14)
AS
	IF EXISTS (SELECT * FROM ZCL27_BADGE WHERE B_CARD_NO = @Num AND SITEID = @SiteID)
		UPDATE ZCL27_BADGE SET B_ASSIGNED = @Val, CARDQUALITY = 'Pool', DATEMAJ = CURRENT_TIMESTAMP
			WHERE B_CARD_NO = @Num AND SITEID = @SiteID
	ELSE
		INSERT INTO ZCL27_BADGE (B_CARD_NO, B_ASSIGNED, SITEID, DATECREATION, DATEMAJ) VALUES (@Num, @Val, @SiteID, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)