UPDATE TQ_COMMUNE SET BDG_FREE1='GUICHET';
UPDATE TQ_COMMUNE SET BDG_FREE2='FINPREVU';
UPDATE TQ_COMMUNE SET BDG_FREE3='NUMEROVISITE';
UPDATE TQ_COMMUNE SET BDG_FREE4='NUMEROBADGE';
UPDATE TQ_COMMUNE SET BDG_FREE5='PIECE';
UPDATE TQ_COMMUNE SET BDG_FREE6='HEUREVISIJOUR';
UPDATE TQ_COMMUNE SET BDG_FREE7='IMMATRICULATION';
UPDATE TQ_COMMUNE SET BDG_FREE8='TELR';
UPDATE TQ_COMMUNE SET BDG_FREE9='BUREAUR';

COMMIT;
EXIT;

