ALTER TABLE VISITES ADD EMETTEUR VARCHAR(200)
ALTER TABLE VISITES ADD USER_IN VARCHAR(200)
ALTER TABLE VISITES ADD USER_OUT VARCHAR(200)
GO

UPDATE VISITES SET EMETTEUR=(SELECT NOMPRENOM FROM RESIDANTS WHERE RESIDANTS.RESIDANTID=VISITES.EXTERNALID) WHERE EMETTEUR IS NULL
GO