ALTER TABLE BADGES_ELEMENTS_TMP ADD BORDURE int null
GO
UPDATE BADGES_ELEMENTS_TMP SET BORDURE='0'
GO
ALTER TABLE BADGES_ELEMENTS ADD BORDURE int null
GO
UPDATE BADGES_ELEMENTS SET BORDURE='0'
GO
ALTER TABLE BADGES_ELEMENTS_TMP ALTER COLUMN VALEUR VARCHAR(4000)
GO
ALTER TABLE BADGES_ELEMENTS ALTER COLUMN VALEUR VARCHAR(4000)
GO