ALTER TABLE APPEL ADD RESIDANTID VARCHAR(14)
ALTER TABLE APPEL ADD INTERLOCUTEURID VARCHAR(14)
ALTER TABLE APPEL ADD SOCIETE VARCHAR(35)
ALTER TABLE APPEL ADD OBJET VARCHAR(4000)
ALTER TABLE APPEL ADD TELEPHONE VARCHAR(30)
ALTER TABLE APPEL ADD DATECREATION DATETIME
GO

UPDATE APPEL SET DATECREATION=QUAND WHERE DATECREATION IS NULL
GO