ALTER TABLE COLISEMIS ADD TRACKING_CRM VARCHAR(500);
GO
ALTER TABLE COLISEMIS ADD TRACKING_TRANSPORTEUR VARCHAR(500);
GO

ALTER TABLE COLISRECU ADD TRACKING_CRM VARCHAR(500);
GO
ALTER TABLE COLISRECU ADD TRACKING_TRANSPORTEUR VARCHAR(500);
GO

ALTER TABLE TYPEVISITE ADD TYPESORTIE INT DEFAULT(0);
GO

UPDATE TYPEVISITE SET TYPESORTIE=0;
GO
