ALTER TABLE LGRESERVATION ADD PAYANT INT DEFAULT 0;
GO
UPDATE LGRESERVATION SET PAYANT=0;
GO

ALTER TABLE GRPUSER ADD PAYANT INT DEFAULT 0;
GO
UPDATE GRPUSER SET PAYANT=0;
GO

ALTER TABLE BADGES_ELEMENTS_TMP ADD RANG INT;
GO
UPDATE BADGES_ELEMENTS_TMP SET RANG=0;
GO
ALTER TABLE BADGES_ELEMENTS ADD RANG INT;
GO
UPDATE BADGES_ELEMENTS SET RANG=0;
GO

ALTER TABLE BADGES_ELEMENTS_TMP ADD TRANSPARENT INT;
GO
UPDATE BADGES_ELEMENTS_TMP SET TRANSPARENT=0;
GO
ALTER TABLE BADGES_ELEMENTS ADD TRANSPARENT INT;
GO
UPDATE BADGES_ELEMENTS SET TRANSPARENT=0;
GO

CREATE TABLE dbo.FILTRE (
	LIBELLE VARCHAR(50),
	VALEUR VARCHAR(MAX),
	SITEID VARCHAR(14),
	DATECREATION DATETIME NOT NULL,
	DATEMAJ DATETIME NOT NULL,
	DATESYNCHRO DATETIME,
	CONSTRAINT FILTRE_PK PRIMARY KEY (LIBELLE,SITEID)
);
GO

--SQL SERVER
CREATE TABLE dbo.RAPPEL (
   RAPPELID INT IDENTITY(1,1) PRIMARY KEY,
   CODELGRESERVATION  VARCHAR(14),
   TEMPS VARCHAR(50),
   UNITE VARCHAR(50),
   DATERAPPEL DATETIME,
   ETAT INT DEFAULT 0,
   DATECREATION DATETIME,
   DATEMAJ      DATETIME
);
GO