
INSERT INTO EVENEMENT (EVENEMENTID,LIBELLE,RAPPORTID,CONSIGNEID,ISRAPPORT,DATEMAJ,DATECREATION,GRPEVENEMENTID,DATESYNCHRO) VALUES (-20,'CHECKLIST',0,0,0,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,-1,CURRENT_TIMESTAMP);
GO

CREATE TABLE dbo.CHECKLIST (
   CHECKLISTID INTEGER PRIMARY KEY,
   LIBELLE  VARCHAR(200),
   SITEID VARCHAR(14),
   NUMERO INTEGER,
   DATECREATION DATETIME,
   DATEMAJ      DATETIME
);
GO

CREATE TABLE dbo.OCHECKLIST (
   OCHECKLISTID INTEGER PRIMARY KEY,
   LIBELLE VARCHAR(200),
   NUMERO INTEGER,
   PERSONNELID INTEGER,
   UNOMPRENOM VARCHAR(300),
   ETAT VARCHAR(1000),
   DETAIL VARCHAR(4000),
   OBSERVATION VARCHAR(4000),
   CHKITEM VARCHAR(4000),
   SITEID VARCHAR(14),
   CHECKDATE DATETIME,
   DATECREATION DATETIME,
   DATEMAJ      DATETIME
);
GO

CREATE TABLE dbo.CHK_CHECKLIST (
   CHKID INTEGER,
   CHECKLISTID INTEGER,
   NORDER INTEGER
);
GO

CREATE TABLE dbo.CHK (
   CHKID INTEGER PRIMARY KEY,
   LIBELLE VARCHAR(400),
   DATECREATION DATETIME,
   DATEMAJ      DATETIME
);
GO
