ALTER TABLE REGLES ADD NATUREVISITE VARCHAR(14) DEFAULT('-2')
GO
CREATE TABLE dbo.VALIDATION_ENQUETE(
	[SITEID] [varchar](14) NULL,
	[EXTERNALID] [varchar](14) NOT NULL,
	[EXTERN_TYPE] [varchar](35) NOT NULL,
	[POLE] [varchar](100) NULL,
	[ECHANGES] [int] DEFAULT 0,
	[CUMUL] [varchar](50) NULL,
	[CODEACTIVITE] [varchar](70) NULL,
	[TYPEVISITE] [varchar](35) NOT NULL,
	[VISITEID] [varchar](14) NULL,
	[DEBUTPREVU] [datetime] NULL,
	[FINPREVU] [datetime] NULL,
	[DATESAISIE] [datetime] NULL,
	[CENTRE] [varchar](35) NULL,
	[CIVILITE] [varchar](30) NULL,
	[NOM] [varchar](35) NULL,
	[PRENOM] [varchar](35) NULL,
	[NOMJEUNEFILLE] [varchar](25) NULL,
	[DATENAISSANCE] [datetime] NULL,
	[LIEUNAISSANCE] [varchar](70) NULL,
	[PAYSNAISSANCE] [varchar](50) NULL,
	[NATIONALITE] [varchar](35) NULL,
	[ADRESSE] [varchar](150) NULL,
	[VILLE] [varchar](35) NULL,
	[CP] [varchar](10) NULL,
	[FONCTION] [varchar](35) NULL,
	[SOCIETE] [varchar](35) NULL,
	[ENQUETE] [int] DEFAULT (0),
	[ETAT] [int] DEFAULT (0),
	[RETOUR] [int] DEFAULT (0),
	[DATECREATION] [datetime] NULL,
	[DATERETOUR] [datetime] NULL,
 CONSTRAINT [PK_ENQUETE] PRIMARY KEY CLUSTERED ([EXTERNALID] ASC,[EXTERN_TYPE] ASC,	[TYPEVISITE] ASC)
) 
GO
ALTER TABLE IDENTITES ADD OFICHIERID INTEGER
GO
 
ALTER TABLE VISITE_REGLE ALTER COLUMN MES_RESI VARCHAR(4000)
GO
ALTER TABLE VISITE_REGLE ALTER COLUMN  MES_VALI VARCHAR(4000)
GO
ALTER TABLE VISITE_REGLE ALTER COLUMN MES_ACC VARCHAR(4000)
GO