DECLARE @TEMPCOUNT INT
SET @TEMPCOUNT=(SELECT TOP 1 NUMEROVISITE FROM VISITES ORDER BY NUMEROVISITE DESC)+100
DBCC CHECKIDENT (SEQ_NUM_BDG_EXT,RESEED,@TEMPCOUNT)
SET @TEMPCOUNT=(SELECT TOP 1 SEQ_IDENTITYID FROM SEQ_IDENTITY ORDER BY SEQ_IDENTITYID DESC)+100
DBCC CHECKIDENT (SEQ_NUM_BDG_RES,RESEED,@TEMPCOUNT)
DBCC CHECKIDENT (SEQ_NUM_BDG_VEH,RESEED,@TEMPCOUNT)
GO