ALTER TABLE ARTICLE ADD SITEID VARCHAR(14)
GO

--UPDATE ARTICLE SET SITEID='VPARDEFAUT'
--GO

CREATE TABLE dbo.JOUR_FERIE (
	JOUR_FERIEID INTEGER PRIMARY KEY,
	LIBELLE VARCHAR(100),
	DEBUT DATETIME,
	FIN DATETIME,
	DATECREATION DATETIME NOT NULL,
	DATEMAJ DATETIME NOT NULL
);
GO