 CREATE TABLE POSTE_CHECKLIST
(CHECKLISTID INT NOT NULL,
 POSTEID INT NOT NULL,
  PRIMARY KEY (CHECKLISTID, POSTEID)
  );
  GO
------

ALTER TABLE RAPPORT ALTER COLUMN NOMTABLE VARCHAR(50)
GO

INSERT INTO PARAMETRAGE(LIBELLE,VALEUR,SITEID,DATEMAJ,DATECREATION) VALUES ('FORM_VISITEUR','nom','ALL',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP)
INSERT INTO PARAMETRAGE(LIBELLE,VALEUR,SITEID,DATEMAJ,DATECREATION) VALUES ('FORM_VISITEUR_CONTROLE','0','ALL',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP)
INSERT INTO PARAMETRAGE(LIBELLE,VALEUR,SITEID,DATEMAJ,DATECREATION) VALUES ('FORM_VISITEUR_OBLIGATOIRE','1','ALL',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP)
GO
ALTER TABLE OJOURNAL ALTER COLUMN CODESALLE VARCHAR(30)
GO
ALTER VIEW [dbo].[VUE_AGENDAMISSION] (
 AGENDA_JOURID,STATUT, POSTEID,SITEID,MISSIONID, TYPE_JOUR,FINVALIDITE, JOURID,DATEOFWEEK,LIBELLE,HEURE,DUREE,TOLERANCE ) AS
  (
  SELECT  AGENDA_JOURID, AJ.STATUT, AJ.POSTEID,AJ.SITEID,AJ.MISSIONID,J.TYPE_JOUR,J.FIN_VALIDITE FINVALIDITE, J.JOURID,
	J.DATEOFWEEK,J.LIBELLE,CONVERT(DATETIME,CONVERT(VARCHAR(5),AJ.HEURE,108),103) HEURE,CONVERT(DATETIME,CONVERT(VARCHAR(5),M.DUREE,108),103) DUREE,CONVERT(DATETIME,convert(VARCHAR(5),AJ.TOLERANCE,108),103) TOLERANCE
	FROM AGENDA_JOUR AJ , MISSION M, JOUR J  WHERE M.MISSIONID=AJ.MISSIONID AND J.JOURID=AJ.JOURID AND J.JOURID =(SELECT  TOP 1 J.JOURID from JOUR J WHERE 
  (DATEPART(dw,J.FIN_VALIDITE)=DATEPART(dw,CURRENT_TIMESTAMP) AND J.TYPE_JOUR IS NULL 
  AND CONVERT(VARCHAR(10),J.FIN_VALIDITE,103)=CONVERT(VARCHAR(10),CURRENT_TIMESTAMP,103)) OR DATEPART(dw,CURRENT_TIMESTAMP)=J.DATEOFWEEK 
  
  OR (J.TYPE_JOUR='AFERIE' AND CONVERT(VARCHAR(5),CURRENT_TIMESTAMP,103)=CONVERT(VARCHAR(5),J.FIN_VALIDITE,103)
  )
  ORDER BY J.TYPE_JOUR)
 )
GO

CREATE TABLE [dbo].EQUIPE(
	[EQUIPEID] [int] PRIMARY KEY NOT NULL,
	[LIBELLE] [varchar](35) NULL,
	[DATECREATION] [datetime] NULL,
	[DATEMAJ] [datetime]NULL,
	[DATESYNCHRO] [datetime] NULL
)
GO
INSERT INTO EQUIPE (EQUIPEID,LIBELLE,DATECREATION,DATEMAJ,DATESYNCHRO) VALUES(1,'**********',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP)
GO
ALTER TABLE OJOURNAL ADD BATIMENTID VARCHAR(14) DEFAULT('VPARDEFAUT')
GO

ALTER table Rapport alter column details varchar (6000)
GO

ALTER TABLE PERSONNEL ADD EQUIPEID INT
GO
 ALTER TABLE CHECKLIST ADD CHKPRISEPOSTE INT DEFAULT(0)
 GO
 UPDATE CHECKLIST SET CHKPRISEPOSTE=0
GO