CREATE TABLE [dbo].[GRPUSER_DROITSTELEM](
	[GRPUSERID] [varchar](14) NOT NULL,
	[ID_DROITSTELEM] [varchar](14) NOT NULL,
 CONSTRAINT [PK_GRPUSER_ID_DROITSTELEM] PRIMARY KEY CLUSTERED 
(
	[GRPUSERID] ASC,
	[ID_DROITSTELEM] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

GO



ALTER TABLE SITE ADD WIFI_ENABLEPWD VARCHAR(200)
ALTER TABLE SITE ADD WIFI_PWD VARCHAR(200)

ALTER TABLE COLISEMIS ADD EMETTEURTYPE VARCHAR(15)
GO
ALTER TABLE COLISEMIS ADD CORRESTYPE VARCHAR(15)
GO

ALTER TABLE COLISRECU ADD EMETTEURTYPE VARCHAR(15)
GO
ALTER TABLE COLISRECU ADD CORRESTYPE VARCHAR(15)
GO



ALTER TABLE COLISEMIS DROP CONSTRAINT fk_cole_resiid
GO

ALTER TABLE COLISRECU DROP CONSTRAINT fk_colr_resiid
GO

 ALTER TABLE RESIDANTS ADD CCASSISTANTE INT DEFAULT(0)
 GO
 UPDATE RESIDANTS SET CCASSISTANTE='0'
 GO

ALTER TABLE RESIDANTS ALTER COLUMN MATRICULE VARCHAR(300)
GO
