CREATE TABLE CONFERENCE
(
	CONFERENCEID INT PRIMARY KEY,
	LIBELLE VARCHAR(50),
	DESCRIPTION VARCHAR(4000),
	STARTDATE DATETIME,
	ENDDATE DATETIME,
	TICKET VARCHAR(50),
	BADGEID VARCHAR(14),
	SITEID VARCHAR(14),
	OFICHIERID INT,
	DATECREATION DATE,
	DATEMAJ DATE
);
GO

INSERT INTO CONFERENCE (CONFERENCEID) VALUES (-1)