 ALTER TABLE BADGES_ELEMENTS_TMP ADD COMP_IF INT DEFAULT(0)
 ALTER TABLE BADGES_ELEMENTS_TMP ADD COMP_SIGNE VARCHAR(20)
 ALTER TABLE BADGES_ELEMENTS_TMP ADD  COMP_CHAMP VARCHAR(50)
 ALTER TABLE BADGES_ELEMENTS_TMP ADD COMP_VALEUR VARCHAR(25)
 GO
 ALTER TABLE BADGES_ELEMENTS ADD COMP_IF INT DEFAULT(0)
 ALTER TABLE BADGES_ELEMENTS ADD COMP_SIGNE VARCHAR(20)
 ALTER TABLE BADGES_ELEMENTS ADD COMP_CHAMP VARCHAR(50)
 ALTER TABLE BADGES_ELEMENTS ADD COMP_VALEUR VARCHAR(25)
 GO
 UPDATE  BADGES_ELEMENTS SET COMP_IF=0;
 GO
  UPDATE BADGES_ELEMENTS_TMP SET COMP_IF=0;
 GO
 