ALTER TABLE TYPEDOCUMENT ADD DEFAULT (2) FOR IN_PREENREG
GO
UPDATE TYPEDOCUMENT SET IN_PREENREG=2 WHERE TYPEDOCUMENTID<>-2
GO

UPDATE XANNEXE SET INFORMATION_TYPEID=1 WHERE XANNEXE_TYPEID=-2 AND ORIGINE='VISITES' AND INFORMATION_TYPEID=-1
UPDATE XANNEXE SET INFORMATION_TYPEID=2 WHERE XANNEXE_TYPEID=-2 AND ORIGINE='VISITES' AND INFORMATION_TYPEID=-2
UPDATE XANNEXE SET INFORMATION_TYPEID=3 WHERE XANNEXE_TYPEID=-2 AND ORIGINE='VISITES' AND INFORMATION_TYPEID=-3
UPDATE XANNEXE SET INFORMATION_TYPEID=4 WHERE XANNEXE_TYPEID=-2 AND ORIGINE='VISITES' AND INFORMATION_TYPEID=-4
UPDATE XANNEXE SET INFORMATION_TYPEID=5 WHERE XANNEXE_TYPEID=-2 AND ORIGINE='VISITES' AND INFORMATION_TYPEID=-5
UPDATE XANNEXE SET INFORMATION_TYPEID=6 WHERE XANNEXE_TYPEID=-2 AND ORIGINE='VISITES' AND INFORMATION_TYPEID=-6
UPDATE XANNEXE SET INFORMATION_TYPEID=7 WHERE XANNEXE_TYPEID=-2 AND ORIGINE='VISITES' AND INFORMATION_TYPEID=-7
UPDATE XANNEXE SET INFORMATION_TYPEID=8 WHERE XANNEXE_TYPEID=-2 AND ORIGINE='VISITES' AND INFORMATION_TYPEID=-8
UPDATE XANNEXE SET INFORMATION_TYPEID=9 WHERE XANNEXE_TYPEID=-2 AND ORIGINE='VISITES' AND INFORMATION_TYPEID=-9
UPDATE XANNEXE SET INFORMATION_TYPEID=10 WHERE XANNEXE_TYPEID=-2 AND ORIGINE='VISITES' AND INFORMATION_TYPEID=-10
UPDATE XANNEXE SET INFORMATION_TYPEID=11 WHERE XANNEXE_TYPEID=-2 AND ORIGINE='VISITES' AND INFORMATION_TYPEID=-11
UPDATE XANNEXE SET INFORMATION_TYPEID=12 WHERE XANNEXE_TYPEID=-2 AND ORIGINE='VISITES' AND INFORMATION_TYPEID=-12
UPDATE XANNEXE SET INFORMATION_TYPEID=13 WHERE XANNEXE_TYPEID=-2 AND ORIGINE='VISITES' AND INFORMATION_TYPEID=-13
GO

ALTER TABLE VISITES ALTER COLUMN LIEU VARCHAR(60)
GO
ALTER TABLE RESIDANTS ALTER COLUMN CPNOM VARCHAR(250)
GO
ALTER TABLE XANNEXE ADD ETAT INT
GO
ALTER TABLE XANNEXE ADD DATERETOUR DATETIME
GO

ALTER TABLE XANNEXE ADD DEFAULT (1) FOR ETAT
GO

UPDATE XANNEXE SET ETAT=1 WHERE 1=1
GO

CREATE TABLE dbo.SEQ_ZCL37_CTPUSER (
  SEQ_ZCL37_CTPUSERID  INTEGER NOT NULL IDENTITY,
  LIBELLE VARCHAR(35));
GO
CREATE TABLE dbo.SEQ_ZCL37_CPTPWD (
  SEQ_ZCL37_CTPUSERID  INTEGER NOT NULL IDENTITY,
  LIBELLE VARCHAR(35));
GO

ALTER TABLE SITE ADD WIFI_PRESENT INT;
ALTER TABLE SITE ADD WIFI_LIB VARCHAR(250);
ALTER TABLE SITE ADD WIFI_HOST VARCHAR(250);
ALTER TABLE SITE ADD WIFI_LOGIN VARCHAR(50);
ALTER TABLE SITE ADD WIFI_PWD VARCHAR(50);
ALTER TABLE SITE ADD WIFI_GRP VARCHAR(50);
ALTER TABLE SITE ADD WIFI_HFIN VARCHAR(10);
GO

ALTER TABLE VISITES ADD WIFI_LOGIN VARCHAR(50);
ALTER TABLE VISITES ADD WIFI_PWD VARCHAR(50);
GO

ALTER TABLE SITE ADD TLMQ_SORTIE_FVISITE INT;
ALTER TABLE SITE ADD TLMQ_SORTIE_JOUR INT;
ALTER TABLE SITE ADD TLMQ_PURGE_PREENRG INT;
ALTER TABLE SITE ADD TLMQ_HEURE_FIN VARCHAR(50);
ALTER TABLE SITE ADD TLMQ_HEURE_EXEC VARCHAR(50);
ALTER TABLE SITE ADD TLMQ_DERN_EXEC DATETIME;
GO

CREATE TABLE dbo.LOGWIFI (
  LOGWIFIID INTEGER NOT NULL,
  VISITEID VARCHAR(15),
  SITEID VARCHAR(15),
  WIFI_LOGIN VARCHAR(50),
  WIFI_PWD VARCHAR(50),
  WIFI_ETAT VARCHAR(50),
  DATECREATION DATETIME,
  DATEMAJ DATETIME,
  DATESYNCHRO DATETIME,
CONSTRAINT PK_LOGWIFIID PRIMARY KEY (LOGWIFIID));
GO

