ALTER TABLE REGLES ADD STATUT INT DEFAULT(1)
GO
ALTER TABLE REGLES ADD MESSAGEACC VARCHAR(100)
GO
UPDATE REGLES SET STATUT=1 WHERE STATUT IS NULL
GO
ALTER TABLE VISITE_REGLE ADD MES_ACC VARCHAR(100)
GO
ALTER TABLE VISITES ALTER COLUMN  FREE2 VARCHAR(250)
GO


