
ALTER TABLE ESVISITES_LOG ADD  TYPELECTEUR VARCHAR(40)
GO
ALTER TABLE VISITES_RESIDANTS ADD SITEID VARCHAR(14)
GO
ALTER TABLE VISITES_RESIDANTS ALTER COLUMN NOMPRENOM VARCHAR(70)
GO

ALTER TABLE REGLES ADD FREE5 INT DEFAULT(0)
GO
ALTER TABLE REGLES ADD FREE6 INT DEFAULT(0)
GO
ALTER TABLE REGLES ADD FREE7 VARCHAR(35)
GO
