CREATE TABLE dbo.LOGDB (
	LOGDBID INT IDENTITY(1,1) PRIMARY KEY,
	QUI VARCHAR(50),
	IP VARCHAR(50),
	URL VARCHAR(250),
	QUAND DATETIME,
	REQUETE VARCHAR(4000),
	LATABLE VARCHAR(100),
	ACTION VARCHAR(100),
	ID VARCHAR(100),
	DONNEES VARCHAR(4000),
	SITE VARCHAR(50),
	POSTE VARCHAR(50)
);
GO

CREATE TABLE dbo.RESIDANT_CTRL(
	RESIDANT_CTRLID INT NOT NULL PRIMARY KEY,
	RESIDANTID VARCHAR(14) NULL,
	ACTION INT NOT NULL,
	SITEID VARCHAR(14) NULL,
	SITE VARCHAR(80) NULL,
	EMETTEUR VARCHAR(80) NULL,
	DH_POST DATETIME NOT NULL,
	DH_PROCEED DATETIME NULL,
	IDENT VARCHAR(80) NOT NULL,
	STATUT INT NULL,
	TXT_ERR VARCHAR(80) NULL,
	DEB_VAL DATETIME NULL,
	FIN_VAL DATETIME NULL,
	NOM VARCHAR(40) NULL,
	PRENOM VARCHAR(40) NULL,
	SOCIETE VARCHAR(40) NULL,
	CODE_ANTENNE VARCHAR(40) NULL,
	MATRICULE VARCHAR(40) NULL,
	ANTI_RETOUR INT NULL,
	CODE_CLASSE INT NULL,
	DATA_01 VARCHAR(80) NULL,
	DATA_02 VARCHAR(80) NULL,
	DATA_03 VARCHAR(80) NULL,
	DATA_04 VARCHAR(80) NULL,
	DATA_05 VARCHAR(80) NULL,
	DATA_06 VARCHAR(80) NULL,
	DATA_07 VARCHAR(80) NULL,
	DATA_08 VARCHAR(80) NULL,
	DATA_09 VARCHAR(80) NULL,
	DATA_10 VARCHAR(80) NULL,
	ACCES_01 VARCHAR(4000) NULL,
	ACCES_02 VARCHAR(4000) NULL,
	ACCES_03 VARCHAR(4000) NULL,
	ACCES_04 VARCHAR(4000) NULL,
	ACCES_05 VARCHAR(4000) NULL,
	ACCES_06 VARCHAR(4000) NULL,
	ACCES_07 VARCHAR(4000) NULL,
	ACCES_08 VARCHAR(4000) NULL,
	ACCES_09 VARCHAR(4000) NULL,
	ACCES_10 VARCHAR(4000) NULL
);
GO

CREATE TABLE dbo.RESIDANT_SITE_PROFIL (
	RESIDANTID	VARCHAR(14),
	SITEID		VARCHAR(14),
	PROFIL_CTRLID	INTEGER,
	DATECREATION DATETIME,
	DATEMAJ		DATETIME,
	DATESYNCHRO	DATETIME
);
GO

CREATE TABLE dbo.ROI_LOG (
	ROI_LOGID INT,
	QUI VARCHAR(100),
	QUAND DATETIME,
	ACTION VARCHAR(100),
	QUOI VARCHAR(100),
	BADGE VARCHAR(100),
	MATRICULE VARCHAR(100),
	NOM VARCHAR(100),
	PRENOM VARCHAR(100),
	SOCIETE VARCHAR(100),
	SITE  VARCHAR(100)
);
GO

ALTER TABLE PROFIL_CTRL ADD PROFILDEFAULT INT DEFAULT 0;
GO
UPDATE PROFIL_CTRL SET PROFILDEFAULT=0;
GO
