CREATE TABLE [dbo].[ZCL15_CPPA](
	[IDCPPA] [varchar](14) NULL,
	[REGLEID] [varchar](14) NULL,
	[SITEID] [varchar](14) NULL,
	[SITE] [varchar](35) NULL,
	[SOCIETEID] [varchar](14) NULL,
	[SOCIETE] [varchar](35) NULL,
	[PAYSID] [varchar](14) NULL,
	[PAYS] [varchar](35) NULL,
	[TYPEVISITEID] [int] NULL,
	[TYPEVISITE] [varchar](70) NULL,
	[ETAT] [varchar](3) NULL,
	[DATESYNCHRO] [datetime] NULL
) 

GO


CREATE TABLE [dbo].[ZRR](
[ID_ZRR] [int] NOT NULL,
[CODE] [varchar](25) NULL,
[LIBELLE] [varchar](255) NULL,
[DEB_VALITE] [datetime] NULL,
[FIN_VALIDITE] [datetime] NULL,
[ACTIVE] [varchar](1) NULL,
[ZONE_PARTENAIRE] [varchar](1) NULL,
[CENTRE] [varchar](3) NULL,
[SITEID] [varchar](14) NULL,
[LOCAUX_SENSIBLES] [varchar](1) NULL,
[UCREA] [varchar](8) NULL,
[DCREA] [datetime] NULL,
[UDERMAJ] [varchar](8) NULL,
[DDERMAJ] [datetime] NULL,
CONSTRAINT [PK_ZRR] PRIMARY KEY CLUSTERED
(
      [ID_ZRR] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
 GO
 
 
ALTER TABLE MAIL ALTER COLUMN TOADDRESS VARCHAR(4000)
GO


INSERT INTO ZRR ([ID_ZRR],[CODE],[LIBELLE],[DEB_VALITE],[FIN_VALIDITE],[ACTIVE],[ZONE_PARTENAIRE],[SITEID],[CENTRE],[LOCAUX_SENSIBLES],[DCREA],[DDERMAJ]) VALUES (0,'**********','********** Libelle','01/05/2014','01/03/2113','O','N','VPARDEFAUT','','N',CURRENT_TIMESTAMP,CURRENt_TIMESTAMP) 
INSERT INTO ZRR ([ID_ZRR],[CODE],[LIBELLE],[DEB_VALITE],[FIN_VALIDITE],[ACTIVE],[ZONE_PARTENAIRE],[SITEID],[CENTRE],[LOCAUX_SENSIBLES],[DCREA],[DDERMAJ]) VALUES (1,'38B12ZRR12','38B12ZRR12 Libelle','01/03/2013','01/03/2013','O','N','VPARDEFAUT','','N',CURRENT_TIMESTAMP,CURRENt_TIMESTAMP)   
INSERT INTO ZRR ([ID_ZRR],[CODE],[LIBELLE],[DEB_VALITE],[FIN_VALIDITE],[ACTIVE],[ZONE_PARTENAIRE],[SITEID],[CENTRE],[LOCAUX_SENSIBLES],[DCREA],[DDERMAJ]) VALUES (2,'38B12ZRR13','38B12ZRR13 Libelle','01/03/2013','01/03/2014','O','O','VPARDEFAUT','','N',CURRENT_TIMESTAMP,CURRENt_TIMESTAMP)  
INSERT INTO ZRR ([ID_ZRR],[CODE],[LIBELLE],[DEB_VALITE],[FIN_VALIDITE],[ACTIVE],[ZONE_PARTENAIRE],[SITEID],[CENTRE],[LOCAUX_SENSIBLES],[DCREA],[DDERMAJ]) VALUES (3,'38B12ZRR14','38B12ZRR14 Libelle','01/03/2013','01/03/2015','O','N','VPARDEFAUT','','O',CURRENT_TIMESTAMP,CURRENt_TIMESTAMP)  
INSERT INTO ZRR ([ID_ZRR],[CODE],[LIBELLE],[DEB_VALITE],[FIN_VALIDITE],[ACTIVE],[ZONE_PARTENAIRE],[SITEID],[CENTRE],[LOCAUX_SENSIBLES],[DCREA],[DDERMAJ]) VALUES (4,'38B12ZRR15','38B12ZRR15 Libelle','01/03/2013','01/03/2016','O','N','VPARDEFAUT','','O',CURRENT_TIMESTAMP,CURRENt_TIMESTAMP)  
INSERT INTO ZRR ([ID_ZRR],[CODE],[LIBELLE],[DEB_VALITE],[FIN_VALIDITE],[ACTIVE],[ZONE_PARTENAIRE],[SITEID],[CENTRE],[LOCAUX_SENSIBLES],[DCREA],[DDERMAJ]) VALUES (5,'38B12ZRR16','38B12ZRR16 Libelle','01/03/2013','01/03/2017','O','O','VPARDEFAUT','','O',CURRENT_TIMESTAMP,CURRENt_TIMESTAMP)  
INSERT INTO ZRR ([ID_ZRR],[CODE],[LIBELLE],[DEB_VALITE],[FIN_VALIDITE],[ACTIVE],[ZONE_PARTENAIRE],[SITEID],[CENTRE],[LOCAUX_SENSIBLES],[DCREA],[DDERMAJ]) VALUES (6,'38B12ZRR17','38B12ZRR17 Libelle','01/03/2013','01/03/2018','O','O','VPARDEFAUT','','N',CURRENT_TIMESTAMP,CURRENt_TIMESTAMP)  
INSERT INTO ZRR ([ID_ZRR],[CODE],[LIBELLE],[DEB_VALITE],[FIN_VALIDITE],[ACTIVE],[ZONE_PARTENAIRE],[SITEID],[CENTRE],[LOCAUX_SENSIBLES],[DCREA],[DDERMAJ]) VALUES (7,'38B12ZRR18','38B12ZRR18 Libelle','01/03/2013','01/03/2019','N','N','VPARDEFAUT','','N',CURRENT_TIMESTAMP,CURRENt_TIMESTAMP)  
GO


ALTER TABLE dbo.VISITES ADD ZRR_CODE VARCHAR(25);
ALTER TABLE dbo.VISITES ADD ZRR_LIB VARCHAR(255);
ALTER TABLE dbo.VISITES ADD ZRR_LS VARCHAR(3);
GO
 
ALTER TABLE TYPEVISITE ALTER COLUMN TYPEVISITE VARCHAR(70)

--SUPPRIMER LES CODES ACTIVITES  RESIDANTS, TRAVAIL


INSERT INTO TYPECONSIGNE (TYPECONSIGNEID,TYPECONSIGNE,DATECREATION,DATEMAJ) VALUES (-3,'DEMANDE LPE',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
GO

ALTER TABLE CONSIGNE ADD SITEID VARCHAR(14);
GO
ALTER TABLE CONSIGNE ADD EMETTEUR_NOM VARCHAR(70);
GO
ALTER TABLE CONSIGNE ADD EMETTEUR_PROFIL VARCHAR(50);
GO
ALTER TABLE CONSIGNE ADD TYPEOBJET INT;
GO

CREATE TABLE [dbo].ZCL15_DEMANDE_LPE(
	[ZCL15_DEMANDE_LPEID] [varchar](14) NOT NULL PRIMARY KEY,
	[CONSIGNE1_ID] [varchar](14) NULL,
	[CONSIGNE2_ID] [varchar](14) NULL,
	[INTERLOCUTEURID] [varchar](14) NULL,
	[EME_SITEID] [varchar](14) NULL,
	[REM_SITEID] [varchar](14) NULL,
	[REC_SITEID] [varchar](14) NULL,
	[LPE_SAISIE_DCS] [datetime] NULL,
	[LPE_SAISIE_CACS] [datetime] NULL,
	[LPE_REMISE] [datetime] NULL,
	[LPE_ENVOI] [datetime] NULL,
	[LPE_INTERDICTION] [int] NULL,
	[DATECREATION] [datetime] NULL,
	[DATEMAJ] [datetime] NULL

 )
 GO
 
ALTER TABLE DROITSTELEM ADD VISITEUR VARCHAR(500);
GO