
 --Table GRPVALIDEUR
CREATE TABLE dbo.GRPVALIDEUR (
  GRPVALIDEURID INT NOT NULL,
  GRPVALIDEURN VARCHAR(100),
  RANGVALIDEUR INTEGER DEFAULT (0),
  AVIS INTEGER DEFAULT (0),
  DATECREATION DATETIME NOT NULL,
  DATEMAJ DATETIME NOT NULL,
  DATESYNCHRO DATETIME,
CONSTRAINT PK_GRPVALIDEURID PRIMARY KEY (GRPVALIDEURID));
GO

INSERT INTO GRPVALIDEUR (GRPVALIDEURID,GRPVALIDEURN,RANGVALIDEUR,DATECREATION,DATEMAJ) VALUES ('-1','GRPVALIDEUR1',1,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP)
GO
INSERT INTO GRPVALIDEUR (GRPVALIDEURID,GRPVALIDEURN,RANGVALIDEUR,DATECREATION,DATEMAJ) VALUES ('-2','GRPVALIDEUR2',2,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP)
GO
INSERT INTO GRPVALIDEUR (GRPVALIDEURID,GRPVALIDEURN,RANGVALIDEUR,DATECREATION,DATEMAJ) VALUES ('-3','GRPVALIDEUR3',3,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP)
GO
INSERT INTO GRPVALIDEUR (GRPVALIDEURID,GRPVALIDEURN,RANGVALIDEUR,DATECREATION,DATEMAJ) VALUES ('-4','GRPVALIDEUR4',4,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP)
GO

ALTER TABLE DROITSTELEM ADD GRPVALIDEURID INT NULL
GO

ALTER TABLE VISITES ADD GRPVALIDEUR2 VARCHAR(50) NULL
GO
ALTER TABLE VISITES ADD GRPVALIDEUR3 VARCHAR(50) NULL
GO
ALTER TABLE VISITES ADD GRPVALIDEUR4 VARCHAR(50) NULL
GO
ALTER TABLE VISITES ADD RANKLASTVAL INT NULL
GO
--METTRE A JOUR LES CHAMPS CI-DESSUS  A PARTIR DE ZCL01_VISITES

UPDATE VISITES SET NATUREVISITE='TRAVAIL' WHERE ISTATUT='EXTERIEUR'

 CREATE TABLE dbo.POSTE_TYPEVISITE (
  NOM_POSTE VARCHAR(50),
  TYPEVISITEID INT);
GO

ALTER TABLE REGLES ADD BYPASS INT DEFAULT(0)
GO
UPDATE REGLES SET BYPASS=0
GO

ALTER TABLE REGLES ADD CATEGORIE VARCHAR(30) NULL
GO

ALTER TABLE REGLES ADD GRPVALIDEURID INT NULL
GO

--FAIRE UPDATE
ALTER TABLE VISITE_REGLE ADD CATEGORIE VARCHAR(30)
GO

ALTER TABLE VISITES ADD CATEGORIE VARCHAR(30)
GO


UPDATE INTERLOCUTEUR SET NATIONALITEID='VPARDEFAUT' WHERE NATIONALITEID='FRANCE'
UPDATE RESIDANTS SET NATIONALITEID='VPARDEFAUT' WHERE NATIONALITEID='FRANCE'
UPDATE VILLE SET PAYSID='VPARDEFAUT' WHERE PAYSID='FRANCE'
GO

CREATE TABLE dbo.REGLE_GRPVALIDEUR (
  REGLEID INT NOT NULL,
  GRPVALIDEURID INT NOT NULL,
CONSTRAINT PK_REGLE_GRPVALIDEUR PRIMARY KEY (REGLEID,GRPVALIDEURID));
GO

CREATE TABLE dbo.LOCALISATION_USER (
  LOCALISATIONID INT NOT NULL,
  USERID VARCHAR(14) NOT NULL,
CONSTRAINT PK_LOCALISATION_USER PRIMARY KEY (USERID,LOCALISATIONID));
GO

ALTER TABLE INTERLOCUTEUR ADD DEPFRID INT NULL ;
GO
ALTER TABLE VISITES ADD IDEPFR VARCHAR(100);
GO

UPDATE TYPEDOCUMENT SET ISMULTISITE='1';
GO