UPDATE GRPSALLE SET CONFIDENTIEL=0 WHERE CONFIDENTIEL IS NULL;
GO

UPDATE LGRESERVATION SET CONFIDENTIEL=0 WHERE CONFIDENTIEL IS NULL;
GO

UPDATE SITE SET IS_SSR='0' WHERE IS_SSR IS NULL OR IS_SSR='';
GO

UPDATE CHECKLIST SET CHKPRISEPOSTE=0 WHERE CHKPRISEPOSTE IS NULL;
GO

UPDATE APPEL SET DATECREATION=QUAND WHERE DATECREATION IS NULL;
GO

UPDATE RESERVATION SET EMETTEURID=CODEANIMATEUR WHERE EMETTEURID IS NULL;
GO

UPDATE BADGES_ELEMENTS_TMP SET BORDURE='0' WHERE BORDURE IS NULL OR BORDURE='';
GO

UPDATE BADGES_ELEMENTS SET BORDURE='0' WHERE BORDURE IS NULL OR BORDURE='';
GO

UPDATE VISITES SET EMETTEUR=(SELECT NOMPRENOM FROM RESIDANTS WHERE RESIDANTS.RESIDANTID=VISITES.EXTERNALID) WHERE EMETTEUR IS NULL OR EMETTEUR='';
GO

UPDATE RESERVATION SET EMETTEUR=(SELECT FULLNAME FROM USERS WHERE USERID=RESERVATION.USERID) WHERE EMETTEUR IS NULL OR EMETTEUR='';
GO

UPDATE TYPEDOCUMENT SET INTER_EFFECT='2' WHERE INTER_EFFECT IS NULL OR INTER_EFFECT='';
GO

UPDATE COLISRECU SET SERVICEID='VPARDEFAUT' WHERE SERVICEID IS NULL OR SERVICEID='';
GO
UPDATE COLISEMIS SET SERVICEID='VPARDEFAUT' WHERE SERVICEID IS NULL OR SERVICEID='';
GO

UPDATE COLISRECU SET NATURECOLISID='0' WHERE NATURECOLISID IS NULL OR NATURECOLISID='';
GO
UPDATE COLISEMIS SET NATURECOLISID='0' WHERE NATURECOLISID IS NULL OR NATURECOLISID='';
GO
UPDATE COLISEMIS SET NATURECOLISID='-1' WHERE LETTRECOLIS='2' AND (NATURECOLISID IS NULL OR NATURECOLISID='');
GO

UPDATE DROITSTELEM SET ETRANGER=0 WHERE ETRANGER IS NULL;
GO
UPDATE RESIDANTS SET ETRANGER=0 WHERE ETRANGER IS NULL;
GO

UPDATE VISITES SET TYPEVISITEID='0' WHERE TYPEVISITEID='' OR TYPEVISITEID IS NULL;
GO

UPDATE VISITES SET STATUTPARKING='0' WHERE STATUTPARKING IS NULL OR STATUTPARKING='';
GO

UPDATE RESERVATION SET SALLE_VALIDEE=0 WHERE SALLE_VALIDEE IS NULL;
GO

UPDATE SITE SET TIMEZONE='+01:00' WHERE TIMEZONE IS NULL OR TIMEZONE='';
GO

UPDATE RESIDANTS SET ISNOTIFIED=1 WHERE ISNOTIFIED IS NULL;
GO

UPDATE LGPARTICIPANT SET ISNOTIFIED=1 WHERE ISNOTIFIED IS NULL;
GO

UPDATE GRPSALLE SET CONFIDENTIEL=0 WHERE CONFIDENTIEL IS NULL;
GO