INSERT INTO STATUTPARKING (CODE_STATUT,STATUT_NAME) VALUES ('0','Non affecté');


INSERT INTO STATUTPARKING (CODE_STATUT,STATUT_NAME) VALUES ('1','Attribué');


INSERT INTO VERSION_SFW SELECT '8.0.5','S00012','29559',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,'DD/MM/YYYY','' WHERE NOT EXISTS (SELECT VERSION FROM VERSION_SFW);


INSERT INTO TYPEIDENTITE (TYPEIDENTITEID,LIBELLE,DATEMAJ,DATECREATION) VALUES (0,'**********',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);


INSERT INTO TYPEIDENTITE (TYPEIDENTITEID,LIBELLE,DATEMAJ,DATECREATION,DATESYNCHRO) VALUES (-1,'Passeport',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);


INSERT INTO TYPEIDENTITE (TYPEIDENTITEID,LIBELLE,DATEMAJ,DATECREATION,DATESYNCHRO) VALUES (-2,'CNI',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);


INSERT INTO TYPEIDENTITE (TYPEIDENTITEID,LIBELLE,DATEMAJ,DATECREATION,DATESYNCHRO) VALUES (-3,'Titre de séjour',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);


INSERT INTO TYPEIDENTITE (TYPEIDENTITEID,LIBELLE,DATEMAJ,DATECREATION,DATESYNCHRO) VALUES (-4,'CIE',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);


INSERT INTO TYPEIDENTITE (TYPEIDENTITEID,LIBELLE,DATEMAJ,DATECREATION,DATESYNCHRO) VALUES (-5,'VISA',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);


INSERT INTO TYPEADRESSE (TYPEADRESSEID,TYPEADRESSE,DATECREATION,DATEMAJ) VALUES (0,'**********',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);


INSERT INTO TYPEADRESSE (TYPEADRESSEID,TYPEADRESSE,DATECREATION,DATEMAJ) VALUES (-1,'Taxis',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);


INSERT INTO TYPECONSIGNE (TYPECONSIGNEID,TYPECONSIGNE,DATECREATION,DATEMAJ) VALUES (-1,'Message',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);


INSERT INTO TYPECONSIGNE (TYPECONSIGNEID,TYPECONSIGNE,DATECREATION,DATEMAJ) VALUES (-2,'Consigne',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);


INSERT INTO TYPEVISITE (TYPEVISITEID,TYPEVISITE,DATECREATION,DATEMAJ) VALUES (0,'Visite',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);


INSERT INTO TYPEVISITE (TYPEVISITEID,TYPEVISITE,DATECREATION,DATEMAJ) VALUES (-2,'Tous',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);


INSERT INTO TYPEVISITE (TYPEVISITEID,TYPEVISITE,DATECREATION,DATEMAJ) VALUES (-1,'Résidant',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);


INSERT INTO TYPEVISITE (TYPEVISITEID,TYPEVISITE,TRAVAIL,DATECREATION,DATEMAJ) VALUES (-3,'Travail',1,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);


INSERT INTO NATURE (NATUREID,LIBELLE,ABREGE,TVISITE,INTERDIT,DEBUTINTERDIT,FININTERDIT,DATECREATION,DATEMAJ) VALUES ('VPARDEFAUT','**********','*','0','0',CURRENT_TIMESTAMP-1,CURRENT_TIMESTAMP+36000,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);


INSERT INTO NATURE (NATUREID,LIBELLE,ABREGE,TVISITE,INTERDIT,DEBUTINTERDIT,FININTERDIT,DATECREATION,DATEMAJ) VALUES ('-1','Société extérieur','','0','0',CURRENT_TIMESTAMP-1,CURRENT_TIMESTAMP+36000,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP)


INSERT INTO NATURE (NATUREID,LIBELLE,ABREGE,TVISITE,INTERDIT,DEBUTINTERDIT,FININTERDIT,DATECREATION,DATEMAJ) VALUES ('-2','Résidant','','0','0',CURRENT_TIMESTAMP-1,CURRENT_TIMESTAMP+36000,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP)


INSERT INTO FONCTION (CODEFONCTION,LIBELLE,DATEMAJ,DATECREATION) VALUES (0,'**********',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);


INSERT INTO AMENAGEMENT (CODEAMENAGEMENT,LIBELLE,DATECREATION,DATEMAJ) VALUES ('VPARDEFAUT','Standard',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);


INSERT INTO CIVILITE (CODECIVILITE,CIVILITE,LIBELLECOURT,DATECREATION,DATEMAJ) VALUES (0,'','',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);


INSERT INTO CIVILITE (CODECIVILITE,CIVILITE,LIBELLECOURT,DATECREATION,DATEMAJ) VALUES (1,'Monsieur','M.',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);


INSERT INTO CIVILITE (CODECIVILITE,CIVILITE,LIBELLECOURT,DATECREATION,DATEMAJ) VALUES (2,'Madame','Mme',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);


INSERT INTO CIVILITE (CODECIVILITE,CIVILITE,LIBELLECOURT,DATECREATION,DATEMAJ) VALUES (3,'Mademoiselle','Mlle',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);


INSERT INTO EQUIPEMENTFIXE (CODEEQUIPEMENTFIXE,LIBELLE,DATECREATION,DATEMAJ) VALUES ('E1','Rétroprojecteur',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);


INSERT INTO PLANS (PLANID,LIBELLE,DATECREATION,DATEMAJ) VALUES ('VPARDEFAUT','**********',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);


INSERT INTO SITE (SITEID,LIBELLE,IS_SECURED,PAYS,DATEMAJ,DATECREATION) VALUES ('VPARDEFAUT','**********',0,'France',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);


INSERT INTO STATUTRESERVATION (CODESTATUT,LIBELLE,COLOR,COLORNAME,CONFIRMATION,NBJOURAD,NBJOURAR,NBJOURDELAI,DATECREATION,DATEMAJ,LIBELLE_EN)
              VALUES ('VPARDEFAUT','Confirmée',47616,'Green',1,0,0,0,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,'Confirmed');
INSERT INTO STATUTRESERVATION (CODESTATUT,LIBELLE,COLOR,COLORNAME,CONFIRMATION,NBJOURAD,NBJOURAR,NBJOURDELAI,DATECREATION,DATEMAJ,LIBELLE_EN)
              VALUES ('-1','Annulée',255,'Red',2,0,0,0,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,'Cancelled');


INSERT INTO TRANCHE (CODETRANCHE,LIBELLE,DATECREATION,DATEMAJ) VALUES ('VPARDEFAUT','9H00-10H00',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);


INSERT INTO TVA (CODETVA,LIBELLE,TAUXTVA,DATECREATION,DATEMAJ) VALUES ('VPARDEFAUT','Taxe sur la valeur ajouté','19.6',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);


INSERT INTO TYPERESERVATION (CODETYPERESERVATION,LIBELLE,DATEMAJ,DATECREATION) VALUES ('VPARDEFAUT','Réunion',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);


INSERT INTO TYPETARIF (CODETYPETARIF,LIBELLE,COEFICIENT,DATECREATION) VALUES ('VPARDEFAUT','Plein','1',CURRENT_TIMESTAMP);


INSERT INTO VILLE (CODEVILLE,CODEPOSTAL,VILLE,DATECREATION,DATEMAJ) VALUES ('VPARDEFAUT','75002','Paris',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);


INSERT INTO BATIMENT (BATIMENTID,SITEID,LIBELLE,NOBAT,DATEMAJ,DATECREATION) VALUES ('VPARDEFAUT','VPARDEFAUT','**********','',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);


INSERT INTO ETAGES (ETAGEID,BATIMENTID,DATECREATION,DATEMAJ) VALUES ('VPARDEFAUT','VPARDEFAUT',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);


INSERT INTO BUREAUX (BUREAUID,ETAGEID,SORTORDER,BUREAU,DATECREATION,DATEMAJ) VALUES ('VPARDEFAUT','VPARDEFAUT',0,'**********',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);


INSERT INTO SOCIETE (SOCIETEID,ISRESIDANT,NOM,INTERDIT,DEBUTINTERDIT,FININTERDIT,DATEMAJ,DATECREATION) VALUES ('VPARDEFAUT',0,'**********',0,CURRENT_TIMESTAMP-1,CURRENT_TIMESTAMP+36000,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);


INSERT INTO DEPARTEMENT (DEPTID,SOCIETEID,LIBELLE,DATECREATION,DATEMAJ) VALUES ('VPARDEFAUT','VPARDEFAUT','**********',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);


INSERT INTO SERVICE (SERVICEID,DEPTID,LIBELLE,DATECREATION,DATEMAJ) VALUES ('VPARDEFAUT','VPARDEFAUT','**********',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);


INSERT INTO MARQUE (CODEMARQUE,LIBELLE,DATECREATION,DATEMAJ) VALUES ('MA1','Cola',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);


INSERT INTO FAMILLE (CODEFAMILLE,LIBELLE,MARGE,DATECREATION,DATEMAJ) VALUES ('F1','Personnel','1',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);


INSERT INTO SOUSFAMILLE (CODESOUSFAMILLE,CODEFAMILLE,SOUSFAMILLE,MARGE,DATECREATION,DATEMAJ) VALUES ('SF1','F1','Confort','1',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);


INSERT INTO ARTICLE (CODEARTICLE,CODEFAMILLE,CODESOUSFAMILLE,CODETVA,FULLNAME,LIBELLE,PRIXACHATHT,PRIXVENTEHT,PRIXVENTETTC,REFERENCE,TAUXTVA,DATEMAJ,DATECREATION,GESTION)
              VALUES ('CA2','F1','SF1','TVA','Boisson gazeuse','Boisson','5','7','10','REF002','20',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,0);


INSERT INTO ARTICLEDEFAULT (CODEARTICLEDEFAULT,CODETYPEDEFAULT,CODEARTICLE,QUANTITE,SORTORDER,DATECREATION,DATEMAJ)
              VALUES ('CAD2','COD1','CA2','2','5',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);


/*INSERT INTO CFGPRODUIT (CODETVA,MARGE) VALUES ('VPARDEFAUT','1');
*/

INSERT INTO CFGGSALLESPARAM (HEUREOUVERTURE,HEUREFERMETURE,TRANCHE,REFRESERVATION,RESA_ORDRE_SALLE,RESA_PRESTA_STYLE,FILTRE_ORDRE_TRI)
              SELECT convert(SMALLDATETIME,'09:00',108),convert(SMALLDATETIME,'17:00',108),convert(SMALLDATETIME,'01:00',108),'REF001',0,0,0 WHERE NOT EXISTS (SELECT HEUREOUVERTURE FROM CFGGSALLESPARAM);


/*
INSERT INTO CFGDEFAULTAGENDA (CODECIVILITE) VALUES (0);
*/

INSERT INTO CFGGSALLESDEFAULT (CODETYPERESERVATION,CODESTATUT,CODEAMMENAGEMENT,CODETYPETARIF,HEUREDEBUT,HEUREFIN,PREPARATIONDEFAUT,RANGEMENTDEFAUT)
              SELECT 'VPARDEFAUT','VPARDEFAUT','VPARDEFAUT','VPARDEFAUT',convert(SMALLDATETIME,'09:00',108),convert(SMALLDATETIME,'17:00',108),convert(SMALLDATETIME,'00:10',108),convert(SMALLDATETIME,'00:10',108) WHERE NOT EXISTS (SELECT CODETYPERESERVATION FROM CFGGSALLESDEFAULT);


INSERT INTO SALLE (SITEID,SOCIETEID,BATIMENTID,CODESALLE,LIBELLE,NOSALLE,SORTORDER,DATEMAJ,DATECREATION)
              VALUES ('VPARDEFAUT','VPARDEFAUT','VPARDEFAUT','VPARDEFAUT','Salle jaune','01',1,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);


INSERT INTO AMENAGSALLE (CODESALLE,CODEAMENAGEMENT,DATEMAJ,DATECREATION) VALUES ('VPARDEFAUT','VPARDEFAUT',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP)


INSERT INTO RESIDANTS (SOCIETEID,RESIDANTID,PLANID,BUREAUID,CODEFONCTION,SERVICEID,THEPASSWORD,THELOGIN,SITEID,BATIMENTID,ISRESIDENT,ISACTIF,INTERDIT,NATUREID,NATIONALITEID,DATEMAJ,DATECREATION,DEBUTINTERDIT,FININTERDIT,HABILITATIONVISITE,CODECIVILITE,CIVILITE,NOMPRENOM,NOM,PRENOM,BOITEPOSTALE)
              VALUES ('VPARDEFAUT','VPARDEFAUT','VPARDEFAUT','VPARDEFAUT',0,'VPARDEFAUT','23Turbig0','ADM','VPARDEFAUT','VPARDEFAUT',1,1,0,'VPARDEFAUT','VPARDEFAUT',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP+(100*365),'1',1,'M.','RESIDANT INCONNU','RESIDANT','INCONNU','0');


INSERT INTO RESIDANTS (SOCIETEID,RESIDANTID,PLANID,BUREAUID,CODEFONCTION,SERVICEID,THEPASSWORD,THELOGIN,SITEID,BATIMENTID,ISRESIDENT,ISACTIF,INTERDIT,NATUREID,NATIONALITEID,DATEMAJ,DATECREATION,NOMPRENOM,NOM,PRENOM,DEBUTINTERDIT,FININTERDIT,HABILITATIONVISITE,CODECIVILITE,CIVILITE,BOITEPOSTALE)
              VALUES ('VPARDEFAUT','123','VPARDEFAUT','VPARDEFAUT',0,'VPARDEFAUT','TAFFIN','TAFFIN','VPARDEFAUT','VPARDEFAUT',1,1,0,'VPARDEFAUT','VPARDEFAUT',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,'TAFFIN JEAN MARIE','TAFFIN','JEAN MARIE',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP+(100*365),'1',1,'M.','0');


INSERT INTO GRPUSER (GRPUSERID, LIBELLE, NIVEAU, STATUT, SURRESERVATION, RESAPERIODIQUE, ACCESDRAGDROP, PLANNING, RESA, PRESTA, DATECREATION, DATEMAJ, STATUTCHECK) VALUES ('ADMINISTRATEUR','Administrateur','2','VPARDEFAUT','1','1','1','100','000000111011','10',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,1);


INSERT INTO GRPUSER (GRPUSERID, LIBELLE, NIVEAU, STATUT, SURRESERVATION, RESAPERIODIQUE, ACCESDRAGDROP, PLANNING, RESA, PRESTA, DATECREATION, DATEMAJ, STATUTCHECK) VALUES ('VPARDEFAUT','Utilisateur','1','VPARDEFAUT','0','0','0','010','111000000011','00',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,0);


INSERT INTO RESIDANTS (SOCIETEID,RESIDANTID,PLANID,BUREAUID,CODEFONCTION,SERVICEID,THEPASSWORD,THELOGIN,SITEID,BATIMENTID,ISRESIDENT,ISACTIF,INTERDIT,NATUREID,NATIONALITEID,DATEMAJ,DATECREATION,NOMPRENOM,NOM,PRENOM,DEBUTINTERDIT,FININTERDIT,HABILITATIONVISITE,CODECIVILITE,CIVILITE,BOITEPOSTALE)
              VALUES ('VPARDEFAUT','124','VPARDEFAUT','VPARDEFAUT',0,'VPARDEFAUT','TAFFIN','TAFFIN','VPARDEFAUT','VPARDEFAUT',1,1,0,'VPARDEFAUT','VPARDEFAUT',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,'ROLLANDEAU FRANCOIS','ROLLANDEAU','FRANCOIS',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP+(100*365),'1',1,'M.','0');


INSERT INTO USERS (USERTYPEID,GVACCESS,USERID,CIVILITEID,FIRSTNAME,FULLNAME,THELOGIN,THEPASSWORD,DATEMAJ,DATECREATION,SITE,SITEID,TYPEUSERID,ID_DROITSTAXI,ID_DROITSTELEM,ENABLED)
              VALUES ('ADM','20595','VPARDEFAUT',0,'TAFFIN','ADM','23Turbig0','2206',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,'**********','VPARDEFAUT',-1,1,-1,1);


INSERT INTO USERS (USERID, CIVILITEID, FIRSTNAME, USERTYPEID, GVACCESS, EXTERNALID, FULLNAME, PROFIL_ID_ORGA, PROFIL_ID_INTER,PROFIL_SURBOOKING,THELOGIN, THEPASSWORD, USERTYPE, DATEMAJ, DATECREATION, GRPUSERID,ENABLED,GSACCESS)
              VALUES ('GESROOM',0,'ADMINISTRATEUR','Administrateur',78847,'VPARDEFAUT','ADMINISTRATEUR','VPARDEFAUT','VPARDEFAUT','0','ADM','ADM',1,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,'ADMINISTRATEUR',1,1);


INSERT INTO USERS (USERTYPEID,GVACCESS,USERID,CIVILITEID,FIRSTNAME,FULLNAME,THELOGIN,THEPASSWORD,DATEMAJ,DATECREATION,SITE,SITEID,TYPEUSERID,ID_DROITSTAXI,ID_DROITSTELEM,ENABLED)
              VALUES ('ADM','20595','123',0,'TELEMAQUE','TELEMAQUE','TELEMAQUE','TELEMAQUE',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,'**********','VPARDEFAUT',-1,1,-2,1);


INSERT INTO PARAMETRES (PREENREG,SECURITE,I_PLAN,IMPRESSION,DATESORTIVI,SORTIVI,PURGEVP,APPETEL,MONOSOC,MODULE,GESPHOTO,TRCLUNIK,TYPEANNU,IMPORTAUTO,GESTCASIER,NBESSAIS,DATECREATION,DATEMAJ,INFOBULLES,REFIMPORTATION,SORTIFINVI)
              SELECT 0,0,0,0,CURRENT_TIMESTAMP,1,1,0,0,0,0,0,0,0,0,10,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,0,'1',0 WHERE NOT EXISTS (SELECT PREENREG FROM PARAMETRES);


INSERT INTO IMPUTATION_TYPE (IMPUTATION_TYPEID,LIBELLE) VALUES ('VPARDEFAUT','Code Imputation');


INSERT INTO IMPUTATION_TYPE (IMPUTATION_TYPEID,LIBELLE) VALUES ('1','Code projet');


INSERT INTO STATUTRESERVATION_ETAT VALUES (0,'Apres demande de réservation',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,NULL);;


INSERT INTO STATUTRESERVATION_ETAT VALUES (1,'avant réunion',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,NULL);;


INSERT INTO STATUTRESERVATION_SET VALUES (0,'Pas de relance',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,NULL);;


INSERT INTO STATUTRESERVATION_SET VALUES (1,'Relance',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,NULL);;


INSERT INTO STATUTRESERVATION_SET VALUES (2,'Confirmer',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,NULL);;


INSERT INTO IMPUTATION (IMPUTATIONID, LIBELLE, LIBELLE2, IMPUTATION_TYPEID, DATECREATION, DATEMAJ) VALUES ('VPARDEFAUT','', '*****', 'VPARDEFAUT', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);


INSERT INTO GRPSALLE (GRPSALLEID, LIBELLE, HEUREDEBUT, HEUREFIN, OPENPRERESA, CLOSEPRERESA, RESA, DATECREATION, DATEMAJ,SITEID) VALUES ('Everyone','Everyone','00:00','00:00',0,0,'1',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,'ALL');


INSERT INTO ZONE (ZONEID, ZONENOM, ZONERESPONSABLE, DATEMAJ, DATECREATION) VALUES ('VPARDEFAUT','TOUTES ZONES','**********',CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);


-- 2004_02_06
INSERT INTO CONSTEMP_SITE (CONSIGNETEMPID,SITEID) (SELECT CONSIGNETEMPID,SITEID FROM CONSIGNETEMP);


INSERT INTO CONSTEMP_POSTE (CONSIGNETEMPID,POSTEID) (SELECT CONSIGNETEMPID,POSTEID FROM CONSIGNETEMP);


INSERT INTO CONSTEMP_QUALIF (CONSIGNETEMPID,QUALIFID) (SELECT CONSIGNETEMPID,QUALIFID FROM CONSIGNETEMP);


INSERT INTO TYPE_MISSION (TYPE_MISSIONID, LIBELLE, DATEMAJ, DATECREATION, DATESYNCHRO) VALUES (-1,'Prise de poste',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);


INSERT INTO TYPE_MISSION (TYPE_MISSIONID, LIBELLE, DATEMAJ, DATECREATION, DATESYNCHRO) VALUES (-2,'Fin de poste',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);


INSERT INTO TYPE_MISSION (TYPE_MISSIONID, LIBELLE, DATEMAJ, DATECREATION, DATESYNCHRO) VALUES (-3,'Sans fin',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);


INSERT INTO TYPE_MISSION (TYPE_MISSIONID, LIBELLE, DATEMAJ, DATECREATION, DATESYNCHRO) VALUES (-4,'Mission',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);


INSERT INTO ODROIT (ODROITID,LIBELLE,OMACCESS,DATEMAJ,DATECREATION) VALUES (1,'Administrateur',8191,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);


INSERT INTO ODROIT (ODROITID,LIBELLE,OMACCESS,DATEMAJ,DATECREATION) VALUES (2,'Agent',513,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);


INSERT INTO VSERVICE (VSERVICEID, LIBELLE, DATEMAJ, DATECREATION, DATESYNCHRO) VALUES (0,'**********',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);


INSERT INTO OCONSIGNE (OCONSIGNEID,LIBELLE) VALUES (0,'**********');


INSERT INTO QUALIF (QUALIFID, LIBELLE, DATEMAJ, DATECREATION, DATESYNCHRO) VALUES (0,'**********',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);


INSERT INTO RAPPORT (RAPPORTID, LIBELLE, NOMTABLE, DETAILS, AUTEURID, DATEMAJ, DATECREATION, DATESYNCHRO) VALUES (0,'**********','*','*',0,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);


--INSERT INTO POSTE (POSTEID,LIBELLE,DATECREATION,DATEMAJ) VALUES (0,'**********',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO POSTE (POSTEID,LIBELLE,REP_LOCAL,DATECREATION,DATEMAJ) VALUES (-1,'SYSTEME','SYSTEME',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);


INSERT INTO PERSONNEL (PERSONNELID,THELOGIN,THEPASSWORD,NOM,PRENOM,DATECREATION,DATEMAJ) VALUES (-1,'Ommnigarde','OM','***','***',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);


INSERT INTO PERSONNEL (PERSONNELID,THEPASSWORD,THELOGIN,NOM,PRENOM,DATE_NAISSANCE,DATE_EMBAUCHE,DATE_ARRIVEE,DEBUT_VALIDITE,FIN_VALIDITE,QUALIFID,CODEFONCTION,MEDICAL_LAST,MEDICAL_NEXT,ODROITID,SITEID,DATEMAJ,DATECREATION) VALUES (1,'23Turbig0','ADM','TAFFIN','Jean-marie','01/01/1950','01/01/1950','01/01/1950','01/01/1950','01/01/1950',0,0,'01/01/1950','01/01/1950',1,'VPARDEFAUT',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);


INSERT INTO EVENEMENT_SITE SELECT EVENEMENTID,'VPARDEFAUT' AS SITEID FROM EVENEMENT WHERE EVENEMENTID >0;


INSERT INTO EVENEMENT (EVENEMENTID,LIBELLE,RAPPORTID,CONSIGNEID,ISRAPPORT,DATEMAJ,DATECREATION,DATESYNCHRO) VALUES (-1,'Prise de poste',0,0,0,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);


INSERT INTO EVENEMENT (EVENEMENTID,LIBELLE,RAPPORTID,CONSIGNEID,ISRAPPORT,DATEMAJ,DATECREATION,DATESYNCHRO) VALUES (-2,'Fin de poste',0,0,0,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);


INSERT INTO EVENEMENT (EVENEMENTID,LIBELLE,RAPPORTID,CONSIGNEID,ISRAPPORT,DATEMAJ,DATECREATION,DATESYNCHRO) VALUES (-3,'Mission',0,0,0,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);


INSERT INTO EVENEMENT (EVENEMENTID,LIBELLE,RAPPORTID,CONSIGNEID,ISRAPPORT,DATEMAJ,DATECREATION,DATESYNCHRO) VALUES (-4,'Mission retard',0,0,0,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);


INSERT INTO EVENEMENT (EVENEMENTID,LIBELLE,RAPPORTID,CONSIGNEID,ISRAPPORT,DATEMAJ,DATECREATION,DATESYNCHRO) VALUES (-5,'Ouverture appli',0,0,0,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);


INSERT INTO EVENEMENT (EVENEMENTID,LIBELLE,RAPPORTID,CONSIGNEID,ISRAPPORT,DATEMAJ,DATECREATION,DATESYNCHRO) VALUES (-6,'Fermeture appli',0,0,0,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);


INSERT INTO EVENEMENT (EVENEMENTID,LIBELLE,RAPPORTID,CONSIGNEID,ISRAPPORT,DATEMAJ,DATECREATION,DATESYNCHRO) VALUES (-7,'Connexion',0,0,0,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);


INSERT INTO EVENEMENT (EVENEMENTID,LIBELLE,RAPPORTID,CONSIGNEID,ISRAPPORT,DATEMAJ,DATECREATION,DATESYNCHRO) VALUES (-8,'Message ponctuel',0,0,0,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);


INSERT INTO EVENEMENT (EVENEMENTID,LIBELLE,RAPPORTID,CONSIGNEID,ISRAPPORT,DATEMAJ,DATECREATION,DATESYNCHRO) VALUES (-9,'Mission supprimée',0,0,0,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);


INSERT INTO EVENEMENT (EVENEMENTID,LIBELLE,RAPPORTID,CONSIGNEID,ISRAPPORT,DATEMAJ,DATECREATION,DATESYNCHRO) VALUES (-10,'Mission suspendue',0,0,0,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);


INSERT INTO EVENEMENT (EVENEMENTID,LIBELLE,RAPPORTID,CONSIGNEID,ISRAPPORT,DATEMAJ,DATECREATION,DATESYNCHRO) VALUES (-11,'Agent',0,0,0,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);


INSERT INTO EVENEMENT (EVENEMENTID,LIBELLE,RAPPORTID,CONSIGNEID,ISRAPPORT,DATEMAJ,DATECREATION,DATESYNCHRO) VALUES (-12,'Mouvement',0,0,0,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);


INSERT INTO EVENEMENT (EVENEMENTID,LIBELLE,RAPPORTID,CONSIGNEID,ISRAPPORT,DATEMAJ,DATECREATION,DATESYNCHRO) VALUES (-13,'Probleme materiel',0,0,0,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);


INSERT INTO EVENEMENT (EVENEMENTID,LIBELLE,RAPPORTID,CONSIGNEID,ISRAPPORT,DATEMAJ,DATECREATION,DATESYNCHRO,GRPEVENEMENTID) VALUES (1,'Incident',0,0,0,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,0);


INSERT INTO EVENEMENT (EVENEMENTID,LIBELLE,RAPPORTID,CONSIGNEID,ISRAPPORT,DATEMAJ,DATECREATION,DATESYNCHRO) VALUES (-14,'MC email automatique',0,0,0,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);


INSERT INTO EVENEMENT (EVENEMENTID,LIBELLE,RAPPORTID,CONSIGNEID,ISRAPPORT,DATEMAJ,DATECREATION,DATESYNCHRO) VALUES (-15,'Alarme',0,0,0,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);


INSERT INTO EVENEMENT (EVENEMENTID,LIBELLE,RAPPORTID,CONSIGNEID,ISRAPPORT,DATEMAJ,DATECREATION,DATESYNCHRO) VALUES (-16,'Visiteur non prevu',0,0,0,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);


INSERT INTO EVENEMENT (EVENEMENTID,LIBELLE,RAPPORTID,CONSIGNEID,ISRAPPORT,DATEMAJ,DATECREATION,DATESYNCHRO) VALUES (-17,'Colis non prevu',0,0,0,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);


INSERT INTO EVENEMENT (EVENEMENTID,LIBELLE,RAPPORTID,CONSIGNEID,ISRAPPORT,DATEMAJ,DATECREATION,DATESYNCHRO) VALUES (-18,'Objet perdu',0,0,0,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);


INSERT INTO EVENEMENT (EVENEMENTID,LIBELLE,RAPPORTID,CONSIGNEID,ISRAPPORT,DATEMAJ,DATECREATION,DATESYNCHRO) VALUES (-19,'Clé en retard',0,0,0,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);


INSERT INTO EVENEMENT (EVENEMENTID,LIBELLE,RAPPORTID,CONSIGNEID,ISRAPPORT,DATEMAJ,DATECREATION,GRPEVENEMENTID,DATESYNCHRO) VALUES (-20,'Checklist',0,0,0,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,-1,CURRENT_TIMESTAMP);


INSERT INTO JOUR (JOURID, LIBELLE, TYPE_JOUR, CL, DATEOFWEEK, DEBUT_VALIDITE, FIN_VALIDITE, DATEMAJ, DATECREATION) VALUES (1,'DIMANCHE','Dimanche',7,1,CURRENT_TIMESTAMP,'01/01/2110',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);


INSERT INTO JOUR (JOURID, LIBELLE, TYPE_JOUR, CL, DATEOFWEEK, DEBUT_VALIDITE, FIN_VALIDITE, DATEMAJ, DATECREATION) VALUES (2,'LUNDI','Lundi',1,2,CURRENT_TIMESTAMP,'01/01/2110',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);


INSERT INTO JOUR (JOURID, LIBELLE, TYPE_JOUR, CL, DATEOFWEEK, DEBUT_VALIDITE, FIN_VALIDITE, DATEMAJ, DATECREATION) VALUES (3,'MARDI','Mardi',2,3,CURRENT_TIMESTAMP,'01/01/2110',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);


INSERT INTO JOUR (JOURID, LIBELLE, TYPE_JOUR, CL, DATEOFWEEK, DEBUT_VALIDITE, FIN_VALIDITE, DATEMAJ, DATECREATION) VALUES (4,'MERCREDI','Mercredi',3,4,CURRENT_TIMESTAMP,'01/01/2110',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);


INSERT INTO JOUR (JOURID, LIBELLE, TYPE_JOUR, CL, DATEOFWEEK, DEBUT_VALIDITE, FIN_VALIDITE, DATEMAJ, DATECREATION) VALUES (5,'JEUDI','Jeudi',4,5,CURRENT_TIMESTAMP,'01/01/2110',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);


INSERT INTO JOUR (JOURID, LIBELLE, TYPE_JOUR, CL, DATEOFWEEK, DEBUT_VALIDITE, FIN_VALIDITE, DATEMAJ, DATECREATION) VALUES (6,'VENDREDI','Vendredi',5,6,CURRENT_TIMESTAMP,'01/01/2110',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);


INSERT INTO JOUR (JOURID, LIBELLE, TYPE_JOUR, CL, DATEOFWEEK, DEBUT_VALIDITE, FIN_VALIDITE, DATEMAJ, DATECREATION) VALUES (7,'SAMEDI','Samedi',6,7,CURRENT_TIMESTAMP,'01/01/2110',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);


INSERT INTO ADRESSE (ADRESSEID,TYPEADRESSEID,SOCIETE,NOM,DATECREATION,DATEMAJ) VALUES ('VPARDEFAUT',0,'********','********',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);


INSERT INTO GUICHET (GUICHETID,SITEID,GUICHET,BOITE,DATECREATION,DATEMAJ) VALUES ('VPARDEFAUT','VPARDEFAUT','Administration','B',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);


INSERT INTO INTERLOCUTEUR (SOCIETEID,INTERLOCUTEURID,CODECIVILITE,CODEFONCTION,PAYS,CIVILITE,NOMPRENOM,NOM,NOMJEUNEFILLE,PRENOM,
FONCTION,TELEPHONE,EMAIL,GSM,FAX,IMMATRICULATION,INTERDIT,DEBUTINTERDIT,FININTERDIT,NATUREID,NATIONALITEID,DATEMAJ,DATECREATION,SOCIETE,DATENAISSANCE,FINVALIDITEAUTO,PHONKEY)
VALUES
('VPARDEFAUT','2l6tAq4h207',1,0,'France','Mr','VISITEUR','VISITEUR','','','**********','01 25 46 85 92','','06 13 25 46 95',
'','','0',CURRENT_TIMESTAMP-1,CURRENT_TIMESTAMP+100*365,'VPARDEFAUT','VPARDEFAUT',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,'**********','05/08/1960',CURRENT_TIMESTAMP+365,1);


INSERT INTO INTERLOCUTEUR (SOCIETEID,INTERLOCUTEURID,CODECIVILITE,CODEFONCTION,PAYS,CIVILITE,NOMPRENOM,NOM,NOMJEUNEFILLE,PRENOM,
FONCTION,TELEPHONE,EMAIL,GSM,FAX,IMMATRICULATION,INTERDIT,DEBUTINTERDIT,FININTERDIT,NATUREID,NATIONALITEID,DATEMAJ,DATECREATION,SOCIETE,DATENAISSANCE,FINVALIDITEAUTO,PHONKEY)
VALUES
('VPARDEFAUT','258964',1,0,'FRANCE','Mr','DELEGUE','DELEGUE','','','**********','01 25 46 85 92','','06 13 25 46 95',
'','','0',CURRENT_TIMESTAMP-1,CURRENT_TIMESTAMP+100*365,'VPARDEFAUT','VPARDEFAUT',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,'**********','05/08/1960',CURRENT_TIMESTAMP+365,2);


INSERT INTO INTERLOCUTEUR (SOCIETEID,INTERLOCUTEURID,CODECIVILITE,CODEFONCTION,PAYS,CIVILITE,NOMPRENOM,NOM,NOMJEUNEFILLE,PRENOM,
FONCTION,TELEPHONE,EMAIL,GSM,FAX,IMMATRICULATION,INTERDIT,DEBUTINTERDIT,FININTERDIT,NATUREID,NATIONALITEID,DATEMAJ,DATECREATION,SOCIETE,DATENAISSANCE,FINVALIDITEAUTO,PHONKEY)
VALUES
('VPARDEFAUT','123',1,0,'FRANCE','Mr','VISITEUR Parking','VISITEUR','','Parking','**********','01 25 46 85 92','','06 13 25 46 95',
'','','0',CURRENT_TIMESTAMP-1,CURRENT_TIMESTAMP+100*365,'VPARDEFAUT','VPARDEFAUT',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,'**********','05/08/1960',CURRENT_TIMESTAMP+365,1);


INSERT INTO RESIDANTS (SOCIETEID,RESIDANTID,PLANID,BUREAUID,CODEFONCTION,SERVICEID,THEPASSWORD,THELOGIN,SITEID,BATIMENTID,ISRESIDENT,ISACTIF,INTERDIT,NATUREID,NATIONALITEID,DATEMAJ,DATECREATION,NOMPRENOM,NOM,PRENOM,DEBUTINTERDIT,FININTERDIT,HABILITATIONVISITE,CODECIVILITE,CIVILITE,BOITEPOSTALE)
	VALUES ('VPARDEFAUT','456','VPARDEFAUT','VPARDEFAUT',0,'VPARDEFAUT','RESIDANT','RESIDANT','VPARDEFAUT','VPARDEFAUT',1,1,0,'VPARDEFAUT','VPARDEFAUT',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,'RESIDANT Parking','RESIDANT','Parking',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP+(100*365),'1',1,'M.','0');


INSERT INTO TQ_COMMUNE (NOM_IMG_DEF,HAUTEUR,LARGEUR,PERMIS_TRAVAIL,PARAM_ALTAIR,TITRE,BDG_FREE1,BDG_FREE2,BDG_FREE3,BDG_FREE4,BDG_FREE5,BDG_FREE6,BDG_FREE7,BDG_FREE8,BDG_FREE9,PLANS_FREE1,PLANS_FREE2,PLANS_FREE3,PLANS_FREE4,PLANS_FREE5,PLANS_FREE6,PLANS_FREE7,PLANS_FREE8,PLANS_FREE9,VALIDATION_RESID,MODIF_VISITEUR_PREENREG,MODIF_VISITEUR_ENCOURS,MODIF_VISITEUR_TERMINE) SELECT 'capture_webcam_telemaque2.bmp',198,150,0,0,'Telemaque C/S','GUICHET','FINPREVU','NUMEROVISITE','NUMEROBADGE','PIECE','HEUREVISIJOUR','IMMATRICULATION','TELR','BUREAUR','CIVILITEV','CIVILITER','SITER','BATIMENT','ETAGE','BUREAUR','PLANLIBELLE','SERVICER','TELR','0,1',0,0,0 WHERE NOT EXISTS (SELECT NOM_IMG_DEF FROM TQ_COMMUNE);


INSERT INTO TQ_POSTE (NOM_POSTE,NB_CAR_RECHERCHE,DELAI_RECHERCHE,SEPARATEUR,CHAMP1,CHAMP2,CHAMP3,CHAMP4,CHAMP5,CHAMP6,CHAMP7,CHAMP8,CHAMP9,POS_CHAMP1,POS_CHAMP2,POS_CHAMP3,POS_CHAMP4,POS_CHAMP5,POS_CHAMP6,POS_CHAMP7,POS_CHAMP8,POS_CHAMP9,CRITERE_IMPORT_CHAMP,BLOCAGE_HDEBUT_VISITE,RESID_CTRL_HORAIRE_MSG,RESID_CTRL_HORAIRE_VERROU,RESID_HORAIRE_VERROU,FERMETURE_FENETRE_APRES_BDG,HISTORIQUE,MODIF_CHAMPS_OBS,MSG_ALERTEXJOUR_AVANTJ,MSG_CONFIR_ES,MSG_INFOR_FORMATIONS_PERIMEES,AFFICHAGE_DATE_SI_STATUT_LONG,BLOCAGE_SI_FORM_PERIMEE,SELECT_MODEL_BDG,SELECT_IMPR_BDG,ELARGIR_PAR_DEFAUT,TRACAGE,FICHIER_TRACE,ENVOI_BDG_MANUEL,ENVOI_BDG_AUTO,GENERATION_BDG,DEBUT_CODE,MILIEU_CHAMP,MILIEU_FORMAT,FIN_CODE,MODE_ES_VIS_RES,VISITEUR_CTRL_PLUS,SITE,SITEID,GUICHET,GUICHETID) VALUES ('VPARDEFAUT',1,700,'{Tab}','Civ','Nom','Prenom','Societe','Fonction','Nom jeune fille','Date naissance','Lieu naissance','Nationalite',1,2,3,4,5,6,7,8,9,'000001110',0,1,0,0,1,0,0,10,0,0,0,0,0,0,0,0,'Trace.log',1,0,1,'V','NUMEROVISITE','NUMBER/6','0',0,0,'**********','VPARDEFAUT','**********','VPARDEFAUT');


INSERT INTO TYPEUSER (USERID,LIBELLE,DATECREATION,DATEMAJ) VALUES (-1,'ADM',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);


INSERT INTO TYPEUSER (USERID,LIBELLE,DATECREATION,DATEMAJ) VALUES (-2,'Accueil',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);


INSERT INTO TYPEUSER (USERID,LIBELLE,DATECREATION,DATEMAJ) VALUES (-3,'Tech',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);


INSERT INTO TYPEUSER (USERID,LIBELLE,DATECREATION,DATEMAJ) VALUES (-4,'Parking',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);


INSERT INTO ETATAPP (ETATID,ETATNOM,VISIBLE,APP,DATECREATION,DATEMAJ) VALUES ('ETAT_ETRANGERS','ListeEtranger',1,'TQ',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);


INSERT INTO ETATAPP (ETATID,ETATNOM,VISIBLE,APP,DATECREATION,DATEMAJ) VALUES ('BLACKLISTEVIS','BlackListeVis',1,'TQ',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);


INSERT INTO ETATAPP (ETATID,ETATNOM,VISIBLE,APP,DATECREATION,DATEMAJ) VALUES ('BLACKLISTERES','BlackListeRes',1,'TQ',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);


INSERT INTO ETATAPP (ETATID,ETATNOM,VISIBLE,APP,DATECREATION,DATEMAJ) VALUES ('ETAT_VISITEUR_PAYS','NbVisiteursParPays',1,'TQ',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);


INSERT INTO ETATAPP (ETATID,ETATNOM,VISIBLE,APP,DATECREATION,DATEMAJ) VALUES ('ETAT_VISITE_DETAIL','VisiteDetailVisiteur',1,'TQ',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);


INSERT INTO ETATAPP (ETATID,ETATNOM,VISIBLE,APP,DATECREATION,DATEMAJ) VALUES ('NBBDGIMPRRES','NbBdgImprRes',1,'TQ',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);


INSERT INTO ETATAPP (ETATID,ETATNOM,VISIBLE,APP,DATECREATION,DATEMAJ) VALUES ('LISTE_PHR_PHS','PHR_PHS',1,'TQ',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);


INSERT INTO ETATAPP (ETATID,ETATNOM,VISIBLE,APP,DATECREATION,DATEMAJ) VALUES ('LISTE_ENQUETES','Enquete',1,'TQ',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);


INSERT INTO ETATAPP (ETATID,ETATNOM,VISIBLE,APP,DATECREATION,DATEMAJ) VALUES ('LISTE_PASSAGE_SELF','Repas',1,'TQ',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);


INSERT INTO ETATAPP (ETATID,ETATNOM,VISIBLE,APP,DATECREATION,DATEMAJ) VALUES ('ETAT_ETRANGERS_DETAILS','ListeEtrangerDetails',1,'TQ',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);


INSERT INTO ETATAPP (ETATID,ETATNOM,VISIBLE,APP,DATECREATION,DATEMAJ) VALUES ('STATISTIQUE','JVisite',1,'TQ_NonVisible',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);


INSERT INTO ETATAPP (ETATID,ETATNOM,VISIBLE,APP,DATECREATION,DATEMAJ) VALUES ('STATISTIQUE_OBS','JVisiteObs',1,'TQ_NonVisible',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);


INSERT INTO ETATAPP (ETATID,ETATNOM,VISIBLE,APP,DATECREATION,DATEMAJ) VALUES ('PRE_ENREG','PreEnreg',1,'TQ_NonVisible',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);


INSERT INTO ETATAPP (ETATID,ETATNOM,VISIBLE,REQUETE,FILTRE,APP,DATECREATION,DATEMAJ) VALUES ('VISITES_DEBLOQUEES', 'VisitesDebloquees', 1, '', '', 'TQ', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);


INSERT INTO ETATAPP (ETATID,ETATNOM,VISIBLE,REQUETE,FILTRE,APP,DATECREATION,DATEMAJ) VALUES ('ETAT_ESVISITE_LOG', 'ListePassagesES', 1, '', '', 'TQ', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);


INSERT INTO CFGETAT (CFGETATID,ETATNOM,VISIBLE,REQUETE,FILTRE,DATECREATION,DATEMAJ) VALUES
  ('Reservationdessalles1','Reservation des salles',1,'EtatReservationSalleAccueil','',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);


INSERT INTO CFGETAT (CFGETATID,ETATNOM,VISIBLE,REQUETE,FILTRE,DATECREATION,DATEMAJ) VALUES
  ('Equipementdessalles1','Equipement des salles',1,'EtatEquipementdessalles','AND F.LIBELLE<>''ALIMENTAIRE''',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);


INSERT INTO CFGETAT (CFGETATID,ETATNOM,VISIBLE,REQUETE,FILTRE,DATECREATION,DATEMAJ) VALUES
  ('Restauration1','Restauration',1,'EtatRestaurations','AND F.LIBELLE=''ALIMENTAIRE'' AND UPPER(A.LIBELLE)<>UPPER(''jetons'') AND UPPER(A.LIBELLE)<>UPPER(''Places pour repas'')',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);


INSERT INTO CFGETAT (CFGETATID,ETATNOM,VISIBLE,REQUETE,FILTRE,DATECREATION,DATEMAJ) VALUES
  ('Reservations1','Reservations',1,'EtatReservationListe','',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);


INSERT INTO CFGETAT (CFGETATID,ETATNOM,VISIBLE,REQUETE,FILTRE,DATECREATION,DATEMAJ) VALUES
  ('Places1','Places',1,'EtatPlaces','AND F.LIBELLE=''ALIMENTAIRE'' AND SF.SOUSFAMILLE=''PLACES''',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);


INSERT INTO CFGETAT (CFGETATID,ETATNOM,VISIBLE,REQUETE,FILTRE,DATECREATION,DATEMAJ) VALUES
  ('Jetons1','Jetons',1,'EtatJetons','AND F.LIBELLE=''ALIMENTAIRE'' AND UPPER(A.LIBELLE)=UPPER(''jetons'')',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);


INSERT INTO CFGETAT (CFGETATID,ETATNOM,VISIBLE,REQUETE,FILTRE,DATECREATION,DATEMAJ) VALUES
  ('Facturation1','Facturation Matériels et Prestations',1,'EtatFacturationMaterielEtPrestation','AND ( F.LIBELLE=''MATERIEL TECHNIQUE'' OR F.LIBELLE=''PRESTATIONS TECHNIQUES'')',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);


INSERT INTO CFGETAT (CFGETATID,ETATNOM,VISIBLE,REQUETE,FILTRE,DATECREATION,DATEMAJ) VALUES
  ('FacturationSalles1','Facturation Salles',1,'EtatFacturationSalle','',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);


INSERT INTO CFGETAT (CFGETATID,ETATNOM,VISIBLE,REQUETE,FILTRE,DATECREATION,DATEMAJ) VALUES
  ('Restaurationsur7j1','Restauration sur 7j',1,'EtatRestaurationSurXJours','AND F.LIBELLE=''RESTAURATION''',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);


INSERT INTO CFGETAT (CFGETATID,ETATNOM,VISIBLE,REQUETE,FILTRE,DATECREATION,DATEMAJ) VALUES
  ('Reservation1','Reservation des salles',1,'EtatReservationTypeReunion','',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);


INSERT INTO CFGETAT (CFGETATID,ETATNOM,VISIBLE,REQUETE,FILTRE,DATECREATION,DATEMAJ) VALUES
  ('Equipementdessalles2','Equipement des salles',1,'EtatEquipementdessallesTypeReunion','AND F.LIBELLE<>''RESTAURATION''',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);


INSERT INTO CFGETAT (CFGETATID,ETATNOM,VISIBLE,REQUETE,FILTRE,DATECREATION,DATEMAJ) VALUES
  ('Prvisionpause1','Prévision pauses',1,'EtatPrevisionPauses','AND F.LIBELLE=''RESTAURATION'' AND SF.SOUSFAMILLE=''PAUSES''',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);


INSERT INTO CFGETAT (CFGETATID,ETATNOM,VISIBLE,REQUETE,FILTRE,DATECREATION,DATEMAJ) VALUES
  ('Bonderestauration1','Bon de restauration',1,'EtatBonDeRestauration','AND F.LIBELLE=''RESTAURATION'' AND SF.SOUSFAMILLE=''REPAS''',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);


INSERT INTO CFGETAT (CFGETATID,ETATNOM,VISIBLE,REQUETE,FILTRE,DATECREATION,DATEMAJ) VALUES
  ('Salledereunionavecprestationrestaurant1','Salle de reunion avec prestation restaurant',1,'EtatReservationSallePrestationRestaurant','AND F.LIBELLE=''RESTAURATION'' ',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);


INSERT INTO CFGETAT (CFGETATID,ETATNOM,VISIBLE,REQUETE,FILTRE,DATECREATION,DATEMAJ) VALUES
  ('gsrm011','Réservation par tranche horaire',1,'','',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);


INSERT INTO CFGETAT (CFGETATID,ETATNOM,VISIBLE,REQUETE,FILTRE,DATECREATION,DATEMAJ) VALUES
  ('gsrm021','Taux d''occupation par société',1,'','',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);


INSERT INTO CFGETAT (CFGETATID,ETATNOM,VISIBLE,REQUETE,FILTRE,DATECREATION,DATEMAJ) VALUES
  ('gsrm031','Liste des réservations par société',1,'','',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);


INSERT INTO ROLE_AUTRES (USERID,SITE,SOC_RES,DIRECTIONS,PAYS,UTILISATEURS,TYPEUSER,PROFILUSER,MODIFAFF,DATECREATION,DATEMAJ) VALUES (-1,1,1,1,1,1,1,1,1,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);


INSERT INTO ROLE_PARAMETRAGES (USERID,PARAMETRAGES_GENERAUX,PERIPHERIQUES,PRESENTATION,BADGES,DATECREATION,DATEMAJ) VALUES (-1,1,1,1,1,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);


INSERT INTO ROLE_RESTES (USERID,STAT,DATECREATION,DATEMAJ) VALUES (-1,1,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);


INSERT INTO GRPEVENEMENT (GRPEVENEMENTID,LIBELLE,DATECREATION,DATEMAJ) VALUES (0,'SURETE',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);


INSERT INTO GRPEVENEMENT (GRPEVENEMENTID,LIBELLE,DATECREATION,DATEMAJ) VALUES (-1,'SYSTEME',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);


INSERT INTO GRPEVENEMENT (GRPEVENEMENTID,LIBELLE,DATECREATION,DATEMAJ) VALUES (1,'SECURITE',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);


INSERT INTO RONDEMOTCLE (RONDEMOTCLEID,LIBELLE,DATECREATION,DATEMAJ) VALUES (1,'NON PREVU',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);


INSERT INTO RONDEMOTCLE (RONDEMOTCLEID,LIBELLE,DATECREATION,DATEMAJ) VALUES (2,'INCIDENT',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);


INSERT INTO RONDEMOTCLE (RONDEMOTCLEID,LIBELLE,DATECREATION,DATEMAJ) VALUES (3,'DEJA LU',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);


INSERT INTO RONDEMOTCLE (RONDEMOTCLEID,LIBELLE,DATECREATION,DATEMAJ) VALUES (4,'NON DEFINI',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);


INSERT INTO RONDEMOTCLE (RONDEMOTCLEID,LIBELLE,DATECREATION,DATEMAJ) VALUES (5,'MANQUE',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);


INSERT INTO INTERLOCUTEUR (SOCIETEID,INTERLOCUTEURID,CODECIVILITE,CODEFONCTION,PAYS,CIVILITE,NOMPRENOM,NOM,NOMJEUNEFILLE,PRENOM,
FONCTION,TELEPHONE,EMAIL,GSM,FAX,IMMATRICULATION,INTERDIT,DEBUTINTERDIT,FININTERDIT,NATUREID,NATIONALITEID,DATEMAJ,DATECREATION,SOCIETE,DATENAISSANCE,FINVALIDITEAUTO,PHONKEY)
VALUES
('VPARDEFAUT','VPARDEFAUT',1,0,'FRANCE','Mr','VISITEUR INCONNU','VISITEUR','','INCONNU','**********','01 25 46 85 92','','06 13 25 46 95',
'','','0',CURRENT_TIMESTAMP-1,CURRENT_TIMESTAMP+100*365,'VPARDEFAUT','VPARDEFAUT',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,'**********','05/08/1960',CURRENT_TIMESTAMP+365,1);


INSERT INTO ZCL27_PARAMETRE (H_LISTE, FREQ_EMPL, H_LOG, H_SORTIE1, H_SORTIE2, DATECREATION, DATEMAJ) SELECT '01/01/2000 06:00:00', 500, '01/01/2000 22:00:00', '01/01/2000 13:00:00', '01/01/2000 23:00:00', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP WHERE NOT EXISTS (SELECT H_LISTE FROM ZCL27_PARAMETRE);


INSERT INTO DEPFR (DEPFRID,NUMERO,DEPARTEMENT,PREFERTURE,REGION,DATECREATION,DATEMAJ) VALUES (1,'001','Ain','Bourg-en-Bresse','Rhône-Alpes',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);


INSERT INTO DEPFR (DEPFRID,NUMERO,DEPARTEMENT,PREFERTURE,REGION,DATECREATION,DATEMAJ) VALUES (2,'002','Aisne','Laon','Picardie',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);


INSERT INTO DEPFR (DEPFRID,NUMERO,DEPARTEMENT,PREFERTURE,REGION,DATECREATION,DATEMAJ) VALUES (3,'003','Allier','Moulins','Auvergne',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);


INSERT INTO DEPFR (DEPFRID,NUMERO,DEPARTEMENT,PREFERTURE,REGION,DATECREATION,DATEMAJ) VALUES (4,'004','Alpes de Hautes-Provence','Digne','Provence-Alpes-Côte d''Azur',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);


INSERT INTO DEPFR (DEPFRID,NUMERO,DEPARTEMENT,PREFERTURE,REGION,DATECREATION,DATEMAJ) VALUES (5,'005','Hautes-Alpes','Gap','Provence-Alpes-Côte d''Azur',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);


INSERT INTO DEPFR (DEPFRID,NUMERO,DEPARTEMENT,PREFERTURE,REGION,DATECREATION,DATEMAJ) VALUES (6,'006','Alpes-Maritimes','Nice','Provence-Alpes-Côte d''Azur',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);


INSERT INTO DEPFR (DEPFRID,NUMERO,DEPARTEMENT,PREFERTURE,REGION,DATECREATION,DATEMAJ) VALUES (7,'007','Ardèche','Privas','Rhône-Alpes',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);


INSERT INTO DEPFR (DEPFRID,NUMERO,DEPARTEMENT,PREFERTURE,REGION,DATECREATION,DATEMAJ) VALUES (8,'008','Ardennes','Charleville-Mézières','Champagne-Ardenne',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);


INSERT INTO DEPFR (DEPFRID,NUMERO,DEPARTEMENT,PREFERTURE,REGION,DATECREATION,DATEMAJ) VALUES (9,'009','Ariège','Foix','Midi-Pyrénées',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);


INSERT INTO DEPFR (DEPFRID,NUMERO,DEPARTEMENT,PREFERTURE,REGION,DATECREATION,DATEMAJ) VALUES (10,'010','Aube','Troyes','Champagne-Ardenne',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);


INSERT INTO DEPFR (DEPFRID,NUMERO,DEPARTEMENT,PREFERTURE,REGION,DATECREATION,DATEMAJ) VALUES (11,'011','Aude','Carcassonne','Languedoc-Roussillon',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);


INSERT INTO DEPFR (DEPFRID,NUMERO,DEPARTEMENT,PREFERTURE,REGION,DATECREATION,DATEMAJ) VALUES (12,'012','Aveyron','Rodez','Midi-Pyrénées',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);


INSERT INTO DEPFR (DEPFRID,NUMERO,DEPARTEMENT,PREFERTURE,REGION,DATECREATION,DATEMAJ) VALUES (13,'013','Bouches-du-Rhône','Marseille','Provence-Alpes-Côte d''Azur',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);


INSERT INTO DEPFR (DEPFRID,NUMERO,DEPARTEMENT,PREFERTURE,REGION,DATECREATION,DATEMAJ) VALUES (14,'014','Calvados','Caen','Basse-Normandie',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);


INSERT INTO DEPFR (DEPFRID,NUMERO,DEPARTEMENT,PREFERTURE,REGION,DATECREATION,DATEMAJ) VALUES (15,'015','Cantal','Aurillac','Auvergne',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);


INSERT INTO DEPFR (DEPFRID,NUMERO,DEPARTEMENT,PREFERTURE,REGION,DATECREATION,DATEMAJ) VALUES (16,'016','Charente','Angoulême','Poitou-Charentes',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);


INSERT INTO DEPFR (DEPFRID,NUMERO,DEPARTEMENT,PREFERTURE,REGION,DATECREATION,DATEMAJ) VALUES (17,'017','Charente-Maritime','La Rochelle','Poitou-Charentes',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);


INSERT INTO DEPFR (DEPFRID,NUMERO,DEPARTEMENT,PREFERTURE,REGION,DATECREATION,DATEMAJ) VALUES (18,'018','Cher','Bourges','Centre',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);


INSERT INTO DEPFR (DEPFRID,NUMERO,DEPARTEMENT,PREFERTURE,REGION,DATECREATION,DATEMAJ) VALUES (19,'019','Corrèze','Tulle','Limousin',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);


INSERT INTO DEPFR (DEPFRID,NUMERO,DEPARTEMENT,PREFERTURE,REGION,DATECREATION,DATEMAJ) VALUES (20,'02A','Corse-du-Sud','Ajaccio','Corse',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);


INSERT INTO DEPFR (DEPFRID,NUMERO,DEPARTEMENT,PREFERTURE,REGION,DATECREATION,DATEMAJ) VALUES (21,'02B','Haute-Corse','Bastia','Corse',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);


INSERT INTO DEPFR (DEPFRID,NUMERO,DEPARTEMENT,PREFERTURE,REGION,DATECREATION,DATEMAJ) VALUES (22,'021','Côte-d''Or','Dijon','Bourgogne',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);


INSERT INTO DEPFR (DEPFRID,NUMERO,DEPARTEMENT,PREFERTURE,REGION,DATECREATION,DATEMAJ) VALUES (23,'022','Côtes d''Armor','Saint-Brieuc','Bretagne',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);


INSERT INTO DEPFR (DEPFRID,NUMERO,DEPARTEMENT,PREFERTURE,REGION,DATECREATION,DATEMAJ) VALUES (24,'023','Creuse','Guéret','Limousin',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);


INSERT INTO DEPFR (DEPFRID,NUMERO,DEPARTEMENT,PREFERTURE,REGION,DATECREATION,DATEMAJ) VALUES (25,'024','Dordogne','Périgueux','Aquitaine',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);


INSERT INTO DEPFR (DEPFRID,NUMERO,DEPARTEMENT,PREFERTURE,REGION,DATECREATION,DATEMAJ) VALUES (26,'025','Doubs','Besançon','Franche-Comté',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);


INSERT INTO DEPFR (DEPFRID,NUMERO,DEPARTEMENT,PREFERTURE,REGION,DATECREATION,DATEMAJ) VALUES (27,'026','Drôme','Valence','Rhône-Alpes',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);


INSERT INTO DEPFR (DEPFRID,NUMERO,DEPARTEMENT,PREFERTURE,REGION,DATECREATION,DATEMAJ) VALUES (28,'027','Eure','Évreux','Haute-Normandie',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);


INSERT INTO DEPFR (DEPFRID,NUMERO,DEPARTEMENT,PREFERTURE,REGION,DATECREATION,DATEMAJ) VALUES (29,'028','Eure-et-Loir','Chartres','Centre',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);


INSERT INTO DEPFR (DEPFRID,NUMERO,DEPARTEMENT,PREFERTURE,REGION,DATECREATION,DATEMAJ) VALUES (30,'029','Finistère','Quimper','Bretagne',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);


INSERT INTO DEPFR (DEPFRID,NUMERO,DEPARTEMENT,PREFERTURE,REGION,DATECREATION,DATEMAJ) VALUES (31,'030','Gard','Nîmes','Languedoc-Roussillon',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);


INSERT INTO DEPFR (DEPFRID,NUMERO,DEPARTEMENT,PREFERTURE,REGION,DATECREATION,DATEMAJ) VALUES (32,'031','Haute-Garonne','Toulouse','Midi-Pyrénées',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);


INSERT INTO DEPFR (DEPFRID,NUMERO,DEPARTEMENT,PREFERTURE,REGION,DATECREATION,DATEMAJ) VALUES (33,'032','Gers','Auch','Midi-Pyrénées',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);


INSERT INTO DEPFR (DEPFRID,NUMERO,DEPARTEMENT,PREFERTURE,REGION,DATECREATION,DATEMAJ) VALUES (34,'033','Gironde','Bordeaux','Aquitaine',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);


INSERT INTO DEPFR (DEPFRID,NUMERO,DEPARTEMENT,PREFERTURE,REGION,DATECREATION,DATEMAJ) VALUES (35,'034','Hérault','Montpellier','Languedoc-Roussillon',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);


INSERT INTO DEPFR (DEPFRID,NUMERO,DEPARTEMENT,PREFERTURE,REGION,DATECREATION,DATEMAJ) VALUES (36,'035','Ille-et-Vilaine','Rennes','Bretagne',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);


INSERT INTO DEPFR (DEPFRID,NUMERO,DEPARTEMENT,PREFERTURE,REGION,DATECREATION,DATEMAJ) VALUES (37,'036','Indre','Châteauroux','Centre',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);


INSERT INTO DEPFR (DEPFRID,NUMERO,DEPARTEMENT,PREFERTURE,REGION,DATECREATION,DATEMAJ) VALUES (38,'037','Indre-et-Loire','Tours','Centre',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);


INSERT INTO DEPFR (DEPFRID,NUMERO,DEPARTEMENT,PREFERTURE,REGION,DATECREATION,DATEMAJ) VALUES (39,'038','Isère','Grenoble','Rhône-Alpes',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);


INSERT INTO DEPFR (DEPFRID,NUMERO,DEPARTEMENT,PREFERTURE,REGION,DATECREATION,DATEMAJ) VALUES (40,'039','Jura','Lons-le-Saunier','Franche-Comté',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);


INSERT INTO DEPFR (DEPFRID,NUMERO,DEPARTEMENT,PREFERTURE,REGION,DATECREATION,DATEMAJ) VALUES (41,'040','Landes','Mont-de-Marsan','Aquitaine',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);


INSERT INTO DEPFR (DEPFRID,NUMERO,DEPARTEMENT,PREFERTURE,REGION,DATECREATION,DATEMAJ) VALUES (42,'041','Loir-et-Cher','Blois','Centre',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);


INSERT INTO DEPFR (DEPFRID,NUMERO,DEPARTEMENT,PREFERTURE,REGION,DATECREATION,DATEMAJ) VALUES (43,'042','Loire','Saint-Étienne','Rhône-Alpes',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);


INSERT INTO DEPFR (DEPFRID,NUMERO,DEPARTEMENT,PREFERTURE,REGION,DATECREATION,DATEMAJ) VALUES (44,'043','Haute-Loire','Le Puy-en-Velay','Auvergne',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);


INSERT INTO DEPFR (DEPFRID,NUMERO,DEPARTEMENT,PREFERTURE,REGION,DATECREATION,DATEMAJ) VALUES (45,'044','Loire-Atlantique','Nantes','Pays de la Loire',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);


INSERT INTO DEPFR (DEPFRID,NUMERO,DEPARTEMENT,PREFERTURE,REGION,DATECREATION,DATEMAJ) VALUES (46,'045','Loiret','Orléans','Centre',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);


INSERT INTO DEPFR (DEPFRID,NUMERO,DEPARTEMENT,PREFERTURE,REGION,DATECREATION,DATEMAJ) VALUES (47,'046','Lot','Cahors','Midi-Pyrénées',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);


INSERT INTO DEPFR (DEPFRID,NUMERO,DEPARTEMENT,PREFERTURE,REGION,DATECREATION,DATEMAJ) VALUES (48,'047','Lot-et-Garonne','Agen','Aquitaine',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);


INSERT INTO DEPFR (DEPFRID,NUMERO,DEPARTEMENT,PREFERTURE,REGION,DATECREATION,DATEMAJ) VALUES (49,'048','Lozère','Mende','Languedoc-Roussillon',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);


INSERT INTO DEPFR (DEPFRID,NUMERO,DEPARTEMENT,PREFERTURE,REGION,DATECREATION,DATEMAJ) VALUES (50,'049','Maine-et-Loire','Angers','Pays de la Loire',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);


INSERT INTO DEPFR (DEPFRID,NUMERO,DEPARTEMENT,PREFERTURE,REGION,DATECREATION,DATEMAJ) VALUES (51,'050','Manche','Saint-Lô','Basse-Normandie',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);


INSERT INTO DEPFR (DEPFRID,NUMERO,DEPARTEMENT,PREFERTURE,REGION,DATECREATION,DATEMAJ) VALUES (52,'051','Marne','Châlons-en-Champagne','Champagne-Ardenne',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);


INSERT INTO DEPFR (DEPFRID,NUMERO,DEPARTEMENT,PREFERTURE,REGION,DATECREATION,DATEMAJ) VALUES (53,'052','Haute-Marne','Chaumont','Champagne-Ardenne',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);


INSERT INTO DEPFR (DEPFRID,NUMERO,DEPARTEMENT,PREFERTURE,REGION,DATECREATION,DATEMAJ) VALUES (54,'053','Mayenne','Laval','Pays de la Loire',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);


INSERT INTO DEPFR (DEPFRID,NUMERO,DEPARTEMENT,PREFERTURE,REGION,DATECREATION,DATEMAJ) VALUES (55,'054','Meurthe-et-Moselle','Nancy','Lorraine',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);


INSERT INTO DEPFR (DEPFRID,NUMERO,DEPARTEMENT,PREFERTURE,REGION,DATECREATION,DATEMAJ) VALUES (56,'055','Meuse','Bar-le-Duc','Lorraine',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);


INSERT INTO DEPFR (DEPFRID,NUMERO,DEPARTEMENT,PREFERTURE,REGION,DATECREATION,DATEMAJ) VALUES (57,'056','Morbihan','Vannes','Bretagne',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);


INSERT INTO DEPFR (DEPFRID,NUMERO,DEPARTEMENT,PREFERTURE,REGION,DATECREATION,DATEMAJ) VALUES (58,'057','Moselle','Metz','Lorraine',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);


INSERT INTO DEPFR (DEPFRID,NUMERO,DEPARTEMENT,PREFERTURE,REGION,DATECREATION,DATEMAJ) VALUES (59,'058','Nièvre','Nevers','Bourgogne',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);


INSERT INTO DEPFR (DEPFRID,NUMERO,DEPARTEMENT,PREFERTURE,REGION,DATECREATION,DATEMAJ) VALUES (60,'059','Nord','Lille','Nord-Pas-de-Calais',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);


INSERT INTO DEPFR (DEPFRID,NUMERO,DEPARTEMENT,PREFERTURE,REGION,DATECREATION,DATEMAJ) VALUES (61,'060','Oise','Beauvais','Picardie',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);


INSERT INTO DEPFR (DEPFRID,NUMERO,DEPARTEMENT,PREFERTURE,REGION,DATECREATION,DATEMAJ) VALUES (62,'061','Orne','Alençon','Basse-Normandie',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);


INSERT INTO DEPFR (DEPFRID,NUMERO,DEPARTEMENT,PREFERTURE,REGION,DATECREATION,DATEMAJ) VALUES (63,'062','Pas-de-Calais','Arras','Nord-Pas-de-Calais',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);


INSERT INTO DEPFR (DEPFRID,NUMERO,DEPARTEMENT,PREFERTURE,REGION,DATECREATION,DATEMAJ) VALUES (64,'063','Puy-de-Dôme','Clermont-Ferrand','Auvergne',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);


INSERT INTO DEPFR (DEPFRID,NUMERO,DEPARTEMENT,PREFERTURE,REGION,DATECREATION,DATEMAJ) VALUES (65,'064','Pyrénées-Atlantiques','Pau','Aquitaine',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);


INSERT INTO DEPFR (DEPFRID,NUMERO,DEPARTEMENT,PREFERTURE,REGION,DATECREATION,DATEMAJ) VALUES (66,'065','Hautes-Pyrénées','Tarbes','Midi-Pyrénées',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);


INSERT INTO DEPFR (DEPFRID,NUMERO,DEPARTEMENT,PREFERTURE,REGION,DATECREATION,DATEMAJ) VALUES (67,'066','Pyrénées-Orientales','Perpignan','Languedoc-Roussillon',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);


INSERT INTO DEPFR (DEPFRID,NUMERO,DEPARTEMENT,PREFERTURE,REGION,DATECREATION,DATEMAJ) VALUES (68,'067','Bas-Rhin','Strasbourg','Alsace',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);


INSERT INTO DEPFR (DEPFRID,NUMERO,DEPARTEMENT,PREFERTURE,REGION,DATECREATION,DATEMAJ) VALUES (69,'068','Haut-Rhin','Colmar','Alsace',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);


INSERT INTO DEPFR (DEPFRID,NUMERO,DEPARTEMENT,PREFERTURE,REGION,DATECREATION,DATEMAJ) VALUES (70,'069','Rhône','Lyon','Rhône-Alpes',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);


INSERT INTO DEPFR (DEPFRID,NUMERO,DEPARTEMENT,PREFERTURE,REGION,DATECREATION,DATEMAJ) VALUES (71,'070','Haute-Saône','Vesoul','Franche-Comté',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);


INSERT INTO DEPFR (DEPFRID,NUMERO,DEPARTEMENT,PREFERTURE,REGION,DATECREATION,DATEMAJ) VALUES (72,'071','Saône-et-Loire','Mâcon','Bourgogne',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);


INSERT INTO DEPFR (DEPFRID,NUMERO,DEPARTEMENT,PREFERTURE,REGION,DATECREATION,DATEMAJ) VALUES (73,'072','Sarthe','Le Mans','Pays de la Loire',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);


INSERT INTO DEPFR (DEPFRID,NUMERO,DEPARTEMENT,PREFERTURE,REGION,DATECREATION,DATEMAJ) VALUES (74,'073','Savoie','Chambéry','Rhône-Alpes',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);


INSERT INTO DEPFR (DEPFRID,NUMERO,DEPARTEMENT,PREFERTURE,REGION,DATECREATION,DATEMAJ) VALUES (75,'074','Haute-Savoie','Annecy','Rhône-Alpes',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);


INSERT INTO DEPFR (DEPFRID,NUMERO,DEPARTEMENT,PREFERTURE,REGION,DATECREATION,DATEMAJ) VALUES (76,'075','Paris','Paris','Ile-de-France',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);


INSERT INTO DEPFR (DEPFRID,NUMERO,DEPARTEMENT,PREFERTURE,REGION,DATECREATION,DATEMAJ) VALUES (77,'076','Seine-Maritime','Rouen','Haute-Normandie',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);


INSERT INTO DEPFR (DEPFRID,NUMERO,DEPARTEMENT,PREFERTURE,REGION,DATECREATION,DATEMAJ) VALUES (78,'077','Seine-et-Marne','Melun','Ile-de-France',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);


INSERT INTO DEPFR (DEPFRID,NUMERO,DEPARTEMENT,PREFERTURE,REGION,DATECREATION,DATEMAJ) VALUES (79,'078','Yvelines','Versailles','Ile-de-France',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);


INSERT INTO DEPFR (DEPFRID,NUMERO,DEPARTEMENT,PREFERTURE,REGION,DATECREATION,DATEMAJ) VALUES (80,'079','Deux-Sèvres','Niort','Poitou-Charentes',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);


INSERT INTO DEPFR (DEPFRID,NUMERO,DEPARTEMENT,PREFERTURE,REGION,DATECREATION,DATEMAJ) VALUES (81,'080','Somme','Amiens','Picardie',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);


INSERT INTO DEPFR (DEPFRID,NUMERO,DEPARTEMENT,PREFERTURE,REGION,DATECREATION,DATEMAJ) VALUES (82,'081','Tarn','Albi','Midi-Pyrénées',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);


INSERT INTO DEPFR (DEPFRID,NUMERO,DEPARTEMENT,PREFERTURE,REGION,DATECREATION,DATEMAJ) VALUES (83,'082','Tarn-et-Garonne','Montauban','Midi-Pyrénées',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);


INSERT INTO DEPFR (DEPFRID,NUMERO,DEPARTEMENT,PREFERTURE,REGION,DATECREATION,DATEMAJ) VALUES (84,'083','Var','Toulon','Provence-Alpes-Côte d''Azur',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);


INSERT INTO DEPFR (DEPFRID,NUMERO,DEPARTEMENT,PREFERTURE,REGION,DATECREATION,DATEMAJ) VALUES (85,'084','Vaucluse','Avignon','Provence-Alpes-Côte d''Azur',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);


INSERT INTO DEPFR (DEPFRID,NUMERO,DEPARTEMENT,PREFERTURE,REGION,DATECREATION,DATEMAJ) VALUES (86,'085','Vendée','La Roche-sur-Yon','Pays de la Loire',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);


INSERT INTO DEPFR (DEPFRID,NUMERO,DEPARTEMENT,PREFERTURE,REGION,DATECREATION,DATEMAJ) VALUES (87,'086','Vienne','Poitiers','Poitou-Charentes',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);


INSERT INTO DEPFR (DEPFRID,NUMERO,DEPARTEMENT,PREFERTURE,REGION,DATECREATION,DATEMAJ) VALUES (88,'087','Haute-Vienne','Limoges','Limousin',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);


INSERT INTO DEPFR (DEPFRID,NUMERO,DEPARTEMENT,PREFERTURE,REGION,DATECREATION,DATEMAJ) VALUES (89,'088','Vosges','Épinal','Lorraine',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);


INSERT INTO DEPFR (DEPFRID,NUMERO,DEPARTEMENT,PREFERTURE,REGION,DATECREATION,DATEMAJ) VALUES (90,'089','Yonne','Auxerre','Bourgogne',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);


INSERT INTO DEPFR (DEPFRID,NUMERO,DEPARTEMENT,PREFERTURE,REGION,DATECREATION,DATEMAJ) VALUES (91,'090','Territoire-de-Belfort','Belfort','Franche-Comté',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);


INSERT INTO DEPFR (DEPFRID,NUMERO,DEPARTEMENT,PREFERTURE,REGION,DATECREATION,DATEMAJ) VALUES (92,'091','Essonne','Évry','Ile-de-France',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);


INSERT INTO DEPFR (DEPFRID,NUMERO,DEPARTEMENT,PREFERTURE,REGION,DATECREATION,DATEMAJ) VALUES (93,'092','Hauts-de-Seine','Nanterre','Ile-de-France',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);


INSERT INTO DEPFR (DEPFRID,NUMERO,DEPARTEMENT,PREFERTURE,REGION,DATECREATION,DATEMAJ) VALUES (94,'093','Seine-Saint-Denis','Bobigny','Ile-de-France',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);


INSERT INTO DEPFR (DEPFRID,NUMERO,DEPARTEMENT,PREFERTURE,REGION,DATECREATION,DATEMAJ) VALUES (95,'094','Val-de-Marne','Créteil','Ile-de-France',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);


INSERT INTO DEPFR (DEPFRID,NUMERO,DEPARTEMENT,PREFERTURE,REGION,DATECREATION,DATEMAJ) VALUES (96,'095','Val-d''Oise','Pontoise','Ile-de-France',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);


INSERT INTO DEPFR (DEPFRID,NUMERO,DEPARTEMENT,PREFERTURE,REGION,DATECREATION,DATEMAJ) VALUES (97,'971','Guadeloupe','Basse Terre','Département d''Outre Mer',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);


INSERT INTO DEPFR (DEPFRID,NUMERO,DEPARTEMENT,PREFERTURE,REGION,DATECREATION,DATEMAJ) VALUES (98,'972','Martinique','Fort-de-France','Département d''Outre Mer',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);


INSERT INTO DEPFR (DEPFRID,NUMERO,DEPARTEMENT,PREFERTURE,REGION,DATECREATION,DATEMAJ) VALUES (99,'973','Guyane','Cayenne','Département d''Outre Mer',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);


INSERT INTO DEPFR (DEPFRID,NUMERO,DEPARTEMENT,PREFERTURE,REGION,DATECREATION,DATEMAJ) VALUES (100,'974','La Réunion','Saint-Denis','Département d''Outre Mer',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);


INSERT INTO MARCHE (MARCHEID,MARCHE,OBJET,MANDATAIRE,MANDATAIREID,RANG,FINPREVUE,CSPS,INSPECCOMMUNE,DATECREATION,DATEMAJ,DATESYNCHRO) VALUES ('VPARDEFAUT','PAS DE MARCHE','','**********','VPARDEFAUT','-1','01/01/1900','01/01/1900','01/01/1900',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);


INSERT INTO LIEU (LIEUID,LIBELLE,DATECREATION,DATEMAJ) VALUES (-1,'-NC-',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);


INSERT INTO OTACHE (OTACHEID,TYPEJOUR,HEUREEXECUTION,ACTION,HEUREDEBUT,HEUREFIN,NBJOURMOINS,SITEID,GROUPEDESTID,DATECREATION) VALUES (1,'0:0','08:00','MAINCOURANTE','07:00','07:00',-1,'VPARDEFAULT',1865,CURRENT_TIMESTAMP);


INSERT INTO OMNI_PARAM (PARAMACCES, OPTION_NBJMC, OPTION_NBJMI, OPTION_DUBIP, OPTION_BIPLONG, SEPARATEUR, OPTION_AVMISS, OPTION_TIMER_MISSION, OPTION_PASSWORD, CARTEPRO_CTRL, CARTEPRO_NBJ, MC_FILTRAGE, PASS_SENSIBLE, STATION_POSTE_ONLY, STATION_ALERT_LOCK, ALERT_NOLOCK) SELECT 401903, 30, NULL, NULL, 0, '$DA$', 10, 5, 0, 0, 0, 0, 0, 0, 0, 0 WHERE NOT EXISTS (SELECT PARAMACCES FROM OMNI_PARAM);


INSERT INTO EVENEMENT_SITE (EVENEMENTID,SITEID) VALUES (1,'VPARDEFAUT');


INSERT INTO PERIPHERIQUE (PERIPHERIQUEID, PERIPHERIQUE_TRAITEMENTID, NOM, AVANT, APRES, DEBUT, LONGUEUR, LONGUEUR_MAX, DECOUPE, CONVERSION, TYPE_PORT, BIT_SECONDE, BIT_DONNEE, PARITE, BIT_ARRET, CONTROLE_FLUX, DATECREATION, DATEMAJ) VALUES (-1,-4,'Lecteur Ecran Clavier','','',NULL,NULL,NULL,NULL,NULL,'PS2',NULL,NULL,'',NULL,'',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);


INSERT INTO PERIPHERIQUE (PERIPHERIQUEID, PERIPHERIQUE_TRAITEMENTID, NOM, AVANT, APRES, DEBUT, LONGUEUR, LONGUEUR_MAX, DECOUPE, CONVERSION, TYPE_PORT, BIT_SECONDE, BIT_DONNEE, PARITE, BIT_ARRET, CONTROLE_FLUX, DATECREATION, DATEMAJ) VALUES (-2,-4,'WIEGAND','','',2,10,NULL,1,NULL,'RS232',9600,8,'',1,'',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);


INSERT INTO PERIPHERIQUE (PERIPHERIQUEID, PERIPHERIQUE_TRAITEMENTID, NOM, AVANT, APRES, DEBUT, LONGUEUR, LONGUEUR_MAX, DECOUPE, CONVERSION, TYPE_PORT, BIT_SECONDE, BIT_DONNEE, PARITE, BIT_ARRET, CONTROLE_FLUX, DATECREATION, DATEMAJ) VALUES (-3,-4,'POWERSCAN','','"CR""LF"',4,99,NULL,1,NULL,'RS232',9600,8,'',1,'',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);


INSERT INTO PERIPHERIQUE (PERIPHERIQUEID, PERIPHERIQUE_TRAITEMENTID, NOM, AVANT, APRES, DEBUT, LONGUEUR, LONGUEUR_MAX, DECOUPE, CONVERSION, TYPE_PORT, BIT_SECONDE, BIT_DONNEE, PARITE, BIT_ARRET, CONTROLE_FLUX, DATECREATION, DATEMAJ) VALUES (-4,-1,'SWISS READER','','',NULL,NULL,NULL,NULL,NULL,'PS2',NULL,NULL,'',NULL,'',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);


INSERT INTO STATUTVISITE (STATUTID, STATUTVISITE) VALUES (-3,'Annulée');


INSERT INTO STATUTVISITE (STATUTID, STATUTVISITE) VALUES (-2,'Non venu');


INSERT INTO STATUTVISITE (STATUTID, STATUTVISITE) VALUES (-1,'Supprimée');


INSERT INTO STATUTVISITE (STATUTID, STATUTVISITE) VALUES (1,'En attente');


INSERT INTO STATUTVISITE (STATUTID, STATUTVISITE) VALUES (2,'Pré-enregistrée');


INSERT INTO STATUTVISITE (STATUTID, STATUTVISITE) VALUES (4,'Pré-enregistrée interdit');


INSERT INTO STATUTVISITE (STATUTID, STATUTVISITE) VALUES (8,'En cours');


INSERT INTO STATUTVISITE (STATUTID, STATUTVISITE) VALUES (16,'Terminée');


INSERT INTO STATUTVISITE (STATUTID, STATUTVISITE) VALUES (32,'Pré-enregistrée extérieur');


INSERT INTO STATUTVISITE (STATUTID, STATUTVISITE) VALUES (33,'En cours extérieur');


INSERT INTO STATUTVISITE (STATUTID, STATUTVISITE) VALUES (34,'En attente extérieur');


INSERT INTO STATUTVISITE (STATUTID, STATUTVISITE) VALUES (35,'Terminée extérieur');


INSERT INTO STATUTCOLIS (ID_STATUTCOLIS, LIBELLE, COLOR, DATECREATION, DATEMAJ) VALUES (-1, 'Enregistré', 65535, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);


INSERT INTO STATUTCOLIS (ID_STATUTCOLIS, LIBELLE, COLOR, DATECREATION, DATEMAJ) VALUES (-2, 'En attente', 42495, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);


INSERT INTO STATUTCOLIS (ID_STATUTCOLIS, LIBELLE, COLOR, DATECREATION, DATEMAJ) VALUES (-3, 'En stock', 16711680, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);


INSERT INTO STATUTCOLIS (ID_STATUTCOLIS, LIBELLE, COLOR, DATECREATION, DATEMAJ) VALUES (-4, 'En stock partiel', 16711680, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);


INSERT INTO STATUTCOLIS (ID_STATUTCOLIS, LIBELLE, COLOR, DATECREATION, DATEMAJ) VALUES (-5, 'Traité', 32768, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);


INSERT INTO STATUTCOLIS (ID_STATUTCOLIS, LIBELLE, COLOR, DATECREATION, DATEMAJ) VALUES (-6, 'Refusé', 255, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);


INSERT INTO DROITSTAXI (ID_DROITSTAXI, LIBELLE, DROITS, DATECREATION, DATEMAJ) VALUES (1, 'Administration', 63, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);


INSERT INTO DROITSTAXI (ID_DROITSTAXI, LIBELLE, DROITS, DATECREATION, DATEMAJ) VALUES (9, 'Accueil', 28, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);


INSERT INTO STATUTCOURSE (ID_STATUTCOURSE, LIBELLE, COLOR, DATECREATION, DATEMAJ) VALUES (-1, 'Nouveau', 65535, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);


INSERT INTO STATUTCOURSE (ID_STATUTCOURSE, LIBELLE, COLOR, DATECREATION, DATEMAJ) VALUES (-2, 'Confirmé', 42495, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);


INSERT INTO STATUTCOURSE (ID_STATUTCOURSE, LIBELLE, COLOR, DATECREATION, DATEMAJ) VALUES (-3, 'Traité', 32768, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);


INSERT INTO STATUTCOURSE (ID_STATUTCOURSE, LIBELLE, COLOR, DATECREATION, DATEMAJ) VALUES (-4, 'Annulé', 255, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);


INSERT INTO TYPEVEHICULE (ID_TYPEVEHICULE, LIBELLE, DATECREATION, DATEMAJ) VALUES (-1, 'Berline/Break', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);


INSERT INTO TYPEVEHICULE (ID_TYPEVEHICULE, LIBELLE, DATECREATION, DATEMAJ) VALUES (-2, 'Monospace', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);


INSERT INTO TYPEDOCUMENT (TYPEDOCUMENTID,LIBELLE,DATECREATION,DATEMAJ,DATESYNCHRO,PORTEEID,OBLIGATOIRE,MODIFIABLE,VALIDITEPARDEFAUT,CREATCTRL,IN_PREENREG) VALUES (6,'Habilitation amiante',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,NULL,-2,2,2,730,2,2)


INSERT INTO TYPEDOCUMENT (TYPEDOCUMENTID,LIBELLE,DATECREATION,DATEMAJ,DATESYNCHRO,PORTEEID,OBLIGATOIRE,MODIFIABLE,VALIDITEPARDEFAUT,CREATCTRL,IN_PREENREG) VALUES (0,'Formulaire 82b individuel',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,NULL,-1,1,2,730,2,2)


INSERT INTO TYPEDOCUMENT (TYPEDOCUMENTID,LIBELLE,DATECREATION,DATEMAJ,DATESYNCHRO,PORTEEID,OBLIGATOIRE,MODIFIABLE,VALIDITEPARDEFAUT,CREATCTRL,IN_PREENREG) VALUES (-2,'Autorisation de travail',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,NULL,-2,1,2,730,2,2)


INSERT INTO TYPEDOCUMENT (TYPEDOCUMENTID,LIBELLE,DATECREATION,DATEMAJ,DATESYNCHRO,PORTEEID,OBLIGATOIRE,MODIFIABLE,VALIDITEPARDEFAUT,CREATCTRL,IN_PREENREG) VALUES (-3,'Permis de conduire',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,NULL,-1,2,2,360,2,2)


INSERT INTO DROITSTELEM (ID_DROITSTELEM, LIBELLE, DROITS, DATECREATION, DATEMAJ) VALUES (-1,'ADMINISTRATEUR','accueil,sortie,en_attente,preenreg,exterieurs,visiteurs,residants,es_badge,validation,sur_site,historique,messagerie,entree_colis,sortie_colis,vehicules,annuaire,taxi,vip,multisite,statistiques,administration,gestion_site,gestion_user,parametrages,modeles,pays',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);


INSERT INTO DROITSTELEM (ID_DROITSTELEM, LIBELLE, DROITS, DATECREATION, DATEMAJ) VALUES (-2,'ACCUEIL','accueil,sortie,en_attente,preenreg,visiteurs,residants,sur_site,historique,messagerie,entree_colis,sortie_colis,annuaire,vip',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);


INSERT INTO OBJVISITE (OBJVISITEID,LIBELLE,DATEMAJ,DATECREATION) VALUES (0,'**********',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);


INSERT INTO GRPVALIDEUR (GRPVALIDEURID,GRPVALIDEURN,RANGVALIDEUR,DATECREATION,DATEMAJ) VALUES ('-1','GRPVALIDEUR1',1,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP)


INSERT INTO GRPVALIDEUR (GRPVALIDEURID,GRPVALIDEURN,RANGVALIDEUR,DATECREATION,DATEMAJ) VALUES ('-2','GRPVALIDEUR2',2,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP)


INSERT INTO GRPVALIDEUR (GRPVALIDEURID,GRPVALIDEURN,RANGVALIDEUR,DATECREATION,DATEMAJ) VALUES ('-3','GRPVALIDEUR3',3,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP)


INSERT INTO GRPVALIDEUR (GRPVALIDEURID,GRPVALIDEURN,RANGVALIDEUR,DATECREATION,DATEMAJ) VALUES ('-4','GRPVALIDEUR4',4,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP)


INSERT INTO NATURECOLIS (NATURECOLISID,LIBELLE,DATECREATION,DATEMAJ) VALUES (0,'Lettre',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);


INSERT INTO NATURECOLIS (NATURECOLISID,LIBELLE,DATECREATION,DATEMAJ) VALUES (-1,'Colis',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);


INSERT INTO NATURECOLIS (NATURECOLISID,LIBELLE,DATECREATION,DATEMAJ) VALUES (-2,'Paquet',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);


INSERT INTO NATURECOLIS (NATURECOLISID,LIBELLE,DATECREATION,DATEMAJ) VALUES (-3,'Palette',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);


INSERT INTO EQUIPE (EQUIPEID,LIBELLE,DATECREATION,DATEMAJ,DATESYNCHRO) VALUES(1,'**********',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP)


INSERT INTO PERIPHERIQUE_TRAITEMENT (PERIPHERIQUE_TRAITEMENTID, LIBELLE, FAMILLE, DATECREATION, DATEMAJ) VALUES (-1,'SWISS_READER',2,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);


INSERT INTO PERIPHERIQUE_TRAITEMENT (PERIPHERIQUE_TRAITEMENTID, LIBELLE, FAMILLE, DATECREATION, DATEMAJ) VALUES (-2,'MAGNETA_ESCORT2',4,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);


INSERT INTO PERIPHERIQUE_TRAITEMENT (PERIPHERIQUE_TRAITEMENTID, LIBELLE, FAMILLE, DATECREATION, DATEMAJ) VALUES (-3,'DEISTER_GUARDIX',4,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);


INSERT INTO PERIPHERIQUE_TRAITEMENT (PERIPHERIQUE_TRAITEMENTID, LIBELLE, FAMILLE, DATECREATION, DATEMAJ) VALUES (-4,'BADGE',1,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);


INSERT INTO PERIPHERIQUE_TRAITEMENT (PERIPHERIQUE_TRAITEMENTID, LIBELLE, FAMILLE, DATECREATION, DATEMAJ) VALUES (-5,'HITACHI_BIOVEIN',5,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);


INSERT INTO PERIPHERIQUE_TRAITEMENT (PERIPHERIQUE_TRAITEMENTID, LIBELLE, FAMILLE, DATECREATION, DATEMAJ) VALUES (-6,'SRI_RADIO',4,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);


INSERT INTO PERIPHERIQUE_TRAITEMENT (PERIPHERIQUE_TRAITEMENTID, LIBELLE, FAMILLE, DATECREATION, DATEMAJ) VALUES (-7,'TOPAZ_SIGPLUS',6,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);


INSERT INTO PERIPHERIQUE_TRAITEMENT (PERIPHERIQUE_TRAITEMENTID, LIBELLE, FAMILLE, DATECREATION, DATEMAJ) VALUES (-8,'IRIS_IRISCARD_A6',3,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);


INSERT INTO PERIPHERIQUE_TRAITEMENT (PERIPHERIQUE_TRAITEMENTID, LIBELLE, FAMILLE, DATECREATION, DATEMAJ) VALUES (-9,'DESKO_EVO',2,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);


INSERT INTO PERIPHERIQUE_TRAITEMENT (PERIPHERIQUE_TRAITEMENTID, LIBELLE, FAMILLE, DATECREATION, DATEMAJ) VALUES (-10,'EDEN_BIOVEIN',8,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);


INSERT INTO PERIPHERIQUE_TRAITEMENT (PERIPHERIQUE_TRAITEMENTID, LIBELLE, FAMILLE, DATECREATION, DATEMAJ) VALUES (-11,'DATALOGIC_POWERSCAN',7,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);


INSERT INTO PERIPHERIQUE_TRAITEMENT (PERIPHERIQUE_TRAITEMENTID, LIBELLE, FAMILLE, DATECREATION, DATEMAJ) VALUES (-12,'SIGN_SCREEN',6,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);


INSERT INTO PERIPHERIQUE_TRAITEMENT (PERIPHERIQUE_TRAITEMENTID, LIBELLE, FAMILLE, DATECREATION, DATEMAJ) VALUES (-13,'ARH_COMBOSMART',2,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);


INSERT INTO PERIPHERIQUE_TRAITEMENT (PERIPHERIQUE_TRAITEMENTID, LIBELLE, FAMILLE, DATECREATION, DATEMAJ) VALUES (-14,'MAGNETA_EASYRONDE',4,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);


INSERT INTO PERIPHERIQUE_TRAITEMENT (PERIPHERIQUE_TRAITEMENTID, LIBELLE, FAMILLE, DATECREATION, DATEMAJ) VALUES (-15,'SURVACOM_TRACING',4,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);


INSERT INTO PERIPHERIQUE_TRAITEMENT (PERIPHERIQUE_TRAITEMENTID, LIBELLE, FAMILLE, DATECREATION, DATEMAJ) VALUES (-16,'ZALIX_VEINSECURE',5,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);


INSERT INTO PERIPHERIQUE_TRAITEMENT (PERIPHERIQUE_TRAITEMENTID, LIBELLE, FAMILLE, DATECREATION, DATEMAJ) VALUES (-17,'WACOM_STU',6,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);


INSERT INTO PERIPHERIQUE_TRAITEMENT (PERIPHERIQUE_TRAITEMENTID, LIBELLE, FAMILLE, DATECREATION, DATEMAJ) VALUES (-18,'WACOM_STU_AFF',9,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);


INSERT INTO PERIPHERIQUE_TRAITEMENT (PERIPHERIQUE_TRAITEMENTID, LIBELLE, FAMILLE, DATECREATION, DATEMAJ) VALUES (-19,'SIGN_SCREEN_TABLET',6,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);

--PARAMETRAGE
INSERT [dbo].[PARAMETRAGE] ([LIBELLE], [VALEUR], [SITEID], [DATECREATION], [DATEMAJ], [DATESYNCHRO]) VALUES (N'ACCUEIL_TYPE_PIECE', N'0', N'ALL', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL);
INSERT [dbo].[PARAMETRAGE] ([LIBELLE], [VALEUR], [SITEID], [DATECREATION], [DATEMAJ], [DATESYNCHRO]) VALUES (N'ACCUEIL_WIFI', N'0', N'ALL', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL);
INSERT [dbo].[PARAMETRAGE] ([LIBELLE], [VALEUR], [SITEID], [DATECREATION], [DATEMAJ], [DATESYNCHRO]) VALUES (N'ACTIVATION_DELAI_EXP', N'0', N'ALL', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL);
INSERT [dbo].[PARAMETRAGE] ([LIBELLE], [VALEUR], [SITEID], [DATECREATION], [DATEMAJ], [DATESYNCHRO]) VALUES (N'AFFICHE_INTERLOCUTEUR', N'1', N'ALL', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL);
INSERT [dbo].[PARAMETRAGE] ([LIBELLE], [VALEUR], [SITEID], [DATECREATION], [DATEMAJ], [DATESYNCHRO]) VALUES (N'AFFICHER_RESULTAT_RECHERCHE_ACCUEIL', N'0', N'ALL', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL);
INSERT [dbo].[PARAMETRAGE] ([LIBELLE], [VALEUR], [SITEID], [DATECREATION], [DATEMAJ], [DATESYNCHRO]) VALUES (N'AFFICHER_RESULTAT_RECHERCHE_PREENREG', N'0', N'ALL', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL);
INSERT [dbo].[PARAMETRAGE] ([LIBELLE], [VALEUR], [SITEID], [DATECREATION], [DATEMAJ], [DATESYNCHRO]) VALUES (N'AVIS_DIRECTION', N'0', N'ALL', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL);
INSERT [dbo].[PARAMETRAGE] ([LIBELLE], [VALEUR], [SITEID], [DATECREATION], [DATEMAJ], [DATESYNCHRO]) VALUES (N'BADGE_AFFICHE_ACCUEIL', N'1', N'ALL', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL);
INSERT [dbo].[PARAMETRAGE] ([LIBELLE], [VALEUR], [SITEID], [DATECREATION], [DATEMAJ], [DATESYNCHRO]) VALUES (N'BADGE_AFFICHE_PRE_ENREG', N'0', N'ALL', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL);
INSERT [dbo].[PARAMETRAGE] ([LIBELLE], [VALEUR], [SITEID], [DATECREATION], [DATEMAJ], [DATESYNCHRO]) VALUES (N'BADGE_GENERATION', N'1', N'ALL', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL);
INSERT [dbo].[PARAMETRAGE] ([LIBELLE], [VALEUR], [SITEID], [DATECREATION], [DATEMAJ], [DATESYNCHRO]) VALUES (N'BADGE_IMPRESSION_AUTO', N'0', N'ALL', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL);
INSERT [dbo].[PARAMETRAGE] ([LIBELLE], [VALEUR], [SITEID], [DATECREATION], [DATEMAJ], [DATESYNCHRO]) VALUES (N'BADGE_UNIQUE', N'0', N'ALL', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL);
INSERT [dbo].[PARAMETRAGE] ([LIBELLE], [VALEUR], [SITEID], [DATECREATION], [DATEMAJ], [DATESYNCHRO]) VALUES (N'BADGE_UNIQUE_VISITES_EN_COURS', N'0', N'ALL', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL);
INSERT [dbo].[PARAMETRAGE] ([LIBELLE], [VALEUR], [SITEID], [DATECREATION], [DATEMAJ], [DATESYNCHRO]) VALUES (N'CATEGORIE_VI', N'', N'ALL', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL);
INSERT [dbo].[PARAMETRAGE] ([LIBELLE], [VALEUR], [SITEID], [DATECREATION], [DATEMAJ], [DATESYNCHRO]) VALUES (N'CHOIX_RESIDANT', N'1', N'ALL', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL);
INSERT [dbo].[PARAMETRAGE] ([LIBELLE], [VALEUR], [SITEID], [DATECREATION], [DATEMAJ], [DATESYNCHRO]) VALUES (N'CHOIX_RESIDANT_SITE', N'0', N'ALL', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL);
INSERT [dbo].[PARAMETRAGE] ([LIBELLE], [VALEUR], [SITEID], [DATECREATION], [DATEMAJ], [DATESYNCHRO]) VALUES (N'CLEAR_STRING_PARAM', N'1', N'ALL', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL);
INSERT [dbo].[PARAMETRAGE] ([LIBELLE], [VALEUR], [SITEID], [DATECREATION], [DATEMAJ], [DATESYNCHRO]) VALUES (N'CNI_OBLIGATOIRE_PREENREG', N'0', N'ALL', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL);
INSERT [dbo].[PARAMETRAGE] ([LIBELLE], [VALEUR], [SITEID], [DATECREATION], [DATEMAJ], [DATESYNCHRO]) VALUES (N'CODE_IMPUTATION', N'1', N'ALL', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL);
INSERT [dbo].[PARAMETRAGE] ([LIBELLE], [VALEUR], [SITEID], [DATECREATION], [DATEMAJ], [DATESYNCHRO]) VALUES (N'CODE_IMPUTATION_PRESTATION', N'', N'ALL', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL);
INSERT [dbo].[PARAMETRAGE] ([LIBELLE], [VALEUR], [SITEID], [DATECREATION], [DATEMAJ], [DATESYNCHRO]) VALUES (N'COMPTAGE_TELEPHONIQUE', N'', N'ALL', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL);
INSERT [dbo].[PARAMETRAGE] ([LIBELLE], [VALEUR], [SITEID], [DATECREATION], [DATEMAJ], [DATESYNCHRO]) VALUES (N'CRYPTAGE', N'0', N'ALL', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL);
INSERT [dbo].[PARAMETRAGE] ([LIBELLE], [VALEUR], [SITEID], [DATECREATION], [DATEMAJ], [DATESYNCHRO]) VALUES (N'CTRL_ES_BADGE', N'1', N'ALL', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL);
INSERT [dbo].[PARAMETRAGE] ([LIBELLE], [VALEUR], [SITEID], [DATECREATION], [DATEMAJ], [DATESYNCHRO]) VALUES (N'DELAI_DEBUT_PREVU', N'0', N'ALL', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL);
INSERT [dbo].[PARAMETRAGE] ([LIBELLE], [VALEUR], [SITEID], [DATECREATION], [DATEMAJ], [DATESYNCHRO]) VALUES (N'ENROL_APRES_IMPR', N'0', N'ALL', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL);
INSERT [dbo].[PARAMETRAGE] ([LIBELLE], [VALEUR], [SITEID], [DATECREATION], [DATEMAJ], [DATESYNCHRO]) VALUES (N'ENTREE_SORTIE_GROUPE', N'1', N'ALL', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL);
INSERT [dbo].[PARAMETRAGE] ([LIBELLE], [VALEUR], [SITEID], [DATECREATION], [DATEMAJ], [DATESYNCHRO]) VALUES (N'ES_BADGE_CREATION_VISITE', N'1', N'ALL', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL);
INSERT [dbo].[PARAMETRAGE] ([LIBELLE], [VALEUR], [SITEID], [DATECREATION], [DATEMAJ], [DATESYNCHRO]) VALUES (N'EXCHANGE_GESROOM', N'0', N'ALL', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL);
INSERT [dbo].[PARAMETRAGE] ([LIBELLE], [VALEUR], [SITEID], [DATECREATION], [DATEMAJ], [DATESYNCHRO]) VALUES (N'FILTER_LOCALISATION', N'0', N'ALL', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL);
INSERT [dbo].[PARAMETRAGE] ([LIBELLE], [VALEUR], [SITEID], [DATECREATION], [DATEMAJ], [DATESYNCHRO]) VALUES (N'FILTRE_RESERVATION_PAR_DEFAUT', N'', N'ALL', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL);
INSERT [dbo].[PARAMETRAGE] ([LIBELLE], [VALEUR], [SITEID], [DATECREATION], [DATEMAJ], [DATESYNCHRO]) VALUES (N'FORM_DOUBLON', N'nom,prenom', N'ALL', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL);
INSERT [dbo].[PARAMETRAGE] ([LIBELLE], [VALEUR], [SITEID], [DATECREATION], [DATEMAJ], [DATESYNCHRO]) VALUES (N'FORM_PROFIL', N'nom,prenom,matricule,site,service,batiment,bureau,email,telephone,mobile,fax,pass,pers_prevenir,delegataire,vehicule', N'ALL', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL);
INSERT [dbo].[PARAMETRAGE] ([LIBELLE], [VALEUR], [SITEID], [DATECREATION], [DATEMAJ], [DATESYNCHRO]) VALUES (N'FORM_PROFIL_MODIF', N'0,0,0,0,0,1,1,1,1,1,1,1,1,1,1', N'ALL', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL);
INSERT [dbo].[PARAMETRAGE] ([LIBELLE], [VALEUR], [SITEID], [DATECREATION], [DATEMAJ], [DATESYNCHRO]) VALUES (N'FORM_RESIDANT', N'civilite,nom,prenom,site,service,batiment,bureau,fonction,email,telephone,mobile', N'ALL', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL);
INSERT [dbo].[PARAMETRAGE] ([LIBELLE], [VALEUR], [SITEID], [DATECREATION], [DATEMAJ], [DATESYNCHRO]) VALUES (N'FORM_RESIDANT_OBLIGATOIRE', N'1,1,1,0,0,0,0,0,0,0,0', N'ALL', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL);
INSERT [dbo].[PARAMETRAGE] ([LIBELLE], [VALEUR], [SITEID], [DATECREATION], [DATEMAJ], [DATESYNCHRO]) VALUES (N'FORM_SOCIETE', N'nom,siret,agence,statut,pays,adresse,codepostal,ville', N'ALL', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL);
INSERT [dbo].[PARAMETRAGE] ([LIBELLE], [VALEUR], [SITEID], [DATECREATION], [DATEMAJ], [DATESYNCHRO]) VALUES (N'FORM_SOCIETE_CONTROLE', N'0,0,0,0,0,0,0,0', N'ALL', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL);
INSERT [dbo].[PARAMETRAGE] ([LIBELLE], [VALEUR], [SITEID], [DATECREATION], [DATEMAJ], [DATESYNCHRO]) VALUES (N'FORM_SOCIETE_OBLIGATOIRE', N'1,0,0,0,0,0,0,0', N'ALL', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL);
INSERT [dbo].[PARAMETRAGE] ([LIBELLE], [VALEUR], [SITEID], [DATECREATION], [DATEMAJ], [DATESYNCHRO]) VALUES (N'FORM_VILLE', N'nom,codepostal,pays', N'ALL', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL);
INSERT [dbo].[PARAMETRAGE] ([LIBELLE], [VALEUR], [SITEID], [DATECREATION], [DATEMAJ], [DATESYNCHRO]) VALUES (N'FORM_VILLE_OBLIGATOIRE', N'1,0,0', N'ALL', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL);
INSERT [dbo].[PARAMETRAGE] ([LIBELLE], [VALEUR], [SITEID], [DATECREATION], [DATEMAJ], [DATESYNCHRO]) VALUES (N'FORM_VISITEUR', N'civilite,nom,prenom,nomfille,date_naiss,lieu_naiss,nationalite,statut,fonction,societe,telephone,mobile,email', N'ALL', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL);
INSERT [dbo].[PARAMETRAGE] ([LIBELLE], [VALEUR], [SITEID], [DATECREATION], [DATEMAJ], [DATESYNCHRO]) VALUES (N'FORM_VISITEUR_CONTROLE', N'0,0,0,0,0,0,0,0,0,0,0,0,0', N'ALL', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL);
INSERT [dbo].[PARAMETRAGE] ([LIBELLE], [VALEUR], [SITEID], [DATECREATION], [DATEMAJ], [DATESYNCHRO]) VALUES (N'FORM_VISITEUR_OBLIGATOIRE', N'1,1,1,0,0,0,0,0,0,1,0,0,0', N'ALL', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL);
INSERT [dbo].[PARAMETRAGE] ([LIBELLE], [VALEUR], [SITEID], [DATECREATION], [DATEMAJ], [DATESYNCHRO]) VALUES (N'FORMAT_SALLE', N'%n - %s', N'ALL', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL);
INSERT [dbo].[PARAMETRAGE] ([LIBELLE], [VALEUR], [SITEID], [DATECREATION], [DATEMAJ], [DATESYNCHRO]) VALUES (N'GARDER_MEMOIRE_RESERVANT', N'1', N'ALL', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL);
INSERT [dbo].[PARAMETRAGE] ([LIBELLE], [VALEUR], [SITEID], [DATECREATION], [DATEMAJ], [DATESYNCHRO]) VALUES (N'GERER_PIECEID_PREENREG', N'0', N'ALL', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL);
INSERT [dbo].[PARAMETRAGE] ([LIBELLE], [VALEUR], [SITEID], [DATECREATION], [DATEMAJ], [DATESYNCHRO]) VALUES (N'GESROOM_FACTURE', N'0', N'ALL', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL);
INSERT [dbo].[PARAMETRAGE] ([LIBELLE], [VALEUR], [SITEID], [DATECREATION], [DATEMAJ], [DATESYNCHRO]) VALUES (N'GESROOM_FACTURE_FOOTER', N'', N'ALL', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL);
INSERT [dbo].[PARAMETRAGE] ([LIBELLE], [VALEUR], [SITEID], [DATECREATION], [DATEMAJ], [DATESYNCHRO]) VALUES (N'GESROOM_MODIFICATION_APRES_VALIDATION', N'0', N'ALL', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL);
INSERT [dbo].[PARAMETRAGE] ([LIBELLE], [VALEUR], [SITEID], [DATECREATION], [DATEMAJ], [DATESYNCHRO]) VALUES (N'GESROOM_NB_PARTICIPANT_OBLIGATOIRE', N'0', N'ALL', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL);
INSERT [dbo].[PARAMETRAGE] ([LIBELLE], [VALEUR], [SITEID], [DATECREATION], [DATEMAJ], [DATESYNCHRO]) VALUES (N'GESROOM_OBJET_OBLIGATOIRE', N'0', N'ALL', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL);
INSERT [dbo].[PARAMETRAGE] ([LIBELLE], [VALEUR], [SITEID], [DATECREATION], [DATEMAJ], [DATESYNCHRO]) VALUES (N'gesroom_taux_occupation_min', N'0', N'ALL', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL);
INSERT [dbo].[PARAMETRAGE] ([LIBELLE], [VALEUR], [SITEID], [DATECREATION], [DATEMAJ], [DATESYNCHRO]) VALUES (N'GEST_GRPVALIDEUR', N'0', N'ALL', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL);
INSERT [dbo].[PARAMETRAGE] ([LIBELLE], [VALEUR], [SITEID], [DATECREATION], [DATEMAJ], [DATESYNCHRO]) VALUES (N'GESTION_ETAT', N'1', N'ALL', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL);
INSERT [dbo].[PARAMETRAGE] ([LIBELLE], [VALEUR], [SITEID], [DATECREATION], [DATEMAJ], [DATESYNCHRO]) VALUES (N'GESTION_VISITEUR', N'0', N'ALL', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL);
INSERT [dbo].[PARAMETRAGE] ([LIBELLE], [VALEUR], [SITEID], [DATECREATION], [DATEMAJ], [DATESYNCHRO]) VALUES (N'GESTION_VISITEUR_LOT', N'0', N'ALL', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL);
INSERT [dbo].[PARAMETRAGE] ([LIBELLE], [VALEUR], [SITEID], [DATECREATION], [DATEMAJ], [DATESYNCHRO]) VALUES (N'GRISER_DATE_DEBUT', N'1', N'ALL', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL);
INSERT [dbo].[PARAMETRAGE] ([LIBELLE], [VALEUR], [SITEID], [DATECREATION], [DATEMAJ], [DATESYNCHRO]) VALUES (N'GRPUSER_LOCALISATION', N'0', N'ALL', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL);
INSERT [dbo].[PARAMETRAGE] ([LIBELLE], [VALEUR], [SITEID], [DATECREATION], [DATEMAJ], [DATESYNCHRO]) VALUES (N'HEURE_DEBUT', N'08:00', N'ALL', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL);
INSERT [dbo].[PARAMETRAGE] ([LIBELLE], [VALEUR], [SITEID], [DATECREATION], [DATEMAJ], [DATESYNCHRO]) VALUES (N'HEURE_EN_PLUS', N'2', N'ALL', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL);
INSERT [dbo].[PARAMETRAGE] ([LIBELLE], [VALEUR], [SITEID], [DATECREATION], [DATEMAJ], [DATESYNCHRO]) VALUES (N'HEURE_FIN', N'2', N'ALL', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL);
INSERT [dbo].[PARAMETRAGE] ([LIBELLE], [VALEUR], [SITEID], [DATECREATION], [DATEMAJ], [DATESYNCHRO]) VALUES (N'HEURE_MAX_DEBUT', N'07:00', N'ALL', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL);
INSERT [dbo].[PARAMETRAGE] ([LIBELLE], [VALEUR], [SITEID], [DATECREATION], [DATEMAJ], [DATESYNCHRO]) VALUES (N'HEURE_MAX_FIN', N'20:00', N'ALL', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL);
INSERT [dbo].[PARAMETRAGE] ([LIBELLE], [VALEUR], [SITEID], [DATECREATION], [DATEMAJ], [DATESYNCHRO]) VALUES (N'INTERDIRE_VISITEUR_SI_REFUS_VISITE', N'0', N'ALL', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL);
INSERT [dbo].[PARAMETRAGE] ([LIBELLE], [VALEUR], [SITEID], [DATECREATION], [DATEMAJ], [DATESYNCHRO]) VALUES (N'JOUR_ENPLUS', N'0', N'ALL', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL);
INSERT [dbo].[PARAMETRAGE] ([LIBELLE], [VALEUR], [SITEID], [DATECREATION], [DATEMAJ], [DATESYNCHRO]) VALUES (N'LIMIT_DUREE_VISITE', N'0', N'ALL', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL);
INSERT [dbo].[PARAMETRAGE] ([LIBELLE], [VALEUR], [SITEID], [DATECREATION], [DATEMAJ], [DATESYNCHRO]) VALUES (N'LIMIT_DUREE_VISITE_NB', N'5', N'ALL', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL);
INSERT [dbo].[PARAMETRAGE] ([LIBELLE], [VALEUR], [SITEID], [DATECREATION], [DATEMAJ], [DATESYNCHRO]) VALUES (N'LOCAL_BADGE_DETAIL', N'profil', N'ALL', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL);
INSERT [dbo].[PARAMETRAGE] ([LIBELLE], [VALEUR], [SITEID], [DATECREATION], [DATEMAJ], [DATESYNCHRO]) VALUES (N'LOCAL_BADGE_HEBERGE', N'0', N'ALL', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL);
INSERT [dbo].[PARAMETRAGE] ([LIBELLE], [VALEUR], [SITEID], [DATECREATION], [DATEMAJ], [DATESYNCHRO]) VALUES (N'LOCAL_BADGE_SOCIETE', N'0', N'ALL', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL);
INSERT [dbo].[PARAMETRAGE] ([LIBELLE], [VALEUR], [SITEID], [DATECREATION], [DATEMAJ], [DATESYNCHRO]) VALUES (N'LOCALISATION_BAIE', N'0', N'ALL', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL);
INSERT [dbo].[PARAMETRAGE] ([LIBELLE], [VALEUR], [SITEID], [DATECREATION], [DATEMAJ], [DATESYNCHRO]) VALUES (N'LOCALISATION_CLE', N'0', N'ALL', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL);
INSERT [dbo].[PARAMETRAGE] ([LIBELLE], [VALEUR], [SITEID], [DATECREATION], [DATEMAJ], [DATESYNCHRO]) VALUES (N'LOCALISATION_CODE', N'0', N'ALL', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL);
INSERT [dbo].[PARAMETRAGE] ([LIBELLE], [VALEUR], [SITEID], [DATECREATION], [DATEMAJ], [DATESYNCHRO]) VALUES (N'LOCALISATION_EMPREINTE', N'0', N'ALL', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL);
INSERT [dbo].[PARAMETRAGE] ([LIBELLE], [VALEUR], [SITEID], [DATECREATION], [DATEMAJ], [DATESYNCHRO]) VALUES (N'LOCALISATION_OBLIGATOIRE', N'0', N'ALL', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL);
INSERT [dbo].[PARAMETRAGE] ([LIBELLE], [VALEUR], [SITEID], [DATECREATION], [DATEMAJ], [DATESYNCHRO]) VALUES (N'LOCALISATION_PROFIL', N'0', N'ALL', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL);
INSERT [dbo].[PARAMETRAGE] ([LIBELLE], [VALEUR], [SITEID], [DATECREATION], [DATEMAJ], [DATESYNCHRO]) VALUES (N'LOCALISATION_SALLE_CAGE', N'0', N'ALL', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL);
INSERT [dbo].[PARAMETRAGE] ([LIBELLE], [VALEUR], [SITEID], [DATECREATION], [DATEMAJ], [DATESYNCHRO]) VALUES (N'LOCALISATION_SOCIETE', N'0', N'ALL', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL);
INSERT [dbo].[PARAMETRAGE] ([LIBELLE], [VALEUR], [SITEID], [DATECREATION], [DATEMAJ], [DATESYNCHRO]) VALUES (N'LOCALISATION_TYPE', N'0', N'ALL', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL);
INSERT [dbo].[PARAMETRAGE] ([LIBELLE], [VALEUR], [SITEID], [DATECREATION], [DATEMAJ], [DATESYNCHRO]) VALUES (N'MASQUER_BTN_ACCOMPAGNER', N'0', N'ALL', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL);
INSERT [dbo].[PARAMETRAGE] ([LIBELLE], [VALEUR], [SITEID], [DATECREATION], [DATEMAJ], [DATESYNCHRO]) VALUES (N'MASQUER_BTN_INCOMPLET', N'0', N'ALL', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL);
INSERT [dbo].[PARAMETRAGE] ([LIBELLE], [VALEUR], [SITEID], [DATECREATION], [DATEMAJ], [DATESYNCHRO]) VALUES (N'MASQUER_BTN_VALIDER', N'0', N'ALL', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL);
INSERT [dbo].[PARAMETRAGE] ([LIBELLE], [VALEUR], [SITEID], [DATECREATION], [DATEMAJ], [DATESYNCHRO]) VALUES (N'MAX_CPT', N'200', N'ALL', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL);
INSERT [dbo].[PARAMETRAGE] ([LIBELLE], [VALEUR], [SITEID], [DATECREATION], [DATEMAJ], [DATESYNCHRO]) VALUES (N'MAX_PERIODE', N'90', N'ALL', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL);
INSERT [dbo].[PARAMETRAGE] ([LIBELLE], [VALEUR], [SITEID], [DATECREATION], [DATEMAJ], [DATESYNCHRO]) VALUES (N'MAX_SIZE_DOC', N'0', N'ALL', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL);
INSERT [dbo].[PARAMETRAGE] ([LIBELLE], [VALEUR], [SITEID], [DATECREATION], [DATEMAJ], [DATESYNCHRO]) VALUES (N'MODIF_OBS_VISITEUR', N'0', N'ALL', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL);
INSERT [dbo].[PARAMETRAGE] ([LIBELLE], [VALEUR], [SITEID], [DATECREATION], [DATEMAJ], [DATESYNCHRO]) VALUES (N'MODIF_VISITEUR_ENCOURS', N'0', N'ALL', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL);
INSERT [dbo].[PARAMETRAGE] ([LIBELLE], [VALEUR], [SITEID], [DATECREATION], [DATEMAJ], [DATESYNCHRO]) VALUES (N'MODIF_VISITEUR_PREENREG', N'0', N'ALL', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL);
INSERT [dbo].[PARAMETRAGE] ([LIBELLE], [VALEUR], [SITEID], [DATECREATION], [DATEMAJ], [DATESYNCHRO]) VALUES (N'MODIF_VISITEUR_TERMINE', N'0', N'ALL', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL);
INSERT [dbo].[PARAMETRAGE] ([LIBELLE], [VALEUR], [SITEID], [DATECREATION], [DATEMAJ], [DATESYNCHRO]) VALUES (N'NB_ENROLE', N'2', N'ALL', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL);
INSERT [dbo].[PARAMETRAGE] ([LIBELLE], [VALEUR], [SITEID], [DATECREATION], [DATEMAJ], [DATESYNCHRO]) VALUES (N'OBJET_VISITE_OBLIGATOIRE', N'0', N'ALL', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL);
INSERT [dbo].[PARAMETRAGE] ([LIBELLE], [VALEUR], [SITEID], [DATECREATION], [DATEMAJ], [DATESYNCHRO]) VALUES (N'ORDRE_SALLE', N'n', N'ALL', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL);
INSERT [dbo].[PARAMETRAGE] ([LIBELLE], [VALEUR], [SITEID], [DATECREATION], [DATEMAJ], [DATESYNCHRO]) VALUES (N'OS_INTERDIT_MODIF', N'0', N'ALL', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL);
INSERT [dbo].[PARAMETRAGE] ([LIBELLE], [VALEUR], [SITEID], [DATECREATION], [DATEMAJ], [DATESYNCHRO]) VALUES (N'OSFIRST', N'1', N'ALL', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL);
INSERT [dbo].[PARAMETRAGE] ([LIBELLE], [VALEUR], [SITEID], [DATECREATION], [DATEMAJ], [DATESYNCHRO]) VALUES (N'PARAMETRAGE_PORTAIL', N'salle,accueil,facility,main_courante,services,workplace,access', N'ucykN2IqWsWk0', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL);
INSERT [dbo].[PARAMETRAGE] ([LIBELLE], [VALEUR], [SITEID], [DATECREATION], [DATEMAJ], [DATESYNCHRO]) VALUES (N'PARAMETRAGE_PORTAIL', N'salle,accueil,facility,main_courante,services,workplace,access', N'VPARDEFAUT', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL);
INSERT [dbo].[PARAMETRAGE] ([LIBELLE], [VALEUR], [SITEID], [DATECREATION], [DATEMAJ], [DATESYNCHRO]) VALUES (N'PERIPH_ACQUI_CREATION_FICHE', N'1', N'ALL', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL);
INSERT [dbo].[PARAMETRAGE] ([LIBELLE], [VALEUR], [SITEID], [DATECREATION], [DATEMAJ], [DATESYNCHRO]) VALUES (N'PERIPH_ACQUI_MAJ_INFOS', N'0', N'ALL', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL);
INSERT [dbo].[PARAMETRAGE] ([LIBELLE], [VALEUR], [SITEID], [DATECREATION], [DATEMAJ], [DATESYNCHRO]) VALUES (N'PERMIS_TRAVAIL', N'0', N'ALL', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL);
INSERT [dbo].[PARAMETRAGE] ([LIBELLE], [VALEUR], [SITEID], [DATECREATION], [DATEMAJ], [DATESYNCHRO]) VALUES (N'PHOTO_RESIDANT', N'1', N'ALL', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL);
INSERT [dbo].[PARAMETRAGE] ([LIBELLE], [VALEUR], [SITEID], [DATECREATION], [DATEMAJ], [DATESYNCHRO]) VALUES (N'PHOTO_VISITEUR', N'1', N'ALL', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL);
INSERT [dbo].[PARAMETRAGE] ([LIBELLE], [VALEUR], [SITEID], [DATECREATION], [DATEMAJ], [DATESYNCHRO]) VALUES (N'PLANNING_AFF_JOUR', N'1,2,3,4,5,6,7', N'ALL', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL);
INSERT [dbo].[PARAMETRAGE] ([LIBELLE], [VALEUR], [SITEID], [DATECREATION], [DATEMAJ], [DATESYNCHRO]) VALUES (N'PLANNING_JOUR', N'7', N'ALL', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL);
INSERT [dbo].[PARAMETRAGE] ([LIBELLE], [VALEUR], [SITEID], [DATECREATION], [DATEMAJ], [DATESYNCHRO]) VALUES (N'PLANNING_PERS_JOUR', N'1,2,3,4,5,6,7', N'ALL', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL);
INSERT [dbo].[PARAMETRAGE] ([LIBELLE], [VALEUR], [SITEID], [DATECREATION], [DATEMAJ], [DATESYNCHRO]) VALUES (N'PREENREG_OBLIGATOIRE', N'0', N'ALL', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL);
INSERT [dbo].[PARAMETRAGE] ([LIBELLE], [VALEUR], [SITEID], [DATECREATION], [DATEMAJ], [DATESYNCHRO]) VALUES (N'PREENREG_PROFIL', N'0', N'ALL', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL);
INSERT [dbo].[PARAMETRAGE] ([LIBELLE], [VALEUR], [SITEID], [DATECREATION], [DATEMAJ], [DATESYNCHRO]) VALUES (N'PREENREG_SELECTION_RESIDANT', N'0', N'ALL', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL);
INSERT [dbo].[PARAMETRAGE] ([LIBELLE], [VALEUR], [SITEID], [DATECREATION], [DATEMAJ], [DATESYNCHRO]) VALUES (N'PRET_PTI', N'0', N'ALL', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL);
INSERT [dbo].[PARAMETRAGE] ([LIBELLE], [VALEUR], [SITEID], [DATECREATION], [DATEMAJ], [DATESYNCHRO]) VALUES (N'PREVENIR_VISITES_DOUBLON', N'0', N'ALL', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL);
INSERT [dbo].[PARAMETRAGE] ([LIBELLE], [VALEUR], [SITEID], [DATECREATION], [DATEMAJ], [DATESYNCHRO]) VALUES (N'READONLYSOC', N'0', N'ALL', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL);
INSERT [dbo].[PARAMETRAGE] ([LIBELLE], [VALEUR], [SITEID], [DATECREATION], [DATEMAJ], [DATESYNCHRO]) VALUES (N'RECALCUL_PAR_OS', N'0', N'ALL', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL);
INSERT [dbo].[PARAMETRAGE] ([LIBELLE], [VALEUR], [SITEID], [DATECREATION], [DATEMAJ], [DATESYNCHRO]) VALUES (N'RECH_CODE_IMPUTATION_AFFICHAGE', N'', N'ALL', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL);
INSERT [dbo].[PARAMETRAGE] ([LIBELLE], [VALEUR], [SITEID], [DATECREATION], [DATEMAJ], [DATESYNCHRO]) VALUES (N'RECH_SALLE_AFFICHAGE', N'', N'ALL', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL);
INSERT [dbo].[PARAMETRAGE] ([LIBELLE], [VALEUR], [SITEID], [DATECREATION], [DATEMAJ], [DATESYNCHRO]) VALUES (N'REGLEFIRST', N'1', N'ALL', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL);
INSERT [dbo].[PARAMETRAGE] ([LIBELLE], [VALEUR], [SITEID], [DATECREATION], [DATEMAJ], [DATESYNCHRO]) VALUES (N'REMETTRE_DANS_WEB', N'0', N'ALL', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL);
INSERT [dbo].[PARAMETRAGE] ([LIBELLE], [VALEUR], [SITEID], [DATECREATION], [DATEMAJ], [DATESYNCHRO]) VALUES (N'RESIDANT_ANNUAIRE', N'0', N'ALL', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL);
INSERT [dbo].[PARAMETRAGE] ([LIBELLE], [VALEUR], [SITEID], [DATECREATION], [DATEMAJ], [DATESYNCHRO]) VALUES (N'RESIDANT_COLIS', N'0', N'ALL', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL);
INSERT [dbo].[PARAMETRAGE] ([LIBELLE], [VALEUR], [SITEID], [DATECREATION], [DATEMAJ], [DATESYNCHRO]) VALUES (N'RESIDANT_MAX', N'5', N'ALL', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL);
INSERT [dbo].[PARAMETRAGE] ([LIBELLE], [VALEUR], [SITEID], [DATECREATION], [DATEMAJ], [DATESYNCHRO]) VALUES (N'RESIDANT_REFERENT_HEBERGE', N'0', N'ALL', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL);
INSERT [dbo].[PARAMETRAGE] ([LIBELLE], [VALEUR], [SITEID], [DATECREATION], [DATEMAJ], [DATESYNCHRO]) VALUES (N'SAISIE_BADGE_OBLIGATOIRE', N'0', N'ALL', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL);
INSERT [dbo].[PARAMETRAGE] ([LIBELLE], [VALEUR], [SITEID], [DATECREATION], [DATEMAJ], [DATESYNCHRO]) VALUES (N'SAISIE_PRODUITS_ADR', N'0', N'ALL', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL);
INSERT [dbo].[PARAMETRAGE] ([LIBELLE], [VALEUR], [SITEID], [DATECREATION], [DATEMAJ], [DATESYNCHRO]) VALUES (N'SELECT_FONCTION', N'0', N'ALL', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL);
INSERT [dbo].[PARAMETRAGE] ([LIBELLE], [VALEUR], [SITEID], [DATECREATION], [DATEMAJ], [DATESYNCHRO]) VALUES (N'SELECT_OBJVISITE', N'0', N'ALL', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL);
INSERT [dbo].[PARAMETRAGE] ([LIBELLE], [VALEUR], [SITEID], [DATECREATION], [DATEMAJ], [DATESYNCHRO]) VALUES (N'SELECT_OBJVISITE_DEFAUT', N'', N'ALL', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL);
INSERT [dbo].[PARAMETRAGE] ([LIBELLE], [VALEUR], [SITEID], [DATECREATION], [DATEMAJ], [DATESYNCHRO]) VALUES (N'SELECTION_SITE', N'0', N'ALL', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL);
INSERT [dbo].[PARAMETRAGE] ([LIBELLE], [VALEUR], [SITEID], [DATECREATION], [DATEMAJ], [DATESYNCHRO]) VALUES (N'SIGN_PDF_CLE', N'', N'ALL', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL);
INSERT [dbo].[PARAMETRAGE] ([LIBELLE], [VALEUR], [SITEID], [DATECREATION], [DATEMAJ], [DATESYNCHRO]) VALUES (N'SIGN_PDF_COLIS', N'', N'ALL', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL);
INSERT [dbo].[PARAMETRAGE] ([LIBELLE], [VALEUR], [SITEID], [DATECREATION], [DATEMAJ], [DATESYNCHRO]) VALUES (N'SIGN_PDF_VISITEUR', N'', N'ALL', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL);
INSERT [dbo].[PARAMETRAGE] ([LIBELLE], [VALEUR], [SITEID], [DATECREATION], [DATEMAJ], [DATESYNCHRO]) VALUES (N'SIGNATURE_VISITEUR_PREMIERE', N'0', N'ALL', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL);
INSERT [dbo].[PARAMETRAGE] ([LIBELLE], [VALEUR], [SITEID], [DATECREATION], [DATEMAJ], [DATESYNCHRO]) VALUES (N'SITE_SSR', N'0', N'ALL', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL);
INSERT [dbo].[PARAMETRAGE] ([LIBELLE], [VALEUR], [SITEID], [DATECREATION], [DATEMAJ], [DATESYNCHRO]) VALUES (N'SOCIETE_DOCUMENT', N'0', N'ALL', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL);
INSERT [dbo].[PARAMETRAGE] ([LIBELLE], [VALEUR], [SITEID], [DATECREATION], [DATEMAJ], [DATESYNCHRO]) VALUES (N'STATISTIQUES_TOP', N'10', N'ALL', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL);
INSERT [dbo].[PARAMETRAGE] ([LIBELLE], [VALEUR], [SITEID], [DATECREATION], [DATEMAJ], [DATESYNCHRO]) VALUES (N'STATUTVISITE_CONTROLE', N'2', N'ALL', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL);
INSERT [dbo].[PARAMETRAGE] ([LIBELLE], [VALEUR], [SITEID], [DATECREATION], [DATEMAJ], [DATESYNCHRO]) VALUES (N'SUPP_RESA_MEME_REFERENCE', N'0', N'ALL', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL);
INSERT [dbo].[PARAMETRAGE] ([LIBELLE], [VALEUR], [SITEID], [DATECREATION], [DATEMAJ], [DATESYNCHRO]) VALUES (N'suppavisos', N'0', N'ALL', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL);
INSERT [dbo].[PARAMETRAGE] ([LIBELLE], [VALEUR], [SITEID], [DATECREATION], [DATEMAJ], [DATESYNCHRO]) VALUES (N'TELEMAQUE_FONCTIONS', N'accueil,sortie,preenreg,sur_site,historique,messagerie,annuaire,en_attente,vehicules', N'ALL', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL);
INSERT [dbo].[PARAMETRAGE] ([LIBELLE], [VALEUR], [SITEID], [DATECREATION], [DATEMAJ], [DATESYNCHRO]) VALUES (N'TIMEZONE_SGBD', N'+01:00', N'ALL', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL);
INSERT [dbo].[PARAMETRAGE] ([LIBELLE], [VALEUR], [SITEID], [DATECREATION], [DATEMAJ], [DATESYNCHRO]) VALUES (N'TIMEZONE_WEB', N'+01:00', N'ALL', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL);
INSERT [dbo].[PARAMETRAGE] ([LIBELLE], [VALEUR], [SITEID], [DATECREATION], [DATEMAJ], [DATESYNCHRO]) VALUES (N'UNIQUEMENT_WEB_NON_INTERDITS', N'0', N'ALL', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL);
INSERT [dbo].[PARAMETRAGE] ([LIBELLE], [VALEUR], [SITEID], [DATECREATION], [DATEMAJ], [DATESYNCHRO]) VALUES (N'UTILISATION_OBS_VISITEUR', N'0', N'ALL', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL);
INSERT [dbo].[PARAMETRAGE] ([LIBELLE], [VALEUR], [SITEID], [DATECREATION], [DATEMAJ], [DATESYNCHRO]) VALUES (N'VISITE_CASIER', N'0', N'ALL', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL);
INSERT [dbo].[PARAMETRAGE] ([LIBELLE], [VALEUR], [SITEID], [DATECREATION], [DATEMAJ], [DATESYNCHRO]) VALUES (N'VISITE_DETAIL_DUPLIQUER', N'1', N'ALL', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL);
INSERT [dbo].[PARAMETRAGE] ([LIBELLE], [VALEUR], [SITEID], [DATECREATION], [DATEMAJ], [DATESYNCHRO]) VALUES (N'VISITE_DETAIL_EMETTEUR', N'1', N'ALL', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL);
INSERT [dbo].[PARAMETRAGE] ([LIBELLE], [VALEUR], [SITEID], [DATECREATION], [DATEMAJ], [DATESYNCHRO]) VALUES (N'VISITE_FORMULAIRE', N'0', N'ALL', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL);
INSERT [dbo].[PARAMETRAGE] ([LIBELLE], [VALEUR], [SITEID], [DATECREATION], [DATEMAJ], [DATESYNCHRO]) VALUES (N'VISITE_IDENTITE', N'1', N'ALL', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL);
INSERT [dbo].[PARAMETRAGE] ([LIBELLE], [VALEUR], [SITEID], [DATECREATION], [DATEMAJ], [DATESYNCHRO]) VALUES (N'VISITE_IDENTITE_OBLIGATOIRE', N'0', N'ALL', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL);
INSERT [dbo].[PARAMETRAGE] ([LIBELLE], [VALEUR], [SITEID], [DATECREATION], [DATEMAJ], [DATESYNCHRO]) VALUES (N'VISITE_LIEUX_VISITES', N'salle', N'ALL', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL);
INSERT [dbo].[PARAMETRAGE] ([LIBELLE], [VALEUR], [SITEID], [DATECREATION], [DATEMAJ], [DATESYNCHRO]) VALUES (N'VISITE_ORDRE_ELEMENT', N'visiteur,residant,localisation,periode,detail,identite,badge,vehicule,autres,pret_objet,observation,produit', N'ALL', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL);
INSERT [dbo].[PARAMETRAGE] ([LIBELLE], [VALEUR], [SITEID], [DATECREATION], [DATEMAJ], [DATESYNCHRO]) VALUES (N'VISITE_OU_TRAVAIL', N'0', N'ALL', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL);
INSERT [dbo].[PARAMETRAGE] ([LIBELLE], [VALEUR], [SITEID], [DATECREATION], [DATEMAJ], [DATESYNCHRO]) VALUES (N'VISITE_PERSONNE_PREVENIR', N'1', N'ALL', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL);
INSERT [dbo].[PARAMETRAGE] ([LIBELLE], [VALEUR], [SITEID], [DATECREATION], [DATEMAJ], [DATESYNCHRO]) VALUES (N'VISITE_REUNION', N'0', N'ALL', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL);
INSERT [dbo].[PARAMETRAGE] ([LIBELLE], [VALEUR], [SITEID], [DATECREATION], [DATEMAJ], [DATESYNCHRO]) VALUES (N'VISITE_TYPEVISITE_DEFAUT', N'', N'ALL', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL);
INSERT [dbo].[PARAMETRAGE] ([LIBELLE], [VALEUR], [SITEID], [DATECREATION], [DATEMAJ], [DATESYNCHRO]) VALUES (N'VISITE_TYPEVISITE_HIDDEN', N'0', N'ALL', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL);
INSERT [dbo].[PARAMETRAGE] ([LIBELLE], [VALEUR], [SITEID], [DATECREATION], [DATEMAJ], [DATESYNCHRO]) VALUES (N'VISITE_UN_LIEU', N'0', N'ALL', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL);
INSERT [dbo].[PARAMETRAGE] ([LIBELLE], [VALEUR], [SITEID], [DATECREATION], [DATEMAJ], [DATESYNCHRO]) VALUES (N'VISITE_VEHICULE', N'0', N'ALL', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL);
INSERT [dbo].[PARAMETRAGE] ([LIBELLE], [VALEUR], [SITEID], [DATECREATION], [DATEMAJ], [DATESYNCHRO]) VALUES (N'VISITEUR_DOCUMENT', N'0', N'ALL', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL);
INSERT [dbo].[PARAMETRAGE] ([LIBELLE], [VALEUR], [SITEID], [DATECREATION], [DATEMAJ], [DATESYNCHRO]) VALUES (N'VISITEUR_MAX', N'10', N'ALL', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL);
INSERT [dbo].[PARAMETRAGE] ([LIBELLE], [VALEUR], [SITEID], [DATECREATION], [DATEMAJ], [DATESYNCHRO]) VALUES (N'ZONE_ACCES', N'0', N'ALL', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL);
