INSERT INTO PARAMETRAGE (LIBELLE,VALEUR,SITEID,DATECREATION,DATEMAJ) SELECT 'TIMEZONE_SGBD','+01:00','ALL',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP WHERE NOT EXISTS (SELECT LIBELLE FROM PARAMETRAGE WHERE LIBELLE='TIMEZONE_SGBD' AND SITEID='ALL');
GO
INSERT INTO PARAMETRAGE (LIBELLE,VALEUR,SITEID,DATECREATION,DATEMAJ) SELECT 'TIMEZONE_WEB','+01:00','ALL',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP WHERE NOT EXISTS (SELECT LIBELLE FROM PARAMETRAGE WHERE LIBELLE='TIMEZONE_WEB' AND SITEID='ALL');
GO