ALTER TABLE AMENAGSALLE ADD SORTORDER INTEGER;
UPDATE AMENAGSALLE SET SORTORDER=0;

DROP INDEX SALLE_SORTORDER;

CREATE TABLE GRPUSER (
   GRPUSERID      VARCHAR2(14),
   LIBELLE        VARCHAR2(50),
   NIVEAU         VARCHAR2(14),
   STATUT         VARCHAR2(14),
   STATUTCHECK    INTEGER,
   SURRESERVATION VARCHAR2(1),
   RESAPERIODIQUE VARCHAR2(1),
   ACCESDRAGDROP  VARCHAR2(1),
   PLANNING       VARCHAR2(2),
   RESA           VARCHAR2(15),
   PRESTA         VARCHAR2(15),
   DATECREATION DATE,
   DATEMAJ      DATE
);

CREATE TABLE GRPSALLE(
   GRPSALLEID   VARCHAR2(14),
   LIBELLE      VARCHAR2(50),
   HEUREDEBUT   DATE,
   HEUREFIN     DATE,
   OPENPRERESA  INTEGER,
   CLOSEPRERESA INTEGER,
   RESA         VARCHAR2(15),
   DATECREATION DATE,
   DATEMAJ      DATE
);

CREATE TABLE GRPSALLES_SAL(
   GRPSALLEID   VARCHAR2(14),
   SALLEID      VARCHAR2(14)
);

ALTER TABLE USERS ADD (
	GRPUSERID VARCHAR2(14)
);


CREATE TABLE USER_GRPS(
	USERID VARCHAR2(14),
	GRPSALLEID VARCHAR2(14)
);

INSERT INTO GRPUSER (GRPUSERID, LIBELLE, NIVEAU, STATUT, SURRESERVATION, RESAPERIODIQUE, ACCESDRAGDROP, PLANNING, RESA, PRESTA, DATECREATION, DATEMAJ, STATUTCHECK)
       VALUES ('ADMINISTRATEUR','ADMINISTRATEUR','2','VPARDEFAUT','1','1','1','11','000000111','1',SYSDATE,SYSDATE,1);
INSERT INTO GRPUSER (GRPUSERID, LIBELLE, NIVEAU, STATUT, SURRESERVATION, RESAPERIODIQUE, ACCESDRAGDROP, PLANNING, RESA, PRESTA, DATECREATION, DATEMAJ, STATUTCHECK)
       VALUES ('VPARDEFAUT','UTILISATEUR','1','VPARDEFAUT','0','0','0','10','111000000','0',SYSDATE,SYSDATE,0);
INSERT INTO GRPSALLE  (GRPSALLEID, LIBELLE, HEUREDEBUT, HEUREFIN, OPENPRERESA, CLOSEPRERESA, RESA, DATECREATION, DATEMAJ)
VALUES ('EVERYONE','EVERYONE',TO_DATE('00:00','HH24:MI'),TO_DATE('00:00','HH24:MI'),0,0,'1',SYSDATE,SYSDATE);

INSERT INTO USERS
(USERID, CIVILITEID, FIRSTNAME, USERTYPEID, GVACCESS, EXTERNALID, FULLNAME,  PROFIL_ID_ORGA, PROFIL_ID_INTER,PROFIL_SURBOOKING,THELOGIN, THEPASSWORD, USERTYPE, DATEMAJ, DATECREATION,GRPUSERID)
VALUES ('GESROOM',0,'ADMINISTRATEUR','Administrateur',78847,'VPARDEFAUT','ADMINISTRATEUR','VPARDEFAUT','VPARDEFAUT','0','ADM','ADM',1,SYSDATE,SYSDATE,'ADMINISTRATEUR')

ALTER TABLE CFGGSALLESPARAM ADD (DRAGDROP NUMBER);
UPDATE CFGGSALLESPARAM SET DRAGDROP=0;

ALTER TABLE CFGGSALLESPARAM ADD ( CTRLDEFAUTHORAIRE NUMBER);
UPDATE CFGGSALLESPARAM SET CTRLDEFAUTHORAIRE=0;


UPDATE RESIDANTS SET EXTERNALID='VPARDEFAUT' WHERE EXTERNALID IS NULL;
UPDATE RESIDANTS SET HABILITATIONVISITE=1 WHERE HABILITATIONVISITE IS NULL;
UPDATE RESIDANTS SET LISTEROUGE=0 WHERE LISTEROUGE IS NULL;
UPDATE RESIDANTS SET ISEXTERN=0 WHERE ISEXTERN IS NULL;
UPDATE RESIDANTS SET ISRESIDENT=1 WHERE ISRESIDENT IS NULL;
UPDATE RESIDANTS SET ISACTIF=1 WHERE ISACTIF IS NULL;
UPDATE RESIDANTS SET INTERDIT=0,DEBUTINTERDIT=SYSDATE-1,FININTERDIT=SYSDATE+36000 WHERE INTERDIT IS NULL;
UPDATE RESIDANTS SET NBBDGIMPR=0 WHERE NBBDGIMPR IS NULL;
--
ALTER TABLE GRPUSER ADD (
	EMAILAUTO VARCHAR2(1)
);

UPDATE GRPUSER SET EMAILAUTO='0';

ALTER TABLE ARTICLE ADD (
	HDEBUT  DATE,
	HFIN    DATE
);

CREATE TABLE CFGGSALLES (
SITE           VARCHAR2(30),
NETTOYAGE	   INTEGER,
E_EMAIL        VARCHAR2(15),
E_HOST         VARCHAR2(50),
E_REPERTOIRE   VARCHAR2(50),
E_USERID       VARCHAR2(50),
E_DESTINATAIRE INTEGER
);

UPDATE USERS SET GRPUSERID='VPARDEFAUT' WHERE GRPUSERID<>'ADMINISTRATEUR';
UPDATE USERS SET GRPUSERID='VPARDEFAUT' WHERE GRPUSERID IS NULL;

ALTER TABLE CFGGSALLESPARAM ADD ( CTRLDEFAUTPRESTA NUMBER);
UPDATE CFGGSALLESPARAM SET CTRLDEFAUTPRESTA=0;

ALTER TABLE LGRESERVATION ADD ( CODESALLEASS VARCHAR2(14));
UPDATE LGRESERVATION SET CODESALLEASS=CODESALLE;

ALTER TABLE HVISITES ADD (  ORIGINEVISITE    NUMBER);
ALTER TABLE HVISITES ADD (  NBBDGIMPR        NUMBER);
ALTER TABLE HVISITES ADD (  NBBDGIMPRTOTAL   NUMBER);

ALTER TABLE RESIDANTS ADD ( NBBDGIMPR NUMBER);

ALTER TABLE SOCIETE ADD ( NATUREID VARCHAR2 (14));

CREATE TABLE CFGETAT (
   CFGETATID    VARCHAR2(50),
   ETATNOM      VARCHAR2(50),
   VISIBLE      INTEGER,
   REQUETE      VARCHAR2(50),
   FILTRE       VARCHAR2(250),
   DATECREATION DATE,
   DATEMAJ      DATE
);


INSERT INTO CFGETAT (CFGETATID,ETATNOM,VISIBLE,REQUETE,FILTRE,DATECREATION,DATEMAJ) VALUES
  ('Reservationdessalles1','Reservation des salles',1,'EtatReservationSalleAccueil','',SYSDATE,SYSDATE);

INSERT INTO CFGETAT (CFGETATID,ETATNOM,VISIBLE,REQUETE,FILTRE,DATECREATION,DATEMAJ) VALUES
  ('Equipementdessalles1','Equipement des salles',1,'EtatEquipementdessalles','AND F.LIBELLE<>''ALIMENTAIRE''',SYSDATE,SYSDATE);

INSERT INTO CFGETAT (CFGETATID,ETATNOM,VISIBLE,REQUETE,FILTRE,DATECREATION,DATEMAJ) VALUES
  ('Restauration1','Restauration',1,'EtatRestaurations','AND F.LIBELLE=''ALIMENTAIRE'' AND UPPER(A.LIBELLE)<>UPPER(''jetons'') AND UPPER(A.LIBELLE)<>UPPER(''Places pour repas'')',SYSDATE,SYSDATE);

INSERT INTO CFGETAT (CFGETATID,ETATNOM,VISIBLE,REQUETE,FILTRE,DATECREATION,DATEMAJ) VALUES
  ('Reservations1','Reservations',1,'EtatReservationListe','',SYSDATE,SYSDATE);

INSERT INTO CFGETAT (CFGETATID,ETATNOM,VISIBLE,REQUETE,FILTRE,DATECREATION,DATEMAJ) VALUES
  ('Places1','Places',1,'EtatPlaces','AND F.LIBELLE=''ALIMENTAIRE'' AND SF.SOUSFAMILLE=''PLACES''',SYSDATE,SYSDATE);

INSERT INTO CFGETAT (CFGETATID,ETATNOM,VISIBLE,REQUETE,FILTRE,DATECREATION,DATEMAJ) VALUES
  ('Jetons1','Jetons',1,'EtatJetons','AND F.LIBELLE=''ALIMENTAIRE'' AND UPPER(A.LIBELLE)=UPPER(''jetons'')',SYSDATE,SYSDATE);

INSERT INTO CFGETAT (CFGETATID,ETATNOM,VISIBLE,REQUETE,FILTRE,DATECREATION,DATEMAJ) VALUES
  ('Facturation1','Facturation Matériels et Prestations',1,'EtatFacturationMaterielEtPrestation','AND ( F.LIBELLE=''MATERIEL TECHNIQUE'' OR F.LIBELLE=''PRESTATIONS TECHNIQUES'')',SYSDATE,SYSDATE);

INSERT INTO CFGETAT (CFGETATID,ETATNOM,VISIBLE,REQUETE,FILTRE,DATECREATION,DATEMAJ) VALUES
  ('FacturationSalles1','Facturation Salles',1,'EtatFacturationSalle','',SYSDATE,SYSDATE);

INSERT INTO CFGETAT (CFGETATID,ETATNOM,VISIBLE,REQUETE,FILTRE,DATECREATION,DATEMAJ) VALUES
  ('Restaurationsur7j1','Restauration sur 7j',1,'EtatRestaurationSurXJours','AND F.LIBELLE=''RESTAURATION''',SYSDATE,SYSDATE);

INSERT INTO CFGETAT (CFGETATID,ETATNOM,VISIBLE,REQUETE,FILTRE,DATECREATION,DATEMAJ) VALUES
  ('Reservation1','Reservation des salles',1,'EtatReservationTypeReunion','',SYSDATE,SYSDATE);

INSERT INTO CFGETAT (CFGETATID,ETATNOM,VISIBLE,REQUETE,FILTRE,DATECREATION,DATEMAJ) VALUES
  ('Equipementdessalles2','Equipement des salles',1,'EtatEquipementdessallesTypeReunion','AND F.LIBELLE<>''RESTAURATION''',SYSDATE,SYSDATE);

INSERT INTO CFGETAT (CFGETATID,ETATNOM,VISIBLE,REQUETE,FILTRE,DATECREATION,DATEMAJ) VALUES
  ('Prvisionpause1','Prévision pauses',1,'EtatPrevisionPauses','AND F.LIBELLE=''RESTAURATION'' AND SF.SOUSFAMILLE=''PAUSES''',SYSDATE,SYSDATE);

INSERT INTO CFGETAT (CFGETATID,ETATNOM,VISIBLE,REQUETE,FILTRE,DATECREATION,DATEMAJ) VALUES
  ('Bonderestauration1','Bon de restauration',1,'EtatBonDeRestauration','AND F.LIBELLE=''RESTAURATION'' AND SF.SOUSFAMILLE=''REPAS''',SYSDATE,SYSDATE);

INSERT INTO CFGETAT (CFGETATID,ETATNOM,VISIBLE,REQUETE,FILTRE,DATECREATION,DATEMAJ) VALUES
  ('Salledereunionavecprestationrestaurant1','Salle de reunion avec prestation restaurant',1,'EtatReservationSallePrestationRestaurant','AND F.LIBELLE=''RESTAURATION'' ',SYSDATE,SYSDATE);

CREATE GLOBAL TEMPORARY TABLE TEMPO_GS
(	FREE1	VARCHAR2(100),
	FREE2	VARCHAR2(100),
	FREE3	VARCHAR2(100),
	FREE4	VARCHAR2(100),
	FREE5	VARCHAR2(100),
	FREEINT1	INTEGER,
	FREEINT2	INTEGER,
	FREEDATE1	DATE,
	FREEDATE2	DATE,
	FREEDATE3	DATE,
	FREEDATE4	DATE
) ON COMMIT PRESERVE ROWS ;


-- INSERTION DES NOUVEAU ETAT

INSERT INTO CFGETAT (CFGETATID,ETATNOM,VISIBLE,REQUETE,FILTRE,DATECREATION,DATEMAJ) VALUES
  ('gsrm011','Réservation par tranche horaire',1,'','',SYSDATE,SYSDATE);

INSERT INTO CFGETAT (CFGETATID,ETATNOM,VISIBLE,REQUETE,FILTRE,DATECREATION,DATEMAJ) VALUES
  ('gsrm021','Taux d''occupation par société',1,'','',SYSDATE,SYSDATE);

INSERT INTO CFGETAT (CFGETATID,ETATNOM,VISIBLE,REQUETE,FILTRE,DATECREATION,DATEMAJ) VALUES
  ('gsrm031','Liste des réservations par société',1,'','',SYSDATE,SYSDATE);


COMMIT;
EXIT;