ALTER TABLE RAPPORT ADD TYPERAPPORT INTEGER;

UPDATE RAPPORT SET TYPERAPPORT=0;

CREATE TABLE GRPEVENEMENT (
  GRPEVENEMENTID   NUMBER(10, 0) PRIMARY KEY,
  LIBELLE          VARCHAR(50),
  DATECREATION     DATE,
  DATEMAJ          DATE
);

INSERT INTO GRPEVENEMENT (GRPEVENEMENTID,LIBELLE,DATECREATION,DATEMAJ) VALUES (0,'SURETE',SYSDATE,SYSDATE);

ALTER TABLE EVENEMENT ADD GRPEVENEMENTID INTEGER;

UPDATE EVENEMENT SET GRPEVENEMENTID=0;

CREATE TABLE RONDIER (
  RONDIERID        INTEGER PRIMARY KEY,
  LIBELLE          VARCHAR(50),
  SITEID           VARCHAR(14),
  DATECREATION     DATE,
  DATEMAJ          DATE
);

CREATE TABLE RONDE (
  RONDEID          INTEGER PRIMARY KEY,
  NUMERO	   INTEGER,
  LIBELLE          VARCHAR(50),
  SITEID           VARCHAR(14),
  DATECREATION     DATE,
  DATEMAJ          DATE
);

CREATE TABLE ORONDE (
  ORONDEID         NUMBER(10, 0) PRIMARY KEY,
  RONDIERID        NUMBER(10, 0),
  RONDIERLIB       VARCHAR(50),
  RONDENUM         INTEGER,
  RONDELIB         VARCHAR(50),
  SITEID           VARCHAR(14),
  RONDEDATE        DATE,
  DETAILS          VARCHAR(4000),
  ETAT             INTEGER,
  RONDEAGENT	   VARCHAR(50),
  AGENTID	   NUMBER(10, 0),
  DATECREATION     DATE,
  DATEMAJ          DATE
);


CREATE TABLE RONDECLEEVT (
  RONDECLEEVTID   NUMBER(10, 0) PRIMARY KEY,
  MOTCLE           VARCHAR(50),
  EVENEMENTID      INTEGER,
  DATECREATION     DATE,
  DATEMAJ          DATE
);

CREATE TABLE RONDEMOTCLE (
  RONDEMOTCLEID    NUMBER(10, 0) PRIMARY KEY,
  LIBELLE          VARCHAR(50),
  DATECREATION     DATE,
  DATEMAJ          DATE
);

CREATE TABLE RONDEMOTCLE_EVT (
  RONDEMOTCLEID    NUMBER(10,0),
  EVENEMENTID     NUMBER(10,0)
);


INSERT INTO RONDEMOTCLE (RONDEMOTCLEID,LIBELLE,DATECREATION,DATEMAJ) VALUES (1,'NON PREVU',SYSDATE,SYSDATE);
INSERT INTO RONDEMOTCLE (RONDEMOTCLEID,LIBELLE,DATECREATION,DATEMAJ) VALUES (2,'INCIDENT',SYSDATE,SYSDATE);
INSERT INTO RONDEMOTCLE (RONDEMOTCLEID,LIBELLE,DATECREATION,DATEMAJ) VALUES (3,'DEJA LU',SYSDATE,SYSDATE);
INSERT INTO RONDEMOTCLE (RONDEMOTCLEID,LIBELLE,DATECREATION,DATEMAJ) VALUES (4,'NON DEFINI',SYSDATE,SYSDATE);
INSERT INTO RONDEMOTCLE (RONDEMOTCLEID,LIBELLE,DATECREATION,DATEMAJ) VALUES (5,'MANQUE',SYSDATE,SYSDATE);

CREATE SEQUENCE SEQ_GRPEVENEMENT;

CREATE SEQUENCE SEQ_RONDIER;

CREATE SEQUENCE SEQ_ORONDE;

CREATE SEQUENCE SEQ_RONDEMOTCLE START WITH 10;


CREATE TABLE OFICHIER (
  OFICHIERID NUMBER(10, 0) NOT NULL,
  LIBELLE VARCHAR(200),
  DOCUMENT VARCHAR(2000),
  DATEMAJ DATE,
  DATECREATION DATE,
  DATESYNCHRO DATE)
;


CREATE TABLE ONOTE (
  ONOTEID        NUMBER(10, 0)  PRIMARY KEY,
  EXPEDITEURID   NUMBER(10, 0),
  DESTINATAIREID NUMBER(10, 0),
  EXPEDITEUR     VARCHAR(70),
  DESTINATAIRE   VARCHAR(70),
  OBJET          VARCHAR(70),
  CORPS          VARCHAR(2000),
  SUPPEXP        INTEGER,
  SUPPDEST       INTEGER,
  NEW            INTEGER,
  DATECREATION   DATE not null,
  DATEMAJ        DATE
);


CREATE SEQUENCE SEQ_ONOTE;

ALTER TABLE POSTE ADD TYPEPOSTE INTEGER;
ALTER TABLE POSTE ADD PRISEPOSTE INTEGER;

UPDATE POSTE SET TYPEPOSTE=0;
UPDATE POSTE SET PRISEPOSTE=0;

ALTER TABLE RONDEMOTCLE ADD ETAT INTEGER;

UPDATE RONDEMOTCLE SET ETAT=1;

ALTER TABLE JOUR ADD DATEOFWEEK INTEGER;


UPDATE JOUR SET DATEOFWEEK=1 WHERE CL = 7;
UPDATE JOUR SET DATEOFWEEK=2 WHERE CL = 1;
UPDATE JOUR SET DATEOFWEEK=3 WHERE CL = 2;
UPDATE JOUR SET DATEOFWEEK=4 WHERE CL = 3;
UPDATE JOUR SET DATEOFWEEK=5 WHERE CL = 4;
UPDATE JOUR SET DATEOFWEEK=6 WHERE CL = 5;
UPDATE JOUR SET DATEOFWEEK=7 WHERE CL = 6;

COMMIT;
EXIT;


