CREATE TABLE LGPARTICIPANT (
	LGPARTICIPANTID VARCHAR(14) NOT NULL,
	CODELGRESERVATION  VARCHAR(14),
	RESIDANTID  VARCHAR(14),
	INTERLOCUTEURID  VARCHAR(14),
        CIVILITE VARCHAR(14),
        NOM VARCHAR(35),
        PRENOM VARCHAR(35),
        SOCIETE VARCHAR(35),
        EMAIL VARCHAR(50),
        DATECREATION DATE NOT NULL,
        DATEMAJ DATE NOT NULL,
        DATESYNCHRO DATE);

ALTER TABLE JOURNAL ADD RESA_REF VARCHAR2(15);
ALTER TABLE JOURNAL ADD NOMPRENOM VARCHAR2(40);
ALTER TABLE JOURNAL ADD SALLE_NO_LIB VARCHAR2(40);
ALTER TABLE JOURNAL ADD RESA_DHDEBUT DATE;
ALTER TABLE JOURNAL ADD RESA_DHFIN DATE;
ALTER TABLE JOURNAL ADD RESA_CREATION DATE;

--------------------------------------------------------
-- 2002_02_20
ALTER TABLE NATURE ADD (
  TVISITE	VARCHAR2(1),
  PROFIL	VARCHAR2(20)
);
--------------------------------------------------------
-- 2002_09_03
ALTER TABLE CFGGSALLESPARAM ADD ActivationTempsPrepa NUMBER;
ALTER TABLE AMENAGEMENT ADD Coefficient FLOAT;
ALTER TABLE PXACHAT ADD ContactID VARCHAR2(14);

ALTER TABLE STATUTRESERVATION ADD (
  Confirmation	NUMBER,
  Message	BLOB,
  NbJourAD	NUMBER,
  NbJourAR	NUMBER,
  NbJourDelai	NUMBER
);

ALTER TABLE CFGGSALLESDEFAULT ADD(
PREPARATIONDEFAUT	DATE,
RANGEMENTDEFAUT		DATE
);

--------------------------------------------------------
-- 2002_09_12
--  Table IMPUTATION
CREATE TABLE IMPUTATION (
  IMPUTATIONID VARCHAR2(14) NOT NULL,
  LIBELLE VARCHAR2(35),
  IMPUTATION_TYPEID VARCHAR2(14),
  DATECREATION DATE NOT NULL,
  DATEMAJ DATE NOT NULL,
  DATESYNCHRO DATE,
CONSTRAINT PK_IMPUTATIONID PRIMARY KEY (IMPUTATIONID));

--  Table IMPUTATION_TYPE
CREATE TABLE IMPUTATION_TYPE (
  IMPUTATION_TYPEID VARCHAR2(14) NOT NULL,
  LIBELLE VARCHAR2(35) );

ALTER TABLE RESERVATION ADD (IMPUTATIONID VARCHAR2(14));

ALTER TABLE ARTICLE ADD (QUANTITE INTEGER);

ALTER TABLE LGPA ADD (
  COMMENTAIRE BLOB,
  CONFIRMER INTEGER);

--------------------------------------------------------
-- 2002_09_26
ALTER TABLE ARTICLE ADD ( GESTION INTEGER);
UPDATE ARTICLE SET GESTION=0;

--------------------------------------------------------
-- 2002_10_09
ALTER TABLE CFGGSALLESPARAM ADD (
  CTRL_PA_HORSHORAIRE INTEGER,
  CTRL_NB_PARTICIPANT INTEGER,
  CTRL_MATERIEL_DISPO INTEGER
);

CREATE TABLE STATUTRESERVATION_ETAT (
  ID                NUMBER,
  TEXTE             VARCHAR2 (50),
  DATECREATION      DATE          NOT NULL,
  DATEMAJ           DATE          NOT NULL,
  DATESYNCHRO       DATE);

CREATE TABLE STATUTRESERVATION_SET (
  ID                NUMBER,
  TEXTE             VARCHAR2 (50),
  DATECREATION      DATE          NOT NULL,
  DATEMAJ           DATE          NOT NULL,
  DATESYNCHRO       DATE);

--------------------------------------------------------
-- 2002_12_16
UPDATE LGPA SET WIZARD=1 WHERE CODEARTICLE IN (SELECT CODEARTICLE FROM ARTICLE WHERE GESTION=1);
-- 2002_12_26
ALTER TABLE INTERLOCUTEUR ADD NOMJEUNEFILLE VARCHAR2(25);

COMMIT;
EXIT;