ALTER TABLE TQ_COMMUNE ADD PRIORITE_INTERDIT NUMBER;

ALTER TABLE INTERLOCUTEUR MODIFY EMAIL VARCHAR2(150);
ALTER TABLE LGPARTICIPANT MODIFY EMAIL VARCHAR2(150);
ALTER TABLE RESIDANTS MODIFY EMAIL VARCHAR2(150);
ALTER TABLE SOCIETE MODIFY EMAIL VARCHAR2(150);

INSERT INTO INTERLOCUTEUR (SOCIETEID,INTERLOCUTEURID,CODECIVILITE,CODEFONCTION,PAYS,CIVILITE,NOMPRENOM,NOM,NOMJEUNEFILLE,PRENOM,
FONCTION,TELEPHONE,EMAIL,GSM,FAX,IMMATRICULATION,INTERDIT,DEBUTINTERDIT,FININTERDIT,NATUREID,NATIONALITEID,DATEMAJ,DATECREATION,SOCIETE,DATENAISSANCE,FINVALIDITEAUTO,PHONKEY)
VALUES
('VPARDEFAUT','VPARDEFAUT',1,0,'FRANCE','Mr','VISITEUR INCONNU','VISITEUR','','INCONNU','**********','01 25 46 85 92','','06 13 25 46 95',
'','','0',SYSDATE-1,SYSDATE+100*365,'VPARDEFAUT','VPARDEFAUT',SYSDATE,SYSDATE,'**********','05/08/1960',SYSDATE+365,1);

UPDATE RESIDANTS SET NOMPRENOM='RESIDANT INCONNU', NOM='RESIDANT', PRENOM='INCONNU' WHERE RESIDANTID='VPARDEFAUT';

CREATE TABLE ZCL25_VISITES
(
  VISITEID VARCHAR2(14),
  STATUTID INTEGER
);

UPDATE VISITES SET TYPEVISITEID='0' WHERE TYPEVISITEID='' OR TYPEVISITEID IS NULL;

ALTER TABLE TQ_COMMUNE ADD PARAM_DIVERS VARCHAR(4000);

ALTER TABLE VISITES ADD DEBLOC NUMBER;

ALTER TABLE VISITES ADD DEBLOC_USER VARCHAR2(50);

ALTER TABLE VISITES ADD DEBLOC_USERID VARCHAR2(14);

ALTER TABLE VISITES ADD DEBLOC_HEURE DATE;

INSERT INTO ETATAPP (ETATID, ETATNOM, VISIBLE, REQUETE, FILTRE, APP, DATECREATION, DATEMAJ) VALUES ('VISITES_DEBLOQUEES', 'VisitesDebloquees', 1, '', '', 'TQ', SYSDATE, SYSDATE);

ALTER TABLE TQ_POSTE ADD MODE_ES_RSDT NUMBER DEFAULT 0;

CREATE TABLE VISITES_RESIDANTS (
  PASSAGERID    VARCHAR2 (14)  NOT NULL,
  RESIDANTID    VARCHAR2 (14),
  NOMPRENOM     VARCHAR2 (35),
  CODEACCES     VARCHAR2 (34),
  ENTREE        DATE,
  SORTIE        DATE,
  CIRCULATION   VARCHAR2 (20),
  OBSERVATION   VARCHAR2 (200),
  TYPEENTREE    NUMBER,
  GUICHET_E     VARCHAR2 (30),
  GUICHET_S     VARCHAR2 (30),
  DATECREATION  DATE          NOT NULL,
  DATEMAJ       DATE          NOT NULL,
  DATESYNCHRO   DATE
  );

INSERT INTO VISITES_RESIDANTS SELECT PASSAGERID,RESIDANTID,NOMPRENOM,CODEACCES,PASSAGE,NULL,CIRCULATION,OBSERVATION,NULL,NULL,NULL,DATECREATION,DATEMAJ,DATESYNCHRO FROM PASSAGER;

UPDATE VISITES_RESIDANTS SET SORTIE=ENTREE;

UPDATE VISITES_RESIDANTS SET TYPEENTREE=1;

UPDATE VISITES_RESIDANTS SET TYPEENTREE=2 WHERE OBSERVATION='VEHICULE';

COMMIT;
EXIT;

