ALTER TABLE INTERLOCUTEUR ADD (PAYS_ADRESSE VARCHAR2(50));
ALTER TABLE INTERLOCUTEUR ADD (PAYS_NAISSANCE VARCHAR2(50));
ALTER TABLE RESIDANTS ADD (PASSWORD1 VARCHAR2(250));
ALTER TABLE RESIDANTS ADD (PASSWORD2 VARCHAR2(250));
ALTER TABLE RESIDANTS ADD (PASSWORD3 VARCHAR2(250));
ALTER TABLE PAYS ADD (ENQUETE1 VARCHAR2 (10));
ALTER TABLE PAYS ADD (STATUT1 VARCHAR2 (10));
ALTER TABLE PAYS ADD (ENQUETE2 VARCHAR2 (10));
ALTER TABLE PAYS ADD (STATUT2 VARCHAR2 (10));
ALTER TABLE PAYS ADD (ENQUETE3 VARCHAR2 (10));
ALTER TABLE PAYS ADD (STATUT3 VARCHAR2 (10));
ALTER TABLE TYPEVISITE ADD (SITEID VARCHAR2(14));
ALTER TABLE TYPEVISITE ADD (SITE VARCHAR2(35));
ALTER TABLE RESIDANTS ADD (DIRECTIONID VARCHAR2(14));
ALTER TABLE RESIDANTS ADD (DIRECTION VARCHAR2(35));
ALTER TABLE VISITES ADD (ECHANGES NUMBER DEFAULT 0);
ALTER TABLE RESIDANTS MODIFY (THEPASSWORD VARCHAR2(250));
ALTER TABLE USERS MODIFY (THEPASSWORD VARCHAR2(250));
ALTER TABLE TQ_COMMUNE ADD (CRYPTAGE VARCHAR2(1));


CREATE TABLE ZCL05_GRP
(
  LIBELLE VARCHAR(50),
  DATECREATION DATE
);

CREATE TABLE ZCL05_BADGE
(
  NUMBADGE  VARCHAR(50),
  CODEBADGE VARCHAR(50),
  DATECREATION DATE
);

CREATE TABLE ZCL05_ASCENSEUR
(
  LIBELLE VARCHAR(50),
  DATECREATION DATE
);



CREATE TABLE TYPEUSER
(
USERID		INT,
LIBELLE		VARCHAR(50),
DATECREATION	DATE NOT NULL,
DATEMAJ		DATE NOT NULL,
DATESYNCHRO	DATE
);


DELETE FROM TYPEUSER;

INSERT INTO TYPEUSER (USERID,LIBELLE,DATECREATION,DATEMAJ) VALUES (-1,'ADM',SYSDATE,SYSDATE);

INSERT INTO TYPEUSER (USERID,LIBELLE,DATECREATION,DATEMAJ) VALUES (-2,'ACCUEIL',SYSDATE,SYSDATE);

INSERT INTO TYPEUSER (USERID,LIBELLE,DATECREATION,DATEMAJ) VALUES (-3,'TECH',SYSDATE,SYSDATE);


CREATE TABLE DIRECTIONS
(
DIRECTIONID	VARCHAR(14) NOT NULL,
SOCIETEID	VARCHAR(14),
LIBELLE		VARCHAR(35),
DATECREATION	DATE NOT NULL,
DATEMAJ		DATE NOT NULL,
DATESYNCHRO	DATE,
CONSTRAINT PK_DIRECTIONID PRIMARY KEY (DIRECTIONID)
);



ALTER TABLE RESIDANTS ADD (DIRECTIONID VARCHAR(14));


ALTER TABLE RESIDANTS ADD (DIRECTION VARCHAR(35));


ALTER TABLE INTERLOCUTEUR MODIFY LIEUNAISSANCE VARCHAR(70);



ALTER TABLE SITE DROP CONSTRAINT fk_site_planid;


ALTER TABLE BATIMENT DROP CONSTRAINT fk_bat_planid;




UPDATE TQ_COMMUNE SET VALIDATION_RESID='0,1';



ALTER TABLE INTERLOCUTEUR ADD (PAYS_ADRESSE VARCHAR(50));


ALTER TABLE INTERLOCUTEUR ADD (PAYS_NAISSANCE VARCHAR(50));


ALTER TABLE RESIDANTS ADD (PASSWORD1 VARCHAR(50));


ALTER TABLE RESIDANTS ADD (PASSWORD2 VARCHAR(50));


ALTER TABLE RESIDANTS ADD (PASSWORD3 VARCHAR(50));


ALTER TABLE PAYS ADD (ENQUETE1 VARCHAR (10));


ALTER TABLE PAYS ADD (STATUT1 VARCHAR (10));


ALTER TABLE PAYS ADD (ENQUETE2 VARCHAR (10));


ALTER TABLE PAYS ADD (STATUT2 VARCHAR (10));


ALTER TABLE PAYS ADD (ENQUETE3 VARCHAR (10));


ALTER TABLE PAYS ADD (STATUT3 VARCHAR (10));


ALTER TABLE VISITES MODIFY FREE8 VARCHAR(250);

ALTER TABLE VISITES MODIFY FREE9 VARCHAR(250);


DROP TABLE DROITS;


CREATE TABLE DROITS (
  RESIDANTID VARCHAR(14) NOT NULL,
  DELEGATIONID VARCHAR(14),
  CREATION VARCHAR(1),
  MODIFICATION VARCHAR(1),
  SUPPRESSION VARCHAR(1),
  APPLI VARCHAR(80),
  DIVERSACCES INT,
  DATECREATION DATE NOT NULL,
  DATEMAJ DATE NOT NULL,
  DATESYNCHRO	 DATE,
PRIMARY KEY (RESIDANTID,DELEGATIONID));



ALTER TABLE RESIDANTS DROP CONSTRAINT fk_resi_planid;


ALTER TABLE RESIDANTS MODIFY THEPASSWORD VARCHAR(250);


ALTER TABLE RESIDANTS MODIFY PASSWORD1 VARCHAR(250);


ALTER TABLE RESIDANTS MODIFY PASSWORD2	VARCHAR(250);


ALTER TABLE RESIDANTS MODIFY PASSWORD3	VARCHAR(250);


ALTER TABLE USERS MODIFY THEPASSWORD	VARCHAR(250);


ALTER TABLE TQ_COMMUNE ADD (CRYPTAGE VARCHAR(1));


ALTER TABLE TQ_COMMUNE ADD (
MODIF_VISITEUR_PREENREG  INT,
MODIF_VISITEUR_ENCOURS  INT,
MODIF_VISITEUR_TERMINE  INT);


ALTER TABLE INTERLOCUTEUR MODIFY NOMPRENOM VARCHAR(70);


ALTER TABLE RESIDANTS MODIFY NOMPRENOM VARCHAR(70);


ALTER TABLE VISITES MODIFY NOMPRENOMVISIT VARCHAR(70);


ALTER TABLE VISITES MODIFY NOMPRENOMRESID VARCHAR(70);


ALTER TABLE HVISITES MODIFY NOMPRENOMVISIT VARCHAR(70);


CREATE TABLE PROFILS_USERS
(
TYPEUSER	VARCHAR(24),
SITE		VARCHAR(35),
GVACCESS	INT
);


ALTER TABLE HVISITES MODIFY NOMPRENOMRESID VARCHAR(70);


CREATE TABLE ZCL08_REPAS (
REPASID		VARCHAR(14),
REPAS		VARCHAR(10),
NUMEROBADGE	VARCHAR(20) NOT NULL,
DATEPASSAGE	VARCHAR(20),
DATEPASSAGE2	VARCHAR(20) NOT NULL,
VISITEID	VARCHAR(14)
);

ALTER TABLE ZCL08_REPAS ADD CONSTRAINT PK_BDG PRIMARY KEY (NUMEROBADGE,DATEPASSAGE2);


DELETE FROM TYPEUSER ;


INSERT INTO TYPEUSER (USERID,LIBELLE,DATECREATION,DATEMAJ) VALUES (-1,'ADM',SYSDATE,SYSDATE);

INSERT INTO TYPEUSER (USERID,LIBELLE,DATECREATION,DATEMAJ) VALUES (-2,'ACCUEIL',SYSDATE,SYSDATE);

INSERT INTO TYPEUSER (USERID,LIBELLE,DATECREATION,DATEMAJ) VALUES (-3,'TECH',SYSDATE,SYSDATE);

INSERT INTO TYPEUSER (USERID,LIBELLE,DATECREATION,DATEMAJ) VALUES (-4,'PARKING',SYSDATE,SYSDATE);


UPDATE USERS SET USERTYPEID='ADM' WHERE USERTYPEID='Administrateur';

CREATE TABLE ROLE_AUTRES (
USERID INT,
SITE INT,
SOC_RES INT,
DIRECTIONS INT,
PAYS INT,
UTILISATEURS INT,
TYPEUSER	INT,
DATECREATION	DATE,
DATEMAJ DATE
);


CREATE TABLE ROLE_PARAMETRAGES (
USERID INT,
PARAMETRAGES_GENERAUX INT,
PERIPHERIQUES INT,
PRESENTATION INT,
OPTIONS INT,
BADGES INT,
CTRL_ACCES INT,
ES_VEHICULE INT,
PARAMETRAGES_CHAMPS INT,
AUTORISATION_ACCES INT,
REGLES INT,
PARAM_ETATS	INT,
DATECREATION	DATE,
DATEMAJ DATE
);


CREATE TABLE ROLE_RESTES (
USERID INT,
EXPORT_TABLES INT,
STAT INT,
ETATS INT,
NETTOYAGES INT,
DATECREATION	DATE,
DATEMAJ DATE
);


UPDATE TQ_POSTE SET DEBUT_CODE ='';
ALTER TABLE TQ_POSTE MODIFY DEBUT_CODE VARCHAR2(20);
ALTER TABLE RESIDANTS ADD (NOMJEUNEFILLE  VARCHAR(35));


ALTER TABLE TQ_POSTE ADD ENVOI_MAIL INTEGER;
ALTER TABLE TQ_POSTE ADD MODIF_VISITEUR	INTEGER;
ALTER TABLE TQ_POSTE ADD CHAMPS_VISITEUR VARCHAR(4000);

ALTER TABLE TQ_COMMUNE ADD ANNUAIRE INTEGER;
ALTER TABLE TQ_COMMUNE ADD ANNUAIRE_URL VARCHAR(250);


ALTER TABLE ROLE_PARAMETRAGES ADD ENVOI_MAIL INTEGER;
ALTER TABLE ROLE_PARAMETRAGES ADD PROFIL_ACCUEIL INTEGER;
ALTER TABLE ROLE_PARAMETRAGES ADD PARAM_ETATS  INTEGER;

--SHORTNAME pour le code activité du PHR
ALTER TABLE RESIDANTS MODIFY SHORTNAME INTEGER;


CREATE TABLE ETATAPP (
   ETATID    	VARCHAR2(50),
   ETATNOM      VARCHAR2(50),
   VISIBLE      INTEGER,
   REQUETE      VARCHAR2(50),
   FILTRE       VARCHAR2(250),
   APP		VARCHAR(20),
   DATECREATION DATE,
   DATEMAJ      DATE
);

INSERT INTO ETATAPP (ETATID,ETATNOM,VISIBLE,APP,DATECREATION,DATEMAJ) VALUES ('ETAT_ETRANGERS','ListeEtranger',1,'TQ',SYSDATE,SYSDATE);
INSERT INTO ETATAPP (ETATID,ETATNOM,VISIBLE,APP,DATECREATION,DATEMAJ) VALUES ('BLACKLISTEVIS','BlackListeVis',1,'TQ',SYSDATE,SYSDATE);
INSERT INTO ETATAPP (ETATID,ETATNOM,VISIBLE,APP,DATECREATION,DATEMAJ) VALUES ('BLACKLISTERES','BlackListeRes',1,'TQ',SYSDATE,SYSDATE);
INSERT INTO ETATAPP (ETATID,ETATNOM,VISIBLE,APP,DATECREATION,DATEMAJ) VALUES ('ETAT_VISITEUR_PAYS','NbVisiteursParPays',1,'TQ',SYSDATE,SYSDATE);
INSERT INTO ETATAPP (ETATID,ETATNOM,VISIBLE,APP,DATECREATION,DATEMAJ) VALUES ('ETAT_VISITE_DETAIL','VisiteDetailVisiteur',1,'TQ',SYSDATE,SYSDATE);
INSERT INTO ETATAPP (ETATID,ETATNOM,VISIBLE,APP,DATECREATION,DATEMAJ) VALUES ('NBBDGIMPRRES','NbBdgImprRes',1,'TQ',SYSDATE,SYSDATE);
INSERT INTO ETATAPP (ETATID,ETATNOM,VISIBLE,APP,DATECREATION,DATEMAJ) VALUES ('LISTE_PHR_PHS','PHR_PHS',1,'TQ',SYSDATE,SYSDATE);
INSERT INTO ETATAPP (ETATID,ETATNOM,VISIBLE,APP,DATECREATION,DATEMAJ) VALUES ('LISTE_ENQUETES','Enquete',1,'TQ',SYSDATE,SYSDATE);
INSERT INTO ETATAPP (ETATID,ETATNOM,VISIBLE,APP,DATECREATION,DATEMAJ) VALUES ('LISTE_PASSAGE_SELF','Repas',1,'TQ',SYSDATE,SYSDATE);
INSERT INTO ETATAPP (ETATID,ETATNOM,VISIBLE,APP,DATECREATION,DATEMAJ) VALUES ('ETAT_ETRANGERS_DETAILS','ListeEtrangerDetails',1,'TQ',SYSDATE,SYSDATE);
INSERT INTO ETATAPP (ETATID,ETATNOM,VISIBLE,APP,DATECREATION,DATEMAJ) VALUES ('STATISTIQUE','JVisite',1,'TQ_NonVisible',SYSDATE,SYSDATE);
INSERT INTO ETATAPP (ETATID,ETATNOM,VISIBLE,APP,DATECREATION,DATEMAJ) VALUES ('STATISTIQUE_OBS','JVisiteObs',1,'TQ_NonVisible',SYSDATE,SYSDATE);
INSERT INTO ETATAPP (ETATID,ETATNOM,VISIBLE,APP,DATECREATION,DATEMAJ) VALUES ('PRE_ENREG','PreEnreg',1,'TQ_NonVisible',SYSDATE,SYSDATE);




ALTER TABLE TQ_POSTE ADD REPSCAN VARCHAR(100);

CREATE TABLE PHOTOS (ID VARCHAR(14),PHOTO BLOB);

DROP TABLE MAIL;

CREATE TABLE MAIL
(
MAILID		VARCHAR(14),
APP 		VARCHAR(10),
SITEID		VARCHAR(14),
SITE		VARCHAR(35),
USERID 		VARCHAR(50),
SMTP 		VARCHAR(50),
FROMADDRESS 	VARCHAR(50),
TOADDRESS 	VARCHAR(1000),
CARBONCOPY 	VARCHAR(1000),
SUJET 		VARCHAR(200),
BODY 		VARCHAR(4000),
STATUT 		INTEGER,
ETAT 		VARCHAR(50),
DATECREATION 	DATE,
DATEMAJ 	DATE
);

ALTER TABLE SITE ADD (USERID VARCHAR(50),SMTP VARCHAR(50),FROMADDRESS VARCHAR(50),TOADDRESS VARCHAR(1000),CARBONCOPY VARCHAR(1000),ACTIF INTEGER,SUPPRESSION	VARCHAR(5),HEURESUPP VARCHAR(10),INTERVAL INTEGER,OEMAILPARAM  VARCHAR(20));


ALTER TABLE ZCL01_BA MODIFY CODIND VARCHAR2(20);
ALTER TABLE ZCL08_REPAS ADD (DATEREELLE DATE);
ALTER TABLE VISITES ADD (PREMIER INT);
ALTER TABLE VISITES ADD (PREENREG INT DEFAULT 0);


ALTER TABLE PARAMETRES ADD (SORTIFINVI INT);
UPDATE PARAMETRES SET SORTIFINVI=0;
UPDATE RESIDANTS SET BOITEPOSTALE='0';
ALTER TABLE ROLE_PARAMETRAGES ADD (CHAMPS_VISITEUR VARCHAR(4000));
ALTER TABLE ROLE_AUTRES ADD (PROFILUSER INT,MODIFAFF  INT);
ALTER TABLE ROLE_PARAMETRAGES ADD (PARAM_ETATS INT);
ALTER TABLE ROLE_PARAMETRAGES ADD (PROFIL_ACCUEIL INT);
ALTER TABLE ROLE_PARAMETRAGES ADD (ENVOI_MAIL INT);
INSERT INTO ROLE_AUTRES (USERID,SITE,SOC_RES,DIRECTIONS,PAYS,UTILISATEURS,TYPEUSER,PROFILUSER,MODIFAFF,DATECREATION,DATEMAJ) VALUES (-1,1,1,1,1,1,1,1,1,SYSDATE,SYSDATE);

;premier pour dire si c la premier visite, et dire dans le champ condidatmailing 1 pour ne pas refaire le test sur les autres visites
;preenreg pour dire si c une visite qui avait un preenreg ou pas

ALTER TABLE VISITES ADD (PREMIER INT,PREENREG INT DEFAULT 0);
ALTER TABLE VISITES_LOG ADD (PREMIER INT,PREENREG INT DEFAULT 0);
ALTER TABLE RESIDANTS ADD (NOMJEUNEFILLE  VARCHAR(35));
ALTER TABLE RESIDANTS MODIFY ISUSER VARCHAR(10);

UPDATE INTERLOCUTEUR SET CANDIDATMAILING=0;
UPDATE INTERLOCUTEUR SET CANDIDATMAILING=1 WHERE INTERLOCUTEURID IN (SELECT DISTINCT INTERLOCUTEURID FROM VISITES WHERE STATUTID<>2);

ALTER TABLE ZCL08_REPAS ADD (DATEREELLE DATE);
ALTER TABLE ZCL01_BA MODIFY CODIND VARCHAR2(14);
ALTER TABLE VISITES ADD (ZONE VARCHAR(1));
ALTER TABLE VISITES_LOG ADD (ZONE VARCHAR(1));
UPDATE VISITES SET ZONE='I';
ALTER TABLE VISITES ADD (DESCENTE INT);
ALTER TABLE VISITES_LOG ADD (DESCENTE INT);
UPDATE VISITES SET DESCENTE=0;
ALTER TABLE INTERLOCUTEUR ADD (ENQUETE_VE INT DEFAULT 0);
ALTER TABLE INTERLOCUTEUR ADD (ENQUETE_LPE INT DEFAULT 0);

ALTER TABLE INTERLOCUTEUR_PARTENAIRE ADD (ENQUETE_VE INT DEFAULT 0);
ALTER TABLE INTERLOCUTEUR_PARTENAIRE ADD (ENQUETE_LPE INT DEFAULT 0);

ALTER TABLE INTERLOCUTEUR_PARTENAIRE MODIFY LIEUNAISSANCE VARCHAR(70);
ALTER TABLE INTERLOCUTEUR_PARTENAIRE ADD (PAYS_ADRESSE VARCHAR(50));
ALTER TABLE INTERLOCUTEUR_PARTENAIRE ADD (PAYS_NAISSANCE VARCHAR(50));
ALTER TABLE INTERLOCUTEUR_PARTENAIRE MODIFY NOMPRENOM VARCHAR(70);
;A vérifier
UPDATE INTERLOCUTEUR SET ENQUETE_VE=1,ENQUETE_LPE=1 WHERE INTERLOCTEURID IN (SELECT DISTINCT INTERLOCUTEURID FROM VISITES WHERE COTE=1);


ALTER TABLE TQ_COMMUNE ADD (UTILISATION_OBS_VISITEUR INT,MODIF_OBS_VISITEUR INT);
ALTER TABLE INTERLOCUTEUR ADD (OBS VARCHAR(200));

ALTER TABLE USERS ADD SITEID VARCHAR(14);
UPDATE USERS SET SITEID=(SELECT SITEID FROM SITE WHERE LIBELLE=USERS.SITE);
UPDATE USERS SET SITEID='VPARDEFAUT' WHERE SITEID IS NULL;


ALTER TABLE PROFILS_USERS ADD SITEID VARCHAR(14);
UPDATE PROFILS_USERS SET SITEID=(SELECT SITEID FROM SITE WHERE LIBELLE=USERS.SITE);
UPDATE PROFILS_USERS SET SITEID='VPARDEFAUT' WHERE SITEID IS NULL;

ALTER TABLE PARAMETRES ADD CHIMGVT VARCHAR2 (4000);
ALTER TABLE PARAMETRES ADD CHIMGRE VARCHAR2 (4000);
ALTER TABLE PARAMETRES ADD CHIMGPL VARCHAR2 (4000);

ALTER TABLE TQ_POSTE MODIFY FIN_CODE VARCHAR2 (20);


-- Création d'une table temporaire
CREATE GLOBAL TEMPORARY TABLE TEMPO_TQ
(	FREE1	VARCHAR2(100),
	FREE2	VARCHAR2(100),
	FREE3	VARCHAR2(100),
	FREE4	VARCHAR2(100),
	FREE5	VARCHAR2(100),
	FREE6	VARCHAR2(100),
	FREE7 	VARCHAR2(100),
	FREE8 	VARCHAR2(100),
	FREE9	VARCHAR2(100),
	FREE10	VARCHAR2(100),
	FREE11	VARCHAR2(100),
	FREE12	VARCHAR2(100),
	FREE13	VARCHAR2(100),
	FREE14	VARCHAR2(100),
	FREE15	VARCHAR2(100),
	FREEINT1	INTEGER,
	FREEINT2	INTEGER,
	FREEDATE1	DATE,
	FREEDATE2	DATE,
	FREEDATE3	DATE,
	FREEDATE4	DATE
) ON COMMIT PRESERVE ROWS ;

CREATE GLOBAL TEMPORARY TABLE TEMPO_TQ2
(	FREE1	VARCHAR2(100),
	FREE2	VARCHAR2(100),
	FREE3	VARCHAR2(100),
	FREE4	VARCHAR2(100),
	FREE5	VARCHAR2(100),
	FREE6	VARCHAR2(100),
	FREE7 	VARCHAR2(100),
	FREE8 	VARCHAR2(100),
	FREE9	VARCHAR2(100),
	FREE10	VARCHAR2(100),
	FREE11	VARCHAR2(100),
	FREE12	VARCHAR2(100),
	FREE13	VARCHAR2(100),
	FREE14	VARCHAR2(100),
	FREE15	VARCHAR2(100),
	FREEINT1	INTEGER,
	FREEINT2	INTEGER,
	FREEDATE1	DATE,
	FREEDATE2	DATE,
	FREEDATE3	DATE,
	FREEDATE4	DATE
) ON COMMIT PRESERVE ROWS ;


ALTER TABLE TQ_POSTE ADD (CHEMIN_EXPORT VARCHAR2(300));


CREATE TABLE ZCL09_ID (ID INTEGER);

CREATE TABLE ZCL09_PERSONNEID_BDG (PERSONNEID VARCHAR(14),NUMEROBADGE VARCHAR(50));


COMMIT;
EXIT;

