ALTER TABLE RESERVATION ADD EMETTEUR VARCHAR2(200 CHAR);
COMMIT;

UPDATE RESERVATION SET EMETTEUR=(SELECT FULLNAME FROM USERS WHERE USERID=RESERVATION.USERID);
COMMIT;

UPDATE GRPUSER SET RESA=RESA||'011';
COMMIT;
EXIT;