ALTER TABLE APPEL ADD RESIDANTID VARCHAR2(14);
ALTER TABLE APPEL ADD INTERLOCUTEURID VARCHAR2(14);
ALTER TABLE APPEL ADD SOCIETE VARCHAR2(35);
ALTER TABLE APPEL ADD OBJET VARCHAR2(4000);
ALTER TABLE APPEL ADD TELEPHONE VARCHAR2(30);
ALTER TABLE APPEL ADD DATECREATION DATE;
COMMIT;

UPDATE APPEL SET DATECREATION=QUAND WHERE DATECREATION IS NULL;
COMMIT;