ALTER TABLE DROITS ALTER COLUMN DATEMAJ DATE NULL;
COMMIT;
ALTER TABLE DROITS ALTER COLUMN DATECREATION DATE NULL;
COMMIT;

CREATE TABLE GRPUSER_DROITSTELEM(
	GRPUSERID varchar2(14) NOT NULL,
	ID_DROITSTELEM varchar2(14) NOT NULL,
 CONSTRAINT PK_GRPUSER_ID_DROITSTELEM PRIMARY KEY
(
	GRPUSERID,
	ID_DROITSTELEM
));

COMMIT;

 ALTER TABLE RESIDANTS ADD CCASSISTANTE INT DEFAULT(0);

COMMIT;

 UPDATE RESIDANTS SET CCASSISTANTE='0';

COMMIT;

ALTER TABLE RESIDANTS ALTER COLUMN MATRICULE VARCHAR2(300);

COMMIT;
