
CREATE TABLE ZCL17_PROFIL (
  ZCL17_PROFILID  VARCHAR2 (14)  NOT NULL,
  NUMERO	  VARCHAR2 (35),
  LIBELLE         VARCHAR2 (35),
  SITEID          VARCHAR2 (14),
  DATECREATION    DATE,
  DATEMAJ         DATE,
  DATESYNCHRO     DATE
);
COMMIT;

CREATE TABLE ZCL17_VISITE (
  ZCL17_VISITEID VARCHAR2 (14) NOT NULL,
  ACT            VARCHAR2 (14),
  NUMERO		 VARCHAR2 (20),
  NOMV			 VARCHAR2 (35),
  PRENOMV		 VARCHAR2 (35),
  SOCIETE		 VARCHAR2 (35),
  NOMR			 VARCHAR2 (35),
  PRENOMR		 VARCHAR2 (35),
  GUICHET		 VARCHAR2 (40),
  PROFIL1		 VARCHAR2 (35),
  PROFIL2		 VARCHAR2 (35),
  PROFIL3		 VARCHAR2 (35),
  PROFIL4		 VARCHAR2 (35),
  DEBUT			 VARCHAR2 (35),
  FIN			 VARCHAR2 (35),
  STATUT		 INTEGER,
  SITEID		 VARCHAR2 (14),
  DATECREATION   DATE,
  DATEMAJ        DATE,
  DATESYNCHRO    DATE
);
COMMIT;

CREATE TABLE ZCL09_PROFIL (
  ZCL09_PROFILID  VARCHAR2 (14)  NOT NULL,
  NUMERO	  VARCHAR2 (35),
  LIBELLE         VARCHAR2 (35),
  SITEID          VARCHAR2 (14),
  DATECREATION    DATE,
  DATEMAJ         DATE,
  DATESYNCHRO     DATE
);
COMMIT;

CREATE TABLE ZCL09_VISITE (
  ZCL09_VISITEID  VARCHAR2 (14) NOT NULL,
  LIGNE		VARCHAR2 (300),
  STATUT		INTEGER,
  SITEID		 	VARCHAR2 (14),
  DATECREATION   		DATE,
  DATEMAJ        		DATE,
  DATESYNCHRO    	DATE
);
COMMIT;

EXIT;