ALTER TABLE OMNI_PARAM ADD MC_FILTRAGE INT;
ALTER TABLE OMNI_PARAM ADD PASS_SENSIBLE INT;

ALTER TABLE OMNI_PARAM ADD STATION_POSTE_ONLY INT;
ALTER TABLE OMNI_PARAM ADD STATION_ALERT_LOCK INT;

ALTER TABLE OMNI_PARAM ADD ALERT_NOLOCK INT;


INSERT INTO POSTE (POSTEID,LIBELLE,REP_LOCAL,DATECREATION,DATEMAJ) VALUES (-1,'SYSTEME','SYSTEME',SYSDATE,SYSDATE);

CREATE TABLE OJVACATION (
  JVACATIONID INT NOT NULL,
  OJOURNALID INT NOT NULL
);

ALTER TABLE RPT_SEM5 MODIFY BATIMENT VARCHAR2(35);
ALTER TABLE RPT_SEM5 MODIFY RUE VARCHAR2(60);
ALTER TABLE RPT_SEM5 MODIFY SECTEUR VARCHAR2(40);

CREATE TABLE OFICHIER_POSTE (
  OFICHIERID INT NOT NULL,
  POSTEID INT NOT NULL
);

UPDATE OFICHIER SET TYPEFILE=3;

ALTER TABLE RPT_SEM5 ADD SITEID VARCHAR2(14);
UPDATE RPT_SEM5 SET SITEID='VPARDEFAUT';

ALTER TABLE PERSONNEL MODIFY CODEFONCTION INT;

COMMIT;
EXIT;