--  Table LICENCE
CREATE TABLE LICENCE (
	ID_LICENCE NUMBER(*, 0) NOT NULL,
	CLE VARCHAR2(30 CHAR) NOT NULL,
	DATECREATION DATE NOT NULL,
	CONSTRAINT PK_ID_LICENCE PRIMARY KEY (ID_LICENCE)
);

--  Table LICENCE1
CREATE TABLE LICENCE1 (
	ID_LICENCE1 NUMBER(*, 0) NOT NULL,
	NOM_POSTE VARCHAR2(24 CHAR) NOT NULL,
	LOGIN VARCHAR2(50 CHAR) NOT NULL,
	APPLICATION VARCHAR2(20 CHAR) NOT NULL,
	DATECREATION DATE NOT NULL,
	CONSTRAINT PK_ID_LICENCE1 PRIMARY KEY (ID_LICENCE1)
);

CREATE SEQUENCE SEQ_LICENCE1
	START WITH 1
	INCREMENT BY 1
	NOMAXVALUE;

--  Table LICENCE2
CREATE TABLE LICENCE2 (
	ID_LICENCE2 NUMBER(*, 0) NOT NULL,
	LOGIN VARCHAR2(50 CHAR) NOT NULL,
	APPLICATION VARCHAR2(20 CHAR) NOT NULL,
	DATECREATION DATE NOT NULL,
	CONSTRAINT PK_ID_LICENCE2 PRIMARY KEY (ID_LICENCE2)
);

CREATE SEQUENCE SEQ_LICENCE2
	START WITH 1
	INCREMENT BY 1
	NOMAXVALUE;

--  Table LICENCE3
CREATE TABLE LICENCE3 (
	ID_LICENCE3 NUMBER(*, 0) NOT NULL,
	LOGIN VARCHAR2(50 CHAR) NOT NULL,
	APPLICATION VARCHAR2(20 CHAR) NOT NULL,
	DATECREATION DATE NOT NULL,
	CONSTRAINT PK_ID_LICENCE3 PRIMARY KEY (ID_LICENCE3)
);

CREATE SEQUENCE SEQ_LICENCE3
	START WITH 1
	INCREMENT BY 1
	NOMAXVALUE;

COMMIT;
EXIT;