ALTER TABLE POSTE ADD OPTIONADMIN_AUTOSTART INTEGER;
ALTER TABLE POSTE ADD OPTIONADMIN_LOCKDESKTOP INTEGER;
ALTER TABLE POSTE ADD OPTIONADMIN_SHUTDOWN INTEGER;
COMMIT;

ALTER TABLE PERSONNEL ADD EMPPK_LEN INTEGER;
COMMIT;
EXIT;