ALTER TABLE BADGES_ELEMENTS ADD SUBSTR_DEBUT INT;
ALTER TABLE BADGES_ELEMENTS ADD SUBSTR_LONG INT;
COMMIT;

ALTER TABLE BADGES_ELEMENTS_TMP ADD SUBSTR_DEBUT INT;
ALTER TABLE BADGES_ELEMENTS_TMP ADD SUBSTR_LONG INT;
COMMIT;
EXIT;
