ALTER TABLE VISITES ADD CODELGRESERVATION VARCHAR2(14);
COMMIT;

ALTER TABLE LGRESERVATION ADD PORTE_CODE VARCHAR2(50);
COMMIT;

ALTER TABLE SALLE ADD PORTE_CLE VARCHAR2(50);
COMMIT;

ALTER TABLE SALLE ADD PORTE_OPTION VARCHAR2(300);
COMMIT;

ALTER TABLE BAGDES_IMAGES RENAME TO BADGES_IMAGES;
COMMIT;
ALTER TABLE BADGES_IMAGES RENAME COLUMN BAGDES_IMAGEID TO BADGES_IMAGEID;
ALTER TABLE BADGES_ELEMENTS RENAME COLUMN BAGDES_IMAGEID TO BADGES_IMAGEID;
ALTER TABLE BADGES_ELEMENTS_TMP RENAME COLUMN BAGDES_IMAGEID TO BADGES_IMAGEID;
COMMIT;
EXIT;