CREATE TABLE STATUTCOURSE (
	ID_STATUTCOURSE INTEGER PRIMARY KEY,
	LIBELLE VARCHAR2(35),
	COLOR INTEGER,
	DATECREATION DATE NOT NULL,
	DATEMAJ DATE NOT NULL,
	DATESYNCHRO DATE
);

CREATE TABLE TYPEVEHICULE (
	ID_TYPEVEHICULE INTEGER PRIMARY KEY,
	LIBELLE VARCHAR2(35),
	DATECREATION DATE NOT NULL,
	DATEMAJ DATE NOT NULL,
	DATESYNCHRO DATE
);

CREATE TABLE COURSE (
	ID_COURSE INTEGER PRIMARY KEY,
	ID_STATUTCOURSE VARCHAR2(14),
	SITEID VARCHAR2(14),
	DATEHEUREDEMANDE DATE,
	LIEUDEPART VARCHAR2(40),
	DATEHEUREDEPART DATE,
	ID_TYPEVEHICULE INTEGER,
	OBJET VARCHAR2(200),
	MOYENPAIEMENT VARCHAR2(50),
	IMPUTATIONID VARCHAR2(14),
	CODECLIENT VARCHAR2(10),
	NUMCOURSE VARCHAR2(35),
	REFERENCESTAXI VARCHAR2(200),
	DELAI INT,
	ADRESSEID VARCHAR2(14),
	DATEHEUREFIN DATE,
	DATECREATION DATE NOT NULL,
	DATEMAJ DATE NOT NULL,
	DATESYNCHRO DATE
);

CREATE TABLE EVENEMENTCOURSE (
	ID_EVENEMENTCOURSE INTEGER	PRIMARY KEY,
	ID_COURSE INTEGER,
	LIBELLE VARCHAR2(200),
	DATEHEURE DATE,
	USERID VARCHAR2(14),
	DATECREATION DATE NOT NULL,
	DATEMAJ DATE NOT NULL,
	DATESYNCHRO DATE
);

CREATE TABLE PASSAGERTAXI (
	ID_PASSAGERTAXI INTEGER PRIMARY KEY,
	ID_COURSE INTEGER,
	RESIDANTID VARCHAR2(14),
	INTERLOCUTEURID VARCHAR2(14),
	CONTACT VARCHAR2(200),
	HANDICAP VARCHAR2(200),
	ANIMAL VARCHAR2(200),
	ORDRE INTEGER,
	DATECREATION DATE NOT NULL,
	DATEMAJ DATE NOT NULL,
	DATESYNCHRO DATE
);

CREATE TABLE DROITSTAXI (
	ID_DROITSTAXI INT PRIMARY KEY,
	LIBELLE VARCHAR2(35),
	DROITS INTEGER,
	DATECREATION DATE NOT NULL,
	DATEMAJ DATE NOT NULL,
	DATESYNCHRO DATE
);

INSERT INTO DROITSTAXI (ID_DROITSTAXI, LIBELLE, DROITS, DATECREATION, DATEMAJ) VALUES (1, 'ADMINISTRATION', 63, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO DROITSTAXI (ID_DROITSTAXI, LIBELLE, DROITS, DATECREATION, DATEMAJ) VALUES (9, 'ACCUEIL', 28, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

INSERT INTO TYPEADRESSE (TYPEADRESSEID, TYPEADRESSE, DATECREATION, DATEMAJ) VALUES (-1, 'TAXIS', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
--INSERT INTO ADRESSE (ADRESSEID, TYPEADRESSEID, SOCIETE, TELEPHONE, DATECREATION, DATEMAJ) VALUES ('G7', -1, 'TAXIS G7', '01 47 39 47 39', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
ALTER TABLE USERS ADD ID_DROITSTAXI INT;

ALTER TABLE TABLEREFERENCE ADD TEXTE_FR VARCHAR2(100);
ALTER TABLE TABLEREFERENCE ADD TEXTE_EN VARCHAR2(100);

DELETE FROM STATUTCOURSE;
INSERT INTO STATUTCOURSE(ID_STATUTCOURSE, LIBELLE, COLOR, DATECREATION, DATEMAJ) VALUES (-1, 'NOUVEAU', 65535, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO STATUTCOURSE(ID_STATUTCOURSE, LIBELLE, COLOR, DATECREATION, DATEMAJ) VALUES (-2, 'CONFIRME', 42495, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO STATUTCOURSE(ID_STATUTCOURSE, LIBELLE, COLOR, DATECREATION, DATEMAJ) VALUES (-3, 'TRAITE', 32768, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO STATUTCOURSE(ID_STATUTCOURSE, LIBELLE, COLOR, DATECREATION, DATEMAJ) VALUES (-4, 'ANNULE', 255, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

UPDATE COURSE SET ID_STATUTCOURSE=-1 WHERE ID_STATUTCOURSE=0;
UPDATE COURSE SET ID_STATUTCOURSE=-2 WHERE ID_STATUTCOURSE=1;
UPDATE COURSE SET ID_STATUTCOURSE=-3 WHERE ID_STATUTCOURSE=2;
UPDATE COURSE SET ID_STATUTCOURSE=-4 WHERE ID_STATUTCOURSE=3;

DELETE FROM TYPEVEHICULE;
INSERT INTO TYPEVEHICULE(ID_TYPEVEHICULE, LIBELLE, DATECREATION, DATEMAJ) VALUES (-1, 'BERLINE/BREAK', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO TYPEVEHICULE(ID_TYPEVEHICULE, LIBELLE, DATECREATION, DATEMAJ) VALUES (-2, 'MONOSPACE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

UPDATE COURSE SET ID_TYPEVEHICULE=-1 WHERE ID_TYPEVEHICULE=0;
UPDATE COURSE SET ID_TYPEVEHICULE=-2 WHERE ID_TYPEVEHICULE=1;

UPDATE USERS SET ID_DROITSTAXI = '1' WHERE USERTYPEID = 'ADM';
UPDATE USERS SET ID_DROITSTAXI = '9' WHERE USERID = 'VPARDEFAUT';

COMMIT;
EXIT;