ALTER TABLE INTERLOCUTEUR ADD NATIONALITE_ORIGINE VARCHAR2(50);
COMMIT;

CREATE TABLE TYPEDOCUMENT (
	TYPEDOCUMENTID NUMBER PRIMARY KEY,
	LIBELLE VARCHAR2(35),
	PORTEEID NUMBER,
	OBLIGATOIRE NUMBER,
	MODIFIABLE NUMBER,
    VALIDITEPARDEFAUT NUMBER,
	CREATCTRL NUMBER,
	DATECREATION DATE,
	DATEMAJ DATE,
	DATESYNCHRO DATE
);
COMMIT;

CREATE TABLE TYPEVISDOC (
  TYPEDOCUMENTID  NUMBER,
  TYPEVISITEID    NUMBER
);
COMMIT;

CREATE TABLE REGLES (
	REGLEID NUMBER PRIMARY KEY,
	LIBELLE VARCHAR2(50),
	RANGREGLE NUMBER,
	TYPEVISITE NUMBER,
	TYPEACTION NUMBER,
	ACTIONBLOQUANTE NUMBER,
	TYPEREGLE NUMBER,
	FREE1 VARCHAR2(35),
	FREE2 NUMBER,
	FREE3 VARCHAR2(35),
	FREE4 NUMBER,
	MESSAGE VARCHAR2(100),
	FREE8 VARCHAR2(100),
	SITEID VARCHAR2(14),
	DATECREATION DATE,
	DATEMAJ DATE,
	DATESYNCHRO DATE
);

ALTER TABLE TABLEREFERENCE MODIFY TEXTE VARCHAR2(100 CHAR);
ALTER TABLE TABLEREFERENCE MODIFY TEXTE_FR VARCHAR2(100 CHAR);
ALTER TABLE TABLEREFERENCE MODIFY TEXTE_EN VARCHAR2(100 CHAR);
COMMIT;

EXIT;