ALTER TABLE TYPEDOCUMENT ADD IN_PREENREG NUMBER;
COMMIT;

UPDATE TYPEDOCUMENT SET IN_PREENREG=1 WHERE TYPEDOCUMENTID=-2;
UPDATE TYPEDOCUMENT SET IN_PREENREG=2 WHERE TYPEDOCUMENTID<>-2;
COMMIT;


ALTER TABLE XANNEXE ADD REFID VARCHAR2(14);
COMMIT;

UPDATE XANNEXE SET REFID=XANNEXEID  WHERE XANNEXE_TYPEID=-1 AND ORIGINE='SOCIETE';
COMMIT;
UPDATE XANNEXE SET REFID=XANNEXEID  WHERE XANNEXE_TYPEID=-1 AND ORIGINE='INTERLOCUTEUR';
COMMIT;

DELETE FROM TABLEREFERENCE WHERE ID=127;
COMMIT;



DELETE FROM XANNEXE WHERE XANNEXE_TYPEID=-1 AND INFORMATION_TYPEID=-1;
COMMIT;
DELETE FROM TYPEVISDOC WHERE TYPEDOCUMENTID=-1;
COMMIT;
DELETE FROM TYPEDOCUMENT WHERE TYPEDOCUMENTID=-1;
COMMIT;

INSERT INTO TYPEVISITE ( TYPEVISITEID, TYPEVISITE, DATECREATION, DATEMAJ) VALUES (-1, 'Résidant',SYSDATE,SYSDATE);
COMMIT;

ALTER TABLE BATIMENT  MODIFY LIBELLE VARCHAR2(60);
COMMIT;

ALTER TABLE RESIDANTS MODIFY BATIMENT VARCHAR2(60);
COMMIT;

ALTER TABLE RESIDANTS MODIFY PHONKEY VARCHAR2(35) DEFAULT '0';
COMMIT;

INSERT INTO EVENEMENT (EVENEMENTID,LIBELLE,RAPPORTID,CONSIGNEID,ISRAPPORT,DATEMAJ,DATECREATION,DATESYNCHRO) VALUES (-19,'CLE EN RETARD',0,0,0,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
COMMIT;


--  Table LICENCE2_LOG
CREATE TABLE LICENCE2_LOG (
	ID_LICENCE2_LOG NUMBER(*, 0) NOT NULL,
	LOGIN VARCHAR2(50 CHAR) NOT NULL,
	APPLICATION VARCHAR2(20 CHAR) NOT NULL,
	ACTION VARCHAR2(50 CHAR) NOT NULL,
	DATECREATION DATE NOT NULL,
	CONSTRAINT PK_ID_LICENCE2_LOG PRIMARY KEY (ID_LICENCE2_LOG)
);

CREATE SEQUENCE SEQ_LICENCE2_LOG
	START WITH 1
	INCREMENT BY 1
	NOMAXVALUE;

--  Table LICENCE3_LOG
CREATE TABLE LICENCE3_LOG (
	ID_LICENCE3_LOG NUMBER(*, 0) NOT NULL,
	LOGIN VARCHAR2(50 CHAR) NOT NULL,
	APPLICATION VARCHAR2(20 CHAR) NOT NULL,
	ACTION VARCHAR2(50 CHAR) NOT NULL,
	DATECREATION DATE NOT NULL,
	CONSTRAINT PK_ID_LICENCE3_LOG PRIMARY KEY (ID_LICENCE3_LOG)
);

CREATE SEQUENCE SEQ_LICENCE3_LOG
	START WITH 1
	INCREMENT BY 1
	NOMAXVALUE;

--  Table CONNECTION_LOG
CREATE TABLE CONNECTION_LOG (
	ID_CONNECTION_LOG NUMBER(*, 0) NOT NULL,
	LOGIN VARCHAR2(50 CHAR) NOT NULL,
	APPLICATION VARCHAR2(100 CHAR) NOT NULL,
	ACTION VARCHAR2(500 CHAR) NOT NULL,
	DATECREATION DATE NOT NULL,
	CONSTRAINT PK_ID_CONNECTION_LOG PRIMARY KEY (ID_CONNECTION_LOG)
);

CREATE SEQUENCE SEQ_CONNECTION_LOG
	START WITH 1
	INCREMENT BY 1
	NOMAXVALUE;

COMMIT;

ALTER TABLE INDCLE ADD OFICHIERID INT;
COMMIT;

ALTER TABLE BADGES ADD TYPEVISITEID INT;
COMMIT;
EXIT;