CREATE TABLE OCONSIGNE_ODROIT (
  OCONSIGNEID INT NOT NULL,
  ODROITID INT NOT NULL
);
COMMIT;

CREATE TABLE OCONSIGNE_POSTE (
  OCONSIGNEID INT NOT NULL,
  POSTEID INT NOT NULL
);
COMMIT;

ALTER TABLE VISITES ADD PROFIL_CTRL_ID VARCHAR2(500);
COMMIT;

--DROP TABLE ETATS;

CREATE TABLE ETATS
(
ETATID		INT	PRIMARY KEY,
LIBELLE		VARCHAR2(100 CHAR),
REQUETE_MSSQL		VARCHAR2(4000 CHAR),
REQUETE_ORACLE		VARCHAR2(4000 CHAR),
MODIFICATION	VARCHAR2(1000 CHAR),
MODIFICATION_OPERATEUR	VARCHAR2(1000 CHAR),
MODIFICATION_VALEUR	VARCHAR2(1000 CHAR),
DATECREATION	DATE NOT NULL,
DATEMAJ			DATE NOT NULL
);
COMMIT;
ALTER TABLE VISITES MODIFY PIECE VARCHAR2(35);
COMMIT;

ALTER TABLE VISITES ADD ALERTE VARCHAR2(4000);
ALTER TABLE VISITES ADD LAST_ACTION VARCHAR2(50);
ALTER TABLE VISITES ADD RES_OS VARCHAR2(50);
ALTER TABLE VISITES ADD RES_FINAL VARCHAR2(50);
ALTER TABLE VISITES ADD RES_MOTEUR1 VARCHAR2(50);
ALTER TABLE VISITES ADD RES_MOTEUR2 VARCHAR2(50);
ALTER TABLE VISITES ADD INFO VARCHAR2(50);
COMMIT;


UPDATE VISITES SET LAST_ACTION=FREE6;
COMMIT;
UPDATE VISITES SET ALERTE=FREE9;
COMMIT;
UPDATE VISITES SET RES_FINAL=STATUTVISITE;
COMMIT;
EXIT;