CREATE SEQUENCE SEQ_TACHE_LOG;
COMMIT;
ALTER TABLE SOCIETE MODIFY SIRET VARCHAR2(40);
COMMIT;

ALTER TABLE GROUPEDEST ADD SITEID VARCHAR2(14);
COMMIT;
UPDATE GROUPEDEST SET SITEID='VPARDEFAUT' WHERE SITEID IS NULL;
COMMIT;

ALTER TABLE TACHE MODIFY FREE01 VARCHAR2(200);
COMMIT;

CREATE TABLE FORMULAIRE_OFICHIER (
  FORMULAIREID INT,
  OFICHIERID INT
);
COMMIT;

CREATE TABLE MAIL_OFICHIER (
  MAILID VARCHAR2(14),
  OFICHIERID INT
);
COMMIT;

ALTER TABLE TYPEVISITE ADD TRAVAIL INT DEFAULT 0;
COMMIT;
UPDATE TYPEVISITE SET TRAVAIL=0;
COMMIT;

ALTER TABLE OFICHIER MODIFY CONTENTTYPE VARCHAR2(100);
COMMIT;
EXIT;
