ALTER TABLE COLISEMIS ADD TRACKING_CRM VARCHAR2(500);
ALTER TABLE COLISEMIS ADD TRACKING_TRANSPORTEUR VARCHAR2(500);
COMMIT;

ALTER TABLE COLISRECU ADD TRACKING_CRM VARCHAR2(500);
ALTER TABLE COLISRECU ADD TRACKING_TRANSPORTEUR VARCHAR2(500);
COMMIT;

ALTER TABLE TYPEVISITE ADD TYPESORTIE INT DEFAULT(0);
COMMIT;
UPDATE TYPEVISITE SET TYPESORTIE=0;
COMMIT;
EXIT;
