ALTER TABLE REGLES ADD STATUT INT DEFAULT(1);
COMMIT;
ALTER TABLE REGLES ADD MESSAGEACC VARCHAR2(100);
COMMIT;
UPDATE REGLES SET STATUT=1 WHERE STATUT IS NULL;
COMMIT;
ALTER TABLE VISITE_REGLE ADD MES_ACC VARCHAR2(100);
COMMIT;
ALTER TABLE VISITES MODIFY FREE2 VARCHAR2(250);
COMMIT;
EXIT;

