INSERT INTO EVENEMENT (EVENEMENTID,LIBELLE,RAPPORTID,CONSIGNEID,ISRAPPORT,DATEMAJ,DATECREATION,GRPEVENEMENTID,DATESYNCHRO) VALUES (-20,'CHECKLIST',0,0,0,SYSDATE,SYSDATE,-1,SYSDATE);
COMMIT;
CREATE TABLE CHECKLIST (
   CHECKLISTID INTEGER PRIMARY KEY,
   LIBELLE  VARCHAR2(200),
   SITEID VARCHAR2(14),
   NUMERO INT NOT NULL,
   DATECREATION DATE,
   DATEMAJ    DATE
);
COMMIT;

CREATE TABLE OCHECKLIST (
   OCHECKLISTID INTEGER PRIMARY KEY,
   LIBELLE VARCHAR2(200),
   NUMERO INTEGER,
   PERSONNELID INTEGER,
   UNOMPRENOM VARCHAR2(300),
   ETAT VARCHAR2(1000),
   DETAIL VARCHAR2(4000),
   OBSERVATION VARCHAR2(4000),
   CHKITEM VARCHAR2(4000),
   SITEID VARCHAR2(14),
   CHECKDATE DATE,
   DATECREATION DATE,
   DATEMAJ      DATE
);
COMMIT;
CREATE TABLE CHK_CHECKLIST (
   CHKID INTEGER PRIMARY KEY,
   CHECKLISTID INTEGER,
   NORDER INTEGER
);
COMMIT;

CREATE TABLE CHK (
   CHKID INTEGER PRIMARY KEY,
   LIBELLE VARCHAR2(400),
   DATECREATION DATE,
   DATEMAJ      DATE
);
COMMIT;

CREATE SEQUENCE SEQ_CHECKLIST;
CREATE SEQUENCE SEQ_OCHECKLIST;
COMMIT;